# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

from sklearn.metrics import roc_auc_score
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import StackingClassifier
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split, cross_val_predict

from feature_engine.encoding import RareLabelEncoder
from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

In [3]:
def dump_pickle(file_obj, file_path):
    with open(file_path, 'bw') as file:
        pickle.dump(file_obj, file)


def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)


def voting_cross_val_predict(probas: list[np.ndarray], weights: np.ndarray[float]) -> np.ndarray[float]:
    weights /= weights.sum()
    return np.sum([proba * weight for proba, weight in zip(probas, weights)], axis=0)

# Loading Dataset

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_stacking.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking.parquet')

In [5]:
X_train.head()

   lgbm_proba  cat_proba  xgb_proba  hist_proba  lg_proba  knn_proba
0    0.802607   0.891870   0.895659    0.883947  0.808497   0.887454
1    0.649405   0.831360   0.829854    0.779541  0.689888   0.519966
2    0.505904   0.851809   0.751522    0.758911  0.558520   0.209855
3    0.001713   0.005910   0.007057    0.007298  0.002275   0.000000
4    0.392205   0.565506   0.489033    0.482967  0.414144   0.297043

In [6]:
X_test.head()

   lgbm_proba  cat_proba  xgb_proba  hist_proba  lg_proba  knn_proba
0    0.004591   0.031986   0.022774    0.020057  0.006419   0.000000
1    0.003032   0.011817   0.014957    0.018887  0.063872   0.117213
2    0.003777   0.011641   0.014307    0.011497  0.004517   0.000000
3    0.163131   0.544040   0.585898    0.485388  0.655870   0.099916
4    0.872172   0.967646   0.959451    0.959356  0.840450   1.000000

# Feature Engineering

In [7]:
X_train['voting_lgbm_cat_xgb_hist_proba'] = voting_cross_val_predict(
    [
        X_train['lgbm_proba'],
        X_train['cat_proba'],
        X_train['xgb_proba'],
        X_train['hist_proba']
    ], 
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

In [8]:
X_test['voting_lgbm_cat_xgb_hist_proba'] = voting_cross_val_predict(
    [
        X_test['lgbm_proba'],
        X_test['cat_proba'],
        X_test['xgb_proba'],
        X_test['hist_proba']
    ], 
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

# Machine Learning

In [25]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000)
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LogisticRegression(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

features_to_use = ['lg_proba', 'knn_proba', 'voting_lgbm_cat_xgb_hist_proba']

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train[features_to_use], y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-18 14:46:36,653] A new study created in memory with name: no-name-72a9c76d-7c28-4c51-804a-631b5f89331b
Best trial: 4. Best value: 0.5:   0%|          | 1/500 [00:02<19:27,  2.34s/it]

[I 2026-05-18 14:46:38,984] Trial 4 finished with value: 0.5 and parameters: {'solver': 'saga', 'C': 1.9166027703730564e-05, 'l1_ratio': 0.9378992291791106, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0004149387921797278, 'max_iter': 4303}. Best is trial 4 with value: 0.5.

Best trial: 6. Best value: 0.904902:   0%|          | 2/500 [00:07<34:54,  4.21s/it]

[I 2026-05-18 14:46:44,506] Trial 6 finished with value: 0.9049024728241661 and parameters: {'solver': 'saga', 'C': 0.05418154752388287, 'l1_ratio': 0.4415492826714462, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00802015487823809, 'max_iter': 1670}. Best is trial 6 with value: 0.9049024728241661.

Best trial: 2. Best value: 0.94962:   1%|          | 3/500 [00:08<21:26,  2.59s/it]

[I 2026-05-18 14:46:45,166] Trial 2 finished with value: 0.9496201265491233 and parameters: {'solver': 'saga', 'C': 0.8120437249575594, 'l1_ratio': 0.7575200624458551, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.007233688691090751, 'max_iter': 1334}. Best is trial 2 with value: 0.9496201265491233.

Best trial: 10. Best value: 0.949632:   1%|          | 4/500 [00:10<18:09,  2.20s/it]

[I 2026-05-18 14:46:46,763] Trial 10 finished with value: 0.9496321022803793 and parameters: {'solver': 'saga', 'C': 0.001021820893554214, 'l1_ratio': 0.9878383575232703, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0011006288394978898, 'max_iter': 3520}. Best is trial 10 with value: 0.9496321022803793.

Best trial: 10. Best value: 0.949632:   1%|          | 5/500 [00:10<13:51,  1.68s/it]

[I 2026-05-18 14:46:47,527] Trial 1 finished with value: 0.9470029613332764 and parameters: {'solver': 'saga', 'C': 0.00013219946881267518, 'l1_ratio': 0.44740931446480636, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0036391251803277536, 'max_iter': 2313}. Best is trial 10 with value: 0.9496321022803793.

Best trial: 10. Best value: 0.949632:   1%|          | 6/500 [00:11<10:59,  1.33s/it]

[I 2026-05-18 14:46:48,192] Trial 8 pruned.

Best trial: 10. Best value: 0.949632:   1%|▏         | 7/500 [00:12<08:50,  1.08s/it]

[I 2026-05-18 14:46:48,726] Trial 3 pruned.

Best trial: 5. Best value: 0.949632:   2%|▏         | 8/500 [00:13<08:59,  1.10s/it]

[I 2026-05-18 14:46:49,870] Trial 5 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.45791521928225e-05, 'l1_ratio': 0.6620472097221942, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0011701198641922265, 'max_iter': 3764}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   2%|▏         | 9/500 [00:14<08:31,  1.04s/it]

[I 2026-05-18 14:46:50,795] Trial 12 pruned.
[I 2026-05-18 14:46:50,808] Trial 11 pruned.

Best trial: 5. Best value: 0.949632:   2%|▏         | 11/500 [00:14<04:54,  1.66it/s]

[I 2026-05-18 14:46:51,014] Trial 7 pruned.

Best trial: 5. Best value: 0.949632:   2%|▏         | 12/500 [00:16<07:57,  1.02it/s]

[I 2026-05-18 14:46:53,114] Trial 0 finished with value: 0.9496184302240666 and parameters: {'solver': 'saga', 'C': 11.869068816325724, 'l1_ratio': 0.15632717277051522, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000165910338747528, 'max_iter': 3121}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   3%|▎         | 14/500 [00:19<08:22,  1.03s/it]

[I 2026-05-18 14:46:55,582] Trial 13 finished with value: 0.9496210547024546 and parameters: {'solver': 'saga', 'C': 0.16063922107651377, 'l1_ratio': 0.2655590305265738, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0013706292809415243, 'max_iter': 1913}. Best is trial 5 with value: 0.9496323679229632.
[I 2026-05-18 14:46:55,722] Trial 14 pruned.

Best trial: 5. Best value: 0.949632:   3%|▎         | 15/500 [00:21<10:43,  1.33s/it]

[I 2026-05-18 14:46:57,792] Trial 15 pruned.

Best trial: 5. Best value: 0.949632:   3%|▎         | 16/500 [00:21<09:07,  1.13s/it]

[I 2026-05-18 14:46:58,438] Trial 18 finished with value: 0.9495317255022095 and parameters: {'solver': 'saga', 'C': 5.021643279332424, 'l1_ratio': 0.5784324937803342, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002197207853216995, 'max_iter': 4777}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   3%|▎         | 17/500 [00:22<07:28,  1.08it/s]

[I 2026-05-18 14:46:58,871] Trial 9 finished with value: 0.9496184956163436 and parameters: {'solver': 'saga', 'C': 49.539994928981734, 'l1_ratio': 0.5386383767066095, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.187589101721493e-05, 'max_iter': 1525}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   4%|▎         | 18/500 [00:25<13:02,  1.62s/it]

[I 2026-05-18 14:47:02,141] Trial 23 finished with value: 0.9496322634878507 and parameters: {'solver': 'saga', 'C': 0.002242605976655768, 'l1_ratio': 0.9935828862712363, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0011842866858630958, 'max_iter': 4835}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   4%|▍         | 19/500 [00:25<09:45,  1.22s/it]

[I 2026-05-18 14:47:02,416] Trial 20 finished with value: 0.9495341187252443 and parameters: {'solver': 'saga', 'C': 0.796176484865916, 'l1_ratio': 0.15335609669820782, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005064725972691083, 'max_iter': 2524}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   4%|▍         | 20/500 [00:26<08:48,  1.10s/it]

[I 2026-05-18 14:47:03,244] Trial 16 finished with value: 0.9495353317333066 and parameters: {'solver': 'saga', 'C': 0.5776258993427279, 'l1_ratio': 0.4991393420622332, 'class_weight': None, 'fit_intercept': True, 'tol': 6.32704571460899e-05, 'max_iter': 4610}. Best is trial 5 with value: 0.9496323679229632.
[I 2026-05-18 14:47:03,294] Trial 22 finished with value: 0.9496297017596383 and parameters: {'solver': 'saga', 'C': 0.0024269304410877305, 'l1_ratio': 0.9401078707280841, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0003265337504736238, 'max_iter': 3290}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   4%|▍         | 22/500 [00:30<11:01,  1.38s/it]

[I 2026-05-18 14:47:06,680] Trial 17 finished with value: 0.9495442450485736 and parameters: {'solver': 'saga', 'C': 0.200051427715589, 'l1_ratio': 0.31519821368564505, 'class_weight': None, 'fit_intercept': True, 'tol': 1.971805984395567e-05, 'max_iter': 1815}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   5%|▍         | 23/500 [00:32<12:50,  1.62s/it]

[I 2026-05-18 14:47:09,002] Trial 21 finished with value: 0.9489014452977491 and parameters: {'solver': 'saga', 'C': 0.00534010970667391, 'l1_ratio': 0.20636719727576974, 'class_weight': None, 'fit_intercept': True, 'tol': 2.195926100387813e-05, 'max_iter': 4844}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   5%|▍         | 24/500 [00:33<12:01,  1.52s/it]

[I 2026-05-18 14:47:10,235] Trial 19 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.4606510363565322e-05, 'l1_ratio': 0.4076194800572359, 'class_weight': None, 'fit_intercept': True, 'tol': 1.784510741005454e-06, 'max_iter': 3938}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   5%|▌         | 25/500 [00:33<09:15,  1.17s/it]

[I 2026-05-18 14:47:10,470] Trial 25 finished with value: 0.949628970383694 and parameters: {'solver': 'saga', 'C': 0.004621339088627059, 'l1_ratio': 0.9772150016132477, 'class_weight': None, 'fit_intercept': True, 'tol': 3.661869162133856e-05, 'max_iter': 4882}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 5. Best value: 0.949632:   5%|▌         | 26/500 [00:34<08:10,  1.03s/it]

[I 2026-05-18 14:47:11,160] Trial 24 finished with value: 0.9496323142433012 and parameters: {'solver': 'saga', 'C': 0.0035704166799861176, 'l1_ratio': 0.967682388879344, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.5681912689171106e-05, 'max_iter': 4775}. Best is trial 5 with value: 0.9496323679229632.

Best trial: 26. Best value: 0.949632:   5%|▌         | 27/500 [00:35<07:30,  1.05it/s]

[I 2026-05-18 14:47:11,905] Trial 26 finished with value: 0.9496323877681956 and parameters: {'solver': 'saga', 'C': 0.003978904019933721, 'l1_ratio': 0.985568808936758, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.987100747214617e-05, 'max_iter': 4925}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:   6%|▌         | 28/500 [00:35<05:51,  1.34it/s]

[I 2026-05-18 14:47:12,129] Trial 32 finished with value: 0.9496316267904847 and parameters: {'solver': 'saga', 'C': 0.004710252584039734, 'l1_ratio': 0.9977163594019011, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0014550008746033966, 'max_iter': 3444}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:47:12,145] Trial 37 pruned.

Best trial: 26. Best value: 0.949632:   6%|▌         | 30/500 [00:36<04:20,  1.81it/s]

[I 2026-05-18 14:47:12,786] Trial 28 finished with value: 0.9496323322977964 and parameters: {'solver': 'saga', 'C': 0.0036773504703576402, 'l1_ratio': 0.9740171738058573, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.336298775065883e-05, 'max_iter': 3448}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:   6%|▋         | 32/500 [00:36<03:09,  2.47it/s]

[I 2026-05-18 14:47:13,114] Trial 35 pruned.
[I 2026-05-18 14:47:13,250] Trial 27 finished with value: 0.9496322436445211 and parameters: {'solver': 'saga', 'C': 0.006243064203011163, 'l1_ratio': 0.9934681713678676, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.9934255584194367e-05, 'max_iter': 3555}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:   7%|▋         | 33/500 [00:37<03:41,  2.11it/s]

[I 2026-05-18 14:47:13,914] Trial 40 pruned.

Best trial: 26. Best value: 0.949632:   7%|▋         | 35/500 [00:38<04:05,  1.89it/s]

[I 2026-05-18 14:47:15,141] Trial 41 pruned.
[I 2026-05-18 14:47:15,274] Trial 36 pruned.
[I 2026-05-18 14:47:15,294] Trial 39 pruned.

Best trial: 26. Best value: 0.949632:   7%|▋         | 37/500 [00:41<06:29,  1.19it/s]

[I 2026-05-18 14:47:17,728] Trial 30 finished with value: 0.9496240132142842 and parameters: {'solver': 'saga', 'C': 0.006776041051434565, 'l1_ratio': 0.8788276403592403, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.442611003826959e-05, 'max_iter': 4826}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:   8%|▊         | 39/500 [00:41<04:50,  1.59it/s]

[I 2026-05-18 14:47:18,412] Trial 31 finished with value: 0.9496211256594556 and parameters: {'solver': 'saga', 'C': 0.004706529758769707, 'l1_ratio': 0.8790069542736054, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.6309194307414044e-05, 'max_iter': 4941}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:47:18,542] Trial 33 finished with value: 0.9496204824542636 and parameters: {'solver': 'saga', 'C': 0.006761715781977178, 'l1_ratio': 0.8522841798404901, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0011989813852209298, 'max_iter': 3470}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:   8%|▊         | 41/500 [00:46<09:05,  1.19s/it]

[I 2026-05-18 14:47:22,731] Trial 43 pruned.
[I 2026-05-18 14:47:22,864] Trial 42 pruned.

Best trial: 26. Best value: 0.949632:   8%|▊         | 42/500 [00:47<08:21,  1.10s/it]

[I 2026-05-18 14:47:23,750] Trial 44 pruned.

Best trial: 26. Best value: 0.949632:   9%|▉         | 44/500 [00:48<06:19,  1.20it/s]

[I 2026-05-18 14:47:24,932] Trial 45 pruned.
[I 2026-05-18 14:47:25,066] Trial 29 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.6218188667019043e-05, 'l1_ratio': 0.8518815012182468, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.854279000897774e-05, 'max_iter': 4932}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:   9%|▉         | 46/500 [00:48<03:38,  2.08it/s]

[I 2026-05-18 14:47:25,218] Trial 34 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.6194568423560202e-05, 'l1_ratio': 0.8158766108166977, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010748910807905124, 'max_iter': 3583}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:47:25,342] Trial 46 pruned.

Best trial: 26. Best value: 0.949632:   9%|▉         | 47/500 [00:52<12:02,  1.60s/it]

[I 2026-05-18 14:47:29,570] Trial 47 pruned.

Best trial: 26. Best value: 0.949632:  10%|▉         | 48/500 [00:54<11:36,  1.54s/it]

[I 2026-05-18 14:47:30,981] Trial 48 pruned.

Best trial: 26. Best value: 0.949632:  10%|▉         | 49/500 [00:54<09:11,  1.22s/it]

[I 2026-05-18 14:47:31,454] Trial 49 pruned.

Best trial: 26. Best value: 0.949632:  10%|█         | 50/500 [00:55<08:46,  1.17s/it]

[I 2026-05-18 14:47:32,508] Trial 50 pruned.

Best trial: 26. Best value: 0.949632:  10%|█         | 51/500 [00:57<09:39,  1.29s/it]

[I 2026-05-18 14:47:34,056] Trial 38 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 6.661972482187306e-05, 'l1_ratio': 0.8383690467376442, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.1673815442472923e-06, 'max_iter': 3701}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  10%|█         | 52/500 [00:58<08:09,  1.09s/it]

[I 2026-05-18 14:47:34,710] Trial 58 pruned.

Best trial: 26. Best value: 0.949632:  11%|█         | 53/500 [00:58<06:57,  1.07it/s]

[I 2026-05-18 14:47:35,273] Trial 56 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00012236503727825273, 'l1_ratio': 0.7862575712090142, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006911806247488828, 'max_iter': 4096}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  11%|█         | 54/500 [00:58<05:31,  1.35it/s]

[I 2026-05-18 14:47:35,566] Trial 57 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.4537789251628885e-05, 'l1_ratio': 0.7665509906520742, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0041250729950604356, 'max_iter': 4056}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  11%|█         | 55/500 [01:00<06:53,  1.08it/s]

[I 2026-05-18 14:47:36,931] Trial 61 pruned.

Best trial: 26. Best value: 0.949632:  11%|█         | 56/500 [01:00<05:37,  1.32it/s]

[I 2026-05-18 14:47:37,295] Trial 52 pruned.

Best trial: 26. Best value: 0.949632:  12%|█▏        | 59/500 [01:01<02:49,  2.60it/s]

[I 2026-05-18 14:47:37,728] Trial 51 pruned.
[I 2026-05-18 14:47:37,746] Trial 60 pruned.
[I 2026-05-18 14:47:37,848] Trial 53 pruned.

Best trial: 26. Best value: 0.949632:  12%|█▏        | 60/500 [01:01<02:45,  2.66it/s]

[I 2026-05-18 14:47:38,203] Trial 59 pruned.

Best trial: 26. Best value: 0.949632:  12%|█▏        | 61/500 [01:02<03:17,  2.23it/s]

[I 2026-05-18 14:47:38,858] Trial 55 pruned.
[I 2026-05-18 14:47:38,960] Trial 67 pruned.

Best trial: 26. Best value: 0.949632:  13%|█▎        | 63/500 [01:02<02:34,  2.82it/s]

[I 2026-05-18 14:47:39,315] Trial 54 pruned.

Best trial: 26. Best value: 0.949632:  13%|█▎        | 64/500 [01:04<05:31,  1.31it/s]

[I 2026-05-18 14:47:41,398] Trial 70 pruned.

Best trial: 26. Best value: 0.949632:  13%|█▎        | 65/500 [01:06<06:44,  1.08it/s]

[I 2026-05-18 14:47:42,838] Trial 64 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.315676773429952e-05, 'l1_ratio': 0.7835027512368463, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005653832076499412, 'max_iter': 3879}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  13%|█▎        | 66/500 [01:10<13:24,  1.85s/it]

[I 2026-05-18 14:47:47,268] Trial 74 pruned.

Best trial: 26. Best value: 0.949632:  13%|█▎        | 67/500 [01:11<10:49,  1.50s/it]

[I 2026-05-18 14:47:47,836] Trial 62 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.4557810639117595e-05, 'l1_ratio': 0.7859348267929491, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000646361671123728, 'max_iter': 3922}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  14%|█▍        | 69/500 [01:11<06:42,  1.07it/s]

[I 2026-05-18 14:47:48,448] Trial 72 pruned.
[I 2026-05-18 14:47:48,584] Trial 63 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.556840692293628e-05, 'l1_ratio': 0.7826149348076631, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005903821503218608, 'max_iter': 3909}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  14%|█▍        | 70/500 [01:12<05:14,  1.37it/s]

[I 2026-05-18 14:47:48,830] Trial 75 pruned.

Best trial: 26. Best value: 0.949632:  14%|█▍        | 71/500 [01:12<04:33,  1.57it/s]

[I 2026-05-18 14:47:49,243] Trial 65 pruned.

Best trial: 26. Best value: 0.949632:  14%|█▍        | 72/500 [01:12<03:43,  1.91it/s]

[I 2026-05-18 14:47:49,488] Trial 76 pruned.

Best trial: 26. Best value: 0.949632:  15%|█▍        | 73/500 [01:13<04:00,  1.78it/s]

[I 2026-05-18 14:47:50,140] Trial 71 pruned.

Best trial: 26. Best value: 0.949632:  15%|█▍        | 74/500 [01:14<04:10,  1.70it/s]

[I 2026-05-18 14:47:50,791] Trial 69 pruned.

Best trial: 26. Best value: 0.949632:  15%|█▌        | 75/500 [01:14<04:34,  1.55it/s]

[I 2026-05-18 14:47:51,576] Trial 82 pruned.

Best trial: 26. Best value: 0.949632:  15%|█▌        | 77/500 [01:15<03:40,  1.92it/s]

[I 2026-05-18 14:47:51,802] Trial 73 finished with value: 0.9495521425134804 and parameters: {'solver': 'saga', 'C': 6.723633981368287e-05, 'l1_ratio': 0.7198597586660139, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006444523686300626, 'max_iter': 3786}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:47:51,846] Trial 68 pruned.
[I 2026-05-18 14:47:51,999] Trial 83 pruned.

Best trial: 26. Best value: 0.949632:  16%|█▌        | 79/500 [01:15<02:42,  2.59it/s]

[I 2026-05-18 14:47:52,568] Trial 66 pruned.

Best trial: 26. Best value: 0.949632:  16%|█▌        | 80/500 [01:17<04:33,  1.54it/s]

[I 2026-05-18 14:47:53,969] Trial 77 pruned.

Best trial: 26. Best value: 0.949632:  16%|█▌        | 81/500 [01:17<04:25,  1.58it/s]

[I 2026-05-18 14:47:54,555] Trial 78 pruned.

Best trial: 26. Best value: 0.949632:  16%|█▋        | 82/500 [01:19<06:56,  1.00it/s]

[I 2026-05-18 14:47:56,474] Trial 90 pruned.

Best trial: 26. Best value: 0.949632:  17%|█▋        | 84/500 [01:20<04:27,  1.55it/s]

[I 2026-05-18 14:47:56,954] Trial 84 pruned.
[I 2026-05-18 14:47:57,102] Trial 85 pruned.

Best trial: 26. Best value: 0.949632:  17%|█▋        | 85/500 [01:21<04:27,  1.55it/s]

[I 2026-05-18 14:47:57,756] Trial 86 pruned.

Best trial: 26. Best value: 0.949632:  17%|█▋        | 86/500 [01:21<04:42,  1.47it/s]

[I 2026-05-18 14:47:58,526] Trial 80 pruned.

Best trial: 26. Best value: 0.949632:  17%|█▋        | 87/500 [01:22<04:53,  1.41it/s]

[I 2026-05-18 14:47:59,307] Trial 88 pruned.

Best trial: 26. Best value: 0.949632:  18%|█▊        | 88/500 [01:24<06:51,  1.00it/s]

[I 2026-05-18 14:48:00,986] Trial 89 pruned.
[I 2026-05-18 14:48:01,045] Trial 81 pruned.

Best trial: 26. Best value: 0.949632:  18%|█▊        | 90/500 [01:27<09:04,  1.33s/it]

[I 2026-05-18 14:48:04,413] Trial 91 pruned.

Best trial: 26. Best value: 0.949632:  18%|█▊        | 91/500 [01:29<09:59,  1.46s/it]

[I 2026-05-18 14:48:06,297] Trial 87 finished with value: 0.9491808669718628 and parameters: {'solver': 'saga', 'C': 9.614160367845736e-05, 'l1_ratio': 0.9012484616097115, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0002740031450096333, 'max_iter': 3573}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  18%|█▊        | 92/500 [01:31<10:23,  1.53s/it]

[I 2026-05-18 14:48:07,998] Trial 79 finished with value: 0.9491063860696871 and parameters: {'solver': 'saga', 'C': 9.729064101863555e-05, 'l1_ratio': 0.8984155181400911, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.8501137581820737e-05, 'max_iter': 3754}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  19%|█▊        | 93/500 [01:32<08:59,  1.33s/it]

[I 2026-05-18 14:48:08,790] Trial 93 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.9693619474511787e-05, 'l1_ratio': 0.8102568060181496, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0015669283516408562, 'max_iter': 3572}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  19%|█▉        | 94/500 [01:34<10:48,  1.60s/it]

[I 2026-05-18 14:48:11,087] Trial 96 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.951755664400295e-05, 'l1_ratio': 0.9508113548290335, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002890923930842112, 'max_iter': 4283}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  19%|█▉        | 96/500 [01:35<07:15,  1.08s/it]

[I 2026-05-18 14:48:12,159] Trial 92 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.6895847506332e-05, 'l1_ratio': 0.651653830128921, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00033167499599730846, 'max_iter': 4265}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:48:12,326] Trial 101 finished with value: 0.9496320883026543 and parameters: {'solver': 'saga', 'C': 4.269284311407227e-05, 'l1_ratio': 0.8175106278719386, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.008052539717391994, 'max_iter': 4234}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  19%|█▉        | 96/500 [01:35<07:15,  1.08s/it]

[I 2026-05-18 14:48:12,376] Trial 100 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.6372348633866763e-05, 'l1_ratio': 0.7759422314812561, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.009081953818420684, 'max_iter': 1093}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  20%|█▉        | 98/500 [01:36<04:52,  1.38it/s]

[I 2026-05-18 14:48:12,934] Trial 97 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.131292748903166e-05, 'l1_ratio': 0.808644061669004, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003877947815384436, 'max_iter': 4281}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  20%|█▉        | 99/500 [01:36<04:09,  1.61it/s]

[I 2026-05-18 14:48:13,233] Trial 99 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.326773810454363e-05, 'l1_ratio': 0.8201215987596397, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0015439812020311458, 'max_iter': 4270}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  20%|██        | 100/500 [01:36<03:41,  1.81it/s]

[I 2026-05-18 14:48:13,585] Trial 94 finished with value: 0.9494854967470852 and parameters: {'solver': 'saga', 'C': 3.787443813957882e-05, 'l1_ratio': 0.65036655531385, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002680534078777334, 'max_iter': 2322}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  20%|██        | 101/500 [01:37<04:16,  1.55it/s]

[I 2026-05-18 14:48:14,474] Trial 95 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.9530228163295274e-05, 'l1_ratio': 0.815418604086591, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.185216014724177e-05, 'max_iter': 4318}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  20%|██        | 102/500 [01:40<07:32,  1.14s/it]

[I 2026-05-18 14:48:16,891] Trial 102 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.233272496085506e-05, 'l1_ratio': 0.8154930877372412, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0010434213341847403, 'max_iter': 4229}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  21%|██        | 103/500 [01:43<11:17,  1.71s/it]

[I 2026-05-18 14:48:20,032] Trial 104 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.578421144118327e-05, 'l1_ratio': 0.7760117578606869, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005548201783532457, 'max_iter': 4260}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  21%|██        | 104/500 [01:45<12:31,  1.90s/it]

[I 2026-05-18 14:48:22,396] Trial 103 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.964394569869347e-05, 'l1_ratio': 0.8266803123444518, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005093800114011449, 'max_iter': 3417}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  21%|██        | 105/500 [01:46<09:36,  1.46s/it]

[I 2026-05-18 14:48:22,769] Trial 98 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.8259056024843206e-05, 'l1_ratio': 0.8163445101250771, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.4268944595815522e-06, 'max_iter': 2360}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  21%|██        | 106/500 [01:46<07:13,  1.10s/it]

[I 2026-05-18 14:48:23,037] Trial 106 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.3480005682811755e-05, 'l1_ratio': 0.774854739697383, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0010429407224423369, 'max_iter': 3972}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  21%|██▏       | 107/500 [01:47<06:21,  1.03it/s]

[I 2026-05-18 14:48:23,701] Trial 112 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.350152824514989e-05, 'l1_ratio': 0.8776425267282214, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005420003331728002, 'max_iter': 3973}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  22%|██▏       | 108/500 [01:47<05:11,  1.26it/s]

[I 2026-05-18 14:48:24,079] Trial 108 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.7492062656146568e-05, 'l1_ratio': 0.77250313418155, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0011089461586258156, 'max_iter': 2144}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  22%|██▏       | 110/500 [01:48<03:59,  1.63it/s]

[I 2026-05-18 14:48:24,965] Trial 107 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.6211065517148446e-05, 'l1_ratio': 0.7647208728982071, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0011496936453949007, 'max_iter': 4455}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:48:25,090] Trial 105 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.7425527578432232e-05, 'l1_ratio': 0.8123679035958441, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012732981624176624, 'max_iter': 4317}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  22%|██▏       | 111/500 [01:48<03:36,  1.80it/s]

[I 2026-05-18 14:48:25,515] Trial 118 pruned.

Best trial: 26. Best value: 0.949632:  22%|██▏       | 112/500 [01:49<03:19,  1.94it/s]

[I 2026-05-18 14:48:25,933] Trial 110 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.6970244668189765e-05, 'l1_ratio': 0.7742872302115664, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00112897784052619, 'max_iter': 2281}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:48:26,007] Trial 121 pruned.

Best trial: 26. Best value: 0.949632:  23%|██▎       | 114/500 [01:49<02:15,  2.85it/s]

[I 2026-05-18 14:48:26,247] Trial 109 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.659874660047991e-05, 'l1_ratio': 0.7721362814024432, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0004852277087156173, 'max_iter': 4440}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  23%|██▎       | 115/500 [01:50<02:58,  2.16it/s]

[I 2026-05-18 14:48:27,056] Trial 120 pruned.

Best trial: 26. Best value: 0.949632:  23%|██▎       | 116/500 [01:50<02:54,  2.20it/s]

[I 2026-05-18 14:48:27,482] Trial 113 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.422138686784458e-05, 'l1_ratio': 0.7689464845071527, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0055630131760791455, 'max_iter': 3412}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:48:27,495] Trial 111 pruned.

Best trial: 26. Best value: 0.949632:  24%|██▎       | 118/500 [01:52<04:08,  1.54it/s]

[I 2026-05-18 14:48:29,311] Trial 127 pruned.

Best trial: 26. Best value: 0.949632:  24%|██▍       | 119/500 [01:52<03:36,  1.76it/s]

[I 2026-05-18 14:48:29,612] Trial 119 pruned.

Best trial: 26. Best value: 0.949632:  24%|██▍       | 120/500 [01:53<03:19,  1.90it/s]

[I 2026-05-18 14:48:30,002] Trial 114 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.46142960838154e-05, 'l1_ratio': 0.7682376573495827, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006010617763884286, 'max_iter': 4457}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  24%|██▍       | 121/500 [01:55<05:19,  1.19it/s]

[I 2026-05-18 14:48:31,735] Trial 130 pruned.

Best trial: 26. Best value: 0.949632:  24%|██▍       | 122/500 [01:56<06:02,  1.04it/s]

[I 2026-05-18 14:48:33,009] Trial 125 pruned.

Best trial: 26. Best value: 0.949632:  25%|██▍       | 124/500 [01:57<04:28,  1.40it/s]

[I 2026-05-18 14:48:33,863] Trial 116 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.1595038727052763e-05, 'l1_ratio': 0.7755737213884871, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004589699100411294, 'max_iter': 3963}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:48:34,012] Trial 126 pruned.

Best trial: 26. Best value: 0.949632:  25%|██▌       | 125/500 [01:57<03:31,  1.78it/s]

[I 2026-05-18 14:48:34,219] Trial 115 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.400414513237813e-05, 'l1_ratio': 0.7648173102407514, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0061410023160694445, 'max_iter': 4471}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  25%|██▌       | 127/500 [01:57<02:22,  2.61it/s]

[I 2026-05-18 14:48:34,451] Trial 117 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.594692342695213e-05, 'l1_ratio': 0.871281336079376, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004634273806900027, 'max_iter': 4493}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:48:34,646] Trial 122 pruned.

Best trial: 26. Best value: 0.949632:  26%|██▌       | 128/500 [02:00<06:04,  1.02it/s]

[I 2026-05-18 14:48:37,044] Trial 123 pruned.

Best trial: 26. Best value: 0.949632:  26%|██▌       | 129/500 [02:00<04:57,  1.25it/s]

[I 2026-05-18 14:48:37,424] Trial 129 pruned.

Best trial: 26. Best value: 0.949632:  26%|██▌       | 130/500 [02:02<06:53,  1.12s/it]

[I 2026-05-18 14:48:39,281] Trial 124 pruned.

Best trial: 26. Best value: 0.949632:  26%|██▌       | 131/500 [02:03<07:17,  1.19s/it]

[I 2026-05-18 14:48:40,625] Trial 131 pruned.

Best trial: 26. Best value: 0.949632:  26%|██▋       | 132/500 [02:04<05:38,  1.09it/s]

[I 2026-05-18 14:48:40,923] Trial 135 pruned.

Best trial: 26. Best value: 0.949632:  27%|██▋       | 133/500 [02:04<04:27,  1.37it/s]

[I 2026-05-18 14:48:41,204] Trial 134 pruned.

Best trial: 26. Best value: 0.949632:  27%|██▋       | 134/500 [02:06<07:04,  1.16s/it]

[I 2026-05-18 14:48:43,367] Trial 128 pruned.
[I 2026-05-18 14:48:43,386] Trial 136 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 6.102448409764611e-05, 'l1_ratio': 0.9335494909909621, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0016102970333484294, 'max_iter': 3483}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  27%|██▋       | 136/500 [02:07<04:25,  1.37it/s]

[I 2026-05-18 14:48:43,828] Trial 139 pruned.

Best trial: 26. Best value: 0.949632:  27%|██▋       | 137/500 [02:07<04:00,  1.51it/s]

[I 2026-05-18 14:48:44,286] Trial 132 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.7157606125128382e-05, 'l1_ratio': 0.51555157977785, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0016340054706188395, 'max_iter': 3840}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  28%|██▊       | 138/500 [02:09<06:24,  1.06s/it]

[I 2026-05-18 14:48:46,476] Trial 137 finished with value: 0.9496189078263892 and parameters: {'solver': 'saga', 'C': 3.55687213529399, 'l1_ratio': 0.35791985266570353, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008369768264083108, 'max_iter': 4873}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  28%|██▊       | 139/500 [02:10<05:54,  1.02it/s]

[I 2026-05-18 14:48:47,245] Trial 133 finished with value: 0.9493304439242556 and parameters: {'solver': 'saga', 'C': 1.7949657846061215e-05, 'l1_ratio': 0.4896097640757804, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0015680020338190966, 'max_iter': 3507}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  28%|██▊       | 140/500 [02:10<04:49,  1.24it/s]

[I 2026-05-18 14:48:47,585] Trial 138 pruned.

Best trial: 26. Best value: 0.949632:  28%|██▊       | 141/500 [02:12<05:22,  1.11it/s]

[I 2026-05-18 14:48:48,723] Trial 150 pruned.
[I 2026-05-18 14:48:48,741] Trial 141 finished with value: 0.9496308946151389 and parameters: {'solver': 'saga', 'C': 5.948004111467539e-05, 'l1_ratio': 0.9078020408163177, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0015527189028708762, 'max_iter': 3489}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  29%|██▊       | 143/500 [02:16<08:42,  1.46s/it]

[I 2026-05-18 14:48:53,029] Trial 140 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.8134582703812962e-05, 'l1_ratio': 0.9141901887086458, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008503347831937077, 'max_iter': 3486}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  29%|██▉       | 144/500 [02:20<12:09,  2.05s/it]

[I 2026-05-18 14:48:56,906] Trial 142 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.681674729386983e-05, 'l1_ratio': 0.8401556592661805, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0015640180296212323, 'max_iter': 4893}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  29%|██▉       | 145/500 [02:22<12:01,  2.03s/it]

[I 2026-05-18 14:48:58,888] Trial 144 finished with value: 0.8598344250422156 and parameters: {'solver': 'saga', 'C': 1.7567976620269084e-05, 'l1_ratio': 0.925107118317607, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.822645442689278e-05, 'max_iter': 4077}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  29%|██▉       | 146/500 [02:22<09:35,  1.62s/it]

[I 2026-05-18 14:48:59,408] Trial 147 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.944843876885089e-05, 'l1_ratio': 0.7431478661298146, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00013411722714993748, 'max_iter': 4149}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  29%|██▉       | 147/500 [02:23<08:40,  1.47s/it]

[I 2026-05-18 14:49:00,481] Trial 148 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.8675090874151272e-05, 'l1_ratio': 0.829590788584568, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014606620599249913, 'max_iter': 4851}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  30%|██▉       | 148/500 [02:25<08:52,  1.51s/it]

[I 2026-05-18 14:49:02,103] Trial 151 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00015375335744471656, 'l1_ratio': 0.8471624565290315, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014648581326288628, 'max_iter': 4129}. Best is trial 26 with value: 0.9496323877681956.

[I 2026-05-18 14:49:03,464] Trial 145 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.7904925654964835e-05, 'l1_ratio': 0.8424016610842271, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.305494652071772e-05, 'max_iter': 4137}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  30%|███       | 150/500 [02:27<06:25,  1.10s/it]

[I 2026-05-18 14:49:03,665] Trial 143 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.7445579052456683e-05, 'l1_ratio': 0.924883263984714, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.90235618287628e-05, 'max_iter': 3510}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  30%|███       | 151/500 [02:27<06:04,  1.04s/it]

[I 2026-05-18 14:49:04,576] Trial 146 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.7947448601639203e-05, 'l1_ratio': 0.833734690957754, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.02421416811462e-05, 'max_iter': 4873}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  30%|███       | 152/500 [02:29<07:25,  1.28s/it]

[I 2026-05-18 14:49:06,416] Trial 161 pruned.

Best trial: 26. Best value: 0.949632:  31%|███       | 153/500 [02:30<05:52,  1.02s/it]

[I 2026-05-18 14:49:06,806] Trial 149 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.8545414328636375e-05, 'l1_ratio': 0.8399354743169221, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.047055824417068e-05, 'max_iter': 4183}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  31%|███       | 154/500 [02:30<04:41,  1.23it/s]

[I 2026-05-18 14:49:07,147] Trial 153 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.715873152070755e-05, 'l1_ratio': 0.8305409376569961, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00015079517890298136, 'max_iter': 4195}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  31%|███       | 155/500 [02:31<04:26,  1.29it/s]

[I 2026-05-18 14:49:07,827] Trial 158 pruned.

Best trial: 26. Best value: 0.949632:  31%|███       | 156/500 [02:31<04:07,  1.39it/s]

[I 2026-05-18 14:49:08,424] Trial 152 finished with value: 0.8597010643314833 and parameters: {'solver': 'saga', 'C': 1.7600642907745237e-05, 'l1_ratio': 0.9454911541127743, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.640710772461852e-05, 'max_iter': 4153}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  31%|███▏      | 157/500 [02:32<04:06,  1.39it/s]

[I 2026-05-18 14:49:09,135] Trial 157 pruned.

Best trial: 26. Best value: 0.949632:  32%|███▏      | 158/500 [02:35<08:08,  1.43s/it]

[I 2026-05-18 14:49:12,228] Trial 155 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.171700525658675e-05, 'l1_ratio': 0.796704455323749, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001387107248736455, 'max_iter': 4183}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  32%|███▏      | 159/500 [02:36<06:38,  1.17s/it]

[I 2026-05-18 14:49:12,790] Trial 162 pruned.

Best trial: 26. Best value: 0.949632:  32%|███▏      | 160/500 [02:38<08:35,  1.52s/it]

[I 2026-05-18 14:49:15,116] Trial 154 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.8141703766870048e-05, 'l1_ratio': 0.8380310154551013, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.931255466034774e-05, 'max_iter': 4150}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  32%|███▏      | 161/500 [02:38<06:21,  1.13s/it]

[I 2026-05-18 14:49:15,332] Trial 156 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.331560067492212e-05, 'l1_ratio': 0.8040541058947697, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00011498388271172765, 'max_iter': 4154}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  32%|███▏      | 162/500 [02:40<06:41,  1.19s/it]

[I 2026-05-18 14:49:16,661] Trial 160 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.474043459743935e-05, 'l1_ratio': 0.9509299036770246, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0004141329115084961, 'max_iter': 4340}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  33%|███▎      | 164/500 [02:42<06:41,  1.20s/it]

[I 2026-05-18 14:49:19,335] Trial 159 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.09948304019966e-05, 'l1_ratio': 0.9458290510162035, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.631638684544707e-05, 'max_iter': 4023}. Best is trial 26 with value: 0.9496323877681956.
[I 2026-05-18 14:49:19,510] Trial 165 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.484103625688055e-05, 'l1_ratio': 0.8024208049568579, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00040568269538307603, 'max_iter': 4325}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  33%|███▎      | 165/500 [02:44<07:03,  1.27s/it]

[I 2026-05-18 14:49:20,930] Trial 163 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.7451896415313965e-05, 'l1_ratio': 0.8020806130239019, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0004550637068589866, 'max_iter': 4008}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  33%|███▎      | 166/500 [02:44<05:26,  1.02it/s]

[I 2026-05-18 14:49:21,214] Trial 164 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.357679972563906e-05, 'l1_ratio': 0.8004954905559943, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00040014665695299953, 'max_iter': 4361}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  33%|███▎      | 167/500 [02:45<06:06,  1.10s/it]

[I 2026-05-18 14:49:22,632] Trial 167 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.496623273192156e-05, 'l1_ratio': 0.8024694123666947, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003727751767400372, 'max_iter': 4370}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  34%|███▎      | 168/500 [02:46<04:55,  1.12it/s]

[I 2026-05-18 14:49:23,033] Trial 166 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.886855930774584e-05, 'l1_ratio': 0.800525707760632, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00038466615556915075, 'max_iter': 3933}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  34%|███▍      | 169/500 [02:47<04:58,  1.11it/s]

[I 2026-05-18 14:49:23,955] Trial 179 pruned.

Best trial: 26. Best value: 0.949632:  34%|███▍      | 170/500 [02:47<04:06,  1.34it/s]

[I 2026-05-18 14:49:24,340] Trial 168 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.096859697608364e-05, 'l1_ratio': 0.8058221934488927, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000305340154710061, 'max_iter': 4333}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  34%|███▍      | 171/500 [02:49<05:56,  1.08s/it]

[I 2026-05-18 14:49:26,215] Trial 178 pruned.

Best trial: 26. Best value: 0.949632:  34%|███▍      | 172/500 [02:49<04:29,  1.22it/s]

[I 2026-05-18 14:49:26,423] Trial 170 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.962533625609934e-05, 'l1_ratio': 0.7466045925720737, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00041160903128893543, 'max_iter': 4352}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  35%|███▍      | 173/500 [02:50<03:51,  1.41it/s]

[I 2026-05-18 14:49:26,862] Trial 169 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.164717110517912e-05, 'l1_ratio': 0.8112867234129468, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003463808477250137, 'max_iter': 4553}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  35%|███▍      | 174/500 [02:51<04:48,  1.13it/s]

[I 2026-05-18 14:49:28,166] Trial 171 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.2315177393005685e-05, 'l1_ratio': 0.8088502016507543, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00038600423749440523, 'max_iter': 4352}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  35%|███▌      | 175/500 [02:53<05:56,  1.10s/it]

[I 2026-05-18 14:49:29,746] Trial 173 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.302937277807315e-05, 'l1_ratio': 0.8116037728545838, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00042126476441462635, 'max_iter': 3941}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  35%|███▌      | 176/500 [02:55<08:34,  1.59s/it]

[I 2026-05-18 14:49:32,485] Trial 175 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 5.015072782081347e-05, 'l1_ratio': 0.7507962082086449, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003141445383121053, 'max_iter': 1896}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  35%|███▌      | 177/500 [03:00<13:22,  2.48s/it]

[I 2026-05-18 14:49:37,063] Trial 185 finished with value: 0.9496323778454989 and parameters: {'solver': 'saga', 'C': 8.698460456482418e-05, 'l1_ratio': 0.8685060830881438, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0031694941041423156, 'max_iter': 2616}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  36%|███▌      | 178/500 [03:01<11:18,  2.11s/it]

[I 2026-05-18 14:49:38,288] Trial 182 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 8.176593152946545e-05, 'l1_ratio': 0.818878854173017, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000531982073259567, 'max_iter': 1421}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  36%|███▌      | 179/500 [03:02<09:44,  1.82s/it]

[I 2026-05-18 14:49:39,441] Trial 187 pruned.

Best trial: 26. Best value: 0.949632:  36%|███▌      | 180/500 [03:03<07:22,  1.38s/it]

[I 2026-05-18 14:49:39,802] Trial 172 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.7932393216892765e-05, 'l1_ratio': 0.806828935154925, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.0583395769559608e-06, 'max_iter': 1515}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  36%|███▌      | 181/500 [03:03<05:49,  1.10s/it]

[I 2026-05-18 14:49:40,228] Trial 181 pruned.

Best trial: 26. Best value: 0.949632:  36%|███▋      | 182/500 [03:05<07:01,  1.33s/it]

[I 2026-05-18 14:49:42,080] Trial 174 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.446604895539721e-05, 'l1_ratio': 0.7996301950906484, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.716824863038703e-06, 'max_iter': 2652}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  37%|███▋      | 183/500 [03:06<07:00,  1.33s/it]

[I 2026-05-18 14:49:43,425] Trial 188 pruned.

Best trial: 26. Best value: 0.949632:  37%|███▋      | 184/500 [03:07<05:55,  1.13s/it]

[I 2026-05-18 14:49:44,077] Trial 189 pruned.

Best trial: 26. Best value: 0.949632:  37%|███▋      | 186/500 [03:08<04:12,  1.24it/s]

[I 2026-05-18 14:49:45,031] Trial 193 pruned.
[I 2026-05-18 14:49:45,205] Trial 176 finished with value: 0.9494479661678964 and parameters: {'solver': 'saga', 'C': 4.9458175489830505e-05, 'l1_ratio': 0.6800829114538345, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.3643136480497636e-06, 'max_iter': 3674}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  37%|███▋      | 187/500 [03:08<03:29,  1.50it/s]

[I 2026-05-18 14:49:45,556] Trial 190 pruned.
[I 2026-05-18 14:49:45,574] Trial 177 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.934494043542551e-05, 'l1_ratio': 0.7500682409639711, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.0617282593936101e-06, 'max_iter': 2693}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  38%|███▊      | 189/500 [03:09<02:39,  1.95it/s]

[I 2026-05-18 14:49:46,223] Trial 191 pruned.

Best trial: 26. Best value: 0.949632:  38%|███▊      | 190/500 [03:09<02:21,  2.19it/s]

[I 2026-05-18 14:49:46,511] Trial 194 pruned.

Best trial: 26. Best value: 0.949632:  38%|███▊      | 191/500 [03:10<02:02,  2.52it/s]

[I 2026-05-18 14:49:46,737] Trial 186 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 8.136302860222484e-05, 'l1_ratio': 0.8907445914945735, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.383576994667183e-05, 'max_iter': 1518}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 26. Best value: 0.949632:  38%|███▊      | 192/500 [03:11<03:03,  1.68it/s]

[I 2026-05-18 14:49:47,864] Trial 180 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.775062768521714e-05, 'l1_ratio': 0.7465023781028542, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.246850662017757e-06, 'max_iter': 2527}. Best is trial 26 with value: 0.9496323877681956.

Best trial: 192. Best value: 0.949632:  39%|███▊      | 193/500 [03:12<03:32,  1.44it/s]

[I 2026-05-18 14:49:48,807] Trial 192 finished with value: 0.9496324484453632 and parameters: {'solver': 'saga', 'C': 0.00013765154049246483, 'l1_ratio': 0.8930181573733315, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003526853478114651, 'max_iter': 3765}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  39%|███▉      | 194/500 [03:12<03:15,  1.57it/s]

[I 2026-05-18 14:49:49,296] Trial 184 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 8.436023439318506e-05, 'l1_ratio': 0.8625034180880131, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.9100539558115123e-06, 'max_iter': 2418}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  39%|███▉      | 195/500 [03:15<07:03,  1.39s/it]

[I 2026-05-18 14:49:52,529] Trial 183 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.715611728829517e-05, 'l1_ratio': 0.8883902293291784, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.0241834847619069e-06, 'max_iter': 2563}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  39%|███▉      | 196/500 [03:16<06:35,  1.30s/it]

[I 2026-05-18 14:49:53,622] Trial 195 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.0001338134551852584, 'l1_ratio': 0.9755612171863828, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0024203818438628586, 'max_iter': 2183}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  39%|███▉      | 197/500 [03:19<08:29,  1.68s/it]

[I 2026-05-18 14:49:56,214] Trial 203 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.3911168921747787e-05, 'l1_ratio': 0.7717887861202886, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.009844470993987567, 'max_iter': 4259}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  40%|███▉      | 199/500 [03:20<05:03,  1.01s/it]

[I 2026-05-18 14:49:56,779] Trial 196 finished with value: 0.9496323845154577 and parameters: {'solver': 'saga', 'C': 0.00016648149524889683, 'l1_ratio': 0.7849217834450547, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006289680024195528, 'max_iter': 4277}. Best is trial 192 with value: 0.9496324484453632.
[I 2026-05-18 14:49:56,951] Trial 197 finished with value: 0.9489932115768172 and parameters: {'solver': 'saga', 'C': 0.00012405780539252173, 'l1_ratio': 0.8971080288558334, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009323648600829084, 'max_iter': 3916}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  40%|████      | 200/500 [03:20<05:02,  1.01s/it]

[I 2026-05-18 14:49:57,042] Trial 202 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.3469280528083427e-05, 'l1_ratio': 0.7861209531785349, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.007811584689353305, 'max_iter': 1049}. Best is trial 192 with value: 0.9496324484453632.
[I 2026-05-18 14:49:57,043] Trial 201 finished with value: 0.9496323000889415 and parameters: {'solver': 'saga', 'C': 0.00015062284652917878, 'l1_ratio': 0.7809240916518929, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00218291659200566, 'max_iter': 4266}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  40%|████      | 202/500 [03:21<03:14,  1.53it/s]

[I 2026-05-18 14:49:58,111] Trial 204 finished with value: 0.949632440149116 and parameters: {'solver': 'saga', 'C': 0.00015625844815960106, 'l1_ratio': 0.9846499202683542, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0024733439310679712, 'max_iter': 4229}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  41%|████      | 203/500 [03:22<03:16,  1.51it/s]

[I 2026-05-18 14:49:58,802] Trial 206 pruned.

Best trial: 192. Best value: 0.949632:  41%|████      | 204/500 [03:22<03:02,  1.63it/s]

[I 2026-05-18 14:49:59,263] Trial 199 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.395598001920872e-05, 'l1_ratio': 0.9007376853657664, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0009542506015920899, 'max_iter': 3751}. Best is trial 192 with value: 0.9496324484453632.
[I 2026-05-18 14:49:59,346] Trial 205 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.0001465415308594317, 'l1_ratio': 0.975096800343366, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002009993841614334, 'max_iter': 4239}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  41%|████      | 206/500 [03:23<02:18,  2.13it/s]

[I 2026-05-18 14:49:59,758] Trial 198 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.284331071260145e-05, 'l1_ratio': 0.8927433956691754, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0008892491205287345, 'max_iter': 3222}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  41%|████▏     | 207/500 [03:24<03:23,  1.44it/s]

[I 2026-05-18 14:50:01,248] Trial 207 pruned.

Best trial: 192. Best value: 0.949632:  42%|████▏     | 208/500 [03:26<04:21,  1.12it/s]

[I 2026-05-18 14:50:02,776] Trial 218 pruned.

Best trial: 192. Best value: 0.949632:  42%|████▏     | 210/500 [03:27<03:49,  1.26it/s]

[I 2026-05-18 14:50:04,195] Trial 213 pruned.
[I 2026-05-18 14:50:04,342] Trial 200 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00012591645597374984, 'l1_ratio': 0.9999584095820439, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.436959560958412e-05, 'max_iter': 3771}. Best is trial 192 with value: 0.9496324484453632.

Best trial: 192. Best value: 0.949632:  42%|████▏     | 212/500 [03:28<02:30,  1.91it/s]

[I 2026-05-18 14:50:04,745] Trial 212 pruned.
[I 2026-05-18 14:50:04,857] Trial 216 pruned.

Best trial: 208. Best value: 0.949633:  42%|████▏     | 212/500 [03:28<02:30,  1.91it/s]

[I 2026-05-18 14:50:04,952] Trial 208 finished with value: 0.9496331184893334 and parameters: {'solver': 'saga', 'C': 0.00015813586635123712, 'l1_ratio': 0.8276432907389577, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004053520185422894, 'max_iter': 3768}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  43%|████▎     | 214/500 [03:28<02:05,  2.28it/s]

[I 2026-05-18 14:50:05,523] Trial 217 pruned.

Best trial: 208. Best value: 0.949633:  43%|████▎     | 215/500 [03:29<02:12,  2.16it/s]

[I 2026-05-18 14:50:06,068] Trial 210 pruned.

Best trial: 208. Best value: 0.949633:  43%|████▎     | 216/500 [03:30<03:22,  1.40it/s]

[I 2026-05-18 14:50:07,504] Trial 225 pruned.

Best trial: 208. Best value: 0.949633:  43%|████▎     | 217/500 [03:31<02:56,  1.60it/s]

[I 2026-05-18 14:50:07,841] Trial 223 pruned.
[I 2026-05-18 14:50:07,912] Trial 215 pruned.

Best trial: 208. Best value: 0.949633:  44%|████▍     | 219/500 [03:32<03:03,  1.53it/s]

[I 2026-05-18 14:50:09,273] Trial 211 finished with value: 0.9496323802859983 and parameters: {'solver': 'saga', 'C': 0.00016851068797600174, 'l1_ratio': 0.8272276507161439, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006867942916574482, 'max_iter': 3819}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  44%|████▍     | 221/500 [03:34<02:56,  1.58it/s]

[I 2026-05-18 14:50:10,597] Trial 219 pruned.
[I 2026-05-18 14:50:10,695] Trial 209 finished with value: 0.9493531687866354 and parameters: {'solver': 'saga', 'C': 0.00018340916361988624, 'l1_ratio': 0.7803319391426106, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006581733885183325, 'max_iter': 3788}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  45%|████▍     | 223/500 [03:35<02:38,  1.75it/s]

[I 2026-05-18 14:50:11,712] Trial 222 pruned.
[I 2026-05-18 14:50:11,851] Trial 224 pruned.

Best trial: 208. Best value: 0.949633:  45%|████▍     | 224/500 [03:35<02:07,  2.16it/s]

[I 2026-05-18 14:50:12,035] Trial 214 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.3573041453862064e-05, 'l1_ratio': 0.9992843111290531, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003641875947043596, 'max_iter': 3747}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  45%|████▌     | 225/500 [03:35<01:50,  2.49it/s]

[I 2026-05-18 14:50:12,291] Trial 221 pruned.

Best trial: 208. Best value: 0.949633:  45%|████▌     | 227/500 [03:36<01:32,  2.96it/s]

[I 2026-05-18 14:50:12,692] Trial 220 pruned.
[I 2026-05-18 14:50:12,874] Trial 226 pruned.

Best trial: 208. Best value: 0.949633:  46%|████▌     | 228/500 [03:39<05:13,  1.15s/it]

[I 2026-05-18 14:50:15,969] Trial 227 pruned.

Best trial: 208. Best value: 0.949633:  46%|████▌     | 229/500 [03:39<04:21,  1.04it/s]

[I 2026-05-18 14:50:16,494] Trial 231 pruned.

Best trial: 208. Best value: 0.949633:  46%|████▌     | 230/500 [03:40<03:24,  1.32it/s]

[I 2026-05-18 14:50:16,758] Trial 228 pruned.

Best trial: 208. Best value: 0.949633:  46%|████▋     | 232/500 [03:40<02:12,  2.03it/s]

[I 2026-05-18 14:50:17,177] Trial 230 pruned.
[I 2026-05-18 14:50:17,287] Trial 229 pruned.

Best trial: 208. Best value: 0.949633:  47%|████▋     | 233/500 [03:41<03:05,  1.44it/s]

[I 2026-05-18 14:50:18,461] Trial 237 pruned.

Best trial: 208. Best value: 0.949633:  47%|████▋     | 234/500 [03:43<04:36,  1.04s/it]

[I 2026-05-18 14:50:20,303] Trial 235 pruned.

Best trial: 208. Best value: 0.949633:  47%|████▋     | 235/500 [03:44<04:04,  1.09it/s]

[I 2026-05-18 14:50:20,947] Trial 236 pruned.

Best trial: 208. Best value: 0.949633:  47%|████▋     | 236/500 [03:44<03:14,  1.36it/s]

[I 2026-05-18 14:50:21,252] Trial 232 pruned.

Best trial: 208. Best value: 0.949633:  47%|████▋     | 237/500 [03:45<02:53,  1.51it/s]

[I 2026-05-18 14:50:21,737] Trial 238 pruned.

Best trial: 208. Best value: 0.949633:  48%|████▊     | 238/500 [03:45<02:25,  1.79it/s]

[I 2026-05-18 14:50:22,042] Trial 234 pruned.

Best trial: 208. Best value: 0.949633:  48%|████▊     | 239/500 [03:46<03:34,  1.21it/s]

[I 2026-05-18 14:50:23,499] Trial 242 pruned.

Best trial: 208. Best value: 0.949633:  48%|████▊     | 240/500 [03:48<04:16,  1.01it/s]

[I 2026-05-18 14:50:24,864] Trial 233 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00010876131213105287, 'l1_ratio': 0.8547390053472379, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002507577159392391, 'max_iter': 3669}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  48%|████▊     | 242/500 [03:50<04:17,  1.00it/s]

[I 2026-05-18 14:50:27,159] Trial 241 pruned.
[I 2026-05-18 14:50:27,266] Trial 244 pruned.

Best trial: 208. Best value: 0.949633:  49%|████▊     | 243/500 [03:51<03:40,  1.16it/s]

[I 2026-05-18 14:50:27,806] Trial 239 pruned.

Best trial: 208. Best value: 0.949633:  49%|████▉     | 244/500 [03:51<03:24,  1.25it/s]

[I 2026-05-18 14:50:28,458] Trial 243 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 5.807023742069725e-05, 'l1_ratio': 0.8170760275839569, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0018674808402111352, 'max_iter': 4254}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  49%|████▉     | 245/500 [03:52<03:33,  1.20it/s]

[I 2026-05-18 14:50:29,386] Trial 246 pruned.

Best trial: 208. Best value: 0.949633:  49%|████▉     | 246/500 [03:53<03:30,  1.21it/s]

[I 2026-05-18 14:50:30,197] Trial 240 finished with value: 0.949624214301202 and parameters: {'solver': 'saga', 'C': 0.03325118247878122, 'l1_ratio': 0.7256731391723766, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00025007292958461734, 'max_iter': 3945}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  49%|████▉     | 247/500 [03:55<04:30,  1.07s/it]

[I 2026-05-18 14:50:31,825] Trial 248 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.5180011760087542e-05, 'l1_ratio': 0.8154331802561462, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0019210501324947505, 'max_iter': 4228}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  50%|████▉     | 248/500 [03:56<04:11,  1.00it/s]

[I 2026-05-18 14:50:32,652] Trial 251 pruned.

Best trial: 208. Best value: 0.949633:  50%|████▉     | 249/500 [03:56<03:16,  1.28it/s]

[I 2026-05-18 14:50:32,943] Trial 247 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.500815370154231e-05, 'l1_ratio': 0.7616056956773993, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0018796471431587853, 'max_iter': 4201}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  50%|█████     | 250/500 [03:56<02:53,  1.44it/s]

[I 2026-05-18 14:50:33,425] Trial 249 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.716558954629273e-05, 'l1_ratio': 0.7613896897748819, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012262741980821007, 'max_iter': 4234}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  50%|█████     | 251/500 [03:57<03:19,  1.25it/s]

[I 2026-05-18 14:50:34,478] Trial 254 pruned.

Best trial: 208. Best value: 0.949633:  50%|█████     | 252/500 [03:58<03:34,  1.16it/s]

[I 2026-05-18 14:50:35,490] Trial 252 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.4027199693623944e-05, 'l1_ratio': 0.7721187220771535, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006259384495648278, 'max_iter': 4279}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  51%|█████     | 253/500 [04:00<04:21,  1.06s/it]

[I 2026-05-18 14:50:36,999] Trial 250 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.24981705158009e-05, 'l1_ratio': 0.8133588638863142, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0010347357474183826, 'max_iter': 4221}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  51%|█████     | 254/500 [04:00<03:18,  1.24it/s]

[I 2026-05-18 14:50:37,219] Trial 258 pruned.

Best trial: 208. Best value: 0.949633:  51%|█████     | 255/500 [04:02<04:08,  1.01s/it]

[I 2026-05-18 14:50:38,711] Trial 245 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 5.633040099879343e-05, 'l1_ratio': 0.7608012657557794, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 3.750066130424534e-05, 'max_iter': 4198}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  51%|█████     | 256/500 [04:02<03:19,  1.22it/s]

[I 2026-05-18 14:50:39,044] Trial 261 pruned.

Best trial: 208. Best value: 0.949633:  51%|█████▏    | 257/500 [04:02<02:54,  1.39it/s]

[I 2026-05-18 14:50:39,559] Trial 263 pruned.
[I 2026-05-18 14:50:39,636] Trial 257 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.0422049638121798e-05, 'l1_ratio': 0.797156700344025, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006949111091342481, 'max_iter': 1208}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  52%|█████▏    | 260/500 [04:04<01:59,  2.00it/s]

[I 2026-05-18 14:50:40,597] Trial 255 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.630684588688499e-05, 'l1_ratio': 0.7852959987711409, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006223093120427232, 'max_iter': 4408}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:50:40,685] Trial 256 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.2577510381464397e-05, 'l1_ratio': 0.7904920694084913, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0050354039114605745, 'max_iter': 4223}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  52%|█████▏    | 261/500 [04:04<02:23,  1.66it/s]

[I 2026-05-18 14:50:41,600] Trial 267 pruned.

Best trial: 208. Best value: 0.949633:  52%|█████▏    | 262/500 [04:05<02:07,  1.87it/s]

[I 2026-05-18 14:50:41,961] Trial 269 pruned.

Best trial: 208. Best value: 0.949633:  53%|█████▎    | 263/500 [04:06<02:21,  1.67it/s]

[I 2026-05-18 14:50:42,725] Trial 268 pruned.
[I 2026-05-18 14:50:42,816] Trial 260 finished with value: 0.859788304088943 and parameters: {'solver': 'saga', 'C': 1.5367010829286094e-05, 'l1_ratio': 0.7826435755745569, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006102904995558293, 'max_iter': 3019}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  53%|█████▎    | 265/500 [04:06<01:56,  2.02it/s]

[I 2026-05-18 14:50:43,451] Trial 270 pruned.

Best trial: 208. Best value: 0.949633:  53%|█████▎    | 266/500 [04:07<01:40,  2.33it/s]

[I 2026-05-18 14:50:43,672] Trial 271 pruned.
[I 2026-05-18 14:50:43,692] Trial 253 pruned.

Best trial: 208. Best value: 0.949633:  54%|█████▎    | 268/500 [04:08<01:52,  2.06it/s]

[I 2026-05-18 14:50:44,810] Trial 265 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.121805037796716e-05, 'l1_ratio': 0.7911692698641817, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.009387921114869326, 'max_iter': 1179}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  54%|█████▍    | 269/500 [04:08<01:41,  2.28it/s]

[I 2026-05-18 14:50:45,043] Trial 278 pruned.

Best trial: 208. Best value: 0.949633:  54%|█████▍    | 270/500 [04:09<01:50,  2.08it/s]

[I 2026-05-18 14:50:45,697] Trial 277 pruned.

Best trial: 208. Best value: 0.949633:  54%|█████▍    | 271/500 [04:10<02:29,  1.53it/s]

[I 2026-05-18 14:50:46,836] Trial 279 pruned.

Best trial: 208. Best value: 0.949633:  55%|█████▍    | 273/500 [04:10<01:46,  2.13it/s]

[I 2026-05-18 14:50:47,281] Trial 262 finished with value: 0.8596438600798798 and parameters: {'solver': 'saga', 'C': 1.6670657153583226e-05, 'l1_ratio': 0.7919554083013334, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0008276583900434674, 'max_iter': 2965}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:50:47,426] Trial 259 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.4771946893059009e-05, 'l1_ratio': 0.7952128332769492, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006702517877570636, 'max_iter': 4407}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  55%|█████▍    | 274/500 [04:15<06:15,  1.66s/it]

[I 2026-05-18 14:50:52,087] Trial 264 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.517967233794299e-05, 'l1_ratio': 0.7914284033116643, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004470452666747864, 'max_iter': 4456}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  55%|█████▌    | 275/500 [04:16<05:15,  1.40s/it]

[I 2026-05-18 14:50:52,847] Trial 272 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.820346321076814e-05, 'l1_ratio': 0.8772159599797901, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007885310350097784, 'max_iter': 4916}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  55%|█████▌    | 277/500 [04:18<04:21,  1.17s/it]

[I 2026-05-18 14:50:54,877] Trial 284 pruned.
[I 2026-05-18 14:50:55,070] Trial 274 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.1200803114976214e-05, 'l1_ratio': 0.8269716123094081, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014208575726646197, 'max_iter': 3025}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  56%|█████▌    | 278/500 [04:19<04:01,  1.09s/it]

[I 2026-05-18 14:50:55,957] Trial 283 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.25759665558993e-05, 'l1_ratio': 0.8132832642463301, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0037142690577483812, 'max_iter': 4009}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  56%|█████▌    | 279/500 [04:20<04:11,  1.14s/it]

[I 2026-05-18 14:50:57,209] Trial 281 finished with value: 0.9493647116110729 and parameters: {'solver': 'saga', 'C': 2.8600355763322892e-05, 'l1_ratio': 0.5887179789491153, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003553417111334389, 'max_iter': 4018}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  56%|█████▌    | 281/500 [04:20<02:25,  1.51it/s]

[I 2026-05-18 14:50:57,471] Trial 280 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.917620354645723e-05, 'l1_ratio': 0.8750864163296865, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0015119917613458805, 'max_iter': 3390}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:50:57,620] Trial 273 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.439253314717107e-05, 'l1_ratio': 0.8181185921130958, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00010334477770985304, 'max_iter': 3387}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  57%|█████▋    | 283/500 [04:22<02:09,  1.68it/s]

[I 2026-05-18 14:50:58,733] Trial 282 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.9164409295339077e-05, 'l1_ratio': 0.8171567677197185, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0013936775834751574, 'max_iter': 3992}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:50:58,859] Trial 276 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.08426980225784e-05, 'l1_ratio': 0.9563549612730243, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00017573260438659159, 'max_iter': 4114}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  57%|█████▋    | 284/500 [04:23<02:51,  1.26it/s]

[I 2026-05-18 14:51:00,126] Trial 275 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.9832564468464966e-05, 'l1_ratio': 0.8307684492824318, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.983025426701577e-05, 'max_iter': 2732}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  57%|█████▋    | 285/500 [04:25<04:12,  1.17s/it]

[I 2026-05-18 14:51:02,179] Trial 266 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.9894926521675105e-05, 'l1_ratio': 0.9184594147611986, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.5256071647493501e-06, 'max_iter': 3384}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  57%|█████▋    | 286/500 [04:28<06:04,  1.70s/it]

[I 2026-05-18 14:51:05,115] Trial 286 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.8932906546285228e-05, 'l1_ratio': 0.8166494298714191, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014344255642158234, 'max_iter': 4021}. Best is trial 208 with value: 0.9496331184893334.

[I 2026-05-18 14:51:08,121] Trial 294 pruned.
[I 2026-05-18 14:51:08,257] Trial 293 pruned.

Best trial: 208. Best value: 0.949633:  58%|█████▊    | 288/500 [04:31<05:19,  1.50s/it]

[I 2026-05-18 14:51:08,332] Trial 290 pruned.

Best trial: 208. Best value: 0.949633:  58%|█████▊    | 290/500 [04:32<03:14,  1.08it/s]

[I 2026-05-18 14:51:08,762] Trial 289 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 5.395933021990855e-05, 'l1_ratio': 0.8225744129636436, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0004446807022047055, 'max_iter': 4812}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  58%|█████▊    | 291/500 [04:32<02:55,  1.19it/s]

[I 2026-05-18 14:51:09,351] Trial 285 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.0165083742140436e-05, 'l1_ratio': 0.8312179408832674, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.0073552356018955e-05, 'max_iter': 2772}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  58%|█████▊    | 292/500 [04:33<02:55,  1.18it/s]

[I 2026-05-18 14:51:10,206] Trial 291 pruned.

Best trial: 208. Best value: 0.949633:  59%|█████▊    | 293/500 [04:34<02:48,  1.23it/s]

[I 2026-05-18 14:51:10,937] Trial 288 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.0367019682043687e-05, 'l1_ratio': 0.8158481360918893, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00011594364018977356, 'max_iter': 4826}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  59%|█████▉    | 294/500 [04:35<03:20,  1.03it/s]

[I 2026-05-18 14:51:12,323] Trial 287 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.924923408397803e-05, 'l1_ratio': 0.8181587937056516, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.887623355286478e-05, 'max_iter': 2775}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  59%|█████▉    | 295/500 [04:36<02:49,  1.21it/s]

[I 2026-05-18 14:51:12,783] Trial 292 pruned.

Best trial: 208. Best value: 0.949633:  59%|█████▉    | 296/500 [04:38<04:36,  1.36s/it]

[I 2026-05-18 14:51:15,433] Trial 303 pruned.

Best trial: 208. Best value: 0.949633:  60%|█████▉    | 298/500 [04:39<02:50,  1.19it/s]

[I 2026-05-18 14:51:16,004] Trial 300 pruned.
[I 2026-05-18 14:51:16,173] Trial 296 finished with value: 0.9494603321473616 and parameters: {'solver': 'saga', 'C': 0.0038822416498565304, 'l1_ratio': 0.7302799161930127, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00030550096664136136, 'max_iter': 3733}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  60%|█████▉    | 299/500 [04:40<02:50,  1.18it/s]

[I 2026-05-18 14:51:17,028] Trial 295 pruned.

Best trial: 208. Best value: 0.949633:  60%|██████    | 300/500 [04:43<04:54,  1.47s/it]

[I 2026-05-18 14:51:19,975] Trial 301 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.991743258115237e-05, 'l1_ratio': 0.8348127017698359, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0027792482460347327, 'max_iter': 3215}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  60%|██████    | 301/500 [04:43<03:57,  1.20s/it]

[I 2026-05-18 14:51:20,518] Trial 304 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.969807158852127e-05, 'l1_ratio': 0.672049363541729, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0028335032235287305, 'max_iter': 3857}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  60%|██████    | 302/500 [04:44<03:08,  1.05it/s]

[I 2026-05-18 14:51:20,897] Trial 299 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.93628077568546e-05, 'l1_ratio': 0.6758654713335633, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0023430695279332715, 'max_iter': 3843}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  61%|██████    | 303/500 [04:45<03:22,  1.03s/it]

[I 2026-05-18 14:51:22,107] Trial 297 pruned.

Best trial: 208. Best value: 0.949633:  61%|██████    | 304/500 [04:47<04:07,  1.26s/it]

[I 2026-05-18 14:51:23,911] Trial 306 finished with value: 0.9492172340381699 and parameters: {'solver': 'saga', 'C': 0.00014464188022600394, 'l1_ratio': 0.6968449735168145, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00227158875140198, 'max_iter': 3836}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  61%|██████    | 305/500 [04:51<06:41,  2.06s/it]

[I 2026-05-18 14:51:27,843] Trial 309 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.022502258104498e-05, 'l1_ratio': 0.9686675749420889, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004814834343643594, 'max_iter': 4333}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  61%|██████    | 306/500 [04:52<05:34,  1.72s/it]

[I 2026-05-18 14:51:28,777] Trial 308 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.1999805334745397e-05, 'l1_ratio': 0.9692992368156907, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0023627129613626183, 'max_iter': 4347}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  62%|██████▏   | 308/500 [04:52<03:04,  1.04it/s]

[I 2026-05-18 14:51:29,076] Trial 310 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.9990146138244836e-05, 'l1_ratio': 0.9669695480106703, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0023320440544145403, 'max_iter': 3548}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:51:29,250] Trial 307 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.9796302262900342e-05, 'l1_ratio': 0.6778779761418258, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001002613798721731, 'max_iter': 1701}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  62%|██████▏   | 309/500 [04:53<02:54,  1.10it/s]

[I 2026-05-18 14:51:30,051] Trial 314 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 8.17907313610117e-05, 'l1_ratio': 0.9786012402144257, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005265886102051037, 'max_iter': 4334}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  62%|██████▏   | 310/500 [04:54<02:40,  1.18it/s]

[I 2026-05-18 14:51:30,745] Trial 313 finished with value: 0.949608831123491 and parameters: {'solver': 'saga', 'C': 0.00015946050322149634, 'l1_ratio': 0.7607610184290878, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004273362718194602, 'max_iter': 4324}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  62%|██████▏   | 311/500 [04:56<03:55,  1.24s/it]

[I 2026-05-18 14:51:32,915] Trial 315 finished with value: 0.9496326618703907 and parameters: {'solver': 'saga', 'C': 8.172287788714406e-05, 'l1_ratio': 0.7724042839821391, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0043012972032200085, 'max_iter': 4359}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:51:32,919] Trial 305 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.0005385468278315302, 'l1_ratio': 0.9679343297730311, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.314719295702884e-06, 'max_iter': 3821}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  63%|██████▎   | 313/500 [04:57<02:50,  1.10it/s]

[I 2026-05-18 14:51:33,971] Trial 298 finished with value: 0.9496185013098675 and parameters: {'solver': 'saga', 'C': 13.202256231012045, 'l1_ratio': 0.8356307318949945, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.5307292678051588e-06, 'max_iter': 3824}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  63%|██████▎   | 314/500 [04:59<03:36,  1.16s/it]

[I 2026-05-18 14:51:35,898] Trial 302 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.948933238024857e-05, 'l1_ratio': 0.839319582023105, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.226939189876044e-06, 'max_iter': 3873}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  63%|██████▎   | 315/500 [04:59<03:03,  1.01it/s]

[I 2026-05-18 14:51:36,395] Trial 312 pruned.

Best trial: 208. Best value: 0.949633:  63%|██████▎   | 316/500 [05:00<02:36,  1.18it/s]

[I 2026-05-18 14:51:36,870] Trial 320 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 8.447230574068295e-05, 'l1_ratio': 0.9349943731441803, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004158768393766667, 'max_iter': 3952}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  63%|██████▎   | 317/500 [05:00<02:17,  1.33it/s]

[I 2026-05-18 14:51:37,376] Trial 323 pruned.

Best trial: 208. Best value: 0.949633:  64%|██████▎   | 318/500 [05:01<02:32,  1.19it/s]

[I 2026-05-18 14:51:38,418] Trial 316 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 8.306748447010312e-05, 'l1_ratio': 0.7696536673595329, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0009895263664143244, 'max_iter': 3584}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  64%|██████▍   | 319/500 [05:02<02:52,  1.05it/s]

[I 2026-05-18 14:51:39,649] Trial 324 pruned.

Best trial: 208. Best value: 0.949633:  64%|██████▍   | 320/500 [05:03<02:30,  1.20it/s]

[I 2026-05-18 14:51:40,202] Trial 317 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 8.36569124847014e-05, 'l1_ratio': 0.7687931860289299, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00048578994901403693, 'max_iter': 3940}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  64%|██████▍   | 321/500 [05:04<02:31,  1.18it/s]

[I 2026-05-18 14:51:41,076] Trial 322 pruned.

Best trial: 208. Best value: 0.949633:  65%|██████▍   | 323/500 [05:07<02:52,  1.03it/s]

[I 2026-05-18 14:51:43,531] Trial 327 pruned.
[I 2026-05-18 14:51:43,681] Trial 311 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 8.404017440433746e-05, 'l1_ratio': 0.766392202049388, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.2443025553001865e-06, 'max_iter': 4314}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:51:43,683] Trial 318 pruned.

Best trial: 208. Best value: 0.949633:  65%|██████▌   | 325/500 [05:08<02:11,  1.33it/s]

[I 2026-05-18 14:51:44,668] Trial 326 pruned.

Best trial: 208. Best value: 0.949633:  65%|██████▌   | 326/500 [05:09<02:48,  1.03it/s]

[I 2026-05-18 14:51:46,283] Trial 319 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 7.88078070374967e-05, 'l1_ratio': 0.7694217206656709, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.490221774907323e-06, 'max_iter': 3146}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  66%|██████▌   | 328/500 [05:11<02:35,  1.11it/s]

[I 2026-05-18 14:51:48,071] Trial 330 pruned.
[I 2026-05-18 14:51:48,240] Trial 321 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 8.191913617350898e-05, 'l1_ratio': 0.7761609481807299, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 2.5585514917683843e-05, 'max_iter': 3929}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  66%|██████▌   | 329/500 [05:11<02:10,  1.31it/s]

[I 2026-05-18 14:51:48,648] Trial 325 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 9.97093870039044e-05, 'l1_ratio': 0.7694424273040645, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000620181761751282, 'max_iter': 4185}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  66%|██████▌   | 330/500 [05:12<01:46,  1.60it/s]

[I 2026-05-18 14:51:48,925] Trial 328 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00016907308933736145, 'l1_ratio': 0.870446683221035, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000637341668870039, 'max_iter': 4165}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  66%|██████▌   | 331/500 [05:13<01:55,  1.46it/s]

[I 2026-05-18 14:51:49,752] Trial 329 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00016269704800719612, 'l1_ratio': 0.8700662845515346, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005775601765641721, 'max_iter': 4134}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  66%|██████▋   | 332/500 [05:14<02:22,  1.18it/s]

[I 2026-05-18 14:51:50,973] Trial 341 pruned.

Best trial: 208. Best value: 0.949633:  67%|██████▋   | 333/500 [05:14<02:01,  1.37it/s]

[I 2026-05-18 14:51:51,444] Trial 334 pruned.

Best trial: 208. Best value: 0.949633:  67%|██████▋   | 334/500 [05:16<02:28,  1.12it/s]

[I 2026-05-18 14:51:52,722] Trial 332 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00012725596003893978, 'l1_ratio': 0.8682227244459474, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006438107258178144, 'max_iter': 4294}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  67%|██████▋   | 335/500 [05:16<02:09,  1.27it/s]

[I 2026-05-18 14:51:53,248] Trial 331 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.0001281113124792817, 'l1_ratio': 0.86714376778209, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00019943875673758833, 'max_iter': 4633}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  67%|██████▋   | 336/500 [05:18<02:40,  1.02it/s]

[I 2026-05-18 14:51:54,678] Trial 333 finished with value: 0.949632468291288 and parameters: {'solver': 'saga', 'C': 0.00013228003007214885, 'l1_ratio': 0.8056373061920399, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000720405774392676, 'max_iter': 4406}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  67%|██████▋   | 337/500 [05:18<02:35,  1.05it/s]

[I 2026-05-18 14:51:55,582] Trial 336 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.0001533783046488508, 'l1_ratio': 0.9051652108935054, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006774239285387957, 'max_iter': 4402}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  68%|██████▊   | 338/500 [05:20<02:51,  1.06s/it]

[I 2026-05-18 14:51:56,890] Trial 335 finished with value: 0.9495519892006425 and parameters: {'solver': 'saga', 'C': 0.00017932539189431781, 'l1_ratio': 0.8698771454253731, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006728860745702286, 'max_iter': 4094}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  68%|██████▊   | 339/500 [05:22<03:36,  1.34s/it]

[I 2026-05-18 14:51:58,897] Trial 338 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.0001213319405378892, 'l1_ratio': 0.8680656297927016, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005912425790732376, 'max_iter': 4385}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:51:58,917] Trial 339 finished with value: 0.9496325253889898 and parameters: {'solver': 'saga', 'C': 0.0001733814968776132, 'l1_ratio': 0.8744872507589122, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005966351469931539, 'max_iter': 4381}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  68%|██████▊   | 341/500 [05:22<02:16,  1.17it/s]

[I 2026-05-18 14:51:59,473] Trial 337 pruned.

Best trial: 208. Best value: 0.949633:  68%|██████▊   | 342/500 [05:23<02:02,  1.29it/s]

[I 2026-05-18 14:52:00,003] Trial 342 pruned.

Best trial: 208. Best value: 0.949633:  69%|██████▊   | 343/500 [05:25<02:38,  1.01s/it]

[I 2026-05-18 14:52:01,662] Trial 344 pruned.

Best trial: 208. Best value: 0.949633:  69%|██████▉   | 344/500 [05:25<02:13,  1.17it/s]

[I 2026-05-18 14:52:02,108] Trial 346 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.259351121118593e-05, 'l1_ratio': 0.9016724314009994, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0017955211934949028, 'max_iter': 3706}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  69%|██████▉   | 345/500 [05:25<01:55,  1.34it/s]

[I 2026-05-18 14:52:02,583] Trial 345 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.3023695532689296e-05, 'l1_ratio': 0.9022617942095355, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005471034728667414, 'max_iter': 4460}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  69%|██████▉   | 346/500 [05:28<03:05,  1.20s/it]

[I 2026-05-18 14:52:04,927] Trial 340 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.0001599932346231362, 'l1_ratio': 0.9010262597475076, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 4.2789116390925794e-05, 'max_iter': 4047}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  69%|██████▉   | 347/500 [05:28<02:25,  1.05it/s]

[I 2026-05-18 14:52:05,264] Trial 347 pruned.

Best trial: 208. Best value: 0.949633:  70%|██████▉   | 348/500 [05:29<02:09,  1.17it/s]

[I 2026-05-18 14:52:05,879] Trial 350 pruned.

Best trial: 208. Best value: 0.949633:  70%|██████▉   | 349/500 [05:29<02:02,  1.24it/s]

[I 2026-05-18 14:52:06,582] Trial 348 pruned.

Best trial: 208. Best value: 0.949633:  70%|███████   | 350/500 [05:30<01:46,  1.41it/s]

[I 2026-05-18 14:52:07,060] Trial 343 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.455335649938661e-05, 'l1_ratio': 0.7995150486454209, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 4.686980482600667e-05, 'max_iter': 4409}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  70%|███████   | 351/500 [05:31<01:42,  1.45it/s]

[I 2026-05-18 14:52:07,691] Trial 352 pruned.

Best trial: 208. Best value: 0.949633:  70%|███████   | 352/500 [05:31<01:42,  1.45it/s]

[I 2026-05-18 14:52:08,387] Trial 349 pruned.

Best trial: 208. Best value: 0.949633:  71%|███████   | 353/500 [05:32<01:44,  1.40it/s]

[I 2026-05-18 14:52:09,155] Trial 354 pruned.

Best trial: 208. Best value: 0.949633:  71%|███████   | 354/500 [05:32<01:33,  1.56it/s]

[I 2026-05-18 14:52:09,618] Trial 351 pruned.

Best trial: 208. Best value: 0.949633:  71%|███████   | 355/500 [05:34<01:57,  1.23it/s]

[I 2026-05-18 14:52:10,843] Trial 362 pruned.

Best trial: 208. Best value: 0.949633:  71%|███████   | 356/500 [05:34<01:44,  1.38it/s]

[I 2026-05-18 14:52:11,359] Trial 364 pruned.

Best trial: 208. Best value: 0.949633:  71%|███████▏  | 357/500 [05:35<01:51,  1.28it/s]

[I 2026-05-18 14:52:12,267] Trial 353 finished with value: 0.9494643034360137 and parameters: {'solver': 'saga', 'C': 0.000908234205900024, 'l1_ratio': 0.8933356956042197, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0004976255092999443, 'max_iter': 3682}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  72%|███████▏  | 358/500 [05:36<02:03,  1.15it/s]

[I 2026-05-18 14:52:13,338] Trial 365 pruned.

Best trial: 208. Best value: 0.949633:  72%|███████▏  | 360/500 [05:37<01:30,  1.55it/s]

[I 2026-05-18 14:52:14,179] Trial 366 pruned.
[I 2026-05-18 14:52:14,323] Trial 356 finished with value: 0.9495198166797885 and parameters: {'solver': 'saga', 'C': 0.008954811977528107, 'l1_ratio': 0.5544458182541765, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008472425310487948, 'max_iter': 4533}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  72%|███████▏  | 361/500 [05:37<01:10,  1.97it/s]

[I 2026-05-18 14:52:14,512] Trial 359 pruned.

Best trial: 208. Best value: 0.949633:  72%|███████▏  | 362/500 [05:38<00:58,  2.35it/s]

[I 2026-05-18 14:52:14,719] Trial 358 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00025742925402955563, 'l1_ratio': 0.9997925442790788, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00048701114154757106, 'max_iter': 4576}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  73%|███████▎  | 363/500 [05:38<00:52,  2.63it/s]

[I 2026-05-18 14:52:15,022] Trial 361 pruned.

Best trial: 208. Best value: 0.949633:  73%|███████▎  | 364/500 [05:40<01:58,  1.15it/s]

[I 2026-05-18 14:52:17,044] Trial 360 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.0002992109920607955, 'l1_ratio': 0.9974911525598642, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0003336502995537749, 'max_iter': 4292}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  73%|███████▎  | 365/500 [05:42<03:01,  1.34s/it]

[I 2026-05-18 14:52:19,479] Trial 367 pruned.
[I 2026-05-18 14:52:19,575] Trial 373 pruned.

Best trial: 208. Best value: 0.949633:  74%|███████▎  | 368/500 [05:43<01:30,  1.46it/s]

[I 2026-05-18 14:52:20,036] Trial 371 pruned.
[I 2026-05-18 14:52:20,206] Trial 355 finished with value: 0.9496323675976341 and parameters: {'solver': 'saga', 'C': 0.005885968662593827, 'l1_ratio': 0.9971203282779292, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.029969123437328e-06, 'max_iter': 4460}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  74%|███████▍  | 369/500 [05:43<01:17,  1.69it/s]

[I 2026-05-18 14:52:20,546] Trial 357 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.3635098582123414e-05, 'l1_ratio': 0.5461495481067005, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008752800670134388, 'max_iter': 4493}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  74%|███████▍  | 370/500 [05:44<01:19,  1.63it/s]

[I 2026-05-18 14:52:21,218] Trial 369 pruned.

Best trial: 208. Best value: 0.949633:  74%|███████▍  | 371/500 [05:44<01:11,  1.79it/s]

[I 2026-05-18 14:52:21,635] Trial 370 pruned.

Best trial: 208. Best value: 0.949633:  74%|███████▍  | 372/500 [05:45<01:09,  1.85it/s]

[I 2026-05-18 14:52:22,120] Trial 375 pruned.

Best trial: 208. Best value: 0.949633:  75%|███████▍  | 374/500 [05:46<01:06,  1.90it/s]

[I 2026-05-18 14:52:23,100] Trial 374 pruned.
[I 2026-05-18 14:52:23,292] Trial 382 pruned.

Best trial: 208. Best value: 0.949633:  75%|███████▌  | 375/500 [05:47<00:59,  2.08it/s]

[I 2026-05-18 14:52:23,659] Trial 383 pruned.

Best trial: 208. Best value: 0.949633:  75%|███████▌  | 376/500 [05:48<01:43,  1.20it/s]

[I 2026-05-18 14:52:25,330] Trial 377 pruned.

Best trial: 208. Best value: 0.949633:  75%|███████▌  | 377/500 [05:49<01:33,  1.31it/s]

[I 2026-05-18 14:52:25,934] Trial 368 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.5043589248723696e-05, 'l1_ratio': 0.7120601357870575, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007935689719954028, 'max_iter': 3819}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  76%|███████▌  | 378/500 [05:50<02:02,  1.00s/it]

[I 2026-05-18 14:52:27,487] Trial 379 pruned.

Best trial: 208. Best value: 0.949633:  76%|███████▌  | 379/500 [05:51<01:55,  1.05it/s]

[I 2026-05-18 14:52:28,337] Trial 378 pruned.

Best trial: 208. Best value: 0.949633:  76%|███████▌  | 381/500 [05:52<01:12,  1.65it/s]

[I 2026-05-18 14:52:28,818] Trial 384 pruned.
[I 2026-05-18 14:52:28,927] Trial 372 finished with value: 0.9495150607693674 and parameters: {'solver': 'saga', 'C': 0.00011300595106070666, 'l1_ratio': 0.7360965605728186, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00030769714038545267, 'max_iter': 3795}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  76%|███████▋  | 382/500 [05:52<00:54,  2.18it/s]

[I 2026-05-18 14:52:29,047] Trial 381 pruned.

Best trial: 208. Best value: 0.949633:  77%|███████▋  | 384/500 [05:54<01:19,  1.47it/s]

[I 2026-05-18 14:52:31,050] Trial 380 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00011767863491273993, 'l1_ratio': 0.8373827866107176, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0010714089857370454, 'max_iter': 3566}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:52:31,155] Trial 363 finished with value: 0.9496187972012665 and parameters: {'solver': 'saga', 'C': 1.0808083879819754, 'l1_ratio': 0.8424453552286497, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.801200844632522e-06, 'max_iter': 4265}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  77%|███████▋  | 385/500 [05:59<03:46,  1.97s/it]

[I 2026-05-18 14:52:36,151] Trial 389 finished with value: 0.9496321540092705 and parameters: {'solver': 'saga', 'C': 6.637070623740027e-05, 'l1_ratio': 0.7821874436595498, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002720674206976975, 'max_iter': 4208}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  77%|███████▋  | 386/500 [06:00<03:22,  1.78s/it]

[I 2026-05-18 14:52:37,489] Trial 393 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 6.632542161961705e-05, 'l1_ratio': 0.7886151402757635, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0030816821668138853, 'max_iter': 4221}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  77%|███████▋  | 387/500 [06:01<02:52,  1.53s/it]

[I 2026-05-18 14:52:38,435] Trial 386 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 5.973121711921954e-05, 'l1_ratio': 0.8192415371026104, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.527581854443913e-05, 'max_iter': 4211}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  78%|███████▊  | 388/500 [06:02<02:10,  1.17s/it]

[I 2026-05-18 14:52:38,766] Trial 376 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00011703489777004258, 'l1_ratio': 0.8463398531032061, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 4.653546214549972e-06, 'max_iter': 3787}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:52:38,834] Trial 390 pruned.

Best trial: 208. Best value: 0.949633:  78%|███████▊  | 390/500 [06:03<01:39,  1.11it/s]

[I 2026-05-18 14:52:39,952] Trial 387 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 6.209822295098367e-05, 'l1_ratio': 0.7836824090720468, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.408001825268296e-05, 'max_iter': 4361}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  78%|███████▊  | 391/500 [06:03<01:27,  1.24it/s]

[I 2026-05-18 14:52:40,464] Trial 394 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 6.409966224056925e-05, 'l1_ratio': 0.8170619752778624, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005320963257227653, 'max_iter': 4213}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  78%|███████▊  | 392/500 [06:04<01:24,  1.28it/s]

[I 2026-05-18 14:52:41,169] Trial 388 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 6.267177810577371e-05, 'l1_ratio': 0.7822098601813203, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.975596511655785e-05, 'max_iter': 3475}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  79%|███████▊  | 393/500 [06:05<01:19,  1.34it/s]

[I 2026-05-18 14:52:41,822] Trial 395 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 6.459421629532841e-05, 'l1_ratio': 0.790708725253353, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005589409284626004, 'max_iter': 4207}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  79%|███████▉  | 394/500 [06:05<01:09,  1.53it/s]

[I 2026-05-18 14:52:42,238] Trial 385 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.341544114526777e-05, 'l1_ratio': 0.8367319934981439, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 3.087679682192458e-05, 'max_iter': 3588}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  79%|███████▉  | 395/500 [06:07<01:39,  1.05it/s]

[I 2026-05-18 14:52:43,934] Trial 392 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 6.648526472741379e-05, 'l1_ratio': 0.7866093548387957, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.167688863376997e-05, 'max_iter': 4368}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  79%|███████▉  | 396/500 [06:07<01:22,  1.27it/s]

[I 2026-05-18 14:52:44,330] Trial 391 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 5.7511445959332395e-05, 'l1_ratio': 0.8175790720492391, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 3.214006303690354e-05, 'max_iter': 4224}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  79%|███████▉  | 397/500 [06:09<02:04,  1.21s/it]

[I 2026-05-18 14:52:46,541] Trial 396 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 6.429797188130662e-05, 'l1_ratio': 0.7828003525094868, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0030061130144418027, 'max_iter': 4377}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  80%|███████▉  | 398/500 [06:11<02:22,  1.40s/it]

[I 2026-05-18 14:52:48,395] Trial 400 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.690974897667157e-05, 'l1_ratio': 0.8118561377383511, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005752234244620039, 'max_iter': 4380}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  80%|███████▉  | 399/500 [06:12<01:49,  1.09s/it]

[I 2026-05-18 14:52:48,746] Trial 398 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.8292119010533348e-05, 'l1_ratio': 0.8161483478236808, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005602139829599998, 'max_iter': 4369}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  80%|████████  | 400/500 [06:13<01:58,  1.18s/it]

[I 2026-05-18 14:52:50,147] Trial 399 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.589613595782091e-05, 'l1_ratio': 0.8094011008722866, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005525657900825468, 'max_iter': 4367}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  80%|████████  | 401/500 [06:13<01:30,  1.10it/s]

[I 2026-05-18 14:52:50,419] Trial 408 pruned.

Best trial: 208. Best value: 0.949633:  80%|████████  | 402/500 [06:14<01:30,  1.09it/s]

[I 2026-05-18 14:52:51,367] Trial 401 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.593329520534341e-05, 'l1_ratio': 0.8189322767222882, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00519335377865334, 'max_iter': 3672}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  81%|████████  | 403/500 [06:15<01:13,  1.32it/s]

[I 2026-05-18 14:52:51,744] Trial 409 pruned.

Best trial: 208. Best value: 0.949633:  81%|████████  | 404/500 [06:17<02:00,  1.26s/it]

[I 2026-05-18 14:52:54,173] Trial 403 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.8689322846765434e-05, 'l1_ratio': 0.9549287561728089, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005684537206799729, 'max_iter': 4116}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  81%|████████  | 405/500 [06:18<01:50,  1.16s/it]

[I 2026-05-18 14:52:55,103] Trial 397 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.007094850404211e-05, 'l1_ratio': 0.8139958912839236, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.341632561838812e-05, 'max_iter': 4367}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  81%|████████  | 406/500 [06:20<02:04,  1.32s/it]

[I 2026-05-18 14:52:56,795] Trial 405 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.144612439368617e-05, 'l1_ratio': 0.8101949388153818, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001770010981044447, 'max_iter': 4092}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  81%|████████▏ | 407/500 [06:21<01:52,  1.21s/it]

[I 2026-05-18 14:52:57,743] Trial 410 pruned.

Best trial: 208. Best value: 0.949633:  82%|████████▏ | 408/500 [06:21<01:38,  1.07s/it]

[I 2026-05-18 14:52:58,505] Trial 406 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.144710847628318e-05, 'l1_ratio': 0.8082928184046325, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00016185225894352158, 'max_iter': 4085}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  82%|████████▏ | 409/500 [06:22<01:16,  1.18it/s]

[I 2026-05-18 14:52:58,813] Trial 402 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.9488224300218135e-05, 'l1_ratio': 0.8834407121784231, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 3.2769283632174636e-05, 'max_iter': 4117}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  82%|████████▏ | 410/500 [06:22<01:02,  1.45it/s]

[I 2026-05-18 14:52:59,142] Trial 407 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.7134059669540568e-05, 'l1_ratio': 0.8803196522471349, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003934480819257741, 'max_iter': 2898}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  82%|████████▏ | 411/500 [06:23<01:14,  1.19it/s]

[I 2026-05-18 14:53:00,336] Trial 404 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.8265786383625984e-05, 'l1_ratio': 0.9528878747218315, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 3.2457094981811795e-05, 'max_iter': 4108}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:53:00,437] Trial 412 pruned.

Best trial: 208. Best value: 0.949633:  83%|████████▎ | 413/500 [06:24<00:57,  1.50it/s]

[I 2026-05-18 14:53:01,253] Trial 415 pruned.

Best trial: 208. Best value: 0.949633:  83%|████████▎ | 414/500 [06:28<02:08,  1.49s/it]

[I 2026-05-18 14:53:05,263] Trial 418 pruned.

Best trial: 208. Best value: 0.949633:  83%|████████▎ | 416/500 [06:28<01:14,  1.13it/s]

[I 2026-05-18 14:53:05,480] Trial 419 pruned.
[I 2026-05-18 14:53:05,614] Trial 420 pruned.

Best trial: 208. Best value: 0.949633:  83%|████████▎ | 417/500 [06:29<01:15,  1.11it/s]

[I 2026-05-18 14:53:06,588] Trial 411 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.744773009898419e-05, 'l1_ratio': 0.9467309549612116, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004325171488231738, 'max_iter': 4998}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  84%|████████▎ | 418/500 [06:30<01:01,  1.33it/s]

[I 2026-05-18 14:53:06,965] Trial 416 finished with value: 0.9495600207199797 and parameters: {'solver': 'saga', 'C': 0.00017912791717767534, 'l1_ratio': 0.8848366671304102, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0008610613844440053, 'max_iter': 3864}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  84%|████████▍ | 419/500 [06:34<02:22,  1.76s/it]

[I 2026-05-18 14:53:11,209] Trial 423 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.550886724067999e-05, 'l1_ratio': 0.7678401933778944, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000945942301694328, 'max_iter': 3867}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  84%|████████▍ | 420/500 [06:34<01:45,  1.32s/it]

[I 2026-05-18 14:53:11,437] Trial 413 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.8994312161886556e-05, 'l1_ratio': 0.880952831586862, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.0567481317539926e-05, 'max_iter': 3870}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  84%|████████▍ | 421/500 [06:35<01:19,  1.01s/it]

[I 2026-05-18 14:53:11,714] Trial 414 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 3.845340236652187e-05, 'l1_ratio': 0.9258586103835478, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.0463691593046533e-05, 'max_iter': 2886}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  85%|████████▍ | 423/500 [06:35<00:52,  1.47it/s]

[I 2026-05-18 14:53:12,398] Trial 424 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 4.048885215509928e-05, 'l1_ratio': 0.76531918516128, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002102151102452617, 'max_iter': 3967}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:53:12,519] Trial 422 finished with value: 0.9491528623152755 and parameters: {'solver': 'saga', 'C': 0.0001855273500297386, 'l1_ratio': 0.7599970293263293, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0017587664503522424, 'max_iter': 3882}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  85%|████████▍ | 424/500 [06:36<00:39,  1.90it/s]

[I 2026-05-18 14:53:12,682] Trial 430 pruned.

Best trial: 208. Best value: 0.949633:  85%|████████▌ | 425/500 [06:36<00:45,  1.64it/s]

[I 2026-05-18 14:53:13,495] Trial 429 pruned.
[I 2026-05-18 14:53:13,589] Trial 431 pruned.

Best trial: 208. Best value: 0.949633:  85%|████████▌ | 427/500 [06:37<00:34,  2.10it/s]

[I 2026-05-18 14:53:14,132] Trial 417 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00017407873287270375, 'l1_ratio': 0.8747216211101868, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 9.11242000763027e-06, 'max_iter': 2904}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  86%|████████▌ | 428/500 [06:37<00:30,  2.33it/s]

[I 2026-05-18 14:53:14,420] Trial 433 pruned.

Best trial: 208. Best value: 0.949633:  86%|████████▌ | 429/500 [06:38<00:29,  2.43it/s]

[I 2026-05-18 14:53:14,783] Trial 427 pruned.

Best trial: 208. Best value: 0.949633:  86%|████████▌ | 430/500 [06:38<00:28,  2.43it/s]

[I 2026-05-18 14:53:15,193] Trial 425 pruned.

Best trial: 208. Best value: 0.949633:  86%|████████▌ | 431/500 [06:39<00:29,  2.32it/s]

[I 2026-05-18 14:53:15,679] Trial 436 pruned.

Best trial: 208. Best value: 0.949633:  87%|████████▋ | 433/500 [06:39<00:24,  2.75it/s]

[I 2026-05-18 14:53:16,199] Trial 439 pruned.
[I 2026-05-18 14:53:16,333] Trial 435 pruned.

Best trial: 208. Best value: 0.949633:  87%|████████▋ | 434/500 [06:39<00:22,  2.98it/s]

[I 2026-05-18 14:53:16,601] Trial 421 finished with value: 0.9493905967810997 and parameters: {'solver': 'saga', 'C': 0.00018150618864964317, 'l1_ratio': 0.7663797874044609, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000116817271003432, 'max_iter': 4985}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  87%|████████▋ | 435/500 [06:43<01:25,  1.31s/it]

[I 2026-05-18 14:53:20,255] Trial 428 finished with value: 0.9491740451713163 and parameters: {'solver': 'saga', 'C': 4.519239748312929e-05, 'l1_ratio': 0.8632800126220077, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000613525800094131, 'max_iter': 3979}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  87%|████████▋ | 436/500 [06:44<01:08,  1.08s/it]

[I 2026-05-18 14:53:20,761] Trial 437 pruned.
[I 2026-05-18 14:53:20,856] Trial 438 pruned.

Best trial: 208. Best value: 0.949633:  88%|████████▊ | 438/500 [06:46<01:06,  1.08s/it]

[I 2026-05-18 14:53:22,927] Trial 440 pruned.

Best trial: 208. Best value: 0.949633:  88%|████████▊ | 439/500 [06:46<00:54,  1.12it/s]

[I 2026-05-18 14:53:23,264] Trial 443 pruned.
[I 2026-05-18 14:53:23,357] Trial 426 finished with value: 0.9496190036425969 and parameters: {'solver': 'saga', 'C': 0.012535031354168651, 'l1_ratio': 0.7638724444064289, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.1227072975139333e-05, 'max_iter': 4774}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  88%|████████▊ | 441/500 [06:47<00:38,  1.52it/s]

[I 2026-05-18 14:53:23,905] Trial 442 pruned.

Best trial: 208. Best value: 0.949633:  88%|████████▊ | 442/500 [06:47<00:32,  1.76it/s]

[I 2026-05-18 14:53:24,168] Trial 432 finished with value: 0.9496246738128343 and parameters: {'solver': 'saga', 'C': 0.012797366421128586, 'l1_ratio': 0.8531172170117448, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0003571802561933475, 'max_iter': 3985}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  89%|████████▉ | 444/500 [06:47<00:21,  2.58it/s]

[I 2026-05-18 14:53:24,384] Trial 434 finished with value: 0.9495353919048315 and parameters: {'solver': 'saga', 'C': 0.0016010698536877213, 'l1_ratio': 0.8580288611737666, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003329215754073537, 'max_iter': 4790}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:53:24,502] Trial 441 pruned.

Best trial: 208. Best value: 0.949633:  89%|████████▉ | 445/500 [06:49<00:46,  1.17it/s]

[I 2026-05-18 14:53:26,610] Trial 450 pruned.

Best trial: 208. Best value: 0.949633:  89%|████████▉ | 446/500 [06:50<00:42,  1.28it/s]

[I 2026-05-18 14:53:27,202] Trial 452 pruned.

Best trial: 208. Best value: 0.949633:  89%|████████▉ | 447/500 [06:51<00:41,  1.29it/s]

[I 2026-05-18 14:53:27,966] Trial 454 pruned.

Best trial: 208. Best value: 0.949633:  90%|████████▉ | 448/500 [06:52<00:48,  1.07it/s]

[I 2026-05-18 14:53:29,301] Trial 445 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00010085885878320003, 'l1_ratio': 0.7955044629321069, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0004544052334279292, 'max_iter': 4299}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:53:29,371] Trial 448 pruned.

Best trial: 208. Best value: 0.949633:  90%|█████████ | 450/500 [06:53<00:36,  1.39it/s]

[I 2026-05-18 14:53:30,224] Trial 446 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00010102442016526811, 'l1_ratio': 0.8294028843835801, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007529935098088042, 'max_iter': 3719}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  90%|█████████ | 451/500 [06:54<00:31,  1.53it/s]

[I 2026-05-18 14:53:30,659] Trial 444 finished with value: 0.949347839817098 and parameters: {'solver': 'saga', 'C': 9.705019431802688e-05, 'l1_ratio': 0.7107989105597396, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0004719060486459497, 'max_iter': 4310}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:53:30,722] Trial 455 pruned.

Best trial: 208. Best value: 0.949633:  91%|█████████ | 454/500 [06:55<00:25,  1.82it/s]

[I 2026-05-18 14:53:31,985] Trial 447 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 9.533376193118568e-05, 'l1_ratio': 0.79571126509176, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00044737190287678035, 'max_iter': 4307}. Best is trial 208 with value: 0.9496331184893334.
[I 2026-05-18 14:53:32,161] Trial 453 finished with value: 0.949632749387666 and parameters: {'solver': 'saga', 'C': 0.00013466384408894558, 'l1_ratio': 0.8046272784018688, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.007559079652255556, 'max_iter': 3612}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  91%|█████████ | 455/500 [06:55<00:20,  2.21it/s]

[I 2026-05-18 14:53:32,325] Trial 449 pruned.

Best trial: 208. Best value: 0.949633:  91%|█████████ | 456/500 [06:57<00:36,  1.20it/s]

[I 2026-05-18 14:53:34,259] Trial 456 pruned.

Best trial: 208. Best value: 0.949633:  91%|█████████▏| 457/500 [06:58<00:34,  1.23it/s]

[I 2026-05-18 14:53:35,009] Trial 460 pruned.

Best trial: 208. Best value: 0.949633:  92%|█████████▏| 458/500 [06:58<00:27,  1.51it/s]

[I 2026-05-18 14:53:35,284] Trial 457 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00012496860021877416, 'l1_ratio': 0.8251352825294408, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.007167673440534179, 'max_iter': 4163}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  92%|█████████▏| 459/500 [06:59<00:26,  1.53it/s]

[I 2026-05-18 14:53:35,904] Trial 462 pruned.

Best trial: 208. Best value: 0.949633:  92%|█████████▏| 461/500 [07:00<00:23,  1.69it/s]

[I 2026-05-18 14:53:37,047] Trial 463 pruned.
[I 2026-05-18 14:53:37,147] Trial 451 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 1.7060733883804122e-05, 'l1_ratio': 0.7228609813611352, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007963583805429781, 'max_iter': 3310}. Best is trial 208 with value: 0.9496331184893334.

Best trial: 208. Best value: 0.949633:  92%|█████████▏| 462/500 [07:02<00:34,  1.09it/s]

[I 2026-05-18 14:53:38,843] Trial 464 pruned.

Best trial: 208. Best value: 0.949633:  93%|█████████▎| 463/500 [07:02<00:26,  1.40it/s]

[I 2026-05-18 14:53:39,076] Trial 467 pruned.

Best trial: 466. Best value: 0.949636:  93%|█████████▎| 464/500 [07:02<00:23,  1.54it/s]

[I 2026-05-18 14:53:39,559] Trial 466 finished with value: 0.9496364649677398 and parameters: {'solver': 'saga', 'C': 0.00013900263941740717, 'l1_ratio': 0.9094481647699592, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00926265679750946, 'max_iter': 3517}. Best is trial 466 with value: 0.9496364649677398.
[I 2026-05-18 14:53:39,587] Trial 458 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00013693540198477576, 'l1_ratio': 0.9113051869279087, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007600047103430991, 'max_iter': 4431}. Best is trial 466 with value: 0.9496364649677398.

Best trial: 466. Best value: 0.949636:  93%|█████████▎| 466/500 [07:04<00:21,  1.57it/s]

[I 2026-05-18 14:53:40,816] Trial 465 finished with value: 0.949465975873872 and parameters: {'solver': 'saga', 'C': 0.00013645686173594426, 'l1_ratio': 0.729855487650992, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00717303513000559, 'max_iter': 3483}. Best is trial 466 with value: 0.9496364649677398.

Best trial: 466. Best value: 0.949636:  93%|█████████▎| 467/500 [07:04<00:22,  1.48it/s]

[I 2026-05-18 14:53:41,594] Trial 470 pruned.

Best trial: 466. Best value: 0.949636:  94%|█████████▍| 469/500 [07:05<00:14,  2.12it/s]

[I 2026-05-18 14:53:41,974] Trial 461 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 2.1679778915505066e-05, 'l1_ratio': 0.7157247180872209, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002151754506829426, 'max_iter': 4451}. Best is trial 466 with value: 0.9496364649677398.
[I 2026-05-18 14:53:42,091] Trial 469 pruned.

Best trial: 466. Best value: 0.949636:  94%|█████████▍| 470/500 [07:05<00:11,  2.51it/s]

[I 2026-05-18 14:53:42,325] Trial 471 pruned.

Best trial: 466. Best value: 0.949636:  94%|█████████▍| 471/500 [07:07<00:22,  1.27it/s]

[I 2026-05-18 14:53:44,092] Trial 476 pruned.

Best trial: 466. Best value: 0.949636:  94%|█████████▍| 472/500 [07:08<00:21,  1.29it/s]

[I 2026-05-18 14:53:44,842] Trial 475 pruned.

Best trial: 466. Best value: 0.949636:  95%|█████████▍| 474/500 [07:08<00:14,  1.85it/s]

[I 2026-05-18 14:53:45,381] Trial 468 finished with value: 0.9494865457494089 and parameters: {'solver': 'saga', 'C': 0.00014158701718948013, 'l1_ratio': 0.7323952285651829, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006764369473560419, 'max_iter': 3277}. Best is trial 466 with value: 0.9496364649677398.
[I 2026-05-18 14:53:45,489] Trial 473 pruned.

Best trial: 466. Best value: 0.949636:  95%|█████████▌| 475/500 [07:09<00:14,  1.70it/s]

[I 2026-05-18 14:53:46,225] Trial 472 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00014277123920434622, 'l1_ratio': 0.9088521491517496, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004375308781941158, 'max_iter': 3821}. Best is trial 466 with value: 0.9496364649677398.
[I 2026-05-18 14:53:46,276] Trial 474 finished with value: 0.949631583846261 and parameters: {'solver': 'saga', 'C': 0.0001258653397625582, 'l1_ratio': 0.8054160931596713, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005820470104813484, 'max_iter': 3848}. Best is trial 466 with value: 0.9496364649677398.

Best trial: 466. Best value: 0.949636:  95%|█████████▌| 477/500 [07:10<00:10,  2.14it/s]

[I 2026-05-18 14:53:46,878] Trial 478 pruned.

Best trial: 466. Best value: 0.949636:  96%|█████████▌| 478/500 [07:10<00:08,  2.47it/s]

[I 2026-05-18 14:53:47,090] Trial 477 pruned.

Best trial: 466. Best value: 0.949636:  96%|█████████▌| 481/500 [07:11<00:05,  3.31it/s]

[I 2026-05-18 14:53:47,696] Trial 480 pruned.
[I 2026-05-18 14:53:47,794] Trial 481 pruned.
[I 2026-05-18 14:53:47,879] Trial 479 pruned.

Best trial: 466. Best value: 0.949636:  96%|█████████▋| 482/500 [07:12<00:11,  1.56it/s]

[I 2026-05-18 14:53:49,633] Trial 459 finished with value: 0.949371288402746 and parameters: {'solver': 'saga', 'C': 0.00014062118169346884, 'l1_ratio': 0.7169966489593576, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 2.5114032802614304e-05, 'max_iter': 4453}. Best is trial 466 with value: 0.9496364649677398.

Best trial: 466. Best value: 0.949636:  97%|█████████▋| 484/500 [07:14<00:09,  1.67it/s]

[I 2026-05-18 14:53:50,778] Trial 489 pruned.
[I 2026-05-18 14:53:50,909] Trial 484 pruned.

Best trial: 466. Best value: 0.949636:  97%|█████████▋| 485/500 [07:14<00:07,  2.01it/s]

[I 2026-05-18 14:53:51,133] Trial 485 pruned.

Best trial: 466. Best value: 0.949636:  97%|█████████▋| 486/500 [07:15<00:07,  1.98it/s]

[I 2026-05-18 14:53:51,660] Trial 482 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.0001598379191315147, 'l1_ratio': 0.8794466080338342, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.007782570603731565, 'max_iter': 3662}. Best is trial 466 with value: 0.9496364649677398.

Best trial: 466. Best value: 0.949636:  97%|█████████▋| 487/500 [07:15<00:05,  2.25it/s]

[I 2026-05-18 14:53:51,955] Trial 490 pruned.

Best trial: 466. Best value: 0.949636:  98%|█████████▊| 488/500 [07:16<00:07,  1.55it/s]

[I 2026-05-18 14:53:53,090] Trial 491 pruned.

Best trial: 466. Best value: 0.949636:  98%|█████████▊| 489/500 [07:16<00:06,  1.69it/s]

[I 2026-05-18 14:53:53,552] Trial 495 pruned.

Best trial: 466. Best value: 0.949636:  98%|█████████▊| 490/500 [07:17<00:04,  2.08it/s]

[I 2026-05-18 14:53:53,763] Trial 486 finished with value: 0.9492574670670264 and parameters: {'solver': 'saga', 'C': 0.0005247250106393108, 'l1_ratio': 0.8870210927523496, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.008381943442108348, 'max_iter': 3686}. Best is trial 466 with value: 0.9496364649677398.

Best trial: 466. Best value: 0.949636:  98%|█████████▊| 491/500 [07:17<00:04,  2.21it/s]

[I 2026-05-18 14:53:54,156] Trial 488 pruned.

Best trial: 466. Best value: 0.949636:  98%|█████████▊| 492/500 [07:17<00:03,  2.19it/s]

[I 2026-05-18 14:53:54,625] Trial 493 pruned.

Best trial: 466. Best value: 0.949636:  99%|█████████▉| 494/500 [07:18<00:02,  2.80it/s]

[I 2026-05-18 14:53:54,988] Trial 498 pruned.
[I 2026-05-18 14:53:55,176] Trial 492 pruned.

Best trial: 466. Best value: 0.949636:  99%|█████████▉| 495/500 [07:18<00:01,  2.71it/s]

[I 2026-05-18 14:53:55,573] Trial 497 pruned.

Best trial: 466. Best value: 0.949636:  99%|█████████▉| 496/500 [07:19<00:01,  2.52it/s]

[I 2026-05-18 14:53:56,036] Trial 487 pruned.

Best trial: 466. Best value: 0.949636:  99%|█████████▉| 497/500 [07:20<00:01,  2.08it/s]

[I 2026-05-18 14:53:56,709] Trial 494 finished with value: 0.9496169487411337 and parameters: {'solver': 'saga', 'C': 34.41849260301143, 'l1_ratio': 0.8380002355610601, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.009360512594852453, 'max_iter': 3659}. Best is trial 466 with value: 0.9496364649677398.

Best trial: 466. Best value: 0.949636: 100%|█████████▉| 498/500 [07:21<00:01,  1.23it/s]

[I 2026-05-18 14:53:58,306] Trial 483 finished with value: 0.9496323679229632 and parameters: {'solver': 'saga', 'C': 0.00016404646884609058, 'l1_ratio': 0.8079569954883311, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 2.319709986330781e-05, 'max_iter': 3641}. Best is trial 466 with value: 0.9496364649677398.

Best trial: 466. Best value: 0.949636: 100%|█████████▉| 499/500 [07:22<00:00,  1.12it/s]

[I 2026-05-18 14:53:59,387] Trial 499 pruned.

Best trial: 466. Best value: 0.949636: 100%|██████████| 500/500 [07:24<00:00,  1.12it/s]

[I 2026-05-18 14:54:01,357] Trial 496 pruned.
Best trial score:
0.9496364649677398

Best params:
{'solver': 'saga', 'C': 0.00013900263941740717, 'l1_ratio': 0.9094481647699592, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00926265679750946, 'max_iter': 3517}

## Train Dataset

In [26]:
cv = StratifiedKFold(shuffle=True, random_state=42, n_splits=5)

stacking_proba = cross_val_predict(
    LogisticRegression(**study.best_params), 
    X_train[features_to_use], 
    y_train.PitNextLap, 
    cv=cv, 
    n_jobs=-1, 
    method='predict_proba'
)[:, 1]

In [27]:
X_train_stacking = X_train.copy()
X_train_stacking['stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba'] = stacking_proba

# Test Dataset

In [28]:
stacking = LogisticRegression(**study.best_params).fit(X_train[features_to_use], y_train.PitNextLap)

In [29]:
X_test_stacking = X_test.copy()
X_test_stacking['stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba'] = stacking.predict_proba(X_test[features_to_use])[:, 1]

# Saving

In [31]:
X_test_stacking.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_lgbm_cat_xgb_hist_proba,stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,0.019849,0.509303
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,0.012173,0.505573
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,0.010304,0.504827
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.444558,0.696136
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.939648,0.852833

In [33]:
X_train_stacking.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_lgbm_cat_xgb_hist_proba,stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.868510,0.826590
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.772514,0.801335
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.717012,0.782757
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,0.005494,0.502476
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,0.482416,0.703165

In [32]:
X_train_stacking.to_parquet('../data/processed/X_train_stacking2.parquet')
X_test_stacking.to_parquet('../data/processed/X_test_stacking2.parquet')