# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

from scipy.special import expit

from sklearn.metrics import roc_auc_score
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import StackingClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split, cross_val_predict

from feature_engine.encoding import RareLabelEncoder
from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

In [3]:
def dump_pickle(file_obj, file_path):
    with open(file_path, 'bw') as file:
        pickle.dump(file_obj, file)


def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)


def voting_cross_val_predict(probas: list[np.ndarray], weights: np.ndarray[float]) -> np.ndarray[float]:
    weights /= weights.sum()
    return np.sum([proba * weight for proba, weight in zip(probas, weights)], axis=0)

# Loading Dataset

In [4]:
X_train_proba = pd.read_parquet('../data/processed/X_train_stacking.parquet').rename(columns={'knn_proba': 'pca_knn_proba'})
X_test_proba = pd.read_parquet('../data/processed/X_test_stacking.parquet').rename(columns={'knn_proba': 'pca_knn_proba'})

In [5]:
X_train = pd.read_parquet('../data/processed/X_train.parquet')
X_test = pd.read_parquet('../data/processed/X_test.parquet')

y_train = pd.read_parquet('../data/processed/y_train.parquet')

In [6]:
X_train_proba.head()

   lgbm_proba  cat_proba  xgb_proba  hist_proba  lg_proba  pca_knn_proba
0    0.802607   0.891870   0.895659    0.883947  0.808497       0.887454
1    0.649405   0.831360   0.829854    0.779541  0.689888       0.519966
2    0.505904   0.851809   0.751522    0.758911  0.558520       0.209855
3    0.001713   0.005910   0.007057    0.007298  0.002275       0.000000
4    0.392205   0.565506   0.489033    0.482967  0.414144       0.297043

In [7]:
X_train.head()

,driver,compound,race,year,pitstop,lapnumber,stint,tyrelife,position,laptime_s,...,treeraceprogress,treeposition,treelaptime_s,treecumulative_degradation,treeraceprogress_position,treeraceprogress_laptime_s,treeraceprogress_cumulative_degradation,treeposition_laptime_s,treeposition_cumulative_degradation,treelaptime_s_cumulative_degradation
id,,,,,,,,,,,,,,,,,,,,,
0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,...,0.298107,0.207392,0.252153,0.279021,0.298107,0.298107,0.321361,0.252153,0.279021,0.253721
1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,...,0.298107,0.185508,0.252153,0.586119,0.298107,0.298107,0.610176,0.252153,0.544023,0.613159
2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,...,0.298107,0.207392,0.252153,0.207676,0.298107,0.298107,0.423519,0.252153,0.228194,0.231339
3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,...,0.102471,0.185508,0.178575,0.138352,0.102471,0.102471,0.043550,0.178575,0.138352,0.070991
4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,...,0.298107,0.185508,0.178575,0.138352,0.298107,0.298107,0.206543,0.178575,0.138352,0.153276

# Feature Engineering

## Models

In [8]:
ridge = load_pickle('../models/model_ridge.pkl')
truncatedsvd_ridge = load_pickle('../models/model_truncatedsvd_ridge.pkl')

sgdclassifier = load_pickle('../models/model_sgdclassifier.pkl')
truncatedsvd_rbfsampler_sgdclassifier = load_pickle('../models/model_truncatedsvd_rbfsampler_sgdclassifier.pkl')
truncatedsvd_nystroem_sgdclassifier = load_pickle('../models/model_truncatedsvd_nystroem_sgdclassifier.pkl')

truncatedsvd_knn = load_pickle('../models/model_truncatedsvd_knn.pkl')
truncatedsvd_nystroem_knn = load_pickle('../models/model_truncatedsvd_nystroem_knn.pkl')
truncatedsvd_rbfsampler_knn = load_pickle('../models/model_truncatedsvd_rbfsampler_knn.pkl')

truncatedsvd_lgbm = load_pickle('../models/model_truncatedsvd_lgbm.pkl')

truncatedsvd_linear_svc = load_pickle('../models/model_truncatedsvd_linear_svc.pkl')

truncatedsvd_logistic_regression = load_pickle('../models/model_truncatedsvd_logistic_regression.pkl')
truncatedsvd_rbfsampler_logistic_regression = load_pickle('../models/model_truncatedsvd_rbfsampler_logistic_regression.pkl')
truncatedsvd_nystroem_logistic_regression = load_pickle('../models/model_truncatedsvd_nystroem_logistic_regression.pkl')

In [9]:
decision_function_dict = {
    'ridge': ridge, 
    'truncatedsvd_linear_svc': truncatedsvd_linear_svc, 
    'truncatedsvd_ridge': truncatedsvd_ridge
}

for model_name, model in decision_function_dict.items():

    print(f"using: {model_name}")

    X_train_proba[f'{model_name}_logit'] = cross_val_predict(model, X_train, y_train.PitNextLap,  cv=StratifiedKFold(shuffle=True), n_jobs=-1, method='decision_function')
    X_test_proba[f'{model_name}_logit'] = model.decision_function(X_test)

using: ridge
using: truncatedsvd_linear_svc

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but TruncatedSVD was fitted with feature names
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearSVC was fitted with feature names
  warnings.warn(

using: truncatedsvd_ridge

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [10]:
proba_dict = {
    'sgdclassifier': sgdclassifier,
    'truncatedsvd_lgbm': truncatedsvd_lgbm,
    'truncatedsvd_knn': truncatedsvd_knn,
    'truncatedsvd_nystroem_knn': truncatedsvd_nystroem_knn,
    'truncatedsvd_rbfsampler_knn': truncatedsvd_rbfsampler_knn,
    'truncatedsvd_logistic_regression': truncatedsvd_logistic_regression,
    'truncatedsvd_nystroem_logistic_regression': truncatedsvd_nystroem_logistic_regression,
    'truncatedsvd_nystroem_sgdclassifier': truncatedsvd_nystroem_sgdclassifier,
    'truncatedsvd_rbfsampler_logistic_regression': truncatedsvd_rbfsampler_logistic_regression,
    'truncatedsvd_rbfsampler_sgdclassifier': truncatedsvd_rbfsampler_sgdclassifier
}


for model_name, model in proba_dict.items():

    print(f"using: {model_name}")

    X_train_proba[f'{model_name}_proba'] = cross_val_predict(model, X_train, y_train.PitNextLap,  cv=StratifiedKFold(shuffle=True), n_jobs=-1, method='predict_proba')[:, 1]
    X_test_proba[f'{model_name}_proba'] = model.predict_proba(X_test)[:, 1]

using: sgdclassifier
using: truncatedsvd_lgbm

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

using: truncatedsvd_knn

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but TruncatedSVD was fitted with feature names
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

using: truncatedsvd_nystroem_knn
using: truncatedsvd_rbfsampler_knn
using: truncatedsvd_logistic_regression

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

using: truncatedsvd_nystroem_logistic_regression
using: truncatedsvd_nystroem_sgdclassifier
using: truncatedsvd_rbfsampler_logistic_regression
using: truncatedsvd_rbfsampler_sgdclassifier

## Voting Classifier

In [11]:
X_train_proba['voting_lgbm_and_cat_and_xgb_and_hist_proba'] = voting_cross_val_predict(
    [
        X_train_proba['lgbm_proba'],
        X_train_proba['cat_proba'],
        X_train_proba['xgb_proba'],
        X_train_proba['hist_proba']
    ], 
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

X_test_proba['voting_lgbm_and_cat_and_xgb_and_hist_proba'] = voting_cross_val_predict(
    [
        X_test_proba['lgbm_proba'],
        X_test_proba['cat_proba'],
        X_test_proba['xgb_proba'],
        X_test_proba['hist_proba']
    ],
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

In [12]:
column_name = (
    'voting',
    'lg',
    'ridge',
    'truncatedsvd_ridge',
    'sgdclassifier', 
    'truncatedsvd_logistic_regression',
    'truncatedsvd_nystroem_logistic_regression',
    'truncatedsvd_nystroem_sgdclassifier',
    'truncatedsvd_rbfsampler_logistic_regression',
    'truncatedsvd_rbfsampler_sgdclassifier'
)


X_train_proba['_and_'.join(column_name)] = voting_cross_val_predict(
    [
        X_train_proba['lg_proba'],
        X_train_proba['ridge_logit'].apply(expit),
        X_train_proba['truncatedsvd_ridge_logit'].apply(expit),
        X_train_proba['sgdclassifier_proba'],
        X_train_proba['truncatedsvd_logistic_regression_proba'],
        X_train_proba['truncatedsvd_nystroem_logistic_regression_proba'],
        X_train_proba['truncatedsvd_nystroem_sgdclassifier_proba'],
        X_train_proba['truncatedsvd_rbfsampler_logistic_regression_proba'],
        X_train_proba['truncatedsvd_rbfsampler_sgdclassifier_proba']
    ],
    weights=np.power(
        [
            0.8934924863693583, 
            0.8880861768599859, 
            0.8883182313760992,
            0.893129083108098,
            0.8937726214182687,
            0.8952558589759955,
            0.895307168953566,
            0.8814223922338199,
            0.8929350054167198
        ], 2)
)


X_test_proba['_and_'.join(column_name)] = voting_cross_val_predict(
    [
        X_test_proba['lg_proba'],
        X_test_proba['ridge_logit'].apply(expit),
        X_test_proba['truncatedsvd_ridge_logit'].apply(expit),
        X_test_proba['sgdclassifier_proba'],
        X_test_proba['truncatedsvd_logistic_regression_proba'],
        X_test_proba['truncatedsvd_nystroem_logistic_regression_proba'],
        X_test_proba['truncatedsvd_nystroem_sgdclassifier_proba'],
        X_test_proba['truncatedsvd_rbfsampler_logistic_regression_proba'],
        X_test_proba['truncatedsvd_rbfsampler_sgdclassifier_proba']
    ],
    weights=np.power(
        [
            0.8934924863693583, 
            0.8880861768599859, 
            0.8883182313760992,
            0.893129083108098,
            0.8937726214182687,
            0.8952558589759955,
            0.895307168953566,
            0.8814223922338199,
            0.8929350054167198
        ], 2)
)

In [13]:
X_train_proba['voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba'] = voting_cross_val_predict(
    [
        X_train_proba['truncatedsvd_nystroem_knn_proba'],
        X_train_proba['truncatedsvd_rbfsampler_knn_proba'],
        X_train_proba['truncatedsvd_knn_proba'],
        X_train_proba['pca_knn_proba']
    ],
    weights=np.power([0.9013407399373964, 0.9089648111229082, 0.9111399758749241, 0.8914149276506438], 2)
)


X_test_proba['voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba'] = voting_cross_val_predict(
    [
        X_test_proba['truncatedsvd_nystroem_knn_proba'],
        X_test_proba['truncatedsvd_rbfsampler_knn_proba'],
        X_test_proba['truncatedsvd_knn_proba'],
        X_test_proba['pca_knn_proba']
    ],
    weights=np.power([0.9013407399373964, 0.9089648111229082, 0.9111399758749241, 0.8914149276506438], 2)
)

In [14]:
X_test_proba.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_nystroem_knn_proba,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,-1.272709,-1.721325,-0.872993,0.005473,...,0.000000,0.0,0.006534,0.003712,0.009642,0.010313,0.000000,0.019849,0.061327,0.000000
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,-0.626960,-0.919863,-0.289991,0.054146,...,0.097699,0.1,0.063555,0.110500,0.044563,0.145672,0.047794,0.012173,0.144461,0.102869
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,-1.335019,-1.809246,-0.917667,0.003687,...,0.000000,0.0,0.004404,0.003123,0.008417,0.006856,0.000000,0.010304,0.057929,0.000000
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.190133,0.328363,0.387739,0.676445,...,0.000000,0.3,0.670446,0.712745,0.648495,0.504756,0.637237,0.444558,0.628242,0.183451
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.535153,0.644014,0.670147,0.852891,...,0.703383,0.8,0.835307,0.855796,0.796202,0.823601,0.787922,0.939648,0.787450,0.823541

# Machine Learning

In [16]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    # params = {
    #     "objective": "binary",
    #     "n_estimators": trial.suggest_int("n_estimators", 30, 300),
    #     "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.05, log=True),
    #     "max_depth": trial.suggest_int("max_depth", 1, 4),
    #     "num_leaves": trial.suggest_int("num_leaves", 2, 16),
    #     "min_child_samples": trial.suggest_int("min_child_samples", 20, 300),
    #     "subsample": trial.suggest_float("subsample", 0.6, 1.0),
    #     "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
    #     "reg_alpha": trial.suggest_float("reg_alpha", 1e-5, 100, log=True),
    #     "reg_lambda": trial.suggest_float("reg_lambda", 1e-5, 100, log=True),
    #     "verbosity": -1,
    # }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LGBMClassifier(
            objective='binary',
            metric='auc',
            boosting_type='gbdt',
            num_leaves=trial.suggest_int('num_leaves', 16, 256),
            max_depth=trial.suggest_int('max_depth', 3, 12),
            learning_rate=trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
            lambda_l1=trial.suggest_float('lambda_l1', 1e-3, 10.0, log=True),
            lambda_l2=trial.suggest_float('lambda_l2', 1e-3, 10.0, log=True),
            feature_fraction=trial.suggest_float('feature_fraction', 0.6, 1.0),
            bagging_fraction=trial.suggest_float('bagging_fraction', 0.6, 1.0),
            bagging_freq=trial.suggest_int('bagging_freq', 1, 7),
            min_child_samples=trial.suggest_int('min_child_samples', 10, 100),
            verbosity=-1,
            n_estimators=2000,
            random_state=42,
            n_jobs=1
        ).fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

features_to_use = [
    'voting_lgbm_and_cat_and_xgb_and_hist_proba', 
    '_and_'.join(column_name), 
    'voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba',
    'truncatedsvd_linear_svc_logit'
]

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train_proba[features_to_use], y_train), n_trials=200, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-24 00:14:38,652] A new study created in memory with name: no-name-829ff3fe-1764-4586-ad69-116a3756cd09
Best trial: 0. Best value: 0.949017:   0%|▌                                                                                                           | 1/200 [04:01<13:21:44, 241.73s/it]

[I 2026-05-24 00:18:40,380] Trial 0 finished with value: 0.9490166437446697 and parameters: {'num_leaves': 98, 'max_depth': 3, 'learning_rate': 0.15380286670651813, 'lambda_l1': 0.0370198118582365, 'lambda_l2': 2.005601492827561, 'feature_fraction': 0.7160773407541479, 'bagging_fraction': 0.8970142949814397, 'bagging_freq': 6, 'min_child_samples': 79}. Best is trial 0 with value: 0.9490166437446697.

Best trial: 0. Best value: 0.949017:   1%|█                                                                                                            | 2/200 [04:39<6:42:15, 121.90s/it]

[I 2026-05-24 00:19:18,392] Trial 8 finished with value: 0.9489232770633841 and parameters: {'num_leaves': 30, 'max_depth': 9, 'learning_rate': 0.045076123651945514, 'lambda_l1': 0.16174943321621266, 'lambda_l2': 0.9111062319420031, 'feature_fraction': 0.8123417369305744, 'bagging_fraction': 0.9462220838030863, 'bagging_freq': 7, 'min_child_samples': 21}. Best is trial 0 with value: 0.9490166437446697.

Best trial: 3. Best value: 0.949505:   2%|█▋                                                                                                            | 3/200 [04:49<3:51:43, 70.58s/it]

[I 2026-05-24 00:19:27,897] Trial 3 finished with value: 0.9495052723819294 and parameters: {'num_leaves': 142, 'max_depth': 4, 'learning_rate': 0.036551670135477235, 'lambda_l1': 0.051125880111730033, 'lambda_l2': 8.969694987159441, 'feature_fraction': 0.6946780001350837, 'bagging_fraction': 0.7688671274034556, 'bagging_freq': 6, 'min_child_samples': 62}. Best is trial 3 with value: 0.9495052723819294.

Best trial: 6. Best value: 0.949591:   2%|██▏                                                                                                           | 4/200 [05:04<2:39:21, 48.78s/it]

[I 2026-05-24 00:19:43,265] Trial 6 finished with value: 0.9495906468747443 and parameters: {'num_leaves': 18, 'max_depth': 5, 'learning_rate': 0.019199931272398225, 'lambda_l1': 1.2427086745113893, 'lambda_l2': 0.0010774256806470482, 'feature_fraction': 0.8537642649536988, 'bagging_fraction': 0.6261120697575661, 'bagging_freq': 2, 'min_child_samples': 21}. Best is trial 6 with value: 0.9495906468747443.

Best trial: 6. Best value: 0.949591:   2%|██▊                                                                                                           | 5/200 [05:54<2:40:05, 49.26s/it]

[I 2026-05-24 00:20:33,380] Trial 5 finished with value: 0.949217498462961 and parameters: {'num_leaves': 56, 'max_depth': 5, 'learning_rate': 0.030097452698473543, 'lambda_l1': 0.0093870331229258, 'lambda_l2': 0.05568927331505462, 'feature_fraction': 0.6135313219632325, 'bagging_fraction': 0.6855411613085943, 'bagging_freq': 2, 'min_child_samples': 45}. Best is trial 6 with value: 0.9495906468747443.

Best trial: 6. Best value: 0.949591:   3%|███▎                                                                                                          | 6/200 [06:40<2:35:57, 48.23s/it]

[I 2026-05-24 00:21:19,615] Trial 4 pruned.

Best trial: 6. Best value: 0.949591:   4%|███▊                                                                                                          | 7/200 [07:33<2:39:11, 49.49s/it]

[I 2026-05-24 00:22:11,697] Trial 10 pruned.

Best trial: 6. Best value: 0.949591:   4%|████▍                                                                                                         | 8/200 [07:53<2:08:22, 40.12s/it]

[I 2026-05-24 00:22:31,740] Trial 2 pruned.

Best trial: 6. Best value: 0.949591:   4%|████▉                                                                                                         | 9/200 [09:07<2:41:24, 50.70s/it]

[I 2026-05-24 00:23:45,722] Trial 12 finished with value: 0.9489297649055786 and parameters: {'num_leaves': 20, 'max_depth': 5, 'learning_rate': 0.04647549118745644, 'lambda_l1': 0.4404127498443672, 'lambda_l2': 0.07702816044177686, 'feature_fraction': 0.6870674633930296, 'bagging_fraction': 0.6104656960696927, 'bagging_freq': 4, 'min_child_samples': 63}. Best is trial 6 with value: 0.9495906468747443.

Best trial: 15. Best value: 0.949797:   5%|█████▍                                                                                                      | 10/200 [09:56<2:39:16, 50.30s/it]

[I 2026-05-24 00:24:35,113] Trial 15 finished with value: 0.9497967725111052 and parameters: {'num_leaves': 256, 'max_depth': 4, 'learning_rate': 0.011867301190130967, 'lambda_l1': 0.11960646762548013, 'lambda_l2': 1.1839389407684695, 'feature_fraction': 0.9144458128949313, 'bagging_fraction': 0.7643501793232008, 'bagging_freq': 6, 'min_child_samples': 18}. Best is trial 15 with value: 0.9497967725111052.

Best trial: 15. Best value: 0.949797:   6%|█████▉                                                                                                      | 11/200 [10:35<2:27:40, 46.88s/it]

[I 2026-05-24 00:25:14,255] Trial 16 finished with value: 0.9496341728389582 and parameters: {'num_leaves': 111, 'max_depth': 4, 'learning_rate': 0.02368950991194783, 'lambda_l1': 0.017340203464389612, 'lambda_l2': 0.004008002529440974, 'feature_fraction': 0.7867152861512843, 'bagging_fraction': 0.8233026532696177, 'bagging_freq': 5, 'min_child_samples': 29}. Best is trial 15 with value: 0.9497967725111052.

Best trial: 15. Best value: 0.949797:   6%|██████▍                                                                                                     | 12/200 [11:30<2:34:25, 49.28s/it]

[I 2026-05-24 00:26:09,020] Trial 11 pruned.

Best trial: 15. Best value: 0.949797:   6%|███████                                                                                                     | 13/200 [11:45<2:00:54, 38.79s/it]

[I 2026-05-24 00:26:23,684] Trial 7 finished with value: 0.9491021151925432 and parameters: {'num_leaves': 62, 'max_depth': 10, 'learning_rate': 0.013320140756681042, 'lambda_l1': 0.002275487351674738, 'lambda_l2': 5.434105078317631, 'feature_fraction': 0.7097772577859716, 'bagging_fraction': 0.6085237157385165, 'bagging_freq': 4, 'min_child_samples': 83}. Best is trial 15 with value: 0.9497967725111052.

Best trial: 15. Best value: 0.949797:   7%|███████▌                                                                                                    | 14/200 [12:35<2:11:03, 42.27s/it]

[I 2026-05-24 00:27:13,998] Trial 1 finished with value: 0.9490121899455091 and parameters: {'num_leaves': 121, 'max_depth': 7, 'learning_rate': 0.015411890553269794, 'lambda_l1': 0.021511594081732945, 'lambda_l2': 0.0348215832091809, 'feature_fraction': 0.9953306703870312, 'bagging_fraction': 0.7916796056152486, 'bagging_freq': 5, 'min_child_samples': 39}. Best is trial 15 with value: 0.9497967725111052.

Best trial: 15. Best value: 0.949797:   8%|████████                                                                                                    | 15/200 [12:58<1:52:43, 36.56s/it]

[I 2026-05-24 00:27:37,310] Trial 9 pruned.

Best trial: 15. Best value: 0.949797:   8%|████████▋                                                                                                   | 16/200 [14:22<2:35:44, 50.79s/it]

[I 2026-05-24 00:29:01,134] Trial 20 pruned.

Best trial: 22. Best value: 0.949864:   8%|█████████▏                                                                                                  | 17/200 [14:31<1:56:24, 38.17s/it]

[I 2026-05-24 00:29:09,959] Trial 22 finished with value: 0.9498635057375712 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.011001133386592941, 'lambda_l1': 0.003689356211978601, 'lambda_l2': 0.00571718237422858, 'feature_fraction': 0.9985184099516264, 'bagging_fraction': 0.7790050349905007, 'bagging_freq': 7, 'min_child_samples': 37}. Best is trial 22 with value: 0.9498635057375712.

Best trial: 23. Best value: 0.94988:   9%|█████████▊                                                                                                   | 18/200 [15:33<2:18:05, 45.53s/it]

[I 2026-05-24 00:30:12,622] Trial 23 finished with value: 0.9498798214274012 and parameters: {'num_leaves': 256, 'max_depth': 3, 'learning_rate': 0.010528079530713417, 'lambda_l1': 9.218977432870055, 'lambda_l2': 0.009406380316586447, 'feature_fraction': 0.9002629094437156, 'bagging_fraction': 0.7190918931241458, 'bagging_freq': 7, 'min_child_samples': 39}. Best is trial 23 with value: 0.9498798214274012.

Best trial: 23. Best value: 0.94988:  10%|██████████▎                                                                                                  | 19/200 [15:50<1:51:06, 36.83s/it]

[I 2026-05-24 00:30:29,201] Trial 24 finished with value: 0.9498762919821226 and parameters: {'num_leaves': 256, 'max_depth': 3, 'learning_rate': 0.010765008178849586, 'lambda_l1': 3.8811453923276593, 'lambda_l2': 0.00680328892382355, 'feature_fraction': 0.8844514892173386, 'bagging_fraction': 0.8250100599155379, 'bagging_freq': 7, 'min_child_samples': 36}. Best is trial 23 with value: 0.9498798214274012.

Best trial: 23. Best value: 0.94988:  10%|██████████▉                                                                                                  | 20/200 [15:52<1:19:01, 26.34s/it]

[I 2026-05-24 00:30:31,093] Trial 13 pruned.

Best trial: 23. Best value: 0.94988:  10%|███████████▋                                                                                                   | 21/200 [15:55<57:37, 19.32s/it]

[I 2026-05-24 00:30:34,028] Trial 17 pruned.

Best trial: 25. Best value: 0.94988:  11%|███████████▉                                                                                                 | 22/200 [16:34<1:15:07, 25.32s/it]

[I 2026-05-24 00:31:13,348] Trial 25 finished with value: 0.9498799053133057 and parameters: {'num_leaves': 256, 'max_depth': 3, 'learning_rate': 0.010666532869713287, 'lambda_l1': 9.652526089041944, 'lambda_l2': 0.005553712823135739, 'feature_fraction': 0.8651797062790053, 'bagging_fraction': 0.7130001919885798, 'bagging_freq': 7, 'min_child_samples': 11}. Best is trial 25 with value: 0.9498799053133057.

Best trial: 25. Best value: 0.94988:  12%|████████████▌                                                                                                | 23/200 [16:56<1:11:21, 24.19s/it]

[I 2026-05-24 00:31:34,907] Trial 26 finished with value: 0.9498761655616482 and parameters: {'num_leaves': 253, 'max_depth': 3, 'learning_rate': 0.010048787110094087, 'lambda_l1': 0.17309919838886548, 'lambda_l2': 0.005272677540243019, 'feature_fraction': 0.7890571886500967, 'bagging_fraction': 0.7293488984253731, 'bagging_freq': 6, 'min_child_samples': 10}. Best is trial 25 with value: 0.9498799053133057.

Best trial: 25. Best value: 0.94988:  12%|█████████████▎                                                                                                 | 24/200 [16:58<51:13, 17.46s/it]

[I 2026-05-24 00:31:36,671] Trial 18 pruned.

Best trial: 27. Best value: 0.949881:  12%|█████████████▌                                                                                              | 25/200 [18:24<1:51:15, 38.15s/it]

[I 2026-05-24 00:33:03,071] Trial 27 finished with value: 0.949880898758213 and parameters: {'num_leaves': 248, 'max_depth': 3, 'learning_rate': 0.010062518319235126, 'lambda_l1': 0.16664927368042248, 'lambda_l2': 0.006724913635568204, 'feature_fraction': 0.7672588133031097, 'bagging_fraction': 0.71828095872822, 'bagging_freq': 6, 'min_child_samples': 12}. Best is trial 27 with value: 0.949880898758213.

Best trial: 27. Best value: 0.949881:  13%|██████████████                                                                                              | 26/200 [18:32<1:24:29, 29.14s/it]

[I 2026-05-24 00:33:11,184] Trial 28 finished with value: 0.9498698467714346 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.011098615033056536, 'lambda_l1': 0.12854229969640357, 'lambda_l2': 0.009483456047774754, 'feature_fraction': 0.9125848197664115, 'bagging_fraction': 0.7209396613749234, 'bagging_freq': 7, 'min_child_samples': 12}. Best is trial 27 with value: 0.949880898758213.

Best trial: 27. Best value: 0.949881:  14%|██████████████▌                                                                                             | 27/200 [18:34<1:00:09, 20.86s/it]

[I 2026-05-24 00:33:12,743] Trial 19 pruned.

Best trial: 27. Best value: 0.949881:  14%|███████████████                                                                                             | 28/200 [19:23<1:24:10, 29.36s/it]

[I 2026-05-24 00:34:01,941] Trial 14 finished with value: 0.9489867129470181 and parameters: {'num_leaves': 187, 'max_depth': 8, 'learning_rate': 0.019687083928505853, 'lambda_l1': 9.764348750816465, 'lambda_l2': 0.06769029559894375, 'feature_fraction': 0.980297134100044, 'bagging_fraction': 0.6649708043123924, 'bagging_freq': 4, 'min_child_samples': 16}. Best is trial 27 with value: 0.949880898758213.

Best trial: 29. Best value: 0.949883:  14%|███████████████▋                                                                                            | 29/200 [19:38<1:11:46, 25.18s/it]

[I 2026-05-24 00:34:17,371] Trial 29 finished with value: 0.9498826283087837 and parameters: {'num_leaves': 254, 'max_depth': 3, 'learning_rate': 0.010257926249874417, 'lambda_l1': 5.7901757998530075, 'lambda_l2': 0.008679087449052355, 'feature_fraction': 0.9976374692076992, 'bagging_fraction': 0.7105709579270756, 'bagging_freq': 7, 'min_child_samples': 45}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  15%|████████████████▏                                                                                           | 30/200 [20:02<1:09:55, 24.68s/it]

[I 2026-05-24 00:34:40,885] Trial 32 finished with value: 0.9498743824175069 and parameters: {'num_leaves': 225, 'max_depth': 3, 'learning_rate': 0.010829582876874256, 'lambda_l1': 8.99585977413418, 'lambda_l2': 0.011877193315741982, 'feature_fraction': 0.8984202636251798, 'bagging_fraction': 0.721430145147471, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  16%|████████████████▋                                                                                           | 31/200 [20:39<1:20:25, 28.55s/it]

[I 2026-05-24 00:35:18,467] Trial 33 finished with value: 0.9498338008108307 and parameters: {'num_leaves': 221, 'max_depth': 3, 'learning_rate': 0.018950304241339262, 'lambda_l1': 8.106850831691533, 'lambda_l2': 0.010768505987906818, 'feature_fraction': 0.8903359529259263, 'bagging_fraction': 0.7197383323936942, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  16%|█████████████████▎                                                                                          | 32/200 [23:21<3:12:03, 68.59s/it]

[I 2026-05-24 00:38:00,482] Trial 30 finished with value: 0.9497005549935642 and parameters: {'num_leaves': 221, 'max_depth': 6, 'learning_rate': 0.010101552151918883, 'lambda_l1': 8.724097162846824, 'lambda_l2': 0.011256061161263613, 'feature_fraction': 0.7722741887634923, 'bagging_fraction': 0.7126547209980763, 'bagging_freq': 7, 'min_child_samples': 49}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  16%|█████████████████▊                                                                                          | 33/200 [24:31<3:12:00, 68.98s/it]

[I 2026-05-24 00:39:10,381] Trial 37 finished with value: 0.9495866480326949 and parameters: {'num_leaves': 218, 'max_depth': 5, 'learning_rate': 0.015608392883902079, 'lambda_l1': 1.9012360168862232, 'lambda_l2': 0.0015217538154041342, 'feature_fraction': 0.7500361104916671, 'bagging_fraction': 0.7129814295597731, 'bagging_freq': 7, 'min_child_samples': 47}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  17%|██████████████████▎                                                                                         | 34/200 [25:18<2:52:08, 62.22s/it]

[I 2026-05-24 00:39:56,821] Trial 31 finished with value: 0.9494784825758039 and parameters: {'num_leaves': 220, 'max_depth': 6, 'learning_rate': 0.018740777305236114, 'lambda_l1': 8.649921813160093, 'lambda_l2': 0.008045350225763803, 'feature_fraction': 0.7665977986184265, 'bagging_fraction': 0.7061013012380206, 'bagging_freq': 7, 'min_child_samples': 50}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  18%|██████████████████▉                                                                                         | 35/200 [25:27<2:07:45, 46.45s/it]

[I 2026-05-24 00:40:06,489] Trial 42 finished with value: 0.9497583486694758 and parameters: {'num_leaves': 190, 'max_depth': 4, 'learning_rate': 0.014221005285683402, 'lambda_l1': 2.796892489409997, 'lambda_l2': 0.0023811786471250565, 'feature_fraction': 0.7369997918617149, 'bagging_fraction': 0.6975677968848369, 'bagging_freq': 6, 'min_child_samples': 48}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  18%|███████████████████▍                                                                                        | 36/200 [25:36<1:36:14, 35.21s/it]

[I 2026-05-24 00:40:15,464] Trial 35 finished with value: 0.9494471580367186 and parameters: {'num_leaves': 216, 'max_depth': 6, 'learning_rate': 0.01774823291493481, 'lambda_l1': 9.21805296223923, 'lambda_l2': 0.0015130938836434586, 'feature_fraction': 0.8837008956227405, 'bagging_fraction': 0.7285569591536603, 'bagging_freq': 7, 'min_child_samples': 47}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  18%|███████████████████▉                                                                                        | 37/200 [25:41<1:10:54, 26.10s/it]

[I 2026-05-24 00:40:20,309] Trial 21 finished with value: 0.9493113536602653 and parameters: {'num_leaves': 256, 'max_depth': 9, 'learning_rate': 0.010218133142960144, 'lambda_l1': 9.455537210600475, 'lambda_l2': 0.009634581477199016, 'feature_fraction': 0.9937414373055704, 'bagging_fraction': 0.7605595005677657, 'bagging_freq': 7, 'min_child_samples': 100}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  19%|████████████████████▌                                                                                       | 38/200 [26:26<1:25:59, 31.85s/it]

[I 2026-05-24 00:41:05,573] Trial 34 finished with value: 0.9494299637762802 and parameters: {'num_leaves': 205, 'max_depth': 6, 'learning_rate': 0.018082600032770325, 'lambda_l1': 8.960774578647525, 'lambda_l2': 0.015370075609233758, 'feature_fraction': 0.8885855755267762, 'bagging_fraction': 0.7268699131934194, 'bagging_freq': 7, 'min_child_samples': 48}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  20%|█████████████████████                                                                                       | 39/200 [27:57<2:12:30, 49.38s/it]

[I 2026-05-24 00:42:35,861] Trial 39 finished with value: 0.9493790023866795 and parameters: {'num_leaves': 225, 'max_depth': 6, 'learning_rate': 0.015447558321156093, 'lambda_l1': 1.978904205164943, 'lambda_l2': 0.0013614455725465017, 'feature_fraction': 0.7524100481127526, 'bagging_fraction': 0.7164499501775303, 'bagging_freq': 7, 'min_child_samples': 48}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  20%|█████████████████████▌                                                                                      | 40/200 [28:00<1:34:37, 35.48s/it]

[I 2026-05-24 00:42:38,907] Trial 38 finished with value: 0.949317188577902 and parameters: {'num_leaves': 224, 'max_depth': 6, 'learning_rate': 0.016597094340001933, 'lambda_l1': 2.1181674330664646, 'lambda_l2': 0.0014677616619178113, 'feature_fraction': 0.7395250009649481, 'bagging_fraction': 0.7226860209390841, 'bagging_freq': 7, 'min_child_samples': 49}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  20%|██████████████████████▏                                                                                     | 41/200 [29:01<1:54:32, 43.22s/it]

[I 2026-05-24 00:43:40,194] Trial 36 finished with value: 0.9492713223723197 and parameters: {'num_leaves': 212, 'max_depth': 6, 'learning_rate': 0.017009972046157083, 'lambda_l1': 1.8705717448666748, 'lambda_l2': 0.0015845547022345576, 'feature_fraction': 0.7542299002850477, 'bagging_fraction': 0.7221111789572937, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  21%|██████████████████████▋                                                                                     | 42/200 [29:06<1:23:57, 31.88s/it]

[I 2026-05-24 00:43:45,621] Trial 40 finished with value: 0.9493279716190207 and parameters: {'num_leaves': 224, 'max_depth': 6, 'learning_rate': 0.016913801966496698, 'lambda_l1': 2.0818664707282264, 'lambda_l2': 0.00135463791451521, 'feature_fraction': 0.7529470943723204, 'bagging_fraction': 0.6995090869227534, 'bagging_freq': 6, 'min_child_samples': 47}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  22%|███████████████████████▏                                                                                    | 43/200 [29:35<1:20:26, 30.74s/it]

[I 2026-05-24 00:44:13,687] Trial 44 finished with value: 0.9497596365916131 and parameters: {'num_leaves': 187, 'max_depth': 4, 'learning_rate': 0.015326825914116026, 'lambda_l1': 3.5059201885852986, 'lambda_l2': 0.0025601988682336864, 'feature_fraction': 0.7410102631510187, 'bagging_fraction': 0.7452750234099175, 'bagging_freq': 6, 'min_child_samples': 29}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  22%|████████████████████████▏                                                                                     | 44/200 [29:38<58:57, 22.68s/it]

[I 2026-05-24 00:44:17,551] Trial 41 finished with value: 0.9493254982214527 and parameters: {'num_leaves': 184, 'max_depth': 6, 'learning_rate': 0.017192934531161445, 'lambda_l1': 2.956590010788976, 'lambda_l2': 0.002122398100973795, 'feature_fraction': 0.7600108015944415, 'bagging_fraction': 0.6898896769352582, 'bagging_freq': 6, 'min_child_samples': 48}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  22%|████████████████████████▊                                                                                     | 45/200 [29:46<46:42, 18.08s/it]

[I 2026-05-24 00:44:24,914] Trial 43 finished with value: 0.9495798260247932 and parameters: {'num_leaves': 191, 'max_depth': 5, 'learning_rate': 0.015423106202024986, 'lambda_l1': 2.660551995545975, 'lambda_l2': 0.0023743778547754366, 'feature_fraction': 0.7588119495252842, 'bagging_fraction': 0.6855314426548216, 'bagging_freq': 6, 'min_child_samples': 28}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  23%|████████████████████████▊                                                                                   | 46/200 [30:25<1:02:38, 24.41s/it]

[I 2026-05-24 00:45:04,080] Trial 45 finished with value: 0.9497410639362981 and parameters: {'num_leaves': 190, 'max_depth': 4, 'learning_rate': 0.015373341567711436, 'lambda_l1': 3.191056094029707, 'lambda_l2': 0.003373685531549534, 'feature_fraction': 0.9336433815400256, 'bagging_fraction': 0.74927801882048, 'bagging_freq': 6, 'min_child_samples': 27}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  24%|█████████████████████████▊                                                                                    | 47/200 [30:34<50:34, 19.83s/it]

[I 2026-05-24 00:45:13,234] Trial 46 finished with value: 0.9497180918656003 and parameters: {'num_leaves': 237, 'max_depth': 4, 'learning_rate': 0.015675938594180098, 'lambda_l1': 1.0710251053364173, 'lambda_l2': 0.020325774312599697, 'feature_fraction': 0.9453001356843835, 'bagging_fraction': 0.7491446735347776, 'bagging_freq': 6, 'min_child_samples': 28}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  24%|██████████████████████████▍                                                                                   | 48/200 [30:42<40:53, 16.14s/it]

[I 2026-05-24 00:45:20,767] Trial 47 finished with value: 0.9497394827113942 and parameters: {'num_leaves': 233, 'max_depth': 4, 'learning_rate': 0.015272878713683243, 'lambda_l1': 3.898439667072209, 'lambda_l2': 0.022451603208326686, 'feature_fraction': 0.9550644977754935, 'bagging_fraction': 0.6580142936025305, 'bagging_freq': 6, 'min_child_samples': 28}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  24%|██████████████████████████▉                                                                                   | 49/200 [30:42<29:03, 11.54s/it]

[I 2026-05-24 00:45:21,586] Trial 48 finished with value: 0.9495666911707248 and parameters: {'num_leaves': 237, 'max_depth': 4, 'learning_rate': 0.02489853212897955, 'lambda_l1': 1.2101440222207112, 'lambda_l2': 0.021927064204531402, 'feature_fraction': 0.9362588473130904, 'bagging_fraction': 0.6578574549695821, 'bagging_freq': 6, 'min_child_samples': 28}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  25%|███████████████████████████▌                                                                                  | 50/200 [31:30<55:36, 22.24s/it]

[I 2026-05-24 00:46:08,793] Trial 49 finished with value: 0.9497250794432792 and parameters: {'num_leaves': 237, 'max_depth': 4, 'learning_rate': 0.014660615069744127, 'lambda_l1': 1.1673479175157429, 'lambda_l2': 0.025458469669158556, 'feature_fraction': 0.9456108602060994, 'bagging_fraction': 0.6524962751495278, 'bagging_freq': 6, 'min_child_samples': 41}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  26%|███████████████████████████▌                                                                                | 51/200 [33:07<1:51:18, 44.82s/it]

[I 2026-05-24 00:47:46,304] Trial 50 finished with value: 0.949561276754799 and parameters: {'num_leaves': 237, 'max_depth': 4, 'learning_rate': 0.023800996958502046, 'lambda_l1': 0.8982085036109634, 'lambda_l2': 0.026072204192567373, 'feature_fraction': 0.9393454321582747, 'bagging_fraction': 0.6453668722353059, 'bagging_freq': 6, 'min_child_samples': 27}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  26%|████████████████████████████                                                                                | 52/200 [33:16<1:23:44, 33.95s/it]

[I 2026-05-24 00:47:54,882] Trial 51 finished with value: 0.9497641095418441 and parameters: {'num_leaves': 239, 'max_depth': 4, 'learning_rate': 0.013472451289847705, 'lambda_l1': 4.647521547505196, 'lambda_l2': 0.02660749395476838, 'feature_fraction': 0.9329928866632389, 'bagging_fraction': 0.6537010446724113, 'bagging_freq': 6, 'min_child_samples': 28}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  26%|████████████████████████████▌                                                                               | 53/200 [34:35<1:56:46, 47.66s/it]

[I 2026-05-24 00:49:14,544] Trial 52 finished with value: 0.9497806134947098 and parameters: {'num_leaves': 238, 'max_depth': 4, 'learning_rate': 0.013393453575384804, 'lambda_l1': 3.787805499443082, 'lambda_l2': 0.026362235308218077, 'feature_fraction': 0.9351522594120653, 'bagging_fraction': 0.8174620105890706, 'bagging_freq': 6, 'min_child_samples': 40}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  27%|█████████████████████████████▏                                                                              | 54/200 [34:44<1:27:11, 35.83s/it]

[I 2026-05-24 00:49:22,743] Trial 53 finished with value: 0.9497833838577392 and parameters: {'num_leaves': 238, 'max_depth': 4, 'learning_rate': 0.013522855382566267, 'lambda_l1': 4.213841925504489, 'lambda_l2': 0.02108388795566757, 'feature_fraction': 0.9328379850706899, 'bagging_fraction': 0.8113604868403699, 'bagging_freq': 6, 'min_child_samples': 27}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  28%|█████████████████████████████▋                                                                              | 55/200 [34:44<1:00:56, 25.22s/it]

[I 2026-05-24 00:49:23,218] Trial 60 finished with value: 0.9498636907521838 and parameters: {'num_leaves': 242, 'max_depth': 3, 'learning_rate': 0.012903392974223327, 'lambda_l1': 0.05785631315670244, 'lambda_l2': 0.3574286972826082, 'feature_fraction': 0.8658290632230776, 'bagging_fraction': 0.7986959446875769, 'bagging_freq': 1, 'min_child_samples': 41}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  28%|██████████████████████████████▊                                                                               | 56/200 [35:01<54:54, 22.88s/it]

[I 2026-05-24 00:49:40,630] Trial 57 finished with value: 0.9498613776678482 and parameters: {'num_leaves': 238, 'max_depth': 3, 'learning_rate': 0.012894480418796156, 'lambda_l1': 4.958291320533673, 'lambda_l2': 0.024946386892513696, 'feature_fraction': 0.9662537282763883, 'bagging_fraction': 0.8454226066258232, 'bagging_freq': 6, 'min_child_samples': 39}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  28%|███████████████████████████████▎                                                                              | 57/200 [35:06<41:34, 17.44s/it]

[I 2026-05-24 00:49:45,402] Trial 54 finished with value: 0.9497908051718857 and parameters: {'num_leaves': 238, 'max_depth': 4, 'learning_rate': 0.012940255477201892, 'lambda_l1': 4.470220469987082, 'lambda_l2': 0.023439205585291074, 'feature_fraction': 0.8637303637974892, 'bagging_fraction': 0.8071028562671699, 'bagging_freq': 6, 'min_child_samples': 40}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  29%|███████████████████████████████▉                                                                              | 58/200 [35:12<32:47, 13.86s/it]

[I 2026-05-24 00:49:50,891] Trial 58 finished with value: 0.9498600467501557 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.012966774109709605, 'lambda_l1': 4.987604937348611, 'lambda_l2': 0.025670617572666327, 'feature_fraction': 0.8112882828809611, 'bagging_fraction': 0.8094009264136873, 'bagging_freq': 3, 'min_child_samples': 42}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  30%|████████████████████████████████▍                                                                             | 59/200 [35:22<30:20, 12.91s/it]

[I 2026-05-24 00:50:01,600] Trial 55 finished with value: 0.9497710971077012 and parameters: {'num_leaves': 238, 'max_depth': 4, 'learning_rate': 0.013853166050307224, 'lambda_l1': 4.969679862839835, 'lambda_l2': 0.02280553117249795, 'feature_fraction': 0.9329967360271851, 'bagging_fraction': 0.8084818776777909, 'bagging_freq': 6, 'min_child_samples': 27}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  30%|█████████████████████████████████                                                                             | 60/200 [35:23<21:38,  9.28s/it]

[I 2026-05-24 00:50:02,392] Trial 59 finished with value: 0.9498564089996595 and parameters: {'num_leaves': 242, 'max_depth': 3, 'learning_rate': 0.01286127426318428, 'lambda_l1': 5.061007528377926, 'lambda_l2': 0.0308794353675263, 'feature_fraction': 0.8587820687509642, 'bagging_fraction': 0.8126177025813925, 'bagging_freq': 3, 'min_child_samples': 41}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  30%|█████████████████████████████████▌                                                                            | 61/200 [35:24<15:35,  6.73s/it]

[I 2026-05-24 00:50:03,190] Trial 56 finished with value: 0.9497839455472203 and parameters: {'num_leaves': 239, 'max_depth': 4, 'learning_rate': 0.013141922659715465, 'lambda_l1': 4.666561896892336, 'lambda_l2': 0.02110667614119931, 'feature_fraction': 0.9433599106990812, 'bagging_fraction': 0.802686684366504, 'bagging_freq': 6, 'min_child_samples': 40}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  31%|██████████████████████████████████                                                                            | 62/200 [35:58<34:26, 14.98s/it]

[I 2026-05-24 00:50:37,402] Trial 61 finished with value: 0.9498591042556971 and parameters: {'num_leaves': 243, 'max_depth': 3, 'learning_rate': 0.013156304516745201, 'lambda_l1': 5.1503825802653, 'lambda_l2': 0.004418466523882948, 'feature_fraction': 0.8551449273691758, 'bagging_fraction': 0.81913046680825, 'bagging_freq': 7, 'min_child_samples': 41}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  32%|██████████████████████████████████                                                                          | 63/200 [37:39<1:32:45, 40.63s/it]

[I 2026-05-24 00:52:17,868] Trial 62 finished with value: 0.9498591784722837 and parameters: {'num_leaves': 242, 'max_depth': 3, 'learning_rate': 0.013169523058829957, 'lambda_l1': 5.241467213683279, 'lambda_l2': 0.005579694724692251, 'feature_fraction': 0.8656935696173764, 'bagging_fraction': 0.8182306300948571, 'bagging_freq': 5, 'min_child_samples': 15}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  32%|██████████████████████████████████▌                                                                         | 64/200 [37:45<1:08:25, 30.19s/it]

[I 2026-05-24 00:52:23,705] Trial 63 finished with value: 0.9498589101131237 and parameters: {'num_leaves': 248, 'max_depth': 3, 'learning_rate': 0.012740275466356922, 'lambda_l1': 5.390581605688133, 'lambda_l2': 0.0051615562501876495, 'feature_fraction': 0.8169399958821374, 'bagging_fraction': 0.8135589642875447, 'bagging_freq': 5, 'min_child_samples': 38}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  32%|███████████████████████████████████                                                                         | 65/200 [39:07<1:42:59, 45.78s/it]

[I 2026-05-24 00:53:45,854] Trial 65 finished with value: 0.9498660374688199 and parameters: {'num_leaves': 249, 'max_depth': 3, 'learning_rate': 0.012050844252712948, 'lambda_l1': 0.08029967063417945, 'lambda_l2': 0.005333498818708267, 'feature_fraction': 0.8587607397244046, 'bagging_fraction': 0.7921776841284008, 'bagging_freq': 5, 'min_child_samples': 14}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  33%|███████████████████████████████████▋                                                                        | 66/200 [39:11<1:14:19, 33.28s/it]

[I 2026-05-24 00:53:49,985] Trial 64 finished with value: 0.9498600806565284 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.012639712681005322, 'lambda_l1': 5.573155052308418, 'lambda_l2': 0.004312492301845161, 'feature_fraction': 0.8164492620227477, 'bagging_fraction': 0.789864459932363, 'bagging_freq': 3, 'min_child_samples': 14}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  34%|████████████████████████████████████▊                                                                         | 67/200 [39:15<54:32, 24.60s/it]

[I 2026-05-24 00:53:54,326] Trial 68 finished with value: 0.9498697283136839 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.01175157861076639, 'lambda_l1': 0.0011955054094186482, 'lambda_l2': 0.004194933038523443, 'feature_fraction': 0.8145328151877703, 'bagging_fraction': 0.6284343835709579, 'bagging_freq': 5, 'min_child_samples': 14}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  34%|█████████████████████████████████████▍                                                                        | 68/200 [39:17<38:47, 17.63s/it]

[I 2026-05-24 00:53:55,699] Trial 66 finished with value: 0.9498688589200638 and parameters: {'num_leaves': 249, 'max_depth': 3, 'learning_rate': 0.012015362489735915, 'lambda_l1': 5.668727654045843, 'lambda_l2': 0.004491398204822042, 'feature_fraction': 0.8453619655956961, 'bagging_fraction': 0.8480184044317585, 'bagging_freq': 5, 'min_child_samples': 15}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  34%|█████████████████████████████████████▉                                                                        | 69/200 [39:24<32:00, 14.66s/it]

[I 2026-05-24 00:54:03,420] Trial 67 finished with value: 0.9498596637628275 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.012290278065737785, 'lambda_l1': 0.2153024787461906, 'lambda_l2': 0.004804664496460597, 'feature_fraction': 0.8054514754775336, 'bagging_fraction': 0.7839241095912737, 'bagging_freq': 5, 'min_child_samples': 17}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  35%|██████████████████████████████████████▌                                                                       | 70/200 [39:29<25:17, 11.67s/it]

[I 2026-05-24 00:54:08,125] Trial 69 finished with value: 0.9494239433937887 and parameters: {'num_leaves': 256, 'max_depth': 3, 'learning_rate': 0.07130368324139663, 'lambda_l1': 0.214980665916482, 'lambda_l2': 0.005179431053010539, 'feature_fraction': 0.8392760393687457, 'bagging_fraction': 0.8377440511356483, 'bagging_freq': 7, 'min_child_samples': 16}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  36%|███████████████████████████████████████                                                                       | 71/200 [39:31<19:06,  8.88s/it]

[I 2026-05-24 00:54:10,507] Trial 70 finished with value: 0.949552004839294 and parameters: {'num_leaves': 248, 'max_depth': 3, 'learning_rate': 0.05474062429699434, 'lambda_l1': 0.24668959666108012, 'lambda_l2': 0.004410921517587606, 'feature_fraction': 0.8347306095890998, 'bagging_fraction': 0.6270093035243852, 'bagging_freq': 5, 'min_child_samples': 54}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  36%|███████████████████████████████████████▌                                                                      | 72/200 [39:47<23:26, 10.99s/it]

[I 2026-05-24 00:54:26,403] Trial 72 finished with value: 0.9498694519330023 and parameters: {'num_leaves': 250, 'max_depth': 3, 'learning_rate': 0.010334948081319316, 'lambda_l1': 0.21368300606421248, 'lambda_l2': 0.004933838607039368, 'feature_fraction': 0.9078402934920929, 'bagging_fraction': 0.7871211214404316, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  36%|████████████████████████████████████████▏                                                                     | 73/200 [39:52<19:26,  9.19s/it]

[I 2026-05-24 00:54:31,391] Trial 71 finished with value: 0.9498784956605604 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.010482446089522068, 'lambda_l1': 0.009924697449591563, 'lambda_l2': 0.005037383048762497, 'feature_fraction': 0.8394718167529207, 'bagging_fraction': 0.8370941084300142, 'bagging_freq': 5, 'min_child_samples': 14}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  37%|████████████████████████████████████████▋                                                                     | 74/200 [40:18<29:27, 14.03s/it]

[I 2026-05-24 00:54:56,715] Trial 73 finished with value: 0.9498754879946869 and parameters: {'num_leaves': 250, 'max_depth': 3, 'learning_rate': 0.01007193051002817, 'lambda_l1': 0.06677631390228658, 'lambda_l2': 0.006238455021573742, 'feature_fraction': 0.9092313017084704, 'bagging_fraction': 0.7387138830144967, 'bagging_freq': 7, 'min_child_samples': 14}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  38%|████████████████████████████████████████▌                                                                   | 75/200 [41:47<1:16:39, 36.80s/it]

[I 2026-05-24 00:56:26,637] Trial 74 finished with value: 0.9498694148239245 and parameters: {'num_leaves': 255, 'max_depth': 3, 'learning_rate': 0.010161464844051353, 'lambda_l1': 0.1987720025377879, 'lambda_l2': 0.014458927767918166, 'feature_fraction': 0.9141922406542833, 'bagging_fraction': 0.6760244672716937, 'bagging_freq': 7, 'min_child_samples': 14}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  38%|█████████████████████████████████████████▊                                                                    | 76/200 [41:53<56:27, 27.32s/it]

[I 2026-05-24 00:56:31,840] Trial 75 finished with value: 0.9498738241244288 and parameters: {'num_leaves': 256, 'max_depth': 3, 'learning_rate': 0.010142394364919788, 'lambda_l1': 0.2088038924572272, 'lambda_l2': 0.014778055701207802, 'feature_fraction': 0.905514052073816, 'bagging_fraction': 0.6769781981518261, 'bagging_freq': 7, 'min_child_samples': 14}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  38%|█████████████████████████████████████████▌                                                                  | 77/200 [43:18<1:31:33, 44.66s/it]

[I 2026-05-24 00:57:56,973] Trial 76 finished with value: 0.9498697380003831 and parameters: {'num_leaves': 256, 'max_depth': 3, 'learning_rate': 0.010324632483925013, 'lambda_l1': 0.21042050352361064, 'lambda_l2': 0.012536924436646323, 'feature_fraction': 0.836720003766634, 'bagging_fraction': 0.7367386835282139, 'bagging_freq': 7, 'min_child_samples': 34}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  39%|██████████████████████████████████████████                                                                  | 78/200 [43:38<1:15:57, 37.36s/it]

[I 2026-05-24 00:58:17,291] Trial 82 finished with value: 0.9498724022476978 and parameters: {'num_leaves': 228, 'max_depth': 3, 'learning_rate': 0.010042255864537894, 'lambda_l1': 0.15501031338119875, 'lambda_l2': 0.014457963891562632, 'feature_fraction': 0.9106486787363123, 'bagging_fraction': 0.6744416464990823, 'bagging_freq': 7, 'min_child_samples': 22}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  40%|██████████████████████████████████████████▋                                                                 | 79/200 [43:56<1:03:46, 31.62s/it]

[I 2026-05-24 00:58:35,524] Trial 84 finished with value: 0.9498763189152616 and parameters: {'num_leaves': 231, 'max_depth': 3, 'learning_rate': 0.010498322588016697, 'lambda_l1': 0.011030111610736705, 'lambda_l2': 0.013484300796620998, 'feature_fraction': 0.7954211866437724, 'bagging_fraction': 0.6790149942964765, 'bagging_freq': 7, 'min_child_samples': 33}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  40%|████████████████████████████████████████████                                                                  | 80/200 [44:21<59:00, 29.51s/it]

[I 2026-05-24 00:59:00,101] Trial 85 finished with value: 0.949879015699627 and parameters: {'num_leaves': 256, 'max_depth': 3, 'learning_rate': 0.010453254329080163, 'lambda_l1': 0.009787887226837244, 'lambda_l2': 0.013056411652690232, 'feature_fraction': 0.7892252213428, 'bagging_fraction': 0.6775367220853122, 'bagging_freq': 7, 'min_child_samples': 22}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  40%|███████████████████████████████████████████▋                                                                | 81/200 [45:42<1:29:00, 44.88s/it]

[I 2026-05-24 01:00:20,835] Trial 77 finished with value: 0.9496891350594614 and parameters: {'num_leaves': 256, 'max_depth': 5, 'learning_rate': 0.010037419811373008, 'lambda_l1': 0.2071017632084147, 'lambda_l2': 0.007220331491072656, 'feature_fraction': 0.9065872527167981, 'bagging_fraction': 0.6776116312664425, 'bagging_freq': 7, 'min_child_samples': 22}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  41%|████████████████████████████████████████████▎                                                               | 82/200 [46:01<1:13:14, 37.24s/it]

[I 2026-05-24 01:00:40,274] Trial 80 finished with value: 0.9496957630031548 and parameters: {'num_leaves': 228, 'max_depth': 5, 'learning_rate': 0.010091567723602868, 'lambda_l1': 0.009114233527199995, 'lambda_l2': 0.014374959287496368, 'feature_fraction': 0.9112804148412776, 'bagging_fraction': 0.6775079822491129, 'bagging_freq': 7, 'min_child_samples': 34}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  42%|█████████████████████████████████████████████▋                                                                | 83/200 [46:03<52:02, 26.68s/it]

[I 2026-05-24 01:00:42,316] Trial 78 finished with value: 0.9497271650782692 and parameters: {'num_leaves': 255, 'max_depth': 5, 'learning_rate': 0.010062669589804056, 'lambda_l1': 0.18951661813024834, 'lambda_l2': 0.01327231095842564, 'feature_fraction': 0.9083683328862245, 'bagging_fraction': 0.7383390508200004, 'bagging_freq': 7, 'min_child_samples': 34}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  42%|██████████████████████████████████████████████▏                                                               | 84/200 [46:38<56:08, 29.04s/it]

[I 2026-05-24 01:01:16,843] Trial 81 finished with value: 0.9497204815866569 and parameters: {'num_leaves': 228, 'max_depth': 5, 'learning_rate': 0.010482189595796075, 'lambda_l1': 0.5847737466786139, 'lambda_l2': 0.013545903217240656, 'feature_fraction': 0.9126791266682028, 'bagging_fraction': 0.7388759672131202, 'bagging_freq': 7, 'min_child_samples': 22}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  42%|██████████████████████████████████████████████▊                                                               | 85/200 [46:38<39:12, 20.46s/it]

[I 2026-05-24 01:01:17,273] Trial 83 finished with value: 0.9497095130988281 and parameters: {'num_leaves': 227, 'max_depth': 5, 'learning_rate': 0.010669294457551246, 'lambda_l1': 0.12582643193283188, 'lambda_l2': 0.014256494610843462, 'feature_fraction': 0.9125166330127791, 'bagging_fraction': 0.7367723509255962, 'bagging_freq': 7, 'min_child_samples': 34}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  43%|███████████████████████████████████████████████▎                                                              | 86/200 [46:52<34:49, 18.33s/it]

[I 2026-05-24 01:01:30,652] Trial 79 finished with value: 0.9497284332290835 and parameters: {'num_leaves': 229, 'max_depth': 5, 'learning_rate': 0.010091195455730232, 'lambda_l1': 0.2426769474412825, 'lambda_l2': 0.008107915151775036, 'feature_fraction': 0.9155536876452298, 'bagging_fraction': 0.7364127300314449, 'bagging_freq': 7, 'min_child_samples': 22}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  44%|██████████████████████████████████████████████▉                                                             | 87/200 [49:11<1:43:07, 54.75s/it]

[I 2026-05-24 01:03:50,389] Trial 87 finished with value: 0.9497229955069887 and parameters: {'num_leaves': 230, 'max_depth': 5, 'learning_rate': 0.01083992478201461, 'lambda_l1': 0.011939807575773037, 'lambda_l2': 0.007024214846752133, 'feature_fraction': 0.7864479268316167, 'bagging_fraction': 0.8773407146699508, 'bagging_freq': 4, 'min_child_samples': 23}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  44%|███████████████████████████████████████████████▌                                                            | 88/200 [49:43<1:29:18, 47.84s/it]

[I 2026-05-24 01:04:22,099] Trial 86 finished with value: 0.9497206104977796 and parameters: {'num_leaves': 230, 'max_depth': 5, 'learning_rate': 0.010871855839107361, 'lambda_l1': 0.010384260789476109, 'lambda_l2': 0.007641440205837031, 'feature_fraction': 0.7893770348150538, 'bagging_fraction': 0.8736471357556183, 'bagging_freq': 4, 'min_child_samples': 21}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  44%|████████████████████████████████████████████████                                                            | 89/200 [50:38<1:32:21, 49.93s/it]

[I 2026-05-24 01:05:16,896] Trial 88 finished with value: 0.9496993772494697 and parameters: {'num_leaves': 229, 'max_depth': 5, 'learning_rate': 0.011148189545807275, 'lambda_l1': 0.009342447744364149, 'lambda_l2': 0.00767447638158422, 'feature_fraction': 0.7953506567859333, 'bagging_fraction': 0.760984044112536, 'bagging_freq': 4, 'min_child_samples': 22}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  45%|████████████████████████████████████████████████▌                                                           | 90/200 [50:38<1:04:12, 35.02s/it]

[I 2026-05-24 01:05:17,127] Trial 90 finished with value: 0.9495044258575518 and parameters: {'num_leaves': 205, 'max_depth': 5, 'learning_rate': 0.02101006469703159, 'lambda_l1': 0.0126045079858799, 'lambda_l2': 0.0074787422042315145, 'feature_fraction': 0.7849892344591968, 'bagging_fraction': 0.8715342483657185, 'bagging_freq': 4, 'min_child_samples': 34}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  46%|█████████████████████████████████████████████████▏                                                          | 91/200 [51:17<1:05:59, 36.33s/it]

[I 2026-05-24 01:05:56,510] Trial 93 finished with value: 0.949806898436079 and parameters: {'num_leaves': 159, 'max_depth': 4, 'learning_rate': 0.011277185817588764, 'lambda_l1': 0.015412984436664506, 'lambda_l2': 0.0031166364584428396, 'feature_fraction': 0.7925917244227222, 'bagging_fraction': 0.8843967661446284, 'bagging_freq': 4, 'min_child_samples': 19}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  46%|██████████████████████████████████████████████████▌                                                           | 92/200 [51:18<46:02, 25.58s/it]

[I 2026-05-24 01:05:56,991] Trial 91 finished with value: 0.9497077747724632 and parameters: {'num_leaves': 135, 'max_depth': 5, 'learning_rate': 0.011150944357638769, 'lambda_l1': 0.012165908545202895, 'lambda_l2': 0.007893085632043082, 'feature_fraction': 0.7773646386976977, 'bagging_fraction': 0.8967134104944539, 'bagging_freq': 7, 'min_child_samples': 33}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  46%|███████████████████████████████████████████████████▏                                                          | 93/200 [51:18<32:09, 18.03s/it]

[I 2026-05-24 01:05:57,428] Trial 89 finished with value: 0.9497134091908856 and parameters: {'num_leaves': 201, 'max_depth': 5, 'learning_rate': 0.011177829663065257, 'lambda_l1': 0.012514587780006874, 'lambda_l2': 0.009085976671095038, 'feature_fraction': 0.7794753292928781, 'bagging_fraction': 0.872420455329156, 'bagging_freq': 4, 'min_child_samples': 24}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  47%|███████████████████████████████████████████████████▋                                                          | 94/200 [51:19<22:54, 12.97s/it]

[I 2026-05-24 01:05:58,579] Trial 94 finished with value: 0.9498153512211678 and parameters: {'num_leaves': 135, 'max_depth': 4, 'learning_rate': 0.01121109236312187, 'lambda_l1': 0.011833296899834391, 'lambda_l2': 0.008864936963432187, 'feature_fraction': 0.7929466457229176, 'bagging_fraction': 0.8675310930399522, 'bagging_freq': 4, 'min_child_samples': 19}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  48%|████████████████████████████████████████████████████▎                                                         | 95/200 [52:04<39:25, 22.53s/it]

[I 2026-05-24 01:06:43,405] Trial 97 finished with value: 0.9498101508421067 and parameters: {'num_leaves': 135, 'max_depth': 4, 'learning_rate': 0.011405537688325347, 'lambda_l1': 0.014784201003037652, 'lambda_l2': 0.009412482139254011, 'feature_fraction': 0.7754680107023426, 'bagging_fraction': 0.8686027688608421, 'bagging_freq': 4, 'min_child_samples': 31}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  48%|███████████████████████████████████████████████████▊                                                        | 96/200 [53:08<1:00:36, 34.96s/it]

[I 2026-05-24 01:07:47,389] Trial 96 finished with value: 0.9495924866918374 and parameters: {'num_leaves': 43, 'max_depth': 11, 'learning_rate': 0.011283111006655503, 'lambda_l1': 0.006846257957318063, 'lambda_l2': 0.0029675495453769566, 'feature_fraction': 0.7731672353443658, 'bagging_fraction': 0.877343501035666, 'bagging_freq': 4, 'min_child_samples': 19}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  48%|████████████████████████████████████████████████████▍                                                       | 97/200 [54:20<1:19:06, 46.09s/it]

[I 2026-05-24 01:08:59,428] Trial 106 pruned.

Best trial: 29. Best value: 0.949883:  49%|████████████████████████████████████████████████████▉                                                       | 98/200 [54:31<1:00:13, 35.42s/it]

[I 2026-05-24 01:09:09,965] Trial 99 finished with value: 0.9497998655138232 and parameters: {'num_leaves': 38, 'max_depth': 4, 'learning_rate': 0.011245787536837963, 'lambda_l1': 0.007450254856727838, 'lambda_l2': 0.003031918359836944, 'feature_fraction': 0.873227081106621, 'bagging_fraction': 0.7070202087814056, 'bagging_freq': 7, 'min_child_samples': 18}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  50%|█████████████████████████████████████████████████████▍                                                      | 99/200 [55:11<1:02:01, 36.85s/it]

[I 2026-05-24 01:09:50,137] Trial 102 finished with value: 0.9498650284122329 and parameters: {'num_leaves': 211, 'max_depth': 3, 'learning_rate': 0.011576389362432701, 'lambda_l1': 0.006853786612723818, 'lambda_l2': 0.009898267723788493, 'feature_fraction': 0.7691042611291499, 'bagging_fraction': 0.700851724390723, 'bagging_freq': 7, 'min_child_samples': 12}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  50%|██████████████████████████████████████████████████████▌                                                      | 100/200 [55:26<50:40, 30.40s/it]

[I 2026-05-24 01:10:05,496] Trial 100 finished with value: 0.9497994145166444 and parameters: {'num_leaves': 146, 'max_depth': 4, 'learning_rate': 0.011546593053739175, 'lambda_l1': 0.005336622576796558, 'lambda_l2': 0.0028670960214383923, 'feature_fraction': 0.7186529961922069, 'bagging_fraction': 0.7007668809206163, 'bagging_freq': 7, 'min_child_samples': 19}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  50%|██████████████████████████████████████████████████████                                                     | 101/200 [56:56<1:19:17, 48.06s/it]

[I 2026-05-24 01:11:34,752] Trial 107 finished with value: 0.9496501490255275 and parameters: {'num_leaves': 213, 'max_depth': 3, 'learning_rate': 0.03715968403002433, 'lambda_l1': 0.02666126425285677, 'lambda_l2': 0.0018769617018400812, 'feature_fraction': 0.8239620438048131, 'bagging_fraction': 0.7075213328562877, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  51%|███████████████████████████████████████████████████████▌                                                     | 102/200 [57:03<58:48, 36.01s/it]

[I 2026-05-24 01:11:42,649] Trial 105 finished with value: 0.9493984621677152 and parameters: {'num_leaves': 47, 'max_depth': 9, 'learning_rate': 0.011748203001343162, 'lambda_l1': 0.0065774171686514855, 'lambda_l2': 0.0018684406111423783, 'feature_fraction': 0.8761903275437983, 'bagging_fraction': 0.7077079113953387, 'bagging_freq': 7, 'min_child_samples': 11}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  52%|███████████████████████████████████████████████████████                                                    | 103/200 [58:23<1:19:15, 49.03s/it]

[I 2026-05-24 01:13:02,051] Trial 95 pruned.

Best trial: 29. Best value: 0.949883:  52%|████████████████████████████████████████████████████████▋                                                    | 104/200 [58:25<55:45, 34.85s/it]

[I 2026-05-24 01:13:03,836] Trial 109 finished with value: 0.9498566102567796 and parameters: {'num_leaves': 244, 'max_depth': 3, 'learning_rate': 0.014351297295518015, 'lambda_l1': 7.134379515743528, 'lambda_l2': 0.0409898932815964, 'feature_fraction': 0.728056565281661, 'bagging_fraction': 0.690305787165777, 'bagging_freq': 7, 'min_child_samples': 44}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  52%|█████████████████████████████████████████████████████████▏                                                   | 105/200 [58:33<42:29, 26.84s/it]

[I 2026-05-24 01:13:11,971] Trial 98 pruned.

Best trial: 29. Best value: 0.949883:  53%|█████████████████████████████████████████████████████████▊                                                   | 106/200 [59:02<43:03, 27.49s/it]

[I 2026-05-24 01:13:40,969] Trial 103 pruned.

Best trial: 29. Best value: 0.949883:  54%|██████████████████████████████████████████████████████████▎                                                  | 107/200 [59:05<31:12, 20.13s/it]

[I 2026-05-24 01:13:43,936] Trial 110 finished with value: 0.9498537119005318 and parameters: {'num_leaves': 251, 'max_depth': 3, 'learning_rate': 0.014098794417725739, 'lambda_l1': 7.024279041649295, 'lambda_l2': 0.03753523879912701, 'feature_fraction': 0.7152345040389488, 'bagging_fraction': 0.6874537007276919, 'bagging_freq': 7, 'min_child_samples': 44}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  54%|█████████████████████████████████████████████████████████▊                                                 | 108/200 [1:00:01<47:31, 31.00s/it]

[I 2026-05-24 01:14:40,290] Trial 92 finished with value: 0.949368852393517 and parameters: {'num_leaves': 230, 'max_depth': 7, 'learning_rate': 0.01124216561957476, 'lambda_l1': 0.010620881570974747, 'lambda_l2': 0.00952337092926166, 'feature_fraction': 0.778296722116645, 'bagging_fraction': 0.8781681011247522, 'bagging_freq': 4, 'min_child_samples': 19}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  55%|██████████████████████████████████████████████████████████▎                                                | 109/200 [1:00:32<46:55, 30.94s/it]

[I 2026-05-24 01:15:11,088] Trial 101 pruned.

Best trial: 29. Best value: 0.949883:  55%|██████████████████████████████████████████████████████████▊                                                | 110/200 [1:00:45<38:17, 25.53s/it]

[I 2026-05-24 01:15:24,000] Trial 112 finished with value: 0.9498293421556381 and parameters: {'num_leaves': 244, 'max_depth': 3, 'learning_rate': 0.014429656840602378, 'lambda_l1': 0.049522097045668116, 'lambda_l2': 0.006337525604498956, 'feature_fraction': 0.8975933847756096, 'bagging_fraction': 0.6848908230489394, 'bagging_freq': 7, 'min_child_samples': 44}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  56%|███████████████████████████████████████████████████████████▍                                               | 111/200 [1:01:05<35:21, 23.83s/it]

[I 2026-05-24 01:15:43,877] Trial 113 finished with value: 0.94986112016277 and parameters: {'num_leaves': 244, 'max_depth': 3, 'learning_rate': 0.013946054286901714, 'lambda_l1': 6.869841935962161, 'lambda_l2': 0.0065158649685860175, 'feature_fraction': 0.8888687195974808, 'bagging_fraction': 0.6903523077733784, 'bagging_freq': 7, 'min_child_samples': 45}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  56%|███████████████████████████████████████████████████████████▉                                               | 112/200 [1:01:28<34:40, 23.65s/it]

[I 2026-05-24 01:16:07,088] Trial 108 pruned.

Best trial: 29. Best value: 0.949883:  56%|████████████████████████████████████████████████████████████▍                                              | 113/200 [1:02:24<48:27, 33.42s/it]

[I 2026-05-24 01:17:03,303] Trial 114 finished with value: 0.9498392282404857 and parameters: {'num_leaves': 246, 'max_depth': 3, 'learning_rate': 0.014172430729669953, 'lambda_l1': 0.04142609335033754, 'lambda_l2': 0.017899865871034922, 'feature_fraction': 0.8871515904982621, 'bagging_fraction': 0.751778361386608, 'bagging_freq': 7, 'min_child_samples': 37}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  57%|████████████████████████████████████████████████████████████▉                                              | 114/200 [1:02:39<40:05, 27.97s/it]

[I 2026-05-24 01:17:18,545] Trial 116 finished with value: 0.9498407661683371 and parameters: {'num_leaves': 233, 'max_depth': 3, 'learning_rate': 0.01405226701603331, 'lambda_l1': 0.05066710961404794, 'lambda_l2': 0.01814556764700353, 'feature_fraction': 0.8947717184651155, 'bagging_fraction': 0.829092350048398, 'bagging_freq': 7, 'min_child_samples': 37}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  57%|█████████████████████████████████████████████████████████████▌                                             | 115/200 [1:02:42<28:55, 20.41s/it]

[I 2026-05-24 01:17:21,335] Trial 115 finished with value: 0.9495048289612354 and parameters: {'num_leaves': 234, 'max_depth': 3, 'learning_rate': 0.09531721192307734, 'lambda_l1': 7.984968927552031, 'lambda_l2': 0.006378338848173078, 'feature_fraction': 0.8959710565175248, 'bagging_fraction': 0.833490720426521, 'bagging_freq': 7, 'min_child_samples': 52}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  58%|██████████████████████████████████████████████████████████████                                             | 116/200 [1:03:06<30:01, 21.45s/it]

[I 2026-05-24 01:17:45,195] Trial 117 finished with value: 0.9498529249360692 and parameters: {'num_leaves': 233, 'max_depth': 3, 'learning_rate': 0.012191960423975034, 'lambda_l1': 0.04489543414219611, 'lambda_l2': 0.005815985175806931, 'feature_fraction': 0.889278022694394, 'bagging_fraction': 0.7267790624955122, 'bagging_freq': 6, 'min_child_samples': 25}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  58%|██████████████████████████████████████████████████████████████▌                                            | 117/200 [1:03:08<21:34, 15.59s/it]

[I 2026-05-24 01:17:47,122] Trial 118 finished with value: 0.9498513856888271 and parameters: {'num_leaves': 244, 'max_depth': 3, 'learning_rate': 0.012347153003708767, 'lambda_l1': 0.03617214770180417, 'lambda_l2': 0.01840522041022357, 'feature_fraction': 0.8916640747482782, 'bagging_fraction': 0.727504902344358, 'bagging_freq': 6, 'min_child_samples': 67}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  59%|███████████████████████████████████████████████████████████████▏                                           | 118/200 [1:03:57<34:50, 25.50s/it]

[I 2026-05-24 01:18:35,737] Trial 123 pruned.

Best trial: 29. Best value: 0.949883:  60%|███████████████████████████████████████████████████████████████▋                                           | 119/200 [1:04:02<26:11, 19.40s/it]

[I 2026-05-24 01:18:40,900] Trial 119 finished with value: 0.9498436794517108 and parameters: {'num_leaves': 245, 'max_depth': 3, 'learning_rate': 0.012362952769760968, 'lambda_l1': 0.035159440756020725, 'lambda_l2': 0.001039413419097623, 'feature_fraction': 0.9887727503862808, 'bagging_fraction': 0.665501683109033, 'bagging_freq': 6, 'min_child_samples': 66}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  60%|████████████████████████████████████████████████████████████████▏                                          | 120/200 [1:04:11<21:46, 16.33s/it]

[I 2026-05-24 01:18:50,072] Trial 104 pruned.

Best trial: 29. Best value: 0.949883:  60%|████████████████████████████████████████████████████████████████▋                                          | 121/200 [1:04:48<29:40, 22.54s/it]

[I 2026-05-24 01:19:27,109] Trial 120 finished with value: 0.9498683861289884 and parameters: {'num_leaves': 234, 'max_depth': 3, 'learning_rate': 0.012114838607725662, 'lambda_l1': 7.421123687961532, 'lambda_l2': 0.0059701104059244475, 'feature_fraction': 0.895710306830999, 'bagging_fraction': 0.7272279025817959, 'bagging_freq': 6, 'min_child_samples': 37}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  61%|█████████████████████████████████████████████████████████████████▎                                         | 122/200 [1:04:53<22:25, 17.25s/it]

[I 2026-05-24 01:19:32,022] Trial 121 finished with value: 0.9498685053243268 and parameters: {'num_leaves': 233, 'max_depth': 3, 'learning_rate': 0.012182203243055918, 'lambda_l1': 0.06940645838618047, 'lambda_l2': 0.018132076992866827, 'feature_fraction': 0.8470447130631822, 'bagging_fraction': 0.7249826044298804, 'bagging_freq': 6, 'min_child_samples': 16}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  62%|█████████████████████████████████████████████████████████████████▊                                         | 123/200 [1:05:11<22:31, 17.55s/it]

[I 2026-05-24 01:19:50,267] Trial 122 finished with value: 0.9498585277595621 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.011968718684613765, 'lambda_l1': 0.08901300698269222, 'lambda_l2': 0.017037413198551437, 'feature_fraction': 0.9249322014143964, 'bagging_fraction': 0.7284804897909616, 'bagging_freq': 6, 'min_child_samples': 37}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  62%|██████████████████████████████████████████████████████████████████▎                                        | 124/200 [1:06:32<46:13, 36.50s/it]

[I 2026-05-24 01:21:10,975] Trial 124 finished with value: 0.9498662671352489 and parameters: {'num_leaves': 251, 'max_depth': 3, 'learning_rate': 0.012254985845308125, 'lambda_l1': 0.09087312364312976, 'lambda_l2': 0.011312986801579657, 'feature_fraction': 0.8046290185397909, 'bagging_fraction': 0.7265919582270667, 'bagging_freq': 6, 'min_child_samples': 17}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  62%|██████████████████████████████████████████████████████████████████▉                                        | 125/200 [1:06:46<37:11, 29.75s/it]

[I 2026-05-24 01:21:24,988] Trial 125 finished with value: 0.9498499752372311 and parameters: {'num_leaves': 251, 'max_depth': 3, 'learning_rate': 0.012458360987806848, 'lambda_l1': 0.003093316892776308, 'lambda_l2': 0.01158888638575931, 'feature_fraction': 0.9254832754412795, 'bagging_fraction': 0.6671292368767886, 'bagging_freq': 6, 'min_child_samples': 16}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  63%|███████████████████████████████████████████████████████████████████▍                                       | 126/200 [1:06:50<27:23, 22.21s/it]

[I 2026-05-24 01:21:29,610] Trial 126 finished with value: 0.9498565423061865 and parameters: {'num_leaves': 251, 'max_depth': 3, 'learning_rate': 0.012342322237260927, 'lambda_l1': 0.0939094149819798, 'lambda_l2': 0.011636802847129204, 'feature_fraction': 0.9778686149664313, 'bagging_fraction': 0.7300395202153726, 'bagging_freq': 6, 'min_child_samples': 16}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  64%|███████████████████████████████████████████████████████████████████▉                                       | 127/200 [1:07:14<27:28, 22.58s/it]

[I 2026-05-24 01:21:53,037] Trial 128 finished with value: 0.9498708207982988 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.010612772080211776, 'lambda_l1': 0.08064800584257065, 'lambda_l2': 0.011273344890830535, 'feature_fraction': 0.9244226777544355, 'bagging_fraction': 0.6673193824191208, 'bagging_freq': 6, 'min_child_samples': 17}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  64%|████████████████████████████████████████████████████████████████████▍                                      | 128/200 [1:07:14<19:03, 15.88s/it]

[I 2026-05-24 01:21:53,285] Trial 127 finished with value: 0.9498603453701244 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.011982978031448375, 'lambda_l1': 0.07697151181569019, 'lambda_l2': 0.011592514509887176, 'feature_fraction': 0.923920413581668, 'bagging_fraction': 0.6666939242660916, 'bagging_freq': 6, 'min_child_samples': 16}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  64%|█████████████████████████████████████████████████████████████████████                                      | 129/200 [1:08:06<31:25, 26.56s/it]

[I 2026-05-24 01:22:44,758] Trial 130 finished with value: 0.949877857578899 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.010474029203940366, 'lambda_l1': 1.551015650465951, 'lambda_l2': 0.011031608087616709, 'feature_fraction': 0.8045563907005452, 'bagging_fraction': 0.6442965144940045, 'bagging_freq': 7, 'min_child_samples': 17}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  65%|█████████████████████████████████████████████████████████████████████▌                                     | 130/200 [1:08:09<22:57, 19.68s/it]

[I 2026-05-24 01:22:48,380] Trial 129 finished with value: 0.9498539345728545 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.012246156413252197, 'lambda_l1': 0.09201217384212947, 'lambda_l2': 0.01153455174306353, 'feature_fraction': 0.8468629184869548, 'bagging_fraction': 0.7761268121268377, 'bagging_freq': 7, 'min_child_samples': 17}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  66%|██████████████████████████████████████████████████████████████████████                                     | 131/200 [1:08:16<18:10, 15.80s/it]

[I 2026-05-24 01:22:55,152] Trial 131 finished with value: 0.9498736438757931 and parameters: {'num_leaves': 253, 'max_depth': 3, 'learning_rate': 0.010589996986309528, 'lambda_l1': 0.33855706713211065, 'lambda_l2': 0.011340257558070816, 'feature_fraction': 0.8505697493712611, 'bagging_fraction': 0.6426585063339715, 'bagging_freq': 7, 'min_child_samples': 91}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  66%|██████████████████████████████████████████████████████████████████████▌                                    | 132/200 [1:08:23<14:51, 13.12s/it]

[I 2026-05-24 01:23:01,998] Trial 111 finished with value: 0.9493579151114819 and parameters: {'num_leaves': 244, 'max_depth': 7, 'learning_rate': 0.014610809881214139, 'lambda_l1': 6.883750653591517, 'lambda_l2': 0.006227801862162268, 'feature_fraction': 0.8245205919996464, 'bagging_fraction': 0.6844906419091621, 'bagging_freq': 7, 'min_child_samples': 45}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  66%|███████████████████████████████████████████████████████████████████████▏                                   | 133/200 [1:08:51<19:48, 17.74s/it]

[I 2026-05-24 01:23:30,541] Trial 132 finished with value: 0.9498655883190843 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.010554505600761611, 'lambda_l1': 0.10594597219689028, 'lambda_l2': 0.011777804653319363, 'feature_fraction': 0.9199374623329742, 'bagging_fraction': 0.6361295908053148, 'bagging_freq': 7, 'min_child_samples': 16}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  67%|███████████████████████████████████████████████████████████████████████▋                                   | 134/200 [1:08:56<15:10, 13.80s/it]

[I 2026-05-24 01:23:35,122] Trial 133 finished with value: 0.9498825538721831 and parameters: {'num_leaves': 252, 'max_depth': 3, 'learning_rate': 0.01051983102732146, 'lambda_l1': 0.10110001282731622, 'lambda_l2': 0.011872007669027289, 'feature_fraction': 0.8007319584464809, 'bagging_fraction': 0.6709786807072929, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  68%|████████████████████████████████████████████████████████████████████████▏                                  | 135/200 [1:09:15<16:38, 15.36s/it]

[I 2026-05-24 01:23:54,137] Trial 134 finished with value: 0.9498686472926761 and parameters: {'num_leaves': 253, 'max_depth': 3, 'learning_rate': 0.01048598940280612, 'lambda_l1': 0.1428099678483681, 'lambda_l2': 0.011131442482506138, 'feature_fraction': 0.9708003457743232, 'bagging_fraction': 0.6474716238690779, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  68%|████████████████████████████████████████████████████████████████████████▊                                  | 136/200 [1:11:31<55:02, 51.59s/it]

[I 2026-05-24 01:26:10,268] Trial 135 finished with value: 0.94980486284179 and parameters: {'num_leaves': 253, 'max_depth': 4, 'learning_rate': 0.010416935062302006, 'lambda_l1': 0.16282419110372934, 'lambda_l2': 0.011561642767724872, 'feature_fraction': 0.6129158629301015, 'bagging_fraction': 0.6618009329581991, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  68%|█████████████████████████████████████████████████████████████████████████▎                                 | 137/200 [1:11:44<42:05, 40.08s/it]

[I 2026-05-24 01:26:23,500] Trial 136 finished with value: 0.949815134763826 and parameters: {'num_leaves': 174, 'max_depth': 4, 'learning_rate': 0.010460643231837942, 'lambda_l1': 0.1423934922058574, 'lambda_l2': 0.003965507509557399, 'feature_fraction': 0.9715700670193831, 'bagging_fraction': 0.6369219870477388, 'bagging_freq': 7, 'min_child_samples': 31}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  69%|█████████████████████████████████████████████████████████████████████████▊                                 | 138/200 [1:11:52<31:24, 30.39s/it]

[I 2026-05-24 01:26:31,284] Trial 137 finished with value: 0.949800044403591 and parameters: {'num_leaves': 223, 'max_depth': 4, 'learning_rate': 0.010595741736751804, 'lambda_l1': 0.14598590931222535, 'lambda_l2': 0.0037688012954967694, 'feature_fraction': 0.9210452002927701, 'bagging_fraction': 0.6810987111032496, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  70%|██████████████████████████████████████████████████████████████████████████▎                                | 139/200 [1:12:14<28:12, 27.75s/it]

[I 2026-05-24 01:26:52,868] Trial 139 finished with value: 0.9498095550772163 and parameters: {'num_leaves': 224, 'max_depth': 4, 'learning_rate': 0.010578252008231932, 'lambda_l1': 0.31663434403542173, 'lambda_l2': 0.01540982479745792, 'feature_fraction': 0.9575315561789649, 'bagging_fraction': 0.6448635904020277, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  70%|██████████████████████████████████████████████████████████████████████████▉                                | 140/200 [1:12:25<22:44, 22.74s/it]

[I 2026-05-24 01:27:03,907] Trial 138 finished with value: 0.9498187341525759 and parameters: {'num_leaves': 220, 'max_depth': 4, 'learning_rate': 0.010040122605963833, 'lambda_l1': 0.14786732000407812, 'lambda_l2': 0.45328046034643493, 'feature_fraction': 0.7634234455896541, 'bagging_fraction': 0.7550893889091416, 'bagging_freq': 7, 'min_child_samples': 12}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  70%|███████████████████████████████████████████████████████████████████████████▍                               | 141/200 [1:13:08<28:30, 29.00s/it]

[I 2026-05-24 01:27:47,509] Trial 141 finished with value: 0.9498209449441655 and parameters: {'num_leaves': 256, 'max_depth': 4, 'learning_rate': 0.010663494676014762, 'lambda_l1': 0.5649060857169297, 'lambda_l2': 0.05988379436302463, 'feature_fraction': 0.7648354118254246, 'bagging_fraction': 0.6392891393563364, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  71%|███████████████████████████████████████████████████████████████████████████▉                               | 142/200 [1:13:10<20:02, 20.73s/it]

[I 2026-05-24 01:27:48,944] Trial 140 finished with value: 0.9498366538639915 and parameters: {'num_leaves': 221, 'max_depth': 4, 'learning_rate': 0.010625688997402679, 'lambda_l1': 9.94455851270355, 'lambda_l2': 0.003713890637869805, 'feature_fraction': 0.6529047099529534, 'bagging_fraction': 0.6348101553139918, 'bagging_freq': 7, 'min_child_samples': 14}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  72%|████████████████████████████████████████████████████████████████████████████▌                              | 143/200 [1:13:18<16:07, 16.98s/it]

[I 2026-05-24 01:27:57,167] Trial 142 finished with value: 0.9498186183228642 and parameters: {'num_leaves': 256, 'max_depth': 4, 'learning_rate': 0.010637098739335573, 'lambda_l1': 0.3288018660668572, 'lambda_l2': 0.004275743489745308, 'feature_fraction': 0.8249945508302213, 'bagging_fraction': 0.6363066023615885, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  72%|█████████████████████████████████████████████████████████████████████████████                              | 144/200 [1:13:24<12:53, 13.81s/it]

[I 2026-05-24 01:28:03,593] Trial 143 finished with value: 0.949812721349919 and parameters: {'num_leaves': 256, 'max_depth': 4, 'learning_rate': 0.010619355428862227, 'lambda_l1': 0.3819486774464554, 'lambda_l2': 0.0036315362262085006, 'feature_fraction': 0.868460065402355, 'bagging_fraction': 0.6356888091016827, 'bagging_freq': 7, 'min_child_samples': 96}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  72%|█████████████████████████████████████████████████████████████████████████████▌                             | 145/200 [1:13:50<15:53, 17.33s/it]

[I 2026-05-24 01:28:29,140] Trial 144 finished with value: 0.9498184503488087 and parameters: {'num_leaves': 175, 'max_depth': 4, 'learning_rate': 0.010452518504824914, 'lambda_l1': 0.3851670981049062, 'lambda_l2': 0.003985798775767387, 'feature_fraction': 0.634342511235492, 'bagging_fraction': 0.6451148849576241, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  73%|██████████████████████████████████████████████████████████████████████████████                             | 146/200 [1:13:56<12:35, 13.98s/it]

[I 2026-05-24 01:28:35,296] Trial 145 finished with value: 0.9498282242995415 and parameters: {'num_leaves': 222, 'max_depth': 4, 'learning_rate': 0.010017955341800713, 'lambda_l1': 0.16171385834488897, 'lambda_l2': 0.003822302195814618, 'feature_fraction': 0.8298724218924268, 'bagging_fraction': 0.6508356067924479, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  74%|██████████████████████████████████████████████████████████████████████████████▋                            | 147/200 [1:14:28<17:07, 19.40s/it]

[I 2026-05-24 01:29:07,333] Trial 146 finished with value: 0.9498242847734126 and parameters: {'num_leaves': 256, 'max_depth': 4, 'learning_rate': 0.010067993222228205, 'lambda_l1': 0.5398656391478369, 'lambda_l2': 0.0036722123299393243, 'feature_fraction': 0.7629179090327343, 'bagging_fraction': 0.7146629333057776, 'bagging_freq': 7, 'min_child_samples': 12}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  74%|███████████████████████████████████████████████████████████████████████████████▏                           | 148/200 [1:15:58<35:08, 40.56s/it]

[I 2026-05-24 01:30:37,267] Trial 149 finished with value: 0.9498783306046381 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.010030963021965676, 'lambda_l1': 9.864782913293341, 'lambda_l2': 0.9977310251150846, 'feature_fraction': 0.7649545392024725, 'bagging_fraction': 0.6122067305535457, 'bagging_freq': 7, 'min_child_samples': 14}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  74%|███████████████████████████████████████████████████████████████████████████████▋                           | 149/200 [1:16:14<28:11, 33.18s/it]

[I 2026-05-24 01:30:53,220] Trial 150 finished with value: 0.9497332333402297 and parameters: {'num_leaves': 256, 'max_depth': 3, 'learning_rate': 0.029794457174487032, 'lambda_l1': 1.397471085415204, 'lambda_l2': 0.00795881988767668, 'feature_fraction': 0.6287641084030553, 'bagging_fraction': 0.6171980884205076, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  75%|████████████████████████████████████████████████████████████████████████████████▎                          | 150/200 [1:16:28<22:53, 27.48s/it]

[I 2026-05-24 01:31:07,405] Trial 151 finished with value: 0.9498786529902672 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.010059387886948728, 'lambda_l1': 0.46817502410296147, 'lambda_l2': 0.005119610999291485, 'feature_fraction': 0.8002013073681373, 'bagging_fraction': 0.6177186421071097, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  76%|████████████████████████████████████████████████████████████████████████████████▊                          | 151/200 [1:16:43<19:18, 23.65s/it]

[I 2026-05-24 01:31:22,100] Trial 147 finished with value: 0.9498385843374411 and parameters: {'num_leaves': 256, 'max_depth': 4, 'learning_rate': 0.01066649834467609, 'lambda_l1': 9.966442474425756, 'lambda_l2': 0.3275908703266317, 'feature_fraction': 0.8037581154479794, 'bagging_fraction': 0.7172333528181034, 'bagging_freq': 7, 'min_child_samples': 12}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  76%|█████████████████████████████████████████████████████████████████████████████████▎                         | 152/200 [1:16:58<16:44, 20.92s/it]

[I 2026-05-24 01:31:36,674] Trial 148 finished with value: 0.9498380882718369 and parameters: {'num_leaves': 240, 'max_depth': 4, 'learning_rate': 0.010024232877441298, 'lambda_l1': 9.419673373709383, 'lambda_l2': 0.003938110136391734, 'feature_fraction': 0.8035640163217576, 'bagging_fraction': 0.7469564869409775, 'bagging_freq': 7, 'min_child_samples': 13}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  76%|█████████████████████████████████████████████████████████████████████████████████▊                         | 153/200 [1:17:07<13:38, 17.42s/it]

[I 2026-05-24 01:31:45,924] Trial 152 finished with value: 0.9497175426404073 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.029578996399096964, 'lambda_l1': 1.599745814042439, 'lambda_l2': 0.008117953232768921, 'feature_fraction': 0.8067016656887517, 'bagging_fraction': 0.6032663561187472, 'bagging_freq': 7, 'min_child_samples': 79}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  77%|██████████████████████████████████████████████████████████████████████████████████▍                        | 154/200 [1:17:08<09:40, 12.62s/it]

[I 2026-05-24 01:31:47,347] Trial 153 finished with value: 0.949728151224247 and parameters: {'num_leaves': 256, 'max_depth': 3, 'learning_rate': 0.028776481851034548, 'lambda_l1': 1.5275142966538833, 'lambda_l2': 0.007969956582260634, 'feature_fraction': 0.8092839559779751, 'bagging_fraction': 0.6068418208221513, 'bagging_freq': 7, 'min_child_samples': 84}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  78%|██████████████████████████████████████████████████████████████████████████████████▉                        | 155/200 [1:17:24<10:17, 13.71s/it]

[I 2026-05-24 01:32:03,612] Trial 154 finished with value: 0.949873401636901 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.011010577291163929, 'lambda_l1': 1.635202617259026, 'lambda_l2': 0.007918929778106737, 'feature_fraction': 0.8092381313465657, 'bagging_fraction': 0.6204650536745169, 'bagging_freq': 7, 'min_child_samples': 11}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  78%|███████████████████████████████████████████████████████████████████████████████████▍                       | 156/200 [1:17:28<07:49, 10.68s/it]

[I 2026-05-24 01:32:07,216] Trial 155 finished with value: 0.949855059649966 and parameters: {'num_leaves': 241, 'max_depth': 3, 'learning_rate': 0.01314792085678056, 'lambda_l1': 2.476557703160786, 'lambda_l2': 0.007922053450766676, 'feature_fraction': 0.8004862428264901, 'bagging_fraction': 0.6213431004974789, 'bagging_freq': 7, 'min_child_samples': 59}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 29. Best value: 0.949883:  78%|███████████████████████████████████████████████████████████████████████████████████▉                       | 157/200 [1:17:58<11:45, 16.40s/it]

[I 2026-05-24 01:32:36,957] Trial 157 finished with value: 0.9498626775444343 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.011110088430066624, 'lambda_l1': 0.867889843461371, 'lambda_l2': 0.008151289199114321, 'feature_fraction': 0.8029180489224526, 'bagging_fraction': 0.616979235810981, 'bagging_freq': 7, 'min_child_samples': 87}. Best is trial 29 with value: 0.9498826283087837.

Best trial: 156. Best value: 0.949885:  79%|███████████████████████████████████████████████████████████████████████████████████▋                      | 158/200 [1:17:59<08:11, 11.71s/it]

[I 2026-05-24 01:32:37,730] Trial 156 finished with value: 0.9498845985847343 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.010013285874373118, 'lambda_l1': 6.057703941240154, 'lambda_l2': 9.259954338472756, 'feature_fraction': 0.8104593555750118, 'bagging_fraction': 0.6535215604566582, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  80%|████████████████████████████████████████████████████████████████████████████████████▎                     | 159/200 [1:18:30<12:04, 17.67s/it]

[I 2026-05-24 01:33:09,310] Trial 158 finished with value: 0.9498731703755524 and parameters: {'num_leaves': 242, 'max_depth': 3, 'learning_rate': 0.011122969849415264, 'lambda_l1': 3.3696513402384207, 'lambda_l2': 0.007942674705525114, 'feature_fraction': 0.8031002856136028, 'bagging_fraction': 0.6084392554929444, 'bagging_freq': 7, 'min_child_samples': 80}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  80%|████████████████████████████████████████████████████████████████████████████████████▊                     | 160/200 [1:20:23<30:50, 46.27s/it]

[I 2026-05-24 01:35:02,299] Trial 159 finished with value: 0.9498748779391141 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.011381062861732108, 'lambda_l1': 9.594675426611646, 'lambda_l2': 6.734922305842128, 'feature_fraction': 0.8010580365078704, 'bagging_fraction': 0.617373366958695, 'bagging_freq': 2, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  80%|█████████████████████████████████████████████████████████████████████████████████████▎                    | 161/200 [1:20:45<25:22, 39.04s/it]

[I 2026-05-24 01:35:24,465] Trial 162 finished with value: 0.9498737238575717 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.011441208364838184, 'lambda_l1': 0.9466170246692203, 'lambda_l2': 6.435976446162947, 'feature_fraction': 0.8092395946549001, 'bagging_fraction': 0.602199058003826, 'bagging_freq': 7, 'min_child_samples': 11}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  81%|█████████████████████████████████████████████████████████████████████████████████████▊                    | 162/200 [1:20:53<18:44, 29.60s/it]

[I 2026-05-24 01:35:32,034] Trial 160 finished with value: 0.949858205451736 and parameters: {'num_leaves': 241, 'max_depth': 3, 'learning_rate': 0.013225402459459438, 'lambda_l1': 2.3590380234854615, 'lambda_l2': 1.741479593110375, 'feature_fraction': 0.7986676911697272, 'bagging_fraction': 0.85609947058191, 'bagging_freq': 2, 'min_child_samples': 11}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  82%|██████████████████████████████████████████████████████████████████████████████████████▍                   | 163/200 [1:20:54<12:55, 20.96s/it]

[I 2026-05-24 01:35:32,838] Trial 161 finished with value: 0.9498712766630387 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.011322813491929474, 'lambda_l1': 0.79300747761382, 'lambda_l2': 0.00571322873365296, 'feature_fraction': 0.8063445178054565, 'bagging_fraction': 0.8411136818821828, 'bagging_freq': 5, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  82%|██████████████████████████████████████████████████████████████████████████████████████▉                   | 164/200 [1:21:02<10:14, 17.07s/it]

[I 2026-05-24 01:35:40,839] Trial 163 finished with value: 0.94987067564842 and parameters: {'num_leaves': 240, 'max_depth': 3, 'learning_rate': 0.011335613809861944, 'lambda_l1': 0.8419304825850588, 'lambda_l2': 0.0052075614134432565, 'feature_fraction': 0.8180661730007933, 'bagging_fraction': 0.6103735038719802, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  82%|███████████████████████████████████████████████████████████████████████████████████████▍                  | 165/200 [1:21:11<08:38, 14.80s/it]

[I 2026-05-24 01:35:50,346] Trial 164 finished with value: 0.9498678583627237 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.011282538520444873, 'lambda_l1': 0.851872427637908, 'lambda_l2': 0.7560299721867347, 'feature_fraction': 0.7428190437304425, 'bagging_fraction': 0.6218504559251669, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  83%|███████████████████████████████████████████████████████████████████████████████████████▉                  | 166/200 [1:21:18<07:03, 12.47s/it]

[I 2026-05-24 01:35:57,366] Trial 165 finished with value: 0.9498713492710671 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.011293752502652259, 'lambda_l1': 2.4258936354628333, 'lambda_l2': 1.1780750559674709, 'feature_fraction': 0.7435366961428193, 'bagging_fraction': 0.6236523791371411, 'bagging_freq': 5, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  84%|████████████████████████████████████████████████████████████████████████████████████████▌                 | 167/200 [1:21:35<07:29, 13.63s/it]

[I 2026-05-24 01:36:13,718] Trial 166 finished with value: 0.9498687835216432 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.011469549562307715, 'lambda_l1': 6.045577512138334, 'lambda_l2': 0.005718534750589942, 'feature_fraction': 0.7527462693119706, 'bagging_fraction': 0.6130375722474911, 'bagging_freq': 7, 'min_child_samples': 15}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  84%|█████████████████████████████████████████████████████████████████████████████████████████                 | 168/200 [1:21:41<06:03, 11.35s/it]

[I 2026-05-24 01:36:19,746] Trial 167 finished with value: 0.9498693615558016 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.011348986056579137, 'lambda_l1': 0.9550083625896904, 'lambda_l2': 0.005615464661002609, 'feature_fraction': 0.7537657851965917, 'bagging_fraction': 0.615499944984389, 'bagging_freq': 5, 'min_child_samples': 31}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  84%|█████████████████████████████████████████████████████████████████████████████████████████▌                | 169/200 [1:22:20<10:14, 19.84s/it]

[I 2026-05-24 01:36:59,380] Trial 169 finished with value: 0.9498759777071978 and parameters: {'num_leaves': 248, 'max_depth': 3, 'learning_rate': 0.011361844974218934, 'lambda_l1': 6.20043242013949, 'lambda_l2': 2.6642262973840807, 'feature_fraction': 0.7457882975267284, 'bagging_fraction': 0.6568730244408202, 'bagging_freq': 5, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  85%|██████████████████████████████████████████████████████████████████████████████████████████                | 170/200 [1:22:35<09:12, 18.40s/it]

[I 2026-05-24 01:37:14,432] Trial 168 finished with value: 0.9498770894882659 and parameters: {'num_leaves': 246, 'max_depth': 3, 'learning_rate': 0.011555171199023388, 'lambda_l1': 6.112638387706868, 'lambda_l2': 0.005550103141398741, 'feature_fraction': 0.7828591098010824, 'bagging_fraction': 0.6926458365391948, 'bagging_freq': 2, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  86%|██████████████████████████████████████████████████████████████████████████████████████████▋               | 171/200 [1:23:05<10:31, 21.77s/it]

[I 2026-05-24 01:37:44,073] Trial 170 finished with value: 0.949527460143635 and parameters: {'num_leaves': 75, 'max_depth': 3, 'learning_rate': 0.07546346284691703, 'lambda_l1': 4.174132093926706, 'lambda_l2': 2.0636966142183026, 'feature_fraction': 0.748299521118166, 'bagging_fraction': 0.8498503415189623, 'bagging_freq': 5, 'min_child_samples': 15}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  86%|███████████████████████████████████████████████████████████████████████████████████████████▏              | 172/200 [1:25:11<24:48, 53.18s/it]

[I 2026-05-24 01:39:50,525] Trial 174 finished with value: 0.9498699564475587 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.01168672347532502, 'lambda_l1': 6.383671694205559, 'lambda_l2': 7.425217360402682, 'feature_fraction': 0.7457056458764988, 'bagging_fraction': 0.99977286010272, 'bagging_freq': 1, 'min_child_samples': 15}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  86%|███████████████████████████████████████████████████████████████████████████████████████████▋              | 173/200 [1:25:18<17:41, 39.30s/it]

[I 2026-05-24 01:39:57,460] Trial 172 finished with value: 0.9498735942762874 and parameters: {'num_leaves': 72, 'max_depth': 3, 'learning_rate': 0.011627464074429888, 'lambda_l1': 8.043753120740265, 'lambda_l2': 7.339210890044659, 'feature_fraction': 0.7824652140168623, 'bagging_fraction': 0.8436534559664246, 'bagging_freq': 1, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  87%|████████████████████████████████████████████████████████████████████████████████████████████▏             | 174/200 [1:25:31<13:31, 31.21s/it]

[I 2026-05-24 01:40:09,797] Trial 171 finished with value: 0.9498741871632645 and parameters: {'num_leaves': 74, 'max_depth': 3, 'learning_rate': 0.011475853034088419, 'lambda_l1': 7.784703429888487, 'lambda_l2': 7.199220253824004, 'feature_fraction': 0.8158232768835113, 'bagging_fraction': 0.86034548444334, 'bagging_freq': 2, 'min_child_samples': 15}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  88%|████████████████████████████████████████████████████████████████████████████████████████████▊             | 175/200 [1:25:42<10:28, 25.14s/it]

[I 2026-05-24 01:40:20,756] Trial 175 finished with value: 0.9498701688089681 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.011725187093140715, 'lambda_l1': 6.330273721246083, 'lambda_l2': 2.4901384809064595, 'feature_fraction': 0.7809947889027001, 'bagging_fraction': 0.6566727182985241, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  88%|█████████████████████████████████████████████████████████████████████████████████████████████▎            | 176/200 [1:25:55<08:36, 21.51s/it]

[I 2026-05-24 01:40:33,787] Trial 176 finished with value: 0.9496563071512035 and parameters: {'num_leaves': 248, 'max_depth': 3, 'learning_rate': 0.05980884415487005, 'lambda_l1': 6.731216120415577, 'lambda_l2': 3.543882829982357, 'feature_fraction': 0.7848707052140117, 'bagging_fraction': 0.6575489051392811, 'bagging_freq': 1, 'min_child_samples': 15}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  88%|█████████████████████████████████████████████████████████████████████████████████████████████▊            | 177/200 [1:26:09<07:22, 19.23s/it]

[I 2026-05-24 01:40:47,698] Trial 177 finished with value: 0.9495895431225323 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.07737471620272622, 'lambda_l1': 6.211872541044845, 'lambda_l2': 8.357288191519022, 'feature_fraction': 0.783107916129098, 'bagging_fraction': 0.656658389801983, 'bagging_freq': 2, 'min_child_samples': 15}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 156. Best value: 0.949885:  89%|██████████████████████████████████████████████████████████████████████████████████████████████▎           | 178/200 [1:26:09<04:59, 13.62s/it]

[I 2026-05-24 01:40:48,238] Trial 173 finished with value: 0.949869339470021 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.011630392711944326, 'lambda_l1': 5.988496457855763, 'lambda_l2': 9.459876484518658, 'feature_fraction': 0.8198321505176228, 'bagging_fraction': 0.9207007608669145, 'bagging_freq': 2, 'min_child_samples': 10}. Best is trial 156 with value: 0.9498845985847343.

Best trial: 178. Best value: 0.949885:  90%|██████████████████████████████████████████████████████████████████████████████████████████████▊           | 179/200 [1:26:12<03:41, 10.54s/it]

[I 2026-05-24 01:40:51,606] Trial 178 finished with value: 0.9498851961995036 and parameters: {'num_leaves': 247, 'max_depth': 3, 'learning_rate': 0.010067925567094994, 'lambda_l1': 6.524408654498392, 'lambda_l2': 9.468905803303532, 'feature_fraction': 0.7791342817022583, 'bagging_fraction': 0.6948458672742674, 'bagging_freq': 1, 'min_child_samples': 15}. Best is trial 178 with value: 0.9498851961995036.

Best trial: 178. Best value: 0.949885:  90%|███████████████████████████████████████████████████████████████████████████████████████████████▍          | 180/200 [1:26:42<05:23, 16.15s/it]

[I 2026-05-24 01:41:20,852] Trial 179 finished with value: 0.9495806627761167 and parameters: {'num_leaves': 234, 'max_depth': 3, 'learning_rate': 0.07676422398318163, 'lambda_l1': 6.253248572727533, 'lambda_l2': 7.181985031673894, 'feature_fraction': 0.7842489812918443, 'bagging_fraction': 0.6957905135038281, 'bagging_freq': 2, 'min_child_samples': 18}. Best is trial 178 with value: 0.9498851961995036.

Best trial: 178. Best value: 0.949885:  90%|███████████████████████████████████████████████████████████████████████████████████████████████▉          | 181/200 [1:27:05<05:47, 18.30s/it]

[I 2026-05-24 01:41:44,163] Trial 181 finished with value: 0.9496534156179489 and parameters: {'num_leaves': 248, 'max_depth': 3, 'learning_rate': 0.05557930891643192, 'lambda_l1': 6.128121044087467, 'lambda_l2': 4.738290123871446, 'feature_fraction': 0.778735655917514, 'bagging_fraction': 0.6567400920349488, 'bagging_freq': 5, 'min_child_samples': 15}. Best is trial 178 with value: 0.9498851961995036.

Best trial: 178. Best value: 0.949885:  91%|████████████████████████████████████████████████████████████████████████████████████████████████▍         | 182/200 [1:27:16<04:49, 16.10s/it]

[I 2026-05-24 01:41:55,129] Trial 180 finished with value: 0.9496297219516752 and parameters: {'num_leaves': 248, 'max_depth': 3, 'learning_rate': 0.07368826042559817, 'lambda_l1': 8.289808957251422, 'lambda_l2': 9.50291297465387, 'feature_fraction': 0.7769071423885012, 'bagging_fraction': 0.8253093538763773, 'bagging_freq': 2, 'min_child_samples': 15}. Best is trial 178 with value: 0.9498851961995036.

Best trial: 178. Best value: 0.949885:  92%|████████████████████████████████████████████████████████████████████████████████████████████████▉         | 183/200 [1:27:52<06:15, 22.10s/it]

[I 2026-05-24 01:42:31,243] Trial 182 finished with value: 0.9498816653757182 and parameters: {'num_leaves': 248, 'max_depth': 3, 'learning_rate': 0.010157320920531614, 'lambda_l1': 6.12694385242977, 'lambda_l2': 9.84072303123802, 'feature_fraction': 0.7823582242211803, 'bagging_fraction': 0.695597811158665, 'bagging_freq': 2, 'min_child_samples': 15}. Best is trial 178 with value: 0.9498851961995036.

Best trial: 178. Best value: 0.949885:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████▌        | 184/200 [1:29:52<13:41, 51.32s/it]

[I 2026-05-24 01:44:30,726] Trial 183 finished with value: 0.9498831696435308 and parameters: {'num_leaves': 248, 'max_depth': 3, 'learning_rate': 0.010159871404468382, 'lambda_l1': 8.336374887438298, 'lambda_l2': 8.772760508322506, 'feature_fraction': 0.7855126797754226, 'bagging_fraction': 0.6562386546913451, 'bagging_freq': 2, 'min_child_samples': 15}. Best is trial 178 with value: 0.9498851961995036.

Best trial: 184. Best value: 0.949885:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████        | 185/200 [1:29:55<09:16, 37.09s/it]

[I 2026-05-24 01:44:34,608] Trial 184 finished with value: 0.9498852081206932 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.01006912570285503, 'lambda_l1': 8.214714781370546, 'lambda_l2': 3.7929151676120023, 'feature_fraction': 0.7899199083591898, 'bagging_fraction': 0.6555901114219103, 'bagging_freq': 2, 'min_child_samples': 15}. Best is trial 184 with value: 0.9498852081206932.

Best trial: 184. Best value: 0.949885:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████▌       | 186/200 [1:30:07<06:53, 29.53s/it]

[I 2026-05-24 01:44:46,517] Trial 185 finished with value: 0.9498834863124127 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.010044135546741018, 'lambda_l1': 5.660157377831878, 'lambda_l2': 3.362889184080819, 'feature_fraction': 0.7717785686161651, 'bagging_fraction': 0.6602196774309504, 'bagging_freq': 2, 'min_child_samples': 14}. Best is trial 184 with value: 0.9498852081206932.

Best trial: 186. Best value: 0.949886:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████       | 187/200 [1:30:20<05:17, 24.43s/it]

[I 2026-05-24 01:44:59,050] Trial 186 finished with value: 0.9498856935231969 and parameters: {'num_leaves': 249, 'max_depth': 3, 'learning_rate': 0.010039679039207435, 'lambda_l1': 3.778717188646178, 'lambda_l2': 3.5913533331119214, 'feature_fraction': 0.7905843441379262, 'bagging_fraction': 0.6558907986733994, 'bagging_freq': 2, 'min_child_samples': 17}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████▋      | 188/200 [1:30:32<04:09, 20.77s/it]

[I 2026-05-24 01:45:11,259] Trial 190 finished with value: 0.9498834811015341 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.010095333540880855, 'lambda_l1': 3.8267589969946694, 'lambda_l2': 4.313237903260125, 'feature_fraction': 0.7931517499636378, 'bagging_fraction': 0.693194728496901, 'bagging_freq': 1, 'min_child_samples': 18}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 189/200 [1:30:34<02:45, 15.04s/it]

[I 2026-05-24 01:45:12,932] Trial 187 finished with value: 0.9498844627267016 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.010116489073885664, 'lambda_l1': 3.7796872312516077, 'lambda_l2': 5.186929415870343, 'feature_fraction': 0.7905905623878867, 'bagging_fraction': 0.6925442092985599, 'bagging_freq': 2, 'min_child_samples': 25}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 190/200 [1:30:46<02:22, 14.22s/it]

[I 2026-05-24 01:45:25,256] Trial 189 finished with value: 0.9498831731709915 and parameters: {'num_leaves': 233, 'max_depth': 3, 'learning_rate': 0.01004999530357999, 'lambda_l1': 4.0767644310466205, 'lambda_l2': 5.427831593365352, 'feature_fraction': 0.7924601495025625, 'bagging_fraction': 0.6737610763974892, 'bagging_freq': 2, 'min_child_samples': 17}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 191/200 [1:30:47<01:30, 10.09s/it]

[I 2026-05-24 01:45:25,700] Trial 188 finished with value: 0.9497126646001398 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.04204656031268097, 'lambda_l1': 4.516018814337733, 'lambda_l2': 5.426711321223159, 'feature_fraction': 0.7710153291535166, 'bagging_fraction': 0.6709606903334804, 'bagging_freq': 2, 'min_child_samples': 20}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 192/200 [1:31:10<01:52, 14.02s/it]

[I 2026-05-24 01:45:48,878] Trial 192 finished with value: 0.949885164497245 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.010005133079619958, 'lambda_l1': 4.025628035917309, 'lambda_l2': 5.66694698373707, 'feature_fraction': 0.7958736277640015, 'bagging_fraction': 0.6710796830208443, 'bagging_freq': 1, 'min_child_samples': 12}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 193/200 [1:31:15<01:18, 11.25s/it]

[I 2026-05-24 01:45:53,665] Trial 191 finished with value: 0.9498810903586044 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.01007111114136585, 'lambda_l1': 3.8249468659406394, 'lambda_l2': 4.7442295519307, 'feature_fraction': 0.7743040523815689, 'bagging_fraction': 0.693443928146294, 'bagging_freq': 3, 'min_child_samples': 17}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 194/200 [1:31:29<01:13, 12.17s/it]

[I 2026-05-24 01:46:07,978] Trial 193 finished with value: 0.9498786746731682 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.010110107284784916, 'lambda_l1': 4.208892042371912, 'lambda_l2': 4.46666374964431, 'feature_fraction': 0.7922865187077585, 'bagging_fraction': 0.6723246363007092, 'bagging_freq': 7, 'min_child_samples': 18}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 195/200 [1:31:51<01:15, 15.03s/it]

[I 2026-05-24 01:46:29,703] Trial 194 finished with value: 0.9498776128654542 and parameters: {'num_leaves': 236, 'max_depth': 3, 'learning_rate': 0.010102341555438753, 'lambda_l1': 0.0017327943402271192, 'lambda_l2': 4.1720347858239695, 'feature_fraction': 0.7937454117415395, 'bagging_fraction': 0.6725782624305165, 'bagging_freq': 3, 'min_child_samples': 20}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 196/200 [1:33:06<02:12, 33.09s/it]

[I 2026-05-24 01:47:44,920] Trial 195 finished with value: 0.9498818071268673 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.010005463250547632, 'lambda_l1': 4.395677171927208, 'lambda_l2': 4.142088736269866, 'feature_fraction': 0.7699391966926945, 'bagging_fraction': 0.6737231521089173, 'bagging_freq': 3, 'min_child_samples': 12}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 197/200 [1:33:12<01:15, 25.05s/it]

[I 2026-05-24 01:47:51,227] Trial 196 finished with value: 0.9498825172278911 and parameters: {'num_leaves': 234, 'max_depth': 3, 'learning_rate': 0.010044706310929647, 'lambda_l1': 4.666036502729022, 'lambda_l2': 5.427476046004066, 'feature_fraction': 0.7918498936174806, 'bagging_fraction': 0.6931488568442244, 'bagging_freq': 3, 'min_child_samples': 20}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 198/200 [1:33:43<00:53, 26.92s/it]

[I 2026-05-24 01:48:22,516] Trial 199 finished with value: 0.949883241642719 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.01002655464953394, 'lambda_l1': 3.0981901558282128, 'lambda_l2': 4.686208908147776, 'feature_fraction': 0.7706938235315094, 'bagging_fraction': 0.6742770752238196, 'bagging_freq': 2, 'min_child_samples': 21}. Best is trial 186 with value: 0.9498856935231969.

Best trial: 186. Best value: 0.949886: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 199/200 [1:35:43<00:54, 54.64s/it]

[I 2026-05-24 01:50:21,813] Trial 197 pruned.

Best trial: 186. Best value: 0.949886: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [1:36:21<00:00, 28.91s/it]

[I 2026-05-24 01:51:00,641] Trial 198 finished with value: 0.9493879502002359 and parameters: {'num_leaves': 235, 'max_depth': 8, 'learning_rate': 0.010084285821589106, 'lambda_l1': 4.477919879746, 'lambda_l2': 5.691757915028568, 'feature_fraction': 0.7956218301035587, 'bagging_fraction': 0.6826343786095358, 'bagging_freq': 2, 'min_child_samples': 21}. Best is trial 186 with value: 0.9498856935231969.
Best trial score:
0.9498856935231969

Best params:
{'num_leaves': 249, 'max_depth': 3, 'learning_rate': 0.010039679039207435, 'lambda_l1': 3.778717188646178, 'lambda_l2': 3.5913533331119214, 'feature_fraction': 0.7905843441379262, 'bagging_fraction': 0.6558907986733994, 'bagging_freq': 2, 'min_child_samples': 17}

## Train Dataset

In [17]:
cv = StratifiedKFold(shuffle=True, random_state=42, n_splits=5)

stacking_proba = cross_val_predict(
    LGBMClassifier(**study.best_params), 
    X_train_proba[features_to_use], 
    y_train.PitNextLap,
    cv=cv, 
    n_jobs=-1, 
    method='predict_proba'
)[:, 1]

[LightGBM] [Warning] feature_fraction is set=0.7905843441379262, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7905843441379262
[LightGBM] [Warning] lambda_l2 is set=3.5913533331119214, reg_lambda=0.0 will be ignored. Current value: lambda_l2=3.5913533331119214
[LightGBM] [Warning] lambda_l1 is set=3.778717188646178, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.778717188646178
[LightGBM] [Warning] bagging_fraction is set=0.6558907986733994, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6558907986733994
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Warning] feature_fraction is set=0.7905843441379262, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7905843441379262
[LightGBM] [Warning] lambda_l2 is set=3.5913533331119214, reg_lambda=0.0 will be ignored. Current value: lambda_l2=3.5913533331119214
[LightGBM] [Warning] lambda_l1 is set=3.778717188646178, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.778717188646178
[LightGBM] [Warning] bagging_fraction is set=0.6558907986733994, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6558907986733994
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Info] Number of positive: 69905, number of negative: 281407
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.038980 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1020
[LightGBM] [Info] Number of data points in the train set: 351312, number of used features: 4
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198983 -> initscore=-1.392665
[LightGBM] [Info] Start training from score -1.392665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf[LightGBM] [Warning] feature_fraction is set=0.7905843441379262, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7905843441379262
[LightGBM] [Warning] lambda_l2 is set=3.5913533331119214, reg_lambda=0.0 will be ignored. Current value: lambda_l2=3.5913533331119214
[LightGBM] [Warning] lambda_l1 is set=3.778717188646178, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.778717188646178
[LightGBM] [Warning] bagging_fraction is set=0.6558907986733994, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6558907986733994
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Warning] feature_fraction is set=0.7905843441379262, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7905843441379262
[LightGBM] [Warning] lambda_l2 is set=3.5913533331119214, reg_lambda=0.0 will be ignored. Current value: lambda_l2=3.5913533331119214
[LightGBM] [Warning] lambda_l1 is set=3.778717188646178, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.778717188646178
[LightGBM] [Warning] bagging_fraction is set=0.6558907986733994, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6558907986733994
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Info] Number of positive: 69904, number of negative: 281408
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.028780 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1020
[LightGBM] [Info] Number of data points in the train set: 351312, number of used features: 4
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198980 -> initscore=-1.392683
[LightGBM] [Info] Start training from score -1.392683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf[LightGBM] [Warning] feature_fraction is set=0.7905843441379262, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7905843441379262
[LightGBM] [Warning] lambda_l2 is set=3.5913533331119214, reg_lambda=0.0 will be ignored. Current value: lambda_l2=3.5913533331119214
[LightGBM] [Warning] lambda_l1 is set=3.778717188646178, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.778717188646178
[LightGBM] [Warning] bagging_fraction is set=0.6558907986733994, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6558907986733994
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Warning] feature_fraction is set=0.7905843441379262, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7905843441379262
[LightGBM] [Warning] lambda_l2 is set=3.5913533331119214, reg_lambda=0.0 will be ignored. Current value: lambda_l2=3.5913533331119214
[LightGBM] [Warning] lambda_l1 is set=3.778717188646178, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.778717188646178
[LightGBM] [Warning] bagging_fraction is set=0.6558907986733994, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6558907986733994
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Info] Number of positive: 69905, number of negative: 281407
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.043060 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1020
[LightGBM] [Info] Number of data points in the train set: 351312, number of used features: 4
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198983 -> initscore=-1.392665
[LightGBM] [Info] Start training from score -1.392665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [27]:
features_to_use.insert(0, 'stacking_')

In [42]:
features_to_use_rename = [
    'stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba',
    'voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier',
    'voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba',
    'truncatedsvd_linear_svc_logit'
]

In [36]:
features_to_use = [
    'voting_lgbm_and_cat_and_xgb_and_hist_proba',
    'voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier',
    'voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba',
    'truncatedsvd_linear_svc_logit'
]

In [46]:
X_train_stacking = X_train_proba.copy()
X_train_stacking['_and_'.join(features_to_use_rename)] = stacking_proba

# Test Dataset

In [33]:
stacking = LGBMClassifier(**study.best_params).fit(X_train_proba[features_to_use], y_train.PitNextLap)

In [43]:
X_test_stacking = X_test_proba.copy()
X_test_stacking['_and_'.join(features_to_use_rename)] = stacking.predict_proba(X_test_proba[features_to_use])[:, 1]

# Saving

In [44]:
X_test_stacking.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba,stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,-1.272709,-1.721325,-0.872993,0.005473,...,0.0,0.006534,0.003712,0.009642,0.010313,0.000000,0.019849,0.061327,0.000000,0.076454
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,-0.626960,-0.919863,-0.289991,0.054146,...,0.1,0.063555,0.110500,0.044563,0.145672,0.047794,0.012173,0.144461,0.102869,0.089535
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,-1.335019,-1.809246,-0.917667,0.003687,...,0.0,0.004404,0.003123,0.008417,0.006856,0.000000,0.010304,0.057929,0.000000,0.076454
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.190133,0.328363,0.387739,0.676445,...,0.3,0.670446,0.712745,0.648495,0.504756,0.637237,0.444558,0.628242,0.183451,0.215908
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.535153,0.644014,0.670147,0.852891,...,0.8,0.835307,0.855796,0.796202,0.823601,0.787922,0.939648,0.787450,0.823541,0.643512

In [47]:
X_train_stacking.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba,stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.496500,0.527291,0.637203,0.806670,...,0.3,0.815075,0.788450,0.867595,0.911292,0.783514,0.868510,0.784140,0.618609,0.543036
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.340099,0.303278,0.512236,0.734278,...,0.7,0.686883,0.686778,0.594025,0.698730,0.695484,0.772514,0.666212,0.572044,0.446302
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.127990,0.192701,0.330117,0.533609,...,0.5,0.580053,0.607686,0.523752,0.600009,0.614942,0.717012,0.570198,0.631260,0.440385
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,-1.249994,-1.823374,-0.834575,0.001354,...,0.0,0.002635,0.002627,0.013206,0.025528,0.000000,0.005494,0.063219,0.000000,0.076485
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,-0.090382,-0.011299,0.200067,0.386963,...,0.3,0.397511,0.457883,0.364956,0.265409,0.452112,0.482416,0.418672,0.245866,0.244423

In [48]:
X_train_stacking.to_parquet('../data/processed/X_train_stacking2.parquet')
X_test_stacking.to_parquet('../data/processed/X_test_stacking2.parquet')

In [41]:
X_train_stacking.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba,stacking__and_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.496500,0.527291,0.637203,0.806670,...,0.3,0.815075,0.788450,0.867595,0.911292,0.783514,0.868510,0.784140,0.618609,0.543036
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.340099,0.303278,0.512236,0.734278,...,0.7,0.686883,0.686778,0.594025,0.698730,0.695484,0.772514,0.666212,0.572044,0.446302
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.127990,0.192701,0.330117,0.533609,...,0.5,0.580053,0.607686,0.523752,0.600009,0.614942,0.717012,0.570198,0.631260,0.440385
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,-1.249994,-1.823374,-0.834575,0.001354,...,0.0,0.002635,0.002627,0.013206,0.025528,0.000000,0.005494,0.063219,0.000000,0.076485
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,-0.090382,-0.011299,0.200067,0.386963,...,0.3,0.397511,0.457883,0.364956,0.265409,0.452112,0.482416,0.418672,0.245866,0.244423