# Imports

In [11]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from lightgbm import LGBMClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

## Utils

In [2]:
set_config(enable_metadata_routing=True)

In [3]:
def voting_cross_val_predict(probas: list[np.ndarray], weights: np.ndarray[float]) -> np.ndarray[float]:
    weights /= weights.sum()
    return np.sum([proba * weight for proba, weight in zip(probas, weights)], axis=0)

# Loading Dataset

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_stacking.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking.parquet')

In [5]:
X_train.head()

   lgbm_proba  cat_proba  xgb_proba  hist_proba  lg_proba  knn_proba
0    0.802607   0.891870   0.895659    0.883947  0.808497   0.887454
1    0.649405   0.831360   0.829854    0.779541  0.689888   0.519966
2    0.505904   0.851809   0.751522    0.758911  0.558520   0.209855
3    0.001713   0.005910   0.007057    0.007298  0.002275   0.000000
4    0.392205   0.565506   0.489033    0.482967  0.414144   0.297043

In [6]:
X_test.head()

   lgbm_proba  cat_proba  xgb_proba  hist_proba  lg_proba  knn_proba
0    0.004591   0.031986   0.022774    0.020057  0.006419   0.000000
1    0.003032   0.011817   0.014957    0.018887  0.063872   0.117213
2    0.003777   0.011641   0.014307    0.011497  0.004517   0.000000
3    0.163131   0.544040   0.585898    0.485388  0.655870   0.099916
4    0.872172   0.967646   0.959451    0.959356  0.840450   1.000000

## Creating Stacking Database

In [7]:
X_train['voting_proba'] = voting_cross_val_predict(
    [
        X_train['lgbm_proba'],
        X_train['cat_proba'],
        X_train['xgb_proba'],
        X_train['hist_proba']
    ], 
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

In [8]:
X_test['voting_proba'] = voting_cross_val_predict(
    [
        X_test['lgbm_proba'],
        X_test['cat_proba'],
        X_test['xgb_proba'],
        X_test['hist_proba']
    ], 
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

In [9]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.868510
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.772514
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.717012
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,0.005494
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,0.482416

# Machine Learning

In [10]:
features_to_use = ['lgbm_proba', 'cat_proba', 'xgb_proba', 'hist_proba', 'lg_proba', 'voting_proba']

In [12]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "objective": "binary",
        "n_estimators": trial.suggest_int("n_estimators", 30, 300),
        "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.05, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 4),
        "num_leaves": trial.suggest_int("num_leaves", 2, 16),
        "min_child_samples": trial.suggest_int("min_child_samples", 20, 300),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-5, 100, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-5, 100, log=True),
        "verbosity": -1,
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LGBMClassifier(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

features_to_use = ['lgbm_proba', 'cat_proba', 'xgb_proba', 'hist_proba', 'lg_proba', 'voting_proba']

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train[features_to_use], y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-18 12:36:14,276] A new study created in memory with name: no-name-1871f4b7-77a8-49f9-8af4-314fc51c8a59
Best trial: 10. Best value: 0.949267:   0%|          | 1/500 [00:15<2:13:00, 15.99s/it]

[I 2026-05-18 12:36:30,267] Trial 10 finished with value: 0.9492674605293843 and parameters: {'n_estimators': 81, 'learning_rate': 0.017477914782857356, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 170, 'subsample': 0.6715762810423642, 'colsample_bytree': 0.735439410829866, 'reg_alpha': 0.009586648702649374, 'reg_lambda': 0.227010645387839}. Best is trial 10 with value: 0.9492674605293843.

Best trial: 10. Best value: 0.949267:   0%|          | 2/500 [00:17<1:00:03,  7.24s/it]

[I 2026-05-18 12:36:31,362] Trial 1 finished with value: 0.9482886381760309 and parameters: {'n_estimators': 82, 'learning_rate': 0.010199638864485902, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 117, 'subsample': 0.6617379785915019, 'colsample_bytree': 0.9961159985467192, 'reg_alpha': 29.62345578793132, 'reg_lambda': 9.777957786427615}. Best is trial 10 with value: 0.9492674605293843.

Best trial: 10. Best value: 0.949267:   1%|          | 3/500 [00:19<40:04,  4.84s/it]

[I 2026-05-18 12:36:33,350] Trial 5 finished with value: 0.9438808892625172 and parameters: {'n_estimators': 181, 'learning_rate': 0.00994529740965856, 'max_depth': 1, 'num_leaves': 15, 'min_child_samples': 106, 'subsample': 0.7205429776401234, 'colsample_bytree': 0.6447601887999284, 'reg_alpha': 0.21201057471079562, 'reg_lambda': 0.0012878287302179477}. Best is trial 10 with value: 0.9492674605293843.

Best trial: 10. Best value: 0.949267:   1%|          | 4/500 [00:20<29:01,  3.51s/it]

[I 2026-05-18 12:36:34,806] Trial 8 finished with value: 0.9478072877371051 and parameters: {'n_estimators': 191, 'learning_rate': 0.01673454308742483, 'max_depth': 1, 'num_leaves': 15, 'min_child_samples': 262, 'subsample': 0.7183885660285172, 'colsample_bytree': 0.8296779190529054, 'reg_alpha': 4.252067704233769e-05, 'reg_lambda': 0.02297708342148737}. Best is trial 10 with value: 0.9492674605293843.

Best trial: 10. Best value: 0.949267:   1%|          | 5/500 [00:24<30:31,  3.70s/it]

[I 2026-05-18 12:36:38,860] Trial 2 finished with value: 0.934551375560002 and parameters: {'n_estimators': 245, 'learning_rate': 0.0036645308286830615, 'max_depth': 1, 'num_leaves': 3, 'min_child_samples': 267, 'subsample': 0.8757415847603714, 'colsample_bytree': 0.882255319814028, 'reg_alpha': 9.723776528637911e-05, 'reg_lambda': 4.4194216045239604e-05}. Best is trial 10 with value: 0.9492674605293843.

Best trial: 10. Best value: 0.949267:   1%|▏         | 7/500 [00:25<15:04,  1.83s/it]

[I 2026-05-18 12:36:39,457] Trial 13 pruned.
[I 2026-05-18 12:36:39,636] Trial 11 pruned.

Best trial: 10. Best value: 0.949267:   2%|▏         | 8/500 [00:28<17:50,  2.17s/it]

[I 2026-05-18 12:36:42,532] Trial 0 pruned.

Best trial: 6. Best value: 0.949779:   2%|▏         | 9/500 [00:30<17:09,  2.10s/it]

[I 2026-05-18 12:36:44,454] Trial 6 finished with value: 0.9497788734875682 and parameters: {'n_estimators': 230, 'learning_rate': 0.04141748040372126, 'max_depth': 2, 'num_leaves': 3, 'min_child_samples': 36, 'subsample': 0.9903570235468021, 'colsample_bytree': 0.8837244348711122, 'reg_alpha': 0.0018636796488331426, 'reg_lambda': 3.55442017754323e-05}. Best is trial 6 with value: 0.9497788734875682.

Best trial: 6. Best value: 0.949779:   2%|▏         | 10/500 [00:32<16:38,  2.04s/it]

[I 2026-05-18 12:36:46,354] Trial 4 finished with value: 0.9496927769722128 and parameters: {'n_estimators': 224, 'learning_rate': 0.025171994156862647, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 165, 'subsample': 0.6550603893709397, 'colsample_bytree': 0.9848924565165738, 'reg_alpha': 24.825856704316465, 'reg_lambda': 2.7048669069956847e-05}. Best is trial 6 with value: 0.9497788734875682.

Best trial: 6. Best value: 0.949779:   2%|▏         | 11/500 [00:34<16:45,  2.06s/it]

[I 2026-05-18 12:36:48,453] Trial 3 pruned.

Best trial: 6. Best value: 0.949779:   2%|▏         | 12/500 [00:36<18:19,  2.25s/it]

[I 2026-05-18 12:36:51,170] Trial 14 finished with value: 0.9494669517553094 and parameters: {'n_estimators': 168, 'learning_rate': 0.03810209241870495, 'max_depth': 1, 'num_leaves': 14, 'min_child_samples': 150, 'subsample': 0.6323927373575531, 'colsample_bytree': 0.9698450085963587, 'reg_alpha': 89.78550558032727, 'reg_lambda': 31.75458785577296}. Best is trial 6 with value: 0.9497788734875682.

Best trial: 6. Best value: 0.949779:   3%|▎         | 13/500 [00:37<15:18,  1.89s/it]

[I 2026-05-18 12:36:52,214] Trial 7 finished with value: 0.9491555341215895 and parameters: {'n_estimators': 181, 'learning_rate': 0.010026767523372851, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 42, 'subsample': 0.6988184033071255, 'colsample_bytree': 0.9612406338919116, 'reg_alpha': 0.0007874853383093579, 'reg_lambda': 50.501523265768746}. Best is trial 6 with value: 0.9497788734875682.

Best trial: 6. Best value: 0.949779:   3%|▎         | 14/500 [00:38<11:26,  1.41s/it]

[I 2026-05-18 12:36:52,525] Trial 15 pruned.

Best trial: 6. Best value: 0.949779:   3%|▎         | 15/500 [00:39<10:51,  1.34s/it]

[I 2026-05-18 12:36:53,718] Trial 17 pruned.

Best trial: 6. Best value: 0.949779:   3%|▎         | 16/500 [00:42<13:50,  1.72s/it]

[I 2026-05-18 12:36:56,295] Trial 18 finished with value: 0.949568517544335 and parameters: {'n_estimators': 85, 'learning_rate': 0.024649476105279032, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 161, 'subsample': 0.8824251593821213, 'colsample_bytree': 0.7569327132743615, 'reg_alpha': 0.037163514560098386, 'reg_lambda': 0.0750295603108992}. Best is trial 6 with value: 0.9497788734875682.

Best trial: 6. Best value: 0.949779:   3%|▎         | 17/500 [00:44<15:18,  1.90s/it]

[I 2026-05-18 12:36:58,626] Trial 12 finished with value: 0.949602068653561 and parameters: {'n_estimators': 159, 'learning_rate': 0.013736166447808383, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 239, 'subsample': 0.6557120091251049, 'colsample_bytree': 0.851565912812789, 'reg_alpha': 0.07727843066571216, 'reg_lambda': 0.8774643881279068}. Best is trial 6 with value: 0.9497788734875682.

Best trial: 6. Best value: 0.949779:   4%|▎         | 18/500 [00:47<17:48,  2.22s/it]

[I 2026-05-18 12:37:01,560] Trial 20 pruned.

Best trial: 6. Best value: 0.949779:   4%|▍         | 19/500 [00:52<24:06,  3.01s/it]

[I 2026-05-18 12:37:06,416] Trial 21 finished with value: 0.9497355939001343 and parameters: {'n_estimators': 137, 'learning_rate': 0.04912948651084606, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 24, 'subsample': 0.9706484548697798, 'colsample_bytree': 0.6228006886938606, 'reg_alpha': 0.004544407397225931, 'reg_lambda': 1.689710717951882e-05}. Best is trial 6 with value: 0.9497788734875682.

Best trial: 6. Best value: 0.949779:   4%|▍         | 20/500 [00:55<25:02,  3.13s/it]

[I 2026-05-18 12:37:09,841] Trial 9 finished with value: 0.9491332564249084 and parameters: {'n_estimators': 248, 'learning_rate': 0.006172147712166371, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 169, 'subsample': 0.7393847185826311, 'colsample_bytree': 0.9542877920469588, 'reg_alpha': 0.00015725443821942026, 'reg_lambda': 34.914568160749205}. Best is trial 6 with value: 0.9497788734875682.

Best trial: 6. Best value: 0.949779:   4%|▍         | 21/500 [01:00<28:08,  3.52s/it]

[I 2026-05-18 12:37:14,248] Trial 31 pruned.

Best trial: 6. Best value: 0.949779:   4%|▍         | 22/500 [01:00<20:36,  2.59s/it]

[I 2026-05-18 12:37:14,673] Trial 16 pruned.

Best trial: 22. Best value: 0.949813:   5%|▍         | 23/500 [01:05<27:24,  3.45s/it]

[I 2026-05-18 12:37:20,140] Trial 22 finished with value: 0.949812806397129 and parameters: {'n_estimators': 223, 'learning_rate': 0.04402348928379792, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 35, 'subsample': 0.9661452723831411, 'colsample_bytree': 0.996413057478115, 'reg_alpha': 0.00564784690878404, 'reg_lambda': 1.1768573101352563e-05}. Best is trial 22 with value: 0.949812806397129.

Best trial: 24. Best value: 0.949819:   5%|▍         | 24/500 [01:07<23:08,  2.92s/it]

[I 2026-05-18 12:37:21,800] Trial 23 finished with value: 0.9498099617542337 and parameters: {'n_estimators': 212, 'learning_rate': 0.04879044226649712, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 40, 'subsample': 0.9957077608785909, 'colsample_bytree': 0.921809995714028, 'reg_alpha': 0.003186111569383906, 'reg_lambda': 1.056356700474087e-05}. Best is trial 22 with value: 0.949812806397129.
[I 2026-05-18 12:37:21,853] Trial 24 finished with value: 0.9498194970570959 and parameters: {'n_estimators': 221, 'learning_rate': 0.04816750390547993, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 20, 'subsample': 0.99382218463101, 'colsample_bytree': 0.9089415323307379, 'reg_alpha': 0.018673498025183397, 'reg_lambda': 1.0080312952318843e-05}. Best is trial 24 with value: 0.9498194970570959.

Best trial: 25. Best value: 0.949821:   5%|▌         | 26/500 [01:09<15:51,  2.01s/it]

[I 2026-05-18 12:37:23,700] Trial 25 finished with value: 0.9498213679907581 and parameters: {'n_estimators': 229, 'learning_rate': 0.04823620780794465, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 220, 'subsample': 0.9769871610949726, 'colsample_bytree': 0.9050256419553453, 'reg_alpha': 0.016764980555983834, 'reg_lambda': 1.0520881070423902e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   5%|▌         | 27/500 [01:09<12:18,  1.56s/it]

[I 2026-05-18 12:37:23,915] Trial 26 finished with value: 0.9498168627360863 and parameters: {'n_estimators': 222, 'learning_rate': 0.04575784861207968, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 220, 'subsample': 0.9896722669123388, 'colsample_bytree': 0.8999153806192816, 'reg_alpha': 0.8136084877271113, 'reg_lambda': 1.5639114915100328e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   6%|▌         | 28/500 [01:13<17:51,  2.27s/it]

[I 2026-05-18 12:37:28,192] Trial 27 finished with value: 0.9498173796289786 and parameters: {'n_estimators': 223, 'learning_rate': 0.047797314176176754, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 223, 'subsample': 0.9670479184644123, 'colsample_bytree': 0.8659683006573612, 'reg_alpha': 1.0848107564179292, 'reg_lambda': 1.7317021206106594e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   6%|▌         | 29/500 [01:16<17:31,  2.23s/it]

[I 2026-05-18 12:37:30,317] Trial 28 finished with value: 0.9498169716031606 and parameters: {'n_estimators': 224, 'learning_rate': 0.04632558699943531, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 209, 'subsample': 0.9949474844445219, 'colsample_bytree': 0.9220901754634243, 'reg_alpha': 1.2043793558049782, 'reg_lambda': 1.677215132925996e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   6%|▌         | 30/500 [01:18<17:43,  2.26s/it]

[I 2026-05-18 12:37:32,644] Trial 29 finished with value: 0.949815813637531 and parameters: {'n_estimators': 216, 'learning_rate': 0.045257351938260006, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 200, 'subsample': 0.7813440343206951, 'colsample_bytree': 0.9114205175579362, 'reg_alpha': 1.2993167337353106, 'reg_lambda': 1.0905637748022494e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   6%|▌         | 31/500 [01:21<19:02,  2.44s/it]

[I 2026-05-18 12:37:35,537] Trial 30 finished with value: 0.9498117313653335 and parameters: {'n_estimators': 217, 'learning_rate': 0.049029593808928164, 'max_depth': 2, 'num_leaves': 7, 'min_child_samples': 63, 'subsample': 0.9827791087659132, 'colsample_bytree': 0.6870692702997713, 'reg_alpha': 0.0017828242314927407, 'reg_lambda': 0.00016108313636501256}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   6%|▋         | 32/500 [01:22<17:16,  2.21s/it]

[I 2026-05-18 12:37:37,213] Trial 19 finished with value: 0.9497026999019479 and parameters: {'n_estimators': 291, 'learning_rate': 0.013760637812655466, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 115, 'subsample': 0.8612730167072922, 'colsample_bytree': 0.7533937003298397, 'reg_alpha': 0.0001285673252475964, 'reg_lambda': 0.008855511907669053}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   7%|▋         | 33/500 [01:27<22:18,  2.87s/it]

[I 2026-05-18 12:37:41,650] Trial 34 finished with value: 0.9495831572370061 and parameters: {'n_estimators': 198, 'learning_rate': 0.03368878123826627, 'max_depth': 2, 'num_leaves': 2, 'min_child_samples': 45, 'subsample': 0.9991099888287905, 'colsample_bytree': 0.9168966798197558, 'reg_alpha': 0.005262561400436532, 'reg_lambda': 0.00014231422065938992}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   7%|▋         | 34/500 [01:28<19:04,  2.46s/it]

[I 2026-05-18 12:37:43,127] Trial 32 finished with value: 0.9497580637262397 and parameters: {'n_estimators': 215, 'learning_rate': 0.03229192111206017, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 67, 'subsample': 0.7937586443666705, 'colsample_bytree': 0.9050126110685979, 'reg_alpha': 0.6180290340357139, 'reg_lambda': 0.00010551762955336334}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   7%|▋         | 35/500 [01:32<20:45,  2.68s/it]

[I 2026-05-18 12:37:46,305] Trial 33 finished with value: 0.9497363757957247 and parameters: {'n_estimators': 213, 'learning_rate': 0.030536734351738173, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 129, 'subsample': 0.7728690735373634, 'colsample_bytree': 0.9034752881374619, 'reg_alpha': 1.9826784540729072, 'reg_lambda': 0.00010443348695090826}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   7%|▋         | 36/500 [01:36<23:46,  3.07s/it]

[I 2026-05-18 12:37:50,327] Trial 36 finished with value: 0.9497395869492206 and parameters: {'n_estimators': 209, 'learning_rate': 0.03158499842959271, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 52, 'subsample': 0.9126492108895585, 'colsample_bytree': 0.9097638365775705, 'reg_alpha': 1.7956024752102817, 'reg_lambda': 0.00021864092308589126}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   7%|▋         | 37/500 [01:37<19:53,  2.58s/it]

[I 2026-05-18 12:37:51,729] Trial 35 finished with value: 0.9497432588018446 and parameters: {'n_estimators': 208, 'learning_rate': 0.031544505317143465, 'max_depth': 2, 'num_leaves': 8, 'min_child_samples': 55, 'subsample': 0.9978827771380292, 'colsample_bytree': 0.9006654912917333, 'reg_alpha': 0.0008611229948072, 'reg_lambda': 0.00015047731963538117}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   8%|▊         | 38/500 [01:38<17:01,  2.21s/it]

[I 2026-05-18 12:37:53,093] Trial 38 finished with value: 0.9497409824128681 and parameters: {'n_estimators': 206, 'learning_rate': 0.03168992840197834, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 211, 'subsample': 0.9031843757701539, 'colsample_bytree': 0.9090730301935024, 'reg_alpha': 1.019639600869057, 'reg_lambda': 0.00013929779500293613}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   8%|▊         | 39/500 [01:40<15:18,  1.99s/it]

[I 2026-05-18 12:37:54,576] Trial 37 finished with value: 0.9497546321015167 and parameters: {'n_estimators': 203, 'learning_rate': 0.033607803692376384, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 207, 'subsample': 0.8979112461439709, 'colsample_bytree': 0.9152160806517844, 'reg_alpha': 0.5712316788702871, 'reg_lambda': 0.0001066339492123641}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   8%|▊         | 40/500 [01:42<15:20,  2.00s/it]

[I 2026-05-18 12:37:56,580] Trial 39 finished with value: 0.949731488435398 and parameters: {'n_estimators': 201, 'learning_rate': 0.03167450475962889, 'max_depth': 2, 'num_leaves': 9, 'min_child_samples': 203, 'subsample': 0.913336142776072, 'colsample_bytree': 0.8546212361219575, 'reg_alpha': 2.2277215302338345, 'reg_lambda': 0.00015746424881776322}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   8%|▊         | 41/500 [01:46<20:40,  2.70s/it]

[I 2026-05-18 12:38:00,944] Trial 41 finished with value: 0.9497315423051894 and parameters: {'n_estimators': 200, 'learning_rate': 0.03175942646498789, 'max_depth': 2, 'num_leaves': 9, 'min_child_samples': 132, 'subsample': 0.9166342193733088, 'colsample_bytree': 0.8494431316335739, 'reg_alpha': 0.13813716436270204, 'reg_lambda': 0.0001555557763822119}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   8%|▊         | 42/500 [01:49<21:50,  2.86s/it]

[I 2026-05-18 12:38:04,161] Trial 40 finished with value: 0.9497906578648918 and parameters: {'n_estimators': 267, 'learning_rate': 0.031953349988520056, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 138, 'subsample': 0.9088540273403218, 'colsample_bytree': 0.8582443234427443, 'reg_alpha': 3.0679820518329946, 'reg_lambda': 0.00014220361861655043}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   9%|▊         | 43/500 [01:50<16:13,  2.13s/it]

[I 2026-05-18 12:38:04,566] Trial 43 finished with value: 0.94974877266416 and parameters: {'n_estimators': 204, 'learning_rate': 0.03396741059714772, 'max_depth': 2, 'num_leaves': 9, 'min_child_samples': 194, 'subsample': 0.9186998271665421, 'colsample_bytree': 0.8595422544564262, 'reg_alpha': 2.823579765840538, 'reg_lambda': 0.00013834233544195442}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   9%|▉         | 44/500 [01:56<25:28,  3.35s/it]

[I 2026-05-18 12:38:10,788] Trial 42 finished with value: 0.9497953748428929 and parameters: {'n_estimators': 271, 'learning_rate': 0.03186613960164576, 'max_depth': 2, 'num_leaves': 9, 'min_child_samples': 190, 'subsample': 0.9190891971751199, 'colsample_bytree': 0.8607539953513402, 'reg_alpha': 2.204022788122556, 'reg_lambda': 0.00013535533426872368}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   9%|▉         | 45/500 [02:00<25:54,  3.42s/it]

[I 2026-05-18 12:38:14,362] Trial 46 finished with value: 0.949645062531322 and parameters: {'n_estimators': 271, 'learning_rate': 0.027566018927390662, 'max_depth': 1, 'num_leaves': 8, 'min_child_samples': 240, 'subsample': 0.9106700281724651, 'colsample_bytree': 0.8622397562362415, 'reg_alpha': 5.0748649690929115, 'reg_lambda': 0.0003935372296453601}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   9%|▉         | 46/500 [02:00<19:14,  2.54s/it]

[I 2026-05-18 12:38:14,872] Trial 48 finished with value: 0.9494372228523515 and parameters: {'n_estimators': 239, 'learning_rate': 0.023363846544285555, 'max_depth': 1, 'num_leaves': 10, 'min_child_samples': 190, 'subsample': 0.9395980582935646, 'colsample_bytree': 0.8552866008378552, 'reg_alpha': 0.24749461255373364, 'reg_lambda': 0.0007592386092895626}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:   9%|▉         | 47/500 [02:02<16:42,  2.21s/it]

[I 2026-05-18 12:38:16,288] Trial 44 finished with value: 0.9497947077028682 and parameters: {'n_estimators': 272, 'learning_rate': 0.031098051614861216, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 194, 'subsample': 0.9245913104806448, 'colsample_bytree': 0.8598903155113063, 'reg_alpha': 2.0923762785185547, 'reg_lambda': 0.00012263539025309008}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  10%|▉         | 48/500 [02:02<13:30,  1.79s/it]

[I 2026-05-18 12:38:17,093] Trial 47 finished with value: 0.949598124937762 and parameters: {'n_estimators': 269, 'learning_rate': 0.025339262012827747, 'max_depth': 1, 'num_leaves': 8, 'min_child_samples': 192, 'subsample': 0.9363470625810887, 'colsample_bytree': 0.8467579005379002, 'reg_alpha': 0.2170924494375691, 'reg_lambda': 0.00037977930574905553}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  10%|▉         | 49/500 [02:03<10:14,  1.36s/it]

[I 2026-05-18 12:38:17,483] Trial 45 finished with value: 0.9497804041644964 and parameters: {'n_estimators': 267, 'learning_rate': 0.02913661706522122, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 140, 'subsample': 0.9193963572562575, 'colsample_bytree': 0.8567153536003116, 'reg_alpha': 2.4642341238519188, 'reg_lambda': 0.0006417230483610645}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  10%|█         | 50/500 [02:04<10:02,  1.34s/it]

[I 2026-05-18 12:38:18,755] Trial 49 finished with value: 0.9494543892955478 and parameters: {'n_estimators': 259, 'learning_rate': 0.02171802540721105, 'max_depth': 1, 'num_leaves': 10, 'min_child_samples': 243, 'subsample': 0.9412002726354364, 'colsample_bytree': 0.8590862093422198, 'reg_alpha': 0.21888724900701292, 'reg_lambda': 0.0005755067291941435}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  10%|█         | 51/500 [02:05<10:21,  1.38s/it]

[I 2026-05-18 12:38:20,265] Trial 50 finished with value: 0.9495877782744231 and parameters: {'n_estimators': 267, 'learning_rate': 0.02387579380143863, 'max_depth': 1, 'num_leaves': 10, 'min_child_samples': 239, 'subsample': 0.9520175347168351, 'colsample_bytree': 0.8656130176737521, 'reg_alpha': 0.21393432725815784, 'reg_lambda': 0.0005127470167463461}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  10%|█         | 52/500 [02:08<11:52,  1.59s/it]

[I 2026-05-18 12:38:22,325] Trial 51 finished with value: 0.9495511224395823 and parameters: {'n_estimators': 268, 'learning_rate': 0.022825533605986457, 'max_depth': 1, 'num_leaves': 5, 'min_child_samples': 237, 'subsample': 0.9424618273727697, 'colsample_bytree': 0.8731966848626237, 'reg_alpha': 0.23915364845087655, 'reg_lambda': 0.0006512792836287897}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  11%|█         | 53/500 [02:08<10:20,  1.39s/it]

[I 2026-05-18 12:38:23,241] Trial 52 finished with value: 0.9496506956989432 and parameters: {'n_estimators': 236, 'learning_rate': 0.039081784814519356, 'max_depth': 1, 'num_leaves': 11, 'min_child_samples': 248, 'subsample': 0.9372906867670175, 'colsample_bytree': 0.8796319591493701, 'reg_alpha': 4.072967864109043, 'reg_lambda': 3.779348187110182e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  11%|█         | 54/500 [02:12<15:21,  2.07s/it]

[I 2026-05-18 12:38:26,901] Trial 53 finished with value: 0.9495427912813357 and parameters: {'n_estimators': 237, 'learning_rate': 0.024970108664460988, 'max_depth': 1, 'num_leaves': 11, 'min_child_samples': 233, 'subsample': 0.9432780121869702, 'colsample_bytree': 0.8775787612005864, 'reg_alpha': 5.5188460276705635, 'reg_lambda': 4.0680304932786544e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  11%|█         | 55/500 [02:14<14:19,  1.93s/it]

[I 2026-05-18 12:38:28,512] Trial 54 finished with value: 0.9494706913332192 and parameters: {'n_estimators': 237, 'learning_rate': 0.023987111770299878, 'max_depth': 1, 'num_leaves': 11, 'min_child_samples': 236, 'subsample': 0.9446294918612637, 'colsample_bytree': 0.8866789134171174, 'reg_alpha': 0.03535095587464996, 'reg_lambda': 4.5028600733295834e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  11%|█         | 56/500 [02:20<23:29,  3.18s/it]

[I 2026-05-18 12:38:34,582] Trial 55 finished with value: 0.9495392667787341 and parameters: {'n_estimators': 236, 'learning_rate': 0.02497541557340508, 'max_depth': 1, 'num_leaves': 11, 'min_child_samples': 228, 'subsample': 0.9389558951221982, 'colsample_bytree': 0.8757361133865139, 'reg_alpha': 7.314913758368072, 'reg_lambda': 4.470612005660477e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  11%|█▏        | 57/500 [02:23<23:54,  3.24s/it]

[I 2026-05-18 12:38:37,982] Trial 58 finished with value: 0.9496604294787012 and parameters: {'n_estimators': 235, 'learning_rate': 0.039509031968927764, 'max_depth': 1, 'num_leaves': 11, 'min_child_samples': 226, 'subsample': 0.9520263043511976, 'colsample_bytree': 0.8836907180143115, 'reg_alpha': 0.038127146317972496, 'reg_lambda': 4.276381617331687e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  12%|█▏        | 58/500 [02:24<17:22,  2.36s/it]

[I 2026-05-18 12:38:38,267] Trial 57 finished with value: 0.949667404750727 and parameters: {'n_estimators': 237, 'learning_rate': 0.040779863082496835, 'max_depth': 1, 'num_leaves': 11, 'min_child_samples': 229, 'subsample': 0.9493283494477103, 'colsample_bytree': 0.8795357833206865, 'reg_alpha': 0.03531091839891742, 'reg_lambda': 3.5770839452173373e-05}. Best is trial 25 with value: 0.9498213679907581.
[I 2026-05-18 12:38:38,318] Trial 56 finished with value: 0.9496628670022054 and parameters: {'n_estimators': 236, 'learning_rate': 0.03947553863120988, 'max_depth': 1, 'num_leaves': 11, 'min_child_samples': 228, 'subsample': 0.9454991139930047, 'colsample_bytree': 0.7973790480023775, 'reg_alpha': 0.2961232114519225, 'reg_lambda': 3.827069434475698e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  12%|█▏        | 60/500 [02:36<30:11,  4.12s/it]

[I 2026-05-18 12:38:50,604] Trial 64 finished with value: 0.9497964641185066 and parameters: {'n_estimators': 185, 'learning_rate': 0.04022672403977042, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 223, 'subsample': 0.8556212524659271, 'colsample_bytree': 0.9357209892106901, 'reg_alpha': 8.964000495367596, 'reg_lambda': 2.5218964270033448e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  12%|█▏        | 61/500 [02:36<23:28,  3.21s/it]

[I 2026-05-18 12:38:51,074] Trial 62 finished with value: 0.949787648070189 and parameters: {'n_estimators': 234, 'learning_rate': 0.03791873867420084, 'max_depth': 2, 'num_leaves': 5, 'min_child_samples': 223, 'subsample': 0.8406582764906345, 'colsample_bytree': 0.8809590782165083, 'reg_alpha': 10.888574954547284, 'reg_lambda': 3.4225401115862346e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  12%|█▏        | 62/500 [02:39<22:08,  3.03s/it]

[I 2026-05-18 12:38:53,607] Trial 63 finished with value: 0.9498005353831024 and parameters: {'n_estimators': 235, 'learning_rate': 0.03994636325988958, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 224, 'subsample': 0.8270011193931297, 'colsample_bytree': 0.9370042142368766, 'reg_alpha': 13.449152769988782, 'reg_lambda': 4.5315145291336595e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 25. Best value: 0.949821:  13%|█▎        | 63/500 [02:41<20:06,  2.76s/it]

[I 2026-05-18 12:38:55,620] Trial 65 finished with value: 0.9498095187892364 and parameters: {'n_estimators': 184, 'learning_rate': 0.04106840328446597, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 222, 'subsample': 0.844845150635412, 'colsample_bytree': 0.9409440226390816, 'reg_alpha': 0.042375026037555365, 'reg_lambda': 2.344637108498984e-05}. Best is trial 25 with value: 0.9498213679907581.

Best trial: 59. Best value: 0.949842:  13%|█▎        | 65/500 [02:43<14:06,  1.95s/it]

[I 2026-05-18 12:38:58,032] Trial 59 finished with value: 0.9498417769031737 and parameters: {'n_estimators': 255, 'learning_rate': 0.03902181071907913, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 224, 'subsample': 0.9543363608532054, 'colsample_bytree': 0.7934497746944678, 'reg_alpha': 0.051531956099855065, 'reg_lambda': 3.818471944393532e-05}. Best is trial 59 with value: 0.9498417769031737.
[I 2026-05-18 12:38:58,203] Trial 66 finished with value: 0.9498068166001381 and parameters: {'n_estimators': 187, 'learning_rate': 0.04199044488870664, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 219, 'subsample': 0.8224663190165842, 'colsample_bytree': 0.9323405904026804, 'reg_alpha': 11.084281366841628, 'reg_lambda': 2.259962884142397e-05}. Best is trial 59 with value: 0.9498417769031737.

Best trial: 59. Best value: 0.949842:  13%|█▎        | 66/500 [02:44<11:31,  1.59s/it]

[I 2026-05-18 12:38:58,918] Trial 60 finished with value: 0.9497347479423921 and parameters: {'n_estimators': 233, 'learning_rate': 0.02094051936398414, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 226, 'subsample': 0.9543919159461806, 'colsample_bytree': 0.7974095041105205, 'reg_alpha': 0.04660710742211592, 'reg_lambda': 3.756626251231531e-05}. Best is trial 59 with value: 0.9498417769031737.
[I 2026-05-18 12:38:58,937] Trial 61 finished with value: 0.949840771156764 and parameters: {'n_estimators': 235, 'learning_rate': 0.03993470253928161, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 224, 'subsample': 0.9566759260182367, 'colsample_bytree': 0.810803515781671, 'reg_alpha': 0.04563926756167673, 'reg_lambda': 4.409844684250666e-05}. Best is trial 59 with value: 0.9498417769031737.

Best trial: 59. Best value: 0.949842:  14%|█▎        | 68/500 [02:51<17:01,  2.37s/it]

[I 2026-05-18 12:39:05,518] Trial 68 finished with value: 0.9498033312256956 and parameters: {'n_estimators': 186, 'learning_rate': 0.04173352693984133, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 281, 'subsample': 0.8383223744937833, 'colsample_bytree': 0.9375837495655522, 'reg_alpha': 13.63460907757334, 'reg_lambda': 0.0020303711906567933}. Best is trial 59 with value: 0.9498417769031737.

Best trial: 59. Best value: 0.949842:  14%|█▍        | 69/500 [02:53<16:32,  2.30s/it]

[I 2026-05-18 12:39:07,621] Trial 70 finished with value: 0.9498125911587634 and parameters: {'n_estimators': 183, 'learning_rate': 0.04339900113616117, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 262, 'subsample': 0.8215401553831637, 'colsample_bytree': 0.9376141899455728, 'reg_alpha': 0.09266418478938075, 'reg_lambda': 0.0025087052539278123}. Best is trial 59 with value: 0.9498417769031737.

Best trial: 59. Best value: 0.949842:  14%|█▍        | 70/500 [02:54<14:53,  2.08s/it]

[I 2026-05-18 12:39:09,063] Trial 69 finished with value: 0.9498096910197568 and parameters: {'n_estimators': 189, 'learning_rate': 0.043398315213699495, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 261, 'subsample': 0.8455067361743369, 'colsample_bytree': 0.93395414102683, 'reg_alpha': 14.295399614121758, 'reg_lambda': 2.309342444960516e-05}. Best is trial 59 with value: 0.9498417769031737.

Best trial: 67. Best value: 0.949849:  14%|█▍        | 71/500 [03:00<20:57,  2.93s/it]

[I 2026-05-18 12:39:14,286] Trial 67 finished with value: 0.9498485793784415 and parameters: {'n_estimators': 252, 'learning_rate': 0.04180292381236984, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 224, 'subsample': 0.8150681039573112, 'colsample_bytree': 0.9363640694805101, 'reg_alpha': 18.493801145670837, 'reg_lambda': 0.00242023061972472}. Best is trial 67 with value: 0.9498485793784415.

Best trial: 67. Best value: 0.949849:  14%|█▍        | 72/500 [03:04<23:40,  3.32s/it]

[I 2026-05-18 12:39:18,635] Trial 71 finished with value: 0.9498103402086879 and parameters: {'n_estimators': 171, 'learning_rate': 0.04365758277914281, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 263, 'subsample': 0.7455166215719513, 'colsample_bytree': 0.942203432365489, 'reg_alpha': 0.09193079511690097, 'reg_lambda': 0.003976743097691756}. Best is trial 67 with value: 0.9498485793784415.

Best trial: 67. Best value: 0.949849:  15%|█▍        | 73/500 [03:05<19:33,  2.75s/it]

[I 2026-05-18 12:39:19,937] Trial 72 finished with value: 0.9498146968245855 and parameters: {'n_estimators': 223, 'learning_rate': 0.0439025958705028, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 261, 'subsample': 0.9706619473028951, 'colsample_bytree': 0.9947680080791547, 'reg_alpha': 0.0141016249758868, 'reg_lambda': 1.671305477842704e-05}. Best is trial 67 with value: 0.9498485793784415.

Best trial: 67. Best value: 0.949849:  15%|█▍        | 74/500 [03:07<17:57,  2.53s/it]

[I 2026-05-18 12:39:21,933] Trial 73 finished with value: 0.9498170665247668 and parameters: {'n_estimators': 223, 'learning_rate': 0.04505833016184027, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 260, 'subsample': 0.9696325157898996, 'colsample_bytree': 0.9982284687175825, 'reg_alpha': 0.013673531023255248, 'reg_lambda': 1.7290713428650004e-05}. Best is trial 67 with value: 0.9498485793784415.

Best trial: 67. Best value: 0.949849:  15%|█▌        | 75/500 [03:09<15:40,  2.21s/it]

[I 2026-05-18 12:39:23,383] Trial 74 finished with value: 0.949819010714568 and parameters: {'n_estimators': 222, 'learning_rate': 0.04599805905727717, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 257, 'subsample': 0.9677294106774077, 'colsample_bytree': 0.9885038001384471, 'reg_alpha': 0.08835320489145077, 'reg_lambda': 0.002591746639730721}. Best is trial 67 with value: 0.9498485793784415.

Best trial: 67. Best value: 0.949849:  15%|█▌        | 76/500 [03:23<40:39,  5.75s/it]

[I 2026-05-18 12:39:37,593] Trial 75 finished with value: 0.9498421137862223 and parameters: {'n_estimators': 254, 'learning_rate': 0.045101020461544995, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 268, 'subsample': 0.9747091282891882, 'colsample_bytree': 0.9770020438107754, 'reg_alpha': 0.07580864705249017, 'reg_lambda': 0.003462477777321286}. Best is trial 67 with value: 0.9498485793784415.

Best trial: 67. Best value: 0.949849:  15%|█▌        | 77/500 [03:25<34:03,  4.83s/it]

[I 2026-05-18 12:39:40,252] Trial 76 finished with value: 0.9498400621247217 and parameters: {'n_estimators': 250, 'learning_rate': 0.0447120582740013, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 275, 'subsample': 0.9766609946207937, 'colsample_bytree': 0.9721550750573488, 'reg_alpha': 0.012189197312096252, 'reg_lambda': 1.6949386412952864e-05}. Best is trial 67 with value: 0.9498485793784415.

Best trial: 67. Best value: 0.949849:  16%|█▌        | 78/500 [03:27<27:49,  3.96s/it]

[I 2026-05-18 12:39:42,120] Trial 77 finished with value: 0.9498445113552136 and parameters: {'n_estimators': 254, 'learning_rate': 0.03637547971531485, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 267, 'subsample': 0.9761614147947186, 'colsample_bytree': 0.8196168328499177, 'reg_alpha': 0.016203031174751286, 'reg_lambda': 1.747555845441239e-05}. Best is trial 67 with value: 0.9498485793784415.

Best trial: 67. Best value: 0.949849:  16%|█▌        | 79/500 [03:33<31:48,  4.53s/it]

[I 2026-05-18 12:39:48,017] Trial 81 finished with value: 0.9498362205145708 and parameters: {'n_estimators': 170, 'learning_rate': 0.03607257336484064, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 180, 'subsample': 0.977921074659667, 'colsample_bytree': 0.9784227431593725, 'reg_alpha': 0.011641736250421567, 'reg_lambda': 6.929551789967892e-05}. Best is trial 67 with value: 0.9498485793784415.

Best trial: 78. Best value: 0.949855:  16%|█▌        | 80/500 [03:36<28:35,  4.08s/it]

[I 2026-05-18 12:39:51,050] Trial 78 finished with value: 0.94985536849171 and parameters: {'n_estimators': 252, 'learning_rate': 0.03600994903216405, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 260, 'subsample': 0.9772118075460893, 'colsample_bytree': 0.9782743394894425, 'reg_alpha': 0.017527898618671125, 'reg_lambda': 0.0013913922100734987}. Best is trial 78 with value: 0.94985536849171.

Best trial: 79. Best value: 0.949862:  16%|█▌        | 81/500 [03:44<35:16,  5.05s/it]

[I 2026-05-18 12:39:58,366] Trial 79 finished with value: 0.9498620085284815 and parameters: {'n_estimators': 253, 'learning_rate': 0.03665404816546157, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 179, 'subsample': 0.9766330580689151, 'colsample_bytree': 0.8178287030512205, 'reg_alpha': 0.013676774448365129, 'reg_lambda': 6.550720383299353e-05}. Best is trial 79 with value: 0.9498620085284815.

Best trial: 79. Best value: 0.949862:  16%|█▋        | 82/500 [03:47<31:36,  4.54s/it]

[I 2026-05-18 12:40:01,716] Trial 80 finished with value: 0.9498614841870741 and parameters: {'n_estimators': 251, 'learning_rate': 0.03587571463475353, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 177, 'subsample': 0.9748139090549501, 'colsample_bytree': 0.818209847894047, 'reg_alpha': 0.019644273634162122, 'reg_lambda': 1.7252865859482265e-05}. Best is trial 79 with value: 0.9498620085284815.

Best trial: 79. Best value: 0.949862:  17%|█▋        | 83/500 [03:52<32:10,  4.63s/it]

[I 2026-05-18 12:40:06,550] Trial 82 finished with value: 0.9498484218762693 and parameters: {'n_estimators': 253, 'learning_rate': 0.035911719159027536, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 177, 'subsample': 0.972692170069215, 'colsample_bytree': 0.9687032941712664, 'reg_alpha': 0.015081501724265287, 'reg_lambda': 6.647666802515693e-05}. Best is trial 79 with value: 0.9498620085284815.

Best trial: 79. Best value: 0.949862:  17%|█▋        | 84/500 [03:53<25:54,  3.74s/it]

[I 2026-05-18 12:40:08,208] Trial 86 finished with value: 0.9498307735223765 and parameters: {'n_estimators': 253, 'learning_rate': 0.03534281201787693, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 252, 'subsample': 0.9760674427879906, 'colsample_bytree': 0.9591809731675988, 'reg_alpha': 0.010675786785603745, 'reg_lambda': 0.030392913922432555}. Best is trial 79 with value: 0.9498620085284815.

Best trial: 79. Best value: 0.949862:  17%|█▋        | 85/500 [03:54<19:25,  2.81s/it]

[I 2026-05-18 12:40:08,838] Trial 84 finished with value: 0.9498606564058025 and parameters: {'n_estimators': 252, 'learning_rate': 0.03609118754601261, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 176, 'subsample': 0.9753200071484309, 'colsample_bytree': 0.7795607730105124, 'reg_alpha': 0.013747825039733224, 'reg_lambda': 7.017535089402014e-05}. Best is trial 79 with value: 0.9498620085284815.

Best trial: 79. Best value: 0.949862:  17%|█▋        | 86/500 [03:58<21:59,  3.19s/it]

[I 2026-05-18 12:40:12,907] Trial 83 finished with value: 0.9498540713587209 and parameters: {'n_estimators': 253, 'learning_rate': 0.035234049500325014, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 174, 'subsample': 0.9762915567940302, 'colsample_bytree': 0.9723656607074613, 'reg_alpha': 0.014622679400401168, 'reg_lambda': 7.317979694033975e-05}. Best is trial 79 with value: 0.9498620085284815.

Best trial: 79. Best value: 0.949862:  17%|█▋        | 87/500 [04:04<26:50,  3.90s/it]

[I 2026-05-18 12:40:18,474] Trial 85 finished with value: 0.9498604499473744 and parameters: {'n_estimators': 253, 'learning_rate': 0.03575950530976422, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 249, 'subsample': 0.9779669687004735, 'colsample_bytree': 0.9641639490967765, 'reg_alpha': 0.014024317371232067, 'reg_lambda': 7.509269785241689e-05}. Best is trial 79 with value: 0.9498620085284815.

Best trial: 79. Best value: 0.949862:  18%|█▊        | 88/500 [04:16<44:58,  6.55s/it]

[I 2026-05-18 12:40:31,228] Trial 87 finished with value: 0.9498578321585812 and parameters: {'n_estimators': 256, 'learning_rate': 0.03625205691803765, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 251, 'subsample': 0.980222019402515, 'colsample_bytree': 0.9691944929134064, 'reg_alpha': 0.022499352153056932, 'reg_lambda': 0.047698541133071426}. Best is trial 79 with value: 0.9498620085284815.

Best trial: 88. Best value: 0.949864:  18%|█▊        | 89/500 [04:22<42:19,  6.18s/it]

[I 2026-05-18 12:40:36,517] Trial 88 finished with value: 0.9498637781304919 and parameters: {'n_estimators': 253, 'learning_rate': 0.03536571626661802, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 283, 'subsample': 0.9791184418950429, 'colsample_bytree': 0.9702308692956014, 'reg_alpha': 0.019566486397527488, 'reg_lambda': 0.019088580954712428}. Best is trial 88 with value: 0.9498637781304919.

Best trial: 89. Best value: 0.949866:  18%|█▊        | 90/500 [04:25<35:09,  5.15s/it]

[I 2026-05-18 12:40:39,256] Trial 89 finished with value: 0.9498663740511837 and parameters: {'n_estimators': 254, 'learning_rate': 0.036926312744801806, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 274, 'subsample': 0.9767065661641812, 'colsample_bytree': 0.9734986138697572, 'reg_alpha': 0.009347471490544448, 'reg_lambda': 0.019627358137822133}. Best is trial 89 with value: 0.9498663740511837.

Best trial: 89. Best value: 0.949866:  18%|█▊        | 91/500 [04:30<35:00,  5.13s/it]

[I 2026-05-18 12:40:44,380] Trial 90 finished with value: 0.9498580897488746 and parameters: {'n_estimators': 255, 'learning_rate': 0.03625289320869275, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 284, 'subsample': 0.9780046296851217, 'colsample_bytree': 0.9711140426187014, 'reg_alpha': 0.008391996493849226, 'reg_lambda': 0.015212155903521183}. Best is trial 89 with value: 0.9498663740511837.

Best trial: 89. Best value: 0.949866:  18%|█▊        | 92/500 [04:32<28:38,  4.21s/it]

[I 2026-05-18 12:40:46,419] Trial 91 finished with value: 0.9498647799293496 and parameters: {'n_estimators': 249, 'learning_rate': 0.03564358267405113, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 274, 'subsample': 0.8898682383356226, 'colsample_bytree': 0.96629230209519, 'reg_alpha': 0.01059487487584524, 'reg_lambda': 0.01665616323550403}. Best is trial 89 with value: 0.9498663740511837.

Best trial: 89. Best value: 0.949866:  19%|█▊        | 93/500 [04:43<42:21,  6.24s/it]

[I 2026-05-18 12:40:57,422] Trial 93 finished with value: 0.9498635038175008 and parameters: {'n_estimators': 253, 'learning_rate': 0.035372064587303374, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 275, 'subsample': 0.9604373707201471, 'colsample_bytree': 0.8111776030985487, 'reg_alpha': 0.023124474988471456, 'reg_lambda': 0.007070055481739162}. Best is trial 89 with value: 0.9498663740511837.

Best trial: 89. Best value: 0.949866:  19%|█▉        | 94/500 [04:44<32:18,  4.77s/it]

[I 2026-05-18 12:40:58,771] Trial 92 finished with value: 0.9498567835422991 and parameters: {'n_estimators': 285, 'learning_rate': 0.036790976316670505, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 277, 'subsample': 0.9827742972277422, 'colsample_bytree': 0.9711119783037548, 'reg_alpha': 0.006995329922573161, 'reg_lambda': 6.879256668419588e-05}. Best is trial 89 with value: 0.9498663740511837.

Best trial: 94. Best value: 0.949876:  19%|█▉        | 95/500 [04:52<37:46,  5.60s/it]

[I 2026-05-18 12:41:06,276] Trial 94 finished with value: 0.9498761788288069 and parameters: {'n_estimators': 283, 'learning_rate': 0.03586845081443028, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 295, 'subsample': 0.679379787564614, 'colsample_bytree': 0.8136966249318313, 'reg_alpha': 0.023168241642700375, 'reg_lambda': 0.01185950393881092}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  19%|█▉        | 96/500 [04:54<31:16,  4.64s/it]

[I 2026-05-18 12:41:08,679] Trial 95 finished with value: 0.9498549315060638 and parameters: {'n_estimators': 281, 'learning_rate': 0.02806629429851657, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 284, 'subsample': 0.9591874926363171, 'colsample_bytree': 0.7796887294658975, 'reg_alpha': 0.021517681135047637, 'reg_lambda': 0.00028028640347044166}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  19%|█▉        | 97/500 [04:57<28:39,  4.27s/it]

[I 2026-05-18 12:41:12,078] Trial 96 finished with value: 0.9498555642676987 and parameters: {'n_estimators': 284, 'learning_rate': 0.027263926880304077, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 297, 'subsample': 0.958750675218282, 'colsample_bytree': 0.7765569673885395, 'reg_alpha': 0.007328785561017638, 'reg_lambda': 0.06789547703351301}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  20%|█▉        | 98/500 [04:58<20:45,  3.10s/it]

[I 2026-05-18 12:41:12,450] Trial 97 finished with value: 0.9498624145478265 and parameters: {'n_estimators': 281, 'learning_rate': 0.03631626174736992, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 153, 'subsample': 0.6791416395097756, 'colsample_bytree': 0.820081959221827, 'reg_alpha': 0.007007549326294804, 'reg_lambda': 0.005669495823756527}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  20%|█▉        | 99/500 [05:06<31:37,  4.73s/it]

[I 2026-05-18 12:41:20,989] Trial 98 finished with value: 0.9497448569302837 and parameters: {'n_estimators': 286, 'learning_rate': 0.00783723404076971, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 156, 'subsample': 0.6726365900286357, 'colsample_bytree': 0.7310072418717931, 'reg_alpha': 0.007104162002635628, 'reg_lambda': 0.000262580119700472}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  20%|██        | 100/500 [05:18<45:08,  6.77s/it]

[I 2026-05-18 12:41:32,523] Trial 99 finished with value: 0.9498490651380067 and parameters: {'n_estimators': 284, 'learning_rate': 0.028193486861405062, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 172, 'subsample': 0.9850671936053779, 'colsample_bytree': 0.7774909590656103, 'reg_alpha': 0.00722847654631123, 'reg_lambda': 0.095119216898273}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  20%|██        | 101/500 [05:23<41:58,  6.31s/it]

[I 2026-05-18 12:41:37,761] Trial 100 finished with value: 0.9498561469023041 and parameters: {'n_estimators': 283, 'learning_rate': 0.02855001161847841, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 158, 'subsample': 0.684059396940289, 'colsample_bytree': 0.7846261892482462, 'reg_alpha': 0.024877872774337742, 'reg_lambda': 0.015443463109027404}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  20%|██        | 102/500 [05:27<36:32,  5.51s/it]

[I 2026-05-18 12:41:41,399] Trial 101 finished with value: 0.949852168549765 and parameters: {'n_estimators': 282, 'learning_rate': 0.027545087546909982, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 284, 'subsample': 0.9879246184873631, 'colsample_bytree': 0.7775828478053636, 'reg_alpha': 0.0072718824124507215, 'reg_lambda': 0.06042542266324417}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  21%|██        | 103/500 [05:30<31:59,  4.84s/it]

[I 2026-05-18 12:41:44,660] Trial 102 finished with value: 0.9498554779615827 and parameters: {'n_estimators': 283, 'learning_rate': 0.02878928230379293, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 299, 'subsample': 0.9905566769374897, 'colsample_bytree': 0.7795273464267661, 'reg_alpha': 0.006940034782208145, 'reg_lambda': 0.016127598443288697}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  21%|██        | 104/500 [05:36<33:46,  5.12s/it]

[I 2026-05-18 12:41:50,450] Trial 103 finished with value: 0.949853660264156 and parameters: {'n_estimators': 282, 'learning_rate': 0.027949870806673122, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 296, 'subsample': 0.9894096438275615, 'colsample_bytree': 0.9507344347965002, 'reg_alpha': 0.006897879242294743, 'reg_lambda': 0.013835241156057896}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  21%|██        | 105/500 [05:39<29:55,  4.55s/it]

[I 2026-05-18 12:41:53,661] Trial 105 finished with value: 0.9498487435864277 and parameters: {'n_estimators': 244, 'learning_rate': 0.027709101015038724, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 298, 'subsample': 0.9882823157842551, 'colsample_bytree': 0.7805079673827136, 'reg_alpha': 0.02443562819890057, 'reg_lambda': 0.013455553535602507}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  21%|██        | 106/500 [05:44<31:09,  4.75s/it]

[I 2026-05-18 12:41:58,866] Trial 104 finished with value: 0.949854034828394 and parameters: {'n_estimators': 283, 'learning_rate': 0.02724885088869695, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 290, 'subsample': 0.9887211456974141, 'colsample_bytree': 0.7777216917632759, 'reg_alpha': 0.006560526057972339, 'reg_lambda': 0.011435157842979667}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  21%|██▏       | 107/500 [05:51<35:05,  5.36s/it]

[I 2026-05-18 12:42:05,646] Trial 107 finished with value: 0.9498489226295377 and parameters: {'n_estimators': 260, 'learning_rate': 0.027673422684072076, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 299, 'subsample': 0.6822759364641893, 'colsample_bytree': 0.8384130901710826, 'reg_alpha': 0.0033579237581053394, 'reg_lambda': 0.011665574357106136}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  22%|██▏       | 108/500 [05:56<34:09,  5.23s/it]

[I 2026-05-18 12:42:10,576] Trial 106 finished with value: 0.9498567453574097 and parameters: {'n_estimators': 300, 'learning_rate': 0.027959365538271743, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 297, 'subsample': 0.9885241464440564, 'colsample_bytree': 0.7851690551426608, 'reg_alpha': 0.003363773091888639, 'reg_lambda': 0.012351742965721021}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  22%|██▏       | 109/500 [06:02<35:43,  5.48s/it]

[I 2026-05-18 12:42:16,646] Trial 108 finished with value: 0.9498626561463904 and parameters: {'n_estimators': 298, 'learning_rate': 0.028958065453123728, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 293, 'subsample': 0.9881870588258805, 'colsample_bytree': 0.8366597577738312, 'reg_alpha': 0.0031530472758928316, 'reg_lambda': 0.013143618108190319}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  22%|██▏       | 110/500 [06:02<25:46,  3.96s/it]

[I 2026-05-18 12:42:17,081] Trial 110 finished with value: 0.9498534607440463 and parameters: {'n_estimators': 245, 'learning_rate': 0.028959391534354985, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 289, 'subsample': 0.6813535946817395, 'colsample_bytree': 0.8287950853043852, 'reg_alpha': 0.003242577432737757, 'reg_lambda': 0.008248585602076789}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  22%|██▏       | 111/500 [06:06<25:43,  3.97s/it]

[I 2026-05-18 12:42:21,033] Trial 109 finished with value: 0.9497463637221735 and parameters: {'n_estimators': 300, 'learning_rate': 0.007846697711415595, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 151, 'subsample': 0.6810874573814283, 'colsample_bytree': 0.8376733207050091, 'reg_alpha': 0.003884548583788618, 'reg_lambda': 0.007756483299569105}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  22%|██▏       | 112/500 [06:17<38:07,  5.90s/it]

[I 2026-05-18 12:42:31,447] Trial 111 finished with value: 0.9498125096828041 and parameters: {'n_estimators': 245, 'learning_rate': 0.018423480919415005, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 298, 'subsample': 0.6925217633452153, 'colsample_bytree': 0.8333162693650696, 'reg_alpha': 0.0017081194161757904, 'reg_lambda': 0.007350399134471331}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  23%|██▎       | 113/500 [06:22<36:41,  5.69s/it]

[I 2026-05-18 12:42:36,636] Trial 113 finished with value: 0.9497670789186365 and parameters: {'n_estimators': 243, 'learning_rate': 0.011707575380983815, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 292, 'subsample': 0.6277461539764507, 'colsample_bytree': 0.8267877937602705, 'reg_alpha': 0.00259304444103809, 'reg_lambda': 0.00808384092905717}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  23%|██▎       | 114/500 [06:24<29:00,  4.51s/it]

[I 2026-05-18 12:42:38,401] Trial 112 finished with value: 0.9498716443793601 and parameters: {'n_estimators': 296, 'learning_rate': 0.03321338462314428, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 291, 'subsample': 0.6202487273664105, 'colsample_bytree': 0.8288335683071838, 'reg_alpha': 0.0038730480492153987, 'reg_lambda': 0.008487463660076}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  23%|██▎       | 115/500 [06:28<28:26,  4.43s/it]

[I 2026-05-18 12:42:42,665] Trial 115 finished with value: 0.9498529809008884 and parameters: {'n_estimators': 245, 'learning_rate': 0.03345551723068516, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 183, 'subsample': 0.6426531175040667, 'colsample_bytree': 0.8082800738724785, 'reg_alpha': 0.0037206286850296213, 'reg_lambda': 0.007087587282182937}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  23%|██▎       | 116/500 [06:32<27:56,  4.37s/it]

[I 2026-05-18 12:42:46,880] Trial 114 finished with value: 0.9498718692189353 and parameters: {'n_estimators': 300, 'learning_rate': 0.033468231083969915, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 295, 'subsample': 0.6267595399066381, 'colsample_bytree': 0.808705257344231, 'reg_alpha': 0.0030960205018704216, 'reg_lambda': 0.00536721957879264}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  23%|██▎       | 117/500 [06:44<42:20,  6.63s/it]

[I 2026-05-18 12:42:58,782] Trial 116 finished with value: 0.9498669957820706 and parameters: {'n_estimators': 296, 'learning_rate': 0.03388959271449228, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 287, 'subsample': 0.8759445391744719, 'colsample_bytree': 0.8360851869070324, 'reg_alpha': 0.003463354188897158, 'reg_lambda': 0.010537956152204854}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  24%|██▎       | 118/500 [06:50<40:24,  6.35s/it]

[I 2026-05-18 12:43:04,467] Trial 119 finished with value: 0.9498454190661203 and parameters: {'n_estimators': 244, 'learning_rate': 0.02981858446134454, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 98, 'subsample': 0.6187983399475608, 'colsample_bytree': 0.8152915308701257, 'reg_alpha': 0.0019612518662592273, 'reg_lambda': 0.006004640744067996}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  24%|██▍       | 119/500 [06:50<29:38,  4.67s/it]

[I 2026-05-18 12:43:05,226] Trial 118 finished with value: 0.9498690387268619 and parameters: {'n_estimators': 299, 'learning_rate': 0.03357459008467218, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 289, 'subsample': 0.7050638872340774, 'colsample_bytree': 0.8109666926283766, 'reg_alpha': 0.0019890019157869925, 'reg_lambda': 0.005650139785582283}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  24%|██▍       | 120/500 [06:53<26:23,  4.17s/it]

[I 2026-05-18 12:43:08,206] Trial 117 finished with value: 0.9498001514175023 and parameters: {'n_estimators': 300, 'learning_rate': 0.012267460050112922, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 290, 'subsample': 0.6348463876089147, 'colsample_bytree': 0.8409162935818736, 'reg_alpha': 0.057048696985480936, 'reg_lambda': 0.0070770084468032264}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  24%|██▍       | 122/500 [06:59<20:05,  3.19s/it]

[I 2026-05-18 12:43:13,453] Trial 120 finished with value: 0.9498504123498991 and parameters: {'n_estimators': 292, 'learning_rate': 0.0341987314193647, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 102, 'subsample': 0.8787782051655825, 'colsample_bytree': 0.8108740387833001, 'reg_alpha': 0.0005818009911664706, 'reg_lambda': 0.006416408091472268}. Best is trial 94 with value: 0.9498761788288069.
[I 2026-05-18 12:43:13,602] Trial 121 finished with value: 0.9498588200708576 and parameters: {'n_estimators': 276, 'learning_rate': 0.03374495803516492, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 165, 'subsample': 0.708635144371208, 'colsample_bytree': 0.8102059663657531, 'reg_alpha': 0.0013936994995366657, 'reg_lambda': 0.006755379555137377}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  25%|██▍       | 123/500 [07:07<28:32,  4.54s/it]

[I 2026-05-18 12:43:21,321] Trial 122 finished with value: 0.9498656153991911 and parameters: {'n_estimators': 291, 'learning_rate': 0.03388106299821913, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 167, 'subsample': 0.612707571299021, 'colsample_bytree': 0.8082195920815202, 'reg_alpha': 0.0019482499960750653, 'reg_lambda': 0.02463498316633678}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  25%|██▍       | 124/500 [07:16<38:32,  6.15s/it]

[I 2026-05-18 12:43:31,195] Trial 123 finished with value: 0.9498663819469153 and parameters: {'n_estimators': 292, 'learning_rate': 0.033999197158567404, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 273, 'subsample': 0.6058140749175961, 'colsample_bytree': 0.8064633936504304, 'reg_alpha': 0.001050619919803155, 'reg_lambda': 0.025475525246081772}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  25%|██▌       | 125/500 [07:24<40:12,  6.43s/it]

[I 2026-05-18 12:43:38,292] Trial 124 finished with value: 0.9498642412336717 and parameters: {'n_estimators': 290, 'learning_rate': 0.03334103086757354, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 183, 'subsample': 0.6473822895320748, 'colsample_bytree': 0.8097929020254904, 'reg_alpha': 0.00048794943265580636, 'reg_lambda': 0.027180168507236025}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  25%|██▌       | 126/500 [07:27<33:43,  5.41s/it]

[I 2026-05-18 12:43:41,316] Trial 125 finished with value: 0.9498610760795845 and parameters: {'n_estimators': 292, 'learning_rate': 0.03377135008640152, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 274, 'subsample': 0.6023813426140378, 'colsample_bytree': 0.8122453167504752, 'reg_alpha': 0.0022334511559561226, 'reg_lambda': 0.02559920969668151}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  25%|██▌       | 127/500 [07:30<30:22,  4.89s/it]

[I 2026-05-18 12:43:44,997] Trial 126 finished with value: 0.9498600658343846 and parameters: {'n_estimators': 293, 'learning_rate': 0.030091898373762808, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 166, 'subsample': 0.6058553526972946, 'colsample_bytree': 0.8138407222992295, 'reg_alpha': 0.001207172640860683, 'reg_lambda': 0.026350605325927333}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  26%|██▌       | 128/500 [07:35<29:17,  4.72s/it]

[I 2026-05-18 12:43:49,346] Trial 127 finished with value: 0.949866390824891 and parameters: {'n_estimators': 294, 'learning_rate': 0.033529534975001496, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 270, 'subsample': 0.6178335450346962, 'colsample_bytree': 0.8080639723963221, 'reg_alpha': 0.0010468194158531569, 'reg_lambda': 0.024103494897377523}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  26%|██▌       | 129/500 [07:48<45:51,  7.42s/it]

[I 2026-05-18 12:44:03,033] Trial 128 finished with value: 0.9498527567182078 and parameters: {'n_estimators': 293, 'learning_rate': 0.0301926463339478, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 93, 'subsample': 0.6009997809932206, 'colsample_bytree': 0.8086972431950242, 'reg_alpha': 0.0011164670243761048, 'reg_lambda': 0.02181785791232995}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  26%|██▌       | 130/500 [07:53<41:25,  6.72s/it]

[I 2026-05-18 12:44:08,115] Trial 130 finished with value: 0.9498668772091655 and parameters: {'n_estimators': 292, 'learning_rate': 0.03332646339645831, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 276, 'subsample': 0.6005280917691787, 'colsample_bytree': 0.8047621826890542, 'reg_alpha': 0.0009211197142061774, 'reg_lambda': 0.023385141073742333}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  26%|██▌       | 131/500 [07:54<30:46,  5.00s/it]

[I 2026-05-18 12:44:09,122] Trial 129 finished with value: 0.9498665050248158 and parameters: {'n_estimators': 293, 'learning_rate': 0.03315705076840583, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 275, 'subsample': 0.6005812388986113, 'colsample_bytree': 0.8425000312973531, 'reg_alpha': 0.001202853024643268, 'reg_lambda': 0.023437800206534458}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  26%|██▋       | 132/500 [07:55<22:21,  3.65s/it]

[I 2026-05-18 12:44:09,589] Trial 131 finished with value: 0.9498703520747579 and parameters: {'n_estimators': 292, 'learning_rate': 0.03331063897598956, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 271, 'subsample': 0.7171471126062612, 'colsample_bytree': 0.7639005680268788, 'reg_alpha': 0.00037587883437866545, 'reg_lambda': 0.023478316469701978}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  27%|██▋       | 133/500 [07:59<23:15,  3.80s/it]

[I 2026-05-18 12:44:13,772] Trial 133 finished with value: 0.949870544282776 and parameters: {'n_estimators': 293, 'learning_rate': 0.03236535801089246, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 273, 'subsample': 0.6103553436599268, 'colsample_bytree': 0.8229023730173002, 'reg_alpha': 0.00489815812893894, 'reg_lambda': 0.004155671493699479}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  27%|██▋       | 134/500 [08:04<25:27,  4.17s/it]

[I 2026-05-18 12:44:18,819] Trial 132 finished with value: 0.9495879889607904 and parameters: {'n_estimators': 292, 'learning_rate': 0.003115142923288127, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 272, 'subsample': 0.6005773373546915, 'colsample_bytree': 0.7668466109817997, 'reg_alpha': 0.0009258725849826332, 'reg_lambda': 0.021140135786429405}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  27%|██▋       | 135/500 [08:07<23:40,  3.89s/it]

[I 2026-05-18 12:44:22,055] Trial 134 finished with value: 0.9498639849485595 and parameters: {'n_estimators': 293, 'learning_rate': 0.030520146012850684, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 270, 'subsample': 0.6047353321214394, 'colsample_bytree': 0.800732962203458, 'reg_alpha': 0.0006374006733956852, 'reg_lambda': 0.023787398643103686}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  27%|██▋       | 136/500 [08:20<39:20,  6.49s/it]

[I 2026-05-18 12:44:34,588] Trial 135 finished with value: 0.9498690864911934 and parameters: {'n_estimators': 292, 'learning_rate': 0.03251342616465725, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 276, 'subsample': 0.6295242929134631, 'colsample_bytree': 0.8006333247122926, 'reg_alpha': 0.00042118695530342235, 'reg_lambda': 0.029044853404210164}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  27%|██▋       | 137/500 [08:24<34:45,  5.74s/it]

[I 2026-05-18 12:44:38,596] Trial 136 finished with value: 0.9498642871137752 and parameters: {'n_estimators': 295, 'learning_rate': 0.030974215653181245, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 270, 'subsample': 0.6009627201368802, 'colsample_bytree': 0.7914956827081131, 'reg_alpha': 0.00032728483270117023, 'reg_lambda': 0.02128006787377795}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  28%|██▊       | 138/500 [08:28<31:09,  5.16s/it]

[I 2026-05-18 12:44:42,406] Trial 137 finished with value: 0.949863797710148 and parameters: {'n_estimators': 293, 'learning_rate': 0.03104900287796712, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 273, 'subsample': 0.6063329919387372, 'colsample_bytree': 0.7660380766382141, 'reg_alpha': 0.0005002156418228939, 'reg_lambda': 0.04378647501732071}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  28%|██▊       | 139/500 [08:32<29:51,  4.96s/it]

[I 2026-05-18 12:44:46,893] Trial 138 finished with value: 0.9498654577848266 and parameters: {'n_estimators': 295, 'learning_rate': 0.03258811759887935, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 274, 'subsample': 0.6598481794068294, 'colsample_bytree': 0.7675329336596739, 'reg_alpha': 0.000495955028390307, 'reg_lambda': 0.04060364019770774}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  28%|██▊       | 140/500 [08:35<25:29,  4.25s/it]

[I 2026-05-18 12:44:49,485] Trial 139 finished with value: 0.9498651737348028 and parameters: {'n_estimators': 290, 'learning_rate': 0.033189828193471625, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 271, 'subsample': 0.6559288848422948, 'colsample_bytree': 0.8038848610371614, 'reg_alpha': 0.00048362172590735733, 'reg_lambda': 0.04017752468963963}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  28%|██▊       | 141/500 [08:47<40:36,  6.79s/it]

[I 2026-05-18 12:45:02,206] Trial 140 finished with value: 0.949864614541491 and parameters: {'n_estimators': 276, 'learning_rate': 0.03212520718579738, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 272, 'subsample': 0.6589989332407197, 'colsample_bytree': 0.762684641846643, 'reg_alpha': 0.00045111504066931636, 'reg_lambda': 0.04638701551666397}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  28%|██▊       | 142/500 [08:51<34:46,  5.83s/it]

[I 2026-05-18 12:45:05,782] Trial 142 finished with value: 0.9498672006718227 and parameters: {'n_estimators': 275, 'learning_rate': 0.03211547263165035, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 269, 'subsample': 0.6107872874683893, 'colsample_bytree': 0.7953038223838469, 'reg_alpha': 0.0009557095353157943, 'reg_lambda': 0.0420592797981965}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  29%|██▊       | 143/500 [08:53<27:10,  4.57s/it]

[I 2026-05-18 12:45:07,406] Trial 143 finished with value: 0.9498564861795169 and parameters: {'n_estimators': 274, 'learning_rate': 0.031784010561537845, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 270, 'subsample': 0.6131419719619637, 'colsample_bytree': 0.7654242027861448, 'reg_alpha': 0.00039697524180196255, 'reg_lambda': 0.042020317648683046}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  29%|██▉       | 144/500 [08:59<29:37,  4.99s/it]

[I 2026-05-18 12:45:13,398] Trial 141 finished with value: 0.9498545953716746 and parameters: {'n_estimators': 290, 'learning_rate': 0.025940952434829852, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 269, 'subsample': 0.6620566970327153, 'colsample_bytree': 0.7942637581752564, 'reg_alpha': 0.0005136843044890239, 'reg_lambda': 0.04151041999073297}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  29%|██▉       | 145/500 [08:59<21:32,  3.64s/it]

[I 2026-05-18 12:45:13,887] Trial 144 finished with value: 0.9498654742960413 and parameters: {'n_estimators': 275, 'learning_rate': 0.03210552150161851, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 271, 'subsample': 0.6151838196491172, 'colsample_bytree': 0.7630058317782388, 'reg_alpha': 0.00064707825812079, 'reg_lambda': 0.03810900087128411}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  29%|██▉       | 146/500 [09:00<16:07,  2.73s/it]

[I 2026-05-18 12:45:14,480] Trial 145 finished with value: 0.9498643584165952 and parameters: {'n_estimators': 275, 'learning_rate': 0.03226705917934397, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 269, 'subsample': 0.6140758539552421, 'colsample_bytree': 0.7916359911610427, 'reg_alpha': 0.00025119230090393346, 'reg_lambda': 0.03966887965455826}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  29%|██▉       | 147/500 [09:08<26:23,  4.49s/it]

[I 2026-05-18 12:45:23,070] Trial 146 finished with value: 0.9498587096984007 and parameters: {'n_estimators': 274, 'learning_rate': 0.03194434373920707, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 279, 'subsample': 0.612350687367002, 'colsample_bytree': 0.8002515353158745, 'reg_alpha': 0.0003338889362123218, 'reg_lambda': 0.04524857391467418}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  30%|██▉       | 148/500 [09:22<41:40,  7.10s/it]

[I 2026-05-18 12:45:36,277] Trial 148 finished with value: 0.9498672078329007 and parameters: {'n_estimators': 275, 'learning_rate': 0.03904905068362595, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 282, 'subsample': 0.6143970479702979, 'colsample_bytree': 0.7316871883993861, 'reg_alpha': 0.0003759563070551975, 'reg_lambda': 0.04642367513020031}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  30%|██▉       | 149/500 [09:22<29:31,  5.05s/it]

[I 2026-05-18 12:45:36,525] Trial 147 finished with value: 0.9498514641062007 and parameters: {'n_estimators': 275, 'learning_rate': 0.026064648041349794, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 281, 'subsample': 0.6174034509384745, 'colsample_bytree': 0.7904303046172017, 'reg_alpha': 0.0002746913844663421, 'reg_lambda': 0.03825679612305639}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  30%|███       | 150/500 [09:25<26:20,  4.52s/it]

[I 2026-05-18 12:45:39,807] Trial 149 finished with value: 0.9498627535152574 and parameters: {'n_estimators': 276, 'learning_rate': 0.03254470092901002, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 279, 'subsample': 0.662188352770074, 'colsample_bytree': 0.7520416890333559, 'reg_alpha': 0.00026742071749822553, 'reg_lambda': 0.12154696244585042}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  30%|███       | 151/500 [09:26<19:42,  3.39s/it]

[I 2026-05-18 12:45:40,552] Trial 155 finished with value: 0.9498015257669576 and parameters: {'n_estimators': 106, 'learning_rate': 0.038122271266146, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 280, 'subsample': 0.6220770437460061, 'colsample_bytree': 0.8249869410421147, 'reg_alpha': 0.00024152240276284313, 'reg_lambda': 0.10756875173075217}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  31%|███       | 153/500 [09:32<17:14,  2.98s/it]

[I 2026-05-18 12:45:46,678] Trial 151 finished with value: 0.9498731106574146 and parameters: {'n_estimators': 278, 'learning_rate': 0.038935010962153155, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 279, 'subsample': 0.6194719252788631, 'colsample_bytree': 0.7462828376639197, 'reg_alpha': 0.00021646543589889277, 'reg_lambda': 0.11406646715959476}. Best is trial 94 with value: 0.9498761788288069.
[I 2026-05-18 12:45:46,786] Trial 150 finished with value: 0.949849103699606 and parameters: {'n_estimators': 274, 'learning_rate': 0.026076575338783967, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 279, 'subsample': 0.6168800630997131, 'colsample_bytree': 0.8016770427960763, 'reg_alpha': 0.00020077860726835415, 'reg_lambda': 0.004275981033673659}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  31%|███       | 154/500 [09:45<35:18,  6.12s/it]

[I 2026-05-18 12:46:00,263] Trial 152 finished with value: 0.9498668579399883 and parameters: {'n_estimators': 274, 'learning_rate': 0.03818944659814718, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 280, 'subsample': 0.617310836094359, 'colsample_bytree': 0.8258367459678703, 'reg_alpha': 0.0002604943009158258, 'reg_lambda': 0.0034365133451859566}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 94. Best value: 0.949876:  31%|███       | 156/500 [09:48<20:33,  3.59s/it]

[I 2026-05-18 12:46:02,875] Trial 153 finished with value: 0.9498753076957955 and parameters: {'n_estimators': 274, 'learning_rate': 0.03829617882700149, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 280, 'subsample': 0.6145125759784938, 'colsample_bytree': 0.7480441661843189, 'reg_alpha': 0.00031707294097090965, 'reg_lambda': 0.1799254726606378}. Best is trial 94 with value: 0.9498761788288069.
[I 2026-05-18 12:46:02,999] Trial 160 finished with value: 0.9498201198780096 and parameters: {'n_estimators': 112, 'learning_rate': 0.037908086488239234, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 287, 'subsample': 0.6304639261902113, 'colsample_bytree': 0.7325652764199716, 'reg_alpha': 0.00016986622771468924, 'reg_lambda': 0.11689101391736234}. Best is trial 94 with value: 0.9498761788288069.

Best trial: 154. Best value: 0.949877:  31%|███▏      | 157/500 [09:49<16:25,  2.87s/it]

[I 2026-05-18 12:46:04,206] Trial 154 finished with value: 0.9498765088398224 and parameters: {'n_estimators': 276, 'learning_rate': 0.03791095263778279, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 282, 'subsample': 0.6274494068222727, 'colsample_bytree': 0.7367126525792792, 'reg_alpha': 0.0009122698492153065, 'reg_lambda': 0.10331925416924029}. Best is trial 154 with value: 0.9498765088398224.

Best trial: 154. Best value: 0.949877:  32%|███▏      | 158/500 [09:52<16:10,  2.84s/it]

[I 2026-05-18 12:46:06,966] Trial 159 finished with value: 0.9498309213519477 and parameters: {'n_estimators': 121, 'learning_rate': 0.03836917971298506, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 286, 'subsample': 0.6270657566423048, 'colsample_bytree': 0.7224497137232656, 'reg_alpha': 5.251291345516458e-05, 'reg_lambda': 0.10206978318209868}. Best is trial 154 with value: 0.9498765088398224.

Best trial: 154. Best value: 0.949877:  32%|███▏      | 159/500 [09:54<14:38,  2.58s/it]

[I 2026-05-18 12:46:08,913] Trial 161 finished with value: 0.9498260957955231 and parameters: {'n_estimators': 123, 'learning_rate': 0.03904592756749947, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 287, 'subsample': 0.6291101296559334, 'colsample_bytree': 0.729562919680844, 'reg_alpha': 0.0008910695869449267, 'reg_lambda': 0.0032943001577769833}. Best is trial 154 with value: 0.9498765088398224.

Best trial: 154. Best value: 0.949877:  32%|███▏      | 161/500 [09:56<09:43,  1.72s/it]

[I 2026-05-18 12:46:10,923] Trial 157 finished with value: 0.9498701227650892 and parameters: {'n_estimators': 288, 'learning_rate': 0.03900592033808385, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 280, 'subsample': 0.6309996140283952, 'colsample_bytree': 0.7490374306203794, 'reg_alpha': 0.0002539553399639631, 'reg_lambda': 0.003978275118576086}. Best is trial 154 with value: 0.9498765088398224.
[I 2026-05-18 12:46:11,048] Trial 156 finished with value: 0.9498504352022611 and parameters: {'n_estimators': 262, 'learning_rate': 0.02623320493333116, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 280, 'subsample': 0.6290300785783172, 'colsample_bytree': 0.7508327872921147, 'reg_alpha': 0.00024593452038963856, 'reg_lambda': 0.09919076148495207}. Best is trial 154 with value: 0.9498765088398224.

Best trial: 154. Best value: 0.949877:  32%|███▏      | 162/500 [10:03<18:21,  3.26s/it]

[I 2026-05-18 12:46:17,903] Trial 158 finished with value: 0.9498702398552865 and parameters: {'n_estimators': 287, 'learning_rate': 0.03893988913963849, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 287, 'subsample': 0.629800030715789, 'colsample_bytree': 0.7454589009141418, 'reg_alpha': 0.0001559616753186849, 'reg_lambda': 0.13872121839420645}. Best is trial 154 with value: 0.9498765088398224.

[I 2026-05-18 12:46:39,529] Trial 162 finished with value: 0.9498731154382881 and parameters: {'n_estimators': 288, 'learning_rate': 0.03923352057007969, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 289, 'subsample': 0.7322892827518488, 'colsample_bytree': 0.7247962806736375, 'reg_alpha': 0.00014982064311017668, 'reg_lambda': 0.22450487835315283}. Best is trial 154 with value: 0.9498765088398224.

Best trial: 154. Best value: 0.949877:  33%|███▎      | 164/500 [10:25<34:45,  6.21s/it]

[I 2026-05-18 12:46:39,729] Trial 164 finished with value: 0.9498666188080509 and parameters: {'n_estimators': 263, 'learning_rate': 0.03758679468647296, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 288, 'subsample': 0.7307443267884285, 'colsample_bytree': 0.7438040493063116, 'reg_alpha': 0.00013265207619525817, 'reg_lambda': 0.07650099620227993}. Best is trial 154 with value: 0.9498765088398224.

Best trial: 154. Best value: 0.949877:  33%|███▎      | 165/500 [10:29<31:10,  5.58s/it]

[I 2026-05-18 12:46:43,892] Trial 163 finished with value: 0.9498724139715466 and parameters: {'n_estimators': 265, 'learning_rate': 0.039287373947731526, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 289, 'subsample': 0.6336814677573362, 'colsample_bytree': 0.7286870441945952, 'reg_alpha': 8.643579277422766e-05, 'reg_lambda': 0.0039969049662954845}. Best is trial 154 with value: 0.9498765088398224.

Best trial: 154. Best value: 0.949877:  33%|███▎      | 166/500 [10:41<41:58,  7.54s/it]

[I 2026-05-18 12:46:55,986] Trial 167 finished with value: 0.9498724374346675 and parameters: {'n_estimators': 261, 'learning_rate': 0.03896773050277799, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 289, 'subsample': 0.636460998952001, 'colsample_bytree': 0.7196743334147111, 'reg_alpha': 0.00010570418350690623, 'reg_lambda': 0.39723665596023944}. Best is trial 154 with value: 0.9498765088398224.

Best trial: 165. Best value: 0.949884:  34%|███▎      | 168/500 [10:45<24:43,  4.47s/it]

[I 2026-05-18 12:46:59,485] Trial 168 finished with value: 0.9498717603649387 and parameters: {'n_estimators': 260, 'learning_rate': 0.039795913840004575, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 286, 'subsample': 0.7509677518960389, 'colsample_bytree': 0.7217794286001887, 'reg_alpha': 0.0007742283355409525, 'reg_lambda': 0.25282807905521476}. Best is trial 154 with value: 0.9498765088398224.
[I 2026-05-18 12:46:59,600] Trial 165 finished with value: 0.9498836550084226 and parameters: {'n_estimators': 287, 'learning_rate': 0.040266952979101336, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 287, 'subsample': 0.6365679046436848, 'colsample_bytree': 0.7273126934196374, 'reg_alpha': 8.48530814197626e-05, 'reg_lambda': 0.2613110736694998}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  34%|███▍      | 169/500 [10:45<18:01,  3.27s/it]

[I 2026-05-18 12:47:00,096] Trial 169 finished with value: 0.9498755847980271 and parameters: {'n_estimators': 263, 'learning_rate': 0.03999374391596664, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 291, 'subsample': 0.7333430550183451, 'colsample_bytree': 0.7112161149306956, 'reg_alpha': 0.00011621290862813816, 'reg_lambda': 0.4450841873561858}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  34%|███▍      | 170/500 [10:46<13:52,  2.52s/it]

[I 2026-05-18 12:47:00,867] Trial 166 finished with value: 0.9498732204484561 and parameters: {'n_estimators': 262, 'learning_rate': 0.0389736662531861, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 287, 'subsample': 0.6334104098917533, 'colsample_bytree': 0.7153155540379968, 'reg_alpha': 0.00013962513977866067, 'reg_lambda': 0.30079779321622463}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  34%|███▍      | 171/500 [10:49<14:49,  2.70s/it]

[I 2026-05-18 12:47:03,990] Trial 170 finished with value: 0.949880440597083 and parameters: {'n_estimators': 265, 'learning_rate': 0.04163815577569077, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 256, 'subsample': 0.6403133917651702, 'colsample_bytree': 0.7428891085913795, 'reg_alpha': 6.873562158983556e-05, 'reg_lambda': 0.28335717147310036}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  34%|███▍      | 172/500 [10:50<11:12,  2.05s/it]

[I 2026-05-18 12:47:04,508] Trial 171 finished with value: 0.9498784057528674 and parameters: {'n_estimators': 264, 'learning_rate': 0.04059967960856884, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 256, 'subsample': 0.7342170917886689, 'colsample_bytree': 0.7172072733712481, 'reg_alpha': 5.583647693455961e-05, 'reg_lambda': 0.2918269009346282}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  35%|███▍      | 173/500 [10:52<10:40,  1.96s/it]

[I 2026-05-18 12:47:06,274] Trial 172 finished with value: 0.9498747357429098 and parameters: {'n_estimators': 288, 'learning_rate': 0.042301346949497484, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 263, 'subsample': 0.728373738623323, 'colsample_bytree': 0.70787888854285, 'reg_alpha': 9.245624434524247e-05, 'reg_lambda': 0.2831745162068322}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  35%|███▍      | 174/500 [10:59<19:38,  3.62s/it]

[I 2026-05-18 12:47:13,742] Trial 173 finished with value: 0.9498711466327823 and parameters: {'n_estimators': 267, 'learning_rate': 0.03896954408483622, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 291, 'subsample': 0.6443209553586652, 'colsample_bytree': 0.7418367776480495, 'reg_alpha': 0.00014065398215411669, 'reg_lambda': 0.40896918697701706}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  35%|███▌      | 175/500 [11:18<44:47,  8.27s/it]

[I 2026-05-18 12:47:32,867] Trial 174 finished with value: 0.9498724339312801 and parameters: {'n_estimators': 266, 'learning_rate': 0.04309521879517796, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 291, 'subsample': 0.7094680174005477, 'colsample_bytree': 0.7126538909856951, 'reg_alpha': 0.0001211807658629114, 'reg_lambda': 0.30015722351416696}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  35%|███▌      | 176/500 [11:24<40:47,  7.56s/it]

[I 2026-05-18 12:47:38,751] Trial 175 finished with value: 0.9498719058660317 and parameters: {'n_estimators': 287, 'learning_rate': 0.04207474828072234, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 293, 'subsample': 0.637834872779476, 'colsample_bytree': 0.7123042441881935, 'reg_alpha': 8.680273724607705e-05, 'reg_lambda': 0.3035000228712009}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  35%|███▌      | 177/500 [11:27<32:36,  6.06s/it]

[I 2026-05-18 12:47:41,300] Trial 176 finished with value: 0.9498816370665653 and parameters: {'n_estimators': 300, 'learning_rate': 0.04129548938336812, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 292, 'subsample': 0.6410102526052278, 'colsample_bytree': 0.7028474676903051, 'reg_alpha': 9.29223761846438e-05, 'reg_lambda': 0.3816971524996313}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  36%|███▌      | 178/500 [11:37<40:18,  7.51s/it]

[I 2026-05-18 12:47:52,211] Trial 178 finished with value: 0.9498746675393663 and parameters: {'n_estimators': 267, 'learning_rate': 0.04166815261173294, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 300, 'subsample': 0.7495132935130098, 'colsample_bytree': 0.7018349420703626, 'reg_alpha': 8.597048694466394e-05, 'reg_lambda': 0.2884311796822616}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  36%|███▌      | 179/500 [11:38<28:50,  5.39s/it]

[I 2026-05-18 12:47:52,659] Trial 181 finished with value: 0.9498818496647619 and parameters: {'n_estimators': 266, 'learning_rate': 0.04278366731354045, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 294, 'subsample': 0.7600119564780498, 'colsample_bytree': 0.7108973782020248, 'reg_alpha': 7.354476491593914e-05, 'reg_lambda': 0.32558593520785334}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  36%|███▌      | 180/500 [11:39<21:26,  4.02s/it]

[I 2026-05-18 12:47:53,481] Trial 180 finished with value: 0.9498778427510107 and parameters: {'n_estimators': 265, 'learning_rate': 0.04211796535373644, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 294, 'subsample': 0.7550052655996881, 'colsample_bytree': 0.7079162186991285, 'reg_alpha': 9.144172981332515e-05, 'reg_lambda': 0.3554486249794577}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  36%|███▌      | 181/500 [11:39<15:31,  2.92s/it]

[I 2026-05-18 12:47:53,857] Trial 179 finished with value: 0.9498758362141556 and parameters: {'n_estimators': 267, 'learning_rate': 0.04263340704276157, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 299, 'subsample': 0.7532459475019524, 'colsample_bytree': 0.7114002896749962, 'reg_alpha': 7.846870256271346e-05, 'reg_lambda': 0.2627033676744127}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  36%|███▋      | 182/500 [11:39<11:13,  2.12s/it]

[I 2026-05-18 12:47:54,086] Trial 177 finished with value: 0.9498773351473396 and parameters: {'n_estimators': 267, 'learning_rate': 0.03964834470688985, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 291, 'subsample': 0.6403441760253195, 'colsample_bytree': 0.7094741437175344, 'reg_alpha': 9.191119370965737e-05, 'reg_lambda': 0.31355403282767175}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  37%|███▋      | 183/500 [11:43<13:58,  2.65s/it]

[I 2026-05-18 12:47:57,978] Trial 183 finished with value: 0.9498727210246785 and parameters: {'n_estimators': 265, 'learning_rate': 0.04180288848492849, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 292, 'subsample': 0.640134813272254, 'colsample_bytree': 0.7066454133795111, 'reg_alpha': 8.744748588710502e-05, 'reg_lambda': 0.3331376290909538}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  37%|███▋      | 184/500 [11:45<12:13,  2.32s/it]

[I 2026-05-18 12:47:59,532] Trial 182 finished with value: 0.9498731246028485 and parameters: {'n_estimators': 266, 'learning_rate': 0.04151731867412358, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 291, 'subsample': 0.7555585886345755, 'colsample_bytree': 0.7133186404344535, 'reg_alpha': 7.985928091671534e-05, 'reg_lambda': 0.37171324690043295}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  37%|███▋      | 185/500 [11:46<11:00,  2.10s/it]

[I 2026-05-18 12:48:01,098] Trial 184 finished with value: 0.9498748230371173 and parameters: {'n_estimators': 265, 'learning_rate': 0.0418752797481595, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 255, 'subsample': 0.7568964043061565, 'colsample_bytree': 0.7073044619562179, 'reg_alpha': 8.495429736200974e-05, 'reg_lambda': 0.33651043531711056}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  37%|███▋      | 186/500 [11:51<15:01,  2.87s/it]

[I 2026-05-18 12:48:05,770] Trial 185 finished with value: 0.9498770624933849 and parameters: {'n_estimators': 267, 'learning_rate': 0.04208859857420777, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 294, 'subsample': 0.7375070680477926, 'colsample_bytree': 0.7089416492516059, 'reg_alpha': 6.544800348901518e-05, 'reg_lambda': 0.31442773044846656}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  37%|███▋      | 187/500 [12:12<43:01,  8.25s/it]

[I 2026-05-18 12:48:26,570] Trial 186 finished with value: 0.9498749166782489 and parameters: {'n_estimators': 266, 'learning_rate': 0.0423023059564717, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 294, 'subsample': 0.7600594507467969, 'colsample_bytree': 0.711826296127986, 'reg_alpha': 9.599832321599414e-05, 'reg_lambda': 0.3296862672157941}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  38%|███▊      | 188/500 [12:19<40:28,  7.78s/it]

[I 2026-05-18 12:48:33,278] Trial 187 finished with value: 0.9498775498964612 and parameters: {'n_estimators': 265, 'learning_rate': 0.04233842807584396, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 300, 'subsample': 0.7569420445796103, 'colsample_bytree': 0.7095471111089485, 'reg_alpha': 8.027519547340003e-05, 'reg_lambda': 0.22264563819835098}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  38%|███▊      | 189/500 [12:20<31:14,  6.03s/it]

[I 2026-05-18 12:48:35,197] Trial 188 finished with value: 0.9498686203143588 and parameters: {'n_estimators': 266, 'learning_rate': 0.041555885462023844, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 295, 'subsample': 0.7421764386344333, 'colsample_bytree': 0.7083784078387276, 'reg_alpha': 8.319727570859267e-05, 'reg_lambda': 0.23769198460695182}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  38%|███▊      | 190/500 [12:29<34:56,  6.76s/it]

[I 2026-05-18 12:48:43,678] Trial 189 finished with value: 0.9498719239212937 and parameters: {'n_estimators': 266, 'learning_rate': 0.04824593558165984, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 294, 'subsample': 0.7567281146874512, 'colsample_bytree': 0.7017485461096916, 'reg_alpha': 8.640416760424688e-05, 'reg_lambda': 1.2067317538425373}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  38%|███▊      | 191/500 [12:31<27:46,  5.39s/it]

[I 2026-05-18 12:48:45,882] Trial 194 finished with value: 0.9498722911666253 and parameters: {'n_estimators': 260, 'learning_rate': 0.04628830795627041, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 300, 'subsample': 0.7584825118281054, 'colsample_bytree': 0.6884700369663798, 'reg_alpha': 3.211798068157835e-05, 'reg_lambda': 0.9008500671707246}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  38%|███▊      | 192/500 [12:33<22:52,  4.46s/it]

[I 2026-05-18 12:48:48,137] Trial 192 finished with value: 0.9498765947167286 and parameters: {'n_estimators': 265, 'learning_rate': 0.04815379720030927, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 298, 'subsample': 0.7576230137393991, 'colsample_bytree': 0.6953239507557009, 'reg_alpha': 5.43572195334906e-05, 'reg_lambda': 0.9535730907096316}. Best is trial 165 with value: 0.9498836550084226.
[I 2026-05-18 12:48:48,147] Trial 191 finished with value: 0.949868650137299 and parameters: {'n_estimators': 268, 'learning_rate': 0.04963152335261304, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 298, 'subsample': 0.7348445134731656, 'colsample_bytree': 0.7004693603326707, 'reg_alpha': 4.9433969978686055e-05, 'reg_lambda': 1.1107070563478525}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  39%|███▉      | 194/500 [12:34<12:49,  2.51s/it]

[I 2026-05-18 12:48:48,650] Trial 195 finished with value: 0.9498715465016996 and parameters: {'n_estimators': 269, 'learning_rate': 0.04810242236077417, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 299, 'subsample': 0.759167401585225, 'colsample_bytree': 0.6868832183428695, 'reg_alpha': 4.194216792082388e-05, 'reg_lambda': 1.133946783947242}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  39%|███▉      | 195/500 [12:34<10:05,  1.99s/it]

[I 2026-05-18 12:48:48,996] Trial 190 finished with value: 0.9498749950270875 and parameters: {'n_estimators': 267, 'learning_rate': 0.04851409521263806, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 294, 'subsample': 0.7593109158621711, 'colsample_bytree': 0.7041584307009016, 'reg_alpha': 9.154599617712025e-05, 'reg_lambda': 0.9981361994745683}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  39%|███▉      | 196/500 [12:35<08:01,  1.58s/it]

[I 2026-05-18 12:48:49,483] Trial 196 finished with value: 0.9498779829326403 and parameters: {'n_estimators': 268, 'learning_rate': 0.04987623442126655, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 300, 'subsample': 0.7617686920534412, 'colsample_bytree': 0.7008871406557304, 'reg_alpha': 2.2604361915376058e-05, 'reg_lambda': 1.1569840007758982}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  39%|███▉      | 197/500 [12:35<06:44,  1.34s/it]

[I 2026-05-18 12:48:50,140] Trial 193 finished with value: 0.9498683890470898 and parameters: {'n_estimators': 267, 'learning_rate': 0.04645396917382799, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 299, 'subsample': 0.7605767302502175, 'colsample_bytree': 0.6920040549869412, 'reg_alpha': 2.59810669543175e-05, 'reg_lambda': 1.1031087117956773}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  40%|███▉      | 198/500 [12:42<14:18,  2.84s/it]

[I 2026-05-18 12:48:56,871] Trial 197 finished with value: 0.9498697029200676 and parameters: {'n_estimators': 268, 'learning_rate': 0.04700532489298869, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 300, 'subsample': 0.7604342886753837, 'colsample_bytree': 0.6928631500797373, 'reg_alpha': 2.9317443137271846e-05, 'reg_lambda': 1.1222177017192003}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  40%|███▉      | 199/500 [13:03<40:22,  8.05s/it]

[I 2026-05-18 12:49:17,946] Trial 198 finished with value: 0.9498798991939301 and parameters: {'n_estimators': 266, 'learning_rate': 0.04863894591115878, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 244, 'subsample': 0.7577801562538943, 'colsample_bytree': 0.6920118921928005, 'reg_alpha': 3.4275615195848514e-05, 'reg_lambda': 1.0425043892234083}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  40%|████      | 200/500 [13:13<42:49,  8.56s/it]

[I 2026-05-18 12:49:27,763] Trial 200 finished with value: 0.9498811079361748 and parameters: {'n_estimators': 270, 'learning_rate': 0.04609094764610429, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 256, 'subsample': 0.7679331287103865, 'colsample_bytree': 0.6918447612399282, 'reg_alpha': 2.595853165378006e-05, 'reg_lambda': 1.0682626795967973}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  40%|████      | 201/500 [13:14<31:57,  6.41s/it]

[I 2026-05-18 12:49:28,992] Trial 199 finished with value: 0.9498711754394966 and parameters: {'n_estimators': 271, 'learning_rate': 0.04778921794396426, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 299, 'subsample': 0.76225258223625, 'colsample_bytree': 0.69446806049788, 'reg_alpha': 1.7187458373422274e-05, 'reg_lambda': 1.0976043833323408}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  40%|████      | 202/500 [13:21<31:47,  6.40s/it]

[I 2026-05-18 12:49:35,348] Trial 201 finished with value: 0.9498763152904385 and parameters: {'n_estimators': 259, 'learning_rate': 0.045295740050477554, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 299, 'subsample': 0.7674083044236111, 'colsample_bytree': 0.6782434980695524, 'reg_alpha': 1.9596253600222568e-05, 'reg_lambda': 0.5287913128524899}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  41%|████      | 203/500 [13:24<26:37,  5.38s/it]

[I 2026-05-18 12:49:38,322] Trial 202 finished with value: 0.9498689673869107 and parameters: {'n_estimators': 270, 'learning_rate': 0.04981851296183462, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 300, 'subsample': 0.7751293317530996, 'colsample_bytree': 0.6741209606335283, 'reg_alpha': 4.7425642628079725e-05, 'reg_lambda': 0.5759550219296692}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 165. Best value: 0.949884:  41%|████      | 204/500 [13:25<19:55,  4.04s/it]

[I 2026-05-18 12:49:39,177] Trial 206 finished with value: 0.9498789659571164 and parameters: {'n_estimators': 259, 'learning_rate': 0.045477709270978585, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 246, 'subsample': 0.7705606099831014, 'colsample_bytree': 0.6787151082507877, 'reg_alpha': 2.6380091417974642e-05, 'reg_lambda': 0.5786989756096576}. Best is trial 165 with value: 0.9498836550084226.
[I 2026-05-18 12:49:39,349] Trial 205 finished with value: 0.9498755538629922 and parameters: {'n_estimators': 259, 'learning_rate': 0.04419368815295047, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 300, 'subsample': 0.7777580005402129, 'colsample_bytree': 0.6773007503817384, 'reg_alpha': 2.176794266349968e-05, 'reg_lambda': 0.5905053521308495}. Best is trial 165 with value: 0.9498836550084226.

Best trial: 204. Best value: 0.949885:  41%|████      | 206/500 [13:26<11:51,  2.42s/it]

[I 2026-05-18 12:49:40,682] Trial 204 finished with value: 0.9498848631694182 and parameters: {'n_estimators': 270, 'learning_rate': 0.04585736230161231, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 254, 'subsample': 0.7760029143297948, 'colsample_bytree': 0.6734790832681298, 'reg_alpha': 2.0675087167727874e-05, 'reg_lambda': 0.584959189766096}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  42%|████▏     | 208/500 [13:27<07:06,  1.46s/it]

[I 2026-05-18 12:49:41,730] Trial 207 finished with value: 0.9498740041693228 and parameters: {'n_estimators': 259, 'learning_rate': 0.045276639744634174, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 242, 'subsample': 0.7701054519416526, 'colsample_bytree': 0.6813910508648239, 'reg_alpha': 2.0074569297039182e-05, 'reg_lambda': 0.5690587483497284}. Best is trial 204 with value: 0.9498848631694182.
[I 2026-05-18 12:49:41,914] Trial 208 finished with value: 0.9498739708935455 and parameters: {'n_estimators': 257, 'learning_rate': 0.04435754002701676, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 255, 'subsample': 0.76908197232356, 'colsample_bytree': 0.6723995033523856, 'reg_alpha': 1.6526740199635957e-05, 'reg_lambda': 0.5651489780671451}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  42%|████▏     | 209/500 [13:28<05:40,  1.17s/it]

[I 2026-05-18 12:49:42,409] Trial 203 finished with value: 0.9498825819739732 and parameters: {'n_estimators': 259, 'learning_rate': 0.04522120416074713, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 254, 'subsample': 0.77909987212068, 'colsample_bytree': 0.6759753296402128, 'reg_alpha': 3.2430167951793294e-05, 'reg_lambda': 0.5820943120272317}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  42%|████▏     | 210/500 [13:30<08:02,  1.66s/it]

[I 2026-05-18 12:49:45,224] Trial 213 finished with value: 0.9496337362591731 and parameters: {'n_estimators': 38, 'learning_rate': 0.04993764216532449, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 294, 'subsample': 0.7754067716676071, 'colsample_bytree': 0.6799354162131511, 'reg_alpha': 1.1952052989621617e-05, 'reg_lambda': 1.958823970925807}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  42%|████▏     | 211/500 [13:36<13:52,  2.88s/it]

[I 2026-05-18 12:49:50,930] Trial 209 finished with value: 0.9498720104150955 and parameters: {'n_estimators': 280, 'learning_rate': 0.04467850395210266, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 254, 'subsample': 0.7822473080998035, 'colsample_bytree': 0.6701601759938047, 'reg_alpha': 1.878452869109521e-05, 'reg_lambda': 0.6038944048626537}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  42%|████▏     | 212/500 [13:55<37:14,  7.76s/it]

[I 2026-05-18 12:50:10,096] Trial 210 finished with value: 0.9498801480585108 and parameters: {'n_estimators': 259, 'learning_rate': 0.04519547771140686, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 246, 'subsample': 0.7770156682590517, 'colsample_bytree': 0.672127743811973, 'reg_alpha': 1.1706300985302272e-05, 'reg_lambda': 0.5716918696704222}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  43%|████▎     | 213/500 [14:06<40:40,  8.50s/it]

[I 2026-05-18 12:50:20,351] Trial 212 finished with value: 0.9498772974214414 and parameters: {'n_estimators': 259, 'learning_rate': 0.04508699322080369, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 252, 'subsample': 0.7766049082245523, 'colsample_bytree': 0.6788167859114753, 'reg_alpha': 5.7010709840693364e-05, 'reg_lambda': 0.6121716117402509}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  43%|████▎     | 214/500 [14:07<29:48,  6.25s/it]

[I 2026-05-18 12:50:21,332] Trial 211 finished with value: 0.949872153118562 and parameters: {'n_estimators': 258, 'learning_rate': 0.0442285430228907, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 243, 'subsample': 0.7744832805183366, 'colsample_bytree': 0.6727258207338368, 'reg_alpha': 1.6491763893214948e-05, 'reg_lambda': 0.5820580855149604}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  43%|████▎     | 215/500 [14:13<29:50,  6.28s/it]

[I 2026-05-18 12:50:27,692] Trial 214 finished with value: 0.9498698359558306 and parameters: {'n_estimators': 259, 'learning_rate': 0.04442629953329872, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 294, 'subsample': 0.7695958821185318, 'colsample_bytree': 0.6748997710981878, 'reg_alpha': 1.3141307601285484e-05, 'reg_lambda': 0.5552210973902757}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  43%|████▎     | 216/500 [14:13<21:17,  4.50s/it]

[I 2026-05-18 12:50:28,045] Trial 215 finished with value: 0.9498765591463316 and parameters: {'n_estimators': 258, 'learning_rate': 0.04574270950347405, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 256, 'subsample': 0.7903645211836702, 'colsample_bytree': 0.6743741292204788, 'reg_alpha': 1.421487467553241e-05, 'reg_lambda': 0.5979158229342673}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  43%|████▎     | 217/500 [14:15<17:42,  3.75s/it]

[I 2026-05-18 12:50:30,041] Trial 216 finished with value: 0.9498766254161332 and parameters: {'n_estimators': 259, 'learning_rate': 0.045202675725346066, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 248, 'subsample': 0.7902539257044549, 'colsample_bytree': 0.6606681370922519, 'reg_alpha': 1.1442851714310956e-05, 'reg_lambda': 1.8001860161466012}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  44%|████▎     | 218/500 [14:17<14:45,  3.14s/it]

[I 2026-05-18 12:50:31,748] Trial 218 finished with value: 0.9498801370857997 and parameters: {'n_estimators': 257, 'learning_rate': 0.044422881294684496, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 246, 'subsample': 0.7889810387238831, 'colsample_bytree': 0.6522599638795534, 'reg_alpha': 1.4326892185674665e-05, 'reg_lambda': 2.0362563652429735}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  44%|████▍     | 219/500 [14:18<11:28,  2.45s/it]

[I 2026-05-18 12:50:32,600] Trial 219 finished with value: 0.9498776525156682 and parameters: {'n_estimators': 260, 'learning_rate': 0.0444196317980386, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 243, 'subsample': 0.7785036255213558, 'colsample_bytree': 0.6590640477688896, 'reg_alpha': 3.507577943312905e-05, 'reg_lambda': 1.926295485731963}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  44%|████▍     | 220/500 [14:19<09:55,  2.13s/it]

[I 2026-05-18 12:50:33,955] Trial 217 finished with value: 0.9498830007667672 and parameters: {'n_estimators': 279, 'learning_rate': 0.04526234015077066, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 253, 'subsample': 0.7915238060453021, 'colsample_bytree': 0.6808261174732303, 'reg_alpha': 1.4706675969409622e-05, 'reg_lambda': 1.9090186602452053}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  44%|████▍     | 221/500 [14:23<12:18,  2.65s/it]

[I 2026-05-18 12:50:37,830] Trial 220 finished with value: 0.9498825272107128 and parameters: {'n_estimators': 280, 'learning_rate': 0.045245626100889516, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 295, 'subsample': 0.8040513430506875, 'colsample_bytree': 0.6790143114301755, 'reg_alpha': 1.3864392547504886e-05, 'reg_lambda': 2.4501153407749903}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 204. Best value: 0.949885:  44%|████▍     | 222/500 [14:24<10:14,  2.21s/it]

[I 2026-05-18 12:50:39,000] Trial 221 finished with value: 0.9498776656275412 and parameters: {'n_estimators': 280, 'learning_rate': 0.04426169242873924, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 246, 'subsample': 0.7921665306138258, 'colsample_bytree': 0.6618645897458783, 'reg_alpha': 5.9506774117223085e-05, 'reg_lambda': 1.732224347599661}. Best is trial 204 with value: 0.9498848631694182.

Best trial: 222. Best value: 0.949886:  45%|████▍     | 223/500 [14:26<10:10,  2.20s/it]

[I 2026-05-18 12:50:41,205] Trial 222 finished with value: 0.9498855935228651 and parameters: {'n_estimators': 259, 'learning_rate': 0.04391197608904245, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 248, 'subsample': 0.7930522187037894, 'colsample_bytree': 0.6549973442462628, 'reg_alpha': 1.0501918140672241e-05, 'reg_lambda': 1.9097089654276824}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  45%|████▍     | 224/500 [14:40<26:04,  5.67s/it]

[I 2026-05-18 12:50:54,943] Trial 225 finished with value: 0.9498563449846547 and parameters: {'n_estimators': 150, 'learning_rate': 0.04601358423987744, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 246, 'subsample': 0.7884690829072251, 'colsample_bytree': 0.6632937382585883, 'reg_alpha': 5.934480280519051e-05, 'reg_lambda': 1.8062040556717274}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  45%|████▌     | 225/500 [14:43<21:42,  4.74s/it]

[I 2026-05-18 12:50:57,482] Trial 224 finished with value: 0.9498557685236761 and parameters: {'n_estimators': 159, 'learning_rate': 0.045822874269404935, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 248, 'subsample': 0.7880656708136592, 'colsample_bytree': 0.65995837629006, 'reg_alpha': 3.773232851741124e-05, 'reg_lambda': 0.18066445813724535}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  45%|████▌     | 226/500 [14:47<20:49,  4.56s/it]

[I 2026-05-18 12:51:01,651] Trial 223 finished with value: 0.949880902967623 and parameters: {'n_estimators': 258, 'learning_rate': 0.04462015747984728, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 247, 'subsample': 0.7880214270354414, 'colsample_bytree': 0.6651224241255006, 'reg_alpha': 5.9591032167668864e-05, 'reg_lambda': 1.5455945166270304}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  45%|████▌     | 227/500 [14:54<23:54,  5.25s/it]

[I 2026-05-18 12:51:08,511] Trial 231 finished with value: 0.9498565318272046 and parameters: {'n_estimators': 161, 'learning_rate': 0.04706079135017118, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 246, 'subsample': 0.796398098301975, 'colsample_bytree': 0.6600828105732298, 'reg_alpha': 3.85500113807508e-05, 'reg_lambda': 2.089377367591028}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  46%|████▌     | 228/500 [15:03<29:03,  6.41s/it]

[I 2026-05-18 12:51:17,643] Trial 227 finished with value: 0.9498768006319771 and parameters: {'n_estimators': 249, 'learning_rate': 0.04637577267462777, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 245, 'subsample': 0.7924308084615936, 'colsample_bytree': 0.6592806919265429, 'reg_alpha': 5.70032276659272e-05, 'reg_lambda': 1.8352770650902583}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  46%|████▌     | 229/500 [15:05<22:32,  4.99s/it]

[I 2026-05-18 12:51:19,321] Trial 229 finished with value: 0.9498796529196799 and parameters: {'n_estimators': 248, 'learning_rate': 0.046338296957220686, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 246, 'subsample': 0.7906009393531822, 'colsample_bytree': 0.6608137432401263, 'reg_alpha': 1.0542556244856897e-05, 'reg_lambda': 2.0319812050013835}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  46%|████▌     | 230/500 [15:05<16:42,  3.71s/it]

[I 2026-05-18 12:51:20,046] Trial 228 finished with value: 0.9498787163047654 and parameters: {'n_estimators': 248, 'learning_rate': 0.046518344242987994, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 248, 'subsample': 0.7924600289662559, 'colsample_bytree': 0.6522535855737658, 'reg_alpha': 3.7929790256995214e-05, 'reg_lambda': 2.0267910136801217}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  46%|████▌     | 231/500 [15:07<13:49,  3.08s/it]

[I 2026-05-18 12:51:21,654] Trial 226 finished with value: 0.9498602002748724 and parameters: {'n_estimators': 280, 'learning_rate': 0.04680300635070026, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 246, 'subsample': 0.793628431739166, 'colsample_bytree': 0.6549436445098531, 'reg_alpha': 3.772197885769219e-05, 'reg_lambda': 0.19275948546755953}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  46%|████▋     | 232/500 [15:07<10:12,  2.28s/it]

[I 2026-05-18 12:51:22,091] Trial 230 finished with value: 0.9498709623213142 and parameters: {'n_estimators': 249, 'learning_rate': 0.04679950268094705, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 247, 'subsample': 0.7881711779449656, 'colsample_bytree': 0.6591849152073309, 'reg_alpha': 1.0307908082791243e-05, 'reg_lambda': 1.8548767698152355}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  47%|████▋     | 233/500 [15:11<12:10,  2.73s/it]

[I 2026-05-18 12:51:25,862] Trial 233 finished with value: 0.9498738338726389 and parameters: {'n_estimators': 249, 'learning_rate': 0.04608577240864393, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 248, 'subsample': 0.8015457436738062, 'colsample_bytree': 0.6606679374950345, 'reg_alpha': 4.08741779728562e-05, 'reg_lambda': 3.685052456158377}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  47%|████▋     | 234/500 [15:12<09:42,  2.19s/it]

[I 2026-05-18 12:51:26,778] Trial 232 finished with value: 0.9498737483238863 and parameters: {'n_estimators': 249, 'learning_rate': 0.045709524720925744, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 248, 'subsample': 0.8053044456173676, 'colsample_bytree': 0.6585636353357156, 'reg_alpha': 3.260542828940888e-05, 'reg_lambda': 4.463834595592265}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  47%|████▋     | 235/500 [15:17<13:31,  3.06s/it]

[I 2026-05-18 12:51:31,897] Trial 234 finished with value: 0.9498734286804613 and parameters: {'n_estimators': 279, 'learning_rate': 0.047430672963565755, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 236, 'subsample': 0.8080725875753364, 'colsample_bytree': 0.6587243824016987, 'reg_alpha': 3.510650372680387e-05, 'reg_lambda': 4.15344196405309}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  47%|████▋     | 236/500 [15:27<22:26,  5.10s/it]

[I 2026-05-18 12:51:41,744] Trial 244 finished with value: 0.9497589104130354 and parameters: {'n_estimators': 69, 'learning_rate': 0.04949632523473182, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 233, 'subsample': 0.8161355625357731, 'colsample_bytree': 0.6316881940158016, 'reg_alpha': 2.626896908259339e-05, 'reg_lambda': 4.2275483798071045}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  47%|████▋     | 237/500 [15:29<17:53,  4.08s/it]

[I 2026-05-18 12:51:43,458] Trial 235 finished with value: 0.9498795760905105 and parameters: {'n_estimators': 248, 'learning_rate': 0.04984564423816823, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 232, 'subsample': 0.8119986691381303, 'colsample_bytree': 0.6501123912472137, 'reg_alpha': 3.500353835129704e-05, 'reg_lambda': 5.025449789872714}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  48%|████▊     | 238/500 [15:32<16:25,  3.76s/it]

[I 2026-05-18 12:51:46,462] Trial 236 finished with value: 0.9498777331754231 and parameters: {'n_estimators': 248, 'learning_rate': 0.04999989617720015, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 239, 'subsample': 0.8041665946174561, 'colsample_bytree': 0.6450833962746788, 'reg_alpha': 1.018057871020973e-05, 'reg_lambda': 6.063081626965412}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  48%|████▊     | 239/500 [15:36<16:37,  3.82s/it]

[I 2026-05-18 12:51:50,415] Trial 237 finished with value: 0.9498800778018248 and parameters: {'n_estimators': 250, 'learning_rate': 0.04781042998062923, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 235, 'subsample': 0.8094822691424386, 'colsample_bytree': 0.6414165419589115, 'reg_alpha': 2.7937679156653822e-05, 'reg_lambda': 3.7905801262980643}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  48%|████▊     | 240/500 [15:43<21:06,  4.87s/it]

[I 2026-05-18 12:51:57,753] Trial 238 finished with value: 0.9498775396991201 and parameters: {'n_estimators': 248, 'learning_rate': 0.04951799479754332, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 235, 'subsample': 0.8061621438190745, 'colsample_bytree': 0.6418660472600866, 'reg_alpha': 2.777852972880881e-05, 'reg_lambda': 3.627205722344659}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  48%|████▊     | 241/500 [15:52<26:04,  6.04s/it]

[I 2026-05-18 12:52:06,519] Trial 243 finished with value: 0.9498678554607511 and parameters: {'n_estimators': 241, 'learning_rate': 0.049980255386847666, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 236, 'subsample': 0.8014029022263243, 'colsample_bytree': 0.6354577097834249, 'reg_alpha': 2.843645607521629e-05, 'reg_lambda': 3.3405494799469566}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  48%|████▊     | 242/500 [15:53<19:46,  4.60s/it]

[I 2026-05-18 12:52:07,749] Trial 241 finished with value: 0.9498719623448674 and parameters: {'n_estimators': 249, 'learning_rate': 0.04966911614227478, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 234, 'subsample': 0.8056809032549902, 'colsample_bytree': 0.6361855956190653, 'reg_alpha': 2.7375855115470696e-05, 'reg_lambda': 3.9698135256966105}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  49%|████▊     | 243/500 [15:53<14:14,  3.33s/it]

[I 2026-05-18 12:52:08,104] Trial 239 finished with value: 0.9498844074153467 and parameters: {'n_estimators': 250, 'learning_rate': 0.04956969108499019, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 237, 'subsample': 0.8069838238619318, 'colsample_bytree': 0.6389824343068199, 'reg_alpha': 1.0267030904975234e-05, 'reg_lambda': 3.715139707670068}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  49%|████▉     | 244/500 [15:54<10:56,  2.56s/it]

[I 2026-05-18 12:52:08,882] Trial 242 finished with value: 0.9498811049646154 and parameters: {'n_estimators': 250, 'learning_rate': 0.04935837805005192, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 259, 'subsample': 0.8103490852404057, 'colsample_bytree': 0.685358574444836, 'reg_alpha': 2.5586196436122758e-05, 'reg_lambda': 4.089941263848003}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  49%|████▉     | 245/500 [15:58<12:45,  3.00s/it]

[I 2026-05-18 12:52:12,927] Trial 240 finished with value: 0.9498818072661525 and parameters: {'n_estimators': 279, 'learning_rate': 0.049228202035482775, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 236, 'subsample': 0.8031019998030401, 'colsample_bytree': 0.6370069707643798, 'reg_alpha': 1.0240370307649248e-05, 'reg_lambda': 4.184687283762955}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  49%|████▉     | 246/500 [16:03<15:26,  3.65s/it]

[I 2026-05-18 12:52:18,075] Trial 245 finished with value: 0.9498701402589594 and parameters: {'n_estimators': 271, 'learning_rate': 0.042804149820444094, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 234, 'subsample': 0.812956260488835, 'colsample_bytree': 0.6494802364892388, 'reg_alpha': 2.7498599536486568e-05, 'reg_lambda': 2.8825789938942625}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  49%|████▉     | 247/500 [16:05<12:38,  3.00s/it]

[I 2026-05-18 12:52:19,556] Trial 246 finished with value: 0.9498708692179548 and parameters: {'n_estimators': 242, 'learning_rate': 0.04326993593381376, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 232, 'subsample': 0.8148637665466264, 'colsample_bytree': 0.6430663929000775, 'reg_alpha': 2.436869478924966e-05, 'reg_lambda': 3.028298866635438}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  50%|████▉     | 248/500 [16:13<19:00,  4.53s/it]

[I 2026-05-18 12:52:27,645] Trial 248 finished with value: 0.9498690478536649 and parameters: {'n_estimators': 240, 'learning_rate': 0.043217334946829354, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 241, 'subsample': 0.7808884447216071, 'colsample_bytree': 0.6446134058349527, 'reg_alpha': 2.2391949905545213e-05, 'reg_lambda': 2.8260512445652024}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  50%|████▉     | 249/500 [16:14<14:08,  3.38s/it]

[I 2026-05-18 12:52:28,337] Trial 249 finished with value: 0.9498822538418977 and parameters: {'n_estimators': 241, 'learning_rate': 0.04932459388973268, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 240, 'subsample': 0.8069507228558473, 'colsample_bytree': 0.6444498919157898, 'reg_alpha': 2.4427814893481597e-05, 'reg_lambda': 6.864009389511069}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  50%|█████     | 250/500 [16:20<17:30,  4.20s/it]

[I 2026-05-18 12:52:34,474] Trial 247 finished with value: 0.9498796460286222 and parameters: {'n_estimators': 271, 'learning_rate': 0.04316350125666789, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 238, 'subsample': 0.7839616906888658, 'colsample_bytree': 0.6851441467925798, 'reg_alpha': 2.3323421662658505e-05, 'reg_lambda': 2.8615625612928226}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  50%|█████     | 251/500 [16:20<13:05,  3.16s/it]

[I 2026-05-18 12:52:35,185] Trial 250 finished with value: 0.9498735444544811 and parameters: {'n_estimators': 242, 'learning_rate': 0.04970191967981617, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 237, 'subsample': 0.8093203660668363, 'colsample_bytree': 0.6418470160094235, 'reg_alpha': 2.4085790630477097e-05, 'reg_lambda': 9.38538773770655}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  50%|█████     | 252/500 [16:29<19:46,  4.79s/it]

[I 2026-05-18 12:52:43,780] Trial 251 finished with value: 0.94987124483691 and parameters: {'n_estimators': 242, 'learning_rate': 0.04263912206074641, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 240, 'subsample': 0.8302881753860925, 'colsample_bytree': 0.6477685171096793, 'reg_alpha': 1.0163492015132e-05, 'reg_lambda': 10.316454442354765}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  51%|█████     | 253/500 [16:38<25:28,  6.19s/it]

[I 2026-05-18 12:52:53,240] Trial 252 finished with value: 0.9498735029551968 and parameters: {'n_estimators': 240, 'learning_rate': 0.043346918599577615, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 239, 'subsample': 0.7824141245488774, 'colsample_bytree': 0.6476182149351387, 'reg_alpha': 1.0295457776727451e-05, 'reg_lambda': 9.272247852063618}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  51%|█████     | 254/500 [16:39<18:20,  4.47s/it]

[I 2026-05-18 12:52:53,722] Trial 254 finished with value: 0.9498747688846241 and parameters: {'n_estimators': 230, 'learning_rate': 0.043232486811976084, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 239, 'subsample': 0.8298155542358224, 'colsample_bytree': 0.6470132658029024, 'reg_alpha': 1.1984948464415433e-05, 'reg_lambda': 9.761670093757523}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  51%|█████     | 255/500 [16:41<14:52,  3.64s/it]

[I 2026-05-18 12:52:55,415] Trial 255 finished with value: 0.9498770624110543 and parameters: {'n_estimators': 243, 'learning_rate': 0.04308472227175204, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 258, 'subsample': 0.8299580227383141, 'colsample_bytree': 0.6474314193154108, 'reg_alpha': 1.0278311809308447e-05, 'reg_lambda': 6.7622390772996}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  51%|█████     | 256/500 [16:42<11:30,  2.83s/it]

[I 2026-05-18 12:52:56,335] Trial 253 finished with value: 0.9498750771814877 and parameters: {'n_estimators': 254, 'learning_rate': 0.04329967625890998, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 242, 'subsample': 0.7821074510921364, 'colsample_bytree': 0.6078507460251666, 'reg_alpha': 1.0332413322825744e-05, 'reg_lambda': 2.6730444378916536}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  51%|█████▏    | 257/500 [16:47<14:57,  3.69s/it]

[I 2026-05-18 12:53:02,055] Trial 256 finished with value: 0.9498771614120051 and parameters: {'n_estimators': 256, 'learning_rate': 0.04345824947683906, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 260, 'subsample': 0.8332800725047153, 'colsample_bytree': 0.6084700431891839, 'reg_alpha': 1.504848795113388e-05, 'reg_lambda': 11.774942084126014}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  52%|█████▏    | 258/500 [16:51<14:57,  3.71s/it]

[I 2026-05-18 12:53:05,806] Trial 257 finished with value: 0.9498744855939141 and parameters: {'n_estimators': 240, 'learning_rate': 0.04343095260782916, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 258, 'subsample': 0.7979414443223957, 'colsample_bytree': 0.6165845457769104, 'reg_alpha': 1.4059016043855054e-05, 'reg_lambda': 8.822174106392918}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  52%|█████▏    | 259/500 [16:55<15:42,  3.91s/it]

[I 2026-05-18 12:53:10,175] Trial 258 finished with value: 0.9498747167143453 and parameters: {'n_estimators': 254, 'learning_rate': 0.047659032853143754, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 261, 'subsample': 0.8245952369859333, 'colsample_bytree': 0.6097919283062062, 'reg_alpha': 1.4642256732047515e-05, 'reg_lambda': 6.726259986854647}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  52%|█████▏    | 260/500 [16:56<11:46,  2.94s/it]

[I 2026-05-18 12:53:10,875] Trial 260 finished with value: 0.9498705377773525 and parameters: {'n_estimators': 231, 'learning_rate': 0.047666882257117967, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 261, 'subsample': 0.78562943202028, 'colsample_bytree': 0.6514358397804465, 'reg_alpha': 1.7342175364624543e-05, 'reg_lambda': 7.547463575797933}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  52%|█████▏    | 261/500 [17:02<15:30,  3.89s/it]

[I 2026-05-18 12:53:16,963] Trial 259 finished with value: 0.9498733669341615 and parameters: {'n_estimators': 254, 'learning_rate': 0.047048554135347954, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 260, 'subsample': 0.7846237954730166, 'colsample_bytree': 0.6847892655566757, 'reg_alpha': 1.4452457178429498e-05, 'reg_lambda': 7.362683993226509}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  53%|█████▎    | 263/500 [17:10<13:49,  3.50s/it]

[I 2026-05-18 12:53:24,422] Trial 262 finished with value: 0.949878151425656 and parameters: {'n_estimators': 253, 'learning_rate': 0.047427734451273025, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 257, 'subsample': 0.8212977069651805, 'colsample_bytree': 0.6210105578405254, 'reg_alpha': 1.3922677459565815e-05, 'reg_lambda': 5.881928935392546}. Best is trial 222 with value: 0.9498855935228651.
[I 2026-05-18 12:53:24,513] Trial 261 finished with value: 0.9497661777292536 and parameters: {'n_estimators': 253, 'learning_rate': 0.015192020501620997, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 215, 'subsample': 0.8253935552042266, 'colsample_bytree': 0.6509156420171645, 'reg_alpha': 1.4227192235369026e-05, 'reg_lambda': 7.727874977246349}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  53%|█████▎    | 264/500 [17:13<13:38,  3.47s/it]

[I 2026-05-18 12:53:27,899] Trial 263 finished with value: 0.9498706441098044 and parameters: {'n_estimators': 230, 'learning_rate': 0.04726599779467399, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 260, 'subsample': 0.8203904815333598, 'colsample_bytree': 0.6251204100115296, 'reg_alpha': 1.5830873338958646e-05, 'reg_lambda': 8.463760924845857}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  53%|█████▎    | 265/500 [17:24<22:36,  5.77s/it]

[I 2026-05-18 12:53:39,053] Trial 264 finished with value: 0.9498802884628283 and parameters: {'n_estimators': 254, 'learning_rate': 0.04754610996496423, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 258, 'subsample': 0.825156638073089, 'colsample_bytree': 0.6217013279084408, 'reg_alpha': 1.2749312020842407e-05, 'reg_lambda': 5.740087513933017}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  53%|█████▎    | 266/500 [17:27<18:21,  4.71s/it]

[I 2026-05-18 12:53:41,243] Trial 265 finished with value: 0.949875551610929 and parameters: {'n_estimators': 251, 'learning_rate': 0.04727117826233754, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 259, 'subsample': 0.8210714283285577, 'colsample_bytree': 0.6267678209728423, 'reg_alpha': 1.678946135620684e-05, 'reg_lambda': 5.30930492161281}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  53%|█████▎    | 267/500 [17:29<15:19,  3.95s/it]

[I 2026-05-18 12:53:43,449] Trial 266 finished with value: 0.9498791429175137 and parameters: {'n_estimators': 254, 'learning_rate': 0.047452834747174134, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 215, 'subsample': 0.79839403253522, 'colsample_bytree': 0.6230540519245074, 'reg_alpha': 1.5495032697281592e-05, 'reg_lambda': 2.560118643499481}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  54%|█████▎    | 268/500 [17:33<15:15,  3.94s/it]

[I 2026-05-18 12:53:47,369] Trial 267 finished with value: 0.9498791870822194 and parameters: {'n_estimators': 254, 'learning_rate': 0.04731543386537954, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 260, 'subsample': 0.7994936915456942, 'colsample_bytree': 0.6206825391477758, 'reg_alpha': 1.542333409149858e-05, 'reg_lambda': 6.097836428107859}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  54%|█████▍    | 269/500 [17:41<20:36,  5.35s/it]

[I 2026-05-18 12:53:56,039] Trial 269 finished with value: 0.9498741013570164 and parameters: {'n_estimators': 255, 'learning_rate': 0.04750261226263705, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 229, 'subsample': 0.7974750501742652, 'colsample_bytree': 0.6682053303714365, 'reg_alpha': 1.6975968720353062e-05, 'reg_lambda': 5.335784953694889}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  54%|█████▍    | 270/500 [17:42<14:57,  3.90s/it]

[I 2026-05-18 12:53:56,524] Trial 268 finished with value: 0.9493234731264275 and parameters: {'n_estimators': 253, 'learning_rate': 0.005215493721691625, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 253, 'subsample': 0.8210584343041776, 'colsample_bytree': 0.6855888842848732, 'reg_alpha': 1.5271239382360854e-05, 'reg_lambda': 6.116545814864944}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  54%|█████▍    | 271/500 [17:44<13:04,  3.42s/it]

[I 2026-05-18 12:53:58,847] Trial 271 finished with value: 0.9498832946737693 and parameters: {'n_estimators': 254, 'learning_rate': 0.04677589810476847, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 252, 'subsample': 0.8204654068104064, 'colsample_bytree': 0.628214348039611, 'reg_alpha': 1.7808012745158972e-05, 'reg_lambda': 5.3190909256084815}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  54%|█████▍    | 272/500 [17:50<15:35,  4.10s/it]

[I 2026-05-18 12:54:04,541] Trial 270 finished with value: 0.949788992539804 and parameters: {'n_estimators': 252, 'learning_rate': 0.015612702811793536, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 229, 'subsample': 0.7977348046399244, 'colsample_bytree': 0.6301076682822265, 'reg_alpha': 1.9270049801280873e-05, 'reg_lambda': 1.4805765228245897}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  55%|█████▍    | 273/500 [17:52<13:14,  3.50s/it]

[I 2026-05-18 12:54:06,637] Trial 272 finished with value: 0.9498767476227108 and parameters: {'n_estimators': 254, 'learning_rate': 0.04685299492819016, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 251, 'subsample': 0.7987085030482399, 'colsample_bytree': 0.6688200112687631, 'reg_alpha': 2.0697744568015558e-05, 'reg_lambda': 5.288690731314696}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  55%|█████▍    | 274/500 [18:00<18:04,  4.80s/it]

[I 2026-05-18 12:54:14,466] Trial 273 finished with value: 0.949874809542569 and parameters: {'n_estimators': 255, 'learning_rate': 0.046800967824474606, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 252, 'subsample': 0.8135914050348194, 'colsample_bytree': 0.6668026387602218, 'reg_alpha': 2.0143425283947822e-05, 'reg_lambda': 2.5707099362980808}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  55%|█████▌    | 275/500 [18:01<13:54,  3.71s/it]

[I 2026-05-18 12:54:15,629] Trial 274 finished with value: 0.9494348324530156 and parameters: {'n_estimators': 246, 'learning_rate': 0.005852158553366407, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 252, 'subsample': 0.7991512374736705, 'colsample_bytree': 0.6271845523022562, 'reg_alpha': 1.996197881007496e-05, 'reg_lambda': 0.7869423018338831}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  55%|█████▌    | 276/500 [18:02<11:12,  3.00s/it]

[I 2026-05-18 12:54:16,990] Trial 275 finished with value: 0.9498782567060491 and parameters: {'n_estimators': 272, 'learning_rate': 0.045909425947660225, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 252, 'subsample': 0.795096482871348, 'colsample_bytree': 0.6680087679230784, 'reg_alpha': 1.8663656364250695e-05, 'reg_lambda': 2.6421625180960824}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  55%|█████▌    | 277/500 [18:14<20:38,  5.56s/it]

[I 2026-05-18 12:54:28,450] Trial 277 finished with value: 0.9498748273965013 and parameters: {'n_estimators': 247, 'learning_rate': 0.045739797274092754, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 253, 'subsample': 0.7999394491381464, 'colsample_bytree': 0.6701323915155454, 'reg_alpha': 1.9835710257972013e-05, 'reg_lambda': 2.474378158360875}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  56%|█████▌    | 278/500 [18:15<16:11,  4.38s/it]

[I 2026-05-18 12:54:30,120] Trial 276 finished with value: 0.9498756304928471 and parameters: {'n_estimators': 246, 'learning_rate': 0.04582106725704567, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 252, 'subsample': 0.7974718427660524, 'colsample_bytree': 0.6688297833664792, 'reg_alpha': 1.975968427741517e-05, 'reg_lambda': 1.396389318864866}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  56%|█████▌    | 279/500 [18:18<14:13,  3.86s/it]

[I 2026-05-18 12:54:32,772] Trial 278 finished with value: 0.9498811649986543 and parameters: {'n_estimators': 256, 'learning_rate': 0.049745425806537735, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 227, 'subsample': 0.8014875630494753, 'colsample_bytree': 0.6835672043603402, 'reg_alpha': 2.057732861290537e-05, 'reg_lambda': 1.4572231938943525}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  56%|█████▌    | 280/500 [18:24<16:11,  4.42s/it]

[I 2026-05-18 12:54:38,501] Trial 287 pruned.

Best trial: 222. Best value: 0.949886:  56%|█████▌    | 281/500 [18:25<12:30,  3.42s/it]

[I 2026-05-18 12:54:39,592] Trial 279 finished with value: 0.9493245610555816 and parameters: {'n_estimators': 246, 'learning_rate': 0.00521385055738751, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 253, 'subsample': 0.8127943393328975, 'colsample_bytree': 0.629121548480837, 'reg_alpha': 1.9973353467760012e-05, 'reg_lambda': 2.7278414973430354}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  56%|█████▋    | 282/500 [18:27<10:56,  3.01s/it]

[I 2026-05-18 12:54:41,634] Trial 281 finished with value: 0.9498839536339739 and parameters: {'n_estimators': 246, 'learning_rate': 0.049860579800755235, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 252, 'subsample': 0.8122668850465721, 'colsample_bytree': 0.6303744181119982, 'reg_alpha': 2.2100837703774727e-05, 'reg_lambda': 14.602778562833945}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  57%|█████▋    | 283/500 [18:28<08:30,  2.35s/it]

[I 2026-05-18 12:54:42,467] Trial 282 finished with value: 0.9498674309941209 and parameters: {'n_estimators': 246, 'learning_rate': 0.040991025981177244, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 253, 'subsample': 0.8115029504515152, 'colsample_bytree': 0.6344604707491281, 'reg_alpha': 2.15674897765667e-05, 'reg_lambda': 1.4230212257475914}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  57%|█████▋    | 284/500 [18:37<16:00,  4.45s/it]

[I 2026-05-18 12:54:51,797] Trial 280 finished with value: 0.9494914054026328 and parameters: {'n_estimators': 273, 'learning_rate': 0.005598332116148839, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 253, 'subsample': 0.8111856516817776, 'colsample_bytree': 0.6315783612302399, 'reg_alpha': 2.0182254407474163e-05, 'reg_lambda': 15.498168690595087}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  57%|█████▋    | 285/500 [18:40<14:40,  4.10s/it]

[I 2026-05-18 12:54:55,077] Trial 288 finished with value: 0.9497014391775824 and parameters: {'n_estimators': 272, 'learning_rate': 0.04983802088942998, 'max_depth': 4, 'num_leaves': 2, 'min_child_samples': 264, 'subsample': 0.8129819410979483, 'colsample_bytree': 0.6336999976798872, 'reg_alpha': 3.331071843111302e-05, 'reg_lambda': 1.5194897796033036}. Best is trial 222 with value: 0.9498855935228651.
[I 2026-05-18 12:54:55,116] Trial 284 finished with value: 0.949873299630464 and parameters: {'n_estimators': 271, 'learning_rate': 0.04980572214352065, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 252, 'subsample': 0.8104034535219645, 'colsample_bytree': 0.6330708141479551, 'reg_alpha': 2.1615904578758814e-05, 'reg_lambda': 22.198900638487}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  57%|█████▋    | 287/500 [18:43<09:48,  2.76s/it]

[I 2026-05-18 12:54:57,479] Trial 283 finished with value: 0.9498796950910938 and parameters: {'n_estimators': 271, 'learning_rate': 0.04482192756447655, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 251, 'subsample': 0.8133362817879218, 'colsample_bytree': 0.637912521976956, 'reg_alpha': 2.006202990733798e-05, 'reg_lambda': 0.7741811086179918}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  58%|█████▊    | 288/500 [18:51<14:55,  4.22s/it]

[I 2026-05-18 12:55:06,145] Trial 285 finished with value: 0.9498718244343266 and parameters: {'n_estimators': 271, 'learning_rate': 0.04969247891790275, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 252, 'subsample': 0.8100138635171101, 'colsample_bytree': 0.6341392117352432, 'reg_alpha': 2.2274717802016302e-05, 'reg_lambda': 1.4103923449287261}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  58%|█████▊    | 289/500 [18:52<11:14,  3.20s/it]

[I 2026-05-18 12:55:06,443] Trial 286 finished with value: 0.9498752903492305 and parameters: {'n_estimators': 273, 'learning_rate': 0.049836273863993384, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 265, 'subsample': 0.852569804317326, 'colsample_bytree': 0.6374846949893381, 'reg_alpha': 3.090730107322165e-05, 'reg_lambda': 3.748241973351523}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  58%|█████▊    | 290/500 [19:06<21:55,  6.27s/it]

[I 2026-05-18 12:55:20,919] Trial 290 finished with value: 0.9498664648451628 and parameters: {'n_estimators': 262, 'learning_rate': 0.04113760479835591, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 226, 'subsample': 0.8094179754441069, 'colsample_bytree': 0.6901520851391624, 'reg_alpha': 4.3704603570487013e-05, 'reg_lambda': 0.7839866126937094}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  58%|█████▊    | 291/500 [19:09<18:35,  5.34s/it]

[I 2026-05-18 12:55:23,874] Trial 289 finished with value: 0.9498733170833438 and parameters: {'n_estimators': 279, 'learning_rate': 0.049722417290039254, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 264, 'subsample': 0.8089451044639221, 'colsample_bytree': 0.6366954066504389, 'reg_alpha': 4.261343582017119e-05, 'reg_lambda': 4.429518014966435}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  58%|█████▊    | 292/500 [19:17<20:54,  6.03s/it]

[I 2026-05-18 12:55:31,641] Trial 291 finished with value: 0.9498801930652071 and parameters: {'n_estimators': 272, 'learning_rate': 0.04090081161800237, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 242, 'subsample': 0.8140854488393645, 'colsample_bytree': 0.6927971346756919, 'reg_alpha': 4.337537195002119e-05, 'reg_lambda': 1.4297613382653007}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  59%|█████▊    | 293/500 [19:17<15:17,  4.43s/it]

[I 2026-05-18 12:55:32,156] Trial 292 finished with value: 0.949878301230558 and parameters: {'n_estimators': 261, 'learning_rate': 0.04112743821975204, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 230, 'subsample': 0.8070593865677717, 'colsample_bytree': 0.6947514318006611, 'reg_alpha': 3.577352771582829e-05, 'reg_lambda': 0.828883258403745}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  59%|█████▉    | 294/500 [19:19<12:42,  3.70s/it]

[I 2026-05-18 12:55:34,097] Trial 293 finished with value: 0.9498701478169712 and parameters: {'n_estimators': 261, 'learning_rate': 0.04023025339316576, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 240, 'subsample': 0.7847634518471107, 'colsample_bytree': 0.6909907794964721, 'reg_alpha': 4.633637539044553e-05, 'reg_lambda': 14.969174906805252}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  59%|█████▉    | 295/500 [19:21<10:23,  3.04s/it]

[I 2026-05-18 12:55:35,562] Trial 294 finished with value: 0.949878308938571 and parameters: {'n_estimators': 272, 'learning_rate': 0.04981144313167858, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 241, 'subsample': 0.6497773327969758, 'colsample_bytree': 0.6934625440221637, 'reg_alpha': 4.55624743197907e-05, 'reg_lambda': 3.46847671817097}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  59%|█████▉    | 296/500 [19:29<16:02,  4.72s/it]

[I 2026-05-18 12:55:44,245] Trial 296 finished with value: 0.9498724107114196 and parameters: {'n_estimators': 261, 'learning_rate': 0.04997403676520269, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 241, 'subsample': 0.7833249066011537, 'colsample_bytree': 0.6928359431592556, 'reg_alpha': 1.0023800081231529e-05, 'reg_lambda': 0.8385764337483285}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  59%|█████▉    | 297/500 [19:33<15:08,  4.47s/it]

[I 2026-05-18 12:55:48,132] Trial 295 finished with value: 0.9497139947197374 and parameters: {'n_estimators': 262, 'learning_rate': 0.009053019877406268, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 242, 'subsample': 0.8624139691515089, 'colsample_bytree': 0.6918218060589761, 'reg_alpha': 4.5234827392842615e-05, 'reg_lambda': 3.402626398534082}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  60%|█████▉    | 298/500 [19:35<11:51,  3.52s/it]

[I 2026-05-18 12:55:49,413] Trial 298 finished with value: 0.94986682306054 and parameters: {'n_estimators': 261, 'learning_rate': 0.04108458234700096, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 243, 'subsample': 0.649986913268515, 'colsample_bytree': 0.6975245608633119, 'reg_alpha': 1.0078103733874835e-05, 'reg_lambda': 37.638174753261595}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  60%|█████▉    | 299/500 [19:37<10:52,  3.24s/it]

[I 2026-05-18 12:55:52,003] Trial 297 finished with value: 0.949821869238316 and parameters: {'n_estimators': 260, 'learning_rate': 0.01973463056274331, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 241, 'subsample': 0.7808126109719697, 'colsample_bytree': 0.6893504964585884, 'reg_alpha': 1.031798706861938e-05, 'reg_lambda': 0.8799781027204309}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  60%|██████    | 300/500 [19:40<10:40,  3.20s/it]

[I 2026-05-18 12:55:55,115] Trial 300 finished with value: 0.9498785099966405 and parameters: {'n_estimators': 261, 'learning_rate': 0.041220206361324466, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 242, 'subsample': 0.6529739632667066, 'colsample_bytree': 0.6964748780829917, 'reg_alpha': 1.1667636726732158e-05, 'reg_lambda': 0.7882485967656317}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  60%|██████    | 301/500 [19:49<15:44,  4.74s/it]

[I 2026-05-18 12:56:03,414] Trial 299 finished with value: 0.9498763478640111 and parameters: {'n_estimators': 280, 'learning_rate': 0.04105790794616684, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 243, 'subsample': 0.8441790932447761, 'colsample_bytree': 0.6961941116935614, 'reg_alpha': 4.500136148359439e-05, 'reg_lambda': 0.8612264373175383}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  60%|██████    | 302/500 [20:02<23:44,  7.19s/it]

[I 2026-05-18 12:56:16,386] Trial 302 finished with value: 0.9498671388943721 and parameters: {'n_estimators': 261, 'learning_rate': 0.044552694260219794, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 244, 'subsample': 0.8418512726677054, 'colsample_bytree': 0.6162340167168661, 'reg_alpha': 44.6864573343951, 'reg_lambda': 0.8455016390252026}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  61%|██████    | 303/500 [20:06<20:25,  6.22s/it]

[I 2026-05-18 12:56:20,361] Trial 301 finished with value: 0.9498703519571634 and parameters: {'n_estimators': 282, 'learning_rate': 0.0441571959561147, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 243, 'subsample': 0.8347085031019413, 'colsample_bytree': 0.6931357855330617, 'reg_alpha': 1.0575512492207356e-05, 'reg_lambda': 0.8114179859836964}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  61%|██████    | 304/500 [20:06<14:30,  4.44s/it]

[I 2026-05-18 12:56:20,630] Trial 306 finished with value: 0.9497975752636766 and parameters: {'n_estimators': 196, 'learning_rate': 0.019856761942428205, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 245, 'subsample': 0.821979831231143, 'colsample_bytree': 0.6826136993079983, 'reg_alpha': 1.2682054607214202e-05, 'reg_lambda': 0.9201079237309674}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  61%|██████    | 305/500 [20:12<15:44,  4.84s/it]

[I 2026-05-18 12:56:26,405] Trial 303 finished with value: 0.9498751409530156 and parameters: {'n_estimators': 282, 'learning_rate': 0.040846106773318513, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 244, 'subsample': 0.820753358436669, 'colsample_bytree': 0.6897356159884064, 'reg_alpha': 4.768715847081022e-05, 'reg_lambda': 0.7974576764638335}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  61%|██████    | 306/500 [20:13<11:55,  3.69s/it]

[I 2026-05-18 12:56:27,407] Trial 305 finished with value: 0.9498742945696567 and parameters: {'n_estimators': 285, 'learning_rate': 0.04452488975314352, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 242, 'subsample': 0.8340758162484437, 'colsample_bytree': 0.6793269092716357, 'reg_alpha': 1.2837399313137404e-05, 'reg_lambda': 28.43479342020125}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  61%|██████▏   | 307/500 [20:16<11:53,  3.69s/it]

[I 2026-05-18 12:56:31,109] Trial 304 finished with value: 0.9498081205271636 and parameters: {'n_estimators': 283, 'learning_rate': 0.020122900525422635, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 245, 'subsample': 0.8332328281691802, 'colsample_bytree': 0.6983859565511018, 'reg_alpha': 33.85569246840705, 'reg_lambda': 18.595908607844553}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  62%|██████▏   | 308/500 [20:24<15:28,  4.84s/it]

[I 2026-05-18 12:56:38,620] Trial 307 finished with value: 0.9498790122642019 and parameters: {'n_estimators': 283, 'learning_rate': 0.04456148030323642, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 245, 'subsample': 0.8383669589429709, 'colsample_bytree': 0.6175412304044436, 'reg_alpha': 1.3338569677622497e-05, 'reg_lambda': 0.7918183647379242}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  62%|██████▏   | 309/500 [20:29<15:43,  4.94s/it]

[I 2026-05-18 12:56:43,806] Trial 308 finished with value: 0.9498740161510313 and parameters: {'n_estimators': 283, 'learning_rate': 0.044066527084425745, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 245, 'subsample': 0.8207673751041779, 'colsample_bytree': 0.6162419448085742, 'reg_alpha': 1.2848983119494982e-05, 'reg_lambda': 0.8382054537057806}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  62%|██████▏   | 310/500 [20:30<11:59,  3.79s/it]

[I 2026-05-18 12:56:44,871] Trial 310 finished with value: 0.949876027143268 and parameters: {'n_estimators': 283, 'learning_rate': 0.04422852166791789, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 246, 'subsample': 0.8176194982427476, 'colsample_bytree': 0.6148041093442345, 'reg_alpha': 1.381618453033433e-05, 'reg_lambda': 0.44594942269144766}. Best is trial 222 with value: 0.9498855935228651.
[I 2026-05-18 12:56:44,912] Trial 309 finished with value: 0.9498824157085535 and parameters: {'n_estimators': 283, 'learning_rate': 0.04436177909311599, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 248, 'subsample': 0.8401806576598915, 'colsample_bytree': 0.616986180170525, 'reg_alpha': 1.3063003473316046e-05, 'reg_lambda': 0.8182116665295993}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  62%|██████▏   | 312/500 [20:36<10:26,  3.33s/it]

[I 2026-05-18 12:56:50,503] Trial 311 finished with value: 0.9498713061976061 and parameters: {'n_estimators': 286, 'learning_rate': 0.04458969271620623, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 250, 'subsample': 0.8361222795098375, 'colsample_bytree': 0.6852157481359373, 'reg_alpha': 2.679358261059462e-05, 'reg_lambda': 0.4627904397337464}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  63%|██████▎   | 313/500 [20:43<13:48,  4.43s/it]

[I 2026-05-18 12:56:58,252] Trial 312 finished with value: 0.949879839545663 and parameters: {'n_estimators': 285, 'learning_rate': 0.04421687685704864, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 248, 'subsample': 0.8188408067206148, 'colsample_bytree': 0.6847065126791309, 'reg_alpha': 6.164898021504885e-05, 'reg_lambda': 1.4258144758578915}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  63%|██████▎   | 314/500 [20:54<19:03,  6.15s/it]

[I 2026-05-18 12:57:09,244] Trial 313 finished with value: 0.9498724315191722 and parameters: {'n_estimators': 283, 'learning_rate': 0.04440516671984265, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 248, 'subsample': 0.8195301139532403, 'colsample_bytree': 0.6792646957068667, 'reg_alpha': 2.7567847124088916e-05, 'reg_lambda': 0.4591846750529622}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  63%|██████▎   | 315/500 [21:02<19:47,  6.42s/it]

[I 2026-05-18 12:57:16,391] Trial 314 finished with value: 0.9498692407330271 and parameters: {'n_estimators': 283, 'learning_rate': 0.044753875142025105, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 249, 'subsample': 0.8205436893162954, 'colsample_bytree': 0.6819810742926687, 'reg_alpha': 6.3365718877257e-05, 'reg_lambda': 1.4190111438509079}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  63%|██████▎   | 316/500 [21:02<14:26,  4.71s/it]

[I 2026-05-18 12:57:16,707] Trial 315 finished with value: 0.9498744706057278 and parameters: {'n_estimators': 285, 'learning_rate': 0.04435887037488838, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 248, 'subsample': 0.8257060688336554, 'colsample_bytree': 0.6761418947838586, 'reg_alpha': 2.9275259353643725e-05, 'reg_lambda': 1.3771418973242622}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  63%|██████▎   | 317/500 [21:04<11:48,  3.87s/it]

[I 2026-05-18 12:57:18,486] Trial 317 finished with value: 0.9498695965125968 and parameters: {'n_estimators': 278, 'learning_rate': 0.04485151512989931, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 257, 'subsample': 0.7676814241499913, 'colsample_bytree': 0.6814065375191386, 'reg_alpha': 2.830471278275858e-05, 'reg_lambda': 0.4665161470479264}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  64%|██████▎   | 318/500 [21:07<11:35,  3.82s/it]

[I 2026-05-18 12:57:22,114] Trial 316 finished with value: 0.9498671113694332 and parameters: {'n_estimators': 279, 'learning_rate': 0.04449016067572311, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 249, 'subsample': 0.7668900910834158, 'colsample_bytree': 0.6817254179002971, 'reg_alpha': 2.769749518220826e-05, 'reg_lambda': 0.4183730941896537}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  64%|██████▍   | 319/500 [21:08<08:35,  2.85s/it]

[I 2026-05-18 12:57:22,686] Trial 318 finished with value: 0.9498794964927629 and parameters: {'n_estimators': 274, 'learning_rate': 0.04478880302057053, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 235, 'subsample': 0.8032474756496053, 'colsample_bytree': 0.6840552378432802, 'reg_alpha': 2.7558378928646788e-05, 'reg_lambda': 0.4284553793631445}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  64%|██████▍   | 320/500 [21:15<12:04,  4.03s/it]

[I 2026-05-18 12:57:29,522] Trial 319 finished with value: 0.9498773829616141 and parameters: {'n_estimators': 277, 'learning_rate': 0.04428953486728603, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 257, 'subsample': 0.7704712462956318, 'colsample_bytree': 0.6753551130503703, 'reg_alpha': 3.2600636618523854e-05, 'reg_lambda': 0.47349641664280123}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  64%|██████▍   | 321/500 [21:19<11:58,  4.01s/it]

[I 2026-05-18 12:57:33,519] Trial 322 finished with value: 0.9498785281605905 and parameters: {'n_estimators': 256, 'learning_rate': 0.04685839476452906, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 235, 'subsample': 0.7741219099866079, 'colsample_bytree': 0.680728839870323, 'reg_alpha': 2.9156745854320434e-05, 'reg_lambda': 1.458953989602178}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  64%|██████▍   | 322/500 [21:19<09:01,  3.04s/it]

[I 2026-05-18 12:57:34,248] Trial 321 finished with value: 0.9498762816885689 and parameters: {'n_estimators': 277, 'learning_rate': 0.046915766503829594, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 233, 'subsample': 0.7895039722854691, 'colsample_bytree': 0.6763768196275177, 'reg_alpha': 6.443782657913749e-05, 'reg_lambda': 1.3322269217682359}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  65%|██████▍   | 323/500 [21:20<06:46,  2.30s/it]

[I 2026-05-18 12:57:34,790] Trial 320 finished with value: 0.949874403834522 and parameters: {'n_estimators': 274, 'learning_rate': 0.04470841205239762, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 235, 'subsample': 0.7684381506424022, 'colsample_bytree': 0.6709501967249878, 'reg_alpha': 2.8081185630648596e-05, 'reg_lambda': 0.4495579287646368}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  65%|██████▍   | 324/500 [21:28<12:08,  4.14s/it]

[I 2026-05-18 12:57:43,234] Trial 323 finished with value: 0.9498770187724634 and parameters: {'n_estimators': 278, 'learning_rate': 0.04701992251528237, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 85, 'subsample': 0.7740797226085132, 'colsample_bytree': 0.6768227443082264, 'reg_alpha': 2.7993311771149947e-05, 'reg_lambda': 1.4940283710822782}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  65%|██████▌   | 325/500 [21:39<17:17,  5.93s/it]

[I 2026-05-18 12:57:53,372] Trial 324 finished with value: 0.9498790549253394 and parameters: {'n_estimators': 278, 'learning_rate': 0.0470183863658295, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 257, 'subsample': 0.7705884675093775, 'colsample_bytree': 0.6738577240962712, 'reg_alpha': 2.8705712018345437e-05, 'reg_lambda': 1.4262144015037246}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  65%|██████▌   | 326/500 [21:47<19:21,  6.68s/it]

[I 2026-05-18 12:58:01,812] Trial 325 finished with value: 0.9498713806629169 and parameters: {'n_estimators': 278, 'learning_rate': 0.047620827871953146, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 200, 'subsample': 0.7708447685538244, 'colsample_bytree': 0.670360940954409, 'reg_alpha': 3.016227532006969e-05, 'reg_lambda': 1.9679106073140604}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  65%|██████▌   | 327/500 [21:49<14:46,  5.12s/it]

[I 2026-05-18 12:58:03,289] Trial 328 finished with value: 0.9498737087985136 and parameters: {'n_estimators': 237, 'learning_rate': 0.04728171315590963, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 83, 'subsample': 0.7710891048110532, 'colsample_bytree': 0.667120843696545, 'reg_alpha': 1.617313195437281e-05, 'reg_lambda': 2.2154289435499397}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  66%|██████▌   | 328/500 [21:49<10:58,  3.83s/it]

[I 2026-05-18 12:58:04,090] Trial 326 finished with value: 0.9498771591171533 and parameters: {'n_estimators': 258, 'learning_rate': 0.0471809044896096, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 234, 'subsample': 0.7731666225788706, 'colsample_bytree': 0.6542479725975064, 'reg_alpha': 2.75199757834986e-05, 'reg_lambda': 2.2603053979494705}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  66%|██████▌   | 329/500 [21:52<10:09,  3.56s/it]

[I 2026-05-18 12:58:07,044] Trial 329 finished with value: 0.9498793304164351 and parameters: {'n_estimators': 237, 'learning_rate': 0.047438278593518915, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 231, 'subsample': 0.8524293103282741, 'colsample_bytree': 0.6537007816937148, 'reg_alpha': 1.6339265217610705e-05, 'reg_lambda': 1.7943186924634524}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  66%|██████▌   | 330/500 [21:56<10:00,  3.53s/it]

[I 2026-05-18 12:58:10,493] Trial 330 finished with value: 0.9498739578110227 and parameters: {'n_estimators': 258, 'learning_rate': 0.0477358367664658, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 221, 'subsample': 0.7753434533252062, 'colsample_bytree': 0.6537805637249249, 'reg_alpha': 1.5837510227124457e-05, 'reg_lambda': 1.7366199162449933}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  66%|██████▌   | 331/500 [21:56<07:22,  2.62s/it]

[I 2026-05-18 12:58:11,005] Trial 327 finished with value: 0.9498755881526103 and parameters: {'n_estimators': 278, 'learning_rate': 0.04753708848898488, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 113, 'subsample': 0.768699718958406, 'colsample_bytree': 0.6729824881526743, 'reg_alpha': 2.8188660763715945e-05, 'reg_lambda': 2.1401689898437595}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  66%|██████▋   | 332/500 [22:01<09:07,  3.26s/it]

[I 2026-05-18 12:58:15,755] Trial 331 finished with value: 0.9498821639730058 and parameters: {'n_estimators': 256, 'learning_rate': 0.04748252579380967, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 233, 'subsample': 0.7878656699822825, 'colsample_bytree': 0.6664987455629323, 'reg_alpha': 1.6385134910975427e-05, 'reg_lambda': 2.010927013217067}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  67%|██████▋   | 333/500 [22:03<08:10,  2.94s/it]

[I 2026-05-18 12:58:17,937] Trial 339 finished with value: 0.9497338523008665 and parameters: {'n_estimators': 63, 'learning_rate': 0.04119953955147723, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 227, 'subsample': 0.8509679914100823, 'colsample_bytree': 0.6038732249159031, 'reg_alpha': 1.587546393391582e-05, 'reg_lambda': 3.4791138482752744}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  67%|██████▋   | 334/500 [22:04<06:00,  2.17s/it]

[I 2026-05-18 12:58:18,333] Trial 333 finished with value: 0.9498792558447953 and parameters: {'n_estimators': 235, 'learning_rate': 0.04743559121431752, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 224, 'subsample': 0.7913584682821575, 'colsample_bytree': 0.6535048658665105, 'reg_alpha': 1.5990464172760193e-05, 'reg_lambda': 2.4490079209860727}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  67%|██████▋   | 335/500 [22:05<05:24,  1.97s/it]

[I 2026-05-18 12:58:19,820] Trial 332 finished with value: 0.9498789363552429 and parameters: {'n_estimators': 238, 'learning_rate': 0.04747860131797231, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 124, 'subsample': 0.7910968852242046, 'colsample_bytree': 0.6685442275139254, 'reg_alpha': 1.548525079892318e-05, 'reg_lambda': 2.1383569426437705}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  67%|██████▋   | 336/500 [22:11<08:40,  3.18s/it]

[I 2026-05-18 12:58:25,812] Trial 334 finished with value: 0.9498666459353193 and parameters: {'n_estimators': 266, 'learning_rate': 0.04762647833484645, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 202, 'subsample': 0.8523584514619286, 'colsample_bytree': 0.6554145965230962, 'reg_alpha': 1.5869086315491003e-05, 'reg_lambda': 75.41818769368787}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  67%|██████▋   | 337/500 [22:13<07:23,  2.72s/it]

[I 2026-05-18 12:58:27,462] Trial 335 finished with value: 0.9498698557681051 and parameters: {'n_estimators': 238, 'learning_rate': 0.04160864947367779, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 113, 'subsample': 0.804253337109921, 'colsample_bytree': 0.6022443372522134, 'reg_alpha': 1.6312161786345143e-05, 'reg_lambda': 2.1757864094882238}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  68%|██████▊   | 338/500 [22:28<17:22,  6.44s/it]

[I 2026-05-18 12:58:42,572] Trial 336 finished with value: 0.9498758577918689 and parameters: {'n_estimators': 237, 'learning_rate': 0.04066682551280124, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 266, 'subsample': 0.8022361495536239, 'colsample_bytree': 0.6525272324737641, 'reg_alpha': 1.694895401791813e-05, 'reg_lambda': 2.1819734016609837}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  68%|██████▊   | 339/500 [22:35<17:36,  6.56s/it]

[I 2026-05-18 12:58:49,397] Trial 337 finished with value: 0.949874643519518 and parameters: {'n_estimators': 237, 'learning_rate': 0.04165807651024978, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 266, 'subsample': 0.8012800403029349, 'colsample_bytree': 0.6515551583297129, 'reg_alpha': 1.590261713114762e-05, 'reg_lambda': 2.17545301556298}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  68%|██████▊   | 340/500 [22:40<16:33,  6.21s/it]

[I 2026-05-18 12:58:54,811] Trial 340 finished with value: 0.9498669953883262 and parameters: {'n_estimators': 268, 'learning_rate': 0.04147050925294542, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 266, 'subsample': 0.7927831904704453, 'colsample_bytree': 0.6231061696780097, 'reg_alpha': 1.4781571365120228e-05, 'reg_lambda': 4.225477128459592}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  68%|██████▊   | 341/500 [22:42<12:50,  4.85s/it]

[I 2026-05-18 12:58:56,480] Trial 338 finished with value: 0.9498763159742186 and parameters: {'n_estimators': 266, 'learning_rate': 0.04132853750591043, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 264, 'subsample': 0.853350711344062, 'colsample_bytree': 0.6542467581033362, 'reg_alpha': 1.587299071834161e-05, 'reg_lambda': 4.399724133683598}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  68%|██████▊   | 342/500 [22:49<14:21,  5.45s/it]

[I 2026-05-18 12:59:03,349] Trial 341 finished with value: 0.9498792482545271 and parameters: {'n_estimators': 267, 'learning_rate': 0.041600726395030034, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 264, 'subsample': 0.7922893061043229, 'colsample_bytree': 0.641775447389608, 'reg_alpha': 1.622541459213473e-05, 'reg_lambda': 3.589647751075022}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  69%|██████▊   | 343/500 [22:49<10:40,  4.08s/it]

[I 2026-05-18 12:59:04,209] Trial 342 finished with value: 0.9498802611774515 and parameters: {'n_estimators': 264, 'learning_rate': 0.04058487295541035, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 266, 'subsample': 0.7891506132912836, 'colsample_bytree': 0.6041571493835303, 'reg_alpha': 1.557695593886654e-05, 'reg_lambda': 4.782265461295264}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  69%|██████▉   | 345/500 [22:51<05:59,  2.32s/it]

[I 2026-05-18 12:59:05,531] Trial 343 finished with value: 0.9498778006770939 and parameters: {'n_estimators': 252, 'learning_rate': 0.04122984793898721, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 259, 'subsample': 0.7921343045047802, 'colsample_bytree': 0.6432751002668844, 'reg_alpha': 1.5001425307768173e-05, 'reg_lambda': 4.213110413528824}. Best is trial 222 with value: 0.9498855935228651.
[I 2026-05-18 12:59:05,689] Trial 344 finished with value: 0.9498744373256741 and parameters: {'n_estimators': 251, 'learning_rate': 0.04111098274244106, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 265, 'subsample': 0.7916021779764371, 'colsample_bytree': 0.6416924277953663, 'reg_alpha': 1.3837174498864814e-05, 'reg_lambda': 4.971435889321336}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  69%|██████▉   | 346/500 [22:52<04:43,  1.84s/it]

[I 2026-05-18 12:59:06,399] Trial 345 finished with value: 0.9498718146826878 and parameters: {'n_estimators': 252, 'learning_rate': 0.04166954536291097, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 266, 'subsample': 0.801441381951937, 'colsample_bytree': 0.6403628620286872, 'reg_alpha': 1.0026034789644419e-05, 'reg_lambda': 4.330937636258697}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  69%|██████▉   | 347/500 [22:52<03:55,  1.54s/it]

[I 2026-05-18 12:59:07,246] Trial 346 finished with value: 0.9498724386349379 and parameters: {'n_estimators': 251, 'learning_rate': 0.04113535215830678, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 266, 'subsample': 0.8052180550357716, 'colsample_bytree': 0.624389718757527, 'reg_alpha': 1.3203539127494318e-05, 'reg_lambda': 4.379615909770575}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  70%|██████▉   | 348/500 [22:58<06:57,  2.74s/it]

[I 2026-05-18 12:59:12,792] Trial 347 finished with value: 0.9498652688752058 and parameters: {'n_estimators': 251, 'learning_rate': 0.04165414882973666, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 262, 'subsample': 0.8045056658935488, 'colsample_bytree': 0.6248344005302213, 'reg_alpha': 1.0091506410199303e-05, 'reg_lambda': 4.3991531472834575}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  70%|██████▉   | 349/500 [23:00<06:31,  2.59s/it]

[I 2026-05-18 12:59:15,028] Trial 348 finished with value: 0.9498701710155549 and parameters: {'n_estimators': 252, 'learning_rate': 0.04165963065009169, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 265, 'subsample': 0.8035050126592866, 'colsample_bytree': 0.6425076196183894, 'reg_alpha': 2.1176380250232548e-05, 'reg_lambda': 5.28694607779749}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  70%|███████   | 350/500 [23:12<13:25,  5.37s/it]

[I 2026-05-18 12:59:26,905] Trial 349 finished with value: 0.9498784743903878 and parameters: {'n_estimators': 256, 'learning_rate': 0.04232527642909627, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 264, 'subsample': 0.7946594069362123, 'colsample_bytree': 0.6428125592576581, 'reg_alpha': 1.0317090729089077e-05, 'reg_lambda': 4.442823450441974}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  70%|███████   | 351/500 [23:26<19:22,  7.80s/it]

[I 2026-05-18 12:59:40,362] Trial 350 finished with value: 0.949873102045013 and parameters: {'n_estimators': 251, 'learning_rate': 0.042373035019943675, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 258, 'subsample': 0.8687504100306878, 'colsample_bytree': 0.64226666282477, 'reg_alpha': 1.0844905193300376e-05, 'reg_lambda': 4.074443294558854}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  70%|███████   | 352/500 [23:31<17:10,  6.96s/it]

[I 2026-05-18 12:59:45,375] Trial 352 finished with value: 0.9498739075761897 and parameters: {'n_estimators': 252, 'learning_rate': 0.04267072495050534, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 255, 'subsample': 0.7847221427628904, 'colsample_bytree': 0.6408038062996138, 'reg_alpha': 6.579392345780976e-05, 'reg_lambda': 3.3601624461676693}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  71%|███████   | 353/500 [23:33<13:58,  5.70s/it]

[I 2026-05-18 12:59:48,140] Trial 351 finished with value: 0.9498616484346349 and parameters: {'n_estimators': 249, 'learning_rate': 0.03773452932020174, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 256, 'subsample': 0.783544836989414, 'colsample_bytree': 0.6413805385943848, 'reg_alpha': 6.184781389507249e-05, 'reg_lambda': 4.288462414342912}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  71%|███████   | 354/500 [23:40<14:34,  5.99s/it]

[I 2026-05-18 12:59:54,803] Trial 354 finished with value: 0.9498727268194737 and parameters: {'n_estimators': 258, 'learning_rate': 0.0387331619098169, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 257, 'subsample': 0.7842145084786311, 'colsample_bytree': 0.6249735769445222, 'reg_alpha': 1.05628380599622e-05, 'reg_lambda': 5.863362403517888}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  71%|███████   | 355/500 [23:42<11:44,  4.86s/it]

[I 2026-05-18 12:59:57,013] Trial 355 finished with value: 0.9498688397637555 and parameters: {'n_estimators': 258, 'learning_rate': 0.038860244151123303, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 256, 'subsample': 0.8681787240987878, 'colsample_bytree': 0.6107950623181183, 'reg_alpha': 1.0326767982605441e-05, 'reg_lambda': 5.676763737937563}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  71%|███████   | 356/500 [23:43<08:24,  3.50s/it]

[I 2026-05-18 12:59:57,358] Trial 356 finished with value: 0.9498680863763077 and parameters: {'n_estimators': 257, 'learning_rate': 0.037781518838929405, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 146, 'subsample': 0.7838166838702392, 'colsample_bytree': 0.6008219278337396, 'reg_alpha': 1.1637283947545922e-05, 'reg_lambda': 6.247029394171581}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  71%|███████▏  | 357/500 [23:44<07:09,  3.00s/it]

[I 2026-05-18 12:59:59,200] Trial 353 finished with value: 0.949589225082183 and parameters: {'n_estimators': 250, 'learning_rate': 0.007019131412973299, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 256, 'subsample': 0.7839324430071788, 'colsample_bytree': 0.641363530039382, 'reg_alpha': 1.0250473581518614e-05, 'reg_lambda': 5.160023603345904}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  72%|███████▏  | 358/500 [23:45<05:15,  2.22s/it]

[I 2026-05-18 12:59:59,606] Trial 357 finished with value: 0.9498697940088011 and parameters: {'n_estimators': 257, 'learning_rate': 0.03741388766249147, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 255, 'subsample': 0.78393192391139, 'colsample_bytree': 0.6013942490426205, 'reg_alpha': 6.080897426516399e-05, 'reg_lambda': 0.15171873522604654}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  72%|███████▏  | 359/500 [23:47<05:05,  2.17s/it]

[I 2026-05-18 13:00:01,635] Trial 358 finished with value: 0.9498651028720418 and parameters: {'n_estimators': 257, 'learning_rate': 0.0373074938114238, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 257, 'subsample': 0.7834517909097088, 'colsample_bytree': 0.6135639822882099, 'reg_alpha': 2.0720363870914117e-05, 'reg_lambda': 0.16212163447917427}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  72%|███████▏  | 360/500 [23:50<05:44,  2.46s/it]

[I 2026-05-18 13:00:04,774] Trial 359 finished with value: 0.9498617243271369 and parameters: {'n_estimators': 257, 'learning_rate': 0.03843423550913681, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 254, 'subsample': 0.7877444327546841, 'colsample_bytree': 0.7030339347566337, 'reg_alpha': 2.1061698683968036e-05, 'reg_lambda': 7.076318102338565}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  72%|███████▏  | 361/500 [23:54<06:30,  2.81s/it]

[I 2026-05-18 13:00:08,405] Trial 360 finished with value: 0.9498651929514796 and parameters: {'n_estimators': 263, 'learning_rate': 0.03851977338128511, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 256, 'subsample': 0.7838882647632869, 'colsample_bytree': 0.6143053795929871, 'reg_alpha': 1.0000362912449315e-05, 'reg_lambda': 0.16223319159415456}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  72%|███████▏  | 362/500 [24:06<13:09,  5.72s/it]

[I 2026-05-18 13:00:20,908] Trial 361 finished with value: 0.9498672125709815 and parameters: {'n_estimators': 258, 'learning_rate': 0.03895817368736413, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 254, 'subsample': 0.781845333175287, 'colsample_bytree': 0.6108790999658199, 'reg_alpha': 2.102659291868265e-05, 'reg_lambda': 3.0720542137573497}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  73%|███████▎  | 363/500 [24:19<18:13,  7.99s/it]

[I 2026-05-18 13:00:34,191] Trial 362 finished with value: 0.949869425944794 and parameters: {'n_estimators': 263, 'learning_rate': 0.03758381063420946, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 255, 'subsample': 0.7879435831318707, 'colsample_bytree': 0.7203451772532522, 'reg_alpha': 0.3383487425791731, 'reg_lambda': 14.607289992453119}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  73%|███████▎  | 364/500 [24:27<17:44,  7.83s/it]

[I 2026-05-18 13:00:41,657] Trial 363 finished with value: 0.949740609102952 and parameters: {'n_estimators': 258, 'learning_rate': 0.012070839502844823, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 253, 'subsample': 0.782405255692745, 'colsample_bytree': 0.6085033649076633, 'reg_alpha': 2.4649226708694295e-05, 'reg_lambda': 12.200082470864134}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  73%|███████▎  | 365/500 [24:28<13:01,  5.79s/it]

[I 2026-05-18 13:00:42,686] Trial 364 finished with value: 0.9497393053725658 and parameters: {'n_estimators': 263, 'learning_rate': 0.011223230948081113, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 255, 'subsample': 0.7897830046477169, 'colsample_bytree': 0.6644118917410844, 'reg_alpha': 2.1769980862648405e-05, 'reg_lambda': 12.281638580671205}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  73%|███████▎  | 366/500 [24:33<12:41,  5.69s/it]

[I 2026-05-18 13:00:48,114] Trial 365 finished with value: 0.9498675168557401 and parameters: {'n_estimators': 261, 'learning_rate': 0.037028816428697146, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 252, 'subsample': 0.6681941107731911, 'colsample_bytree': 0.6001212366896597, 'reg_alpha': 2.189710515249475e-05, 'reg_lambda': 12.959775571092466}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  73%|███████▎  | 367/500 [24:34<09:24,  4.24s/it]

[I 2026-05-18 13:00:48,995] Trial 368 finished with value: 0.9498795774360582 and parameters: {'n_estimators': 262, 'learning_rate': 0.049357011337780414, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 252, 'subsample': 0.6728009136040282, 'colsample_bytree': 0.7180416308370898, 'reg_alpha': 4.148067958382171e-05, 'reg_lambda': 12.818671420595155}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  74%|███████▎  | 368/500 [24:35<06:48,  3.10s/it]

[I 2026-05-18 13:00:49,439] Trial 369 finished with value: 0.9498785890577194 and parameters: {'n_estimators': 263, 'learning_rate': 0.04546988069748761, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 238, 'subsample': 0.8300966968558207, 'colsample_bytree': 0.6637663670165657, 'reg_alpha': 2.1545465989424573e-05, 'reg_lambda': 1.1220611303824424}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  74%|███████▍  | 369/500 [24:39<07:14,  3.32s/it]

[I 2026-05-18 13:00:53,276] Trial 367 finished with value: 0.9496750551260338 and parameters: {'n_estimators': 263, 'learning_rate': 0.0069248002678302355, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 251, 'subsample': 0.7799608862147608, 'colsample_bytree': 0.6637525450620075, 'reg_alpha': 1.9766401996792286e-05, 'reg_lambda': 1.0838294161731425}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  74%|███████▍  | 370/500 [24:39<05:36,  2.59s/it]

[I 2026-05-18 13:00:54,139] Trial 370 finished with value: 0.9498749922165963 and parameters: {'n_estimators': 263, 'learning_rate': 0.04539840258134456, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 237, 'subsample': 0.7980367596301509, 'colsample_bytree': 0.720618809870762, 'reg_alpha': 2.258418993906735e-05, 'reg_lambda': 0.21029880783052818}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  74%|███████▍  | 371/500 [24:40<04:17,  1.99s/it]

[I 2026-05-18 13:00:54,753] Trial 366 finished with value: 0.9497502694100012 and parameters: {'n_estimators': 270, 'learning_rate': 0.01064098348333423, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 251, 'subsample': 0.6714429899466744, 'colsample_bytree': 0.7222378178699259, 'reg_alpha': 2.1038605722336263e-05, 'reg_lambda': 0.19832469180809745}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  74%|███████▍  | 372/500 [24:41<03:32,  1.66s/it]

[I 2026-05-18 13:00:55,645] Trial 374 finished with value: 0.949770667123154 and parameters: {'n_estimators': 146, 'learning_rate': 0.04977116889150688, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 239, 'subsample': 0.8292514965673403, 'colsample_bytree': 0.7250068794544313, 'reg_alpha': 0.00012363243501438938, 'reg_lambda': 1.2721982323104004}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  75%|███████▍  | 373/500 [24:46<05:24,  2.55s/it]

[I 2026-05-18 13:01:00,275] Trial 372 finished with value: 0.9498663772459979 and parameters: {'n_estimators': 264, 'learning_rate': 0.04954951669618174, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 239, 'subsample': 0.8284943833899688, 'colsample_bytree': 0.6635760968524445, 'reg_alpha': 4.140332422958839e-05, 'reg_lambda': 1.2199159026331783}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  75%|███████▍  | 374/500 [24:48<05:04,  2.41s/it]

[I 2026-05-18 13:01:02,363] Trial 371 finished with value: 0.9498685285855892 and parameters: {'n_estimators': 300, 'learning_rate': 0.045424487622824083, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 238, 'subsample': 0.7975710632706889, 'colsample_bytree': 0.7196625981977576, 'reg_alpha': 4.03139976388442e-05, 'reg_lambda': 1.0681411925584239}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  75%|███████▌  | 375/500 [25:04<13:52,  6.66s/it]

[I 2026-05-18 13:01:18,920] Trial 376 finished with value: 0.94983644925655 and parameters: {'n_estimators': 270, 'learning_rate': 0.04954871946128632, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 238, 'subsample': 0.8256514830299849, 'colsample_bytree': 0.6655106273638443, 'reg_alpha': 3.9937855050921947e-05, 'reg_lambda': 1.0612893297188495}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  75%|███████▌  | 376/500 [25:06<10:38,  5.15s/it]

[I 2026-05-18 13:01:20,555] Trial 373 finished with value: 0.949768355881028 and parameters: {'n_estimators': 270, 'learning_rate': 0.011567470692640776, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 236, 'subsample': 0.8264101634799113, 'colsample_bytree': 0.7214057128303267, 'reg_alpha': 4.41782348065603e-05, 'reg_lambda': 0.6859171839080733}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  75%|███████▌  | 377/500 [25:14<12:41,  6.19s/it]

[I 2026-05-18 13:01:29,159] Trial 375 finished with value: 0.9498643640486778 and parameters: {'n_estimators': 300, 'learning_rate': 0.049901937874034755, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 239, 'subsample': 0.6669202470115475, 'colsample_bytree': 0.6664192441039721, 'reg_alpha': 4.096348383222601e-05, 'reg_lambda': 1.225104685211488}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  76%|███████▌  | 378/500 [25:19<11:41,  5.75s/it]

[I 2026-05-18 13:01:33,902] Trial 379 finished with value: 0.949864448284808 and parameters: {'n_estimators': 270, 'learning_rate': 0.04935301358608221, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 236, 'subsample': 0.8156943351344819, 'colsample_bytree': 0.6992665704925186, 'reg_alpha': 3.53186415393365e-05, 'reg_lambda': 1.1837811738008899}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  76%|███████▌  | 379/500 [25:20<08:38,  4.29s/it]

[I 2026-05-18 13:01:34,773] Trial 380 finished with value: 0.9498655902705858 and parameters: {'n_estimators': 272, 'learning_rate': 0.04986240515002013, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 239, 'subsample': 0.8141952630265288, 'colsample_bytree': 0.7372566021661959, 'reg_alpha': 0.00011677873301017948, 'reg_lambda': 0.6588206549377622}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  76%|███████▌  | 380/500 [25:29<11:17,  5.65s/it]

[I 2026-05-18 13:01:43,593] Trial 377 finished with value: 0.9498813599717195 and parameters: {'n_estimators': 270, 'learning_rate': 0.04511025294133248, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 237, 'subsample': 0.6980293508163375, 'colsample_bytree': 0.6640546875797141, 'reg_alpha': 0.0001263589100053084, 'reg_lambda': 1.1582429718468439}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  76%|███████▌  | 381/500 [25:30<08:36,  4.34s/it]

[I 2026-05-18 13:01:44,889] Trial 383 finished with value: 0.94986509224665 and parameters: {'n_estimators': 297, 'learning_rate': 0.04994904124398635, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 247, 'subsample': 0.6988994440893274, 'colsample_bytree': 0.702842103445292, 'reg_alpha': 4.4862048825452076e-05, 'reg_lambda': 0.6208374692411562}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  76%|███████▋  | 382/500 [25:31<06:13,  3.17s/it]

[I 2026-05-18 13:01:45,314] Trial 381 finished with value: 0.9498752873857091 and parameters: {'n_estimators': 272, 'learning_rate': 0.049258067872964224, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 239, 'subsample': 0.8135718012560984, 'colsample_bytree': 0.7366589400445109, 'reg_alpha': 0.00012228394374285247, 'reg_lambda': 0.6722711563848133}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  77%|███████▋  | 383/500 [25:33<05:59,  3.07s/it]

[I 2026-05-18 13:01:48,138] Trial 378 finished with value: 0.9498664155514895 and parameters: {'n_estimators': 298, 'learning_rate': 0.04953667484670833, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 236, 'subsample': 0.8266577260359673, 'colsample_bytree': 0.6633036598704372, 'reg_alpha': 0.00011161458445665188, 'reg_lambda': 1.1471608847181733}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  77%|███████▋  | 384/500 [25:35<05:04,  2.62s/it]

[I 2026-05-18 13:01:49,712] Trial 382 finished with value: 0.9498838218609265 and parameters: {'n_estimators': 273, 'learning_rate': 0.04935796492918762, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 239, 'subsample': 0.824974993908752, 'colsample_bytree': 0.7029684452828973, 'reg_alpha': 0.00011972977512098882, 'reg_lambda': 1.1593927491550382}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  77%|███████▋  | 385/500 [25:38<05:28,  2.86s/it]

[I 2026-05-18 13:01:53,107] Trial 384 finished with value: 0.949868800000418 and parameters: {'n_estimators': 271, 'learning_rate': 0.049978654671548974, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 247, 'subsample': 0.6976510260874559, 'colsample_bytree': 0.7043025149789115, 'reg_alpha': 4.053043848410038e-05, 'reg_lambda': 0.6368121639562137}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  77%|███████▋  | 386/500 [25:43<06:29,  3.41s/it]

[I 2026-05-18 13:01:57,846] Trial 385 finished with value: 0.9498771361143827 and parameters: {'n_estimators': 289, 'learning_rate': 0.04362736241078312, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 228, 'subsample': 0.8135304945318568, 'colsample_bytree': 0.7355837454156064, 'reg_alpha': 4.77349862674642e-05, 'reg_lambda': 0.6198829210782889}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  77%|███████▋  | 387/500 [25:47<06:26,  3.42s/it]

[I 2026-05-18 13:02:01,301] Trial 387 finished with value: 0.9498490592732475 and parameters: {'n_estimators': 244, 'learning_rate': 0.043283096012277006, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 230, 'subsample': 0.8143177518011212, 'colsample_bytree': 0.6998714297682491, 'reg_alpha': 1.3055430507522758e-05, 'reg_lambda': 2.874911848210445}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  78%|███████▊  | 388/500 [25:49<05:48,  3.11s/it]

[I 2026-05-18 13:02:03,687] Trial 386 finished with value: 0.949864400435834 and parameters: {'n_estimators': 287, 'learning_rate': 0.04388490378786915, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 248, 'subsample': 0.8141653558864058, 'colsample_bytree': 0.7022555122606607, 'reg_alpha': 4.789741067781316e-05, 'reg_lambda': 2.7804878039094807}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  78%|███████▊  | 389/500 [26:06<13:16,  7.18s/it]

[I 2026-05-18 13:02:20,329] Trial 388 finished with value: 0.9498784789937256 and parameters: {'n_estimators': 273, 'learning_rate': 0.04424117817121041, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 216, 'subsample': 0.6987739859431936, 'colsample_bytree': 0.6270220348420283, 'reg_alpha': 1.3444257941860715e-05, 'reg_lambda': 2.653190240655091}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  78%|███████▊  | 390/500 [26:14<13:54,  7.59s/it]

[I 2026-05-18 13:02:28,884] Trial 389 finished with value: 0.9498730548867712 and parameters: {'n_estimators': 288, 'learning_rate': 0.043674288458297586, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 228, 'subsample': 0.8074178680934173, 'colsample_bytree': 0.6208685514616155, 'reg_alpha': 0.12916389058698463, 'reg_lambda': 8.96962098344074}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  78%|███████▊  | 391/500 [26:16<10:56,  6.02s/it]

[I 2026-05-18 13:02:31,248] Trial 390 finished with value: 0.9498765065199992 and parameters: {'n_estimators': 289, 'learning_rate': 0.043900949398752775, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 248, 'subsample': 0.8038208861721486, 'colsample_bytree': 0.629019586550604, 'reg_alpha': 1.3967351534521687e-05, 'reg_lambda': 2.50307634692923}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  78%|███████▊  | 392/500 [26:22<10:19,  5.74s/it]

[I 2026-05-18 13:02:36,326] Trial 393 finished with value: 0.949871383429382 and parameters: {'n_estimators': 290, 'learning_rate': 0.044296950073805026, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 224, 'subsample': 0.7469279266873542, 'colsample_bytree': 0.6871390084692771, 'reg_alpha': 0.0001795075405255629, 'reg_lambda': 0.33475548692377405}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  79%|███████▊  | 393/500 [26:23<08:05,  4.54s/it]

[I 2026-05-18 13:02:38,057] Trial 391 finished with value: 0.9498799326447067 and parameters: {'n_estimators': 275, 'learning_rate': 0.04359848487326928, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 228, 'subsample': 0.7464318346956447, 'colsample_bytree': 0.7026635512341125, 'reg_alpha': 7.35516238173288e-05, 'reg_lambda': 2.6953710192639115}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  79%|███████▉  | 394/500 [26:26<06:50,  3.87s/it]

[I 2026-05-18 13:02:40,367] Trial 392 finished with value: 0.94987899376525 and parameters: {'n_estimators': 288, 'learning_rate': 0.043883085568795485, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 229, 'subsample': 0.6395798801447079, 'colsample_bytree': 0.68750062772001, 'reg_alpha': 0.00014814391508289164, 'reg_lambda': 20.955358517855103}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  79%|███████▉  | 395/500 [26:30<07:06,  4.06s/it]

[I 2026-05-18 13:02:44,884] Trial 394 finished with value: 0.9498776641302944 and parameters: {'n_estimators': 289, 'learning_rate': 0.04342509566939496, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 231, 'subsample': 0.8054821682429661, 'colsample_bytree': 0.687224642786414, 'reg_alpha': 0.00017377927579084176, 'reg_lambda': 2.774575286222797}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  79%|███████▉  | 397/500 [26:34<04:53,  2.85s/it]

[I 2026-05-18 13:02:48,807] Trial 396 finished with value: 0.9498754725934656 and parameters: {'n_estimators': 291, 'learning_rate': 0.04347957588230561, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 232, 'subsample': 0.8053183264428648, 'colsample_bytree': 0.687490015945556, 'reg_alpha': 7.069246831555213e-05, 'reg_lambda': 2.868114991457923}. Best is trial 222 with value: 0.9498855935228651.
[I 2026-05-18 13:02:48,913] Trial 395 finished with value: 0.9498830940379384 and parameters: {'n_estimators': 275, 'learning_rate': 0.04369536351227716, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 232, 'subsample': 0.6455980628393548, 'colsample_bytree': 0.702023970437087, 'reg_alpha': 7.284603941670293e-05, 'reg_lambda': 1.5338849519857398}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  80%|███████▉  | 398/500 [26:36<04:18,  2.53s/it]

[I 2026-05-18 13:02:50,732] Trial 401 finished with value: 0.9498156249811307 and parameters: {'n_estimators': 92, 'learning_rate': 0.04678658681441771, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 219, 'subsample': 0.8414066665755237, 'colsample_bytree': 0.6893703202124404, 'reg_alpha': 7.92850019596232e-05, 'reg_lambda': 1.5497593240867709}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  80%|███████▉  | 399/500 [26:41<05:18,  3.15s/it]

[I 2026-05-18 13:02:55,315] Trial 399 finished with value: 0.9498771122247082 and parameters: {'n_estimators': 276, 'learning_rate': 0.045913584050585356, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 215, 'subsample': 0.8038212925185784, 'colsample_bytree': 0.6291125079287972, 'reg_alpha': 7.631000234664408e-05, 'reg_lambda': 2.7757534186384736}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  80%|████████  | 400/500 [26:42<04:33,  2.74s/it]

[I 2026-05-18 13:02:57,074] Trial 397 finished with value: 0.9498729617133277 and parameters: {'n_estimators': 288, 'learning_rate': 0.04558410408241159, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 284, 'subsample': 0.6448226934631991, 'colsample_bytree': 0.6196279347564674, 'reg_alpha': 0.0001747502043395896, 'reg_lambda': 2.904654616228989}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  80%|████████  | 401/500 [26:43<03:43,  2.26s/it]

[I 2026-05-18 13:02:58,239] Trial 403 finished with value: 0.9497974811585891 and parameters: {'n_estimators': 93, 'learning_rate': 0.04647263650489066, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 220, 'subsample': 0.6416704485385804, 'colsample_bytree': 0.6862559421580192, 'reg_alpha': 7.464966238287032e-05, 'reg_lambda': 24.491725369864305}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  80%|████████  | 402/500 [26:45<03:10,  1.95s/it]

[I 2026-05-18 13:02:59,438] Trial 398 finished with value: 0.9498749188646366 and parameters: {'n_estimators': 288, 'learning_rate': 0.04589207963206725, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 214, 'subsample': 0.6428231527094808, 'colsample_bytree': 0.8936337160994726, 'reg_alpha': 0.00016073583905396778, 'reg_lambda': 24.343837284071117}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  81%|████████  | 403/500 [26:55<07:04,  4.38s/it]

[I 2026-05-18 13:03:09,490] Trial 406 finished with value: 0.9498169823472802 and parameters: {'n_estimators': 92, 'learning_rate': 0.0464875268596802, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 283, 'subsample': 0.8411116542453213, 'colsample_bytree': 0.6789776875735744, 'reg_alpha': 0.00010057669391087503, 'reg_lambda': 1.6496803041097292}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 222. Best value: 0.949886:  81%|████████  | 404/500 [27:00<07:24,  4.63s/it]

[I 2026-05-18 13:03:14,730] Trial 400 finished with value: 0.9498795852415313 and parameters: {'n_estimators': 278, 'learning_rate': 0.045691693634670204, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 222, 'subsample': 0.7434653046785488, 'colsample_bytree': 0.6866135007641007, 'reg_alpha': 0.00018920589383402604, 'reg_lambda': 1.676415486550546}. Best is trial 222 with value: 0.9498855935228651.

Best trial: 402. Best value: 0.949886:  81%|████████  | 405/500 [27:13<11:05,  7.00s/it]

[I 2026-05-18 13:03:27,250] Trial 402 finished with value: 0.9498857992045373 and parameters: {'n_estimators': 279, 'learning_rate': 0.0460336674084307, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 231, 'subsample': 0.6443523206683296, 'colsample_bytree': 0.6862178024026039, 'reg_alpha': 8.19860610452054e-05, 'reg_lambda': 1.6658799864296214}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  81%|████████  | 406/500 [27:17<09:55,  6.33s/it]

[I 2026-05-18 13:03:32,038] Trial 405 finished with value: 0.9498771892357961 and parameters: {'n_estimators': 278, 'learning_rate': 0.04680321085019147, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 282, 'subsample': 0.641345316095021, 'colsample_bytree': 0.6863916373937928, 'reg_alpha': 9.972792144501644e-05, 'reg_lambda': 1.7390823673870137}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  81%|████████▏ | 407/500 [27:18<07:02,  4.55s/it]

[I 2026-05-18 13:03:32,407] Trial 404 finished with value: 0.9498801878437545 and parameters: {'n_estimators': 278, 'learning_rate': 0.04622566840163446, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 219, 'subsample': 0.8351602921525336, 'colsample_bytree': 0.6893259542444333, 'reg_alpha': 7.459700891189256e-05, 'reg_lambda': 1.70057328131434}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  82%|████████▏ | 408/500 [27:28<09:50,  6.41s/it]

[I 2026-05-18 13:03:43,170] Trial 407 finished with value: 0.9498768550921841 and parameters: {'n_estimators': 276, 'learning_rate': 0.04658518914139934, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 286, 'subsample': 0.8443716674892283, 'colsample_bytree': 0.6769407048771438, 'reg_alpha': 0.00010472213269018266, 'reg_lambda': 1.7893424119082406}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  82%|████████▏ | 409/500 [27:29<07:09,  4.72s/it]

[I 2026-05-18 13:03:43,948] Trial 409 finished with value: 0.9498840326488601 and parameters: {'n_estimators': 275, 'learning_rate': 0.04624895061059565, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 282, 'subsample': 0.7173960147422241, 'colsample_bytree': 0.617766291533527, 'reg_alpha': 9.269603135379117e-05, 'reg_lambda': 1.7868188299804275}. Best is trial 402 with value: 0.9498857992045373.
[I 2026-05-18 13:03:44,001] Trial 408 finished with value: 0.94987727883622 and parameters: {'n_estimators': 278, 'learning_rate': 0.046749181827097176, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 222, 'subsample': 0.6514349291163823, 'colsample_bytree': 0.7114467524656563, 'reg_alpha': 7.965849636174068e-05, 'reg_lambda': 1.4902732211828376}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  82%|████████▏ | 411/500 [27:30<03:53,  2.62s/it]

[I 2026-05-18 13:03:44,298] Trial 412 finished with value: 0.949327058377771 and parameters: {'n_estimators': 218, 'learning_rate': 0.003261025506015791, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 261, 'subsample': 0.6554107969618759, 'colsample_bytree': 0.7098344419656468, 'reg_alpha': 0.00010636903250746945, 'reg_lambda': 1.7527035211733004}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  82%|████████▏ | 412/500 [27:37<05:34,  3.80s/it]

[I 2026-05-18 13:03:51,673] Trial 410 finished with value: 0.9498787938237185 and parameters: {'n_estimators': 279, 'learning_rate': 0.04683149842213149, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 270, 'subsample': 0.651078518854902, 'colsample_bytree': 0.6169263271949584, 'reg_alpha': 0.00010603456744196875, 'reg_lambda': 8.247332040283892}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  83%|████████▎ | 413/500 [27:43<06:13,  4.30s/it]

[I 2026-05-18 13:03:57,380] Trial 411 finished with value: 0.9498412878140974 and parameters: {'n_estimators': 277, 'learning_rate': 0.02237377205765311, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 270, 'subsample': 0.6572395304724389, 'colsample_bytree': 0.7148911108343996, 'reg_alpha': 0.0001129463304790141, 'reg_lambda': 1.7897721339182358}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  83%|████████▎ | 414/500 [27:44<05:05,  3.55s/it]

[I 2026-05-18 13:03:58,899] Trial 413 finished with value: 0.9498402650724268 and parameters: {'n_estimators': 278, 'learning_rate': 0.022416101296966685, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 284, 'subsample': 0.8004780008289574, 'colsample_bytree': 0.67347944716408, 'reg_alpha': 6.446295102536068e-05, 'reg_lambda': 1.896443199293273}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  83%|████████▎ | 415/500 [27:55<07:57,  5.62s/it]

[I 2026-05-18 13:04:09,877] Trial 414 finished with value: 0.9494388871691306 and parameters: {'n_estimators': 278, 'learning_rate': 0.003246360259752248, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 259, 'subsample': 0.7143733095811351, 'colsample_bytree': 0.7083700877303662, 'reg_alpha': 9.481882733187094e-05, 'reg_lambda': 1.789133966510895}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  83%|████████▎ | 416/500 [27:58<06:58,  4.98s/it]

[I 2026-05-18 13:04:13,221] Trial 415 finished with value: 0.9498130706143545 and parameters: {'n_estimators': 268, 'learning_rate': 0.01753067923695553, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 260, 'subsample': 0.6520757142472646, 'colsample_bytree': 0.7098903702179951, 'reg_alpha': 0.00010707342387781177, 'reg_lambda': 8.092578063850722}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  83%|████████▎ | 417/500 [28:00<05:41,  4.12s/it]

[I 2026-05-18 13:04:15,255] Trial 419 pruned.

Best trial: 402. Best value: 0.949886:  84%|████████▎ | 418/500 [28:11<08:01,  5.87s/it]

[I 2026-05-18 13:04:25,348] Trial 416 finished with value: 0.9498711870009148 and parameters: {'n_estimators': 280, 'learning_rate': 0.047275554241444195, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 42, 'subsample': 0.7222742216037201, 'colsample_bytree': 0.7090402316096276, 'reg_alpha': 8.997692355587938e-05, 'reg_lambda': 1.6596642176933483}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  84%|████████▍ | 419/500 [28:14<06:58,  5.16s/it]

[I 2026-05-18 13:04:28,821] Trial 418 finished with value: 0.9498756395222774 and parameters: {'n_estimators': 280, 'learning_rate': 0.04684512876475862, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 226, 'subsample': 0.6539339774137979, 'colsample_bytree': 0.7128207969263938, 'reg_alpha': 5.061498166417201e-05, 'reg_lambda': 0.9715528845157363}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  84%|████████▍ | 420/500 [28:18<06:22,  4.78s/it]

[I 2026-05-18 13:04:32,713] Trial 417 finished with value: 0.9494541157894298 and parameters: {'n_estimators': 281, 'learning_rate': 0.003466560990907743, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 210, 'subsample': 0.65471113698321, 'colsample_bytree': 0.6758113597492832, 'reg_alpha': 0.00011496326916089162, 'reg_lambda': 0.9504302629442692}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  84%|████████▍ | 421/500 [28:23<06:30,  4.95s/it]

[I 2026-05-18 13:04:38,029] Trial 421 finished with value: 0.9498779176120904 and parameters: {'n_estimators': 280, 'learning_rate': 0.04745359690325608, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 210, 'subsample': 0.6851596523428035, 'colsample_bytree': 0.709634427224215, 'reg_alpha': 6.146233210218901e-05, 'reg_lambda': 1.039464797907954}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  84%|████████▍ | 422/500 [28:24<04:42,  3.62s/it]

[I 2026-05-18 13:04:38,533] Trial 422 finished with value: 0.9498708542488427 and parameters: {'n_estimators': 283, 'learning_rate': 0.04765666789456864, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 231, 'subsample': 0.6354155068128958, 'colsample_bytree': 0.6979669424159469, 'reg_alpha': 0.0001415842431208208, 'reg_lambda': 0.24946778490258534}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  85%|████████▍ | 424/500 [28:25<02:34,  2.03s/it]

[I 2026-05-18 13:04:39,515] Trial 420 finished with value: 0.9498825482134233 and parameters: {'n_estimators': 283, 'learning_rate': 0.0473518518970074, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 226, 'subsample': 0.7221223967674072, 'colsample_bytree': 0.710783720446528, 'reg_alpha': 0.00011786472391215029, 'reg_lambda': 0.9250069588500955}. Best is trial 402 with value: 0.9498857992045373.
[I 2026-05-18 13:04:39,628] Trial 427 finished with value: 0.9496966473767706 and parameters: {'n_estimators': 283, 'learning_rate': 0.0479443918516505, 'max_depth': 1, 'num_leaves': 13, 'min_child_samples': 227, 'subsample': 0.6323115667972523, 'colsample_bytree': 0.6977986598361401, 'reg_alpha': 5.661076248396089e-05, 'reg_lambda': 0.3934716182979083}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  85%|████████▌ | 425/500 [28:33<04:53,  3.92s/it]

[I 2026-05-18 13:04:48,000] Trial 423 finished with value: 0.9498782042477119 and parameters: {'n_estimators': 283, 'learning_rate': 0.04753962702973863, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 229, 'subsample': 0.7203250803083345, 'colsample_bytree': 0.6996062174186213, 'reg_alpha': 5.940694786278403e-05, 'reg_lambda': 1.1074579827149882}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  85%|████████▌ | 426/500 [28:34<03:47,  3.07s/it]

[I 2026-05-18 13:04:49,096] Trial 424 finished with value: 0.9498677873258611 and parameters: {'n_estimators': 269, 'learning_rate': 0.04986573110251907, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 229, 'subsample': 0.6346550285048307, 'colsample_bytree': 0.7002573401231728, 'reg_alpha': 6.1135508984457e-05, 'reg_lambda': 0.9860772511101911}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  85%|████████▌ | 427/500 [28:37<03:35,  2.95s/it]

[I 2026-05-18 13:04:51,763] Trial 425 finished with value: 0.9498692233789361 and parameters: {'n_estimators': 284, 'learning_rate': 0.04999594560894062, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 233, 'subsample': 0.6470733077608614, 'colsample_bytree': 0.6955018000227334, 'reg_alpha': 6.050211134500041e-05, 'reg_lambda': 1.009047397894344}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  86%|████████▌ | 428/500 [28:39<03:14,  2.71s/it]

[I 2026-05-18 13:04:53,908] Trial 432 pruned.

Best trial: 402. Best value: 0.949886:  86%|████████▌ | 429/500 [28:47<04:57,  4.20s/it]

[I 2026-05-18 13:05:01,571] Trial 426 finished with value: 0.949872479506881 and parameters: {'n_estimators': 268, 'learning_rate': 0.0477668278463357, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 231, 'subsample': 0.6348419584647568, 'colsample_bytree': 0.6996032393753364, 'reg_alpha': 6.273838359371508e-05, 'reg_lambda': 0.8941751644558542}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  86%|████████▌ | 430/500 [28:49<04:05,  3.50s/it]

[I 2026-05-18 13:05:03,475] Trial 433 finished with value: 0.9496792326072633 and parameters: {'n_estimators': 268, 'learning_rate': 0.04290379611395231, 'max_depth': 1, 'num_leaves': 12, 'min_child_samples': 290, 'subsample': 0.6272834153057484, 'colsample_bytree': 0.657316746096239, 'reg_alpha': 0.7586166608153908, 'reg_lambda': 0.36973773541922395}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  86%|████████▌ | 431/500 [28:51<03:33,  3.09s/it]

[I 2026-05-18 13:05:05,576] Trial 428 finished with value: 0.9498776419089922 and parameters: {'n_estimators': 268, 'learning_rate': 0.039940944176982386, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 232, 'subsample': 0.7254646855695598, 'colsample_bytree': 0.6979325844658341, 'reg_alpha': 5.5711554761378487e-05, 'reg_lambda': 0.9968392235038871}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  86%|████████▋ | 432/500 [28:52<02:57,  2.61s/it]

[I 2026-05-18 13:05:07,076] Trial 434 finished with value: 0.9496934904188361 and parameters: {'n_estimators': 284, 'learning_rate': 0.04330223402146617, 'max_depth': 1, 'num_leaves': 13, 'min_child_samples': 291, 'subsample': 0.7648063782709523, 'colsample_bytree': 0.6980370111400217, 'reg_alpha': 0.0001528407709851094, 'reg_lambda': 0.7257425386716118}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  87%|████████▋ | 433/500 [28:57<03:44,  3.36s/it]

[I 2026-05-18 13:05:12,170] Trial 430 finished with value: 0.9498649124709491 and parameters: {'n_estimators': 269, 'learning_rate': 0.049927777916537616, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 230, 'subsample': 0.6337194579134768, 'colsample_bytree': 0.697216009227761, 'reg_alpha': 6.175911502338473e-05, 'reg_lambda': 0.2676945556968775}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  87%|████████▋ | 434/500 [29:03<04:18,  3.92s/it]

[I 2026-05-18 13:05:17,403] Trial 429 finished with value: 0.949868793194138 and parameters: {'n_estimators': 269, 'learning_rate': 0.04992623404834295, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 233, 'subsample': 0.6377463965175906, 'colsample_bytree': 0.6955407188954941, 'reg_alpha': 6.0340534189102534e-05, 'reg_lambda': 1.0516463125099822}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  87%|████████▋ | 435/500 [29:13<06:18,  5.83s/it]

[I 2026-05-18 13:05:27,702] Trial 431 finished with value: 0.9498780785783687 and parameters: {'n_estimators': 269, 'learning_rate': 0.04265645237045451, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 290, 'subsample': 0.6278412421004255, 'colsample_bytree': 0.6979908661490354, 'reg_alpha': 0.00014990063264852887, 'reg_lambda': 0.43130068742813615}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  87%|████████▋ | 436/500 [29:15<04:53,  4.59s/it]

[I 2026-05-18 13:05:29,381] Trial 435 finished with value: 0.9498792234621142 and parameters: {'n_estimators': 271, 'learning_rate': 0.049922475711328566, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 235, 'subsample': 0.7229718743297054, 'colsample_bytree': 0.6961223947436215, 'reg_alpha': 0.00016410688064326417, 'reg_lambda': 0.721081258681834}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  87%|████████▋ | 437/500 [29:24<06:16,  5.98s/it]

[I 2026-05-18 13:05:38,589] Trial 440 finished with value: 0.9498264530656092 and parameters: {'n_estimators': 274, 'learning_rate': 0.04264005634516243, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 240, 'subsample': 0.7219490570182666, 'colsample_bytree': 0.6716447543768904, 'reg_alpha': 0.0001451246506507257, 'reg_lambda': 0.7550721948303647}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  88%|████████▊ | 438/500 [29:25<04:42,  4.56s/it]

[I 2026-05-18 13:05:39,823] Trial 436 finished with value: 0.9498785086176591 and parameters: {'n_estimators': 271, 'learning_rate': 0.04973945005620593, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 233, 'subsample': 0.7333362229033286, 'colsample_bytree': 0.658751843214151, 'reg_alpha': 0.00015361816581381993, 'reg_lambda': 0.7247158967730568}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  88%|████████▊ | 439/500 [29:29<04:31,  4.44s/it]

[I 2026-05-18 13:05:44,010] Trial 438 finished with value: 0.9498750611512465 and parameters: {'n_estimators': 273, 'learning_rate': 0.04251634500013393, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 292, 'subsample': 0.7256873364263475, 'colsample_bytree': 0.6673147964160152, 'reg_alpha': 0.0002276185750233453, 'reg_lambda': 0.773399509561935}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  88%|████████▊ | 440/500 [29:31<03:33,  3.56s/it]

[I 2026-05-18 13:05:45,501] Trial 437 finished with value: 0.9498805589925045 and parameters: {'n_estimators': 293, 'learning_rate': 0.04269764089362371, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 233, 'subsample': 0.6945164617261689, 'colsample_bytree': 0.6577697915749134, 'reg_alpha': 0.00021422180337777816, 'reg_lambda': 0.649306855395501}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  88%|████████▊ | 441/500 [29:35<03:42,  3.78s/it]

[I 2026-05-18 13:05:49,797] Trial 439 finished with value: 0.9498807691810157 and parameters: {'n_estimators': 295, 'learning_rate': 0.04287362875575301, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 291, 'subsample': 0.689465560636555, 'colsample_bytree': 0.6579999537825739, 'reg_alpha': 0.00020266579082049135, 'reg_lambda': 0.5873011128866221}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  88%|████████▊ | 442/500 [29:42<04:41,  4.85s/it]

[I 2026-05-18 13:05:57,150] Trial 441 finished with value: 0.9498827875894655 and parameters: {'n_estimators': 273, 'learning_rate': 0.03990198762619798, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 241, 'subsample': 0.7033443457489561, 'colsample_bytree': 0.6802256626355546, 'reg_alpha': 0.00020371535314286983, 'reg_lambda': 0.6053350449486142}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  89%|████████▊ | 443/500 [29:45<03:51,  4.07s/it]

[I 2026-05-18 13:05:59,394] Trial 442 finished with value: 0.9498732135974042 and parameters: {'n_estimators': 274, 'learning_rate': 0.04293740458493566, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 276, 'subsample': 0.7970243784661865, 'colsample_bytree': 0.6673282847491175, 'reg_alpha': 0.00016001825706797612, 'reg_lambda': 0.6608598437929475}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  89%|████████▉ | 444/500 [29:47<03:14,  3.48s/it]

[I 2026-05-18 13:06:01,504] Trial 443 finished with value: 0.9498736338219607 and parameters: {'n_estimators': 295, 'learning_rate': 0.045249709409952675, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 240, 'subsample': 0.7112603432738679, 'colsample_bytree': 0.6735704196542046, 'reg_alpha': 0.00023615360797935798, 'reg_lambda': 0.5480424711339759}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  89%|████████▉ | 445/500 [29:52<03:34,  3.90s/it]

[I 2026-05-18 13:06:06,350] Trial 447 finished with value: 0.9498336200550691 and parameters: {'n_estimators': 295, 'learning_rate': 0.04481619296460964, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 245, 'subsample': 0.7035589416683025, 'colsample_bytree': 0.6703569665165511, 'reg_alpha': 0.00021334514702867324, 'reg_lambda': 1.2720412446110845}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  89%|████████▉ | 446/500 [29:54<03:11,  3.54s/it]

[I 2026-05-18 13:06:09,080] Trial 444 finished with value: 0.9498771921534956 and parameters: {'n_estimators': 296, 'learning_rate': 0.0443575585189614, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 242, 'subsample': 0.7361408887639933, 'colsample_bytree': 0.6702156503654684, 'reg_alpha': 0.00023242800368966472, 'reg_lambda': 0.606348686863249}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  89%|████████▉ | 447/500 [29:57<02:51,  3.23s/it]

[I 2026-05-18 13:06:11,566] Trial 445 finished with value: 0.9498789366289431 and parameters: {'n_estimators': 273, 'learning_rate': 0.044717094066917956, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 276, 'subsample': 0.7141369337343336, 'colsample_bytree': 0.6670161600017245, 'reg_alpha': 3.276483810026002e-05, 'reg_lambda': 2.1353960614888905}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  90%|████████▉ | 448/500 [30:12<06:01,  6.96s/it]

[I 2026-05-18 13:06:27,241] Trial 446 finished with value: 0.949876189396395 and parameters: {'n_estimators': 296, 'learning_rate': 0.04519535288448537, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 277, 'subsample': 0.6937473220930915, 'colsample_bytree': 0.6722195607780905, 'reg_alpha': 2.8448912559116854e-05, 'reg_lambda': 0.6394313383638669}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  90%|████████▉ | 449/500 [30:13<04:13,  4.97s/it]

[I 2026-05-18 13:06:27,546] Trial 450 finished with value: 0.9498636176544352 and parameters: {'n_estimators': 245, 'learning_rate': 0.04537125918695282, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 56, 'subsample': 0.7029693831928976, 'colsample_bytree': 0.676744861054364, 'reg_alpha': 3.2196037845784146e-05, 'reg_lambda': 2.197219711549788}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  90%|█████████ | 450/500 [30:21<05:03,  6.07s/it]

[I 2026-05-18 13:06:36,218] Trial 451 finished with value: 0.9498698391931744 and parameters: {'n_estimators': 293, 'learning_rate': 0.045696069360765784, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 243, 'subsample': 0.7964397659291986, 'colsample_bytree': 0.635288256310822, 'reg_alpha': 3.2535906219978743e-05, 'reg_lambda': 2.2859310226990863}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  90%|█████████ | 451/500 [30:22<03:39,  4.48s/it]

[I 2026-05-18 13:06:36,956] Trial 448 finished with value: 0.949879902480148 and parameters: {'n_estimators': 293, 'learning_rate': 0.04509536631547014, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 244, 'subsample': 0.7080645957514456, 'colsample_bytree': 0.667259045746141, 'reg_alpha': 3.324140353628088e-05, 'reg_lambda': 2.200325989056105}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  90%|█████████ | 452/500 [30:23<02:37,  3.28s/it]

[I 2026-05-18 13:06:37,419] Trial 449 finished with value: 0.9498716795702432 and parameters: {'n_estimators': 292, 'learning_rate': 0.045099362159887295, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 244, 'subsample': 0.7753281088897005, 'colsample_bytree': 0.6797274439241286, 'reg_alpha': 0.00021457096297305945, 'reg_lambda': 39.05606584805726}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  91%|█████████ | 453/500 [30:32<04:03,  5.18s/it]

[I 2026-05-18 13:06:47,046] Trial 452 finished with value: 0.9498778918176211 and parameters: {'n_estimators': 287, 'learning_rate': 0.04531281741438661, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 244, 'subsample': 0.778239479545535, 'colsample_bytree': 0.6337706148644674, 'reg_alpha': 3.285750014699682e-05, 'reg_lambda': 1.358542885105087}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  91%|█████████ | 454/500 [30:34<03:03,  3.99s/it]

[I 2026-05-18 13:06:48,284] Trial 454 finished with value: 0.9498600384032836 and parameters: {'n_estimators': 286, 'learning_rate': 0.039876325174828385, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 28, 'subsample': 0.697380953722131, 'colsample_bytree': 0.6790662015420246, 'reg_alpha': 2.5767816261998435e-05, 'reg_lambda': 0.4799338281479754}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  91%|█████████ | 455/500 [30:37<02:58,  3.97s/it]

[I 2026-05-18 13:06:52,193] Trial 455 finished with value: 0.949871556704409 and parameters: {'n_estimators': 274, 'learning_rate': 0.045296992315609366, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 243, 'subsample': 0.6963064140377371, 'colsample_bytree': 0.6803837656490064, 'reg_alpha': 2.233722837474429e-05, 'reg_lambda': 1.417508868790594}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  91%|█████████ | 456/500 [30:45<03:42,  5.05s/it]

[I 2026-05-18 13:06:59,787] Trial 456 finished with value: 0.9498751368939278 and parameters: {'n_estimators': 288, 'learning_rate': 0.03961179426747917, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 241, 'subsample': 0.7027638769860334, 'colsample_bytree': 0.6840327532319139, 'reg_alpha': 2.427308303268531e-05, 'reg_lambda': 2.212573462924248}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  91%|█████████▏| 457/500 [30:46<02:39,  3.70s/it]

[I 2026-05-18 13:07:00,335] Trial 457 finished with value: 0.9498740212530834 and parameters: {'n_estimators': 285, 'learning_rate': 0.03990416718431408, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 221, 'subsample': 0.71346273179023, 'colsample_bytree': 0.6806187487898581, 'reg_alpha': 2.2478602448780702e-05, 'reg_lambda': 37.28572580498337}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  92%|█████████▏| 458/500 [30:46<01:52,  2.67s/it]

[I 2026-05-18 13:07:00,586] Trial 453 finished with value: 0.9497368304228313 and parameters: {'n_estimators': 286, 'learning_rate': 0.009424119004228399, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 242, 'subsample': 0.7078488346646615, 'colsample_bytree': 0.6784590583906176, 'reg_alpha': 2.0740120484746937e-05, 'reg_lambda': 0.5103202359145588}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  92%|█████████▏| 459/500 [30:47<01:35,  2.33s/it]

[I 2026-05-18 13:07:02,132] Trial 458 finished with value: 0.9498764906252957 and parameters: {'n_estimators': 288, 'learning_rate': 0.04017689053031351, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 243, 'subsample': 0.7110053257090881, 'colsample_bytree': 0.6792768629811838, 'reg_alpha': 2.1715374754458946e-05, 'reg_lambda': 3.160670516313474}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  92%|█████████▏| 460/500 [31:03<04:13,  6.35s/it]

[I 2026-05-18 13:07:17,845] Trial 459 finished with value: 0.9498649995568831 and parameters: {'n_estimators': 285, 'learning_rate': 0.039887713473043096, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 223, 'subsample': 0.7143207584005226, 'colsample_bytree': 0.6810852667666468, 'reg_alpha': 2.0679888730705585e-05, 'reg_lambda': 50.37703485924117}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  92%|█████████▏| 461/500 [31:09<04:04,  6.27s/it]

[I 2026-05-18 13:07:23,943] Trial 460 finished with value: 0.9498750733124472 and parameters: {'n_estimators': 284, 'learning_rate': 0.039011007050160904, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 223, 'subsample': 0.7157901068027138, 'colsample_bytree': 0.681895592625698, 'reg_alpha': 1.8862344469646018e-05, 'reg_lambda': 3.4208812429319333}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  92%|█████████▏| 462/500 [31:14<03:45,  5.93s/it]

[I 2026-05-18 13:07:29,091] Trial 464 finished with value: 0.9496493921124051 and parameters: {'n_estimators': 210, 'learning_rate': 0.009610737907750121, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 237, 'subsample': 0.6795950937371067, 'colsample_bytree': 0.6827674949727099, 'reg_alpha': 2.0501547626141742e-05, 'reg_lambda': 3.236020939364884}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  93%|█████████▎| 463/500 [31:15<02:37,  4.26s/it]

[I 2026-05-18 13:07:29,462] Trial 461 finished with value: 0.9498732400327201 and parameters: {'n_estimators': 286, 'learning_rate': 0.04006977951303329, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 222, 'subsample': 0.7018764380424548, 'colsample_bytree': 0.6839838767159936, 'reg_alpha': 1.963895468406695e-05, 'reg_lambda': 1.3365767500818466}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  93%|█████████▎| 464/500 [31:18<02:27,  4.09s/it]

[I 2026-05-18 13:07:33,174] Trial 463 finished with value: 0.9498787560233352 and parameters: {'n_estimators': 287, 'learning_rate': 0.04002237196462731, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 220, 'subsample': 0.6753087844912282, 'colsample_bytree': 0.6819961386683643, 'reg_alpha': 2.0049001599658076e-05, 'reg_lambda': 1.4740238604949771}. Best is trial 402 with value: 0.9498857992045373.
[I 2026-05-18 13:07:33,214] Trial 462 finished with value: 0.9498756888562013 and parameters: {'n_estimators': 286, 'learning_rate': 0.03906243358836038, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 222, 'subsample': 0.708579557660358, 'colsample_bytree': 0.6850592546107482, 'reg_alpha': 2.2275353423368726e-05, 'reg_lambda': 3.3525241291875476}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  93%|█████████▎| 466/500 [31:20<01:27,  2.59s/it]

[I 2026-05-18 13:07:34,809] Trial 466 finished with value: 0.9498579777991327 and parameters: {'n_estimators': 207, 'learning_rate': 0.04012577019073519, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 239, 'subsample': 0.7124102187364564, 'colsample_bytree': 0.6828068872960408, 'reg_alpha': 1.873550016351317e-05, 'reg_lambda': 3.475336772403965}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  93%|█████████▎| 467/500 [31:27<02:03,  3.73s/it]

[I 2026-05-18 13:07:41,988] Trial 465 finished with value: 0.9498735537187427 and parameters: {'n_estimators': 276, 'learning_rate': 0.039660625316103634, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 220, 'subsample': 0.7042772025276806, 'colsample_bytree': 0.6807699234099057, 'reg_alpha': 1.7877116999023576e-05, 'reg_lambda': 3.4397768518199494}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  94%|█████████▎| 468/500 [31:29<01:41,  3.17s/it]

[I 2026-05-18 13:07:43,594] Trial 467 finished with value: 0.9498656144101021 and parameters: {'n_estimators': 225, 'learning_rate': 0.040131494940072794, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 221, 'subsample': 0.7119844675841012, 'colsample_bytree': 0.6291790179948412, 'reg_alpha': 1.7781721673355252e-05, 'reg_lambda': 3.1268566323675415}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  94%|█████████▍| 469/500 [31:34<01:57,  3.79s/it]

[I 2026-05-18 13:07:49,045] Trial 468 finished with value: 0.949881216375655 and parameters: {'n_estimators': 276, 'learning_rate': 0.047417980341260796, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 222, 'subsample': 0.6829448578674601, 'colsample_bytree': 0.632653048129181, 'reg_alpha': 1.5807479158854724e-05, 'reg_lambda': 3.117515556692732}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  94%|█████████▍| 470/500 [31:39<02:01,  4.05s/it]

[I 2026-05-18 13:07:53,762] Trial 469 finished with value: 0.9498740825742666 and parameters: {'n_estimators': 276, 'learning_rate': 0.040018741675100764, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 223, 'subsample': 0.8191034907767193, 'colsample_bytree': 0.6291385596061144, 'reg_alpha': 1.7853973664142696e-05, 'reg_lambda': 3.341332564115326}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  94%|█████████▍| 471/500 [31:43<01:53,  3.90s/it]

[I 2026-05-18 13:07:57,321] Trial 470 finished with value: 0.9498741106951009 and parameters: {'n_estimators': 277, 'learning_rate': 0.047710282079179496, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 222, 'subsample': 0.8185687489821798, 'colsample_bytree': 0.6472111467605377, 'reg_alpha': 1.6463928963504633e-05, 'reg_lambda': 3.121380875827841}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  94%|█████████▍| 472/500 [31:52<02:32,  5.46s/it]

[I 2026-05-18 13:08:06,572] Trial 471 finished with value: 0.9498231214382761 and parameters: {'n_estimators': 277, 'learning_rate': 0.047849532665638767, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 250, 'subsample': 0.8189875786209043, 'colsample_bytree': 0.6480359957806264, 'reg_alpha': 90.59622198162546, 'reg_lambda': 3.2249881258097175}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  95%|█████████▍| 473/500 [31:53<01:49,  4.06s/it]

[I 2026-05-18 13:08:07,263] Trial 478 finished with value: 0.9498445722175974 and parameters: {'n_estimators': 128, 'learning_rate': 0.04719721094269519, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 186, 'subsample': 0.8218482409111074, 'colsample_bytree': 0.6277227162307615, 'reg_alpha': 1.3183115047613626e-05, 'reg_lambda': 1.3236558495535455}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  95%|█████████▍| 474/500 [32:01<02:22,  5.46s/it]

[I 2026-05-18 13:08:16,077] Trial 472 finished with value: 0.9498749665550518 and parameters: {'n_estimators': 276, 'learning_rate': 0.04730686670889961, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 236, 'subsample': 0.6749177022420557, 'colsample_bytree': 0.6303204019292411, 'reg_alpha': 1.441508671329805e-05, 'reg_lambda': 1.3958801832560437}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  95%|█████████▌| 475/500 [32:02<01:38,  3.95s/it]

[I 2026-05-18 13:08:16,412] Trial 474 finished with value: 0.9498723567517396 and parameters: {'n_estimators': 264, 'learning_rate': 0.04822673719042859, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 251, 'subsample': 0.8162917454541498, 'colsample_bytree': 0.627033178821542, 'reg_alpha': 1.413981472046969e-05, 'reg_lambda': 1.2800293651616597}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  95%|█████████▌| 476/500 [32:07<01:47,  4.47s/it]

[I 2026-05-18 13:08:22,143] Trial 473 finished with value: 0.9498793307150362 and parameters: {'n_estimators': 276, 'learning_rate': 0.04693007234780502, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 236, 'subsample': 0.8214666877681698, 'colsample_bytree': 0.6479530151622718, 'reg_alpha': 1.3368041473158207e-05, 'reg_lambda': 1.3743073451160828}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  95%|█████████▌| 477/500 [32:09<01:24,  3.67s/it]

[I 2026-05-18 13:08:23,935] Trial 476 finished with value: 0.9498693651399985 and parameters: {'n_estimators': 277, 'learning_rate': 0.04752615192037147, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 237, 'subsample': 0.8081931350394553, 'colsample_bytree': 0.6298679912405862, 'reg_alpha': 1.4851865614192013e-05, 'reg_lambda': 1.420012210808005}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  96%|█████████▌| 478/500 [32:12<01:12,  3.29s/it]

[I 2026-05-18 13:08:26,332] Trial 475 finished with value: 0.9498742496013133 and parameters: {'n_estimators': 277, 'learning_rate': 0.047155711167579266, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 250, 'subsample': 0.6628809373910175, 'colsample_bytree': 0.647516429732972, 'reg_alpha': 1.3442608631817597e-05, 'reg_lambda': 0.9556437924228687}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  96%|█████████▌| 479/500 [32:14<01:04,  3.09s/it]

[I 2026-05-18 13:08:28,932] Trial 477 finished with value: 0.949879202308009 and parameters: {'n_estimators': 277, 'learning_rate': 0.047395014596272954, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 185, 'subsample': 0.8164852744518516, 'colsample_bytree': 0.6467662751252352, 'reg_alpha': 1.4745234282924633e-05, 'reg_lambda': 1.0449091540122486}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  96%|█████████▌| 480/500 [32:25<01:48,  5.45s/it]

[I 2026-05-18 13:08:39,873] Trial 479 finished with value: 0.9498730567144218 and parameters: {'n_estimators': 277, 'learning_rate': 0.0480991463402869, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 250, 'subsample': 0.8073288857139254, 'colsample_bytree': 0.7271647297186319, 'reg_alpha': 0.0001158716668456457, 'reg_lambda': 1.1982585901236134}. Best is trial 402 with value: 0.9498857992045373.
[I 2026-05-18 13:08:39,916] Trial 480 finished with value: 0.9498741344456236 and parameters: {'n_estimators': 278, 'learning_rate': 0.04782262973638905, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 286, 'subsample': 0.685294604069258, 'colsample_bytree': 0.6480530712462242, 'reg_alpha': 0.00011894495088198072, 'reg_lambda': 1.3366401990133305}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  96%|█████████▋| 482/500 [32:27<01:01,  3.44s/it]

[I 2026-05-18 13:08:42,114] Trial 481 finished with value: 0.9498730408067289 and parameters: {'n_estimators': 277, 'learning_rate': 0.04694149142961505, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 226, 'subsample': 0.7510460873044487, 'colsample_bytree': 0.6177024060697298, 'reg_alpha': 1.3230404060244307e-05, 'reg_lambda': 1.1717913770622792}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  97%|█████████▋| 483/500 [32:33<01:08,  4.03s/it]

[I 2026-05-18 13:08:47,923] Trial 482 finished with value: 0.9498776981561876 and parameters: {'n_estimators': 280, 'learning_rate': 0.0474793072577556, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 209, 'subsample': 0.6900833252469096, 'colsample_bytree': 0.6211587440039044, 'reg_alpha': 1.301389567256223e-05, 'reg_lambda': 1.135928913453804}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  97%|█████████▋| 484/500 [32:44<01:33,  5.83s/it]

[I 2026-05-18 13:08:58,833] Trial 483 finished with value: 0.949869675184423 and parameters: {'n_estimators': 265, 'learning_rate': 0.03592431142879782, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 205, 'subsample': 0.6855919949051267, 'colsample_bytree': 0.634139111423559, 'reg_alpha': 1.3116434589478932e-05, 'reg_lambda': 1.226372209347385}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  97%|█████████▋| 485/500 [32:45<01:08,  4.60s/it]

[I 2026-05-18 13:09:00,131] Trial 484 finished with value: 0.949876307248179 and parameters: {'n_estimators': 266, 'learning_rate': 0.047347471303851724, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 195, 'subsample': 0.6891332557022263, 'colsample_bytree': 0.6181490347656018, 'reg_alpha': 1.3165010417458322e-05, 'reg_lambda': 0.9433194154760596}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  97%|█████████▋| 486/500 [32:54<01:19,  5.67s/it]

[I 2026-05-18 13:09:08,581] Trial 485 finished with value: 0.94986891115764 and parameters: {'n_estimators': 265, 'learning_rate': 0.043068885750782424, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 227, 'subsample': 0.6904367422140313, 'colsample_bytree': 0.6206157242311401, 'reg_alpha': 0.0001343749886478401, 'reg_lambda': 0.35154527911678185}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  97%|█████████▋| 487/500 [32:57<01:04,  4.99s/it]

[I 2026-05-18 13:09:11,846] Trial 486 finished with value: 0.9498812563496631 and parameters: {'n_estimators': 281, 'learning_rate': 0.042492467157687314, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 227, 'subsample': 0.6821820535605605, 'colsample_bytree': 0.6362591127644117, 'reg_alpha': 1.0038033399192376e-05, 'reg_lambda': 0.8927210458272402}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  98%|█████████▊| 488/500 [32:59<00:49,  4.12s/it]

[I 2026-05-18 13:09:13,820] Trial 487 finished with value: 0.9498755068455154 and parameters: {'n_estimators': 265, 'learning_rate': 0.04268400665712612, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 208, 'subsample': 0.6868768220832056, 'colsample_bytree': 0.613074087095535, 'reg_alpha': 0.00013475477154123886, 'reg_lambda': 0.8859152372819156}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  98%|█████████▊| 489/500 [33:02<00:42,  3.83s/it]

[I 2026-05-18 13:09:16,982] Trial 488 finished with value: 0.94987632591211 and parameters: {'n_estimators': 265, 'learning_rate': 0.042188123079995275, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 228, 'subsample': 0.6892260314315541, 'colsample_bytree': 0.6164944111657218, 'reg_alpha': 9.605742156815547e-05, 'reg_lambda': 0.0011733358502803084}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  98%|█████████▊| 490/500 [33:05<00:35,  3.59s/it]

[I 2026-05-18 13:09:19,981] Trial 490 finished with value: 0.9498811863695383 and parameters: {'n_estimators': 265, 'learning_rate': 0.042536207341884326, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 135, 'subsample': 0.6939298977203266, 'colsample_bytree': 0.6355617579991094, 'reg_alpha': 0.00011153021619983618, 'reg_lambda': 0.35330227074570697}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  98%|█████████▊| 491/500 [33:06<00:24,  2.68s/it]

[I 2026-05-18 13:09:20,504] Trial 489 finished with value: 0.9498748555586884 and parameters: {'n_estimators': 266, 'learning_rate': 0.042558678105857076, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 284, 'subsample': 0.7986658494658784, 'colsample_bytree': 0.7274463554854875, 'reg_alpha': 1.0073939621518079e-05, 'reg_lambda': 0.32561540480481854}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  98%|█████████▊| 492/500 [33:12<00:30,  3.75s/it]

[I 2026-05-18 13:09:26,803] Trial 494 finished with value: 0.9498604854359346 and parameters: {'n_estimators': 194, 'learning_rate': 0.04302664656363201, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 227, 'subsample': 0.6645131684040386, 'colsample_bytree': 0.6376888395265968, 'reg_alpha': 8.431402096265325e-05, 'reg_lambda': 0.4155704953430914}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  99%|█████████▊| 493/500 [33:15<00:23,  3.40s/it]

[I 2026-05-18 13:09:29,372] Trial 491 finished with value: 0.9498772747849238 and parameters: {'n_estimators': 265, 'learning_rate': 0.042818772405347594, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 227, 'subsample': 0.7981802808721005, 'colsample_bytree': 0.7040098384020537, 'reg_alpha': 0.0003156292776272158, 'reg_lambda': 2.1941867440520233}. Best is trial 402 with value: 0.9498857992045373.
[I 2026-05-18 13:09:29,575] Trial 493 finished with value: 0.949875054396841 and parameters: {'n_estimators': 264, 'learning_rate': 0.042922544034201544, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 286, 'subsample': 0.6855504543406736, 'colsample_bytree': 0.6373810177144006, 'reg_alpha': 7.583301004196432e-05, 'reg_lambda': 0.46506601733839026}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  99%|█████████▉| 495/500 [33:15<00:09,  1.81s/it]

[I 2026-05-18 13:09:29,897] Trial 492 finished with value: 0.9498790632619917 and parameters: {'n_estimators': 265, 'learning_rate': 0.04206455155853143, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 226, 'subsample': 0.7946973288391443, 'colsample_bytree': 0.6144680572668795, 'reg_alpha': 0.0003286101179401216, 'reg_lambda': 0.35356682005080875}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  99%|█████████▉| 496/500 [33:22<00:13,  3.27s/it]

[I 2026-05-18 13:09:36,583] Trial 495 finished with value: 0.9498811549388859 and parameters: {'n_estimators': 265, 'learning_rate': 0.042637195543271486, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 230, 'subsample': 0.7937792601336336, 'colsample_bytree': 0.6182201769232853, 'reg_alpha': 1.5190879983592245, 'reg_lambda': 0.340491691488558}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886:  99%|█████████▉| 497/500 [33:23<00:07,  2.66s/it]

[I 2026-05-18 13:09:37,821] Trial 496 finished with value: 0.9498821998748703 and parameters: {'n_estimators': 270, 'learning_rate': 0.043231015721234965, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 228, 'subsample': 0.7966101450322209, 'colsample_bytree': 0.6396987054225923, 'reg_alpha': 7.129919492247167e-05, 'reg_lambda': 0.4917626381574796}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886: 100%|█████████▉| 498/500 [33:25<00:04,  2.33s/it]

[I 2026-05-18 13:09:39,391] Trial 497 finished with value: 0.949877802806091 and parameters: {'n_estimators': 271, 'learning_rate': 0.042657691700536904, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 284, 'subsample': 0.6627648003785579, 'colsample_bytree': 0.6380435057070192, 'reg_alpha': 9.465356078077375e-05, 'reg_lambda': 1.9709378122005294}. Best is trial 402 with value: 0.9498857992045373.

Best trial: 402. Best value: 0.949886: 100%|██████████| 500/500 [33:25<00:00,  4.01s/it]

[I 2026-05-18 13:09:40,156] Trial 499 finished with value: 0.9498773869093011 and parameters: {'n_estimators': 272, 'learning_rate': 0.0428186246967835, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 228, 'subsample': 0.6636462470335653, 'colsample_bytree': 0.6387952995802296, 'reg_alpha': 1.077338411528663e-05, 'reg_lambda': 0.46468879426367793}. Best is trial 402 with value: 0.9498857992045373.
[I 2026-05-18 13:09:40,181] Trial 498 finished with value: 0.9498830261667685 and parameters: {'n_estimators': 272, 'learning_rate': 0.04203852396521302, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 233, 'subsample': 0.6784121688169144, 'colsample_bytree': 0.6387267050849619, 'reg_alpha': 1.0246328020384085e-05, 'reg_lambda': 0.4468811257355107}. Best is trial 402 with value: 0.9498857992045373.
Best trial score:
0.9498857992045373

Best params:
{'n_estimators': 279, 'learning_rate': 0.0460336674084307, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 231, 'subsample': 0.6443523206683296, 'colsample_bytree': 0.6862178024026039, 'reg_alpha': 8.19860610452054e-05, 'reg_lambda': 1.6658799864296214}

In [13]:
stacking_lg = LGBMClassifier(**study.best_params).fit(X_train, y_train.PitNextLap)

[LightGBM] [Info] Number of positive: 87381, number of negative: 351759
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001593 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1785
[LightGBM] [Info] Number of data points in the train set: 439140, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198982 -> initscore=-1.392668
[LightGBM] [Info] Start training from score -1.392668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

# Submission

In [14]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [15]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test)[:, 1]

In [16]:
submission.to_csv('../data/submission/submission.csv', index=False)