# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from catboost import CatBoostClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

In [3]:
def voting_cross_val_predict(probas: list[np.ndarray], weights: np.ndarray[float]) -> np.ndarray[float]:
    weights /= weights.sum()
    return np.sum([proba * weight for proba, weight in zip(probas, weights)], axis=0)

# Loading Dataset

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_stacking.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking.parquet')

In [5]:
X_train.head()

   lgbm_proba  cat_proba  xgb_proba  hist_proba  lg_proba  knn_proba
0    0.802607   0.891870   0.895659    0.883947  0.808497   0.887454
1    0.649405   0.831360   0.829854    0.779541  0.689888   0.519966
2    0.505904   0.851809   0.751522    0.758911  0.558520   0.209855
3    0.001713   0.005910   0.007057    0.007298  0.002275   0.000000
4    0.392205   0.565506   0.489033    0.482967  0.414144   0.297043

In [6]:
X_test.head()

   lgbm_proba  cat_proba  xgb_proba  hist_proba  lg_proba  knn_proba
0    0.004591   0.031986   0.022774    0.020057  0.006419   0.000000
1    0.003032   0.011817   0.014957    0.018887  0.063872   0.117213
2    0.003777   0.011641   0.014307    0.011497  0.004517   0.000000
3    0.163131   0.544040   0.585898    0.485388  0.655870   0.099916
4    0.872172   0.967646   0.959451    0.959356  0.840450   1.000000

## Creating Stacking Database

In [7]:
X_train['voting_proba'] = voting_cross_val_predict(
    [
        X_train['lgbm_proba'],
        X_train['cat_proba'],
        X_train['xgb_proba'],
        X_train['hist_proba']
    ], 
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

In [8]:
X_test['voting_proba'] = voting_cross_val_predict(
    [
        X_test['lgbm_proba'],
        X_test['cat_proba'],
        X_test['xgb_proba'],
        X_test['hist_proba']
    ], 
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

In [9]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.868510
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.772514
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.717012
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,0.005494
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,0.482416

# Machine Learning

In [10]:
features_to_use = ['lgbm_proba', 'cat_proba', 'xgb_proba', 'hist_proba', 'lg_proba', 'voting_proba']

In [11]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000)
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LogisticRegression(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

features_to_use = ['lgbm_proba', 'cat_proba', 'xgb_proba', 'hist_proba', 'lg_proba', 'voting_proba']

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train[features_to_use], y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-18 11:33:41,331] A new study created in memory with name: no-name-d7dab09d-ef7a-46d7-9929-b223e4875dea
Best trial: 9. Best value: 0.5:   0%|          | 1/500 [00:06<52:36,  6.32s/it]

[I 2026-05-18 11:33:47,655] Trial 9 finished with value: 0.5 and parameters: {'solver': 'saga', 'C': 1.5132575896452491e-05, 'l1_ratio': 0.9337103830604095, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.992329255778545e-06, 'max_iter': 2987}. Best is trial 9 with value: 0.5.

Best trial: 8. Best value: 0.799165:   0%|          | 2/500 [00:08<30:49,  3.71s/it]

[I 2026-05-18 11:33:49,540] Trial 8 finished with value: 0.7991645737687293 and parameters: {'solver': 'saga', 'C': 0.012679707484120391, 'l1_ratio': 0.047039597691156954, 'class_weight': None, 'fit_intercept': False, 'tol': 0.008018631956286612, 'max_iter': 1173}. Best is trial 8 with value: 0.7991645737687293.

Best trial: 2. Best value: 0.831978:   1%|          | 3/500 [00:14<39:24,  4.76s/it]

[I 2026-05-18 11:33:55,533] Trial 2 finished with value: 0.831978375063881 and parameters: {'solver': 'saga', 'C': 0.00027208595360234225, 'l1_ratio': 0.3221044316740659, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0005580522881477371, 'max_iter': 1336}. Best is trial 2 with value: 0.831978375063881.

Best trial: 2. Best value: 0.831978:   1%|          | 4/500 [00:15<28:53,  3.50s/it]

[I 2026-05-18 11:33:57,099] Trial 11 finished with value: 0.7950318518376204 and parameters: {'solver': 'saga', 'C': 0.01612910315622452, 'l1_ratio': 0.8884466502904286, 'class_weight': None, 'fit_intercept': False, 'tol': 5.267532680210247e-05, 'max_iter': 3900}. Best is trial 2 with value: 0.831978375063881.

Best trial: 7. Best value: 0.949627:   1%|          | 5/500 [00:22<37:24,  4.54s/it]

[I 2026-05-18 11:34:03,475] Trial 7 finished with value: 0.9496267992372266 and parameters: {'solver': 'saga', 'C': 0.0022681175495891616, 'l1_ratio': 0.7304462764097139, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.2009171565266103e-05, 'max_iter': 1647}. Best is trial 7 with value: 0.9496267992372266.

Best trial: 1. Best value: 0.949678:   1%|          | 6/500 [00:22<26:39,  3.24s/it]

[I 2026-05-18 11:34:04,195] Trial 1 finished with value: 0.9496775941090302 and parameters: {'solver': 'saga', 'C': 0.024466260079778143, 'l1_ratio': 0.9130905355772118, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4322951869261454e-05, 'max_iter': 2911}. Best is trial 1 with value: 0.9496775941090302.

Best trial: 1. Best value: 0.949678:   1%|▏         | 7/500 [00:23<19:28,  2.37s/it]

[I 2026-05-18 11:34:04,771] Trial 15 pruned.

Best trial: 1. Best value: 0.949678:   2%|▏         | 8/500 [00:25<17:47,  2.17s/it]

[I 2026-05-18 11:34:06,514] Trial 5 finished with value: 0.9496504846959907 and parameters: {'solver': 'saga', 'C': 0.07475028277636624, 'l1_ratio': 0.5443252390307698, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6958273180085083e-06, 'max_iter': 1663}. Best is trial 1 with value: 0.9496775941090302.

Best trial: 19. Best value: 0.949697:   2%|▏         | 9/500 [00:34<36:48,  4.50s/it]

[I 2026-05-18 11:34:16,139] Trial 19 finished with value: 0.949696537439384 and parameters: {'solver': 'saga', 'C': 0.009198486136415693, 'l1_ratio': 0.3457264996159549, 'class_weight': None, 'fit_intercept': True, 'tol': 0.006149618278312617, 'max_iter': 2826}. Best is trial 19 with value: 0.949696537439384.

Best trial: 13. Best value: 0.949705:   2%|▏         | 11/500 [00:35<18:54,  2.32s/it]

[I 2026-05-18 11:34:16,653] Trial 13 finished with value: 0.9497054361384407 and parameters: {'solver': 'saga', 'C': 0.010970930354681826, 'l1_ratio': 0.6787733979025582, 'class_weight': None, 'fit_intercept': True, 'tol': 1.529004678523097e-06, 'max_iter': 4034}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:34:16,826] Trial 3 pruned.

Best trial: 13. Best value: 0.949705:   2%|▏         | 12/500 [00:40<25:08,  3.09s/it]

[I 2026-05-18 11:34:21,675] Trial 0 pruned.

Best trial: 13. Best value: 0.949705:   3%|▎         | 13/500 [00:40<18:11,  2.24s/it]

[I 2026-05-18 11:34:21,968] Trial 16 pruned.

Best trial: 13. Best value: 0.949705:   3%|▎         | 14/500 [00:48<31:04,  3.84s/it]

[I 2026-05-18 11:34:29,483] Trial 18 finished with value: 0.9496280643045539 and parameters: {'solver': 'saga', 'C': 26.07974417708849, 'l1_ratio': 0.9188917681720933, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3914045743720255e-05, 'max_iter': 4896}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   3%|▎         | 15/500 [00:53<34:29,  4.27s/it]

[I 2026-05-18 11:34:34,747] Trial 14 pruned.

Best trial: 13. Best value: 0.949705:   3%|▎         | 16/500 [00:53<25:24,  3.15s/it]

[I 2026-05-18 11:34:35,310] Trial 22 finished with value: 0.9496280568216715 and parameters: {'solver': 'saga', 'C': 43.062518166008346, 'l1_ratio': 0.24102658763492957, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002151895917675298, 'max_iter': 4904}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   3%|▎         | 17/500 [00:55<22:00,  2.73s/it]

[I 2026-05-18 11:34:37,071] Trial 24 finished with value: 0.9496285259615427 and parameters: {'solver': 'saga', 'C': 4.8955714863809074, 'l1_ratio': 0.1994220804209676, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005232723790953481, 'max_iter': 3580}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   4%|▎         | 18/500 [01:01<30:24,  3.79s/it]

[I 2026-05-18 11:34:43,306] Trial 27 finished with value: 0.9496699989133248 and parameters: {'solver': 'saga', 'C': 0.0015701354269417318, 'l1_ratio': 0.6315649739953216, 'class_weight': None, 'fit_intercept': True, 'tol': 0.009039060993225018, 'max_iter': 3616}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   4%|▍         | 19/500 [01:04<28:22,  3.54s/it]

[I 2026-05-18 11:34:46,266] Trial 28 finished with value: 0.9496801783326271 and parameters: {'solver': 'saga', 'C': 0.0025811682144356524, 'l1_ratio': 0.6333320700458881, 'class_weight': None, 'fit_intercept': True, 'tol': 0.008842678512007564, 'max_iter': 2483}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   4%|▍         | 20/500 [01:08<28:04,  3.51s/it]

[I 2026-05-18 11:34:49,713] Trial 26 finished with value: 0.9496141090063313 and parameters: {'solver': 'saga', 'C': 0.0010327741256938073, 'l1_ratio': 0.5656182382621301, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00046322352112290066, 'max_iter': 3883}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   4%|▍         | 21/500 [01:14<33:11,  4.16s/it]

[I 2026-05-18 11:34:55,381] Trial 29 finished with value: 0.9496738695035634 and parameters: {'solver': 'saga', 'C': 0.0018037376938619433, 'l1_ratio': 0.6314220714025938, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002099948551188051, 'max_iter': 2595}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   4%|▍         | 22/500 [01:15<25:33,  3.21s/it]

[I 2026-05-18 11:34:56,375] Trial 25 finished with value: 0.9496702518793251 and parameters: {'solver': 'saga', 'C': 0.0015115885834646407, 'l1_ratio': 0.6270854248755977, 'class_weight': None, 'fit_intercept': True, 'tol': 1.228394519848031e-06, 'max_iter': 3595}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   5%|▍         | 23/500 [01:16<22:17,  2.80s/it]

[I 2026-05-18 11:34:58,232] Trial 30 finished with value: 0.9496490185556675 and parameters: {'solver': 'saga', 'C': 0.08295191458049879, 'l1_ratio': 0.5158695193034489, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002497088325633595, 'max_iter': 4189}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   5%|▍         | 24/500 [01:20<23:38,  2.98s/it]

[I 2026-05-18 11:35:01,629] Trial 31 finished with value: 0.9496460662803395 and parameters: {'solver': 'saga', 'C': 0.0958021333591718, 'l1_ratio': 0.4701883919191843, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0023415736232160335, 'max_iter': 4406}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   5%|▌         | 25/500 [01:25<29:19,  3.70s/it]

[I 2026-05-18 11:35:07,018] Trial 32 finished with value: 0.9496998658018876 and parameters: {'solver': 'saga', 'C': 0.005351717317021367, 'l1_ratio': 0.7446208941026746, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002846600977831104, 'max_iter': 2459}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   5%|▌         | 26/500 [01:27<23:58,  3.03s/it]

[I 2026-05-18 11:35:08,495] Trial 34 finished with value: 0.9497023339968191 and parameters: {'solver': 'saga', 'C': 0.007508458033899994, 'l1_ratio': 0.7469353663718074, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004358962982223498, 'max_iter': 2415}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   5%|▌         | 27/500 [01:27<17:18,  2.20s/it]

[I 2026-05-18 11:35:08,723] Trial 33 finished with value: 0.9496887175338266 and parameters: {'solver': 'saga', 'C': 0.006117896854327706, 'l1_ratio': 0.4360364026042328, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002160428170054678, 'max_iter': 2351}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   6%|▌         | 28/500 [01:30<18:58,  2.41s/it]

[I 2026-05-18 11:35:11,648] Trial 35 finished with value: 0.9497018672808746 and parameters: {'solver': 'saga', 'C': 0.006893277802934369, 'l1_ratio': 0.7290596528000945, 'class_weight': None, 'fit_intercept': True, 'tol': 0.005813819157870817, 'max_iter': 2443}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   6%|▌         | 29/500 [01:36<26:47,  3.41s/it]

[I 2026-05-18 11:35:17,399] Trial 10 finished with value: 0.9495886268704441 and parameters: {'solver': 'saga', 'C': 85.19851170796746, 'l1_ratio': 0.9591531575843594, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.254287470297759e-05, 'max_iter': 1717}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   6%|▌         | 30/500 [01:38<24:04,  3.07s/it]

[I 2026-05-18 11:35:19,679] Trial 36 finished with value: 0.9497051169394807 and parameters: {'solver': 'saga', 'C': 0.00917779780548345, 'l1_ratio': 0.7288504629429466, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011659762122602254, 'max_iter': 2402}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   6%|▌         | 31/500 [01:47<38:49,  4.97s/it]

[I 2026-05-18 11:35:29,059] Trial 17 finished with value: 0.9495889287827037 and parameters: {'solver': 'saga', 'C': 1.9011284969576485, 'l1_ratio': 0.7836663710940998, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 7.366425629224167e-06, 'max_iter': 3197}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   6%|▋         | 32/500 [01:47<27:37,  3.54s/it]

[I 2026-05-18 11:35:29,283] Trial 38 finished with value: 0.9496100344886905 and parameters: {'solver': 'saga', 'C': 0.00023744808883024445, 'l1_ratio': 0.7269330324602065, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.113135887588482e-05, 'max_iter': 2112}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   7%|▋         | 33/500 [01:49<22:07,  2.84s/it]

[I 2026-05-18 11:35:30,497] Trial 37 finished with value: 0.9496255649970345 and parameters: {'solver': 'saga', 'C': 0.00020368439548136948, 'l1_ratio': 0.7364608305006697, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.167928829073609e-05, 'max_iter': 2243}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   7%|▋         | 34/500 [01:51<21:32,  2.77s/it]

[I 2026-05-18 11:35:33,102] Trial 39 finished with value: 0.9496056273951755 and parameters: {'solver': 'saga', 'C': 0.00047760845976674846, 'l1_ratio': 0.7081158941055561, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.754548170237953e-05, 'max_iter': 2046}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   7%|▋         | 35/500 [01:53<18:42,  2.41s/it]

[I 2026-05-18 11:35:34,680] Trial 40 finished with value: 0.9496289852770701 and parameters: {'solver': 'saga', 'C': 0.0002280237747606294, 'l1_ratio': 0.7906543953177181, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00017587279569404607, 'max_iter': 2142}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   7%|▋         | 36/500 [01:55<18:11,  2.35s/it]

[I 2026-05-18 11:35:36,879] Trial 41 finished with value: 0.9496153517859444 and parameters: {'solver': 'saga', 'C': 0.00025522680887372863, 'l1_ratio': 0.8347763133903707, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00018663253755714148, 'max_iter': 3278}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   7%|▋         | 37/500 [01:59<22:48,  2.96s/it]

[I 2026-05-18 11:35:41,249] Trial 20 pruned.

Best trial: 13. Best value: 0.949705:   8%|▊         | 38/500 [02:01<19:22,  2.52s/it]

[I 2026-05-18 11:35:42,740] Trial 42 finished with value: 0.9496360191915931 and parameters: {'solver': 'saga', 'C': 0.00026766828207205385, 'l1_ratio': 0.6981491125938275, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008787599326554663, 'max_iter': 2010}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   8%|▊         | 39/500 [02:02<16:14,  2.11s/it]

[I 2026-05-18 11:35:43,914] Trial 44 finished with value: 0.9496593966554879 and parameters: {'solver': 'saga', 'C': 0.045249626352141414, 'l1_ratio': 0.8251450250770903, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010507226024739965, 'max_iter': 2701}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   8%|▊         | 40/500 [02:03<13:01,  1.70s/it]

[I 2026-05-18 11:35:44,645] Trial 43 finished with value: 0.9496665547442967 and parameters: {'solver': 'saga', 'C': 0.03489793033398167, 'l1_ratio': 0.8246564159662664, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010848626553301634, 'max_iter': 2168}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   8%|▊         | 41/500 [02:05<13:38,  1.78s/it]

[I 2026-05-18 11:35:46,617] Trial 45 finished with value: 0.9496626423958114 and parameters: {'solver': 'saga', 'C': 0.040074950261518784, 'l1_ratio': 0.823826684126522, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011238852259710607, 'max_iter': 2734}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   8%|▊         | 42/500 [02:06<12:59,  1.70s/it]

[I 2026-05-18 11:35:48,139] Trial 46 finished with value: 0.9496676571354421 and parameters: {'solver': 'saga', 'C': 0.03327658636544249, 'l1_ratio': 0.847880933290709, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012131681647267393, 'max_iter': 2694}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   9%|▊         | 43/500 [02:10<16:35,  2.18s/it]

[I 2026-05-18 11:35:51,423] Trial 47 finished with value: 0.9496646482878184 and parameters: {'solver': 'saga', 'C': 0.039676389887760226, 'l1_ratio': 0.6849721732841522, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010828483792954045, 'max_iter': 2631}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   9%|▉         | 44/500 [02:13<19:52,  2.61s/it]

[I 2026-05-18 11:35:55,063] Trial 50 finished with value: 0.9496391259950829 and parameters: {'solver': 'saga', 'C': 0.15130287495595443, 'l1_ratio': 0.5830967037189495, 'class_weight': None, 'fit_intercept': True, 'tol': 0.005184969199568546, 'max_iter': 1836}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   9%|▉         | 45/500 [02:14<15:48,  2.08s/it]

[I 2026-05-18 11:35:55,903] Trial 48 finished with value: 0.9496630466497414 and parameters: {'solver': 'saga', 'C': 0.041835478872895016, 'l1_ratio': 0.6922734294240764, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009305870938369843, 'max_iter': 2744}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   9%|▉         | 46/500 [02:15<12:36,  1.67s/it]

[I 2026-05-18 11:35:56,596] Trial 51 finished with value: 0.9496350646242254 and parameters: {'solver': 'saga', 'C': 0.27492098018247263, 'l1_ratio': 0.6692911232278604, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0050686896989995435, 'max_iter': 1887}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:   9%|▉         | 47/500 [02:15<09:34,  1.27s/it]

[I 2026-05-18 11:35:56,920] Trial 49 finished with value: 0.949668155423022 and parameters: {'solver': 'saga', 'C': 0.03570052217496977, 'l1_ratio': 0.5811584049299389, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010280084644326273, 'max_iter': 2723}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  10%|▉         | 48/500 [02:16<07:44,  1.03s/it]

[I 2026-05-18 11:35:57,395] Trial 52 finished with value: 0.9496350828684094 and parameters: {'solver': 'saga', 'C': 0.1992811258903434, 'l1_ratio': 0.9866041107101999, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004575573730530302, 'max_iter': 2465}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  10%|▉         | 49/500 [02:17<07:34,  1.01s/it]

[I 2026-05-18 11:35:58,369] Trial 53 finished with value: 0.9496981218148743 and parameters: {'solver': 'saga', 'C': 0.005940892475644587, 'l1_ratio': 0.6772345311769195, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004933815309574159, 'max_iter': 2452}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  10%|█         | 50/500 [02:19<10:14,  1.37s/it]

[I 2026-05-18 11:36:00,563] Trial 4 pruned.

Best trial: 13. Best value: 0.949705:  10%|█         | 51/500 [02:21<11:02,  1.48s/it]

[I 2026-05-18 11:36:02,299] Trial 59 pruned.
[I 2026-05-18 11:36:02,331] Trial 58 pruned.

Best trial: 13. Best value: 0.949705:  11%|█         | 53/500 [02:22<09:18,  1.25s/it]

[I 2026-05-18 11:36:04,267] Trial 54 finished with value: 0.9496345504072613 and parameters: {'solver': 'saga', 'C': 0.23573272240185852, 'l1_ratio': 0.9983438940689773, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0044851601708607615, 'max_iter': 1518}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  11%|█         | 54/500 [02:24<10:27,  1.41s/it]

[I 2026-05-18 11:36:06,154] Trial 61 pruned.

Best trial: 13. Best value: 0.949705:  11%|█         | 56/500 [02:25<06:54,  1.07it/s]

[I 2026-05-18 11:36:06,865] Trial 56 finished with value: 0.9496973663763058 and parameters: {'solver': 'saga', 'C': 0.004272910300273344, 'l1_ratio': 0.7546398896158746, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004572577746100162, 'max_iter': 2436}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:36:07,002] Trial 55 finished with value: 0.9496977167635086 and parameters: {'solver': 'saga', 'C': 0.005829039575137447, 'l1_ratio': 0.6743898489138049, 'class_weight': None, 'fit_intercept': True, 'tol': 0.003982384927036428, 'max_iter': 2375}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  11%|█▏        | 57/500 [02:28<11:33,  1.57s/it]

[I 2026-05-18 11:36:10,211] Trial 57 pruned.

Best trial: 13. Best value: 0.949705:  12%|█▏        | 58/500 [02:29<08:42,  1.18s/it]

[I 2026-05-18 11:36:10,435] Trial 23 finished with value: 0.9496280530800586 and parameters: {'solver': 'saga', 'C': 40.76819257613657, 'l1_ratio': 0.20985831946108896, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2169743389611203e-06, 'max_iter': 3689}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  12%|█▏        | 59/500 [02:30<09:32,  1.30s/it]

[I 2026-05-18 11:36:12,014] Trial 60 pruned.

Best trial: 13. Best value: 0.949705:  12%|█▏        | 60/500 [02:36<18:23,  2.51s/it]

[I 2026-05-18 11:36:17,443] Trial 64 finished with value: 0.9496935262371107 and parameters: {'solver': 'saga', 'C': 0.016073176720668034, 'l1_ratio': 0.7670893209216385, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0016146822105440252, 'max_iter': 3006}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  12%|█▏        | 61/500 [02:38<18:22,  2.51s/it]

[I 2026-05-18 11:36:19,965] Trial 69 finished with value: 0.9496928060755392 and parameters: {'solver': 'saga', 'C': 0.015806504457685524, 'l1_ratio': 0.9066821412940739, 'class_weight': None, 'fit_intercept': True, 'tol': 0.007154297827943181, 'max_iter': 3034}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  12%|█▏        | 62/500 [02:38<13:27,  1.84s/it]

[I 2026-05-18 11:36:20,221] Trial 68 finished with value: 0.9496896418314131 and parameters: {'solver': 'saga', 'C': 0.016577435736078387, 'l1_ratio': 0.8849699049894333, 'class_weight': None, 'fit_intercept': True, 'tol': 0.006548279861284252, 'max_iter': 2943}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  13%|█▎        | 63/500 [02:41<14:53,  2.04s/it]

[I 2026-05-18 11:36:22,743] Trial 70 finished with value: 0.9496915751100762 and parameters: {'solver': 'saga', 'C': 0.015363161213951265, 'l1_ratio': 0.8774015365137233, 'class_weight': None, 'fit_intercept': True, 'tol': 0.007341445976933462, 'max_iter': 2991}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  13%|█▎        | 64/500 [02:47<22:55,  3.16s/it]

[I 2026-05-18 11:36:28,513] Trial 62 finished with value: 0.949703765331307 and parameters: {'solver': 'saga', 'C': 0.003837463525701377, 'l1_ratio': 0.8867679466208404, 'class_weight': None, 'fit_intercept': True, 'tol': 3.405420195950819e-06, 'max_iter': 2962}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  13%|█▎        | 66/500 [02:47<12:07,  1.68s/it]

[I 2026-05-18 11:36:28,965] Trial 63 finished with value: 0.949700035826423 and parameters: {'solver': 'saga', 'C': 0.0128959230472194, 'l1_ratio': 0.8870062770618139, 'class_weight': None, 'fit_intercept': True, 'tol': 4.074181095718326e-06, 'max_iter': 2949}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:36:29,065] Trial 71 finished with value: 0.9495975161487993 and parameters: {'solver': 'saga', 'C': 0.0007280875318641047, 'l1_ratio': 0.6037747001091158, 'class_weight': None, 'fit_intercept': True, 'tol': 0.006752735339511443, 'max_iter': 2960}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  13%|█▎        | 67/500 [02:47<08:56,  1.24s/it]

[I 2026-05-18 11:36:29,273] Trial 73 finished with value: 0.9497035281333627 and parameters: {'solver': 'saga', 'C': 0.009072100218280664, 'l1_ratio': 0.6532344229644339, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00981370054697263, 'max_iter': 2323}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  14%|█▎        | 68/500 [02:50<12:31,  1.74s/it]

[I 2026-05-18 11:36:32,191] Trial 21 finished with value: 0.9495887643258735 and parameters: {'solver': 'saga', 'C': 6.4746448235366865, 'l1_ratio': 0.611580470316083, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.4369812579109454e-06, 'max_iter': 4958}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  14%|█▍        | 69/500 [02:51<10:08,  1.41s/it]

[I 2026-05-18 11:36:32,841] Trial 65 finished with value: 0.9496974616179754 and parameters: {'solver': 'saga', 'C': 0.013924945286144385, 'l1_ratio': 0.8753599261374498, 'class_weight': None, 'fit_intercept': True, 'tol': 3.5218487037418565e-06, 'max_iter': 3085}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  14%|█▍        | 70/500 [02:52<09:06,  1.27s/it]

[I 2026-05-18 11:36:33,779] Trial 66 finished with value: 0.9496866879649286 and parameters: {'solver': 'saga', 'C': 0.018773344738060863, 'l1_ratio': 0.8791919444855416, 'class_weight': None, 'fit_intercept': True, 'tol': 2.3441907402259594e-06, 'max_iter': 3303}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  14%|█▍        | 71/500 [02:52<06:56,  1.03it/s]

[I 2026-05-18 11:36:34,049] Trial 67 finished with value: 0.9496999914073687 and parameters: {'solver': 'saga', 'C': 0.01274835423544471, 'l1_ratio': 0.8960696635121056, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2520174361761527e-06, 'max_iter': 2930}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  14%|█▍        | 72/500 [02:54<09:20,  1.31s/it]

[I 2026-05-18 11:36:36,146] Trial 72 finished with value: 0.9495918086887848 and parameters: {'solver': 'saga', 'C': 0.0006857396151078995, 'l1_ratio': 0.6081816976537427, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003585853807713526, 'max_iter': 2253}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  15%|█▍        | 73/500 [02:58<13:30,  1.90s/it]

[I 2026-05-18 11:36:39,420] Trial 74 finished with value: 0.9496409360158576 and parameters: {'solver': 'saga', 'C': 0.0006363415070041877, 'l1_ratio': 0.6599516198785723, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003531614004337769, 'max_iter': 2284}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  15%|█▍        | 74/500 [03:02<18:43,  2.64s/it]

[I 2026-05-18 11:36:43,785] Trial 6 pruned.

Best trial: 13. Best value: 0.949705:  15%|█▌        | 75/500 [03:12<33:22,  4.71s/it]

[I 2026-05-18 11:36:53,335] Trial 75 finished with value: 0.9496327064847192 and parameters: {'solver': 'saga', 'C': 0.0009341227804527061, 'l1_ratio': 0.604445582888817, 'class_weight': None, 'fit_intercept': True, 'tol': 8.256392899209168e-06, 'max_iter': 2536}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  15%|█▌        | 76/500 [03:14<29:04,  4.11s/it]

[I 2026-05-18 11:36:56,053] Trial 76 finished with value: 0.9496986005191008 and parameters: {'solver': 'saga', 'C': 0.009567388691228244, 'l1_ratio': 0.9384523715055569, 'class_weight': None, 'fit_intercept': True, 'tol': 1.972537729469877e-06, 'max_iter': 3186}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  15%|█▌        | 77/500 [03:16<22:51,  3.24s/it]

[I 2026-05-18 11:36:57,257] Trial 77 finished with value: 0.9496995451402551 and parameters: {'solver': 'saga', 'C': 0.010065177146299384, 'l1_ratio': 0.9442932947264991, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9572188051664407e-06, 'max_iter': 3375}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:36:57,341] Trial 78 finished with value: 0.9496995345778136 and parameters: {'solver': 'saga', 'C': 0.009192001835260939, 'l1_ratio': 0.9241056134734356, 'class_weight': None, 'fit_intercept': True, 'tol': 1.993818755530922e-06, 'max_iter': 3316}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  16%|█▌        | 79/500 [03:16<12:36,  1.80s/it]

[I 2026-05-18 11:36:57,483] Trial 79 finished with value: 0.9497026008006714 and parameters: {'solver': 'saga', 'C': 0.01019341140054644, 'l1_ratio': 0.5357247071609011, 'class_weight': None, 'fit_intercept': True, 'tol': 5.0849208334935795e-06, 'max_iter': 1000}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  16%|█▌        | 80/500 [03:17<12:28,  1.78s/it]

[I 2026-05-18 11:36:59,218] Trial 81 finished with value: 0.9497049481119682 and parameters: {'solver': 'saga', 'C': 0.0027290669167058714, 'l1_ratio': 0.938428006943228, 'class_weight': None, 'fit_intercept': True, 'tol': 4.431782175378385e-06, 'max_iter': 3460}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  16%|█▌        | 81/500 [03:18<10:57,  1.57s/it]

[I 2026-05-18 11:37:00,187] Trial 80 finished with value: 0.94970511518191 and parameters: {'solver': 'saga', 'C': 0.0022636181748603075, 'l1_ratio': 0.9426768792759703, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1105900862516162e-06, 'max_iter': 3436}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  16%|█▋        | 82/500 [03:19<08:34,  1.23s/it]

[I 2026-05-18 11:37:00,492] Trial 82 finished with value: 0.9496990366360951 and parameters: {'solver': 'saga', 'C': 0.009694196491048641, 'l1_ratio': 0.9374171542822429, 'class_weight': None, 'fit_intercept': True, 'tol': 4.811612259689571e-06, 'max_iter': 3416}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  17%|█▋        | 83/500 [03:21<09:59,  1.44s/it]

[I 2026-05-18 11:37:02,488] Trial 83 finished with value: 0.9497034933232046 and parameters: {'solver': 'saga', 'C': 0.009051217965736075, 'l1_ratio': 0.8035975264240421, 'class_weight': None, 'fit_intercept': True, 'tol': 5.875523761894898e-06, 'max_iter': 3451}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  17%|█▋        | 84/500 [03:23<10:59,  1.59s/it]

[I 2026-05-18 11:37:04,440] Trial 84 finished with value: 0.9496984480934498 and parameters: {'solver': 'saga', 'C': 0.009837431301216592, 'l1_ratio': 0.949940828533144, 'class_weight': None, 'fit_intercept': True, 'tol': 5.0224270421191284e-06, 'max_iter': 3419}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  17%|█▋        | 85/500 [03:27<16:33,  2.39s/it]

[I 2026-05-18 11:37:08,809] Trial 85 finished with value: 0.9496993829699134 and parameters: {'solver': 'saga', 'C': 0.008653107244841465, 'l1_ratio': 0.9334054097630441, 'class_weight': None, 'fit_intercept': True, 'tol': 4.543448525360048e-06, 'max_iter': 2555}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  17%|█▋        | 86/500 [03:38<34:26,  4.99s/it]

[I 2026-05-18 11:37:20,085] Trial 86 finished with value: 0.9496984121514329 and parameters: {'solver': 'saga', 'C': 0.00922849341535591, 'l1_ratio': 0.9424770851694964, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5558893995299445e-06, 'max_iter': 3389}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  17%|█▋        | 87/500 [03:40<27:09,  3.94s/it]

[I 2026-05-18 11:37:21,518] Trial 89 finished with value: 0.9496938592198007 and parameters: {'solver': 'saga', 'C': 0.0025678711435312123, 'l1_ratio': 0.806401863142978, 'class_weight': None, 'fit_intercept': True, 'tol': 4.747790919114293e-06, 'max_iter': 3475}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:37:21,525] Trial 87 finished with value: 0.9497051581252383 and parameters: {'solver': 'saga', 'C': 0.0023610213660164928, 'l1_ratio': 0.9460449089220041, 'class_weight': None, 'fit_intercept': True, 'tol': 4.4612264519402575e-06, 'max_iter': 3458}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  18%|█▊        | 89/500 [03:41<16:42,  2.44s/it]

[I 2026-05-18 11:37:22,828] Trial 88 finished with value: 0.94968824726735 and parameters: {'solver': 'saga', 'C': 0.002010655246199585, 'l1_ratio': 0.7943221019343759, 'class_weight': None, 'fit_intercept': True, 'tol': 4.355312824522606e-06, 'max_iter': 2841}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  18%|█▊        | 90/500 [03:41<13:06,  1.92s/it]

[I 2026-05-18 11:37:23,158] Trial 93 finished with value: 0.9496784803815898 and parameters: {'solver': 'saga', 'C': 0.002901845538632847, 'l1_ratio': 0.5406477913080152, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1293674107290764e-05, 'max_iter': 4105}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  18%|█▊        | 91/500 [03:42<11:12,  1.64s/it]

[I 2026-05-18 11:37:24,015] Trial 90 finished with value: 0.9496226792362303 and parameters: {'solver': 'saga', 'C': 0.0026252434081722883, 'l1_ratio': 0.5156475446723028, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.679561232363007e-06, 'max_iter': 2838}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  18%|█▊        | 92/500 [03:44<10:39,  1.57s/it]

[I 2026-05-18 11:37:25,378] Trial 92 finished with value: 0.9496497732002401 and parameters: {'solver': 'saga', 'C': 0.0023614949111205427, 'l1_ratio': 0.4022218129962861, 'class_weight': None, 'fit_intercept': True, 'tol': 5.70969803502117e-06, 'max_iter': 1035}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  19%|█▊        | 93/500 [03:46<12:20,  1.82s/it]

[I 2026-05-18 11:37:27,847] Trial 91 finished with value: 0.9496126453358513 and parameters: {'solver': 'saga', 'C': 0.0024196275076355882, 'l1_ratio': 0.49318608867453967, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.0317690636804056e-06, 'max_iter': 4211}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  19%|█▉        | 94/500 [03:48<12:31,  1.85s/it]

[I 2026-05-18 11:37:29,778] Trial 95 finished with value: 0.9496176011139088 and parameters: {'solver': 'saga', 'C': 0.0025641938269492072, 'l1_ratio': 0.4969986045537569, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.0458372195534588e-05, 'max_iter': 3829}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  19%|█▉        | 95/500 [03:48<09:39,  1.43s/it]

[I 2026-05-18 11:37:30,179] Trial 94 finished with value: 0.9496753520712607 and parameters: {'solver': 'saga', 'C': 0.0025816066992341417, 'l1_ratio': 0.527216887741874, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0233726330629127e-06, 'max_iter': 4051}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  19%|█▉        | 96/500 [03:51<12:37,  1.87s/it]

[I 2026-05-18 11:37:33,114] Trial 96 finished with value: 0.9496088866602992 and parameters: {'solver': 'saga', 'C': 0.002043616599104177, 'l1_ratio': 0.5261245168738283, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.7735097665276835e-05, 'max_iter': 1005}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  19%|█▉        | 97/500 [04:03<32:31,  4.84s/it]

[I 2026-05-18 11:37:45,073] Trial 98 finished with value: 0.9495319793716632 and parameters: {'solver': 'saga', 'C': 0.0015176160217089609, 'l1_ratio': 0.4411084200030752, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.800152055524818e-05, 'max_iter': 3795}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  20%|█▉        | 98/500 [04:05<27:18,  4.08s/it]

[I 2026-05-18 11:37:47,317] Trial 102 finished with value: 0.9496903553180689 and parameters: {'solver': 'saga', 'C': 0.0015014934189651076, 'l1_ratio': 0.8580443893579986, 'class_weight': None, 'fit_intercept': True, 'tol': 7.868302937240302e-06, 'max_iter': 3868}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  20%|█▉        | 99/500 [04:06<20:57,  3.14s/it]

[I 2026-05-18 11:37:48,238] Trial 101 finished with value: 0.9495726063772348 and parameters: {'solver': 'saga', 'C': 0.001319002874420982, 'l1_ratio': 0.4569798746577832, 'class_weight': None, 'fit_intercept': True, 'tol': 6.809259771291737e-06, 'max_iter': 4619}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:37:48,270] Trial 100 finished with value: 0.9495539974932157 and parameters: {'solver': 'saga', 'C': 0.0013949299279413978, 'l1_ratio': 0.5035336210513937, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.77314944653203e-06, 'max_iter': 3806}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  20%|██        | 101/500 [04:07<11:48,  1.77s/it]

[I 2026-05-18 11:37:48,588] Trial 103 finished with value: 0.949705428649122 and parameters: {'solver': 'saga', 'C': 0.0017114263899246026, 'l1_ratio': 0.9786692964146102, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6796688916542258e-05, 'max_iter': 3761}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  20%|██        | 102/500 [04:08<10:45,  1.62s/it]

[I 2026-05-18 11:37:49,739] Trial 97 finished with value: 0.9496482525621195 and parameters: {'solver': 'saga', 'C': 0.0018132233318489627, 'l1_ratio': 0.48634273443540477, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0825615886826326e-06, 'max_iter': 1000}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  21%|██        | 103/500 [04:08<08:26,  1.28s/it]

[I 2026-05-18 11:37:50,036] Trial 99 finished with value: 0.9495456572091141 and parameters: {'solver': 'saga', 'C': 0.001237734292061912, 'l1_ratio': 0.5198534671032136, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.0302299065791255e-06, 'max_iter': 3796}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  21%|██        | 104/500 [04:09<08:16,  1.25s/it]

[I 2026-05-18 11:37:51,232] Trial 104 finished with value: 0.9496773969857403 and parameters: {'solver': 'saga', 'C': 0.026831459239879955, 'l1_ratio': 0.7277317847492586, 'class_weight': None, 'fit_intercept': True, 'tol': 9.776089185704543e-06, 'max_iter': 3805}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  21%|██        | 105/500 [04:10<07:36,  1.16s/it]

[I 2026-05-18 11:37:52,140] Trial 106 finished with value: 0.9496871129804225 and parameters: {'solver': 'saga', 'C': 0.0013127105203932458, 'l1_ratio': 0.8521053918249007, 'class_weight': None, 'fit_intercept': True, 'tol': 2.04669041449124e-05, 'max_iter': 3729}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  21%|██        | 106/500 [04:12<08:17,  1.26s/it]

[I 2026-05-18 11:37:53,661] Trial 115 pruned.

Best trial: 13. Best value: 0.949705:  21%|██▏       | 107/500 [04:15<11:19,  1.73s/it]

[I 2026-05-18 11:37:56,540] Trial 107 finished with value: 0.9496697523277715 and parameters: {'solver': 'saga', 'C': 0.0010149506397875896, 'l1_ratio': 0.7292333339768825, 'class_weight': None, 'fit_intercept': True, 'tol': 7.932430606287723e-06, 'max_iter': 3803}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  22%|██▏       | 108/500 [04:19<15:15,  2.34s/it]

[I 2026-05-18 11:38:00,333] Trial 118 pruned.

Best trial: 13. Best value: 0.949705:  22%|██▏       | 109/500 [04:24<21:26,  3.29s/it]

[I 2026-05-18 11:38:05,910] Trial 109 finished with value: 0.949680744891995 and parameters: {'solver': 'saga', 'C': 0.024733560053476593, 'l1_ratio': 0.650010428978113, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012016537035906328, 'max_iter': 4600}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  22%|██▏       | 110/500 [04:24<15:50,  2.44s/it]

[I 2026-05-18 11:38:06,329] Trial 117 pruned.

Best trial: 13. Best value: 0.949705:  22%|██▏       | 111/500 [04:27<15:43,  2.43s/it]

[I 2026-05-18 11:38:08,715] Trial 108 finished with value: 0.9496675502559674 and parameters: {'solver': 'saga', 'C': 0.0012364103731739105, 'l1_ratio': 0.6444793879094217, 'class_weight': None, 'fit_intercept': True, 'tol': 7.552310081162281e-06, 'max_iter': 3662}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  22%|██▏       | 112/500 [04:31<18:11,  2.81s/it]

[I 2026-05-18 11:38:12,447] Trial 105 finished with value: 0.9496765112102953 and parameters: {'solver': 'saga', 'C': 0.023865957410071883, 'l1_ratio': 0.9684686055487628, 'class_weight': None, 'fit_intercept': True, 'tol': 7.1468002021884195e-06, 'max_iter': 3762}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  23%|██▎       | 113/500 [04:32<16:09,  2.51s/it]

[I 2026-05-18 11:38:14,229] Trial 111 finished with value: 0.9496760414640694 and parameters: {'solver': 'saga', 'C': 0.02782788711240269, 'l1_ratio': 0.721197960093139, 'class_weight': None, 'fit_intercept': True, 'tol': 3.568208972840913e-06, 'max_iter': 3687}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  23%|██▎       | 114/500 [04:45<36:12,  5.63s/it]

[I 2026-05-18 11:38:27,179] Trial 119 finished with value: 0.9496522553419782 and parameters: {'solver': 'saga', 'C': 0.06611090458009491, 'l1_ratio': 0.650582518508058, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6498840868790037e-06, 'max_iter': 3562}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  23%|██▎       | 115/500 [04:51<36:59,  5.77s/it]

[I 2026-05-18 11:38:33,261] Trial 122 finished with value: 0.9496981512293379 and parameters: {'solver': 'saga', 'C': 0.00657431528993122, 'l1_ratio': 0.9678261329513621, 'class_weight': None, 'fit_intercept': True, 'tol': 3.5594497649954753e-06, 'max_iter': 3146}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  23%|██▎       | 116/500 [04:55<33:36,  5.25s/it]

[I 2026-05-18 11:38:37,316] Trial 123 finished with value: 0.9497033145616974 and parameters: {'solver': 'saga', 'C': 0.006871523653000847, 'l1_ratio': 0.8166825573029992, 'class_weight': None, 'fit_intercept': True, 'tol': 3.770229786315197e-06, 'max_iter': 3144}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  24%|██▎       | 118/500 [04:58<19:48,  3.11s/it]

[I 2026-05-18 11:38:39,694] Trial 114 finished with value: 0.9496765645645796 and parameters: {'solver': 'saga', 'C': 0.023745257923921542, 'l1_ratio': 0.9718744266020989, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6970146722508844e-06, 'max_iter': 3691}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:38:39,814] Trial 110 finished with value: 0.9496773990538372 and parameters: {'solver': 'saga', 'C': 0.02299339922686738, 'l1_ratio': 0.9739692532222272, 'class_weight': None, 'fit_intercept': True, 'tol': 2.7704381373658114e-06, 'max_iter': 3658}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  24%|██▍       | 119/500 [05:00<17:40,  2.78s/it]

[I 2026-05-18 11:38:41,827] Trial 124 finished with value: 0.9497022118119309 and parameters: {'solver': 'saga', 'C': 0.006808043536631733, 'l1_ratio': 0.9102978237805496, 'class_weight': None, 'fit_intercept': True, 'tol': 3.5955218808754347e-06, 'max_iter': 3184}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  24%|██▍       | 120/500 [05:01<14:31,  2.29s/it]

[I 2026-05-18 11:38:42,983] Trial 112 finished with value: 0.9496748742676099 and parameters: {'solver': 'saga', 'C': 0.024882479091440562, 'l1_ratio': 0.9727509494957255, 'class_weight': None, 'fit_intercept': True, 'tol': 2.7260511656993627e-06, 'max_iter': 3705}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  24%|██▍       | 121/500 [05:07<20:32,  3.25s/it]

[I 2026-05-18 11:38:48,470] Trial 116 finished with value: 0.9496755674015332 and parameters: {'solver': 'saga', 'C': 0.024359710270261497, 'l1_ratio': 0.9745921745287001, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6700655394662845e-06, 'max_iter': 3553}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  24%|██▍       | 122/500 [05:11<21:59,  3.49s/it]

[I 2026-05-18 11:38:52,519] Trial 125 finished with value: 0.9497028005255723 and parameters: {'solver': 'saga', 'C': 0.00717010098436646, 'l1_ratio': 0.7774129609956353, 'class_weight': None, 'fit_intercept': True, 'tol': 3.6386543217449695e-06, 'max_iter': 3147}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  25%|██▍       | 123/500 [05:18<28:48,  4.58s/it]

[I 2026-05-18 11:38:59,649] Trial 126 finished with value: 0.9496981811941888 and parameters: {'solver': 'saga', 'C': 0.0038953921267311817, 'l1_ratio': 0.7825536302042885, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6462988321295556e-06, 'max_iter': 3249}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  25%|██▍       | 124/500 [05:23<29:45,  4.75s/it]

[I 2026-05-18 11:39:04,773] Trial 127 finished with value: 0.949704369491565 and parameters: {'solver': 'saga', 'C': 0.0035336368826676423, 'l1_ratio': 0.912071249975031, 'class_weight': None, 'fit_intercept': True, 'tol': 1.431540047945643e-06, 'max_iter': 3266}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  25%|██▌       | 126/500 [05:24<15:55,  2.56s/it]

[I 2026-05-18 11:39:05,616] Trial 113 finished with value: 0.9496739462364527 and parameters: {'solver': 'saga', 'C': 0.02524671869143687, 'l1_ratio': 0.9833188669858374, 'class_weight': None, 'fit_intercept': True, 'tol': 3.612213446021033e-06, 'max_iter': 3689}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:39:05,792] Trial 128 finished with value: 0.9497033116338619 and parameters: {'solver': 'saga', 'C': 0.007146170313727782, 'l1_ratio': 0.8120898540500321, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4932226829659444e-06, 'max_iter': 3254}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  25%|██▌       | 127/500 [05:24<11:57,  1.92s/it]

[I 2026-05-18 11:39:06,228] Trial 129 finished with value: 0.9496988975913349 and parameters: {'solver': 'saga', 'C': 0.004226470620693704, 'l1_ratio': 0.7775767742947288, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6799207941107665e-06, 'max_iter': 3256}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  26%|██▌       | 128/500 [05:27<13:29,  2.18s/it]

[I 2026-05-18 11:39:09,001] Trial 130 finished with value: 0.9496541923890194 and parameters: {'solver': 'saga', 'C': 0.056787550501030966, 'l1_ratio': 0.8088900703589943, 'class_weight': None, 'fit_intercept': True, 'tol': 1.679901050970877e-06, 'max_iter': 1968}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  26%|██▌       | 129/500 [05:29<13:18,  2.15s/it]

[I 2026-05-18 11:39:11,111] Trial 131 finished with value: 0.9496104020255108 and parameters: {'solver': 'saga', 'C': 0.0035369561424552784, 'l1_ratio': 0.07801542726542493, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7485268588541386e-06, 'max_iter': 3098}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  26%|██▌       | 130/500 [05:33<16:55,  2.74s/it]

[I 2026-05-18 11:39:15,236] Trial 132 finished with value: 0.9497041842014339 and parameters: {'solver': 'saga', 'C': 0.004084725915549517, 'l1_ratio': 0.9104691335793366, 'class_weight': None, 'fit_intercept': True, 'tol': 3.6184930421356397e-06, 'max_iter': 3279}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  26%|██▌       | 131/500 [05:39<21:17,  3.46s/it]

[I 2026-05-18 11:39:20,375] Trial 134 finished with value: 0.9497013065742408 and parameters: {'solver': 'saga', 'C': 0.003801543298314227, 'l1_ratio': 0.8338564494016952, 'class_weight': None, 'fit_intercept': True, 'tol': 5.148396080715173e-05, 'max_iter': 1957}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  26%|██▋       | 132/500 [05:39<15:24,  2.51s/it]

[I 2026-05-18 11:39:20,670] Trial 133 finished with value: 0.9497017861190308 and parameters: {'solver': 'saga', 'C': 0.005022522473210808, 'l1_ratio': 0.8014827168901748, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5701169268722354e-06, 'max_iter': 3092}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  27%|██▋       | 133/500 [05:43<19:06,  3.12s/it]

[I 2026-05-18 11:39:25,219] Trial 140 finished with value: 0.9497029363610163 and parameters: {'solver': 'saga', 'C': 0.005095597547534557, 'l1_ratio': 0.831625397710258, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000713728693504127, 'max_iter': 3515}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  27%|██▋       | 134/500 [05:49<23:44,  3.89s/it]

[I 2026-05-18 11:39:30,902] Trial 135 finished with value: 0.949702146433764 and parameters: {'solver': 'saga', 'C': 0.004922039135461001, 'l1_ratio': 0.812711116462808, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7162891609487252e-06, 'max_iter': 1257}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  27%|██▋       | 135/500 [05:51<19:59,  3.29s/it]

[I 2026-05-18 11:39:32,773] Trial 138 finished with value: 0.9497024925966144 and parameters: {'solver': 'saga', 'C': 0.005353245596466182, 'l1_ratio': 0.8129953456742529, 'class_weight': None, 'fit_intercept': True, 'tol': 1.246836894730512e-06, 'max_iter': 3058}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:39:32,846] Trial 136 finished with value: 0.9496999116798858 and parameters: {'solver': 'saga', 'C': 0.0036472556795924507, 'l1_ratio': 0.8188546477478996, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8771154103464744e-06, 'max_iter': 3079}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  27%|██▋       | 137/500 [05:53<12:55,  2.14s/it]

[I 2026-05-18 11:39:34,368] Trial 137 finished with value: 0.949700440518748 and parameters: {'solver': 'saga', 'C': 0.004088136313177564, 'l1_ratio': 0.8079596901335689, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3243992975764892e-06, 'max_iter': 3332}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  28%|██▊       | 138/500 [05:55<13:33,  2.25s/it]

[I 2026-05-18 11:39:36,949] Trial 121 finished with value: 0.9496512116212928 and parameters: {'solver': 'saga', 'C': 0.05821855334103827, 'l1_ratio': 0.9719380751372019, 'class_weight': None, 'fit_intercept': True, 'tol': 3.4320746711558594e-06, 'max_iter': 3165}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  28%|██▊       | 139/500 [05:56<10:49,  1.80s/it]

[I 2026-05-18 11:39:37,489] Trial 139 finished with value: 0.9497001005422563 and parameters: {'solver': 'saga', 'C': 0.0034079506025545716, 'l1_ratio': 0.8321704328790146, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2803924834009591e-06, 'max_iter': 3063}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  28%|██▊       | 140/500 [05:58<12:18,  2.05s/it]

[I 2026-05-18 11:39:40,206] Trial 141 finished with value: 0.9496745023620539 and parameters: {'solver': 'saga', 'C': 0.00048028857597184226, 'l1_ratio': 0.9086529828779359, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1388833330535943e-06, 'max_iter': 3471}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  28%|██▊       | 141/500 [06:04<18:06,  3.03s/it]

[I 2026-05-18 11:39:45,745] Trial 145 finished with value: 0.9497019398478306 and parameters: {'solver': 'saga', 'C': 0.0033539457383823384, 'l1_ratio': 0.8602286991043554, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006061369724820117, 'max_iter': 3479}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:39:45,760] Trial 142 finished with value: 0.9497033417259235 and parameters: {'solver': 'saga', 'C': 0.005226477648984183, 'l1_ratio': 0.9130137063576758, 'class_weight': None, 'fit_intercept': True, 'tol': 2.3531854485080083e-06, 'max_iter': 3363}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  29%|██▊       | 143/500 [06:06<12:31,  2.10s/it]

[I 2026-05-18 11:39:47,649] Trial 143 finished with value: 0.9497032587597362 and parameters: {'solver': 'saga', 'C': 0.006894345739424263, 'l1_ratio': 0.8620018648895461, 'class_weight': None, 'fit_intercept': True, 'tol': 1.291875529717575e-06, 'max_iter': 3450}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  29%|██▉       | 144/500 [06:07<11:32,  1.94s/it]

[I 2026-05-18 11:39:49,087] Trial 147 finished with value: 0.9497018931905504 and parameters: {'solver': 'saga', 'C': 0.012581637623623146, 'l1_ratio': 0.8544907414929622, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006306865120904726, 'max_iter': 3461}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  29%|██▉       | 145/500 [06:09<10:42,  1.81s/it]

[I 2026-05-18 11:39:50,504] Trial 149 finished with value: 0.9497043325671038 and parameters: {'solver': 'saga', 'C': 0.0029670678970964747, 'l1_ratio': 0.9173235033761267, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014270962720945401, 'max_iter': 3465}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  29%|██▉       | 146/500 [06:11<11:03,  1.87s/it]

[I 2026-05-18 11:39:52,538] Trial 144 finished with value: 0.9497015474927413 and parameters: {'solver': 'saga', 'C': 0.0031335108341946395, 'l1_ratio': 0.8620600930608969, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3423394743265633e-06, 'max_iter': 3434}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  29%|██▉       | 147/500 [06:11<09:03,  1.54s/it]

[I 2026-05-18 11:39:53,205] Trial 151 finished with value: 0.9497010420767513 and parameters: {'solver': 'saga', 'C': 0.012155970286330168, 'l1_ratio': 0.9130295995032477, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0015392096961864947, 'max_iter': 3479}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  30%|██▉       | 148/500 [06:20<21:13,  3.62s/it]

[I 2026-05-18 11:40:02,097] Trial 148 finished with value: 0.9497012234828013 and parameters: {'solver': 'saga', 'C': 0.012657403749716151, 'l1_ratio': 0.8645132663389429, 'class_weight': None, 'fit_intercept': True, 'tol': 2.187557056125242e-06, 'max_iter': 3442}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  30%|██▉       | 149/500 [06:21<15:28,  2.65s/it]

[I 2026-05-18 11:40:02,331] Trial 146 finished with value: 0.9497016101187699 and parameters: {'solver': 'saga', 'C': 0.0032135448985450483, 'l1_ratio': 0.859851651500023, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3547227964465945e-06, 'max_iter': 3472}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  30%|███       | 150/500 [06:21<11:39,  2.00s/it]

[I 2026-05-18 11:40:02,765] Trial 153 finished with value: 0.9496999678079174 and parameters: {'solver': 'saga', 'C': 0.012513324552530326, 'l1_ratio': 0.9191335159514936, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00025046113822633386, 'max_iter': 3360}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  30%|███       | 151/500 [06:23<11:55,  2.05s/it]

[I 2026-05-18 11:40:04,936] Trial 150 finished with value: 0.9496994747553057 and parameters: {'solver': 'saga', 'C': 0.012611723564655664, 'l1_ratio': 0.9259999392034495, 'class_weight': None, 'fit_intercept': True, 'tol': 2.221879208598746e-06, 'max_iter': 3446}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  30%|███       | 152/500 [06:24<10:37,  1.83s/it]

[I 2026-05-18 11:40:06,248] Trial 157 finished with value: 0.9497021736166407 and parameters: {'solver': 'saga', 'C': 0.0019224970274264017, 'l1_ratio': 0.9140981902071977, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0016703334002114232, 'max_iter': 3317}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  31%|███       | 153/500 [06:28<13:31,  2.34s/it]

[I 2026-05-18 11:40:09,789] Trial 160 pruned.

Best trial: 13. Best value: 0.949705:  31%|███       | 154/500 [06:28<10:01,  1.74s/it]

[I 2026-05-18 11:40:10,113] Trial 158 finished with value: 0.9497028880664156 and parameters: {'solver': 'saga', 'C': 0.001970572723530205, 'l1_ratio': 0.9193473870100802, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00027274576032963955, 'max_iter': 3320}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  31%|███       | 155/500 [06:29<08:52,  1.54s/it]

[I 2026-05-18 11:40:11,201] Trial 159 pruned.

Best trial: 13. Best value: 0.949705:  31%|███       | 156/500 [06:30<07:21,  1.28s/it]

[I 2026-05-18 11:40:11,873] Trial 152 finished with value: 0.9497015505527682 and parameters: {'solver': 'saga', 'C': 0.007088621350615037, 'l1_ratio': 0.920931872754384, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2881749531276263e-06, 'max_iter': 3397}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  31%|███▏      | 157/500 [06:31<06:16,  1.10s/it]

[I 2026-05-18 11:40:12,534] Trial 161 pruned.

Best trial: 13. Best value: 0.949705:  32%|███▏      | 158/500 [06:33<07:30,  1.32s/it]

[I 2026-05-18 11:40:14,355] Trial 154 finished with value: 0.9497017540672857 and parameters: {'solver': 'saga', 'C': 0.011581117423895273, 'l1_ratio': 0.9239540702778908, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2667934266884414e-06, 'max_iter': 3388}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  32%|███▏      | 159/500 [06:35<09:10,  1.61s/it]

[I 2026-05-18 11:40:16,670] Trial 155 finished with value: 0.9497009587583858 and parameters: {'solver': 'saga', 'C': 0.007592931431382671, 'l1_ratio': 0.9231160475344508, 'class_weight': None, 'fit_intercept': True, 'tol': 2.253448476237727e-06, 'max_iter': 3351}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  32%|███▏      | 160/500 [06:37<09:23,  1.66s/it]

[I 2026-05-18 11:40:18,427] Trial 156 finished with value: 0.9497032197512351 and parameters: {'solver': 'saga', 'C': 0.001878822814028932, 'l1_ratio': 0.9244424130920309, 'class_weight': None, 'fit_intercept': True, 'tol': 2.239348781084651e-06, 'max_iter': 3329}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  32%|███▏      | 161/500 [06:46<23:09,  4.10s/it]

[I 2026-05-18 11:40:28,232] Trial 162 finished with value: 0.9497003175567256 and parameters: {'solver': 'saga', 'C': 0.0018664882057540387, 'l1_ratio': 0.900841320482566, 'class_weight': None, 'fit_intercept': True, 'tol': 4.173938144741897e-06, 'max_iter': 3255}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  32%|███▏      | 162/500 [06:52<26:15,  4.66s/it]

[I 2026-05-18 11:40:34,190] Trial 163 finished with value: 0.9497016260330368 and parameters: {'solver': 'saga', 'C': 0.008107740145131723, 'l1_ratio': 0.898319851662834, 'class_weight': None, 'fit_intercept': True, 'tol': 2.310304489488596e-06, 'max_iter': 3280}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  33%|███▎      | 163/500 [06:53<19:28,  3.47s/it]

[I 2026-05-18 11:40:34,883] Trial 165 finished with value: 0.949699024606357 and parameters: {'solver': 'saga', 'C': 0.007168007996237776, 'l1_ratio': 0.9529948822296154, 'class_weight': None, 'fit_intercept': True, 'tol': 4.172651934418531e-06, 'max_iter': 3570}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  33%|███▎      | 164/500 [06:54<14:49,  2.65s/it]

[I 2026-05-18 11:40:35,620] Trial 164 finished with value: 0.949702095012762 and parameters: {'solver': 'saga', 'C': 0.00772871530603507, 'l1_ratio': 0.8956006711254236, 'class_weight': None, 'fit_intercept': True, 'tol': 5.227175997758306e-06, 'max_iter': 3250}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  33%|███▎      | 165/500 [06:55<11:44,  2.10s/it]

[I 2026-05-18 11:40:36,453] Trial 168 finished with value: 0.9496985017830248 and parameters: {'solver': 'saga', 'C': 0.0081381729894, 'l1_ratio': 0.9507341738026673, 'class_weight': None, 'fit_intercept': True, 'tol': 4.33605721949809e-06, 'max_iter': 3214}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  33%|███▎      | 166/500 [06:55<08:51,  1.59s/it]

[I 2026-05-18 11:40:36,841] Trial 167 finished with value: 0.9497024860744683 and parameters: {'solver': 'saga', 'C': 0.007313400706361675, 'l1_ratio': 0.889376348060703, 'class_weight': None, 'fit_intercept': True, 'tol': 5.937156508606402e-06, 'max_iter': 3251}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  33%|███▎      | 167/500 [06:56<07:00,  1.26s/it]

[I 2026-05-18 11:40:37,343] Trial 166 finished with value: 0.9497022088823606 and parameters: {'solver': 'saga', 'C': 0.007697179261930237, 'l1_ratio': 0.8920544854109359, 'class_weight': None, 'fit_intercept': True, 'tol': 4.331744773809312e-06, 'max_iter': 3604}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  34%|███▎      | 168/500 [06:57<07:34,  1.37s/it]

[I 2026-05-18 11:40:38,963] Trial 169 finished with value: 0.9497002517936203 and parameters: {'solver': 'saga', 'C': 0.006076592950300291, 'l1_ratio': 0.9516968648705196, 'class_weight': None, 'fit_intercept': True, 'tol': 5.849612407080264e-06, 'max_iter': 3604}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  34%|███▍      | 169/500 [07:00<10:43,  1.94s/it]

[I 2026-05-18 11:40:42,243] Trial 170 finished with value: 0.9496985362689874 and parameters: {'solver': 'saga', 'C': 0.007953189679134647, 'l1_ratio': 0.9518112604656702, 'class_weight': None, 'fit_intercept': True, 'tol': 4.313711223839516e-06, 'max_iter': 3973}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  34%|███▍      | 170/500 [07:03<11:13,  2.04s/it]

[I 2026-05-18 11:40:44,513] Trial 171 finished with value: 0.9496999558961979 and parameters: {'solver': 'saga', 'C': 0.0067583680849951895, 'l1_ratio': 0.9463064075127937, 'class_weight': None, 'fit_intercept': True, 'tol': 4.228812933713297e-06, 'max_iter': 3596}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  34%|███▍      | 171/500 [07:12<23:45,  4.33s/it]

[I 2026-05-18 11:40:54,194] Trial 172 finished with value: 0.9496986231349535 and parameters: {'solver': 'saga', 'C': 0.007496418690035001, 'l1_ratio': 0.955777038335487, 'class_weight': None, 'fit_intercept': True, 'tol': 3.0530056541918765e-06, 'max_iter': 3620}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  34%|███▍      | 172/500 [07:18<25:57,  4.75s/it]

[I 2026-05-18 11:40:59,915] Trial 173 finished with value: 0.9496997214877693 and parameters: {'solver': 'saga', 'C': 0.006178341390351659, 'l1_ratio': 0.9562947516357722, 'class_weight': None, 'fit_intercept': True, 'tol': 4.246612193506157e-06, 'max_iter': 3598}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  35%|███▍      | 173/500 [07:19<19:02,  3.49s/it]

[I 2026-05-18 11:41:00,486] Trial 175 finished with value: 0.9497044347175606 and parameters: {'solver': 'saga', 'C': 0.002828143010465298, 'l1_ratio': 0.9582015804005006, 'class_weight': None, 'fit_intercept': True, 'tol': 3.2973443102259534e-06, 'max_iter': 3595}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  35%|███▍      | 174/500 [07:19<13:49,  2.54s/it]

[I 2026-05-18 11:41:00,809] Trial 174 finished with value: 0.9497011424462791 and parameters: {'solver': 'saga', 'C': 0.002643583859435976, 'l1_ratio': 0.8755856835451705, 'class_weight': None, 'fit_intercept': True, 'tol': 2.8854574188719616e-06, 'max_iter': 4287}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  35%|███▌      | 176/500 [07:21<09:06,  1.69s/it]

[I 2026-05-18 11:41:02,716] Trial 178 finished with value: 0.9497048727938043 and parameters: {'solver': 'saga', 'C': 0.0026955984718934705, 'l1_ratio': 0.9493547608272271, 'class_weight': None, 'fit_intercept': True, 'tol': 3.1939820363622035e-06, 'max_iter': 3934}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:41:02,848] Trial 177 finished with value: 0.9496996421938094 and parameters: {'solver': 'saga', 'C': 0.0008752646621102071, 'l1_ratio': 0.9548256724438746, 'class_weight': None, 'fit_intercept': True, 'tol': 2.9811642243020225e-06, 'max_iter': 3961}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  36%|███▌      | 178/500 [07:23<06:42,  1.25s/it]

[I 2026-05-18 11:41:04,648] Trial 176 finished with value: 0.9497049702343986 and parameters: {'solver': 'saga', 'C': 0.002589977328980785, 'l1_ratio': 0.9513360859726913, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4857349207126442e-06, 'max_iter': 3594}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:41:04,797] Trial 179 finished with value: 0.9497037331195699 and parameters: {'solver': 'saga', 'C': 0.004485099188428883, 'l1_ratio': 0.8707757446157715, 'class_weight': None, 'fit_intercept': True, 'tol': 3.0565591172124697e-06, 'max_iter': 3969}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  36%|███▌      | 179/500 [07:27<11:18,  2.11s/it]

[I 2026-05-18 11:41:08,925] Trial 182 finished with value: 0.9496968362439834 and parameters: {'solver': 'saga', 'C': 0.002664333852040456, 'l1_ratio': 0.8319963011993523, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007279788470261771, 'max_iter': 3520}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:41:09,129] Trial 180 finished with value: 0.9497016571350072 and parameters: {'solver': 'saga', 'C': 0.0026583610221036966, 'l1_ratio': 0.8804344248569839, 'class_weight': None, 'fit_intercept': True, 'tol': 3.237477500439147e-06, 'max_iter': 4285}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  36%|███▌      | 181/500 [07:28<07:16,  1.37s/it]

[I 2026-05-18 11:41:10,100] Trial 181 finished with value: 0.9497013503380269 and parameters: {'solver': 'saga', 'C': 0.002734845023357785, 'l1_ratio': 0.8745035904716527, 'class_weight': None, 'fit_intercept': True, 'tol': 3.1426886034387176e-06, 'max_iter': 4266}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  36%|███▋      | 182/500 [07:32<11:28,  2.16s/it]

[I 2026-05-18 11:41:14,118] Trial 183 finished with value: 0.949699982121136 and parameters: {'solver': 'saga', 'C': 0.002572209455784025, 'l1_ratio': 0.866705250537473, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012687140743383133, 'max_iter': 4353}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  37%|███▋      | 183/500 [07:45<28:31,  5.40s/it]

[I 2026-05-18 11:41:27,066] Trial 184 finished with value: 0.9497022137873966 and parameters: {'solver': 'saga', 'C': 0.002972249249313008, 'l1_ratio': 0.8755071639056684, 'class_weight': None, 'fit_intercept': True, 'tol': 3.044741194828051e-06, 'max_iter': 2295}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  37%|███▋      | 184/500 [07:49<25:49,  4.90s/it]

[I 2026-05-18 11:41:30,815] Trial 189 finished with value: 0.9497021840212234 and parameters: {'solver': 'saga', 'C': 0.0028194523622566653, 'l1_ratio': 0.8804523614563694, 'class_weight': None, 'fit_intercept': True, 'tol': 3.4586447393354305e-06, 'max_iter': 3930}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  37%|███▋      | 186/500 [07:50<13:42,  2.62s/it]

[I 2026-05-18 11:41:31,659] Trial 186 finished with value: 0.949699996246331 and parameters: {'solver': 'saga', 'C': 0.0025007517202068346, 'l1_ratio': 0.9939408926710253, 'class_weight': None, 'fit_intercept': True, 'tol': 3.05306149757122e-06, 'max_iter': 3956}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:41:31,785] Trial 191 finished with value: 0.9496959439899333 and parameters: {'solver': 'saga', 'C': 0.00462760491488774, 'l1_ratio': 0.7050796567796315, 'class_weight': None, 'fit_intercept': True, 'tol': 2.7665138413674812e-05, 'max_iter': 4077}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  37%|███▋      | 187/500 [07:51<11:55,  2.29s/it]

[I 2026-05-18 11:41:33,297] Trial 188 finished with value: 0.949697578798798 and parameters: {'solver': 'saga', 'C': 0.0028242549680096546, 'l1_ratio': 0.998215455688087, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002589197896303413, 'max_iter': 4189}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  38%|███▊      | 188/500 [07:54<12:37,  2.43s/it]

[I 2026-05-18 11:41:36,048] Trial 192 finished with value: 0.9496975197741664 and parameters: {'solver': 'saga', 'C': 0.004393315544409955, 'l1_ratio': 0.7469379336233143, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8558837193972381e-06, 'max_iter': 4144}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:41:36,075] Trial 193 finished with value: 0.9496766662992012 and parameters: {'solver': 'saga', 'C': 0.001379828791366499, 'l1_ratio': 0.7459731123428447, 'class_weight': None, 'fit_intercept': True, 'tol': 2.7227948524674595e-05, 'max_iter': 3910}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  38%|███▊      | 190/500 [08:16<32:25,  6.28s/it]

[I 2026-05-18 11:41:57,587] Trial 197 finished with value: 0.9497046602000081 and parameters: {'solver': 'saga', 'C': 0.001326708986645915, 'l1_ratio': 0.9910147931178676, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5189802512903187e-06, 'max_iter': 2192}. Best is trial 13 with value: 0.9497054361384407.
[I 2026-05-18 11:41:57,605] Trial 195 finished with value: 0.9496988479518145 and parameters: {'solver': 'saga', 'C': 0.004183477023547555, 'l1_ratio': 0.9831329076689289, 'class_weight': None, 'fit_intercept': True, 'tol': 1.504799742358327e-06, 'max_iter': 3883}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  38%|███▊      | 192/500 [08:17<20:14,  3.94s/it]

[I 2026-05-18 11:41:58,402] Trial 199 finished with value: 0.9497001848410932 and parameters: {'solver': 'saga', 'C': 0.001160590745621292, 'l1_ratio': 0.9359682595915678, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4490512110641875e-05, 'max_iter': 4039}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  39%|███▊      | 193/500 [08:18<17:18,  3.38s/it]

[I 2026-05-18 11:41:59,801] Trial 198 finished with value: 0.9497030832409491 and parameters: {'solver': 'saga', 'C': 0.004530079246375826, 'l1_ratio': 0.9373337900756327, 'class_weight': None, 'fit_intercept': True, 'tol': 1.48441270549601e-06, 'max_iter': 4014}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  39%|███▉      | 194/500 [08:19<14:06,  2.77s/it]

[I 2026-05-18 11:42:00,626] Trial 200 finished with value: 0.9496940932937292 and parameters: {'solver': 'saga', 'C': 0.004548131559931194, 'l1_ratio': 0.6774644161831677, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5463085344939724e-06, 'max_iter': 3170}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  39%|███▉      | 195/500 [08:20<12:21,  2.43s/it]

[I 2026-05-18 11:42:02,075] Trial 190 finished with value: 0.9496956158502312 and parameters: {'solver': 'saga', 'C': 0.004480914268855916, 'l1_ratio': 0.9961731180038133, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5405434128959935e-05, 'max_iter': 3894}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 13. Best value: 0.949705:  39%|███▉      | 196/500 [08:32<25:08,  4.96s/it]

[I 2026-05-18 11:42:13,972] Trial 196 finished with value: 0.9496961861714281 and parameters: {'solver': 'saga', 'C': 0.004591014672706833, 'l1_ratio': 0.9928501455403921, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5126349270022568e-06, 'max_iter': 4078}. Best is trial 13 with value: 0.9497054361384407.

Best trial: 201. Best value: 0.949706:  39%|███▉      | 197/500 [08:41<31:08,  6.17s/it]

[I 2026-05-18 11:42:23,299] Trial 201 finished with value: 0.9497063297008517 and parameters: {'solver': 'saga', 'C': 0.0011648304566744653, 'l1_ratio': 0.9833716877640769, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8190208892185874e-06, 'max_iter': 2153}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  40%|███▉      | 198/500 [08:44<25:14,  5.02s/it]

[I 2026-05-18 11:42:25,394] Trial 194 finished with value: 0.9496951115713049 and parameters: {'solver': 'saga', 'C': 0.004752054405294107, 'l1_ratio': 0.9967960190025804, 'class_weight': None, 'fit_intercept': True, 'tol': 2.8833115028575806e-05, 'max_iter': 4133}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  40%|███▉      | 199/500 [08:44<18:51,  3.76s/it]

[I 2026-05-18 11:42:26,049] Trial 203 finished with value: 0.9496916141069478 and parameters: {'solver': 'saga', 'C': 0.017151022619821734, 'l1_ratio': 0.6883000902841951, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5432734104800877e-06, 'max_iter': 3132}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  40%|████      | 200/500 [08:45<14:04,  2.82s/it]

[I 2026-05-18 11:42:26,551] Trial 202 finished with value: 0.9497003113984404 and parameters: {'solver': 'saga', 'C': 0.0011612444438817377, 'l1_ratio': 0.9366081263667274, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4940822660118981e-06, 'max_iter': 2237}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  40%|████      | 201/500 [08:45<10:31,  2.11s/it]

[I 2026-05-18 11:42:26,982] Trial 205 finished with value: 0.949705304537038 and parameters: {'solver': 'saga', 'C': 0.001501790161801082, 'l1_ratio': 0.9849703117142868, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1581170028463983e-06, 'max_iter': 2172}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  40%|████      | 202/500 [08:47<09:55,  2.00s/it]

[I 2026-05-18 11:42:28,721] Trial 204 finished with value: 0.9496960633382574 and parameters: {'solver': 'saga', 'C': 0.0005886418996381124, 'l1_ratio': 0.981914890100371, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8605136824434136e-06, 'max_iter': 2162}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  41%|████      | 203/500 [08:58<23:00,  4.65s/it]

[I 2026-05-18 11:42:39,640] Trial 206 finished with value: 0.9496864453298336 and parameters: {'solver': 'saga', 'C': 0.016381865328913434, 'l1_ratio': 0.9721134874066859, 'class_weight': None, 'fit_intercept': True, 'tol': 2.628351594492203e-06, 'max_iter': 2223}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  41%|████      | 204/500 [09:01<20:07,  4.08s/it]

[I 2026-05-18 11:42:42,384] Trial 207 finished with value: 0.949696551593149 and parameters: {'solver': 'saga', 'C': 0.0013875884125475958, 'l1_ratio': 0.9040272955152376, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1484446612935175e-06, 'max_iter': 2322}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  41%|████      | 205/500 [09:08<25:04,  5.10s/it]

[I 2026-05-18 11:42:49,882] Trial 208 finished with value: 0.9496882406949517 and parameters: {'solver': 'saga', 'C': 0.000545434705219214, 'l1_ratio': 0.9585286471929892, 'class_weight': None, 'fit_intercept': True, 'tol': 2.4785887327915155e-06, 'max_iter': 2220}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  41%|████      | 206/500 [09:09<19:11,  3.92s/it]

[I 2026-05-18 11:42:51,025] Trial 210 finished with value: 0.9492195960874182 and parameters: {'solver': 'saga', 'C': 0.0007478540372147844, 'l1_ratio': 0.2816352771425966, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.6065308424993016e-06, 'max_iter': 2179}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  41%|████▏     | 207/500 [09:10<14:21,  2.94s/it]

[I 2026-05-18 11:42:51,661] Trial 209 finished with value: 0.9497035145178405 and parameters: {'solver': 'saga', 'C': 0.00147083146514522, 'l1_ratio': 0.9410373921599008, 'class_weight': None, 'fit_intercept': True, 'tol': 1.130113885225919e-06, 'max_iter': 3741}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  42%|████▏     | 208/500 [09:11<11:38,  2.39s/it]

[I 2026-05-18 11:42:52,769] Trial 211 finished with value: 0.949578697293167 and parameters: {'solver': 'saga', 'C': 0.0006153954019661521, 'l1_ratio': 0.9718830926565163, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.8925594312345926e-06, 'max_iter': 2104}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  42%|████▏     | 209/500 [09:11<08:51,  1.83s/it]

[I 2026-05-18 11:42:53,277] Trial 185 finished with value: 0.949683043443198 and parameters: {'solver': 'saga', 'C': 0.017670922671036694, 'l1_ratio': 0.9924337868189606, 'class_weight': None, 'fit_intercept': True, 'tol': 1.845128511659234e-06, 'max_iter': 2879}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  42%|████▏     | 210/500 [09:14<10:17,  2.13s/it]

[I 2026-05-18 11:42:56,130] Trial 212 finished with value: 0.949706064212761 and parameters: {'solver': 'saga', 'C': 0.0015667929511103318, 'l1_ratio': 0.9689093857485399, 'class_weight': None, 'fit_intercept': True, 'tol': 1.107453178970034e-06, 'max_iter': 2161}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  42%|████▏     | 211/500 [09:15<08:27,  1.76s/it]

[I 2026-05-18 11:42:57,003] Trial 213 finished with value: 0.9497059916599364 and parameters: {'solver': 'saga', 'C': 0.0015416242927892073, 'l1_ratio': 0.9714887079388158, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2377074965358196e-06, 'max_iter': 2087}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  42%|████▏     | 212/500 [09:18<09:26,  1.97s/it]

[I 2026-05-18 11:42:59,465] Trial 12 pruned.

Best trial: 201. Best value: 0.949706:  43%|████▎     | 213/500 [09:27<19:47,  4.14s/it]

[I 2026-05-18 11:43:08,674] Trial 214 finished with value: 0.9497059941048709 and parameters: {'solver': 'saga', 'C': 0.0014128738744773784, 'l1_ratio': 0.9637941504549032, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1444808958723212e-06, 'max_iter': 2126}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  43%|████▎     | 214/500 [09:29<16:25,  3.45s/it]

[I 2026-05-18 11:43:10,486] Trial 215 finished with value: 0.9495801780811457 and parameters: {'solver': 'saga', 'C': 0.0007469514944845564, 'l1_ratio': 0.9716813933368356, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.0660917056022528e-06, 'max_iter': 2101}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  43%|████▎     | 215/500 [09:32<16:38,  3.50s/it]

[I 2026-05-18 11:43:14,143] Trial 219 finished with value: 0.9497041707275686 and parameters: {'solver': 'saga', 'C': 0.0016607288876760978, 'l1_ratio': 0.9414026691002157, 'class_weight': None, 'fit_intercept': True, 'tol': 4.176631655042388e-05, 'max_iter': 2047}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  43%|████▎     | 216/500 [09:36<16:52,  3.57s/it]

[I 2026-05-18 11:43:17,853] Trial 217 finished with value: 0.9497060110201412 and parameters: {'solver': 'saga', 'C': 0.0015859854131444208, 'l1_ratio': 0.9658032309150695, 'class_weight': None, 'fit_intercept': True, 'tol': 1.902270014566277e-06, 'max_iter': 2354}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  43%|████▎     | 217/500 [09:37<13:04,  2.77s/it]

[I 2026-05-18 11:43:18,775] Trial 216 finished with value: 0.9497024108350332 and parameters: {'solver': 'saga', 'C': 0.0009050413254061279, 'l1_ratio': 0.9644469545264726, 'class_weight': None, 'fit_intercept': True, 'tol': 1.122935598129669e-06, 'max_iter': 2134}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  44%|████▎     | 218/500 [09:38<10:58,  2.34s/it]

[I 2026-05-18 11:43:20,088] Trial 218 finished with value: 0.949705888527399 and parameters: {'solver': 'saga', 'C': 0.0016475588297745697, 'l1_ratio': 0.9607519475526293, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0357464589075639e-06, 'max_iter': 1890}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  44%|████▍     | 219/500 [09:40<10:03,  2.15s/it]

[I 2026-05-18 11:43:21,808] Trial 220 finished with value: 0.9497035802338798 and parameters: {'solver': 'saga', 'C': 0.0015499583312422387, 'l1_ratio': 0.9392881373094356, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1288303613839097e-06, 'max_iter': 1879}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  44%|████▍     | 220/500 [09:43<11:24,  2.44s/it]

[I 2026-05-18 11:43:24,939] Trial 221 finished with value: 0.949705495342729 and parameters: {'solver': 'saga', 'C': 0.0020145331232820853, 'l1_ratio': 0.9641634437282508, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0956629546842235e-06, 'max_iter': 2013}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  44%|████▍     | 221/500 [09:44<09:08,  1.97s/it]

[I 2026-05-18 11:43:25,794] Trial 222 finished with value: 0.9497060121588558 and parameters: {'solver': 'saga', 'C': 0.0015714219753550352, 'l1_ratio': 0.9673592541041401, 'class_weight': None, 'fit_intercept': True, 'tol': 1.014445350901263e-06, 'max_iter': 2030}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  44%|████▍     | 222/500 [09:45<08:16,  1.79s/it]

[I 2026-05-18 11:43:27,140] Trial 223 finished with value: 0.9497059290333688 and parameters: {'solver': 'saga', 'C': 0.0016145062412867817, 'l1_ratio': 0.9676632118076897, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1596351737301673e-06, 'max_iter': 2034}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  45%|████▍     | 223/500 [09:54<17:49,  3.86s/it]

[I 2026-05-18 11:43:35,855] Trial 226 finished with value: 0.9496612342971474 and parameters: {'solver': 'saga', 'C': 0.00034565128942249795, 'l1_ratio': 0.9693665546507884, 'class_weight': None, 'fit_intercept': True, 'tol': 4.4472012411637084e-05, 'max_iter': 1749}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  45%|████▍     | 224/500 [09:55<13:48,  3.00s/it]

[I 2026-05-18 11:43:36,851] Trial 224 finished with value: 0.9497037717240037 and parameters: {'solver': 'saga', 'C': 0.001018889431458135, 'l1_ratio': 0.9637807641220568, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2264674559525197e-06, 'max_iter': 2076}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  45%|████▌     | 225/500 [09:59<14:24,  3.15s/it]

[I 2026-05-18 11:43:40,335] Trial 225 finished with value: 0.9497058332223508 and parameters: {'solver': 'saga', 'C': 0.0014899455121453755, 'l1_ratio': 0.9616008665906465, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1688225212863115e-06, 'max_iter': 1819}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  45%|████▌     | 226/500 [09:59<10:40,  2.34s/it]

[I 2026-05-18 11:43:40,785] Trial 229 finished with value: 0.9497017716925715 and parameters: {'solver': 'saga', 'C': 0.0010592225452051673, 'l1_ratio': 0.9499132088562569, 'class_weight': None, 'fit_intercept': True, 'tol': 3.954803379300102e-05, 'max_iter': 1864}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  45%|████▌     | 227/500 [10:04<13:57,  3.07s/it]

[I 2026-05-18 11:43:45,557] Trial 231 finished with value: 0.9497059335863105 and parameters: {'solver': 'saga', 'C': 0.0016708032720536992, 'l1_ratio': 0.9633720911677839, 'class_weight': None, 'fit_intercept': True, 'tol': 4.380617250366616e-05, 'max_iter': 1752}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  46%|████▌     | 228/500 [10:04<10:12,  2.25s/it]

[I 2026-05-18 11:43:45,902] Trial 227 finished with value: 0.9497026706059334 and parameters: {'solver': 'saga', 'C': 0.0010356080674870135, 'l1_ratio': 0.9565996824597518, 'class_weight': None, 'fit_intercept': True, 'tol': 1.201052380181957e-06, 'max_iter': 1863}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  46%|████▌     | 229/500 [10:04<07:39,  1.69s/it]

[I 2026-05-18 11:43:46,300] Trial 228 finished with value: 0.9497056980365507 and parameters: {'solver': 'saga', 'C': 0.0018038003869719225, 'l1_ratio': 0.9595829149667596, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2938420655848786e-06, 'max_iter': 1991}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  46%|████▌     | 230/500 [10:05<06:03,  1.35s/it]

[I 2026-05-18 11:43:46,836] Trial 232 finished with value: 0.9497038646050875 and parameters: {'solver': 'saga', 'C': 0.0010601758408836674, 'l1_ratio': 0.9624214635420113, 'class_weight': None, 'fit_intercept': True, 'tol': 3.7059395707397024e-05, 'max_iter': 2034}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  46%|████▌     | 231/500 [10:08<08:44,  1.95s/it]

[I 2026-05-18 11:43:50,188] Trial 230 finished with value: 0.9497041183671314 and parameters: {'solver': 'saga', 'C': 0.0011261670705793399, 'l1_ratio': 0.9605898458427841, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3271987512333154e-06, 'max_iter': 1729}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  46%|████▋     | 232/500 [10:13<12:19,  2.76s/it]

[I 2026-05-18 11:43:54,840] Trial 233 finished with value: 0.9497051514883476 and parameters: {'solver': 'saga', 'C': 0.0010869319296502142, 'l1_ratio': 0.968711748252959, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2609930075815733e-06, 'max_iter': 1705}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  47%|████▋     | 233/500 [10:21<19:34,  4.40s/it]

[I 2026-05-18 11:44:03,071] Trial 234 finished with value: 0.9497055247867771 and parameters: {'solver': 'saga', 'C': 0.0019869473248984334, 'l1_ratio': 0.9623235527743564, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0480524267426401e-06, 'max_iter': 1991}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  47%|████▋     | 234/500 [10:22<14:23,  3.25s/it]

[I 2026-05-18 11:44:03,625] Trial 235 finished with value: 0.9497045523345298 and parameters: {'solver': 'saga', 'C': 0.0018683869776099779, 'l1_ratio': 0.9816552088172574, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2929145737520352e-06, 'max_iter': 2008}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  47%|████▋     | 235/500 [10:27<17:05,  3.87s/it]

[I 2026-05-18 11:44:08,946] Trial 236 finished with value: 0.9497062986360136 and parameters: {'solver': 'saga', 'C': 0.0011003110884600727, 'l1_ratio': 0.9841852741484869, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2541199505800153e-06, 'max_iter': 1966}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  47%|████▋     | 236/500 [10:28<13:15,  3.01s/it]

[I 2026-05-18 11:44:09,958] Trial 237 finished with value: 0.9497046831208535 and parameters: {'solver': 'saga', 'C': 0.0019143093826727098, 'l1_ratio': 0.9798079774399531, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1973541533744089e-06, 'max_iter': 1945}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  47%|████▋     | 237/500 [10:32<14:16,  3.26s/it]

[I 2026-05-18 11:44:13,781] Trial 239 finished with value: 0.9497048563688082 and parameters: {'solver': 'saga', 'C': 0.0018372359412600235, 'l1_ratio': 0.9797017648987745, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0481958558616787e-06, 'max_iter': 1771}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  48%|████▊     | 238/500 [10:32<10:19,  2.36s/it]

[I 2026-05-18 11:44:14,072] Trial 238 finished with value: 0.9497057365889511 and parameters: {'solver': 'saga', 'C': 0.001528150975034374, 'l1_ratio': 0.980400922344485, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0287600839240676e-06, 'max_iter': 1774}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  48%|████▊     | 239/500 [10:33<08:49,  2.03s/it]

[I 2026-05-18 11:44:15,311] Trial 240 finished with value: 0.949704637086116 and parameters: {'solver': 'saga', 'C': 0.0018745726140726594, 'l1_ratio': 0.9810979053421215, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0483779912058037e-06, 'max_iter': 1963}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  48%|████▊     | 240/500 [10:40<14:36,  3.37s/it]

[I 2026-05-18 11:44:21,815] Trial 243 finished with value: 0.9497048586480075 and parameters: {'solver': 'saga', 'C': 0.0017362862970393329, 'l1_ratio': 0.9823792899482777, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0634711473404781e-06, 'max_iter': 1967}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  48%|████▊     | 241/500 [10:49<21:59,  5.09s/it]

[I 2026-05-18 11:44:30,883] Trial 244 finished with value: 0.9497043677048296 and parameters: {'solver': 'saga', 'C': 0.0017934451395668956, 'l1_ratio': 0.9840096206211401, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0476223708601228e-06, 'max_iter': 1954}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  48%|████▊     | 242/500 [10:51<17:27,  4.06s/it]

[I 2026-05-18 11:44:32,579] Trial 245 finished with value: 0.9497057417936631 and parameters: {'solver': 'saga', 'C': 0.0015034417552686466, 'l1_ratio': 0.9814925798674202, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0431407622288303e-06, 'max_iter': 1630}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  49%|████▊     | 243/500 [10:55<17:00,  3.97s/it]

[I 2026-05-18 11:44:36,329] Trial 246 finished with value: 0.9497053998560048 and parameters: {'solver': 'saga', 'C': 0.001806706406744023, 'l1_ratio': 0.9754604275731329, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0254587168442129e-06, 'max_iter': 1950}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  49%|████▉     | 244/500 [10:57<14:34,  3.42s/it]

[I 2026-05-18 11:44:38,458] Trial 247 finished with value: 0.9497057170684672 and parameters: {'solver': 'saga', 'C': 0.001582731496632621, 'l1_ratio': 0.978316186900126, 'class_weight': None, 'fit_intercept': True, 'tol': 1.005103686581275e-06, 'max_iter': 1611}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  49%|████▉     | 245/500 [11:00<14:11,  3.34s/it]

[I 2026-05-18 11:44:41,622] Trial 248 finished with value: 0.9497053990468587 and parameters: {'solver': 'saga', 'C': 0.0015515642747075211, 'l1_ratio': 0.9827379884343719, 'class_weight': None, 'fit_intercept': True, 'tol': 1.01818151997236e-06, 'max_iter': 1615}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  49%|████▉     | 246/500 [11:00<10:27,  2.47s/it]

[I 2026-05-18 11:44:42,063] Trial 250 finished with value: 0.9497037945021012 and parameters: {'solver': 'saga', 'C': 0.000846398214233571, 'l1_ratio': 0.9946976647614149, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2571825256300954e-06, 'max_iter': 1602}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  49%|████▉     | 247/500 [11:01<07:57,  1.89s/it]

[I 2026-05-18 11:44:42,598] Trial 249 finished with value: 0.9497014136737707 and parameters: {'solver': 'saga', 'C': 0.000760881727621595, 'l1_ratio': 0.9973652771730073, 'class_weight': None, 'fit_intercept': True, 'tol': 1.003370922225152e-06, 'max_iter': 1582}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  50%|████▉     | 248/500 [11:12<19:53,  4.73s/it]

[I 2026-05-18 11:44:53,967] Trial 258 pruned.

Best trial: 201. Best value: 0.949706:  50%|████▉     | 249/500 [11:16<18:22,  4.39s/it]

[I 2026-05-18 11:44:57,563] Trial 251 finished with value: 0.9497008888980588 and parameters: {'solver': 'saga', 'C': 0.0007649079139806951, 'l1_ratio': 0.9985282435743101, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0464570321205153e-06, 'max_iter': 1701}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  50%|█████     | 250/500 [11:18<15:50,  3.80s/it]

[I 2026-05-18 11:44:59,991] Trial 253 finished with value: 0.9497001607990707 and parameters: {'solver': 'saga', 'C': 0.0007700539774909379, 'l1_ratio': 0.9667875172991423, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2939325557498878e-06, 'max_iter': 1642}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  50%|█████     | 251/500 [11:24<17:50,  4.30s/it]

[I 2026-05-18 11:45:05,436] Trial 252 finished with value: 0.9497018788992282 and parameters: {'solver': 'saga', 'C': 0.0008082374106789916, 'l1_ratio': 0.998322943276153, 'class_weight': None, 'fit_intercept': True, 'tol': 1.000792719349646e-06, 'max_iter': 1791}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  50%|█████     | 252/500 [11:25<14:39,  3.54s/it]

[I 2026-05-18 11:45:07,236] Trial 255 finished with value: 0.9497016270949858 and parameters: {'solver': 'saga', 'C': 0.0007760501174804712, 'l1_ratio': 0.9975068376638876, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0123895493756326e-06, 'max_iter': 1588}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  51%|█████     | 253/500 [11:43<31:57,  7.76s/it]

[I 2026-05-18 11:45:24,844] Trial 260 finished with value: 0.949706088779126 and parameters: {'solver': 'saga', 'C': 0.0014098199652520477, 'l1_ratio': 0.9682790269681092, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2747700274838018e-06, 'max_iter': 1842}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  51%|█████     | 254/500 [11:45<24:23,  5.95s/it]

[I 2026-05-18 11:45:26,553] Trial 242 finished with value: 0.9497001721011082 and parameters: {'solver': 'saga', 'C': 0.0018326892310015475, 'l1_ratio': 0.9989829213080625, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0488513289954614e-06, 'max_iter': 1922}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  51%|█████     | 255/500 [11:49<22:46,  5.58s/it]

[I 2026-05-18 11:45:31,269] Trial 262 finished with value: 0.9497062351839723 and parameters: {'solver': 'saga', 'C': 0.0014147440681375328, 'l1_ratio': 0.973126029411104, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3615072500011867e-06, 'max_iter': 1492}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  51%|█████     | 256/500 [11:51<18:04,  4.44s/it]

[I 2026-05-18 11:45:33,066] Trial 263 finished with value: 0.9497062096455589 and parameters: {'solver': 'saga', 'C': 0.0013658811131115087, 'l1_ratio': 0.9707328500628561, 'class_weight': None, 'fit_intercept': True, 'tol': 1.397924880512504e-06, 'max_iter': 1811}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  51%|█████▏    | 257/500 [12:02<26:06,  6.45s/it]

[I 2026-05-18 11:45:44,190] Trial 259 finished with value: 0.9497023060302183 and parameters: {'solver': 'saga', 'C': 0.001323034076214044, 'l1_ratio': 0.9981971115480849, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0201496705825606e-06, 'max_iter': 1812}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  52%|█████▏    | 258/500 [12:03<18:57,  4.70s/it]

[I 2026-05-18 11:45:44,803] Trial 241 finished with value: 0.9496997873844025 and parameters: {'solver': 'saga', 'C': 0.00188068948457292, 'l1_ratio': 0.9992167154853547, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0485027754175781e-06, 'max_iter': 1726}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  52%|█████▏    | 259/500 [12:09<20:26,  5.09s/it]

[I 2026-05-18 11:45:50,810] Trial 264 finished with value: 0.9497059962238961 and parameters: {'solver': 'saga', 'C': 0.0013345121537627928, 'l1_ratio': 0.967866234461983, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3184633609621172e-06, 'max_iter': 1499}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  52%|█████▏    | 260/500 [12:13<18:31,  4.63s/it]

[I 2026-05-18 11:45:54,364] Trial 265 finished with value: 0.9497060232265699 and parameters: {'solver': 'saga', 'C': 0.0013430659625153904, 'l1_ratio': 0.968496733653304, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3579053852913936e-06, 'max_iter': 1811}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  52%|█████▏    | 261/500 [12:16<17:12,  4.32s/it]

[I 2026-05-18 11:45:57,957] Trial 266 finished with value: 0.9497062291629715 and parameters: {'solver': 'saga', 'C': 0.001451121008799998, 'l1_ratio': 0.973337577794897, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3769041409586514e-06, 'max_iter': 1465}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  53%|█████▎    | 263/500 [12:18<09:38,  2.44s/it]

[I 2026-05-18 11:45:59,278] Trial 261 finished with value: 0.9497021731271849 and parameters: {'solver': 'saga', 'C': 0.0013261650726722645, 'l1_ratio': 0.9985140708221707, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0066455075986156e-06, 'max_iter': 1516}. Best is trial 201 with value: 0.9497063297008517.
[I 2026-05-18 11:45:59,441] Trial 267 finished with value: 0.949706317982766 and parameters: {'solver': 'saga', 'C': 0.0013905633643108964, 'l1_ratio': 0.9717430503101127, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3739422307271227e-06, 'max_iter': 1462}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  53%|█████▎    | 264/500 [12:29<20:11,  5.13s/it]

[I 2026-05-18 11:46:10,859] Trial 268 finished with value: 0.9497062314425484 and parameters: {'solver': 'saga', 'C': 0.0014139402812647747, 'l1_ratio': 0.97292627466689, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3651808175547213e-06, 'max_iter': 1846}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  53%|█████▎    | 265/500 [12:30<15:07,  3.86s/it]

[I 2026-05-18 11:46:11,756] Trial 257 finished with value: 0.9497013217063713 and parameters: {'solver': 'saga', 'C': 0.0014389822268902595, 'l1_ratio': 0.9991142350511913, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0232868956914025e-06, 'max_iter': 1633}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  53%|█████▎    | 266/500 [12:31<11:47,  3.03s/it]

[I 2026-05-18 11:46:12,828] Trial 269 finished with value: 0.9497062994391439 and parameters: {'solver': 'saga', 'C': 0.0013747117064666292, 'l1_ratio': 0.9721824294140747, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4167870738940491e-06, 'max_iter': 1507}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  53%|█████▎    | 267/500 [12:34<12:06,  3.12s/it]

[I 2026-05-18 11:46:16,162] Trial 187 finished with value: 0.9496831010155177 and parameters: {'solver': 'saga', 'C': 0.017358749833376555, 'l1_ratio': 0.9981859867223513, 'class_weight': None, 'fit_intercept': True, 'tol': 3.213077744150808e-06, 'max_iter': 2224}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  54%|█████▎    | 268/500 [12:39<14:01,  3.63s/it]

[I 2026-05-18 11:46:20,964] Trial 271 finished with value: 0.9497042709435055 and parameters: {'solver': 'saga', 'C': 0.00123427895143058, 'l1_ratio': 0.9560528664775405, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6793406768734675e-06, 'max_iter': 1493}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  54%|█████▍    | 269/500 [12:43<14:00,  3.64s/it]

[I 2026-05-18 11:46:24,636] Trial 272 finished with value: 0.9497017583421465 and parameters: {'solver': 'saga', 'C': 0.0012046392831897173, 'l1_ratio': 0.9412850023731465, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4292548615239999e-06, 'max_iter': 1377}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  54%|█████▍    | 270/500 [12:45<11:46,  3.07s/it]

[I 2026-05-18 11:46:26,392] Trial 274 finished with value: 0.9496686054709361 and parameters: {'solver': 'saga', 'C': 0.00036551972692314426, 'l1_ratio': 0.944011064978806, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4297870956198523e-06, 'max_iter': 1341}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  54%|█████▍    | 271/500 [12:45<08:55,  2.34s/it]

[I 2026-05-18 11:46:27,022] Trial 273 finished with value: 0.9496724835096811 and parameters: {'solver': 'saga', 'C': 0.00040138944895819884, 'l1_ratio': 0.9383944304650687, 'class_weight': None, 'fit_intercept': True, 'tol': 1.660503635617181e-06, 'max_iter': 1399}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  54%|█████▍    | 272/500 [12:56<18:38,  4.90s/it]

[I 2026-05-18 11:46:37,907] Trial 280 pruned.

Best trial: 201. Best value: 0.949706:  55%|█████▍    | 273/500 [12:57<13:45,  3.64s/it]

[I 2026-05-18 11:46:38,582] Trial 276 finished with value: 0.9496789626531419 and parameters: {'solver': 'saga', 'C': 0.0004573294452147034, 'l1_ratio': 0.9465938225702863, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6670744879688293e-06, 'max_iter': 1404}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  55%|█████▍    | 274/500 [12:57<09:59,  2.65s/it]

[I 2026-05-18 11:46:38,940] Trial 281 pruned.
[I 2026-05-18 11:46:39,041] Trial 275 finished with value: 0.9496744531169299 and parameters: {'solver': 'saga', 'C': 0.0004173092549955206, 'l1_ratio': 0.9411151806950574, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4289082594087143e-06, 'max_iter': 1527}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  55%|█████▌    | 276/500 [12:57<05:34,  1.49s/it]

[I 2026-05-18 11:46:39,206] Trial 277 finished with value: 0.9496769849028242 and parameters: {'solver': 'saga', 'C': 0.00044797171473647185, 'l1_ratio': 0.9378707716547171, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7500673391547351e-06, 'max_iter': 1362}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  55%|█████▌    | 277/500 [12:58<04:46,  1.29s/it]

[I 2026-05-18 11:46:39,881] Trial 282 pruned.

Best trial: 201. Best value: 0.949706:  56%|█████▌    | 278/500 [13:02<07:41,  2.08s/it]

[I 2026-05-18 11:46:44,204] Trial 278 finished with value: 0.9496640209514735 and parameters: {'solver': 'saga', 'C': 0.00033751498033574224, 'l1_ratio': 0.9435952195979268, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6976493786054554e-06, 'max_iter': 1370}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  56%|█████▌    | 279/500 [13:05<08:03,  2.19s/it]

[I 2026-05-18 11:46:46,675] Trial 279 finished with value: 0.9496994912239402 and parameters: {'solver': 'saga', 'C': 0.0010238715163054276, 'l1_ratio': 0.9412984386079764, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5462453072630525e-06, 'max_iter': 1359}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  56%|█████▌    | 280/500 [13:22<23:11,  6.32s/it]

[I 2026-05-18 11:47:03,647] Trial 283 finished with value: 0.9497038283357127 and parameters: {'solver': 'saga', 'C': 0.0009809799585546286, 'l1_ratio': 0.9666121625370406, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7441727530942495e-06, 'max_iter': 1464}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  56%|█████▌    | 281/500 [13:23<17:52,  4.90s/it]

[I 2026-05-18 11:47:04,982] Trial 284 finished with value: 0.9497025328351226 and parameters: {'solver': 'saga', 'C': 0.0009381684461268626, 'l1_ratio': 0.9629093398456453, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3585150159196937e-06, 'max_iter': 1828}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  56%|█████▋    | 282/500 [13:24<13:24,  3.69s/it]

[I 2026-05-18 11:47:05,697] Trial 285 finished with value: 0.9495571967440706 and parameters: {'solver': 'saga', 'C': 4.8077321767881166e-05, 'l1_ratio': 0.9737442088718189, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3636876781807225e-06, 'max_iter': 1864}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  57%|█████▋    | 283/500 [13:24<10:01,  2.77s/it]

[I 2026-05-18 11:47:06,260] Trial 287 finished with value: 0.9497040227276484 and parameters: {'solver': 'saga', 'C': 0.000978981661171745, 'l1_ratio': 0.9676713840553606, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3326926416602597e-06, 'max_iter': 1818}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  57%|█████▋    | 284/500 [13:26<08:15,  2.29s/it]

[I 2026-05-18 11:47:07,392] Trial 288 finished with value: 0.9495621994869612 and parameters: {'solver': 'saga', 'C': 3.678050018958793e-05, 'l1_ratio': 0.9721370488111181, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2964484643385155e-06, 'max_iter': 1833}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  57%|█████▋    | 285/500 [13:29<09:20,  2.61s/it]

[I 2026-05-18 11:47:10,764] Trial 289 finished with value: 0.9497043519771872 and parameters: {'solver': 'saga', 'C': 0.0009491194358125194, 'l1_ratio': 0.9708315067960164, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3221693831700137e-06, 'max_iter': 1854}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  57%|█████▋    | 286/500 [13:30<07:33,  2.12s/it]

[I 2026-05-18 11:47:11,737] Trial 290 finished with value: 0.9497053410064058 and parameters: {'solver': 'saga', 'C': 0.000996562404215392, 'l1_ratio': 0.9748641322978152, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2904551812830715e-06, 'max_iter': 1815}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  57%|█████▋    | 287/500 [13:49<25:09,  7.09s/it]

[I 2026-05-18 11:47:30,517] Trial 291 finished with value: 0.9497053367769815 and parameters: {'solver': 'saga', 'C': 0.0009926999308291866, 'l1_ratio': 0.9752873718549706, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3106701692623804e-06, 'max_iter': 1870}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  58%|█████▊    | 288/500 [13:51<19:34,  5.54s/it]

[I 2026-05-18 11:47:32,429] Trial 292 finished with value: 0.9497062729247011 and parameters: {'solver': 'saga', 'C': 0.0013174569438186745, 'l1_ratio': 0.9724678254796243, 'class_weight': None, 'fit_intercept': True, 'tol': 1.299531017707081e-06, 'max_iter': 1900}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  58%|█████▊    | 289/500 [13:51<13:56,  3.97s/it]

[I 2026-05-18 11:47:32,697] Trial 293 finished with value: 0.9497062714593003 and parameters: {'solver': 'saga', 'C': 0.001370882136188802, 'l1_ratio': 0.9738221432696267, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3453116128197704e-06, 'max_iter': 2072}. Best is trial 201 with value: 0.9497063297008517.
[I 2026-05-18 11:47:32,717] Trial 294 finished with value: 0.9497062148493682 and parameters: {'solver': 'saga', 'C': 0.0014058539998048642, 'l1_ratio': 0.9740426177857153, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2727701594450419e-06, 'max_iter': 2026}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  58%|█████▊    | 291/500 [13:52<08:14,  2.37s/it]

[I 2026-05-18 11:47:33,695] Trial 295 finished with value: 0.9495876482570941 and parameters: {'solver': 'saga', 'C': 0.000127940899653017, 'l1_ratio': 0.9755391625061078, 'class_weight': None, 'fit_intercept': True, 'tol': 1.964435955633375e-06, 'max_iter': 2043}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  58%|█████▊    | 292/500 [13:54<07:48,  2.25s/it]

[I 2026-05-18 11:47:35,589] Trial 296 finished with value: 0.9497015133480229 and parameters: {'solver': 'saga', 'C': 0.0016044634220274722, 'l1_ratio': 0.9226075115640648, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0508210413122218e-06, 'max_iter': 2068}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  59%|█████▊    | 293/500 [14:04<14:57,  4.34s/it]

[I 2026-05-18 11:47:45,818] Trial 256 finished with value: 0.9496996848145998 and parameters: {'solver': 'saga', 'C': 0.0007513760066093392, 'l1_ratio': 0.9998303374920601, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0145297950348698e-06, 'max_iter': 1621}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  59%|█████▉    | 294/500 [14:13<19:22,  5.64s/it]

[I 2026-05-18 11:47:54,962] Trial 254 finished with value: 0.9497018782355511 and parameters: {'solver': 'saga', 'C': 0.0009021538913968169, 'l1_ratio': 0.9998056338554876, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0303227013307096e-06, 'max_iter': 1529}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  59%|█████▉    | 295/500 [14:14<14:28,  4.24s/it]

[I 2026-05-18 11:47:55,580] Trial 298 finished with value: 0.9496024469130917 and parameters: {'solver': 'saga', 'C': 0.001472302650472781, 'l1_ratio': 0.921610488817917, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.9702790173568148e-06, 'max_iter': 2030}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  59%|█████▉    | 296/500 [14:17<13:04,  3.85s/it]

[I 2026-05-18 11:47:58,452] Trial 299 finished with value: 0.949601779969975 and parameters: {'solver': 'saga', 'C': 0.0015102325767158162, 'l1_ratio': 0.9263239115158997, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.2512258757102824e-06, 'max_iter': 1212}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  59%|█████▉    | 297/500 [14:18<10:07,  2.99s/it]

[I 2026-05-18 11:47:59,357] Trial 303 finished with value: 0.9496015707740078 and parameters: {'solver': 'saga', 'C': 0.0013058926319465577, 'l1_ratio': 0.9276744824424256, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.8241384187170988e-06, 'max_iter': 2091}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  60%|█████▉    | 298/500 [14:18<07:25,  2.21s/it]

[I 2026-05-18 11:47:59,660] Trial 302 finished with value: 0.9496022172232003 and parameters: {'solver': 'saga', 'C': 0.0014049905352479693, 'l1_ratio': 0.9237391721499518, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.923673092175427e-06, 'max_iter': 2081}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  60%|█████▉    | 299/500 [14:31<17:52,  5.34s/it]

[I 2026-05-18 11:48:12,477] Trial 304 finished with value: 0.9493242028583021 and parameters: {'solver': 'saga', 'C': 0.0013590337262417583, 'l1_ratio': 0.1427777281811749, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.856698637355157e-06, 'max_iter': 1224}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  60%|██████    | 300/500 [14:38<19:59,  6.00s/it]

[I 2026-05-18 11:48:20,044] Trial 306 finished with value: 0.9497041630747042 and parameters: {'solver': 'saga', 'C': 0.002194700148878464, 'l1_ratio': 0.9273521422482764, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6751532057384804e-06, 'max_iter': 2105}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  60%|██████    | 301/500 [14:39<14:16,  4.30s/it]

[I 2026-05-18 11:48:20,345] Trial 305 finished with value: 0.9496007803619311 and parameters: {'solver': 'saga', 'C': 0.0012863794693476571, 'l1_ratio': 0.9320103808801352, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.9208378103049742e-06, 'max_iter': 1748}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  60%|██████    | 302/500 [14:43<14:14,  4.32s/it]

[I 2026-05-18 11:48:24,684] Trial 307 finished with value: 0.9494927424979306 and parameters: {'solver': 'saga', 'C': 0.0012775283616164909, 'l1_ratio': 0.3680685489028252, 'class_weight': None, 'fit_intercept': True, 'tol': 1.683133533420165e-06, 'max_iter': 1716}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  61%|██████    | 303/500 [14:44<11:00,  3.35s/it]

[I 2026-05-18 11:48:25,777] Trial 308 finished with value: 0.9496240751474538 and parameters: {'solver': 'saga', 'C': 0.0020956083722837374, 'l1_ratio': 0.38672354383924423, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6873646445586007e-06, 'max_iter': 1910}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  61%|██████    | 304/500 [14:45<08:30,  2.60s/it]

[I 2026-05-18 11:48:26,635] Trial 309 finished with value: 0.9496213043784255 and parameters: {'solver': 'saga', 'C': 0.002171797970612217, 'l1_ratio': 0.36671756464895144, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5129467108933627e-06, 'max_iter': 1747}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  61%|██████    | 305/500 [14:57<17:28,  5.37s/it]

[I 2026-05-18 11:48:38,494] Trial 310 finished with value: 0.9496908103788879 and parameters: {'solver': 'saga', 'C': 0.0006024197906977963, 'l1_ratio': 0.9552599637463646, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5277887371271095e-06, 'max_iter': 1740}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  61%|██████    | 306/500 [15:03<17:57,  5.55s/it]

[I 2026-05-18 11:48:44,468] Trial 311 finished with value: 0.9496995347012721 and parameters: {'solver': 'saga', 'C': 0.0006646026183829089, 'l1_ratio': 0.9793656753660098, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5118826317467668e-06, 'max_iter': 1744}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  61%|██████▏   | 307/500 [15:05<14:49,  4.61s/it]

[I 2026-05-18 11:48:46,861] Trial 312 finished with value: 0.9496909649108669 and parameters: {'solver': 'saga', 'C': 0.0006209068182449588, 'l1_ratio': 0.952291717828981, 'class_weight': None, 'fit_intercept': True, 'tol': 1.485625805692888e-06, 'max_iter': 1931}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  62%|██████▏   | 308/500 [15:08<12:49,  4.01s/it]

[I 2026-05-18 11:48:49,474] Trial 313 finished with value: 0.9496949364954919 and parameters: {'solver': 'saga', 'C': 0.0006844289829808108, 'l1_ratio': 0.9570455117601034, 'class_weight': None, 'fit_intercept': True, 'tol': 1.473325342944608e-06, 'max_iter': 1910}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  62%|██████▏   | 309/500 [15:10<11:04,  3.48s/it]

[I 2026-05-18 11:48:51,707] Trial 314 finished with value: 0.9496946493816111 and parameters: {'solver': 'saga', 'C': 0.000682773748856223, 'l1_ratio': 0.9560712206977718, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2563424396146732e-06, 'max_iter': 1914}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 201. Best value: 0.949706:  62%|██████▏   | 310/500 [15:32<29:01,  9.17s/it]

[I 2026-05-18 11:49:14,155] Trial 319 finished with value: 0.9497044652993087 and parameters: {'solver': 'saga', 'C': 0.002258859436804097, 'l1_ratio': 0.9738714021958998, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2337508913939798e-06, 'max_iter': 1465}. Best is trial 201 with value: 0.9497063297008517.

Best trial: 320. Best value: 0.949706:  62%|██████▏   | 311/500 [15:36<24:05,  7.65s/it]

[I 2026-05-18 11:49:18,253] Trial 320 finished with value: 0.9497063895637801 and parameters: {'solver': 'saga', 'C': 0.0011575816395735902, 'l1_ratio': 0.9800903360473394, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2322272557583773e-06, 'max_iter': 1488}. Best is trial 320 with value: 0.9497063895637801.

Best trial: 320. Best value: 0.949706:  62%|██████▏   | 312/500 [15:42<21:35,  6.89s/it]

[I 2026-05-18 11:49:23,389] Trial 301 finished with value: 0.949589147243364 and parameters: {'solver': 'saga', 'C': 0.6278453558429861, 'l1_ratio': 0.9275141456144402, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.915141057003338e-06, 'max_iter': 2109}. Best is trial 320 with value: 0.9497063895637801.

Best trial: 320. Best value: 0.949706:  63%|██████▎   | 313/500 [15:59<31:37, 10.15s/it]

[I 2026-05-18 11:49:41,125] Trial 321 finished with value: 0.949706294729274 and parameters: {'solver': 'saga', 'C': 0.0011047429770849274, 'l1_ratio': 0.9801104319040186, 'class_weight': None, 'fit_intercept': True, 'tol': 1.224135753311081e-06, 'max_iter': 2145}. Best is trial 320 with value: 0.9497063895637801.

Best trial: 322. Best value: 0.949706:  63%|██████▎   | 314/500 [16:03<25:10,  8.12s/it]

[I 2026-05-18 11:49:44,528] Trial 322 finished with value: 0.9497063898914387 and parameters: {'solver': 'saga', 'C': 0.0011147771434346452, 'l1_ratio': 0.9796608638942146, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2480145811741347e-06, 'max_iter': 1539}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  63%|██████▎   | 315/500 [16:07<21:33,  6.99s/it]

[I 2026-05-18 11:49:48,887] Trial 323 finished with value: 0.9497057833014967 and parameters: {'solver': 'saga', 'C': 0.0010241978978388626, 'l1_ratio': 0.9773107623072456, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2696768590336339e-06, 'max_iter': 1534}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  63%|██████▎   | 316/500 [16:25<31:32, 10.28s/it]

[I 2026-05-18 11:50:06,838] Trial 324 finished with value: 0.9497032547524948 and parameters: {'solver': 'saga', 'C': 0.0010983261511796727, 'l1_ratio': 0.9560049181613453, 'class_weight': None, 'fit_intercept': True, 'tol': 1.274532381122566e-06, 'max_iter': 2264}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  63%|██████▎   | 317/500 [16:30<26:21,  8.64s/it]

[I 2026-05-18 11:50:11,656] Trial 325 finished with value: 0.9497056839137622 and parameters: {'solver': 'saga', 'C': 0.0009885561393032484, 'l1_ratio': 0.9786598870713468, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2845793802923766e-06, 'max_iter': 2356}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  64%|██████▎   | 318/500 [16:33<21:22,  7.05s/it]

[I 2026-05-18 11:50:14,980] Trial 326 finished with value: 0.9497020669391396 and parameters: {'solver': 'saga', 'C': 0.00103258572514298, 'l1_ratio': 0.9531649441833847, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3027939607565232e-06, 'max_iter': 2342}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  64%|██████▍   | 319/500 [16:41<22:11,  7.35s/it]

[I 2026-05-18 11:50:23,055] Trial 327 finished with value: 0.9497050101489911 and parameters: {'solver': 'saga', 'C': 0.0008598931642572451, 'l1_ratio': 0.9843837642344979, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015722224064325748, 'max_iter': 2162}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  64%|██████▍   | 320/500 [16:55<27:58,  9.32s/it]

[I 2026-05-18 11:50:36,966] Trial 328 finished with value: 0.9497033233508281 and parameters: {'solver': 'saga', 'C': 0.0022919710894679177, 'l1_ratio': 0.9819062734933349, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5037728897380555e-06, 'max_iter': 1288}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  64%|██████▍   | 321/500 [17:00<23:22,  7.83s/it]

[I 2026-05-18 11:50:41,330] Trial 329 finished with value: 0.9497034998488134 and parameters: {'solver': 'saga', 'C': 0.0022488624916468815, 'l1_ratio': 0.9814461754989964, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5495559045333816e-06, 'max_iter': 1473}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  64%|██████▍   | 322/500 [17:06<22:20,  7.53s/it]

[I 2026-05-18 11:50:48,147] Trial 330 finished with value: 0.9497028470479467 and parameters: {'solver': 'saga', 'C': 0.002482645404087356, 'l1_ratio': 0.9815105467339814, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5468347278269579e-06, 'max_iter': 2010}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  65%|██████▍   | 323/500 [17:22<29:09,  9.88s/it]

[I 2026-05-18 11:51:03,531] Trial 331 finished with value: 0.9497054533752551 and parameters: {'solver': 'saga', 'C': 0.002130255575035111, 'l1_ratio': 0.9521065681318239, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2443615212467356e-06, 'max_iter': 1482}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  65%|██████▍   | 324/500 [17:30<27:18,  9.31s/it]

[I 2026-05-18 11:51:11,489] Trial 332 finished with value: 0.9497040344143446 and parameters: {'solver': 'saga', 'C': 0.0013717160494925598, 'l1_ratio': 0.9492016264186363, 'class_weight': None, 'fit_intercept': True, 'tol': 1.296851715669521e-06, 'max_iter': 2010}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  65%|██████▌   | 325/500 [17:47<33:45, 11.58s/it]

[I 2026-05-18 11:51:28,358] Trial 334 finished with value: 0.9497028836904796 and parameters: {'solver': 'saga', 'C': 0.0012370343219611987, 'l1_ratio': 0.9470309698363055, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2209529773398733e-06, 'max_iter': 2153}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  65%|██████▌   | 326/500 [17:59<34:22, 11.86s/it]

[I 2026-05-18 11:51:40,870] Trial 335 finished with value: 0.9496280934225384 and parameters: {'solver': 'saga', 'C': 16.37313432732491, 'l1_ratio': 0.999411151714142, 'class_weight': None, 'fit_intercept': True, 'tol': 2.131269664173845e-06, 'max_iter': 2157}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  65%|██████▌   | 327/500 [18:11<34:02, 11.80s/it]

[I 2026-05-18 11:51:52,529] Trial 336 finished with value: 0.9496994862054609 and parameters: {'solver': 'saga', 'C': 0.000770464164246905, 'l1_ratio': 0.9636525096837432, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0603830660668927e-06, 'max_iter': 1546}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  66%|██████▌   | 328/500 [18:17<29:16, 10.21s/it]

[I 2026-05-18 11:51:59,054] Trial 297 finished with value: 0.949631165432888 and parameters: {'solver': 'saga', 'C': 0.4582118245021478, 'l1_ratio': 0.9580183863795653, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9675487314761203e-06, 'max_iter': 2078}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  66%|██████▌   | 329/500 [18:24<26:29,  9.30s/it]

[I 2026-05-18 11:52:06,210] Trial 337 finished with value: 0.9496975017985602 and parameters: {'solver': 'saga', 'C': 0.0007205343699981669, 'l1_ratio': 0.9616629736594036, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7255596307543507e-06, 'max_iter': 2008}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  66%|██████▌   | 330/500 [18:37<29:34, 10.44s/it]

[I 2026-05-18 11:52:19,319] Trial 338 finished with value: 0.9497054682005601 and parameters: {'solver': 'saga', 'C': 0.0011381461991486522, 'l1_ratio': 0.9687135107349434, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6766864073852049e-06, 'max_iter': 2066}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  66%|██████▌   | 331/500 [18:43<25:00,  8.88s/it]

[I 2026-05-18 11:52:24,553] Trial 339 finished with value: 0.9497004981447171 and parameters: {'solver': 'saga', 'C': 0.001140649574581038, 'l1_ratio': 0.938439279841728, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2134180757823884e-06, 'max_iter': 2019}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  66%|██████▋   | 332/500 [18:46<20:18,  7.25s/it]

[I 2026-05-18 11:52:28,019] Trial 340 finished with value: 0.94962801452777 and parameters: {'solver': 'saga', 'C': 60.240025787849135, 'l1_ratio': 0.9335800786444546, 'class_weight': None, 'fit_intercept': True, 'tol': 5.968558958464272e-05, 'max_iter': 1949}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  67%|██████▋   | 333/500 [18:47<14:49,  5.33s/it]

[I 2026-05-18 11:52:28,852] Trial 341 pruned.

Best trial: 322. Best value: 0.949706:  67%|██████▋   | 334/500 [18:49<11:44,  4.24s/it]

[I 2026-05-18 11:52:30,559] Trial 333 finished with value: 0.9496280795956065 and parameters: {'solver': 'saga', 'C': 21.378843743024714, 'l1_ratio': 0.9480810207972623, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2005687425420605e-06, 'max_iter': 2196}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  67%|██████▋   | 335/500 [18:49<08:28,  3.08s/it]

[I 2026-05-18 11:52:30,937] Trial 315 finished with value: 0.9496323107861027 and parameters: {'solver': 'saga', 'C': 0.3376964333444062, 'l1_ratio': 0.957072079385713, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3098267215511493e-06, 'max_iter': 1664}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  67%|██████▋   | 336/500 [18:56<11:24,  4.18s/it]

[I 2026-05-18 11:52:37,664] Trial 342 pruned.

Best trial: 322. Best value: 0.949706:  67%|██████▋   | 337/500 [18:58<09:22,  3.45s/it]

[I 2026-05-18 11:52:39,406] Trial 343 pruned.

Best trial: 322. Best value: 0.949706:  68%|██████▊   | 338/500 [19:14<19:30,  7.22s/it]

[I 2026-05-18 11:52:55,449] Trial 344 finished with value: 0.9497047950421719 and parameters: {'solver': 'saga', 'C': 0.001751428670995503, 'l1_ratio': 0.9824710459241508, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1878011424757867e-06, 'max_iter': 2225}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  68%|██████▊   | 339/500 [19:16<15:04,  5.62s/it]

[I 2026-05-18 11:52:57,332] Trial 345 finished with value: 0.9497044762072827 and parameters: {'solver': 'saga', 'C': 0.0017971138442958543, 'l1_ratio': 0.9832283222805918, 'class_weight': None, 'fit_intercept': True, 'tol': 1.219936196158684e-06, 'max_iter': 1445}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  68%|██████▊   | 340/500 [19:16<11:00,  4.13s/it]

[I 2026-05-18 11:52:57,985] Trial 346 finished with value: 0.9497049235553969 and parameters: {'solver': 'saga', 'C': 0.0016420052134651472, 'l1_ratio': 0.9841579825273442, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5049257200558016e-06, 'max_iter': 2270}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  68%|██████▊   | 341/500 [19:23<13:16,  5.01s/it]

[I 2026-05-18 11:53:05,036] Trial 347 finished with value: 0.9497047951029078 and parameters: {'solver': 'saga', 'C': 0.000841236112705963, 'l1_ratio': 0.9840388467224316, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4582107976866025e-06, 'max_iter': 1894}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  68%|██████▊   | 342/500 [19:26<11:41,  4.44s/it]

[I 2026-05-18 11:53:08,162] Trial 348 finished with value: 0.9497021326637205 and parameters: {'solver': 'saga', 'C': 0.0008145026873203131, 'l1_ratio': 0.9980918314526996, 'class_weight': None, 'fit_intercept': True, 'tol': 1.527236321483953e-06, 'max_iter': 1913}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  69%|██████▊   | 343/500 [19:40<19:01,  7.27s/it]

[I 2026-05-18 11:53:22,033] Trial 350 finished with value: 0.9496872260595042 and parameters: {'solver': 'saga', 'C': 0.0008174041100333848, 'l1_ratio': 0.9080629422546215, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5802955745981064e-06, 'max_iter': 1906}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  69%|██████▉   | 344/500 [19:42<14:47,  5.69s/it]

[I 2026-05-18 11:53:24,023] Trial 351 finished with value: 0.9496890373908318 and parameters: {'solver': 'saga', 'C': 0.0008639163670765446, 'l1_ratio': 0.9109734961690092, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5026875749846036e-06, 'max_iter': 1897}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  69%|██████▉   | 345/500 [19:49<15:50,  6.13s/it]

[I 2026-05-18 11:53:31,197] Trial 349 finished with value: 0.949702616437718 and parameters: {'solver': 'saga', 'C': 0.0008639691693128116, 'l1_ratio': 0.998405759968361, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5117925620713822e-06, 'max_iter': 1935}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  69%|██████▉   | 346/500 [19:50<11:25,  4.45s/it]

[I 2026-05-18 11:53:31,723] Trial 352 finished with value: 0.9497039616774556 and parameters: {'solver': 'saga', 'C': 0.0030623501426316076, 'l1_ratio': 0.9039122930105263, 'class_weight': None, 'fit_intercept': True, 'tol': 1.676272973386325e-06, 'max_iter': 1564}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  69%|██████▉   | 347/500 [19:52<09:43,  3.81s/it]

[I 2026-05-18 11:53:34,040] Trial 353 finished with value: 0.9496800781898992 and parameters: {'solver': 'saga', 'C': 0.0005996850905758264, 'l1_ratio': 0.9079210501812512, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7501418267142803e-06, 'max_iter': 1553}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  70%|██████▉   | 348/500 [20:06<17:04,  6.74s/it]

[I 2026-05-18 11:53:47,605] Trial 354 finished with value: 0.949703603628266 and parameters: {'solver': 'saga', 'C': 0.003000465762071996, 'l1_ratio': 0.9641785611528472, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7978994737924396e-06, 'max_iter': 2084}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  70%|██████▉   | 349/500 [20:07<12:38,  5.03s/it]

[I 2026-05-18 11:53:48,644] Trial 359 pruned.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 322. Best value: 0.949706:  70%|███████   | 350/500 [20:09<10:35,  4.24s/it]

[I 2026-05-18 11:53:51,019] Trial 355 finished with value: 0.9496911175140552 and parameters: {'solver': 'saga', 'C': 0.0005654421115101164, 'l1_ratio': 0.9652044266822075, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0060646736197798e-06, 'max_iter': 1521}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  70%|███████   | 351/500 [20:16<12:38,  5.09s/it]

[I 2026-05-18 11:53:58,115] Trial 357 finished with value: 0.9497054148418685 and parameters: {'solver': 'saga', 'C': 0.0012182249218841133, 'l1_ratio': 0.9644280260542716, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1804675620393826e-06, 'max_iter': 2120}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  70%|███████   | 352/500 [20:17<09:37,  3.90s/it]

[I 2026-05-18 11:53:59,227] Trial 317 finished with value: 0.9496310060167549 and parameters: {'solver': 'saga', 'C': 0.4825592572161092, 'l1_ratio': 0.9568197204330308, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1876058087827656e-06, 'max_iter': 1930}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  71%|███████   | 353/500 [20:20<08:54,  3.64s/it]

[I 2026-05-18 11:54:02,267] Trial 358 finished with value: 0.949704660705043 and parameters: {'solver': 'saga', 'C': 0.0012058146709229803, 'l1_ratio': 0.9603641605258566, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0077006578093832e-06, 'max_iter': 2112}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  71%|███████   | 354/500 [20:34<16:10,  6.65s/it]

[I 2026-05-18 11:54:15,939] Trial 360 finished with value: 0.9497007603624548 and parameters: {'solver': 'saga', 'C': 0.0012659034932588481, 'l1_ratio': 0.9334181656657186, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0084644947242944e-06, 'max_iter': 1470}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  71%|███████   | 355/500 [20:35<12:12,  5.05s/it]

[I 2026-05-18 11:54:17,274] Trial 361 finished with value: 0.9497003710946542 and parameters: {'solver': 'saga', 'C': 0.0012183384457729312, 'l1_ratio': 0.9340590511358466, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2051337208322853e-06, 'max_iter': 1442}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  71%|███████   | 356/500 [20:43<13:36,  5.67s/it]

[I 2026-05-18 11:54:24,378] Trial 363 finished with value: 0.9497016561824763 and parameters: {'solver': 'saga', 'C': 0.0012988716999684628, 'l1_ratio': 0.9368607372651537, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0757872372247e-06, 'max_iter': 1296}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  71%|███████▏  | 357/500 [20:48<13:07,  5.51s/it]

[I 2026-05-18 11:54:29,504] Trial 364 finished with value: 0.9497045679599634 and parameters: {'solver': 'saga', 'C': 0.002291908857094385, 'l1_ratio': 0.9338332745592468, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3817003195440497e-06, 'max_iter': 1422}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  72%|███████▏  | 358/500 [20:52<11:51,  5.01s/it]

[I 2026-05-18 11:54:33,357] Trial 120 finished with value: 0.9496511444359005 and parameters: {'solver': 'saga', 'C': 0.057400652315131195, 'l1_ratio': 0.9985193885115226, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6299545332238826e-06, 'max_iter': 3590}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  72%|███████▏  | 359/500 [21:09<20:36,  8.77s/it]

[I 2026-05-18 11:54:50,898] Trial 367 finished with value: 0.949473470098722 and parameters: {'solver': 'saga', 'C': 0.002327198615342651, 'l1_ratio': 0.03119250343776836, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4190420675547372e-06, 'max_iter': 1679}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  72%|███████▏  | 360/500 [21:13<16:49,  7.21s/it]

[I 2026-05-18 11:54:54,477] Trial 368 finished with value: 0.949703195816696 and parameters: {'solver': 'saga', 'C': 0.00232595481715069, 'l1_ratio': 0.9817592747753817, 'class_weight': None, 'fit_intercept': True, 'tol': 1.406825038439724e-06, 'max_iter': 1810}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  72%|███████▏  | 361/500 [21:33<25:54, 11.19s/it]

[I 2026-05-18 11:55:14,935] Trial 370 finished with value: 0.9497042087697786 and parameters: {'solver': 'saga', 'C': 0.0021057849651296445, 'l1_ratio': 0.9788578379776578, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2562636160455687e-06, 'max_iter': 2003}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  72%|███████▏  | 362/500 [21:40<22:29,  9.78s/it]

[I 2026-05-18 11:55:21,441] Trial 356 finished with value: 0.9496422114801583 and parameters: {'solver': 'saga', 'C': 0.10005287000773887, 'l1_ratio': 0.9638343061926923, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8709114429256213e-06, 'max_iter': 1534}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  73%|███████▎  | 363/500 [21:57<27:19, 11.97s/it]

[I 2026-05-18 11:55:38,503] Trial 372 finished with value: 0.9495618111532231 and parameters: {'solver': 'saga', 'C': 0.00019440956669698758, 'l1_ratio': 0.9983264675479802, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8763592115217093e-06, 'max_iter': 2407}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  73%|███████▎  | 364/500 [22:09<27:37, 12.19s/it]

[I 2026-05-18 11:55:51,199] Trial 366 finished with value: 0.9496990116033039 and parameters: {'solver': 'saga', 'C': 0.002180261843252067, 'l1_ratio': 0.9988561253968951, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3762728908444696e-06, 'max_iter': 1277}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  73%|███████▎  | 365/500 [22:27<30:56, 13.75s/it]

[I 2026-05-18 11:56:08,599] Trial 375 finished with value: 0.9497017295589003 and parameters: {'solver': 'saga', 'C': 0.0010878654568477744, 'l1_ratio': 0.9477112622217175, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010053659182704004, 'max_iter': 1777}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  73%|███████▎  | 366/500 [22:53<38:46, 17.36s/it]

[I 2026-05-18 11:56:34,380] Trial 376 finished with value: 0.9497044132705736 and parameters: {'solver': 'saga', 'C': 0.0015149752289994555, 'l1_ratio': 0.9466506324274118, 'class_weight': None, 'fit_intercept': True, 'tol': 1.193996552538953e-06, 'max_iter': 2003}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  73%|███████▎  | 367/500 [23:18<44:02, 19.87s/it]

[I 2026-05-18 11:57:00,103] Trial 377 finished with value: 0.949693699412801 and parameters: {'solver': 'saga', 'C': 0.0005835782790197774, 'l1_ratio': 0.9714404103414335, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4558253670630784e-06, 'max_iter': 2525}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  74%|███████▎  | 368/500 [23:24<34:04, 15.49s/it]

[I 2026-05-18 11:57:05,368] Trial 316 finished with value: 0.9496316431912994 and parameters: {'solver': 'saga', 'C': 0.3951429156877601, 'l1_ratio': 0.979744114639391, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1959131598764975e-06, 'max_iter': 1923}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  74%|███████▍  | 369/500 [23:45<37:41, 17.27s/it]

[I 2026-05-18 11:57:26,780] Trial 378 finished with value: 0.9497053990783251 and parameters: {'solver': 'saga', 'C': 0.0010044002085286996, 'l1_ratio': 0.9752355017262249, 'class_weight': None, 'fit_intercept': True, 'tol': 1.170169899101504e-06, 'max_iter': 1648}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  74%|███████▍  | 371/500 [23:50<20:31,  9.55s/it]

[I 2026-05-18 11:57:31,728] Trial 379 finished with value: 0.9493689321405192 and parameters: {'solver': 'saga', 'C': 0.0010197092488227481, 'l1_ratio': 0.3105437336065623, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6593559658731698e-06, 'max_iter': 1661}. Best is trial 322 with value: 0.9497063898914387.
[I 2026-05-18 11:57:31,895] Trial 286 finished with value: 0.9496295343484267 and parameters: {'solver': 'saga', 'C': 0.9100746858896085, 'l1_ratio': 0.9702419276236538, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3124399414392794e-06, 'max_iter': 1838}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  74%|███████▍  | 372/500 [24:10<27:08, 12.72s/it]

[I 2026-05-18 11:57:52,019] Trial 380 finished with value: 0.9497046673625424 and parameters: {'solver': 'saga', 'C': 0.0015803101782848935, 'l1_ratio': 0.9478512899782721, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7721813197182575e-06, 'max_iter': 1819}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  75%|███████▍  | 373/500 [24:14<21:26, 10.13s/it]

[I 2026-05-18 11:57:56,099] Trial 365 finished with value: 0.9496982153310721 and parameters: {'solver': 'saga', 'C': 0.002335838947197415, 'l1_ratio': 0.9996398928056323, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2638701779932086e-06, 'max_iter': 2487}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  75%|███████▍  | 374/500 [24:36<28:30, 13.57s/it]

[I 2026-05-18 11:58:17,698] Trial 383 finished with value: 0.9497044329553171 and parameters: {'solver': 'saga', 'C': 0.0014751123960614768, 'l1_ratio': 0.9487549937538637, 'class_weight': None, 'fit_intercept': True, 'tol': 1.00165384936389e-06, 'max_iter': 2054}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  75%|███████▌  | 375/500 [24:40<22:37, 10.86s/it]

[I 2026-05-18 11:58:22,227] Trial 384 finished with value: 0.9496286182015599 and parameters: {'solver': 'saga', 'C': 0.003239426238503276, 'l1_ratio': 0.1912113623457854, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4951463183143909e-06, 'max_iter': 2042}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  75%|███████▌  | 376/500 [24:43<17:27,  8.44s/it]

[I 2026-05-18 11:58:25,040] Trial 373 finished with value: 0.9497019445839129 and parameters: {'solver': 'saga', 'C': 0.0011291632698969582, 'l1_ratio': 0.9997613395794129, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1847189548342322e-06, 'max_iter': 2442}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  75%|███████▌  | 377/500 [25:02<23:27, 11.44s/it]

[I 2026-05-18 11:58:43,481] Trial 385 finished with value: 0.9497044640052261 and parameters: {'solver': 'saga', 'C': 0.002865078769703943, 'l1_ratio': 0.9207088505566949, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4321555911805489e-06, 'max_iter': 2178}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  76%|███████▌  | 378/500 [25:07<19:18,  9.50s/it]

[I 2026-05-18 11:58:48,424] Trial 386 finished with value: 0.9496893111814095 and parameters: {'solver': 'saga', 'C': 0.0007195329273979919, 'l1_ratio': 0.9300987525588775, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2257886849198844e-06, 'max_iter': 1986}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  76%|███████▌  | 379/500 [25:09<14:33,  7.22s/it]

[I 2026-05-18 11:58:50,348] Trial 387 finished with value: 0.9496864220012228 and parameters: {'solver': 'saga', 'C': 0.0006519471627777895, 'l1_ratio': 0.9277281480090375, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3882490212986407e-06, 'max_iter': 2185}. Best is trial 322 with value: 0.9497063898914387.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 322. Best value: 0.949706:  76%|███████▌  | 380/500 [25:27<21:13, 10.61s/it]

[I 2026-05-18 11:59:08,857] Trial 388 finished with value: 0.9497004685685544 and parameters: {'solver': 'saga', 'C': 0.0007930212232080369, 'l1_ratio': 0.9652505311217268, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0073993370153837e-06, 'max_iter': 2212}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  76%|███████▌  | 381/500 [25:51<29:13, 14.74s/it]

[I 2026-05-18 11:59:33,229] Trial 391 finished with value: 0.9497050413403331 and parameters: {'solver': 'saga', 'C': 0.0015621656797917308, 'l1_ratio': 0.9513977903628077, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8124065884069131e-06, 'max_iter': 1586}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  76%|███████▋  | 382/500 [26:17<35:19, 17.96s/it]

[I 2026-05-18 11:59:58,720] Trial 392 finished with value: 0.9497053643938035 and parameters: {'solver': 'saga', 'C': 0.0017904571586711117, 'l1_ratio': 0.976209955727516, 'class_weight': None, 'fit_intercept': True, 'tol': 2.366558069159459e-06, 'max_iter': 1784}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  77%|███████▋  | 383/500 [26:43<39:34, 20.30s/it]

[I 2026-05-18 12:00:24,471] Trial 393 finished with value: 0.9497063389731417 and parameters: {'solver': 'saga', 'C': 0.0012338632674548768, 'l1_ratio': 0.9815239850080406, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6817025043955518e-06, 'max_iter': 1972}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  77%|███████▋  | 384/500 [26:49<31:06, 16.09s/it]

[I 2026-05-18 12:00:30,742] Trial 362 finished with value: 0.9496291728974761 and parameters: {'solver': 'saga', 'C': 1.2652865966287008, 'l1_ratio': 0.9359039274091626, 'class_weight': None, 'fit_intercept': True, 'tol': 2.200571924311389e-06, 'max_iter': 1436}. Best is trial 322 with value: 0.9497063898914387.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 322. Best value: 0.949706:  77%|███████▋  | 385/500 [27:08<32:24, 16.91s/it]

[I 2026-05-18 12:00:49,570] Trial 394 finished with value: 0.9497060847278334 and parameters: {'solver': 'saga', 'C': 0.0010296341029328664, 'l1_ratio': 0.9816457377886241, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9530514657577315e-06, 'max_iter': 2101}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  77%|███████▋  | 386/500 [27:14<25:47, 13.58s/it]

[I 2026-05-18 12:00:55,357] Trial 395 finished with value: 0.9497062028240864 and parameters: {'solver': 'saga', 'C': 0.0010714109499215278, 'l1_ratio': 0.9820370170364527, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6762788564755966e-06, 'max_iter': 2085}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  77%|███████▋  | 387/500 [27:26<25:09, 13.36s/it]

[I 2026-05-18 12:01:08,221] Trial 397 pruned.

Best trial: 322. Best value: 0.949706:  78%|███████▊  | 388/500 [27:50<30:37, 16.40s/it]

[I 2026-05-18 12:01:31,709] Trial 398 finished with value: 0.9497055671251283 and parameters: {'solver': 'saga', 'C': 0.0009198570688223427, 'l1_ratio': 0.984587043867953, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5776807317130433e-06, 'max_iter': 2134}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  78%|███████▊  | 389/500 [28:09<31:56, 17.26s/it]

[I 2026-05-18 12:01:50,997] Trial 390 finished with value: 0.9496284075370085 and parameters: {'solver': 'saga', 'C': 4.725435530591916, 'l1_ratio': 0.5589452396407609, 'class_weight': None, 'fit_intercept': True, 'tol': 1.829183424629366e-06, 'max_iter': 1581}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  78%|███████▊  | 390/500 [28:14<24:59, 13.63s/it]

[I 2026-05-18 12:01:56,163] Trial 399 finished with value: 0.9496924382497868 and parameters: {'solver': 'saga', 'C': 0.0005413703697533832, 'l1_ratio': 0.9818114585048127, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0677470548020406e-06, 'max_iter': 2060}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  78%|███████▊  | 391/500 [28:33<27:20, 15.05s/it]

[I 2026-05-18 12:02:14,525] Trial 400 finished with value: 0.949706220881604 and parameters: {'solver': 'saga', 'C': 0.001074120287010122, 'l1_ratio': 0.9851091312367012, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1023604635199493e-06, 'max_iter': 2245}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  78%|███████▊  | 392/500 [28:37<21:04, 11.71s/it]

[I 2026-05-18 12:02:18,426] Trial 396 finished with value: 0.949702342657179 and parameters: {'solver': 'saga', 'C': 0.0009474770033564594, 'l1_ratio': 0.9994906036706763, 'class_weight': None, 'fit_intercept': True, 'tol': 2.000803177790882e-06, 'max_iter': 2269}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  79%|███████▊  | 393/500 [28:41<16:46,  9.41s/it]

[I 2026-05-18 12:02:22,462] Trial 401 finished with value: 0.9496384154798749 and parameters: {'solver': 'saga', 'C': 0.00031041384331756975, 'l1_ratio': 0.9830877885022132, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6706930836244434e-06, 'max_iter': 2273}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  79%|███████▉  | 394/500 [28:55<19:26, 11.01s/it]

[I 2026-05-18 12:02:37,205] Trial 402 finished with value: 0.9496084464605057 and parameters: {'solver': 'saga', 'C': 0.0002863634111549866, 'l1_ratio': 0.9967147431007454, 'class_weight': None, 'fit_intercept': True, 'tol': 2.318494135483162e-06, 'max_iter': 2253}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  79%|███████▉  | 395/500 [29:05<18:23, 10.51s/it]

[I 2026-05-18 12:02:46,538] Trial 404 finished with value: 0.94969696859648 and parameters: {'solver': 'saga', 'C': 0.0006007069702651818, 'l1_ratio': 0.983113986136382, 'class_weight': None, 'fit_intercept': True, 'tol': 2.516912497560004e-06, 'max_iter': 2157}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  79%|███████▉  | 396/500 [29:20<20:42, 11.95s/it]

[I 2026-05-18 12:03:01,851] Trial 405 finished with value: 0.9496925335347411 and parameters: {'solver': 'saga', 'C': 0.0006393814981554556, 'l1_ratio': 0.9549864789849538, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6700895986527285e-06, 'max_iter': 2161}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  79%|███████▉  | 397/500 [29:31<20:03, 11.69s/it]

[I 2026-05-18 12:03:12,934] Trial 406 finished with value: 0.9497036614243427 and parameters: {'solver': 'saga', 'C': 0.0011386736700272602, 'l1_ratio': 0.9562909478553024, 'class_weight': None, 'fit_intercept': True, 'tol': 1.617270547766245e-06, 'max_iter': 2182}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  80%|███████▉  | 398/500 [29:36<16:36,  9.77s/it]

[I 2026-05-18 12:03:18,240] Trial 270 finished with value: 0.949628099603888 and parameters: {'solver': 'saga', 'C': 15.942282670599736, 'l1_ratio': 0.9633656240643629, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3869186427300243e-06, 'max_iter': 1425}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  80%|███████▉  | 399/500 [29:39<12:53,  7.65s/it]

[I 2026-05-18 12:03:20,947] Trial 403 finished with value: 0.9497004436697878 and parameters: {'solver': 'saga', 'C': 0.0007681036345783578, 'l1_ratio': 0.9993110058145068, 'class_weight': None, 'fit_intercept': True, 'tol': 2.381534419175392e-06, 'max_iter': 2239}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  80%|████████  | 400/500 [29:46<12:30,  7.51s/it]

[I 2026-05-18 12:03:28,113] Trial 407 finished with value: 0.9497054836564945 and parameters: {'solver': 'saga', 'C': 0.001126390231577599, 'l1_ratio': 0.9699891474882274, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6371450566040174e-06, 'max_iter': 2383}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  80%|████████  | 401/500 [29:47<08:58,  5.43s/it]

[I 2026-05-18 12:03:28,716] Trial 300 finished with value: 0.9496281243296645 and parameters: {'solver': 'saga', 'C': 10.822033661188238, 'l1_ratio': 0.9789845927727051, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9985338084733472e-06, 'max_iter': 2067}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  80%|████████  | 402/500 [29:57<11:03,  6.77s/it]

[I 2026-05-18 12:03:38,612] Trial 408 finished with value: 0.9497022459040746 and parameters: {'solver': 'saga', 'C': 0.0007936845057731742, 'l1_ratio': 0.9734839346585472, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9131145753640543e-06, 'max_iter': 2352}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  81%|████████  | 403/500 [30:03<10:36,  6.57s/it]

[I 2026-05-18 12:03:44,693] Trial 409 finished with value: 0.9497051044906627 and parameters: {'solver': 'saga', 'C': 0.0009156561682251855, 'l1_ratio': 0.9790058638208208, 'class_weight': None, 'fit_intercept': True, 'tol': 1.998895061619807e-06, 'max_iter': 1978}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 322. Best value: 0.949706:  81%|████████  | 404/500 [30:04<08:01,  5.01s/it]

[I 2026-05-18 12:03:46,081] Trial 410 finished with value: 0.9497063565395948 and parameters: {'solver': 'saga', 'C': 0.0011935438377133167, 'l1_ratio': 0.9772513352141727, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8944436582728194e-06, 'max_iter': 2362}. Best is trial 322 with value: 0.9497063898914387.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 322. Best value: 0.949706:  81%|████████  | 405/500 [30:12<09:22,  5.92s/it]

[I 2026-05-18 12:03:54,107] Trial 412 finished with value: 0.9496989978532048 and parameters: {'solver': 'saga', 'C': 0.0009199850274619112, 'l1_ratio': 0.9473934527504118, 'class_weight': None, 'fit_intercept': True, 'tol': 2.010361288496755e-06, 'max_iter': 2012}. Best is trial 322 with value: 0.9497063898914387.

Best trial: 411. Best value: 0.949706:  81%|████████  | 406/500 [30:13<06:50,  4.37s/it]

[I 2026-05-18 12:03:54,868] Trial 411 finished with value: 0.9497064502408218 and parameters: {'solver': 'saga', 'C': 0.0011427696891455742, 'l1_ratio': 0.9798523189723278, 'class_weight': None, 'fit_intercept': True, 'tol': 2.014092459415771e-06, 'max_iter': 1984}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  81%|████████▏ | 407/500 [30:22<09:01,  5.83s/it]

[I 2026-05-18 12:04:04,101] Trial 413 finished with value: 0.949701853021949 and parameters: {'solver': 'saga', 'C': 0.0011296486765991496, 'l1_ratio': 0.9458056054375781, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4701671833618827e-06, 'max_iter': 1330}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  82%|████████▏ | 408/500 [30:25<07:30,  4.89s/it]

[I 2026-05-18 12:04:06,811] Trial 417 pruned.

Best trial: 411. Best value: 0.949706:  82%|████████▏ | 409/500 [30:29<06:56,  4.57s/it]

[I 2026-05-18 12:04:10,641] Trial 414 finished with value: 0.9497028270824993 and parameters: {'solver': 'saga', 'C': 0.001242611519310025, 'l1_ratio': 0.9460045330056995, 'class_weight': None, 'fit_intercept': True, 'tol': 1.467266421235491e-06, 'max_iter': 1308}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  82%|████████▏ | 410/500 [30:32<06:10,  4.11s/it]

[I 2026-05-18 12:04:13,666] Trial 415 finished with value: 0.9496285186400373 and parameters: {'solver': 'saga', 'C': 2.7027747995168956, 'l1_ratio': 0.9992129182930658, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5062242724934752e-06, 'max_iter': 1365}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  82%|████████▏ | 411/500 [30:45<10:15,  6.91s/it]

[I 2026-05-18 12:04:27,130] Trial 416 finished with value: 0.9497030266628332 and parameters: {'solver': 'saga', 'C': 0.001224902435870297, 'l1_ratio': 0.9975000132329152, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6022012411852497e-06, 'max_iter': 1345}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  82%|████████▏ | 412/500 [30:50<09:05,  6.20s/it]

[I 2026-05-18 12:04:31,659] Trial 418 finished with value: 0.9496875316281954 and parameters: {'solver': 'saga', 'C': 0.0005181584570513955, 'l1_ratio': 0.9987712999019835, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6688958248245854e-06, 'max_iter': 1955}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  83%|████████▎ | 413/500 [30:50<06:34,  4.54s/it]

[I 2026-05-18 12:04:32,314] Trial 419 finished with value: 0.9497063903779074 and parameters: {'solver': 'saga', 'C': 0.0012187662194907884, 'l1_ratio': 0.9822484374725635, 'class_weight': None, 'fit_intercept': True, 'tol': 2.699086277022704e-06, 'max_iter': 2311}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  83%|████████▎ | 414/500 [30:55<06:34,  4.59s/it]

[I 2026-05-18 12:04:37,027] Trial 420 finished with value: 0.9495453989159224 and parameters: {'solver': 'saga', 'C': 0.000762690411035735, 'l1_ratio': 0.9997250403014729, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.524248186804833e-06, 'max_iter': 2329}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  83%|████████▎ | 415/500 [30:57<05:19,  3.75s/it]

[I 2026-05-18 12:04:38,837] Trial 421 finished with value: 0.9496900208157835 and parameters: {'solver': 'saga', 'C': 0.000517736693105745, 'l1_ratio': 0.9804121637287421, 'class_weight': None, 'fit_intercept': True, 'tol': 2.217738252215218e-06, 'max_iter': 2086}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  83%|████████▎ | 416/500 [31:11<09:28,  6.77s/it]

[I 2026-05-18 12:04:52,631] Trial 422 finished with value: 0.9495644466184154 and parameters: {'solver': 'saga', 'C': 0.0007272315024373918, 'l1_ratio': 0.9810461629559245, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.3935723202083856e-06, 'max_iter': 2326}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  83%|████████▎ | 417/500 [31:14<08:01,  5.81s/it]

[I 2026-05-18 12:04:56,187] Trial 423 finished with value: 0.9495790660904924 and parameters: {'solver': 'saga', 'C': 0.0019665464298139553, 'l1_ratio': 0.9788069712060042, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.1836127851032536e-06, 'max_iter': 4733}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  84%|████████▎ | 418/500 [31:17<06:28,  4.73s/it]

[I 2026-05-18 12:04:58,432] Trial 424 finished with value: 0.9490540668246071 and parameters: {'solver': 'saga', 'C': 0.000733577628885929, 'l1_ratio': 0.09004504105498706, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.1952843119905368e-06, 'max_iter': 2130}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  84%|████████▍ | 419/500 [31:20<05:55,  4.38s/it]

[I 2026-05-18 12:05:01,990] Trial 425 finished with value: 0.9497056349478173 and parameters: {'solver': 'saga', 'C': 0.001012432964752893, 'l1_ratio': 0.9768572546921803, 'class_weight': None, 'fit_intercept': True, 'tol': 2.132515774365107e-06, 'max_iter': 2120}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  84%|████████▍ | 420/500 [31:22<04:51,  3.65s/it]

[I 2026-05-18 12:05:03,919] Trial 426 finished with value: 0.9497045210978141 and parameters: {'solver': 'saga', 'C': 0.00207104526442831, 'l1_ratio': 0.9774286861438254, 'class_weight': None, 'fit_intercept': True, 'tol': 1.775074379710073e-06, 'max_iter': 1162}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  84%|████████▍ | 421/500 [31:37<09:05,  6.91s/it]

[I 2026-05-18 12:05:18,431] Trial 427 finished with value: 0.9495752227538212 and parameters: {'solver': 'saga', 'C': 0.0021973317050531147, 'l1_ratio': 0.26687933322754165, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7193521378618754e-06, 'max_iter': 1886}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  84%|████████▍ | 422/500 [31:39<07:05,  5.45s/it]

[I 2026-05-18 12:05:20,473] Trial 428 finished with value: 0.9492154513711153 and parameters: {'solver': 'saga', 'C': 0.0011299111526957262, 'l1_ratio': 0.07843872192709711, 'class_weight': None, 'fit_intercept': True, 'tol': 1.707446646307513e-06, 'max_iter': 2679}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  85%|████████▍ | 423/500 [31:40<05:19,  4.14s/it]

[I 2026-05-18 12:05:21,582] Trial 374 finished with value: 0.9496290780606544 and parameters: {'solver': 'saga', 'C': 1.3631418982214458, 'l1_ratio': 0.9512477349174318, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2404176259368264e-06, 'max_iter': 1781}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  85%|████████▍ | 424/500 [31:42<04:34,  3.62s/it]

[I 2026-05-18 12:05:23,964] Trial 429 finished with value: 0.9497036381665975 and parameters: {'solver': 'saga', 'C': 0.0011045690100086319, 'l1_ratio': 0.9590264712424744, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7410598031905347e-06, 'max_iter': 1836}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  85%|████████▌ | 425/500 [31:45<04:21,  3.49s/it]

[I 2026-05-18 12:05:27,162] Trial 430 finished with value: 0.9497047439837853 and parameters: {'solver': 'saga', 'C': 0.001375960148492035, 'l1_ratio': 0.9541972701882443, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6988656212946862e-06, 'max_iter': 1858}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  85%|████████▌ | 426/500 [31:46<03:25,  2.78s/it]

[I 2026-05-18 12:05:28,301] Trial 431 finished with value: 0.9497043291751787 and parameters: {'solver': 'saga', 'C': 0.0013055560028734383, 'l1_ratio': 0.9535362764609756, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7305631431724185e-06, 'max_iter': 1851}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  85%|████████▌ | 427/500 [32:00<07:17,  6.00s/it]

[I 2026-05-18 12:05:41,802] Trial 437 pruned.

Best trial: 411. Best value: 0.949706:  86%|████████▌ | 428/500 [32:00<05:11,  4.33s/it]

[I 2026-05-18 12:05:42,220] Trial 432 finished with value: 0.9496986288905778 and parameters: {'solver': 'saga', 'C': 0.001350423028280395, 'l1_ratio': 0.9179068724881553, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5418049200161456e-06, 'max_iter': 2038}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  86%|████████▌ | 429/500 [32:04<04:59,  4.22s/it]

[I 2026-05-18 12:05:46,191] Trial 433 finished with value: 0.9497051721314772 and parameters: {'solver': 'saga', 'C': 0.0014131535644376612, 'l1_ratio': 0.9568313712312647, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4279663684201996e-06, 'max_iter': 1866}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  86%|████████▌ | 430/500 [32:05<03:50,  3.29s/it]

[I 2026-05-18 12:05:47,323] Trial 434 finished with value: 0.9497005015433647 and parameters: {'solver': 'saga', 'C': 0.0015154834458256288, 'l1_ratio': 0.9199107988947077, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4342132714327239e-06, 'max_iter': 2006}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  86%|████████▌ | 431/500 [32:08<03:28,  3.03s/it]

[I 2026-05-18 12:05:49,736] Trial 435 finished with value: 0.94970020955008 and parameters: {'solver': 'saga', 'C': 0.0015245819656065774, 'l1_ratio': 0.9173167321495361, 'class_weight': None, 'fit_intercept': True, 'tol': 1.451697379258087e-06, 'max_iter': 1994}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  86%|████████▋ | 432/500 [32:10<03:15,  2.88s/it]

[I 2026-05-18 12:05:52,272] Trial 436 finished with value: 0.9497045393203957 and parameters: {'solver': 'saga', 'C': 0.0031762663434765598, 'l1_ratio': 0.9238807049005875, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4308474960488681e-06, 'max_iter': 2001}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  87%|████████▋ | 433/500 [32:26<07:23,  6.61s/it]

[I 2026-05-18 12:06:07,598] Trial 438 finished with value: 0.9497023777783113 and parameters: {'solver': 'saga', 'C': 0.0015377486205336432, 'l1_ratio': 0.931011400693735, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4086561610613212e-06, 'max_iter': 1981}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  87%|████████▋ | 434/500 [32:27<05:20,  4.85s/it]

[I 2026-05-18 12:06:08,346] Trial 439 finished with value: 0.949695995125943 and parameters: {'solver': 'saga', 'C': 0.000854440593487756, 'l1_ratio': 0.9411343247635886, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4176515930458404e-06, 'max_iter': 2245}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  87%|████████▋ | 435/500 [32:30<04:52,  4.51s/it]

[I 2026-05-18 12:06:12,036] Trial 440 finished with value: 0.9496689480357471 and parameters: {'solver': 'saga', 'C': 0.0003729560808739437, 'l1_ratio': 0.9311715403761692, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3570335692366055e-06, 'max_iter': 2245}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  87%|████████▋ | 436/500 [32:32<03:49,  3.58s/it]

[I 2026-05-18 12:06:13,468] Trial 441 finished with value: 0.9496771822237149 and parameters: {'solver': 'saga', 'C': 0.00044604109295541186, 'l1_ratio': 0.9399836966999819, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2120687671548354e-06, 'max_iter': 2231}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  87%|████████▋ | 437/500 [32:34<03:26,  3.28s/it]

[I 2026-05-18 12:06:16,049] Trial 442 finished with value: 0.949671623372414 and parameters: {'solver': 'saga', 'C': 0.0003986097103150399, 'l1_ratio': 0.9827649325568062, 'class_weight': None, 'fit_intercept': True, 'tol': 1.209598880443355e-06, 'max_iter': 2212}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  88%|████████▊ | 438/500 [32:38<03:24,  3.30s/it]

[I 2026-05-18 12:06:19,404] Trial 443 finished with value: 0.9496661444909502 and parameters: {'solver': 'saga', 'C': 0.00037457587332826424, 'l1_ratio': 0.9797645364179156, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1637604460401024e-06, 'max_iter': 1674}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  88%|████████▊ | 439/500 [32:52<06:36,  6.49s/it]

[I 2026-05-18 12:06:33,344] Trial 444 finished with value: 0.9497051549174962 and parameters: {'solver': 'saga', 'C': 0.00091724058588946, 'l1_ratio': 0.9804853364705131, 'class_weight': None, 'fit_intercept': True, 'tol': 1.191015999405894e-06, 'max_iter': 2205}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  88%|████████▊ | 440/500 [32:52<04:47,  4.79s/it]

[I 2026-05-18 12:06:34,147] Trial 445 finished with value: 0.94968448532515 and parameters: {'solver': 'saga', 'C': 0.0004725197467499686, 'l1_ratio': 0.9749934351273652, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1822870488876746e-06, 'max_iter': 2203}. Best is trial 411 with value: 0.9497064502408218.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 411. Best value: 0.949706:  88%|████████▊ | 441/500 [32:57<04:45,  4.83s/it]

[I 2026-05-18 12:06:39,071] Trial 446 finished with value: 0.94970562324033 and parameters: {'solver': 'saga', 'C': 0.000972521474730581, 'l1_ratio': 0.9802694118597207, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1581828457442198e-06, 'max_iter': 2190}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  89%|████████▊ | 443/500 [32:59<02:33,  2.69s/it]

[I 2026-05-18 12:06:40,390] Trial 447 finished with value: 0.9497047282400111 and parameters: {'solver': 'saga', 'C': 0.0008761087635387189, 'l1_ratio': 0.9801434613071038, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9736532249447064e-06, 'max_iter': 1689}. Best is trial 411 with value: 0.9497064502408218.
[I 2026-05-18 12:06:40,561] Trial 448 finished with value: 0.9497023358465568 and parameters: {'solver': 'saga', 'C': 0.0008851447876979795, 'l1_ratio': 0.9656179731726489, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9347276143820723e-06, 'max_iter': 2078}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  89%|████████▉ | 444/500 [33:03<02:59,  3.21s/it]

[I 2026-05-18 12:06:44,982] Trial 449 finished with value: 0.9497030229629491 and parameters: {'solver': 'saga', 'C': 0.0009095632190449943, 'l1_ratio': 0.9679088677564598, 'class_weight': None, 'fit_intercept': True, 'tol': 1.882434883998413e-06, 'max_iter': 2143}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  89%|████████▉ | 445/500 [33:17<05:44,  6.26s/it]

[I 2026-05-18 12:06:58,341] Trial 451 finished with value: 0.9497053700844944 and parameters: {'solver': 'saga', 'C': 0.0021470012655302527, 'l1_ratio': 0.9621187138906795, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0754175102328636e-06, 'max_iter': 2082}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  89%|████████▉ | 446/500 [33:17<04:05,  4.55s/it]

[I 2026-05-18 12:06:58,926] Trial 450 finished with value: 0.9496966757679832 and parameters: {'solver': 'saga', 'C': 0.0006730904237172433, 'l1_ratio': 0.9653782725875897, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0225636072549685e-06, 'max_iter': 2092}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  89%|████████▉ | 447/500 [33:20<03:42,  4.20s/it]

[I 2026-05-18 12:07:02,315] Trial 452 finished with value: 0.9497055792811331 and parameters: {'solver': 'saga', 'C': 0.0019794845261313426, 'l1_ratio': 0.9635268044689721, 'class_weight': None, 'fit_intercept': True, 'tol': 1.958855496366169e-06, 'max_iter': 2066}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  90%|████████▉ | 448/500 [33:23<03:15,  3.77s/it]

[I 2026-05-18 12:07:05,056] Trial 454 finished with value: 0.9497051290024409 and parameters: {'solver': 'saga', 'C': 0.0022861963461425945, 'l1_ratio': 0.9626335852305836, 'class_weight': None, 'fit_intercept': True, 'tol': 2.8663184462842767e-06, 'max_iter': 2092}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  90%|████████▉ | 449/500 [33:23<02:18,  2.71s/it]

[I 2026-05-18 12:07:05,310] Trial 453 finished with value: 0.9497053233948034 and parameters: {'solver': 'saga', 'C': 0.002264602919472005, 'l1_ratio': 0.9613424132104068, 'class_weight': None, 'fit_intercept': True, 'tol': 1.983164751374488e-06, 'max_iter': 2077}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  90%|█████████ | 450/500 [33:27<02:34,  3.10s/it]

[I 2026-05-18 12:07:09,300] Trial 459 pruned.

Best trial: 411. Best value: 0.949706:  90%|█████████ | 451/500 [33:29<02:13,  2.73s/it]

[I 2026-05-18 12:07:11,182] Trial 457 pruned.

Best trial: 411. Best value: 0.949706:  90%|█████████ | 452/500 [33:30<01:39,  2.08s/it]

[I 2026-05-18 12:07:11,744] Trial 456 pruned.

Best trial: 411. Best value: 0.949706:  91%|█████████ | 453/500 [33:32<01:40,  2.13s/it]

[I 2026-05-18 12:07:14,007] Trial 458 pruned.

Best trial: 411. Best value: 0.949706:  91%|█████████ | 454/500 [33:36<02:00,  2.63s/it]

[I 2026-05-18 12:07:17,777] Trial 460 pruned.

Best trial: 411. Best value: 0.949706:  91%|█████████ | 455/500 [33:54<05:30,  7.35s/it]

[I 2026-05-18 12:07:36,143] Trial 462 finished with value: 0.9497027236258292 and parameters: {'solver': 'saga', 'C': 0.0012188582467985915, 'l1_ratio': 0.946425624612135, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6200276467196077e-06, 'max_iter': 1448}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  91%|█████████ | 456/500 [33:55<03:51,  5.26s/it]

[I 2026-05-18 12:07:36,537] Trial 463 finished with value: 0.9494144004746659 and parameters: {'solver': 'saga', 'C': 0.0006710455854661239, 'l1_ratio': 0.47502965608939635, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5091387581236912e-06, 'max_iter': 2788}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  91%|█████████▏| 457/500 [33:59<03:28,  4.84s/it]

[I 2026-05-18 12:07:40,397] Trial 464 finished with value: 0.9496872295054773 and parameters: {'solver': 'saga', 'C': 0.000619465478953644, 'l1_ratio': 0.9374922133264713, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0038183416497996e-06, 'max_iter': 2623}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  92%|█████████▏| 458/500 [34:01<02:53,  4.13s/it]

[I 2026-05-18 12:07:42,872] Trial 465 finished with value: 0.9496909504312203 and parameters: {'solver': 'saga', 'C': 0.0006256226236922655, 'l1_ratio': 0.9514879917763729, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6142799157708182e-06, 'max_iter': 2785}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  92%|█████████▏| 459/500 [34:19<05:44,  8.40s/it]

[I 2026-05-18 12:08:01,235] Trial 455 finished with value: 0.9496990317753413 and parameters: {'solver': 'saga', 'C': 0.0022333632164979584, 'l1_ratio': 0.9983254814781339, 'class_weight': None, 'fit_intercept': True, 'tol': 1.004480799024416e-06, 'max_iter': 2435}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  92%|█████████▏| 460/500 [34:20<03:59,  5.99s/it]

[I 2026-05-18 12:08:01,589] Trial 466 finished with value: 0.9496875628222448 and parameters: {'solver': 'saga', 'C': 0.0006054367650379724, 'l1_ratio': 0.9416812684779088, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5837496026494688e-06, 'max_iter': 1559}. Best is trial 411 with value: 0.9497064502408218.
[I 2026-05-18 12:08:01,789] Trial 467 finished with value: 0.9496884080537479 and parameters: {'solver': 'saga', 'C': 0.0006232611936706579, 'l1_ratio': 0.9419981527317686, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3281076736156924e-06, 'max_iter': 2570}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  92%|█████████▏| 462/500 [34:24<02:44,  4.32s/it]

[I 2026-05-18 12:08:06,275] Trial 468 finished with value: 0.9497038209879737 and parameters: {'solver': 'saga', 'C': 0.0014842094266697373, 'l1_ratio': 0.9433807140249187, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2974934593759596e-06, 'max_iter': 1735}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  93%|█████████▎| 463/500 [34:26<02:10,  3.53s/it]

[I 2026-05-18 12:08:07,953] Trial 469 finished with value: 0.9496054661466833 and parameters: {'solver': 'saga', 'C': 0.00019275868744495847, 'l1_ratio': 0.9818374385085998, 'class_weight': None, 'fit_intercept': True, 'tol': 1.295958476361887e-06, 'max_iter': 1584}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  93%|█████████▎| 464/500 [34:44<04:36,  7.69s/it]

[I 2026-05-18 12:08:25,350] Trial 471 finished with value: 0.9497039951865075 and parameters: {'solver': 'saga', 'C': 0.003402412241329915, 'l1_ratio': 0.9017208875330118, 'class_weight': None, 'fit_intercept': True, 'tol': 2.4194680416443514e-06, 'max_iter': 1928}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  93%|█████████▎| 465/500 [34:45<03:20,  5.72s/it]

[I 2026-05-18 12:08:26,489] Trial 472 finished with value: 0.9497039328847585 and parameters: {'solver': 'saga', 'C': 0.003268575022515155, 'l1_ratio': 0.9007246005461339, 'class_weight': None, 'fit_intercept': True, 'tol': 2.334478284184005e-06, 'max_iter': 1938}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  93%|█████████▎| 466/500 [34:45<02:23,  4.23s/it]

[I 2026-05-18 12:08:27,232] Trial 470 finished with value: 0.9497009688523097 and parameters: {'solver': 'saga', 'C': 0.0032772475018509133, 'l1_ratio': 0.9803921149797711, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2996506431128293e-06, 'max_iter': 1579}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  93%|█████████▎| 467/500 [34:48<02:03,  3.75s/it]

[I 2026-05-18 12:08:29,850] Trial 473 finished with value: 0.9497037977042329 and parameters: {'solver': 'saga', 'C': 0.003399564416798776, 'l1_ratio': 0.89462512332047, 'class_weight': None, 'fit_intercept': True, 'tol': 2.4096722274534097e-06, 'max_iter': 1903}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  94%|█████████▎| 468/500 [34:51<01:54,  3.57s/it]

[I 2026-05-18 12:08:33,020] Trial 474 finished with value: 0.9497014708515611 and parameters: {'solver': 'saga', 'C': 0.003216265440355382, 'l1_ratio': 0.9780991504754556, 'class_weight': None, 'fit_intercept': True, 'tol': 2.4086197872166803e-06, 'max_iter': 1944}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  94%|█████████▍| 469/500 [35:01<02:51,  5.54s/it]

[I 2026-05-18 12:08:43,157] Trial 381 finished with value: 0.9496287388946731 and parameters: {'solver': 'saga', 'C': 2.0026067492906043, 'l1_ratio': 0.9481680625140286, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4123335367777917e-06, 'max_iter': 1837}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  94%|█████████▍| 470/500 [35:08<02:56,  5.89s/it]

[I 2026-05-18 12:08:49,866] Trial 475 finished with value: 0.9497060948112708 and parameters: {'solver': 'saga', 'C': 0.0010863590105532684, 'l1_ratio': 0.9774935293765669, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7240340188596168e-06, 'max_iter': 1966}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  94%|█████████▍| 471/500 [35:09<02:08,  4.44s/it]

[I 2026-05-18 12:08:50,916] Trial 476 finished with value: 0.949706426653935 and parameters: {'solver': 'saga', 'C': 0.0011274397956331842, 'l1_ratio': 0.979532321499946, 'class_weight': None, 'fit_intercept': True, 'tol': 1.662134588874802e-06, 'max_iter': 1784}. Best is trial 411 with value: 0.9497064502408218.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 411. Best value: 0.949706:  94%|█████████▍| 472/500 [35:11<01:44,  3.75s/it]

[I 2026-05-18 12:08:53,053] Trial 477 finished with value: 0.9497050400609972 and parameters: {'solver': 'saga', 'C': 0.0010683736845697083, 'l1_ratio': 0.9692854784605945, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7739781693300839e-06, 'max_iter': 1807}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  95%|█████████▍| 473/500 [35:14<01:36,  3.57s/it]

[I 2026-05-18 12:08:56,193] Trial 478 finished with value: 0.9497057258693505 and parameters: {'solver': 'saga', 'C': 0.001233325109796293, 'l1_ratio': 0.968480800621136, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6796632196192464e-06, 'max_iter': 2310}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  95%|█████████▍| 474/500 [35:16<01:20,  3.08s/it]

[I 2026-05-18 12:08:58,155] Trial 479 finished with value: 0.9497041805089512 and parameters: {'solver': 'saga', 'C': 0.001093309639408365, 'l1_ratio': 0.9620561472597495, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6866844904411855e-06, 'max_iter': 1712}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  95%|█████████▌| 475/500 [35:26<02:07,  5.12s/it]

[I 2026-05-18 12:09:08,016] Trial 480 finished with value: 0.9497043300033251 and parameters: {'solver': 'saga', 'C': 0.0010959006658844488, 'l1_ratio': 0.9626151581930751, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6930850894901885e-06, 'max_iter': 2311}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  95%|█████████▌| 476/500 [35:33<02:18,  5.77s/it]

[I 2026-05-18 12:09:15,298] Trial 481 finished with value: 0.9496589695205048 and parameters: {'solver': 'saga', 'C': 0.0010953794513145147, 'l1_ratio': 0.622820317784214, 'class_weight': None, 'fit_intercept': True, 'tol': 1.680287163233936e-06, 'max_iter': 1751}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  95%|█████████▌| 477/500 [35:34<01:38,  4.26s/it]

[I 2026-05-18 12:09:16,052] Trial 482 finished with value: 0.9497052930217438 and parameters: {'solver': 'saga', 'C': 0.0009452513260234476, 'l1_ratio': 0.9787021470954484, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7796687485157514e-06, 'max_iter': 1755}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  96%|█████████▌| 478/500 [35:37<01:23,  3.78s/it]

[I 2026-05-18 12:09:18,703] Trial 483 finished with value: 0.9497056834310781 and parameters: {'solver': 'saga', 'C': 0.0009353244733681937, 'l1_ratio': 0.985335023878879, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7881733177878414e-06, 'max_iter': 1712}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  96%|█████████▌| 479/500 [35:39<01:06,  3.15s/it]

[I 2026-05-18 12:09:20,387] Trial 484 finished with value: 0.949705288474161 and parameters: {'solver': 'saga', 'C': 0.0009043402904031487, 'l1_ratio': 0.9827081236185577, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9369424209556905e-06, 'max_iter': 1729}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  96%|█████████▌| 480/500 [35:42<01:03,  3.18s/it]

[I 2026-05-18 12:09:23,650] Trial 485 finished with value: 0.9497043859867407 and parameters: {'solver': 'saga', 'C': 0.0008230647933734533, 'l1_ratio': 0.9885101670141021, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8682850537355709e-06, 'max_iter': 1394}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  96%|█████████▌| 481/500 [35:59<02:22,  7.52s/it]

[I 2026-05-18 12:09:41,292] Trial 371 finished with value: 0.9496283493011237 and parameters: {'solver': 'saga', 'C': 4.0369350968910584, 'l1_ratio': 0.9492996833147223, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2183526564650325e-06, 'max_iter': 2002}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  96%|█████████▋| 482/500 [36:00<01:38,  5.49s/it]

[I 2026-05-18 12:09:42,040] Trial 488 finished with value: 0.949701471418409 and parameters: {'solver': 'saga', 'C': 0.000779784465860034, 'l1_ratio': 0.9979867133536378, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0796854939883176e-06, 'max_iter': 1449}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  97%|█████████▋| 483/500 [36:03<01:18,  4.63s/it]

[I 2026-05-18 12:09:44,671] Trial 489 finished with value: 0.9497011590948924 and parameters: {'solver': 'saga', 'C': 0.0007652062447538084, 'l1_ratio': 0.9979901280946563, 'class_weight': None, 'fit_intercept': True, 'tol': 2.280519552808458e-06, 'max_iter': 1479}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  97%|█████████▋| 484/500 [36:07<01:14,  4.64s/it]

[I 2026-05-18 12:09:49,324] Trial 491 finished with value: 0.949704097041122 and parameters: {'solver': 'saga', 'C': 0.0014361036946349388, 'l1_ratio': 0.9465204793896297, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2810711103369506e-06, 'max_iter': 1495}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  97%|█████████▋| 485/500 [36:30<02:27,  9.85s/it]

[I 2026-05-18 12:10:11,332] Trial 494 finished with value: 0.9495440326586028 and parameters: {'solver': 'saga', 'C': 0.0016818242399276007, 'l1_ratio': 0.9999356111904251, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.438603810030657e-06, 'max_iter': 2154}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  97%|█████████▋| 486/500 [36:30<01:39,  7.08s/it]

[I 2026-05-18 12:10:11,935] Trial 492 finished with value: 0.9497021181386444 and parameters: {'solver': 'saga', 'C': 0.0015257619518327372, 'l1_ratio': 0.9969484215827186, 'class_weight': None, 'fit_intercept': True, 'tol': 2.562014394800782e-06, 'max_iter': 1472}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  97%|█████████▋| 487/500 [36:31<01:08,  5.26s/it]

[I 2026-05-18 12:10:12,965] Trial 495 finished with value: 0.9496010559272676 and parameters: {'solver': 'saga', 'C': 0.001655797402840918, 'l1_ratio': 0.929485106434869, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.913121377447143e-06, 'max_iter': 1955}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  98%|█████████▊| 488/500 [36:34<00:53,  4.42s/it]

[I 2026-05-18 12:10:15,427] Trial 493 finished with value: 0.9497015343108289 and parameters: {'solver': 'saga', 'C': 0.001599076207659629, 'l1_ratio': 0.9977042328272947, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9706023717640317e-05, 'max_iter': 1635}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  98%|█████████▊| 489/500 [36:43<01:05,  5.96s/it]

[I 2026-05-18 12:10:24,985] Trial 486 finished with value: 0.9497014149613545 and parameters: {'solver': 'saga', 'C': 0.0008175149649518684, 'l1_ratio': 0.9994571214602718, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0328425248235197e-06, 'max_iter': 1425}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  98%|█████████▊| 490/500 [36:53<01:10,  7.08s/it]

[I 2026-05-18 12:10:34,679] Trial 496 finished with value: 0.9497060072794309 and parameters: {'solver': 'saga', 'C': 0.0015737350256643519, 'l1_ratio': 0.9640648760496318, 'class_weight': None, 'fit_intercept': True, 'tol': 2.847427972223959e-06, 'max_iter': 1876}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  98%|█████████▊| 491/500 [36:55<00:50,  5.64s/it]

[I 2026-05-18 12:10:36,962] Trial 497 finished with value: 0.9496783519679959 and parameters: {'solver': 'saga', 'C': 0.000488647635593161, 'l1_ratio': 0.9285111535565208, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4556863784546145e-06, 'max_iter': 1610}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  98%|█████████▊| 492/500 [36:56<00:33,  4.18s/it]

[I 2026-05-18 12:10:37,734] Trial 498 finished with value: 0.949684908099519 and parameters: {'solver': 'saga', 'C': 0.0004846906489099499, 'l1_ratio': 0.968691865210246, 'class_weight': None, 'fit_intercept': True, 'tol': 1.461138239813042e-06, 'max_iter': 1623}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  99%|█████████▊| 493/500 [36:58<00:24,  3.49s/it]

[I 2026-05-18 12:10:39,617] Trial 499 finished with value: 0.9497053705952725 and parameters: {'solver': 'saga', 'C': 0.001218969302222789, 'l1_ratio': 0.9641444278119835, 'class_weight': None, 'fit_intercept': True, 'tol': 1.441183005401889e-06, 'max_iter': 1246}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  99%|█████████▉| 494/500 [37:16<00:47,  7.91s/it]

[I 2026-05-18 12:10:57,810] Trial 487 finished with value: 0.9497021988569448 and parameters: {'solver': 'saga', 'C': 0.0009410255800653656, 'l1_ratio': 0.9996219209604491, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0905075209154934e-06, 'max_iter': 1428}. Best is trial 411 with value: 0.9497064502408218.

Best trial: 411. Best value: 0.949706:  99%|█████████▉| 495/500 [37:36<00:58, 11.67s/it]

[I 2026-05-18 12:11:18,271] Trial 382 finished with value: 0.9496284065609935 and parameters: {'solver': 'saga', 'C': 3.5633816622093426, 'l1_ratio': 0.9438497429806806, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7227949859015488e-06, 'max_iter': 2184}. Best is trial 411 with value: 0.9497064502408218.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 411. Best value: 0.949706:  99%|█████████▉| 496/500 [38:23<01:28, 22.19s/it]

[I 2026-05-18 12:12:05,025] Trial 461 finished with value: 0.9496956071881826 and parameters: {'solver': 'saga', 'C': 0.0006278246904271943, 'l1_ratio': 0.9999411222069895, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5939941605679717e-06, 'max_iter': 2450}. Best is trial 411 with value: 0.9497064502408218.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 411. Best value: 0.949706:  99%|█████████▉| 497/500 [38:51<01:11, 23.89s/it]

[I 2026-05-18 12:12:32,861] Trial 318 finished with value: 0.9496284643086466 and parameters: {'solver': 'saga', 'C': 3.010621707374415, 'l1_ratio': 0.9782405833870068, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2240726198565502e-06, 'max_iter': 1495}. Best is trial 411 with value: 0.9497064502408218.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 411. Best value: 0.949706: 100%|█████████▉| 498/500 [42:05<02:29, 74.86s/it]

[I 2026-05-18 12:15:46,640] Trial 389 finished with value: 0.9496285275871033 and parameters: {'solver': 'saga', 'C': 2.709443970292981, 'l1_ratio': 0.9676053016806354, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0034084829117482e-06, 'max_iter': 2626}. Best is trial 411 with value: 0.9497064502408218.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 411. Best value: 0.949706: 100%|█████████▉| 499/500 [44:26<01:34, 94.67s/it]

[I 2026-05-18 12:18:07,559] Trial 369 finished with value: 0.9496288062402956 and parameters: {'solver': 'saga', 'C': 1.7618715611112983, 'l1_ratio': 0.9990523645192971, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3931673864445e-06, 'max_iter': 1784}. Best is trial 411 with value: 0.9497064502408218.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 411. Best value: 0.949706: 100%|██████████| 500/500 [48:13<00:00,  5.79s/it]

[I 2026-05-18 12:21:54,500] Trial 490 finished with value: 0.949635461850247 and parameters: {'solver': 'saga', 'C': 0.19172016389308552, 'l1_ratio': 0.9983682126462081, 'class_weight': None, 'fit_intercept': True, 'tol': 2.359743729271448e-06, 'max_iter': 1419}. Best is trial 411 with value: 0.9497064502408218.
Best trial score:
0.9497064502408218

Best params:
{'solver': 'saga', 'C': 0.0011427696891455742, 'l1_ratio': 0.9798523189723278, 'class_weight': None, 'fit_intercept': True, 'tol': 2.014092459415771e-06, 'max_iter': 1984}

In [13]:
stacking_lg = LogisticRegression(**study.best_params).fit(X_train, y_train.PitNextLap)

# Submission

In [14]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [15]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test)[:, 1]

In [17]:
submission.to_csv('../data/submission/submission.csv', index=False)