# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking2.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking2.parquet')

In [4]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba,stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.496500,0.527291,0.637203,0.806670,...,0.3,0.815075,0.788450,0.867595,0.911292,0.783514,0.868510,0.784140,0.618609,0.543036
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.340099,0.303278,0.512236,0.734278,...,0.7,0.686883,0.686778,0.594025,0.698730,0.695484,0.772514,0.666212,0.572044,0.446302
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.127990,0.192701,0.330117,0.533609,...,0.5,0.580053,0.607686,0.523752,0.600009,0.614942,0.717012,0.570198,0.631260,0.440385
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,-1.249994,-1.823374,-0.834575,0.001354,...,0.0,0.002635,0.002627,0.013206,0.025528,0.000000,0.005494,0.063219,0.000000,0.076485
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,-0.090382,-0.011299,0.200067,0.386963,...,0.3,0.397511,0.457883,0.364956,0.265409,0.452112,0.482416,0.418672,0.245866,0.244423

In [5]:
X_test.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba,stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,-1.272709,-1.721325,-0.872993,0.005473,...,0.0,0.006534,0.003712,0.009642,0.010313,0.000000,0.019849,0.061327,0.000000,0.076454
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,-0.626960,-0.919863,-0.289991,0.054146,...,0.1,0.063555,0.110500,0.044563,0.145672,0.047794,0.012173,0.144461,0.102869,0.089535
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,-1.335019,-1.809246,-0.917667,0.003687,...,0.0,0.004404,0.003123,0.008417,0.006856,0.000000,0.010304,0.057929,0.000000,0.076454
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.190133,0.328363,0.387739,0.676445,...,0.3,0.670446,0.712745,0.648495,0.504756,0.637237,0.444558,0.628242,0.183451,0.215908
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.535153,0.644014,0.670147,0.852891,...,0.8,0.835307,0.855796,0.796202,0.823601,0.787922,0.939648,0.787450,0.823541,0.643512

# Machine Learning

In [6]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": 5000
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = make_pipeline(
            StandardScaler(),
            LogisticRegression(**params)
        )
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=50, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-25 14:56:09,788] A new study created in memory with name: no-name-5e01c161-09b8-4f51-a366-0523f0364c41
Best trial: 8. Best value: 0.948775:   2%|▉                                            | 1/50 [00:14<12:03, 14.77s/it]

[I 2026-05-25 14:56:24,553] Trial 8 finished with value: 0.9487749635788969 and parameters: {'solver': 'saga', 'C': 0.00010633347666531953, 'l1_ratio': 0.027101924790274734, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.005964200676938382}. Best is trial 8 with value: 0.9487749635788969.

Best trial: 8. Best value: 0.948775:   4%|█▊                                           | 2/50 [00:18<06:34,  8.23s/it]

[I 2026-05-25 14:56:28,204] Trial 2 finished with value: 0.9296732674773158 and parameters: {'solver': 'saga', 'C': 15.462008893041569, 'l1_ratio': 0.07059254315069141, 'class_weight': None, 'fit_intercept': False, 'tol': 0.006255218777310399}. Best is trial 8 with value: 0.9487749635788969.

Best trial: 7. Best value: 0.949169:   6%|██▋                                          | 3/50 [00:19<03:58,  5.07s/it]

[I 2026-05-25 14:56:29,525] Trial 7 finished with value: 0.949168729818729 and parameters: {'solver': 'saga', 'C': 0.0001114734783051445, 'l1_ratio': 0.40159807430642536, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006601948237193364}. Best is trial 7 with value: 0.949168729818729.

Best trial: 7. Best value: 0.949169:   8%|███▌                                         | 4/50 [00:21<02:51,  3.72s/it]

[I 2026-05-25 14:56:31,180] Trial 10 finished with value: 0.9307159882281081 and parameters: {'solver': 'saga', 'C': 0.026837110031575524, 'l1_ratio': 0.21386091075146518, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0023001275336813993}. Best is trial 7 with value: 0.949168729818729.

Best trial: 7. Best value: 0.949169:  10%|████▌                                        | 5/50 [00:23<02:19,  3.10s/it]

[I 2026-05-25 14:56:33,169] Trial 0 finished with value: 0.9478448325375768 and parameters: {'solver': 'saga', 'C': 0.00011010074480194766, 'l1_ratio': 0.30872714262308065, 'class_weight': None, 'fit_intercept': False, 'tol': 3.605127842608172e-05}. Best is trial 7 with value: 0.949168729818729.

Best trial: 7. Best value: 0.949169:  12%|█████▍                                       | 6/50 [00:29<03:00,  4.09s/it]

[I 2026-05-25 14:56:39,187] Trial 12 pruned.

Best trial: 7. Best value: 0.949169:  14%|██████▎                                      | 7/50 [00:31<02:21,  3.29s/it]

[I 2026-05-25 14:56:40,819] Trial 3 finished with value: 0.9486051351848246 and parameters: {'solver': 'saga', 'C': 4.834436269790281e-05, 'l1_ratio': 0.20940304110254404, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.7046642014005498e-06}. Best is trial 7 with value: 0.949168729818729.

Best trial: 7. Best value: 0.949169:  16%|███████▏                                     | 8/50 [00:35<02:38,  3.78s/it]

[I 2026-05-25 14:56:45,654] Trial 16 pruned.

Best trial: 17. Best value: 0.949557:  18%|███████▉                                    | 9/50 [00:58<06:36,  9.67s/it]

[I 2026-05-25 14:57:08,265] Trial 17 finished with value: 0.9495571788484568 and parameters: {'solver': 'saga', 'C': 0.0012720237111541655, 'l1_ratio': 0.7157207582420971, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 8.234198481714054e-06}. Best is trial 17 with value: 0.9495571788484568.

Best trial: 17. Best value: 0.949557:  20%|████████▌                                  | 10/50 [01:40<13:00, 19.52s/it]

[I 2026-05-25 14:57:49,848] Trial 9 finished with value: 0.9491059824943987 and parameters: {'solver': 'saga', 'C': 0.01608314178152376, 'l1_ratio': 0.8719886961852049, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.9317182915545427e-05}. Best is trial 17 with value: 0.9495571788484568.

Best trial: 17. Best value: 0.949557:  22%|█████████▍                                 | 11/50 [01:42<09:19, 14.33s/it]

[I 2026-05-25 14:57:52,424] Trial 15 finished with value: 0.949163465944584 and parameters: {'solver': 'saga', 'C': 0.0232791646983262, 'l1_ratio': 0.8752957140279932, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0018274027666681995}. Best is trial 17 with value: 0.9495571788484568.

Best trial: 17. Best value: 0.949557:  24%|██████████▎                                | 12/50 [01:56<08:55, 14.09s/it]

[I 2026-05-25 14:58:05,960] Trial 5 finished with value: 0.9490045383874486 and parameters: {'solver': 'saga', 'C': 0.05152339192409991, 'l1_ratio': 0.17662354767462196, 'class_weight': None, 'fit_intercept': True, 'tol': 2.9233759961343315e-05}. Best is trial 17 with value: 0.9495571788484568.

Best trial: 17. Best value: 0.949557:  26%|███████████▏                               | 13/50 [02:11<08:57, 14.52s/it]

[I 2026-05-25 14:58:21,478] Trial 22 finished with value: 0.9494209768512691 and parameters: {'solver': 'saga', 'C': 0.0016427584447215298, 'l1_ratio': 0.5991673730579935, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.361902365528631e-06}. Best is trial 17 with value: 0.9495571788484568.

Best trial: 17. Best value: 0.949557:  28%|████████████                               | 14/50 [02:25<08:39, 14.44s/it]

[I 2026-05-25 14:58:35,730] Trial 23 finished with value: 0.9494199138015162 and parameters: {'solver': 'saga', 'C': 0.0016543253028937232, 'l1_ratio': 0.6021999535772317, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.8470020813249234e-06}. Best is trial 17 with value: 0.9495571788484568.

Best trial: 24. Best value: 0.949585:  30%|████████████▉                              | 15/50 [02:39<08:13, 14.11s/it]

[I 2026-05-25 14:58:49,063] Trial 24 finished with value: 0.9495845795479745 and parameters: {'solver': 'saga', 'C': 0.0005621698798045574, 'l1_ratio': 0.6519814617424352, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.484507715646108e-06}. Best is trial 24 with value: 0.9495845795479745.

Best trial: 24. Best value: 0.949585:  32%|█████████████▊                             | 16/50 [04:03<19:56, 35.18s/it]

[I 2026-05-25 15:00:13,189] Trial 11 finished with value: 0.948813875075604 and parameters: {'solver': 'saga', 'C': 0.012790920653250923, 'l1_ratio': 0.7615052895592899, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.90271675875734e-06}. Best is trial 24 with value: 0.9495845795479745.

Best trial: 24. Best value: 0.949585:  34%|██████████████▌                            | 17/50 [04:07<14:12, 25.83s/it]

[I 2026-05-25 15:00:17,283] Trial 14 finished with value: 0.9484991912057076 and parameters: {'solver': 'saga', 'C': 0.04129701211026644, 'l1_ratio': 0.674996792315498, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.944644777241697e-05}. Best is trial 24 with value: 0.9495845795479745.

Best trial: 27. Best value: 0.949689:  36%|███████████████▍                           | 18/50 [04:28<13:03, 24.48s/it]

[I 2026-05-25 15:00:38,610] Trial 27 finished with value: 0.9496885645321023 and parameters: {'solver': 'saga', 'C': 1.4638598992086259e-05, 'l1_ratio': 0.7275374761793565, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 8.651335811843049e-06}. Best is trial 27 with value: 0.9496885645321023.

Best trial: 27. Best value: 0.949689:  38%|████████████████▎                          | 19/50 [04:56<13:12, 25.58s/it]

[I 2026-05-25 15:01:06,739] Trial 29 finished with value: 0.94966444370461 and parameters: {'solver': 'saga', 'C': 1.2203677119510803e-05, 'l1_ratio': 0.9930340657608299, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.1569242836591487e-06}. Best is trial 27 with value: 0.9496885645321023.

Best trial: 27. Best value: 0.949689:  40%|█████████████████▏                         | 20/50 [05:21<12:39, 25.31s/it]

[I 2026-05-25 15:01:31,417] Trial 30 finished with value: 0.9496671693482466 and parameters: {'solver': 'saga', 'C': 1.0328243427710505e-05, 'l1_ratio': 0.9731586563806081, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 8.86253682761521e-06}. Best is trial 27 with value: 0.9496885645321023.

Best trial: 27. Best value: 0.949689:  42%|██████████████████                         | 21/50 [06:25<17:53, 37.00s/it]

[I 2026-05-25 15:02:35,698] Trial 4 pruned.

Best trial: 32. Best value: 0.949697:  44%|██████████████████▉                        | 22/50 [06:52<15:52, 34.01s/it]

[I 2026-05-25 15:03:02,738] Trial 32 finished with value: 0.9496966702580243 and parameters: {'solver': 'saga', 'C': 1.041117129820765e-05, 'l1_ratio': 0.9423172194176649, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.1433303554109067e-05}. Best is trial 32 with value: 0.9496966702580243.

Best trial: 33. Best value: 0.949698:  46%|███████████████████▊                       | 23/50 [07:19<14:18, 31.81s/it]

[I 2026-05-25 15:03:29,397] Trial 33 finished with value: 0.9496976325757286 and parameters: {'solver': 'saga', 'C': 1.2144497284462573e-05, 'l1_ratio': 0.9789984621241354, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.064206320306449e-05}. Best is trial 33 with value: 0.9496976325757286.

Best trial: 33. Best value: 0.949698:  48%|████████████████████▋                      | 24/50 [08:36<19:36, 45.27s/it]

[I 2026-05-25 15:04:46,060] Trial 1 finished with value: 0.9483081025950503 and parameters: {'solver': 'saga', 'C': 4.174460026749491, 'l1_ratio': 0.8138205046748604, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002128193106026971}. Best is trial 33 with value: 0.9496976325757286.

Best trial: 35. Best value: 0.9497:  50%|██████████████████████▌                      | 25/50 [08:54<15:32, 37.28s/it]

[I 2026-05-25 15:05:04,719] Trial 35 finished with value: 0.9496996030585549 and parameters: {'solver': 'saga', 'C': 2.727509878714292e-05, 'l1_ratio': 0.9197791965167764, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00016053336442269504}. Best is trial 35 with value: 0.9496996030585549.

Best trial: 35. Best value: 0.9497:  52%|███████████████████████▍                     | 26/50 [09:15<12:57, 32.38s/it]

[I 2026-05-25 15:05:25,671] Trial 36 finished with value: 0.9496158931155243 and parameters: {'solver': 'saga', 'C': 0.00037055689343961013, 'l1_ratio': 0.9143390174870325, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00015676073076867247}. Best is trial 35 with value: 0.9496996030585549.

Best trial: 35. Best value: 0.9497:  54%|████████████████████████▎                    | 27/50 [13:18<36:32, 95.34s/it]

[I 2026-05-25 15:09:27,888] Trial 20 pruned.

Best trial: 38. Best value: 0.949702:  56%|████████████████████████                   | 28/50 [13:36<26:28, 72.18s/it]

[I 2026-05-25 15:09:46,049] Trial 38 finished with value: 0.9497019377255276 and parameters: {'solver': 'saga', 'C': 4.4557274265802296e-05, 'l1_ratio': 0.8074773892277047, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0003371376075694456}. Best is trial 38 with value: 0.9497019377255276.

Best trial: 38. Best value: 0.949702:  58%|████████████████████████▉                  | 29/50 [15:18<28:27, 81.31s/it]

[I 2026-05-25 15:11:28,654] Trial 34 pruned.

Best trial: 40. Best value: 0.949703:  60%|█████████████████████████▊                 | 30/50 [15:35<20:37, 61.87s/it]

[I 2026-05-25 15:11:45,174] Trial 40 finished with value: 0.9497027473076102 and parameters: {'solver': 'saga', 'C': 5.330159475877343e-05, 'l1_ratio': 0.7719772792871329, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0004370254875869294}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  62%|██████████████████████████▋                | 31/50 [15:52<15:19, 48.41s/it]

[I 2026-05-25 15:12:02,153] Trial 41 finished with value: 0.9495743983391473 and parameters: {'solver': 'saga', 'C': 5.72706400315152e-05, 'l1_ratio': 0.5219730023857417, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00023402563248243978}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  64%|███████████████████████████▌               | 32/50 [16:09<11:40, 38.93s/it]

[I 2026-05-25 15:12:18,963] Trial 42 finished with value: 0.9496155555322486 and parameters: {'solver': 'saga', 'C': 0.0002581267597377985, 'l1_ratio': 0.7881890860217524, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0005295201063171028}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  66%|████████████████████████████▍              | 33/50 [16:14<08:10, 28.83s/it]

[I 2026-05-25 15:12:24,244] Trial 19 pruned.

Best trial: 40. Best value: 0.949703:  68%|█████████████████████████████▏             | 34/50 [16:25<06:15, 23.45s/it]

[I 2026-05-25 15:12:35,147] Trial 43 finished with value: 0.9496896701532798 and parameters: {'solver': 'saga', 'C': 3.962831187219149e-05, 'l1_ratio': 0.9038035137223283, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0006004269786642188}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  70%|██████████████████████████████             | 35/50 [16:32<04:39, 18.63s/it]

[I 2026-05-25 15:12:42,524] Trial 44 finished with value: 0.9496909602729289 and parameters: {'solver': 'saga', 'C': 3.755295046871009e-05, 'l1_ratio': 0.8977897479948648, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0003946847241717226}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  72%|██████████████████████████████▉            | 36/50 [16:43<03:46, 16.14s/it]

[I 2026-05-25 15:12:52,865] Trial 45 finished with value: 0.9496977945260643 and parameters: {'solver': 'saga', 'C': 3.536750861307138e-05, 'l1_ratio': 0.8235800720213233, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00034246726660000244}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  74%|███████████████████████████████▊           | 37/50 [16:54<03:12, 14.79s/it]

[I 2026-05-25 15:13:04,496] Trial 46 finished with value: 0.9496410280951098 and parameters: {'solver': 'saga', 'C': 0.0001851993497114982, 'l1_ratio': 0.8316243177381292, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.159383907606445e-05}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  76%|████████████████████████████████▋          | 38/50 [17:01<02:27, 12.31s/it]

[I 2026-05-25 15:13:11,024] Trial 47 finished with value: 0.9496558554772907 and parameters: {'solver': 'saga', 'C': 0.00015839780049616337, 'l1_ratio': 0.8360064309086008, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000330069214176419}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  78%|█████████████████████████████████▌         | 39/50 [17:13<02:13, 12.15s/it]

[I 2026-05-25 15:13:22,791] Trial 48 finished with value: 0.949584062468157 and parameters: {'solver': 'saga', 'C': 0.0007087672830234073, 'l1_ratio': 0.8055938701484427, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00030955710449357223}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  80%|██████████████████████████████████▍        | 40/50 [17:20<01:47, 10.79s/it]

[I 2026-05-25 15:13:30,393] Trial 49 finished with value: 0.949588293185581 and parameters: {'solver': 'saga', 'C': 0.0006484458675576067, 'l1_ratio': 0.7979932752735848, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011275299232922607}. Best is trial 40 with value: 0.9497027473076102.

Best trial: 40. Best value: 0.949703:  82%|███████████████████████████████████▎       | 41/50 [18:39<04:41, 31.31s/it]

[I 2026-05-25 15:14:49,580] Trial 39 pruned.

Best trial: 40. Best value: 0.949703:  84%|████████████████████████████████████       | 42/50 [19:30<04:57, 37.14s/it]

[I 2026-05-25 15:15:40,324] Trial 37 pruned.

Best trial: 40. Best value: 0.949703:  86%|████████████████████████████████████▉      | 43/50 [21:00<06:11, 53.12s/it]

[I 2026-05-25 15:17:10,753] Trial 18 pruned.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 40. Best value: 0.949703:  88%|████████████████████████████████████▉     | 44/50 [26:34<13:42, 137.15s/it]

[I 2026-05-25 15:22:43,971] Trial 31 pruned.

Best trial: 40. Best value: 0.949703:  90%|█████████████████████████████████████▊    | 45/50 [37:36<24:33, 294.69s/it]

[I 2026-05-25 15:33:46,226] Trial 25 pruned.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 40. Best value: 0.949703:  92%|██████████████████████████████████████▋   | 46/50 [48:05<26:20, 395.11s/it]

[I 2026-05-25 15:44:15,664] Trial 26 pruned.

Best trial: 40. Best value: 0.949703:  94%|███████████████████████████████████████▍  | 47/50 [49:07<14:44, 294.92s/it]

[I 2026-05-25 15:45:16,814] Trial 6 finished with value: 0.9489461436025316 and parameters: {'solver': 'saga', 'C': 2.5668597568241913, 'l1_ratio': 0.7142312019232797, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.6988346900440902e-06}. Best is trial 40 with value: 0.9497027473076102.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 40. Best value: 0.949703:  96%|████████████████████████████████████████▎ | 48/50 [56:00<11:00, 330.41s/it]

[I 2026-05-25 15:52:10,041] Trial 21 pruned.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 40. Best value: 0.949703:  98%|█████████████████████████████████████████▏| 49/50 [57:17<04:14, 254.34s/it]

[I 2026-05-25 15:53:26,869] Trial 28 pruned.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 40. Best value: 0.949703: 100%|█████████████████████████████████████████| 50/50 [1:19:54<00:00, 95.88s/it]

[I 2026-05-25 16:16:03,869] Trial 13 finished with value: 0.9488721724343595 and parameters: {'solver': 'saga', 'C': 85.00201927959763, 'l1_ratio': 0.06823211381107741, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5122132903929594e-06}. Best is trial 40 with value: 0.9497027473076102.
Best trial score:
0.9497027473076102

Best params:
{'solver': 'saga', 'C': 5.330159475877343e-05, 'l1_ratio': 0.7719772792871329, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0004370254875869294}

In [7]:
stacking_lg = make_pipeline(
    StandardScaler(),
    LogisticRegression(**study.best_params, max_iter=5000)
).fit(X_train, y_train.PitNextLap)

# Submission

In [8]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [9]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test)[:, 1]

In [10]:
submission.to_csv('../data/submission/submission.csv', index=False)

In [11]:
X_train.columns.tolist()

['lgbm_proba',
 'cat_proba',
 'xgb_proba',
 'hist_proba',
 'lg_proba',
 'pca_knn_proba',
 'ridge_logit',
 'truncatedsvd_linear_svc_logit',
 'truncatedsvd_ridge_logit',
 'sgdclassifier_proba',
 'truncatedsvd_lgbm_proba',
 'truncatedsvd_knn_proba',
 'truncatedsvd_nystroem_knn_proba',
 'truncatedsvd_rbfsampler_knn_proba',
 'truncatedsvd_logistic_regression_proba',
 'truncatedsvd_nystroem_logistic_regression_proba',
 'truncatedsvd_nystroem_sgdclassifier_proba',
 'truncatedsvd_rbfsampler_logistic_regression_proba',
 'truncatedsvd_rbfsampler_sgdclassifier_proba',
 'voting_lgbm_and_cat_and_xgb_and_hist_proba',
 'voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier',
 'voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba',
 'stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit']