# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from lightgbm import LGBMClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking2.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking2.parquet')

In [4]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba,stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.496500,0.527291,0.637203,0.806670,...,0.3,0.815075,0.788450,0.867595,0.911292,0.783514,0.868510,0.784140,0.618609,0.543036
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.340099,0.303278,0.512236,0.734278,...,0.7,0.686883,0.686778,0.594025,0.698730,0.695484,0.772514,0.666212,0.572044,0.446302
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.127990,0.192701,0.330117,0.533609,...,0.5,0.580053,0.607686,0.523752,0.600009,0.614942,0.717012,0.570198,0.631260,0.440385
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,-1.249994,-1.823374,-0.834575,0.001354,...,0.0,0.002635,0.002627,0.013206,0.025528,0.000000,0.005494,0.063219,0.000000,0.076485
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,-0.090382,-0.011299,0.200067,0.386963,...,0.3,0.397511,0.457883,0.364956,0.265409,0.452112,0.482416,0.418672,0.245866,0.244423

In [5]:
X_test.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba,stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,-1.272709,-1.721325,-0.872993,0.005473,...,0.0,0.006534,0.003712,0.009642,0.010313,0.000000,0.019849,0.061327,0.000000,0.076454
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,-0.626960,-0.919863,-0.289991,0.054146,...,0.1,0.063555,0.110500,0.044563,0.145672,0.047794,0.012173,0.144461,0.102869,0.089535
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,-1.335019,-1.809246,-0.917667,0.003687,...,0.0,0.004404,0.003123,0.008417,0.006856,0.000000,0.010304,0.057929,0.000000,0.076454
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.190133,0.328363,0.387739,0.676445,...,0.3,0.670446,0.712745,0.648495,0.504756,0.637237,0.444558,0.628242,0.183451,0.215908
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.535153,0.644014,0.670147,0.852891,...,0.8,0.835307,0.855796,0.796202,0.823601,0.787922,0.939648,0.787450,0.823541,0.643512

# Machine Learning

In [6]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LGBMClassifier(
            objective='binary',
            metric='auc',
            boosting_type='gbdt',
            num_leaves=trial.suggest_int('num_leaves', 16, 256),
            max_depth=trial.suggest_int('max_depth', 3, 12),
            learning_rate=trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
            lambda_l1=trial.suggest_float('lambda_l1', 1e-3, 10.0, log=True),
            lambda_l2=trial.suggest_float('lambda_l2', 1e-3, 10.0, log=True),
            feature_fraction=trial.suggest_float('feature_fraction', 0.6, 1.0),
            bagging_fraction=trial.suggest_float('bagging_fraction', 0.6, 1.0),
            bagging_freq=trial.suggest_int('bagging_freq', 1, 7),
            min_child_samples=trial.suggest_int('min_child_samples', 10, 100),
            verbosity=-1,
            n_estimators=2000,
            random_state=42,
            n_jobs=1
        )
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=50, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-25 18:28:50,709] A new study created in memory with name: no-name-40bf84bf-ed96-466b-ab45-97c30fe732b1
Best trial: 6. Best value: 0.948279:   2%|▊                                         | 1/50 [06:45<5:31:01, 405.33s/it]

[I 2026-05-25 18:35:36,035] Trial 6 finished with value: 0.9482785396987762 and parameters: {'num_leaves': 21, 'max_depth': 8, 'learning_rate': 0.07766962337877835, 'lambda_l1': 0.29626552967323505, 'lambda_l2': 0.03904837453366228, 'feature_fraction': 0.7951296479075001, 'bagging_fraction': 0.7347101913928169, 'bagging_freq': 3, 'min_child_samples': 98}. Best is trial 6 with value: 0.9482785396987762.

Best trial: 10. Best value: 0.949829:   4%|█▋                                       | 2/50 [07:02<2:21:30, 176.88s/it]

[I 2026-05-25 18:35:53,005] Trial 10 finished with value: 0.9498289448758748 and parameters: {'num_leaves': 56, 'max_depth': 4, 'learning_rate': 0.03138650974606845, 'lambda_l1': 0.004123567265718793, 'lambda_l2': 0.2444920460453599, 'feature_fraction': 0.7418366295967, 'bagging_fraction': 0.8487509229313378, 'bagging_freq': 6, 'min_child_samples': 36}. Best is trial 10 with value: 0.9498289448758748.

Best trial: 5. Best value: 0.950051:   6%|██▌                                       | 3/50 [07:17<1:20:44, 103.08s/it]

[I 2026-05-25 18:36:08,264] Trial 5 finished with value: 0.9500510052110528 and parameters: {'num_leaves': 20, 'max_depth': 12, 'learning_rate': 0.014353991385718329, 'lambda_l1': 0.006090201959390602, 'lambda_l2': 0.0014306958421560058, 'feature_fraction': 0.7383247583238022, 'bagging_fraction': 0.854636942003083, 'bagging_freq': 3, 'min_child_samples': 71}. Best is trial 5 with value: 0.9500510052110528.

Best trial: 5. Best value: 0.950051:   8%|███▍                                       | 4/50 [08:05<1:02:28, 81.50s/it]

[I 2026-05-25 18:36:56,674] Trial 3 finished with value: 0.9491840644201979 and parameters: {'num_leaves': 43, 'max_depth': 12, 'learning_rate': 0.0381547056137826, 'lambda_l1': 0.035428864896804246, 'lambda_l2': 0.0027190155331769344, 'feature_fraction': 0.783383802846696, 'bagging_fraction': 0.8049593192373489, 'bagging_freq': 7, 'min_child_samples': 10}. Best is trial 5 with value: 0.9500510052110528.

Best trial: 5. Best value: 0.950051:  10%|████▏                                     | 5/50 [11:35<1:35:46, 127.70s/it]

[I 2026-05-25 18:40:26,309] Trial 2 finished with value: 0.9485063673561698 and parameters: {'num_leaves': 238, 'max_depth': 6, 'learning_rate': 0.057620658748325546, 'lambda_l1': 0.035000765553808696, 'lambda_l2': 0.6176843523057715, 'feature_fraction': 0.7618073290692842, 'bagging_fraction': 0.9679320710766839, 'bagging_freq': 6, 'min_child_samples': 99}. Best is trial 5 with value: 0.9500510052110528.

Best trial: 5. Best value: 0.950051:  12%|█████                                     | 6/50 [13:33<1:31:13, 124.40s/it]

[I 2026-05-25 18:42:24,302] Trial 13 finished with value: 0.9487035800816164 and parameters: {'num_leaves': 38, 'max_depth': 4, 'learning_rate': 0.0851216499199099, 'lambda_l1': 1.0055743566650417, 'lambda_l2': 0.002066431794676174, 'feature_fraction': 0.6402989021840912, 'bagging_fraction': 0.6417005063623952, 'bagging_freq': 2, 'min_child_samples': 58}. Best is trial 5 with value: 0.9500510052110528.

Best trial: 5. Best value: 0.950051:  14%|█████▉                                    | 7/50 [15:07<1:22:04, 114.53s/it]

[I 2026-05-25 18:43:58,494] Trial 7 pruned.

Best trial: 5. Best value: 0.950051:  16%|██████▉                                    | 8/50 [15:41<1:02:03, 88.66s/it]

[I 2026-05-25 18:44:31,775] Trial 1 finished with value: 0.9487600855173154 and parameters: {'num_leaves': 145, 'max_depth': 6, 'learning_rate': 0.046613225334397934, 'lambda_l1': 8.601737431785379, 'lambda_l2': 4.436510844052196, 'feature_fraction': 0.7305698010117097, 'bagging_fraction': 0.8998890997472253, 'bagging_freq': 5, 'min_child_samples': 86}. Best is trial 5 with value: 0.9500510052110528.

Best trial: 5. Best value: 0.950051:  18%|████████                                     | 9/50 [15:55<44:45, 65.51s/it]

[I 2026-05-25 18:44:46,364] Trial 0 pruned.

Best trial: 5. Best value: 0.950051:  20%|████████▊                                   | 10/50 [17:00<43:32, 65.32s/it]

[I 2026-05-25 18:45:51,275] Trial 11 pruned.

Best trial: 5. Best value: 0.950051:  22%|█████████▋                                  | 11/50 [17:46<38:37, 59.43s/it]

[I 2026-05-25 18:46:37,355] Trial 14 finished with value: 0.9499947892839634 and parameters: {'num_leaves': 37, 'max_depth': 12, 'learning_rate': 0.011207472742428747, 'lambda_l1': 8.081772676412301, 'lambda_l2': 0.005843948293000841, 'feature_fraction': 0.7100402365914762, 'bagging_fraction': 0.9644006247545274, 'bagging_freq': 6, 'min_child_samples': 73}. Best is trial 5 with value: 0.9500510052110528.

Best trial: 5. Best value: 0.950051:  24%|██████████▌                                 | 12/50 [19:32<46:37, 73.63s/it]

[I 2026-05-25 18:48:23,458] Trial 8 pruned.

Best trial: 5. Best value: 0.950051:  26%|███████████▍                                | 13/50 [19:55<35:59, 58.36s/it]

[I 2026-05-25 18:48:46,675] Trial 16 pruned.

Best trial: 5. Best value: 0.950051:  28%|████████████▎                               | 14/50 [21:07<37:20, 62.25s/it]

[I 2026-05-25 18:49:57,912] Trial 15 pruned.

Best trial: 5. Best value: 0.950051:  30%|█████████████▏                              | 15/50 [21:11<26:12, 44.92s/it]

[I 2026-05-25 18:50:02,671] Trial 9 finished with value: 0.9496532039613801 and parameters: {'num_leaves': 196, 'max_depth': 7, 'learning_rate': 0.015414994050200402, 'lambda_l1': 1.4574295110133157, 'lambda_l2': 0.00422970324723598, 'feature_fraction': 0.8660450803795009, 'bagging_fraction': 0.9061811459451977, 'bagging_freq': 2, 'min_child_samples': 76}. Best is trial 5 with value: 0.9500510052110528.

Best trial: 5. Best value: 0.950051:  32%|██████████████                              | 16/50 [21:21<19:30, 34.42s/it]

[I 2026-05-25 18:50:12,696] Trial 18 pruned.

Best trial: 5. Best value: 0.950051:  34%|██████████████▉                             | 17/50 [21:43<16:43, 30.41s/it]

[I 2026-05-25 18:50:33,794] Trial 12 pruned.

Best trial: 5. Best value: 0.950051:  36%|███████████████▊                            | 18/50 [22:04<14:48, 27.76s/it]

[I 2026-05-25 18:50:55,389] Trial 4 pruned.

Best trial: 5. Best value: 0.950051:  38%|████████████████▋                           | 19/50 [23:24<22:25, 43.40s/it]

[I 2026-05-25 18:52:15,204] Trial 20 pruned.

Best trial: 5. Best value: 0.950051:  40%|█████████████████▌                          | 20/50 [27:15<49:53, 99.80s/it]

[I 2026-05-25 18:56:06,447] Trial 19 pruned.

Best trial: 5. Best value: 0.950051:  42%|█████████████████▏                       | 21/50 [32:49<1:22:10, 170.02s/it]

[I 2026-05-25 19:01:40,201] Trial 17 finished with value: 0.9497160549408246 and parameters: {'num_leaves': 77, 'max_depth': 9, 'learning_rate': 0.010570213669475385, 'lambda_l1': 0.05326426137232063, 'lambda_l2': 3.3385276919410396, 'feature_fraction': 0.9837262642577214, 'bagging_fraction': 0.6706980589861159, 'bagging_freq': 1, 'min_child_samples': 88}. Best is trial 5 with value: 0.9500510052110528.

Best trial: 32. Best value: 0.95013:  44%|██████████████████                       | 22/50 [38:35<1:43:59, 222.84s/it]

[I 2026-05-25 19:07:26,218] Trial 32 finished with value: 0.9501301405647788 and parameters: {'num_leaves': 17, 'max_depth': 3, 'learning_rate': 0.01004043509941534, 'lambda_l1': 0.0014302643904862981, 'lambda_l2': 0.012449043608801802, 'feature_fraction': 0.6996516891512191, 'bagging_fraction': 0.8453819807346918, 'bagging_freq': 4, 'min_child_samples': 65}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  46%|██████████████████▊                      | 23/50 [39:22<1:16:29, 169.99s/it]

[I 2026-05-25 19:08:12,944] Trial 23 finished with value: 0.9497266884019332 and parameters: {'num_leaves': 83, 'max_depth': 12, 'learning_rate': 0.01118000704535742, 'lambda_l1': 4.337687119495052, 'lambda_l2': 0.013011852581156648, 'feature_fraction': 0.6620620105087691, 'bagging_fraction': 0.9992872374001586, 'bagging_freq': 4, 'min_child_samples': 69}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  48%|████████████████████▋                      | 24/50 [40:19<58:57, 136.07s/it]

[I 2026-05-25 19:09:09,896] Trial 29 finished with value: 0.9498262474065866 and parameters: {'num_leaves': 82, 'max_depth': 11, 'learning_rate': 0.010149822334528888, 'lambda_l1': 0.0012814940082245942, 'lambda_l2': 0.014710894966178518, 'feature_fraction': 0.6822898345039479, 'bagging_fraction': 0.9948163812266113, 'bagging_freq': 4, 'min_child_samples': 68}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  50%|█████████████████████▌                     | 25/50 [40:50<43:38, 104.75s/it]

[I 2026-05-25 19:09:41,584] Trial 21 finished with value: 0.9496649845418723 and parameters: {'num_leaves': 101, 'max_depth': 9, 'learning_rate': 0.01003123723604782, 'lambda_l1': 0.00100717605358551, 'lambda_l2': 0.01390749479647782, 'feature_fraction': 0.9017540661700452, 'bagging_fraction': 0.7700550994939798, 'bagging_freq': 4, 'min_child_samples': 66}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  52%|██████████████████████▉                     | 26/50 [40:52<29:33, 73.92s/it]

[I 2026-05-25 19:09:43,554] Trial 22 finished with value: 0.9497146325721522 and parameters: {'num_leaves': 92, 'max_depth': 10, 'learning_rate': 0.01000009839102342, 'lambda_l1': 0.001400091629682108, 'lambda_l2': 0.014018557489505453, 'feature_fraction': 0.8943585752405696, 'bagging_fraction': 0.9773783639023311, 'bagging_freq': 4, 'min_child_samples': 67}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  54%|███████████████████████▊                    | 27/50 [41:06<21:22, 55.76s/it]

[I 2026-05-25 19:09:56,969] Trial 26 finished with value: 0.949781173964942 and parameters: {'num_leaves': 88, 'max_depth': 9, 'learning_rate': 0.010830686575382682, 'lambda_l1': 0.0016103924584744038, 'lambda_l2': 0.015356869941709024, 'feature_fraction': 0.6686296640758822, 'bagging_fraction': 0.991236890432576, 'bagging_freq': 4, 'min_child_samples': 63}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  56%|████████████████████████▋                   | 28/50 [41:56<19:52, 54.20s/it]

[I 2026-05-25 19:10:47,534] Trial 27 finished with value: 0.9497823838731501 and parameters: {'num_leaves': 85, 'max_depth': 11, 'learning_rate': 0.010654740292343267, 'lambda_l1': 0.051277317635655864, 'lambda_l2': 0.01861281385126435, 'feature_fraction': 0.677239504378219, 'bagging_fraction': 0.9918877726691543, 'bagging_freq': 4, 'min_child_samples': 66}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  58%|█████████████████████████▌                  | 29/50 [42:33<17:10, 49.08s/it]

[I 2026-05-25 19:11:24,671] Trial 24 finished with value: 0.9497673015420023 and parameters: {'num_leaves': 88, 'max_depth': 12, 'learning_rate': 0.010125219581671995, 'lambda_l1': 0.0014480508914638064, 'lambda_l2': 0.013882909425617073, 'feature_fraction': 0.8596799627442794, 'bagging_fraction': 0.9907160138200387, 'bagging_freq': 4, 'min_child_samples': 68}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  60%|██████████████████████████▍                 | 30/50 [42:36<11:42, 35.10s/it]

[I 2026-05-25 19:11:27,146] Trial 28 finished with value: 0.9498008077704864 and parameters: {'num_leaves': 90, 'max_depth': 11, 'learning_rate': 0.010178470984472927, 'lambda_l1': 0.038452884704367786, 'lambda_l2': 0.017737484293608437, 'feature_fraction': 0.6716975419497806, 'bagging_fraction': 0.9894116753859659, 'bagging_freq': 4, 'min_child_samples': 66}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  62%|███████████████████████████▎                | 31/50 [43:03<10:21, 32.73s/it]

[I 2026-05-25 19:11:54,333] Trial 25 finished with value: 0.9497121824687298 and parameters: {'num_leaves': 86, 'max_depth': 9, 'learning_rate': 0.010631058045134895, 'lambda_l1': 0.0019486140792754055, 'lambda_l2': 0.01814514333735151, 'feature_fraction': 0.8639454378567808, 'bagging_fraction': 0.9954000885203147, 'bagging_freq': 4, 'min_child_samples': 69}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  64%|████████████████████████████▏               | 32/50 [43:24<08:44, 29.14s/it]

[I 2026-05-25 19:12:15,090] Trial 30 finished with value: 0.9498051142930262 and parameters: {'num_leaves': 85, 'max_depth': 11, 'learning_rate': 0.01002120449129633, 'lambda_l1': 0.0013000338203364057, 'lambda_l2': 0.01279705592833646, 'feature_fraction': 0.683670438659889, 'bagging_fraction': 0.8192939684964647, 'bagging_freq': 4, 'min_child_samples': 65}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  66%|█████████████████████████████               | 33/50 [44:24<10:53, 38.44s/it]

[I 2026-05-25 19:13:15,257] Trial 33 finished with value: 0.9501263118390432 and parameters: {'num_leaves': 21, 'max_depth': 3, 'learning_rate': 0.010519787692586812, 'lambda_l1': 0.001062139735601391, 'lambda_l2': 0.013758663716750212, 'feature_fraction': 0.6908197680401704, 'bagging_fraction': 0.778941161180207, 'bagging_freq': 4, 'min_child_samples': 63}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  68%|█████████████████████████████▉              | 34/50 [45:27<12:10, 45.66s/it]

[I 2026-05-25 19:14:17,753] Trial 34 finished with value: 0.9500982661657389 and parameters: {'num_leaves': 20, 'max_depth': 3, 'learning_rate': 0.01820674761515971, 'lambda_l1': 0.0021105399216831923, 'lambda_l2': 0.013471302931015984, 'feature_fraction': 0.6967497729426836, 'bagging_fraction': 0.853495789808798, 'bagging_freq': 4, 'min_child_samples': 60}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  70%|██████████████████████████████▊             | 35/50 [46:51<14:18, 57.20s/it]

[I 2026-05-25 19:15:41,889] Trial 35 finished with value: 0.9501043400593376 and parameters: {'num_leaves': 22, 'max_depth': 3, 'learning_rate': 0.01692279517847781, 'lambda_l1': 0.015009524385683789, 'lambda_l2': 0.01083706910541995, 'feature_fraction': 0.7056212104727924, 'bagging_fraction': 0.8610128811513199, 'bagging_freq': 3, 'min_child_samples': 58}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  72%|███████████████████████████████▋            | 36/50 [47:17<11:13, 48.07s/it]

[I 2026-05-25 19:16:08,655] Trial 36 finished with value: 0.9500918211829955 and parameters: {'num_leaves': 20, 'max_depth': 3, 'learning_rate': 0.01778102440806227, 'lambda_l1': 0.0033153993889704957, 'lambda_l2': 0.0011664964946817074, 'feature_fraction': 0.7093849752615293, 'bagging_fraction': 0.858739748142853, 'bagging_freq': 3, 'min_child_samples': 53}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  74%|████████████████████████████████▌           | 37/50 [47:27<07:53, 36.44s/it]

[I 2026-05-25 19:16:17,946] Trial 38 finished with value: 0.9501058756384915 and parameters: {'num_leaves': 18, 'max_depth': 3, 'learning_rate': 0.016547537606073987, 'lambda_l1': 0.010976724204100983, 'lambda_l2': 0.0070183639332539235, 'feature_fraction': 0.7111185099091527, 'bagging_fraction': 0.8672896029850166, 'bagging_freq': 3, 'min_child_samples': 54}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  76%|█████████████████████████████████▍          | 38/50 [47:30<05:17, 26.42s/it]

[I 2026-05-25 19:16:20,985] Trial 37 finished with value: 0.9500945077744305 and parameters: {'num_leaves': 23, 'max_depth': 3, 'learning_rate': 0.017093935294646333, 'lambda_l1': 0.0033133104781991555, 'lambda_l2': 0.007931942434775609, 'feature_fraction': 0.8326789109752367, 'bagging_fraction': 0.8566346693528047, 'bagging_freq': 3, 'min_child_samples': 52}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  78%|██████████████████████████████████▎         | 39/50 [48:29<06:39, 36.32s/it]

[I 2026-05-25 19:17:20,394] Trial 31 finished with value: 0.9498317104777929 and parameters: {'num_leaves': 82, 'max_depth': 11, 'learning_rate': 0.010013615981641273, 'lambda_l1': 0.09474830740567977, 'lambda_l2': 0.013686809653091091, 'feature_fraction': 0.6922991297979567, 'bagging_fraction': 0.9941872098884732, 'bagging_freq': 4, 'min_child_samples': 64}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  80%|███████████████████████████████████▏        | 40/50 [48:30<04:16, 25.70s/it]

[I 2026-05-25 19:17:21,326] Trial 39 finished with value: 0.9501091798032577 and parameters: {'num_leaves': 18, 'max_depth': 3, 'learning_rate': 0.01645093888472256, 'lambda_l1': 0.01564310467042729, 'lambda_l2': 0.0013881384999650734, 'feature_fraction': 0.7092645607984908, 'bagging_fraction': 0.8538139057955578, 'bagging_freq': 3, 'min_child_samples': 53}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  82%|████████████████████████████████████        | 41/50 [49:04<04:14, 28.29s/it]

[I 2026-05-25 19:17:55,666] Trial 40 finished with value: 0.950108619742392 and parameters: {'num_leaves': 16, 'max_depth': 3, 'learning_rate': 0.017169353245135847, 'lambda_l1': 0.012527272528582257, 'lambda_l2': 0.001046635385107449, 'feature_fraction': 0.7116781619805007, 'bagging_fraction': 0.8614114345573689, 'bagging_freq': 3, 'min_child_samples': 80}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  84%|████████████████████████████████████▉       | 42/50 [49:06<02:42, 20.28s/it]

[I 2026-05-25 19:17:57,257] Trial 41 finished with value: 0.9500985530873525 and parameters: {'num_leaves': 20, 'max_depth': 3, 'learning_rate': 0.016359621578924944, 'lambda_l1': 0.013795306117712057, 'lambda_l2': 0.0011137065126106264, 'feature_fraction': 0.7146568713853958, 'bagging_fraction': 0.8595371912050034, 'bagging_freq': 3, 'min_child_samples': 79}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  86%|█████████████████████████████████████▊      | 43/50 [49:21<02:10, 18.59s/it]

[I 2026-05-25 19:18:11,895] Trial 42 finished with value: 0.9501039069748891 and parameters: {'num_leaves': 17, 'max_depth': 3, 'learning_rate': 0.017054806397503976, 'lambda_l1': 0.00409408897374821, 'lambda_l2': 0.001147245808122717, 'feature_fraction': 0.7069245766378583, 'bagging_fraction': 0.8699133995740319, 'bagging_freq': 3, 'min_child_samples': 79}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  88%|██████████████████████████████████████▋     | 44/50 [49:33<01:39, 16.57s/it]

[I 2026-05-25 19:18:23,753] Trial 43 finished with value: 0.9501111696620139 and parameters: {'num_leaves': 16, 'max_depth': 3, 'learning_rate': 0.016069802041024824, 'lambda_l1': 0.00385906037304179, 'lambda_l2': 0.0011553745366966687, 'feature_fraction': 0.7123057713213228, 'bagging_fraction': 0.8615746443159719, 'bagging_freq': 5, 'min_child_samples': 79}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  90%|███████████████████████████████████████▌    | 45/50 [50:21<02:09, 25.99s/it]

[I 2026-05-25 19:19:11,718] Trial 44 finished with value: 0.950106178233249 and parameters: {'num_leaves': 16, 'max_depth': 3, 'learning_rate': 0.015399302209577775, 'lambda_l1': 0.003171240525477976, 'lambda_l2': 0.0011293757608820032, 'feature_fraction': 0.7090698828833863, 'bagging_fraction': 0.8654680048421102, 'bagging_freq': 3, 'min_child_samples': 55}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  92%|████████████████████████████████████████▍   | 46/50 [50:53<01:51, 27.88s/it]

[I 2026-05-25 19:19:44,008] Trial 45 finished with value: 0.950111972532115 and parameters: {'num_leaves': 23, 'max_depth': 3, 'learning_rate': 0.015601600485953954, 'lambda_l1': 0.0033442413184662134, 'lambda_l2': 0.03597789099961471, 'feature_fraction': 0.7118717730828432, 'bagging_fraction': 0.8466956878579652, 'bagging_freq': 3, 'min_child_samples': 53}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  94%|█████████████████████████████████████████▎  | 47/50 [51:36<01:37, 32.45s/it]

[I 2026-05-25 19:20:27,110] Trial 46 finished with value: 0.9500810033427969 and parameters: {'num_leaves': 16, 'max_depth': 3, 'learning_rate': 0.019913543925150417, 'lambda_l1': 0.015203934685551231, 'lambda_l2': 0.04457361963195896, 'feature_fraction': 0.7090467391006796, 'bagging_fraction': 0.8583815649760116, 'bagging_freq': 3, 'min_child_samples': 56}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  96%|██████████████████████████████████████████▏ | 48/50 [51:39<00:47, 23.68s/it]

[I 2026-05-25 19:20:30,346] Trial 47 finished with value: 0.9500804528494594 and parameters: {'num_leaves': 63, 'max_depth': 3, 'learning_rate': 0.019521485982696016, 'lambda_l1': 0.016138439255424266, 'lambda_l2': 0.038514643456939175, 'feature_fraction': 0.71638455279854, 'bagging_fraction': 0.7830358418451041, 'bagging_freq': 5, 'min_child_samples': 79}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  98%|███████████████████████████████████████████ | 49/50 [52:31<00:32, 32.25s/it]

[I 2026-05-25 19:21:22,591] Trial 49 finished with value: 0.9499930587542377 and parameters: {'num_leaves': 64, 'max_depth': 4, 'learning_rate': 0.020010676587010726, 'lambda_l1': 0.013090534904234183, 'lambda_l2': 0.03847833586768308, 'feature_fraction': 0.7656716747084156, 'bagging_fraction': 0.7851112167005444, 'bagging_freq': 5, 'min_child_samples': 81}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013: 100%|████████████████████████████████████████████| 50/50 [52:54<00:00, 63.50s/it]

[I 2026-05-25 19:21:45,480] Trial 48 finished with value: 0.9500792287935713 and parameters: {'num_leaves': 64, 'max_depth': 4, 'learning_rate': 0.013828073122423496, 'lambda_l1': 0.01567643521531724, 'lambda_l2': 0.058055200886465506, 'feature_fraction': 0.7699927125970286, 'bagging_fraction': 0.883815805932063, 'bagging_freq': 3, 'min_child_samples': 79}. Best is trial 32 with value: 0.9501301405647788.
Best trial score:
0.9501301405647788

Best params:
{'num_leaves': 17, 'max_depth': 3, 'learning_rate': 0.01004043509941534, 'lambda_l1': 0.0014302643904862981, 'lambda_l2': 0.012449043608801802, 'feature_fraction': 0.6996516891512191, 'bagging_fraction': 0.8453819807346918, 'bagging_freq': 4, 'min_child_samples': 65}

In [12]:
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=100, n_jobs=-1, show_progress_bar=True)

Best trial: 32. Best value: 0.95013:   1%|▍                                       | 1/100 [10:10<16:46:39, 610.10s/it]

[I 2026-05-25 19:51:40,112] Trial 56 finished with value: 0.9500279557859661 and parameters: {'num_leaves': 34, 'max_depth': 5, 'learning_rate': 0.012909756801026752, 'lambda_l1': 0.0061762716742159805, 'lambda_l2': 0.09464335077426987, 'feature_fraction': 0.7484448465030112, 'bagging_fraction': 0.8308398269500364, 'bagging_freq': 5, 'min_child_samples': 47}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:   2%|▊                                        | 2/100 [10:20<7:00:42, 257.58s/it]

[I 2026-05-25 19:51:50,924] Trial 57 finished with value: 0.9500254288888705 and parameters: {'num_leaves': 36, 'max_depth': 5, 'learning_rate': 0.013111932582038483, 'lambda_l1': 0.005624223535175666, 'lambda_l2': 0.14460144527437616, 'feature_fraction': 0.7450531906159246, 'bagging_fraction': 0.8298649801168149, 'bagging_freq': 5, 'min_child_samples': 48}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:   3%|█▏                                       | 3/100 [10:23<3:48:28, 141.32s/it]

[I 2026-05-25 19:51:53,906] Trial 51 finished with value: 0.9498348568058518 and parameters: {'num_leaves': 36, 'max_depth': 5, 'learning_rate': 0.022854432988362983, 'lambda_l1': 0.005826163013016672, 'lambda_l2': 0.16728913119181693, 'feature_fraction': 0.6013338633240123, 'bagging_fraction': 0.8351266939729317, 'bagging_freq': 5, 'min_child_samples': 47}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:   4%|█▋                                        | 4/100 [10:54<2:36:10, 97.61s/it]

[I 2026-05-25 19:52:24,492] Trial 59 finished with value: 0.9500210825201492 and parameters: {'num_leaves': 33, 'max_depth': 5, 'learning_rate': 0.01315192591538822, 'lambda_l1': 0.0058502661655066195, 'lambda_l2': 0.12144755820687764, 'feature_fraction': 0.7468395219815849, 'bagging_fraction': 0.8284534184703386, 'bagging_freq': 5, 'min_child_samples': 48}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:   5%|██                                        | 5/100 [10:59<1:41:49, 64.31s/it]

[I 2026-05-25 19:52:29,764] Trial 54 finished with value: 0.9500122489372685 and parameters: {'num_leaves': 43, 'max_depth': 5, 'learning_rate': 0.013012972463723916, 'lambda_l1': 0.005974269507041864, 'lambda_l2': 0.09108439316833991, 'feature_fraction': 0.7489664228061041, 'bagging_fraction': 0.817370034502258, 'bagging_freq': 5, 'min_child_samples': 46}. Best is trial 32 with value: 0.9501301405647788.
[I 2026-05-25 19:52:29,781] Trial 52 finished with value: 0.9500130406001535 and parameters: {'num_leaves': 35, 'max_depth': 5, 'learning_rate': 0.01325433983226045, 'lambda_l1': 0.005393133242952543, 'lambda_l2': 0.0883063733603751, 'feature_fraction': 0.7413929687994868, 'bagging_fraction': 0.8299868780749649, 'bagging_freq': 5, 'min_child_samples': 48}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:   7%|███                                         | 7/100 [11:03<50:39, 32.69s/it]

[I 2026-05-25 19:52:33,755] Trial 58 finished with value: 0.9500254151513132 and parameters: {'num_leaves': 35, 'max_depth': 5, 'learning_rate': 0.013361933754961437, 'lambda_l1': 0.005230092816739312, 'lambda_l2': 0.0018575891961623663, 'feature_fraction': 0.7473140961958716, 'bagging_fraction': 0.8327919108797919, 'bagging_freq': 5, 'min_child_samples': 49}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:   8%|███▌                                        | 8/100 [11:08<38:39, 25.22s/it]

[I 2026-05-25 19:52:38,359] Trial 53 finished with value: 0.9500274462683922 and parameters: {'num_leaves': 45, 'max_depth': 5, 'learning_rate': 0.013012973315196285, 'lambda_l1': 0.0059537165415386875, 'lambda_l2': 0.11615207655182838, 'feature_fraction': 0.749051653040735, 'bagging_fraction': 0.8334628977353498, 'bagging_freq': 5, 'min_child_samples': 36}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:   9%|███▉                                        | 9/100 [11:56<47:38, 31.41s/it]

[I 2026-05-25 19:53:26,072] Trial 55 finished with value: 0.9500406134612653 and parameters: {'num_leaves': 36, 'max_depth': 5, 'learning_rate': 0.012736382330905025, 'lambda_l1': 0.005788925582844436, 'lambda_l2': 0.1991264078896382, 'feature_fraction': 0.7520439781221084, 'bagging_fraction': 0.8271710560498962, 'bagging_freq': 5, 'min_child_samples': 49}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  10%|████▎                                      | 10/100 [11:57<34:15, 22.84s/it]

[I 2026-05-25 19:53:27,135] Trial 50 finished with value: 0.950024665248803 and parameters: {'num_leaves': 33, 'max_depth': 5, 'learning_rate': 0.013025821719879687, 'lambda_l1': 0.004975787326258429, 'lambda_l2': 0.09197828792608004, 'feature_fraction': 0.7413740006350281, 'bagging_fraction': 0.8299815934413579, 'bagging_freq': 5, 'min_child_samples': 46}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  11%|████▋                                      | 11/100 [12:01<26:05, 17.59s/it]

[I 2026-05-25 19:53:31,703] Trial 60 finished with value: 0.9500095138783717 and parameters: {'num_leaves': 33, 'max_depth': 5, 'learning_rate': 0.01372429144214857, 'lambda_l1': 0.00268207519555062, 'lambda_l2': 0.001805076021045647, 'feature_fraction': 0.741854537082945, 'bagging_fraction': 0.830584189007374, 'bagging_freq': 5, 'min_child_samples': 48}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  12%|█████▏                                     | 12/100 [12:08<21:10, 14.43s/it]

[I 2026-05-25 19:53:38,442] Trial 61 finished with value: 0.950043185103147 and parameters: {'num_leaves': 45, 'max_depth': 5, 'learning_rate': 0.013249725670911483, 'lambda_l1': 0.007740839883371166, 'lambda_l2': 0.13316174288174273, 'feature_fraction': 0.6030506235418638, 'bagging_fraction': 0.823078216345619, 'bagging_freq': 5, 'min_child_samples': 34}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  13%|█████▏                                  | 13/100 [19:08<3:13:46, 133.64s/it]

[I 2026-05-25 20:00:38,772] Trial 62 finished with value: 0.9499487460299163 and parameters: {'num_leaves': 44, 'max_depth': 4, 'learning_rate': 0.025281191932952713, 'lambda_l1': 0.0026337557650864376, 'lambda_l2': 0.0025344392177927204, 'feature_fraction': 0.6046376257649173, 'bagging_fraction': 0.9313143169357239, 'bagging_freq': 2, 'min_child_samples': 38}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  14%|█████▋                                   | 14/100 [19:09<2:15:07, 94.27s/it]

[I 2026-05-25 20:00:39,188] Trial 63 finished with value: 0.9499247478553281 and parameters: {'num_leaves': 50, 'max_depth': 4, 'learning_rate': 0.025200625357661353, 'lambda_l1': 0.0025387667221555958, 'lambda_l2': 0.0016320650502981485, 'feature_fraction': 0.6425781036798676, 'bagging_fraction': 0.9246842313173458, 'bagging_freq': 2, 'min_child_samples': 93}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  15%|██████▏                                  | 15/100 [19:56<1:53:50, 80.35s/it]

[I 2026-05-25 20:01:26,597] Trial 64 finished with value: 0.9498703224697479 and parameters: {'num_leaves': 51, 'max_depth': 4, 'learning_rate': 0.029808477291624915, 'lambda_l1': 0.002433407323966873, 'lambda_l2': 0.0021138529022940262, 'feature_fraction': 0.7283996731348881, 'bagging_fraction': 0.9402199522104514, 'bagging_freq': 2, 'min_child_samples': 93}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  16%|██████▌                                  | 16/100 [19:58<1:19:49, 57.02s/it]

[I 2026-05-25 20:01:28,584] Trial 66 finished with value: 0.9498896128464864 and parameters: {'num_leaves': 52, 'max_depth': 4, 'learning_rate': 0.030651626274290085, 'lambda_l1': 0.023673407959323718, 'lambda_l2': 0.0020591817919912736, 'feature_fraction': 0.6461708716417227, 'bagging_fraction': 0.9122016137745401, 'bagging_freq': 2, 'min_child_samples': 36}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  17%|███████▎                                   | 17/100 [20:09<59:41, 43.15s/it]

[I 2026-05-25 20:01:39,121] Trial 69 finished with value: 0.9498649230380399 and parameters: {'num_leaves': 51, 'max_depth': 4, 'learning_rate': 0.029531064175398546, 'lambda_l1': 0.002438810315653414, 'lambda_l2': 0.0018276943668534232, 'feature_fraction': 0.6561161240273525, 'bagging_fraction': 0.9266821722226567, 'bagging_freq': 2, 'min_child_samples': 73}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  18%|███████▋                                   | 18/100 [20:13<43:18, 31.68s/it]

[I 2026-05-25 20:01:43,927] Trial 68 finished with value: 0.9498133270511919 and parameters: {'num_leaves': 53, 'max_depth': 4, 'learning_rate': 0.033774915168395515, 'lambda_l1': 0.024081892107287308, 'lambda_l2': 0.0018675304313994687, 'feature_fraction': 0.6479085416094218, 'bagging_fraction': 0.9283176517694777, 'bagging_freq': 2, 'min_child_samples': 94}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  19%|████████▏                                  | 19/100 [20:23<33:42, 24.97s/it]

[I 2026-05-25 20:01:53,186] Trial 65 finished with value: 0.9498173032568479 and parameters: {'num_leaves': 46, 'max_depth': 4, 'learning_rate': 0.032864802657266344, 'lambda_l1': 0.024139986019008793, 'lambda_l2': 0.002071956427541626, 'feature_fraction': 0.7270686980229625, 'bagging_fraction': 0.9284570423275006, 'bagging_freq': 2, 'min_child_samples': 92}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  20%|████████▌                                  | 20/100 [20:46<32:27, 24.34s/it]

[I 2026-05-25 20:02:16,056] Trial 67 finished with value: 0.9498866873008291 and parameters: {'num_leaves': 50, 'max_depth': 4, 'learning_rate': 0.02963913033097626, 'lambda_l1': 0.002778171442844851, 'lambda_l2': 0.001631247397104275, 'feature_fraction': 0.6473749260889256, 'bagging_fraction': 0.93212204301025, 'bagging_freq': 2, 'min_child_samples': 94}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  21%|█████████                                  | 21/100 [21:15<34:08, 25.93s/it]

[I 2026-05-25 20:02:45,696] Trial 70 finished with value: 0.9498284395398194 and parameters: {'num_leaves': 52, 'max_depth': 4, 'learning_rate': 0.03225201422029134, 'lambda_l1': 0.023973507713821316, 'lambda_l2': 0.0248824325683624, 'feature_fraction': 0.6500183124875506, 'bagging_fraction': 0.9388548098978458, 'bagging_freq': 2, 'min_child_samples': 95}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  22%|█████████▍                                 | 22/100 [21:15<23:43, 18.25s/it]

[I 2026-05-25 20:02:46,001] Trial 71 finished with value: 0.9498587202160452 and parameters: {'num_leaves': 51, 'max_depth': 4, 'learning_rate': 0.03050746417402792, 'lambda_l1': 0.002325469490720568, 'lambda_l2': 0.001831428056670501, 'feature_fraction': 0.6492230709119107, 'bagging_fraction': 0.9251790697417639, 'bagging_freq': 2, 'min_child_samples': 73}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  23%|█████████▉                                 | 23/100 [21:20<18:03, 14.08s/it]

[I 2026-05-25 20:02:50,329] Trial 72 finished with value: 0.9498239231986126 and parameters: {'num_leaves': 55, 'max_depth': 4, 'learning_rate': 0.03172316519005412, 'lambda_l1': 0.024631399789972606, 'lambda_l2': 0.025098271613460257, 'feature_fraction': 0.6472132431348073, 'bagging_fraction': 0.9301947660764062, 'bagging_freq': 2, 'min_child_samples': 96}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  24%|██████████▎                                | 24/100 [21:41<20:24, 16.11s/it]

[I 2026-05-25 20:03:11,192] Trial 73 finished with value: 0.9498801289677259 and parameters: {'num_leaves': 51, 'max_depth': 4, 'learning_rate': 0.029775147349799528, 'lambda_l1': 0.02470841850400253, 'lambda_l2': 0.003077337236883502, 'feature_fraction': 0.6414024454857045, 'bagging_fraction': 0.9307390106851574, 'bagging_freq': 2, 'min_child_samples': 73}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  25%|██████████▎                              | 25/100 [23:54<1:04:13, 51.38s/it]

[I 2026-05-25 20:05:24,907] Trial 77 pruned.

Best trial: 32. Best value: 0.95013:  26%|██████████▍                             | 26/100 [27:29<2:03:48, 100.38s/it]

[I 2026-05-25 20:08:59,651] Trial 79 finished with value: 0.950108077578181 and parameters: {'num_leaves': 27, 'max_depth': 3, 'learning_rate': 0.015224166114563962, 'lambda_l1': 0.009355920834102464, 'lambda_l2': 0.004325178805412608, 'feature_fraction': 0.7265024428364307, 'bagging_fraction': 0.8852518547285209, 'bagging_freq': 3, 'min_child_samples': 61}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  27%|███████████                              | 27/100 [27:30<1:25:56, 70.63s/it]

[I 2026-05-25 20:09:00,865] Trial 81 finished with value: 0.950107830803625 and parameters: {'num_leaves': 27, 'max_depth': 3, 'learning_rate': 0.01500096832792726, 'lambda_l1': 0.0011667388143119808, 'lambda_l2': 0.024770452461610533, 'feature_fraction': 0.6268627349094885, 'bagging_fraction': 0.8844161048715439, 'bagging_freq': 3, 'min_child_samples': 85}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  28%|███████████▍                             | 28/100 [27:42<1:03:35, 53.00s/it]

[I 2026-05-25 20:09:12,709] Trial 80 finished with value: 0.9501113115939761 and parameters: {'num_leaves': 228, 'max_depth': 3, 'learning_rate': 0.015155942361210765, 'lambda_l1': 0.0010247581334619554, 'lambda_l2': 0.024956157608215155, 'feature_fraction': 0.694049335463675, 'bagging_fraction': 0.8813027402807216, 'bagging_freq': 3, 'min_child_samples': 62}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  29%|████████████▍                              | 29/100 [28:02<51:02, 43.14s/it]

[I 2026-05-25 20:09:32,840] Trial 74 finished with value: 0.9498657523623153 and parameters: {'num_leaves': 52, 'max_depth': 4, 'learning_rate': 0.029983430001753082, 'lambda_l1': 0.021120328513921538, 'lambda_l2': 0.029238753387761125, 'feature_fraction': 0.6476721407061861, 'bagging_fraction': 0.9124187669872407, 'bagging_freq': 2, 'min_child_samples': 92}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  30%|████████████▉                              | 30/100 [28:14<39:16, 33.66s/it]

[I 2026-05-25 20:09:44,386] Trial 75 finished with value: 0.9497409438047004 and parameters: {'num_leaves': 222, 'max_depth': 4, 'learning_rate': 0.03731946666054762, 'lambda_l1': 0.0010211187514779262, 'lambda_l2': 0.027330488594464443, 'feature_fraction': 0.7217841244878026, 'bagging_fraction': 0.8972017276530997, 'bagging_freq': 2, 'min_child_samples': 75}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  31%|█████████████▎                             | 31/100 [28:17<28:06, 24.45s/it]

[I 2026-05-25 20:09:47,327] Trial 83 finished with value: 0.9501068189794634 and parameters: {'num_leaves': 28, 'max_depth': 3, 'learning_rate': 0.015315780407423365, 'lambda_l1': 0.0010791094456760913, 'lambda_l2': 0.005616815932678237, 'feature_fraction': 0.6957415148046517, 'bagging_fraction': 0.878289923856096, 'bagging_freq': 3, 'min_child_samples': 60}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  32%|█████████████▊                             | 32/100 [28:18<19:42, 17.38s/it]

[I 2026-05-25 20:09:48,231] Trial 82 finished with value: 0.9501156683318127 and parameters: {'num_leaves': 27, 'max_depth': 3, 'learning_rate': 0.015262214354722988, 'lambda_l1': 0.010585189618120721, 'lambda_l2': 0.005363516921764649, 'feature_fraction': 0.6905071052447681, 'bagging_fraction': 0.8815672280393457, 'bagging_freq': 3, 'min_child_samples': 62}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  33%|██████████████▏                            | 33/100 [28:37<19:58, 17.88s/it]

[I 2026-05-25 20:10:07,285] Trial 84 finished with value: 0.950110020148718 and parameters: {'num_leaves': 26, 'max_depth': 3, 'learning_rate': 0.015001771532312464, 'lambda_l1': 0.0010981565122840278, 'lambda_l2': 0.0053953079097461545, 'feature_fraction': 0.7784349155256698, 'bagging_fraction': 0.8015830101919387, 'bagging_freq': 3, 'min_child_samples': 62}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  34%|██████████████▌                            | 34/100 [28:40<14:53, 13.54s/it]

[I 2026-05-25 20:10:10,693] Trial 85 finished with value: 0.9501111634506503 and parameters: {'num_leaves': 27, 'max_depth': 3, 'learning_rate': 0.015590082490477554, 'lambda_l1': 0.009188320793252365, 'lambda_l2': 0.005618632165847023, 'feature_fraction': 0.6950181186950232, 'bagging_fraction': 0.880378442094745, 'bagging_freq': 3, 'min_child_samples': 60}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  35%|███████████████                            | 35/100 [28:43<11:19, 10.45s/it]

[I 2026-05-25 20:10:13,942] Trial 76 finished with value: 0.950068432160706 and parameters: {'num_leaves': 27, 'max_depth': 4, 'learning_rate': 0.015229718094561912, 'lambda_l1': 0.023130879262216436, 'lambda_l2': 0.004560747589902917, 'feature_fraction': 0.6565073587334792, 'bagging_fraction': 0.8863366896095829, 'bagging_freq': 2, 'min_child_samples': 73}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  36%|███████████████▍                           | 36/100 [30:57<50:40, 47.50s/it]

[I 2026-05-25 20:12:27,881] Trial 86 finished with value: 0.9501015759836615 and parameters: {'num_leaves': 27, 'max_depth': 3, 'learning_rate': 0.015497693735832466, 'lambda_l1': 0.010904338044738629, 'lambda_l2': 0.005127102627946706, 'feature_fraction': 0.6919297564958027, 'bagging_fraction': 0.8013375884122219, 'bagging_freq': 3, 'min_child_samples': 61}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  37%|███████████████▏                         | 37/100 [33:04<1:14:56, 71.37s/it]

[I 2026-05-25 20:14:34,931] Trial 78 pruned.

Best trial: 32. Best value: 0.95013:  38%|███████████████▌                         | 38/100 [33:38<1:01:52, 59.88s/it]

[I 2026-05-25 20:15:08,020] Trial 88 finished with value: 0.9501115751558039 and parameters: {'num_leaves': 27, 'max_depth': 3, 'learning_rate': 0.014902123699864963, 'lambda_l1': 0.010076107450663476, 'lambda_l2': 0.004308760729118531, 'feature_fraction': 0.6261708251325018, 'bagging_fraction': 0.80520950671626, 'bagging_freq': 3, 'min_child_samples': 85}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  39%|████████████████▊                          | 39/100 [33:56<48:20, 47.54s/it]

[I 2026-05-25 20:15:26,769] Trial 87 finished with value: 0.9500977111862523 and parameters: {'num_leaves': 26, 'max_depth': 3, 'learning_rate': 0.015334227691269998, 'lambda_l1': 0.00914465923406103, 'lambda_l2': 0.00461192383305787, 'feature_fraction': 0.6925424138185109, 'bagging_fraction': 0.806177230885741, 'bagging_freq': 3, 'min_child_samples': 61}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  40%|█████████████████▏                         | 40/100 [35:02<53:06, 53.11s/it]

[I 2026-05-25 20:16:32,861] Trial 92 finished with value: 0.950127302956702 and parameters: {'num_leaves': 143, 'max_depth': 3, 'learning_rate': 0.011621228283133025, 'lambda_l1': 0.0018341666598198376, 'lambda_l2': 0.009738616789192581, 'feature_fraction': 0.687822073644178, 'bagging_fraction': 0.8050932004403762, 'bagging_freq': 3, 'min_child_samples': 84}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  41%|█████████████████▋                         | 41/100 [35:11<39:03, 39.71s/it]

[I 2026-05-25 20:16:41,331] Trial 95 finished with value: 0.9501253002513007 and parameters: {'num_leaves': 140, 'max_depth': 3, 'learning_rate': 0.011693779218096046, 'lambda_l1': 0.0019017386141569582, 'lambda_l2': 0.008941039548572888, 'feature_fraction': 0.6879715196714443, 'bagging_fraction': 0.8021586598408169, 'bagging_freq': 4, 'min_child_samples': 63}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  42%|████████████████▊                       | 42/100 [39:35<1:43:25, 106.99s/it]

[I 2026-05-25 20:21:05,291] Trial 98 finished with value: 0.950124745642342 and parameters: {'num_leaves': 122, 'max_depth': 3, 'learning_rate': 0.011946706348948496, 'lambda_l1': 0.00178803586538822, 'lambda_l2': 0.008680741378502528, 'feature_fraction': 0.8280077278268972, 'bagging_fraction': 0.848756687596637, 'bagging_freq': 4, 'min_child_samples': 57}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 32. Best value: 0.95013:  43%|█████████████████▋                       | 43/100 [39:39<1:12:27, 76.27s/it]

[I 2026-05-25 20:21:09,887] Trial 99 finished with value: 0.9501181793951776 and parameters: {'num_leaves': 135, 'max_depth': 3, 'learning_rate': 0.01189530093529164, 'lambda_l1': 0.0017412630952273638, 'lambda_l2': 0.00948627342347254, 'feature_fraction': 0.8221320274813428, 'bagging_fraction': 0.7687161547249278, 'bagging_freq': 6, 'min_child_samples': 70}. Best is trial 32 with value: 0.9501301405647788.

Best trial: 100. Best value: 0.95013:  44%|██████████████████▍                       | 44/100 [40:01<55:55, 59.93s/it]

[I 2026-05-25 20:21:31,684] Trial 100 finished with value: 0.950130445902948 and parameters: {'num_leaves': 115, 'max_depth': 3, 'learning_rate': 0.011413984750256696, 'lambda_l1': 0.0017318269752347245, 'lambda_l2': 0.011179738695343467, 'feature_fraction': 0.779248928117725, 'bagging_fraction': 0.7632578505997745, 'bagging_freq': 4, 'min_child_samples': 57}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  45%|██████████████████▉                       | 45/100 [40:55<53:11, 58.03s/it]

[I 2026-05-25 20:22:25,279] Trial 101 finished with value: 0.9501260407963574 and parameters: {'num_leaves': 151, 'max_depth': 3, 'learning_rate': 0.012056553319640914, 'lambda_l1': 0.0017977705211740178, 'lambda_l2': 0.009686953386107073, 'feature_fraction': 0.6697408474910654, 'bagging_fraction': 0.8462023301440548, 'bagging_freq': 4, 'min_child_samples': 82}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  46%|███████████████████▎                      | 46/100 [40:56<37:00, 41.13s/it]

[I 2026-05-25 20:22:26,969] Trial 102 finished with value: 0.9501301559027857 and parameters: {'num_leaves': 142, 'max_depth': 3, 'learning_rate': 0.011582662849122904, 'lambda_l1': 0.0039864626465617, 'lambda_l2': 0.008836854753907351, 'feature_fraction': 0.6746963709772263, 'bagging_fraction': 0.7561818765101925, 'bagging_freq': 4, 'min_child_samples': 57}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  47%|██████████████████▎                    | 47/100 [45:31<1:38:16, 111.25s/it]

[I 2026-05-25 20:27:01,828] Trial 103 finished with value: 0.9501255861552727 and parameters: {'num_leaves': 138, 'max_depth': 3, 'learning_rate': 0.01171539360261837, 'lambda_l1': 0.0017602629168529571, 'lambda_l2': 0.008557828438748269, 'feature_fraction': 0.6307247138496512, 'bagging_fraction': 0.8442494305764764, 'bagging_freq': 4, 'min_child_samples': 57}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  48%|███████████████████▏                    | 48/100 [45:53<1:13:15, 84.52s/it]

[I 2026-05-25 20:27:23,999] Trial 104 finished with value: 0.9501265724737913 and parameters: {'num_leaves': 145, 'max_depth': 3, 'learning_rate': 0.01168584203474656, 'lambda_l1': 0.0016164121937320038, 'lambda_l2': 0.008415759351370733, 'feature_fraction': 0.8235646937589629, 'bagging_fraction': 0.759159039030926, 'bagging_freq': 4, 'min_child_samples': 57}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  49%|████████████████████▌                     | 49/100 [46:13<55:16, 65.04s/it]

[I 2026-05-25 20:27:43,561] Trial 105 finished with value: 0.9501261233497746 and parameters: {'num_leaves': 140, 'max_depth': 3, 'learning_rate': 0.011398758346782908, 'lambda_l1': 0.001728268531079649, 'lambda_l2': 0.009221745589672793, 'feature_fraction': 0.8253571041151265, 'bagging_fraction': 0.7563320299054491, 'bagging_freq': 4, 'min_child_samples': 57}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  50%|█████████████████████                     | 50/100 [46:52<47:34, 57.10s/it]

[I 2026-05-25 20:28:22,137] Trial 106 finished with value: 0.9501096732167813 and parameters: {'num_leaves': 141, 'max_depth': 3, 'learning_rate': 0.011718345735014143, 'lambda_l1': 0.0017146479102607263, 'lambda_l2': 0.00893921226467486, 'feature_fraction': 0.8176114960914366, 'bagging_fraction': 0.7511782706304652, 'bagging_freq': 7, 'min_child_samples': 70}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  51%|█████████████████████▍                    | 51/100 [47:07<36:22, 44.54s/it]

[I 2026-05-25 20:28:37,390] Trial 107 finished with value: 0.9501202179934942 and parameters: {'num_leaves': 141, 'max_depth': 3, 'learning_rate': 0.011866221116268741, 'lambda_l1': 0.0017392806111454298, 'lambda_l2': 0.009564813491508107, 'feature_fraction': 0.8140821213866677, 'bagging_fraction': 0.7663554125479037, 'bagging_freq': 4, 'min_child_samples': 56}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  52%|█████████████████████▊                    | 52/100 [47:34<31:23, 39.24s/it]

[I 2026-05-25 20:29:04,269] Trial 89 finished with value: 0.9498616929036092 and parameters: {'num_leaves': 151, 'max_depth': 7, 'learning_rate': 0.011926856419161505, 'lambda_l1': 0.001888973345456695, 'lambda_l2': 0.004792444753753677, 'feature_fraction': 0.6949298597572838, 'bagging_fraction': 0.9021001102272046, 'bagging_freq': 3, 'min_child_samples': 62}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  53%|██████████████████████▎                   | 53/100 [48:16<31:27, 40.17s/it]

[I 2026-05-25 20:29:46,591] Trial 90 finished with value: 0.9498490081607557 and parameters: {'num_leaves': 134, 'max_depth': 7, 'learning_rate': 0.011882799030157733, 'lambda_l1': 0.009410644402946115, 'lambda_l2': 0.005828248710132262, 'feature_fraction': 0.6952330294715536, 'bagging_fraction': 0.8041933491559421, 'bagging_freq': 3, 'min_child_samples': 62}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  54%|██████████████████████▋                   | 54/100 [48:51<29:30, 38.49s/it]

[I 2026-05-25 20:30:21,177] Trial 93 finished with value: 0.949844837091119 and parameters: {'num_leaves': 153, 'max_depth': 7, 'learning_rate': 0.011982633554149634, 'lambda_l1': 0.009765009207617694, 'lambda_l2': 0.004649780266343491, 'feature_fraction': 0.6919557119599891, 'bagging_fraction': 0.844425759207392, 'bagging_freq': 3, 'min_child_samples': 62}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  55%|███████████████████████                   | 55/100 [49:29<28:45, 38.34s/it]

[I 2026-05-25 20:30:59,171] Trial 94 finished with value: 0.9498523973060005 and parameters: {'num_leaves': 161, 'max_depth': 7, 'learning_rate': 0.011820690804627344, 'lambda_l1': 0.0017395432625036168, 'lambda_l2': 0.0085624473907548, 'feature_fraction': 0.7797629937852038, 'bagging_fraction': 0.8039140902049128, 'bagging_freq': 3, 'min_child_samples': 62}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  56%|███████████████████████▌                  | 56/100 [49:50<24:22, 33.23s/it]

[I 2026-05-25 20:31:20,463] Trial 91 finished with value: 0.9496852041584537 and parameters: {'num_leaves': 117, 'max_depth': 8, 'learning_rate': 0.011665720365919804, 'lambda_l1': 0.0018059037692144504, 'lambda_l2': 0.0042004749902066355, 'feature_fraction': 0.6943961799626459, 'bagging_fraction': 0.7534212535195772, 'bagging_freq': 3, 'min_child_samples': 62}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  57%|███████████████████████▉                  | 57/100 [51:12<34:19, 47.89s/it]

[I 2026-05-25 20:32:42,572] Trial 97 finished with value: 0.9497913512220857 and parameters: {'num_leaves': 149, 'max_depth': 7, 'learning_rate': 0.011717303853616941, 'lambda_l1': 0.0016633394137439538, 'lambda_l2': 0.006786382742225946, 'feature_fraction': 0.8029412138562352, 'bagging_fraction': 0.7497804580871574, 'bagging_freq': 4, 'min_child_samples': 57}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  58%|████████████████████████▎                 | 58/100 [51:49<31:13, 44.61s/it]

[I 2026-05-25 20:33:19,511] Trial 108 finished with value: 0.9501284522156771 and parameters: {'num_leaves': 148, 'max_depth': 3, 'learning_rate': 0.011991812831355636, 'lambda_l1': 0.0017552888768534957, 'lambda_l2': 0.009361967322764134, 'feature_fraction': 0.820490195071303, 'bagging_fraction': 0.7577582998051032, 'bagging_freq': 4, 'min_child_samples': 69}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  59%|████████████████████████▊                 | 59/100 [51:51<21:49, 31.93s/it]

[I 2026-05-25 20:33:21,868] Trial 96 finished with value: 0.9496907765079075 and parameters: {'num_leaves': 154, 'max_depth': 8, 'learning_rate': 0.011787834610713824, 'lambda_l1': 0.0015847286160896757, 'lambda_l2': 0.007797007888431931, 'feature_fraction': 0.8058474446295538, 'bagging_fraction': 0.8449420730589036, 'bagging_freq': 4, 'min_child_samples': 57}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  60%|█████████████████████████▏                | 60/100 [52:16<19:47, 29.70s/it]

[I 2026-05-25 20:33:46,345] Trial 110 finished with value: 0.9501234423561007 and parameters: {'num_leaves': 161, 'max_depth': 3, 'learning_rate': 0.011543883423541559, 'lambda_l1': 0.0014451181428657995, 'lambda_l2': 0.007124902055432927, 'feature_fraction': 0.8092852914250699, 'bagging_fraction': 0.7475244093703434, 'bagging_freq': 4, 'min_child_samples': 51}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  61%|█████████████████████████▌                | 61/100 [52:52<20:37, 31.74s/it]

[I 2026-05-25 20:34:22,866] Trial 111 finished with value: 0.9501230852927762 and parameters: {'num_leaves': 158, 'max_depth': 3, 'learning_rate': 0.011247599222991485, 'lambda_l1': 0.0014626196228720546, 'lambda_l2': 0.011599573199794487, 'feature_fraction': 0.8519324455658434, 'bagging_fraction': 0.7048236130381543, 'bagging_freq': 4, 'min_child_samples': 51}. Best is trial 100 with value: 0.950130445902948.

Best trial: 100. Best value: 0.95013:  62%|██████████████████████████                | 62/100 [53:22<19:46, 31.21s/it]

[I 2026-05-25 20:34:52,848] Trial 112 finished with value: 0.9501207676385391 and parameters: {'num_leaves': 162, 'max_depth': 3, 'learning_rate': 0.011285828481823435, 'lambda_l1': 0.0014300609902334034, 'lambda_l2': 0.011086160341452147, 'feature_fraction': 0.8446388763607154, 'bagging_fraction': 0.7371011336247165, 'bagging_freq': 4, 'min_child_samples': 58}. Best is trial 100 with value: 0.950130445902948.

Best trial: 113. Best value: 0.950133:  63%|█████████████████████████▊               | 63/100 [53:31<15:06, 24.51s/it]

[I 2026-05-25 20:35:01,711] Trial 113 finished with value: 0.9501328003203569 and parameters: {'num_leaves': 121, 'max_depth': 3, 'learning_rate': 0.01110015097253836, 'lambda_l1': 0.0014711502909837116, 'lambda_l2': 0.007032598349522493, 'feature_fraction': 0.8013605562576517, 'bagging_fraction': 0.7057700503351988, 'bagging_freq': 4, 'min_child_samples': 58}. Best is trial 113 with value: 0.9501328003203569.

Best trial: 113. Best value: 0.950133:  64%|██████████████████████████▏              | 64/100 [54:28<20:30, 34.18s/it]

[I 2026-05-25 20:35:58,460] Trial 114 finished with value: 0.950117060217613 and parameters: {'num_leaves': 118, 'max_depth': 3, 'learning_rate': 0.011033168981869016, 'lambda_l1': 0.0013302362278331782, 'lambda_l2': 0.007443046327856934, 'feature_fraction': 0.848057103963137, 'bagging_fraction': 0.720493791853405, 'bagging_freq': 4, 'min_child_samples': 51}. Best is trial 113 with value: 0.9501328003203569.

Best trial: 113. Best value: 0.950133:  65%|██████████████████████████▋              | 65/100 [55:02<19:58, 34.25s/it]

[I 2026-05-25 20:36:32,883] Trial 115 finished with value: 0.9501188732966723 and parameters: {'num_leaves': 119, 'max_depth': 3, 'learning_rate': 0.01095805987323957, 'lambda_l1': 0.0014782545754722445, 'lambda_l2': 0.007056889086667244, 'feature_fraction': 0.845506660781771, 'bagging_fraction': 0.7264386001487619, 'bagging_freq': 4, 'min_child_samples': 58}. Best is trial 113 with value: 0.9501328003203569.

Best trial: 113. Best value: 0.950133:  66%|███████████████████████████              | 66/100 [55:41<20:11, 35.63s/it]

[I 2026-05-25 20:37:11,731] Trial 116 finished with value: 0.9501211811492045 and parameters: {'num_leaves': 117, 'max_depth': 3, 'learning_rate': 0.010806913780632546, 'lambda_l1': 0.0014133388261953195, 'lambda_l2': 0.007021249751930041, 'feature_fraction': 0.846919771122171, 'bagging_fraction': 0.7216895094989058, 'bagging_freq': 4, 'min_child_samples': 58}. Best is trial 113 with value: 0.9501328003203569.

Best trial: 113. Best value: 0.950133:  67%|███████████████████████████▍             | 67/100 [55:58<16:31, 30.04s/it]

[I 2026-05-25 20:37:28,707] Trial 117 finished with value: 0.9501250076825395 and parameters: {'num_leaves': 122, 'max_depth': 3, 'learning_rate': 0.010862404551659594, 'lambda_l1': 0.0014114028868812442, 'lambda_l2': 0.007007344699816924, 'feature_fraction': 0.8389932610094406, 'bagging_fraction': 0.7153742647400835, 'bagging_freq': 4, 'min_child_samples': 89}. Best is trial 113 with value: 0.9501328003203569.

Best trial: 119. Best value: 0.950133:  68%|███████████████████████████▉             | 68/100 [57:50<29:05, 54.54s/it]

[I 2026-05-25 20:39:20,435] Trial 119 finished with value: 0.9501330765565477 and parameters: {'num_leaves': 167, 'max_depth': 3, 'learning_rate': 0.01058778194796316, 'lambda_l1': 0.0014207556829264546, 'lambda_l2': 0.011936900022044129, 'feature_fraction': 0.6720813689977403, 'bagging_fraction': 0.721700132989176, 'bagging_freq': 4, 'min_child_samples': 82}. Best is trial 119 with value: 0.9501330765565477.

Best trial: 119. Best value: 0.950133:  69%|████████████████████████████▎            | 69/100 [57:53<20:11, 39.09s/it]

[I 2026-05-25 20:39:23,458] Trial 118 finished with value: 0.9501217791412152 and parameters: {'num_leaves': 129, 'max_depth': 3, 'learning_rate': 0.010503804694636996, 'lambda_l1': 0.0014268152827980032, 'lambda_l2': 0.0072325019794769, 'feature_fraction': 0.8487279686255496, 'bagging_fraction': 0.717099209835843, 'bagging_freq': 4, 'min_child_samples': 51}. Best is trial 119 with value: 0.9501330765565477.

Best trial: 119. Best value: 0.950133:  70%|████████████████████████████▋            | 70/100 [58:37<20:15, 40.51s/it]

[I 2026-05-25 20:40:07,289] Trial 120 finished with value: 0.9501233646499987 and parameters: {'num_leaves': 168, 'max_depth': 3, 'learning_rate': 0.010807795901153557, 'lambda_l1': 0.001367857611513615, 'lambda_l2': 0.011257853587357688, 'feature_fraction': 0.8367275696005408, 'bagging_fraction': 0.7874454684362766, 'bagging_freq': 4, 'min_child_samples': 51}. Best is trial 119 with value: 0.9501330765565477.

Best trial: 119. Best value: 0.950133:  71%|█████████████████████████████            | 71/100 [58:41<14:15, 29.48s/it]

[I 2026-05-25 20:40:11,044] Trial 121 finished with value: 0.9501223651214806 and parameters: {'num_leaves': 168, 'max_depth': 3, 'learning_rate': 0.010881620523469618, 'lambda_l1': 0.0013411839153165273, 'lambda_l2': 0.01851588111585168, 'feature_fraction': 0.8557390503246965, 'bagging_fraction': 0.7177954791668789, 'bagging_freq': 4, 'min_child_samples': 65}. Best is trial 119 with value: 0.9501330765565477.

Best trial: 119. Best value: 0.950133:  72%|█████████████████████████████▌           | 72/100 [59:15<14:24, 30.89s/it]

[I 2026-05-25 20:40:45,218] Trial 122 finished with value: 0.9501270664513444 and parameters: {'num_leaves': 170, 'max_depth': 3, 'learning_rate': 0.010522174469382473, 'lambda_l1': 0.0038735174115827973, 'lambda_l2': 0.017712827584865316, 'feature_fraction': 0.8363681667148674, 'bagging_fraction': 0.7278911851835576, 'bagging_freq': 4, 'min_child_samples': 82}. Best is trial 119 with value: 0.9501330765565477.

Best trial: 119. Best value: 0.950133:  73%|█████████████████████████████▉           | 73/100 [59:34<12:20, 27.42s/it]

[I 2026-05-25 20:41:04,545] Trial 123 finished with value: 0.9501324519540517 and parameters: {'num_leaves': 129, 'max_depth': 3, 'learning_rate': 0.010675488907688005, 'lambda_l1': 0.002108695939892625, 'lambda_l2': 0.01831237700099431, 'feature_fraction': 0.6704016336391508, 'bagging_fraction': 0.7880862817018929, 'bagging_freq': 4, 'min_child_samples': 66}. Best is trial 119 with value: 0.9501330765565477.

Best trial: 119. Best value: 0.950133:  74%|████████████████████████████▊          | 74/100 [1:00:00<11:40, 26.95s/it]

[I 2026-05-25 20:41:30,397] Trial 124 finished with value: 0.9501329600184741 and parameters: {'num_leaves': 175, 'max_depth': 3, 'learning_rate': 0.01074945290433952, 'lambda_l1': 0.0041744427152179756, 'lambda_l2': 0.01814418209559794, 'feature_fraction': 0.7944993091713966, 'bagging_fraction': 0.7860809020843301, 'bagging_freq': 4, 'min_child_samples': 65}. Best is trial 119 with value: 0.9501330765565477.

Best trial: 125. Best value: 0.950134:  75%|█████████████████████████████▎         | 75/100 [1:00:59<15:17, 36.72s/it]

[I 2026-05-25 20:42:29,909] Trial 125 finished with value: 0.9501335417861044 and parameters: {'num_leaves': 170, 'max_depth': 3, 'learning_rate': 0.01059812570123415, 'lambda_l1': 0.004122478076423567, 'lambda_l2': 0.019064654208803315, 'feature_fraction': 0.7885391850591392, 'bagging_fraction': 0.7866145307758342, 'bagging_freq': 4, 'min_child_samples': 66}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  76%|█████████████████████████████▋         | 76/100 [1:01:18<12:27, 31.15s/it]

[I 2026-05-25 20:42:48,056] Trial 126 finished with value: 0.9501202200376284 and parameters: {'num_leaves': 169, 'max_depth': 3, 'learning_rate': 0.01405196828602203, 'lambda_l1': 0.004187091148444073, 'lambda_l2': 9.633875198637458, 'feature_fraction': 0.6706294238421604, 'bagging_fraction': 0.7878828194820838, 'bagging_freq': 4, 'min_child_samples': 67}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  77%|██████████████████████████████         | 77/100 [1:01:49<11:55, 31.09s/it]

[I 2026-05-25 20:43:19,022] Trial 127 finished with value: 0.9501217380485272 and parameters: {'num_leaves': 169, 'max_depth': 3, 'learning_rate': 0.013938651117129835, 'lambda_l1': 0.0021482007525209287, 'lambda_l2': 0.01526245487158515, 'feature_fraction': 0.6718836923007425, 'bagging_fraction': 0.7918150245031848, 'bagging_freq': 4, 'min_child_samples': 66}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  78%|██████████████████████████████▍        | 78/100 [1:02:28<12:19, 33.62s/it]

[I 2026-05-25 20:43:58,541] Trial 128 finished with value: 0.9501316486536595 and parameters: {'num_leaves': 129, 'max_depth': 3, 'learning_rate': 0.010356629046526124, 'lambda_l1': 0.003994021120830624, 'lambda_l2': 0.01620736417616838, 'feature_fraction': 0.793872095689091, 'bagging_fraction': 0.7870221746749209, 'bagging_freq': 4, 'min_child_samples': 65}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  79%|██████████████████████████████▊        | 79/100 [1:03:37<15:28, 44.21s/it]

[I 2026-05-25 20:45:07,450] Trial 129 finished with value: 0.9501256044271672 and parameters: {'num_leaves': 111, 'max_depth': 3, 'learning_rate': 0.014110423677336753, 'lambda_l1': 0.004123626295236077, 'lambda_l2': 0.01380814272666931, 'feature_fraction': 0.6751620853510969, 'bagging_fraction': 0.6759542628732572, 'bagging_freq': 4, 'min_child_samples': 67}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  80%|███████████████████████████████▏       | 80/100 [1:04:39<16:34, 49.71s/it]

[I 2026-05-25 20:46:10,010] Trial 132 finished with value: 0.9501158077273381 and parameters: {'num_leaves': 143, 'max_depth': 3, 'learning_rate': 0.014038436792090379, 'lambda_l1': 0.0020472751978628883, 'lambda_l2': 0.01652941063978215, 'feature_fraction': 0.6692250810129046, 'bagging_fraction': 0.7601785670809351, 'bagging_freq': 4, 'min_child_samples': 83}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  81%|███████████████████████████████▌       | 81/100 [1:05:10<13:57, 44.08s/it]

[I 2026-05-25 20:46:40,927] Trial 133 finished with value: 0.9501191721877094 and parameters: {'num_leaves': 183, 'max_depth': 3, 'learning_rate': 0.013830786907409064, 'lambda_l1': 0.0021067785030316442, 'lambda_l2': 0.015304184455980824, 'feature_fraction': 0.6706574092812302, 'bagging_fraction': 0.7609614238387237, 'bagging_freq': 4, 'min_child_samples': 76}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  82%|███████████████████████████████▉       | 82/100 [1:05:52<12:58, 43.25s/it]

[I 2026-05-25 20:47:22,244] Trial 130 finished with value: 0.9500726022387835 and parameters: {'num_leaves': 171, 'max_depth': 4, 'learning_rate': 0.013936501515442033, 'lambda_l1': 0.003943447915776807, 'lambda_l2': 0.015165628828165415, 'feature_fraction': 0.7936590429657642, 'bagging_fraction': 0.7854118120591368, 'bagging_freq': 4, 'min_child_samples': 82}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  83%|████████████████████████████████▎      | 83/100 [1:06:27<11:33, 40.82s/it]

[I 2026-05-25 20:47:57,401] Trial 131 finished with value: 0.9500790868486014 and parameters: {'num_leaves': 176, 'max_depth': 4, 'learning_rate': 0.013808678971835093, 'lambda_l1': 0.0030589683232908177, 'lambda_l2': 0.01926166389855514, 'feature_fraction': 0.7946051097563893, 'bagging_fraction': 0.6856234184116854, 'bagging_freq': 4, 'min_child_samples': 81}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  84%|████████████████████████████████▊      | 84/100 [1:06:48<09:16, 34.78s/it]

[I 2026-05-25 20:48:18,076] Trial 134 finished with value: 0.9500776556030415 and parameters: {'num_leaves': 183, 'max_depth': 4, 'learning_rate': 0.014065939418814307, 'lambda_l1': 0.0035826050905033192, 'lambda_l2': 0.016072691378257547, 'feature_fraction': 0.6695403633055961, 'bagging_fraction': 0.6859630444679775, 'bagging_freq': 4, 'min_child_samples': 82}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  85%|█████████████████████████████████▏     | 85/100 [1:07:47<10:31, 42.08s/it]

[I 2026-05-25 20:49:17,207] Trial 135 finished with value: 0.950071066805996 and parameters: {'num_leaves': 183, 'max_depth': 4, 'learning_rate': 0.013852964550461089, 'lambda_l1': 0.004382074823233788, 'lambda_l2': 0.01602973298335102, 'feature_fraction': 0.7926221285849238, 'bagging_fraction': 0.7611256509025093, 'bagging_freq': 4, 'min_child_samples': 77}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  86%|█████████████████████████████████▌     | 86/100 [1:08:37<10:24, 44.57s/it]

[I 2026-05-25 20:50:07,599] Trial 136 finished with value: 0.9501238374373312 and parameters: {'num_leaves': 183, 'max_depth': 4, 'learning_rate': 0.010022563647953798, 'lambda_l1': 0.00428193905765852, 'lambda_l2': 0.01649974579726466, 'feature_fraction': 0.7902626978130421, 'bagging_fraction': 0.6728115736239662, 'bagging_freq': 4, 'min_child_samples': 77}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  87%|█████████████████████████████████▉     | 87/100 [1:08:52<07:43, 35.63s/it]

[I 2026-05-25 20:50:22,362] Trial 137 finished with value: 0.9501239200523995 and parameters: {'num_leaves': 189, 'max_depth': 4, 'learning_rate': 0.010021173030874644, 'lambda_l1': 0.0031354412689733368, 'lambda_l2': 0.02041077136656496, 'feature_fraction': 0.7908763198644562, 'bagging_fraction': 0.6790500875437266, 'bagging_freq': 4, 'min_child_samples': 83}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  88%|██████████████████████████████████▎    | 88/100 [1:09:51<08:32, 42.67s/it]

[I 2026-05-25 20:51:21,461] Trial 109 finished with value: 0.9496575972764736 and parameters: {'num_leaves': 158, 'max_depth': 8, 'learning_rate': 0.01166069250464718, 'lambda_l1': 0.0015492369432106847, 'lambda_l2': 0.00836172418705935, 'feature_fraction': 0.8138315192583399, 'bagging_fraction': 0.7458527073907766, 'bagging_freq': 4, 'min_child_samples': 57}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  89%|██████████████████████████████████▋    | 89/100 [1:10:13<06:41, 36.51s/it]

[I 2026-05-25 20:51:43,589] Trial 139 finished with value: 0.950131461590454 and parameters: {'num_leaves': 185, 'max_depth': 4, 'learning_rate': 0.010000096125397324, 'lambda_l1': 0.0032830621142596527, 'lambda_l2': 0.020460730082599802, 'feature_fraction': 0.7881726013240004, 'bagging_fraction': 0.6946118321028159, 'bagging_freq': 4, 'min_child_samples': 76}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  90%|███████████████████████████████████    | 90/100 [1:10:22<04:40, 28.10s/it]

[I 2026-05-25 20:51:52,071] Trial 138 finished with value: 0.9501120746707257 and parameters: {'num_leaves': 186, 'max_depth': 4, 'learning_rate': 0.010084109569467078, 'lambda_l1': 0.0032790018530356986, 'lambda_l2': 0.01943048218692619, 'feature_fraction': 0.8751140261944215, 'bagging_fraction': 0.7766149343714762, 'bagging_freq': 4, 'min_child_samples': 83}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  91%|███████████████████████████████████▍   | 91/100 [1:11:33<06:09, 41.10s/it]

[I 2026-05-25 20:53:03,484] Trial 140 finished with value: 0.9501195702025245 and parameters: {'num_leaves': 186, 'max_depth': 4, 'learning_rate': 0.010128635786777616, 'lambda_l1': 0.002779619164056387, 'lambda_l2': 0.018813805325802683, 'feature_fraction': 0.7921458304476273, 'bagging_fraction': 0.7776494048624566, 'bagging_freq': 4, 'min_child_samples': 83}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  92%|███████████████████████████████████▉   | 92/100 [1:12:08<05:15, 39.39s/it]

[I 2026-05-25 20:53:38,893] Trial 141 finished with value: 0.9501046813466637 and parameters: {'num_leaves': 184, 'max_depth': 4, 'learning_rate': 0.010331504385038874, 'lambda_l1': 0.003406286225304381, 'lambda_l2': 0.020047037790557387, 'feature_fraction': 0.7970469135223941, 'bagging_fraction': 0.7387408813325688, 'bagging_freq': 4, 'min_child_samples': 87}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  93%|████████████████████████████████████▎  | 93/100 [1:12:44<04:26, 38.13s/it]

[I 2026-05-25 20:54:14,076] Trial 142 finished with value: 0.9501198590807617 and parameters: {'num_leaves': 197, 'max_depth': 4, 'learning_rate': 0.010138215266054617, 'lambda_l1': 0.003481016725293202, 'lambda_l2': 0.01971686217470159, 'feature_fraction': 0.793858480889487, 'bagging_fraction': 0.7786243967412023, 'bagging_freq': 4, 'min_child_samples': 65}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  94%|████████████████████████████████████▋  | 94/100 [1:12:51<02:53, 28.91s/it]

[I 2026-05-25 20:54:21,477] Trial 143 finished with value: 0.9501186062155197 and parameters: {'num_leaves': 129, 'max_depth': 4, 'learning_rate': 0.010312673084495337, 'lambda_l1': 0.002908480382278309, 'lambda_l2': 0.019239022831297515, 'feature_fraction': 0.7915810130337928, 'bagging_fraction': 0.7789671963886782, 'bagging_freq': 4, 'min_child_samples': 64}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  95%|█████████████████████████████████████  | 95/100 [1:12:56<01:48, 21.74s/it]

[I 2026-05-25 20:54:26,493] Trial 145 finished with value: 0.9501286244196615 and parameters: {'num_leaves': 189, 'max_depth': 3, 'learning_rate': 0.010301080493177277, 'lambda_l1': 0.003012765542939144, 'lambda_l2': 0.019793394878787965, 'feature_fraction': 0.867879583570971, 'bagging_fraction': 0.7745423950394722, 'bagging_freq': 4, 'min_child_samples': 77}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  96%|█████████████████████████████████████▍ | 96/100 [1:13:20<01:30, 22.53s/it]

[I 2026-05-25 20:54:50,882] Trial 146 finished with value: 0.9501298793178237 and parameters: {'num_leaves': 131, 'max_depth': 3, 'learning_rate': 0.010172248494816804, 'lambda_l1': 0.0028834169031883797, 'lambda_l2': 0.020575534074074003, 'feature_fraction': 0.7593594743396639, 'bagging_fraction': 0.7751833065126656, 'bagging_freq': 4, 'min_child_samples': 65}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  97%|█████████████████████████████████████▊ | 97/100 [1:13:29<00:55, 18.47s/it]

[I 2026-05-25 20:54:59,855] Trial 144 finished with value: 0.9501140700585922 and parameters: {'num_leaves': 193, 'max_depth': 4, 'learning_rate': 0.010265615119859831, 'lambda_l1': 0.0033850796716508825, 'lambda_l2': 0.02098560089060636, 'feature_fraction': 0.7887177962104555, 'bagging_fraction': 0.777925412689298, 'bagging_freq': 4, 'min_child_samples': 76}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  98%|██████████████████████████████████████▏| 98/100 [1:13:58<00:42, 21.42s/it]

[I 2026-05-25 20:55:28,167] Trial 147 finished with value: 0.9501244617658923 and parameters: {'num_leaves': 195, 'max_depth': 3, 'learning_rate': 0.012565289999093126, 'lambda_l1': 0.34268952053104595, 'lambda_l2': 1.1904159905642004, 'feature_fraction': 0.7723902397419522, 'bagging_fraction': 0.7750639263342847, 'bagging_freq': 4, 'min_child_samples': 64}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134:  99%|██████████████████████████████████████▌| 99/100 [1:14:03<00:16, 16.48s/it]

[I 2026-05-25 20:55:33,127] Trial 148 finished with value: 0.9501186224519005 and parameters: {'num_leaves': 128, 'max_depth': 3, 'learning_rate': 0.012545542730901164, 'lambda_l1': 0.002720039839131347, 'lambda_l2': 0.716508673802421, 'feature_fraction': 0.8796832719969072, 'bagging_fraction': 0.7790773799001411, 'bagging_freq': 4, 'min_child_samples': 69}. Best is trial 125 with value: 0.9501335417861044.

Best trial: 125. Best value: 0.950134: 100%|██████████████████████████████████████| 100/100 [1:14:20<00:00, 44.60s/it]

[I 2026-05-25 20:55:50,150] Trial 149 finished with value: 0.9501259116763784 and parameters: {'num_leaves': 129, 'max_depth': 3, 'learning_rate': 0.012588066259379983, 'lambda_l1': 0.10189569299996734, 'lambda_l2': 0.04739755566387959, 'feature_fraction': 0.7726157151574102, 'bagging_fraction': 0.7787755416846514, 'bagging_freq': 4, 'min_child_samples': 64}. Best is trial 125 with value: 0.9501335417861044.

In [14]:
stacking_lgbm = LGBMClassifier(
    **study.best_params, 
    verbosity=-1, 
    n_estimators=2000,
    random_state=42,
    objective='binary',
    metric='auc',
    boosting_type='gbdt'
).fit(X_train, y_train.PitNextLap)

# Submission

In [15]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [16]:
submission['PitNextLap'] = stacking_lgbm.predict_proba(X_test)[:, 1]

In [17]:
submission.to_csv('../data/submission/submission.csv', index=False)

In [18]:
X_train.columns

Index(['lgbm_proba', 'cat_proba', 'xgb_proba', 'hist_proba', 'lg_proba',
       'pca_knn_proba', 'ridge_logit', 'truncatedsvd_linear_svc_logit',
       'truncatedsvd_ridge_logit', 'sgdclassifier_proba',
       'truncatedsvd_lgbm_proba', 'truncatedsvd_knn_proba',
       'truncatedsvd_nystroem_knn_proba', 'truncatedsvd_rbfsampler_knn_proba',
       'truncatedsvd_logistic_regression_proba',
       'truncatedsvd_nystroem_logistic_regression_proba',
       'truncatedsvd_nystroem_sgdclassifier_proba',
       'truncatedsvd_rbfsampler_logistic_regression_proba',
       'truncatedsvd_rbfsampler_sgdclassifier_proba',
       'voting_lgbm_and_cat_and_xgb_and_hist_proba',
       'voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier',
       'voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba',
       'stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit'],
      dtype='str')