# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from lightgbm import LGBMClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking2.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking2.parquet')

In [4]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba,stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.496500,0.527291,0.637203,0.806670,...,0.3,0.815075,0.788450,0.867595,0.911292,0.783514,0.868510,0.784140,0.618609,0.543036
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.340099,0.303278,0.512236,0.734278,...,0.7,0.686883,0.686778,0.594025,0.698730,0.695484,0.772514,0.666212,0.572044,0.446302
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.127990,0.192701,0.330117,0.533609,...,0.5,0.580053,0.607686,0.523752,0.600009,0.614942,0.717012,0.570198,0.631260,0.440385
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,-1.249994,-1.823374,-0.834575,0.001354,...,0.0,0.002635,0.002627,0.013206,0.025528,0.000000,0.005494,0.063219,0.000000,0.076485
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,-0.090382,-0.011299,0.200067,0.386963,...,0.3,0.397511,0.457883,0.364956,0.265409,0.452112,0.482416,0.418672,0.245866,0.244423

In [5]:
X_test.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,pca_knn_proba,ridge_logit,truncatedsvd_linear_svc_logit,truncatedsvd_ridge_logit,sgdclassifier_proba,...,truncatedsvd_rbfsampler_knn_proba,truncatedsvd_logistic_regression_proba,truncatedsvd_nystroem_logistic_regression_proba,truncatedsvd_nystroem_sgdclassifier_proba,truncatedsvd_rbfsampler_logistic_regression_proba,truncatedsvd_rbfsampler_sgdclassifier_proba,voting_lgbm_and_cat_and_xgb_and_hist_proba,voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier,voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba,stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,-1.272709,-1.721325,-0.872993,0.005473,...,0.0,0.006534,0.003712,0.009642,0.010313,0.000000,0.019849,0.061327,0.000000,0.076454
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,-0.626960,-0.919863,-0.289991,0.054146,...,0.1,0.063555,0.110500,0.044563,0.145672,0.047794,0.012173,0.144461,0.102869,0.089535
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,-1.335019,-1.809246,-0.917667,0.003687,...,0.0,0.004404,0.003123,0.008417,0.006856,0.000000,0.010304,0.057929,0.000000,0.076454
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.190133,0.328363,0.387739,0.676445,...,0.3,0.670446,0.712745,0.648495,0.504756,0.637237,0.444558,0.628242,0.183451,0.215908
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.535153,0.644014,0.670147,0.852891,...,0.8,0.835307,0.855796,0.796202,0.823601,0.787922,0.939648,0.787450,0.823541,0.643512

# Machine Learning

In [18]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "objective": "binary",
        "n_estimators": trial.suggest_int("n_estimators", 30, 300),
        "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.05, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 4),
        "num_leaves": trial.suggest_int("num_leaves", 2, 16),
        "min_child_samples": trial.suggest_int("min_child_samples", 20, 300),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-5, 100, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-5, 100, log=True),
        "verbosity": -1,
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LGBMClassifier(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=400, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-25 16:34:16,350] A new study created in memory with name: no-name-95dac7a0-9615-42f6-b3a5-62c49ab455a7
Best trial: 0. Best value: 0.94963:   0%|                                           | 1/400 [00:22<2:30:34, 22.64s/it]

[I 2026-05-25 16:34:38,980] Trial 0 finished with value: 0.9496297555027505 and parameters: {'n_estimators': 55, 'learning_rate': 0.02143359339870089, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 171, 'subsample': 0.9496233692684151, 'colsample_bytree': 0.8664141178120989, 'reg_alpha': 0.07954603021890694, 'reg_lambda': 10.82244197290681}. Best is trial 0 with value: 0.9496297555027505.

Best trial: 9. Best value: 0.949697:   0%|▏                                         | 2/400 [00:28<1:25:18, 12.86s/it]

[I 2026-05-25 16:34:44,987] Trial 9 finished with value: 0.9496967419959775 and parameters: {'n_estimators': 200, 'learning_rate': 0.03948082767141426, 'max_depth': 3, 'num_leaves': 2, 'min_child_samples': 144, 'subsample': 0.7328384884066917, 'colsample_bytree': 0.6371658666252459, 'reg_alpha': 0.031874671900745104, 'reg_lambda': 15.5960535682379}. Best is trial 9 with value: 0.9496967419959775.

Best trial: 9. Best value: 0.949697:   1%|▎                                           | 3/400 [00:30<52:48,  7.98s/it]

[I 2026-05-25 16:34:47,167] Trial 7 finished with value: 0.9403837547050294 and parameters: {'n_estimators': 195, 'learning_rate': 0.0067655634868260366, 'max_depth': 1, 'num_leaves': 8, 'min_child_samples': 292, 'subsample': 0.8960325839655954, 'colsample_bytree': 0.8295164130775505, 'reg_alpha': 4.430379317079281, 'reg_lambda': 52.12129723058706}. Best is trial 9 with value: 0.9496967419959775.

Best trial: 9. Best value: 0.949697:   1%|▍                                           | 4/400 [00:34<42:25,  6.43s/it]

[I 2026-05-25 16:34:51,213] Trial 12 finished with value: 0.901584573378658 and parameters: {'n_estimators': 47, 'learning_rate': 0.0035387511027748795, 'max_depth': 1, 'num_leaves': 6, 'min_child_samples': 208, 'subsample': 0.8491360602699548, 'colsample_bytree': 0.8138289735406622, 'reg_alpha': 6.473500296096191, 'reg_lambda': 0.00010953031826900943}. Best is trial 9 with value: 0.9496967419959775.

Best trial: 9. Best value: 0.949697:   1%|▌                                           | 5/400 [00:35<27:40,  4.20s/it]

[I 2026-05-25 16:34:51,437] Trial 5 finished with value: 0.9468756258807678 and parameters: {'n_estimators': 183, 'learning_rate': 0.010400854721274635, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 125, 'subsample': 0.7746004377903861, 'colsample_bytree': 0.7367625296398274, 'reg_alpha': 0.01200637303338567, 'reg_lambda': 6.147612692902506e-05}. Best is trial 9 with value: 0.9496967419959775.

Best trial: 9. Best value: 0.949697:   2%|▋                                           | 6/400 [00:35<18:45,  2.86s/it]

[I 2026-05-25 16:34:51,687] Trial 1 pruned.

Best trial: 9. Best value: 0.949697:   2%|▊                                           | 7/400 [00:38<19:44,  3.01s/it]

[I 2026-05-25 16:34:55,047] Trial 6 finished with value: 0.946607234591571 and parameters: {'n_estimators': 201, 'learning_rate': 0.004762743521754113, 'max_depth': 2, 'num_leaves': 5, 'min_child_samples': 278, 'subsample': 0.7235749359203546, 'colsample_bytree': 0.6864514859896325, 'reg_alpha': 60.88189949847594, 'reg_lambda': 0.14226573758604946}. Best is trial 9 with value: 0.9496967419959775.

Best trial: 10. Best value: 0.949962:   2%|▊                                          | 8/400 [00:59<56:44,  8.68s/it]

[I 2026-05-25 16:35:15,860] Trial 10 finished with value: 0.9499623014018768 and parameters: {'n_estimators': 283, 'learning_rate': 0.028256124127248986, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 193, 'subsample': 0.8539087161997531, 'colsample_bytree': 0.990344193306381, 'reg_alpha': 0.8463466427781293, 'reg_lambda': 0.008322934158400692}. Best is trial 10 with value: 0.9499623014018768.

Best trial: 10. Best value: 0.949962:   2%|▉                                          | 9/400 [01:01<43:50,  6.73s/it]

[I 2026-05-25 16:35:18,307] Trial 8 finished with value: 0.9497824834685324 and parameters: {'n_estimators': 238, 'learning_rate': 0.015386948821314975, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 56, 'subsample': 0.8357852642717282, 'colsample_bytree': 0.7279062729895746, 'reg_alpha': 0.0015805071303503957, 'reg_lambda': 2.830162115905017e-05}. Best is trial 10 with value: 0.9499623014018768.

Best trial: 10. Best value: 0.949962:   2%|█                                         | 10/400 [01:04<35:36,  5.48s/it]

[I 2026-05-25 16:35:20,966] Trial 13 finished with value: 0.9475498138705636 and parameters: {'n_estimators': 176, 'learning_rate': 0.007649206223001991, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 23, 'subsample': 0.832918359113286, 'colsample_bytree': 0.7620902620774628, 'reg_alpha': 27.382772560902072, 'reg_lambda': 0.6234132892598931}. Best is trial 10 with value: 0.9499623014018768.

Best trial: 10. Best value: 0.949962:   3%|█▏                                        | 11/400 [01:10<37:11,  5.74s/it]

[I 2026-05-25 16:35:27,286] Trial 2 finished with value: 0.9497965677798236 and parameters: {'n_estimators': 261, 'learning_rate': 0.015190899594240187, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 140, 'subsample': 0.8978812275004926, 'colsample_bytree': 0.8047377031318792, 'reg_alpha': 0.1461510327947973, 'reg_lambda': 0.07706355683319102}. Best is trial 10 with value: 0.9499623014018768.

Best trial: 10. Best value: 0.949962:   3%|█▎                                        | 12/400 [01:12<28:10,  4.36s/it]

[I 2026-05-25 16:35:28,500] Trial 17 pruned.

Best trial: 4. Best value: 0.950111:   3%|█▍                                         | 13/400 [01:15<25:22,  3.93s/it]

[I 2026-05-25 16:35:31,429] Trial 4 finished with value: 0.9501107737551198 and parameters: {'n_estimators': 257, 'learning_rate': 0.04903202671586062, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 54, 'subsample': 0.7300705881337628, 'colsample_bytree': 0.9519751362055751, 'reg_alpha': 9.801101100162219, 'reg_lambda': 0.30880350514984173}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   4%|█▌                                         | 14/400 [01:22<32:42,  5.08s/it]

[I 2026-05-25 16:35:39,213] Trial 11 finished with value: 0.9494104389875974 and parameters: {'n_estimators': 290, 'learning_rate': 0.008312921200687759, 'max_depth': 4, 'num_leaves': 6, 'min_child_samples': 177, 'subsample': 0.6914249866400477, 'colsample_bytree': 0.904203120047534, 'reg_alpha': 0.0032721986878084283, 'reg_lambda': 0.009082320139022012}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   4%|█▌                                         | 15/400 [01:29<36:12,  5.64s/it]

[I 2026-05-25 16:35:46,141] Trial 18 finished with value: 0.949182114095857 and parameters: {'n_estimators': 182, 'learning_rate': 0.008098434438602637, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 217, 'subsample': 0.9895745303008728, 'colsample_bytree': 0.849397252999419, 'reg_alpha': 29.555472533633218, 'reg_lambda': 3.570181507919741e-05}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   4%|█▋                                         | 16/400 [01:31<28:48,  4.50s/it]

[I 2026-05-25 16:35:47,985] Trial 15 finished with value: 0.9491051623841914 and parameters: {'n_estimators': 201, 'learning_rate': 0.004309891721975142, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 247, 'subsample': 0.979984885652065, 'colsample_bytree': 0.6425976460403177, 'reg_alpha': 0.09807227984155593, 'reg_lambda': 38.02520441838562}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   4%|█▊                                         | 17/400 [01:32<22:35,  3.54s/it]

[I 2026-05-25 16:35:49,306] Trial 3 finished with value: 0.9497775733559631 and parameters: {'n_estimators': 296, 'learning_rate': 0.005922177054941514, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 65, 'subsample': 0.7188528255996378, 'colsample_bytree': 0.7942714006568932, 'reg_alpha': 0.3826067382456244, 'reg_lambda': 0.250362974071913}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   4%|█▉                                         | 18/400 [01:40<30:37,  4.81s/it]

[I 2026-05-25 16:35:57,051] Trial 19 finished with value: 0.9497151620718555 and parameters: {'n_estimators': 285, 'learning_rate': 0.02748035253571155, 'max_depth': 1, 'num_leaves': 5, 'min_child_samples': 148, 'subsample': 0.9945941381013021, 'colsample_bytree': 0.727899198123987, 'reg_alpha': 13.669957826009176, 'reg_lambda': 4.978807637080055}. Best is trial 4 with value: 0.9501107737551198.
[I 2026-05-25 16:35:57,109] Trial 14 finished with value: 0.9497053945539562 and parameters: {'n_estimators': 214, 'learning_rate': 0.007832401353109844, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 137, 'subsample': 0.8236226314350701, 'colsample_bytree': 0.8186439053851795, 'reg_alpha': 0.8372741332384166, 'reg_lambda': 4.65897036473558}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   5%|██▏                                        | 20/400 [01:42<19:14,  3.04s/it]

[I 2026-05-25 16:35:59,003] Trial 20 pruned.

Best trial: 4. Best value: 0.950111:   5%|██▎                                        | 21/400 [01:48<23:51,  3.78s/it]

[I 2026-05-25 16:36:04,987] Trial 25 finished with value: 0.9497327245087778 and parameters: {'n_estimators': 100, 'learning_rate': 0.04406011075468149, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 94, 'subsample': 0.6208395667915373, 'colsample_bytree': 0.9965787732334425, 'reg_alpha': 3.2751692684908895e-05, 'reg_lambda': 0.003935140927516433}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   6%|██▎                                        | 22/400 [01:53<25:01,  3.97s/it]

[I 2026-05-25 16:36:09,548] Trial 16 finished with value: 0.9498635038472454 and parameters: {'n_estimators': 273, 'learning_rate': 0.011775245555261687, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 213, 'subsample': 0.9139417992963575, 'colsample_bytree': 0.7744099249344815, 'reg_alpha': 0.27478482635857593, 'reg_lambda': 2.4522031689656516}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   6%|██▍                                        | 23/400 [01:54<19:46,  3.15s/it]

[I 2026-05-25 16:36:10,492] Trial 26 finished with value: 0.949755977297621 and parameters: {'n_estimators': 98, 'learning_rate': 0.0497480574780065, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 86, 'subsample': 0.6058415921714657, 'colsample_bytree': 0.9552065232300953, 'reg_alpha': 1.4171436102915246e-05, 'reg_lambda': 0.004120907473166039}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   6%|██▌                                        | 24/400 [01:58<22:31,  3.60s/it]

[I 2026-05-25 16:36:15,253] Trial 28 finished with value: 0.9497777149138737 and parameters: {'n_estimators': 110, 'learning_rate': 0.048709876794164914, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 103, 'subsample': 0.626632965998815, 'colsample_bytree': 0.9699052057088605, 'reg_alpha': 2.9525129135424162e-05, 'reg_lambda': 0.004898295327114797}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   6%|██▋                                        | 25/400 [01:59<17:02,  2.73s/it]

[I 2026-05-25 16:36:15,782] Trial 27 finished with value: 0.9497473622361859 and parameters: {'n_estimators': 111, 'learning_rate': 0.044076015283622545, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 96, 'subsample': 0.6070612652553292, 'colsample_bytree': 0.9997714548193272, 'reg_alpha': 3.130621521625805e-05, 'reg_lambda': 0.008298296877921642}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   6%|██▊                                        | 26/400 [02:09<29:20,  4.71s/it]

[I 2026-05-25 16:36:25,359] Trial 31 finished with value: 0.9497506592135885 and parameters: {'n_estimators': 102, 'learning_rate': 0.04720665127406273, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 97, 'subsample': 0.6268946393917515, 'colsample_bytree': 0.9831970533827418, 'reg_alpha': 3.9744964611485276e-05, 'reg_lambda': 0.005528386223874402}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   7%|██▉                                        | 27/400 [02:10<23:03,  3.71s/it]

[I 2026-05-25 16:36:26,647] Trial 30 finished with value: 0.9498317457691469 and parameters: {'n_estimators': 122, 'learning_rate': 0.04928768169215795, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 100, 'subsample': 0.605742107364193, 'colsample_bytree': 0.9997574123192234, 'reg_alpha': 1.955061480358197e-05, 'reg_lambda': 0.006354359867596678}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   7%|███                                        | 28/400 [02:13<21:39,  3.49s/it]

[I 2026-05-25 16:36:29,608] Trial 29 finished with value: 0.9498810610155568 and parameters: {'n_estimators': 134, 'learning_rate': 0.04946501404971809, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 99, 'subsample': 0.6023138985546275, 'colsample_bytree': 0.9916444764100334, 'reg_alpha': 7.123417042344161e-05, 'reg_lambda': 0.0056090873433496235}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   7%|███                                        | 29/400 [02:23<34:29,  5.58s/it]

[I 2026-05-25 16:36:40,150] Trial 32 finished with value: 0.9497377085762079 and parameters: {'n_estimators': 145, 'learning_rate': 0.0308780224676207, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 204, 'subsample': 0.8879584096416931, 'colsample_bytree': 0.9981830877930443, 'reg_alpha': 1.1745666902125658, 'reg_lambda': 0.02737155757413327}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   8%|███▏                                       | 30/400 [02:29<35:12,  5.71s/it]

[I 2026-05-25 16:36:46,177] Trial 21 finished with value: 0.950083105056383 and parameters: {'n_estimators': 295, 'learning_rate': 0.04890894386799581, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 221, 'subsample': 0.6019735287919037, 'colsample_bytree': 0.9777562338062497, 'reg_alpha': 4.443726170949316e-05, 'reg_lambda': 0.007660652763293036}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   8%|███▎                                       | 31/400 [02:38<40:33,  6.60s/it]

[I 2026-05-25 16:36:54,855] Trial 39 finished with value: 0.9491619736856294 and parameters: {'n_estimators': 146, 'learning_rate': 0.032889025802820264, 'max_depth': 1, 'num_leaves': 9, 'min_child_samples': 34, 'subsample': 0.6598743586529483, 'colsample_bytree': 0.9318698118234849, 'reg_alpha': 1.7051767531966122, 'reg_lambda': 0.03907816460857541}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   8%|███▍                                       | 32/400 [02:38<29:10,  4.76s/it]

[I 2026-05-25 16:36:55,304] Trial 24 finished with value: 0.9500737682797036 and parameters: {'n_estimators': 300, 'learning_rate': 0.04976074213976068, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 85, 'subsample': 0.6067333324490406, 'colsample_bytree': 0.9743707046175418, 'reg_alpha': 2.2555705544088658e-05, 'reg_lambda': 0.007577354641537478}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   8%|███▌                                       | 33/400 [02:42<27:42,  4.53s/it]

[I 2026-05-25 16:36:59,295] Trial 22 finished with value: 0.9500878797646664 and parameters: {'n_estimators': 290, 'learning_rate': 0.029408853046041957, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 88, 'subsample': 0.9978646048428252, 'colsample_bytree': 0.9651003122999713, 'reg_alpha': 0.6325198933818477, 'reg_lambda': 0.002279414662212216}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   8%|███▋                                       | 34/400 [02:44<22:36,  3.71s/it]

[I 2026-05-25 16:37:01,066] Trial 23 finished with value: 0.9500853013709449 and parameters: {'n_estimators': 299, 'learning_rate': 0.029750308795255778, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 108, 'subsample': 0.6400910331846466, 'colsample_bytree': 0.9942265031854411, 'reg_alpha': 0.5360901177893098, 'reg_lambda': 0.0037730901675972306}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   9%|███▊                                       | 35/400 [02:50<25:51,  4.25s/it]

[I 2026-05-25 16:37:06,593] Trial 40 finished with value: 0.9492410656578297 and parameters: {'n_estimators': 150, 'learning_rate': 0.03395260283417733, 'max_depth': 1, 'num_leaves': 9, 'min_child_samples': 29, 'subsample': 0.6669552980885163, 'colsample_bytree': 0.9344897336415052, 'reg_alpha': 0.0003095770925308152, 'reg_lambda': 0.0007015531888400742}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   9%|███▊                                       | 36/400 [02:50<18:34,  3.06s/it]

[I 2026-05-25 16:37:06,885] Trial 33 finished with value: 0.9499815617925649 and parameters: {'n_estimators': 267, 'learning_rate': 0.03174795278739438, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 206, 'subsample': 0.7748464152873955, 'colsample_bytree': 0.9900012789765342, 'reg_alpha': 1.2867775697606307, 'reg_lambda': 1.1537504529100997}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:   9%|███▉                                       | 37/400 [03:10<48:40,  8.05s/it]

[I 2026-05-25 16:37:26,555] Trial 42 finished with value: 0.9496902416261793 and parameters: {'n_estimators': 78, 'learning_rate': 0.02312066373783362, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 188, 'subsample': 0.6617032730945273, 'colsample_bytree': 0.8995874914057284, 'reg_alpha': 0.0001972568959818462, 'reg_lambda': 0.0017469532731721176}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  10%|████                                       | 38/400 [03:16<44:30,  7.38s/it]

[I 2026-05-25 16:37:32,381] Trial 35 finished with value: 0.9500868306015067 and parameters: {'n_estimators': 263, 'learning_rate': 0.03239896046791312, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 203, 'subsample': 0.7748926134884218, 'colsample_bytree': 0.915224234979923, 'reg_alpha': 1.454535086790475, 'reg_lambda': 1.1694381510930842}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  10%|████▏                                      | 39/400 [03:17<33:43,  5.61s/it]

[I 2026-05-25 16:37:33,851] Trial 34 finished with value: 0.9500829756579179 and parameters: {'n_estimators': 266, 'learning_rate': 0.03130633183967602, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 208, 'subsample': 0.8971845057616753, 'colsample_bytree': 0.9185254775587762, 'reg_alpha': 1.5844038751744811, 'reg_lambda': 0.02614364623164787}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  10%|████▎                                      | 40/400 [03:22<31:38,  5.27s/it]

[I 2026-05-25 16:37:38,359] Trial 36 finished with value: 0.9500892187574511 and parameters: {'n_estimators': 269, 'learning_rate': 0.0323088652698562, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 210, 'subsample': 0.8984024379675382, 'colsample_bytree': 0.9094765635986267, 'reg_alpha': 1.4454130694009553, 'reg_lambda': 1.0580571482817622}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  10%|████▍                                      | 41/400 [03:31<38:45,  6.48s/it]

[I 2026-05-25 16:37:47,648] Trial 38 finished with value: 0.9500670436077797 and parameters: {'n_estimators': 270, 'learning_rate': 0.02731582797185692, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 201, 'subsample': 0.8789101370475908, 'colsample_bytree': 0.9230195170354175, 'reg_alpha': 1.120274810796224, 'reg_lambda': 1.0803535839567588}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  10%|████▌                                      | 42/400 [03:33<30:36,  5.13s/it]

[I 2026-05-25 16:37:49,626] Trial 37 finished with value: 0.9500809470225041 and parameters: {'n_estimators': 281, 'learning_rate': 0.0298464153705979, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 202, 'subsample': 0.8849725464753855, 'colsample_bytree': 0.9309142192531773, 'reg_alpha': 1.6677679002443044, 'reg_lambda': 2.068111886407623}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  11%|████▌                                      | 43/400 [03:41<35:42,  6.00s/it]

[I 2026-05-25 16:37:57,641] Trial 41 finished with value: 0.9500662099993991 and parameters: {'n_estimators': 230, 'learning_rate': 0.033558227303221014, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 185, 'subsample': 0.6596558750581807, 'colsample_bytree': 0.919857781960678, 'reg_alpha': 0.000496747684838563, 'reg_lambda': 0.03184396712710497}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  11%|████▌                                    | 44/400 [04:04<1:06:21, 11.18s/it]

[I 2026-05-25 16:38:20,939] Trial 44 finished with value: 0.9500430150662312 and parameters: {'n_estimators': 265, 'learning_rate': 0.021978151052053963, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 60, 'subsample': 0.659133758004262, 'colsample_bytree': 0.8945333056105564, 'reg_alpha': 0.00021082068693971512, 'reg_lambda': 0.0005937845344525815}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  11%|████▊                                      | 45/400 [04:06<49:02,  8.29s/it]

[I 2026-05-25 16:38:22,484] Trial 45 finished with value: 0.9500088618593552 and parameters: {'n_estimators': 261, 'learning_rate': 0.018876034555918464, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 57, 'subsample': 0.6640286995508943, 'colsample_bytree': 0.8991391206742889, 'reg_alpha': 0.00021171455797754836, 'reg_lambda': 0.0006111894036328162}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  12%|████▉                                      | 46/400 [04:09<39:24,  6.68s/it]

[I 2026-05-25 16:38:25,381] Trial 47 finished with value: 0.9500270593192723 and parameters: {'n_estimators': 251, 'learning_rate': 0.021999990408370102, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 56, 'subsample': 0.6496062652331145, 'colsample_bytree': 0.8904719350608297, 'reg_alpha': 0.030145131148743745, 'reg_lambda': 0.000836210261438328}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  12%|█████                                      | 47/400 [04:09<29:08,  4.95s/it]

[I 2026-05-25 16:38:26,319] Trial 43 finished with value: 0.950062658450426 and parameters: {'n_estimators': 268, 'learning_rate': 0.024284874719620535, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 236, 'subsample': 0.6647651317206109, 'colsample_bytree': 0.9018893078311611, 'reg_alpha': 0.0001501168199653162, 'reg_lambda': 0.0014771354357325265}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  12%|█████▏                                     | 48/400 [04:10<21:53,  3.73s/it]

[I 2026-05-25 16:38:27,190] Trial 46 finished with value: 0.9500277997123 and parameters: {'n_estimators': 260, 'learning_rate': 0.021364140178235676, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 62, 'subsample': 0.7640912164622468, 'colsample_bytree': 0.8923659228871066, 'reg_alpha': 0.03087058759168362, 'reg_lambda': 0.0012102702582220673}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  12%|█████▎                                     | 49/400 [04:28<45:57,  7.86s/it]

[I 2026-05-25 16:38:44,677] Trial 48 finished with value: 0.9499941540234602 and parameters: {'n_estimators': 254, 'learning_rate': 0.01901800384931067, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 60, 'subsample': 0.7527639472496407, 'colsample_bytree': 0.8886520095076367, 'reg_alpha': 0.04440826181529222, 'reg_lambda': 0.05447543390968873}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  12%|█████▍                                     | 50/400 [04:29<34:01,  5.83s/it]

[I 2026-05-25 16:38:45,786] Trial 49 finished with value: 0.9499653191808244 and parameters: {'n_estimators': 250, 'learning_rate': 0.017653244462207847, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 65, 'subsample': 0.7676451073964802, 'colsample_bytree': 0.8879853817779677, 'reg_alpha': 3.7008614935517983, 'reg_lambda': 0.3493649256743064}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  13%|█████▍                                     | 51/400 [04:33<30:43,  5.28s/it]

[I 2026-05-25 16:38:49,804] Trial 50 finished with value: 0.9499538861367537 and parameters: {'n_estimators': 249, 'learning_rate': 0.01701453315653635, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 62, 'subsample': 0.7856986511084071, 'colsample_bytree': 0.8774759091436087, 'reg_alpha': 0.03730702360706319, 'reg_lambda': 0.21443258568669196}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  13%|█████▌                                     | 52/400 [04:37<29:06,  5.02s/it]

[I 2026-05-25 16:38:54,193] Trial 51 finished with value: 0.9499322454759274 and parameters: {'n_estimators': 246, 'learning_rate': 0.016125825114228737, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 243, 'subsample': 0.7530134619695247, 'colsample_bytree': 0.8776939330171544, 'reg_alpha': 4.855705329264826, 'reg_lambda': 0.343851725530985}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  13%|█████▋                                     | 53/400 [04:40<25:43,  4.45s/it]

[I 2026-05-25 16:38:57,308] Trial 52 finished with value: 0.9499349926473618 and parameters: {'n_estimators': 243, 'learning_rate': 0.01824854802059663, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 57, 'subsample': 0.7565903781712995, 'colsample_bytree': 0.8754690814247371, 'reg_alpha': 0.3345487195366432, 'reg_lambda': 0.29196968341961893}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  14%|█████▊                                     | 54/400 [04:46<28:07,  4.88s/it]

[I 2026-05-25 16:39:03,202] Trial 53 finished with value: 0.9499699911909663 and parameters: {'n_estimators': 250, 'learning_rate': 0.019774441416078477, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 52, 'subsample': 0.7558624240784164, 'colsample_bytree': 0.8773058203992427, 'reg_alpha': 0.3312136330290003, 'reg_lambda': 0.27665988063885577}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  14%|█████▉                                     | 55/400 [04:55<35:16,  6.14s/it]

[I 2026-05-25 16:39:12,275] Trial 54 finished with value: 0.949943143353208 and parameters: {'n_estimators': 254, 'learning_rate': 0.018118143259518518, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 66, 'subsample': 0.7596662032283409, 'colsample_bytree': 0.8744528037584501, 'reg_alpha': 4.457231287089248, 'reg_lambda': 0.23239162295752017}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  14%|██████                                     | 56/400 [05:09<48:02,  8.38s/it]

[I 2026-05-25 16:39:25,888] Trial 56 finished with value: 0.9500659211398415 and parameters: {'n_estimators': 251, 'learning_rate': 0.03854994376138395, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 42, 'subsample': 0.760024278605246, 'colsample_bytree': 0.8713016421644253, 'reg_alpha': 0.034956472744996005, 'reg_lambda': 0.2626760464625667}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  14%|██████▏                                    | 57/400 [05:11<37:28,  6.56s/it]

[I 2026-05-25 16:39:28,182] Trial 55 finished with value: 0.9500863507871437 and parameters: {'n_estimators': 252, 'learning_rate': 0.03890366475337924, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 119, 'subsample': 0.9372912910338442, 'colsample_bytree': 0.8696845940462286, 'reg_alpha': 4.062279151464642, 'reg_lambda': 0.25040914528392666}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  14%|██████▏                                    | 58/400 [05:14<30:45,  5.40s/it]

[I 2026-05-25 16:39:30,877] Trial 57 finished with value: 0.9500606481355252 and parameters: {'n_estimators': 249, 'learning_rate': 0.03931068774519378, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 115, 'subsample': 0.7465945231789343, 'colsample_bytree': 0.9546772887861411, 'reg_alpha': 4.518656664814638, 'reg_lambda': 0.28116988927931985}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  15%|██████▎                                    | 59/400 [05:15<22:32,  3.97s/it]

[I 2026-05-25 16:39:31,512] Trial 59 finished with value: 0.9500499742828211 and parameters: {'n_estimators': 248, 'learning_rate': 0.03793467678930298, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 42, 'subsample': 0.9664279421850137, 'colsample_bytree': 0.952207066904558, 'reg_alpha': 0.2686903666121813, 'reg_lambda': 0.28712295312754926}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  15%|██████▍                                    | 60/400 [05:15<16:24,  2.89s/it]

[I 2026-05-25 16:39:31,906] Trial 58 finished with value: 0.9500546566790943 and parameters: {'n_estimators': 251, 'learning_rate': 0.03714773524843783, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 118, 'subsample': 0.748033767137503, 'colsample_bytree': 0.9529229255498406, 'reg_alpha': 3.8889732266876043, 'reg_lambda': 0.2592411696274214}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  15%|██████▌                                    | 61/400 [05:27<30:58,  5.48s/it]

[I 2026-05-25 16:39:43,411] Trial 61 finished with value: 0.9500414790130499 and parameters: {'n_estimators': 219, 'learning_rate': 0.03865305387380316, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 117, 'subsample': 0.9390840743096023, 'colsample_bytree': 0.9513656276595531, 'reg_alpha': 0.39915286645391634, 'reg_lambda': 1.008667251437119e-05}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  16%|██████▋                                    | 62/400 [05:28<23:46,  4.22s/it]

[I 2026-05-25 16:39:44,676] Trial 60 finished with value: 0.9500364395169442 and parameters: {'n_estimators': 221, 'learning_rate': 0.03776313546578034, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 116, 'subsample': 0.9465068202123621, 'colsample_bytree': 0.9494916704741616, 'reg_alpha': 0.2817237053911952, 'reg_lambda': 0.24142824324069442}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  16%|██████▊                                    | 63/400 [05:48<51:06,  9.10s/it]

[I 2026-05-25 16:40:05,178] Trial 62 finished with value: 0.9500636393111506 and parameters: {'n_estimators': 292, 'learning_rate': 0.03850583267309408, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 114, 'subsample': 0.8063508362936957, 'colsample_bytree': 0.9644635699363225, 'reg_alpha': 0.28972281449763654, 'reg_lambda': 0.10580692829555957}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  16%|██████▉                                    | 64/400 [05:52<41:05,  7.34s/it]

[I 2026-05-25 16:40:08,390] Trial 63 finished with value: 0.9500645793173877 and parameters: {'n_estimators': 289, 'learning_rate': 0.03815819681717519, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 226, 'subsample': 0.9376648617355667, 'colsample_bytree': 0.9537298806773314, 'reg_alpha': 0.29327923380063436, 'reg_lambda': 0.15800475579909234}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  16%|██████▉                                    | 65/400 [05:57<38:30,  6.90s/it]

[I 2026-05-25 16:40:14,272] Trial 64 finished with value: 0.9500746645715994 and parameters: {'n_estimators': 293, 'learning_rate': 0.03765976105928069, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 227, 'subsample': 0.9214427945296827, 'colsample_bytree': 0.954289485467007, 'reg_alpha': 10.53026519434795, 'reg_lambda': 0.10600646081789175}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  16%|███████                                    | 66/400 [06:03<35:49,  6.44s/it]

[I 2026-05-25 16:40:19,633] Trial 65 finished with value: 0.950025106508034 and parameters: {'n_estimators': 293, 'learning_rate': 0.03875733304148152, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 224, 'subsample': 0.9480586578487626, 'colsample_bytree': 0.965733932135717, 'reg_alpha': 89.14196804829598, 'reg_lambda': 0.08122001161329244}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  17%|███████▏                                   | 67/400 [06:08<33:37,  6.06s/it]

[I 2026-05-25 16:40:24,797] Trial 71 finished with value: 0.9498505251108927 and parameters: {'n_estimators': 229, 'learning_rate': 0.026583988017132815, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 154, 'subsample': 0.9338216878276488, 'colsample_bytree': 0.8511054595485128, 'reg_alpha': 92.85911505285404, 'reg_lambda': 0.10068082200834873}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  17%|███████▎                                   | 68/400 [06:11<28:30,  5.15s/it]

[I 2026-05-25 16:40:27,847] Trial 68 finished with value: 0.9500422762054704 and parameters: {'n_estimators': 222, 'learning_rate': 0.03803714269422877, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 118, 'subsample': 0.9445506651517467, 'colsample_bytree': 0.9532188574032257, 'reg_alpha': 9.161461088750974, 'reg_lambda': 0.11377623941205318}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  17%|███████▍                                   | 69/400 [06:12<20:49,  3.78s/it]

[I 2026-05-25 16:40:28,389] Trial 66 finished with value: 0.9500771492088305 and parameters: {'n_estimators': 292, 'learning_rate': 0.03801162044104385, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 274, 'subsample': 0.9448096697257671, 'colsample_bytree': 0.9539401806249832, 'reg_alpha': 10.582066874955721, 'reg_lambda': 0.09144984256142467}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  18%|███████▌                                   | 70/400 [06:12<15:08,  2.75s/it]

[I 2026-05-25 16:40:28,782] Trial 69 finished with value: 0.95000088929364 and parameters: {'n_estimators': 224, 'learning_rate': 0.03724369189608477, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 160, 'subsample': 0.9641628217794768, 'colsample_bytree': 0.8374479912238925, 'reg_alpha': 85.50191730335814, 'reg_lambda': 0.08019174958710282}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  18%|███████▋                                   | 71/400 [06:15<15:15,  2.78s/it]

[I 2026-05-25 16:40:31,626] Trial 70 finished with value: 0.9494823910163352 and parameters: {'n_estimators': 224, 'learning_rate': 0.013422391405645351, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 266, 'subsample': 0.9293468438811852, 'colsample_bytree': 0.8469891851612688, 'reg_alpha': 89.57716132990753, 'reg_lambda': 0.09896305017002008}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  18%|███████▋                                   | 72/400 [06:23<23:23,  4.28s/it]

[I 2026-05-25 16:40:39,399] Trial 67 finished with value: 0.9500288109939469 and parameters: {'n_estimators': 294, 'learning_rate': 0.03863165901795873, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 269, 'subsample': 0.9383177119688838, 'colsample_bytree': 0.9532158814542151, 'reg_alpha': 92.03391943205193, 'reg_lambda': 0.09481164092172584}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  18%|███████▍                                 | 73/400 [06:53<1:06:08, 12.14s/it]

[I 2026-05-25 16:41:09,875] Trial 72 finished with value: 0.9501063479518423 and parameters: {'n_estimators': 292, 'learning_rate': 0.043615712651304823, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 227, 'subsample': 0.9382452569566029, 'colsample_bytree': 0.8505247899011116, 'reg_alpha': 11.085340957123801, 'reg_lambda': 0.014870743854408425}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  18%|███████▉                                   | 74/400 [06:55<49:33,  9.12s/it]

[I 2026-05-25 16:41:11,935] Trial 73 finished with value: 0.9501089962755435 and parameters: {'n_estimators': 300, 'learning_rate': 0.04397304006174881, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 229, 'subsample': 0.6916796809526465, 'colsample_bytree': 0.9741981726019744, 'reg_alpha': 11.877680335662221, 'reg_lambda': 0.1023170672895885}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  19%|████████                                   | 75/400 [07:05<50:19,  9.29s/it]

[I 2026-05-25 16:41:21,631] Trial 74 finished with value: 0.9501068636934104 and parameters: {'n_estimators': 279, 'learning_rate': 0.04351895671556295, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 220, 'subsample': 0.6883734587208901, 'colsample_bytree': 0.8505341366605248, 'reg_alpha': 12.395199399582758, 'reg_lambda': 0.015040104135016606}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  19%|████████▏                                  | 76/400 [07:10<43:06,  7.98s/it]

[I 2026-05-25 16:41:26,577] Trial 75 finished with value: 0.9500231257555081 and parameters: {'n_estimators': 280, 'learning_rate': 0.025677404924516194, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 166, 'subsample': 0.703256779566597, 'colsample_bytree': 0.8391724774832187, 'reg_alpha': 79.00146297697464, 'reg_lambda': 0.013302094224077961}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  19%|████████▎                                  | 77/400 [07:13<35:17,  6.56s/it]

[I 2026-05-25 16:41:29,800] Trial 76 finished with value: 0.9500935412415743 and parameters: {'n_estimators': 276, 'learning_rate': 0.04319073776638439, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 264, 'subsample': 0.6904890563443588, 'colsample_bytree': 0.844176464779601, 'reg_alpha': 0.1280763047687891, 'reg_lambda': 7.693995962175836}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  20%|████████▍                                  | 78/400 [07:16<29:48,  5.55s/it]

[I 2026-05-25 16:41:33,007] Trial 77 finished with value: 0.950093561952778 and parameters: {'n_estimators': 277, 'learning_rate': 0.04402407295962838, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 152, 'subsample': 0.684545044821717, 'colsample_bytree': 0.8467475662452897, 'reg_alpha': 0.00679780452457681, 'reg_lambda': 0.017521196774261283}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  20%|████████▍                                  | 79/400 [07:30<43:40,  8.16s/it]

[I 2026-05-25 16:41:47,257] Trial 81 finished with value: 0.95008381600288 and parameters: {'n_estimators': 281, 'learning_rate': 0.04448624407622275, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 80, 'subsample': 0.867325561636517, 'colsample_bytree': 0.9824506411135063, 'reg_alpha': 0.6109990401980566, 'reg_lambda': 0.012189161365886126}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  20%|████████▌                                  | 80/400 [07:32<32:19,  6.06s/it]

[I 2026-05-25 16:41:48,428] Trial 79 finished with value: 0.9500900597318381 and parameters: {'n_estimators': 278, 'learning_rate': 0.04384518682975932, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 262, 'subsample': 0.6941433508470884, 'colsample_bytree': 0.9745880491517445, 'reg_alpha': 0.6550473467133289, 'reg_lambda': 0.015615267842834901}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  20%|████████▋                                  | 81/400 [07:33<24:31,  4.61s/it]

[I 2026-05-25 16:41:49,649] Trial 78 finished with value: 0.9499065701277081 and parameters: {'n_estimators': 279, 'learning_rate': 0.012569964858286415, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 270, 'subsample': 0.698626681473414, 'colsample_bytree': 0.8501774980863795, 'reg_alpha': 0.6788915323150577, 'reg_lambda': 8.528537924549996}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  20%|████████▊                                  | 82/400 [07:34<19:18,  3.64s/it]

[I 2026-05-25 16:41:51,017] Trial 80 finished with value: 0.9500922624232757 and parameters: {'n_estimators': 278, 'learning_rate': 0.04372194311178939, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 78, 'subsample': 0.6924134891940495, 'colsample_bytree': 0.9800628358745788, 'reg_alpha': 2.3565149293722043, 'reg_lambda': 15.146805628988272}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  21%|████████▉                                  | 83/400 [07:36<16:29,  3.12s/it]

[I 2026-05-25 16:41:52,957] Trial 82 finished with value: 0.9500917003945849 and parameters: {'n_estimators': 278, 'learning_rate': 0.04510815308670691, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 80, 'subsample': 0.6939975442020926, 'colsample_bytree': 0.9184973723957813, 'reg_alpha': 2.4278872967825036, 'reg_lambda': 0.014633323421071766}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 4. Best value: 0.950111:  21%|█████████                                  | 84/400 [07:41<19:22,  3.68s/it]

[I 2026-05-25 16:41:57,921] Trial 83 finished with value: 0.9500883029004807 and parameters: {'n_estimators': 278, 'learning_rate': 0.04437653573917673, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 77, 'subsample': 0.8673998009220593, 'colsample_bytree': 0.9184502042775302, 'reg_alpha': 0.12470785409172676, 'reg_lambda': 0.0027093964445401436}. Best is trial 4 with value: 0.9501107737551198.

Best trial: 85. Best value: 0.950115:  21%|████████▌                               | 85/400 [08:13<1:03:51, 12.16s/it]

[I 2026-05-25 16:42:29,891] Trial 85 finished with value: 0.950114768273786 and parameters: {'n_estimators': 279, 'learning_rate': 0.04432514851865837, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 251, 'subsample': 0.6962146288316533, 'colsample_bytree': 0.8599193217867491, 'reg_alpha': 19.891009462187053, 'reg_lambda': 0.016802009563230427}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  22%|█████████                                 | 86/400 [08:16<49:12,  9.40s/it]

[I 2026-05-25 16:42:32,837] Trial 84 finished with value: 0.9500977544489515 and parameters: {'n_estimators': 278, 'learning_rate': 0.04403914732856279, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 85, 'subsample': 0.7069657468551824, 'colsample_bytree': 0.9812688241320273, 'reg_alpha': 38.190167325609394, 'reg_lambda': 0.015654144387256864}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  22%|█████████▏                                | 87/400 [08:22<43:31,  8.34s/it]

[I 2026-05-25 16:42:38,718] Trial 86 finished with value: 0.9501051056068441 and parameters: {'n_estimators': 276, 'learning_rate': 0.044972375154073485, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 251, 'subsample': 0.7046042758207649, 'colsample_bytree': 0.8158297682341676, 'reg_alpha': 35.34825498173404, 'reg_lambda': 0.014973482647328753}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  22%|█████████▏                                | 88/400 [08:29<41:21,  7.95s/it]

[I 2026-05-25 16:42:45,763] Trial 88 finished with value: 0.9501038039712535 and parameters: {'n_estimators': 275, 'learning_rate': 0.043139660016666845, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 253, 'subsample': 0.6847992364841077, 'colsample_bytree': 0.8104434187087625, 'reg_alpha': 45.950384215758206, 'reg_lambda': 26.56369837312473}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  22%|█████████▎                                | 89/400 [08:31<31:34,  6.09s/it]

[I 2026-05-25 16:42:47,522] Trial 87 finished with value: 0.9501023001651318 and parameters: {'n_estimators': 276, 'learning_rate': 0.04484375412072314, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 258, 'subsample': 0.6877289017940968, 'colsample_bytree': 0.8608498856093187, 'reg_alpha': 38.87996478934968, 'reg_lambda': 0.7348158461293134}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  22%|█████████▍                                | 90/400 [08:39<34:11,  6.62s/it]

[I 2026-05-25 16:42:55,343] Trial 89 finished with value: 0.9501043794817476 and parameters: {'n_estimators': 278, 'learning_rate': 0.04445777386604569, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 294, 'subsample': 0.6846445985041638, 'colsample_bytree': 0.8565377866206649, 'reg_alpha': 36.27864890236477, 'reg_lambda': 16.426033360449637}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  23%|█████████▌                                | 91/400 [08:52<44:50,  8.71s/it]

[I 2026-05-25 16:43:08,933] Trial 90 finished with value: 0.9501052331715082 and parameters: {'n_estimators': 276, 'learning_rate': 0.04303315527192383, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 287, 'subsample': 0.6910170946380856, 'colsample_bytree': 0.8219331708054406, 'reg_alpha': 44.66357825470145, 'reg_lambda': 4.757532889210521}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  23%|█████████▋                                | 92/400 [08:54<34:26,  6.71s/it]

[I 2026-05-25 16:43:10,980] Trial 92 finished with value: 0.9501001191180756 and parameters: {'n_estimators': 274, 'learning_rate': 0.042524307822301786, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 298, 'subsample': 0.6802012187199884, 'colsample_bytree': 0.8216431259922412, 'reg_alpha': 40.74814969184581, 'reg_lambda': 20.4605599063232}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  23%|█████████▊                                | 93/400 [08:55<24:35,  4.81s/it]

[I 2026-05-25 16:43:11,356] Trial 91 finished with value: 0.9500906995816057 and parameters: {'n_estimators': 275, 'learning_rate': 0.04378878450760127, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 254, 'subsample': 0.6823945103813227, 'colsample_bytree': 0.8609031972895647, 'reg_alpha': 0.005095750700078239, 'reg_lambda': 13.077987020929395}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  24%|█████████▊                                | 94/400 [08:57<21:16,  4.17s/it]

[I 2026-05-25 16:43:14,046] Trial 94 finished with value: 0.9501119876538121 and parameters: {'n_estimators': 275, 'learning_rate': 0.04315329448383368, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 290, 'subsample': 0.6874930924764814, 'colsample_bytree': 0.7880125822179328, 'reg_alpha': 20.11184336377004, 'reg_lambda': 0.01959756031884317}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  24%|█████████▉                                | 95/400 [08:59<16:58,  3.34s/it]

[I 2026-05-25 16:43:15,447] Trial 95 finished with value: 0.9501018363681805 and parameters: {'n_estimators': 276, 'learning_rate': 0.04350886791117999, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 294, 'subsample': 0.6793931113320623, 'colsample_bytree': 0.7875473035325564, 'reg_alpha': 38.48165022823277, 'reg_lambda': 46.89326716620997}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  24%|██████████                                | 96/400 [09:01<15:17,  3.02s/it]

[I 2026-05-25 16:43:17,707] Trial 93 finished with value: 0.9501025126011639 and parameters: {'n_estimators': 273, 'learning_rate': 0.04335605744718303, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 299, 'subsample': 0.6802887085161216, 'colsample_bytree': 0.7930337197139657, 'reg_alpha': 38.37883654709987, 'reg_lambda': 22.917999710889315}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  24%|██████████▏                               | 97/400 [09:10<24:50,  4.92s/it]

[I 2026-05-25 16:43:27,081] Trial 99 pruned.

Best trial: 85. Best value: 0.950115:  24%|██████████▎                               | 98/400 [09:30<47:08,  9.37s/it]

[I 2026-05-25 16:43:46,802] Trial 96 finished with value: 0.9501007801186276 and parameters: {'n_estimators': 273, 'learning_rate': 0.041696666661127986, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 285, 'subsample': 0.6805839581945309, 'colsample_bytree': 0.7917497439554589, 'reg_alpha': 41.65887316677862, 'reg_lambda': 24.64307130987433}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  25%|██████████▍                               | 99/400 [09:41<50:03,  9.98s/it]

[I 2026-05-25 16:43:58,216] Trial 97 finished with value: 0.9501001656940012 and parameters: {'n_estimators': 274, 'learning_rate': 0.04270417688918124, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 289, 'subsample': 0.6789472515753626, 'colsample_bytree': 0.8121626744621663, 'reg_alpha': 37.236540560518776, 'reg_lambda': 70.89274473376756}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  25%|██████████▎                              | 100/400 [09:45<40:50,  8.17s/it]

[I 2026-05-25 16:44:02,170] Trial 98 finished with value: 0.9500912291946921 and parameters: {'n_estimators': 286, 'learning_rate': 0.03407259168965192, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 287, 'subsample': 0.6798742082479586, 'colsample_bytree': 0.7958969650254724, 'reg_alpha': 39.192913393952246, 'reg_lambda': 0.04154118222856465}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  25%|██████████▎                              | 101/400 [09:55<42:39,  8.56s/it]

[I 2026-05-25 16:44:11,637] Trial 100 finished with value: 0.9500902679003136 and parameters: {'n_estimators': 300, 'learning_rate': 0.03357090615789015, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 287, 'subsample': 0.7093344628649316, 'colsample_bytree': 0.7844949394886419, 'reg_alpha': 48.28620747079328, 'reg_lambda': 34.84596017441798}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  26%|██████████▍                              | 102/400 [10:09<50:56, 10.26s/it]

[I 2026-05-25 16:44:25,848] Trial 101 finished with value: 0.9501037954945716 and parameters: {'n_estimators': 299, 'learning_rate': 0.03523390173732927, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 295, 'subsample': 0.6774622247995998, 'colsample_bytree': 0.8191927760899909, 'reg_alpha': 20.870456463774453, 'reg_lambda': 39.94514933590335}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  26%|██████████▌                              | 103/400 [10:19<50:50, 10.27s/it]

[I 2026-05-25 16:44:36,154] Trial 103 finished with value: 0.9496178568032384 and parameters: {'n_estimators': 287, 'learning_rate': 0.009306060226536704, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 282, 'subsample': 0.7168853923696811, 'colsample_bytree': 0.7869331230362278, 'reg_alpha': 18.866297061050066, 'reg_lambda': 48.271888959568116}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  26%|██████████▋                              | 104/400 [10:20<37:00,  7.50s/it]

[I 2026-05-25 16:44:37,201] Trial 104 finished with value: 0.9501115588756714 and parameters: {'n_estimators': 299, 'learning_rate': 0.034569763671974514, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 282, 'subsample': 0.717138283363943, 'colsample_bytree': 0.7955807607145244, 'reg_alpha': 15.77978771056893, 'reg_lambda': 3.260823634805603}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  26%|██████████▊                              | 105/400 [10:21<27:28,  5.59s/it]

[I 2026-05-25 16:44:38,312] Trial 102 finished with value: 0.950091803702182 and parameters: {'n_estimators': 299, 'learning_rate': 0.03439899790582196, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 290, 'subsample': 0.6781035504851246, 'colsample_bytree': 0.7912183057341323, 'reg_alpha': 20.00926323672076, 'reg_lambda': 89.56169260999646}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  26%|██████████▊                              | 106/400 [10:23<21:17,  4.35s/it]

[I 2026-05-25 16:44:39,771] Trial 105 finished with value: 0.9501049972664608 and parameters: {'n_estimators': 300, 'learning_rate': 0.035295413084695616, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 284, 'subsample': 0.7215551511181976, 'colsample_bytree': 0.79062787027211, 'reg_alpha': 20.847420259121453, 'reg_lambda': 23.808529479162537}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  27%|██████████▉                              | 107/400 [10:25<18:18,  3.75s/it]

[I 2026-05-25 16:44:42,130] Trial 107 finished with value: 0.9501014078109382 and parameters: {'n_estimators': 286, 'learning_rate': 0.03502620401431898, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 284, 'subsample': 0.7174656667320936, 'colsample_bytree': 0.8098278142401223, 'reg_alpha': 20.775427449156847, 'reg_lambda': 72.9205509095736}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  27%|███████████                              | 108/400 [10:38<31:33,  6.49s/it]

[I 2026-05-25 16:44:54,980] Trial 106 finished with value: 0.9501009465785055 and parameters: {'n_estimators': 300, 'learning_rate': 0.03551603146221841, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 288, 'subsample': 0.7127543489314557, 'colsample_bytree': 0.8107690225643086, 'reg_alpha': 18.536788636176937, 'reg_lambda': 64.24663669613442}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  27%|███████████▏                             | 109/400 [10:45<31:56,  6.59s/it]

[I 2026-05-25 16:45:01,823] Trial 108 finished with value: 0.9501071727379081 and parameters: {'n_estimators': 286, 'learning_rate': 0.03507689469450213, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 284, 'subsample': 0.7133146164658578, 'colsample_bytree': 0.8169106237389525, 'reg_alpha': 19.279465736624, 'reg_lambda': 0.04703983512866675}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  28%|███████████▎                             | 110/400 [10:51<31:03,  6.42s/it]

[I 2026-05-25 16:45:07,861] Trial 109 finished with value: 0.9501005073294208 and parameters: {'n_estimators': 257, 'learning_rate': 0.03534812728333814, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 237, 'subsample': 0.7162521001343072, 'colsample_bytree': 0.8172082082475765, 'reg_alpha': 20.17908554399274, 'reg_lambda': 0.051803780333639304}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  28%|███████████▍                             | 111/400 [10:59<33:39,  6.99s/it]

[I 2026-05-25 16:45:16,159] Trial 110 finished with value: 0.95011283235089 and parameters: {'n_estimators': 286, 'learning_rate': 0.047441273732394845, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 281, 'subsample': 0.7127681645748547, 'colsample_bytree': 0.7673602830036268, 'reg_alpha': 20.362813925342216, 'reg_lambda': 0.045955549159498295}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  28%|███████████▌                             | 113/400 [11:11<28:21,  5.93s/it]

[I 2026-05-25 16:45:27,931] Trial 111 finished with value: 0.9501014732793666 and parameters: {'n_estimators': 300, 'learning_rate': 0.034826295915923705, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 239, 'subsample': 0.7181089264768152, 'colsample_bytree': 0.7679020702024099, 'reg_alpha': 19.076617388015478, 'reg_lambda': 3.4288448135973093}. Best is trial 85 with value: 0.950114768273786.
[I 2026-05-25 16:45:28,038] Trial 112 finished with value: 0.9501116897455907 and parameters: {'n_estimators': 262, 'learning_rate': 0.046866344180596056, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 280, 'subsample': 0.7318848209088713, 'colsample_bytree': 0.7496494056296463, 'reg_alpha': 19.506931030475087, 'reg_lambda': 0.023336566703554863}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  28%|███████████▋                             | 114/400 [11:28<43:14,  9.07s/it]

[I 2026-05-25 16:45:44,451] Trial 113 finished with value: 0.9501106667395005 and parameters: {'n_estimators': 286, 'learning_rate': 0.047440022251237925, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 233, 'subsample': 0.7191182349011355, 'colsample_bytree': 0.763316797932183, 'reg_alpha': 18.733395088320993, 'reg_lambda': 3.5186906544977377}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  29%|███████████▊                             | 115/400 [11:33<37:21,  7.86s/it]

[I 2026-05-25 16:45:49,499] Trial 115 finished with value: 0.9501104979004417 and parameters: {'n_estimators': 261, 'learning_rate': 0.048527971787968915, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 239, 'subsample': 0.7301976817919396, 'colsample_bytree': 0.7592625313417807, 'reg_alpha': 16.67041435469776, 'reg_lambda': 3.8799635621739683}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  29%|███████████▉                             | 116/400 [11:33<26:35,  5.62s/it]

[I 2026-05-25 16:45:49,871] Trial 116 finished with value: 0.9501061300322446 and parameters: {'n_estimators': 259, 'learning_rate': 0.04799100152320655, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 237, 'subsample': 0.7372040435808017, 'colsample_bytree': 0.7635114045511131, 'reg_alpha': 7.773205203122972, 'reg_lambda': 3.4039617384699565}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  29%|███████████▉                             | 117/400 [11:36<22:20,  4.74s/it]

[I 2026-05-25 16:45:52,544] Trial 117 finished with value: 0.950110827198414 and parameters: {'n_estimators': 260, 'learning_rate': 0.04689353628409047, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 237, 'subsample': 0.737409049026934, 'colsample_bytree': 0.7563866764101747, 'reg_alpha': 7.861956493572343, 'reg_lambda': 2.257172569650092}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  30%|████████████                             | 118/400 [11:37<16:58,  3.61s/it]

[I 2026-05-25 16:45:53,538] Trial 118 finished with value: 0.9501114279448526 and parameters: {'n_estimators': 264, 'learning_rate': 0.047990779933472075, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 236, 'subsample': 0.7325866868256394, 'colsample_bytree': 0.7634917523611637, 'reg_alpha': 8.266762461095219, 'reg_lambda': 3.348440385098843}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  30%|████████████▏                            | 119/400 [11:42<19:27,  4.16s/it]

[I 2026-05-25 16:45:58,960] Trial 114 finished with value: 0.9501037640741707 and parameters: {'n_estimators': 285, 'learning_rate': 0.03584196840587686, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 277, 'subsample': 0.7212253726171375, 'colsample_bytree': 0.753001675540001, 'reg_alpha': 20.003610622641236, 'reg_lambda': 2.4444971115107044}. Best is trial 85 with value: 0.950114768273786.

Best trial: 85. Best value: 0.950115:  30%|████████████▎                            | 120/400 [11:44<16:15,  3.48s/it]

[I 2026-05-25 16:46:00,881] Trial 119 finished with value: 0.9501032227176264 and parameters: {'n_estimators': 259, 'learning_rate': 0.047900218631950854, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 235, 'subsample': 0.7370509247463423, 'colsample_bytree': 0.7574591601558559, 'reg_alpha': 7.783858415051078, 'reg_lambda': 4.644798337661992}. Best is trial 85 with value: 0.950114768273786.

Best trial: 120. Best value: 0.950117:  30%|████████████                            | 121/400 [12:02<36:03,  7.76s/it]

[I 2026-05-25 16:46:18,587] Trial 120 finished with value: 0.9501174064007986 and parameters: {'n_estimators': 258, 'learning_rate': 0.04744226165954971, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 232, 'subsample': 0.740091805824237, 'colsample_bytree': 0.7575113219043207, 'reg_alpha': 7.698157614744785, 'reg_lambda': 2.3563508784372478}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  30%|████████████▏                           | 122/400 [12:09<34:36,  7.47s/it]

[I 2026-05-25 16:46:25,378] Trial 121 finished with value: 0.950110147870947 and parameters: {'n_estimators': 265, 'learning_rate': 0.047281843004431466, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 278, 'subsample': 0.728870491768002, 'colsample_bytree': 0.7617442412531897, 'reg_alpha': 8.21799686835799, 'reg_lambda': 0.022681280662292254}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  31%|████████████▎                           | 123/400 [12:15<32:24,  7.02s/it]

[I 2026-05-25 16:46:31,367] Trial 122 finished with value: 0.9501021760199875 and parameters: {'n_estimators': 285, 'learning_rate': 0.047330493580288666, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 275, 'subsample': 0.7311290155836229, 'colsample_bytree': 0.7719069869930025, 'reg_alpha': 6.620885790237856, 'reg_lambda': 2.2041602695706985}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  31%|████████████▍                           | 124/400 [12:26<38:33,  8.38s/it]

[I 2026-05-25 16:46:42,939] Trial 123 finished with value: 0.950110478448728 and parameters: {'n_estimators': 262, 'learning_rate': 0.04781179150710513, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 278, 'subsample': 0.7314811209631098, 'colsample_bytree': 0.7355309825198159, 'reg_alpha': 7.190745677227449, 'reg_lambda': 0.021817000494881698}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  31%|████████████▌                           | 125/400 [12:30<32:02,  6.99s/it]

[I 2026-05-25 16:46:46,687] Trial 134 finished with value: 0.9494304813497079 and parameters: {'n_estimators': 33, 'learning_rate': 0.04998404091805119, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 230, 'subsample': 0.7311414755942284, 'colsample_bytree': 0.7416580163320116, 'reg_alpha': 13.343594729163073, 'reg_lambda': 1.6328471744399522}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  32%|████████████▌                           | 126/400 [12:31<23:29,  5.14s/it]

[I 2026-05-25 16:46:47,517] Trial 124 finished with value: 0.9501063036088839 and parameters: {'n_estimators': 266, 'learning_rate': 0.04752379466842427, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 277, 'subsample': 0.7338364202521952, 'colsample_bytree': 0.7446206493181414, 'reg_alpha': 6.30622469441915, 'reg_lambda': 0.023584830672301847}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  32%|████████████▋                           | 127/400 [12:32<17:52,  3.93s/it]

[I 2026-05-25 16:46:48,604] Trial 125 finished with value: 0.9501164642701285 and parameters: {'n_estimators': 208, 'learning_rate': 0.04764902320729381, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 274, 'subsample': 0.6498848546642575, 'colsample_bytree': 0.7471310548723696, 'reg_alpha': 7.66794334647766, 'reg_lambda': 0.022739943591754384}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  32%|████████████▊                           | 128/400 [12:45<30:39,  6.76s/it]

[I 2026-05-25 16:47:01,999] Trial 126 finished with value: 0.9501159241775733 and parameters: {'n_estimators': 267, 'learning_rate': 0.04695664559852642, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 232, 'subsample': 0.7334062474984677, 'colsample_bytree': 0.7444236469387042, 'reg_alpha': 7.576746911898058, 'reg_lambda': 0.022854466518655733}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  32%|████████████▉                           | 129/400 [12:51<29:11,  6.46s/it]

[I 2026-05-25 16:47:07,753] Trial 128 finished with value: 0.9501118057610908 and parameters: {'n_estimators': 265, 'learning_rate': 0.047406588145544534, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 276, 'subsample': 0.7285390351680762, 'colsample_bytree': 0.7466884437599519, 'reg_alpha': 13.632919071122815, 'reg_lambda': 0.023495950144136295}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  32%|█████████████                           | 130/400 [12:52<21:43,  4.83s/it]

[I 2026-05-25 16:47:08,774] Trial 127 finished with value: 0.9501157027591717 and parameters: {'n_estimators': 263, 'learning_rate': 0.047192213188154974, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 219, 'subsample': 0.7328314379323086, 'colsample_bytree': 0.7482620492947586, 'reg_alpha': 12.981256882928603, 'reg_lambda': 0.025073327631873504}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  33%|█████████████                           | 131/400 [12:55<19:03,  4.25s/it]

[I 2026-05-25 16:47:11,657] Trial 129 finished with value: 0.9501171448881776 and parameters: {'n_estimators': 266, 'learning_rate': 0.048188724447814114, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 275, 'subsample': 0.7302426391277331, 'colsample_bytree': 0.7475873608650251, 'reg_alpha': 6.6078131602838415, 'reg_lambda': 1.6620213818799148}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  33%|█████████████▏                          | 132/400 [12:56<14:38,  3.28s/it]

[I 2026-05-25 16:47:12,664] Trial 130 finished with value: 0.950087069563682 and parameters: {'n_estimators': 266, 'learning_rate': 0.047788522454001656, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 232, 'subsample': 0.7352790314991158, 'colsample_bytree': 0.7216495334231721, 'reg_alpha': 59.95348024109672, 'reg_lambda': 1.841592999510004}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  33%|█████████████▎                          | 133/400 [13:06<23:31,  5.29s/it]

[I 2026-05-25 16:47:22,637] Trial 131 finished with value: 0.9501068233810501 and parameters: {'n_estimators': 267, 'learning_rate': 0.0404416295288018, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 245, 'subsample': 0.7298584447655315, 'colsample_bytree': 0.7242418561462809, 'reg_alpha': 14.565187903094367, 'reg_lambda': 1.481562852883025}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  34%|█████████████▍                          | 134/400 [13:18<32:23,  7.31s/it]

[I 2026-05-25 16:47:34,665] Trial 132 finished with value: 0.9501129678781084 and parameters: {'n_estimators': 264, 'learning_rate': 0.04988647455325488, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 246, 'subsample': 0.7355774136549533, 'colsample_bytree': 0.7421778697384684, 'reg_alpha': 13.793027701168183, 'reg_lambda': 1.7202753615232598}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  34%|█████████████▌                          | 135/400 [13:20<24:53,  5.63s/it]

[I 2026-05-25 16:47:36,402] Trial 138 finished with value: 0.9500717838766057 and parameters: {'n_estimators': 163, 'learning_rate': 0.040706826841530035, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 248, 'subsample': 0.7408179621541428, 'colsample_bytree': 0.7083059915810175, 'reg_alpha': 3.2553768571006065, 'reg_lambda': 0.4993414995133169}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  34%|█████████████▌                          | 136/400 [13:24<23:09,  5.26s/it]

[I 2026-05-25 16:47:40,795] Trial 133 finished with value: 0.9501079279232574 and parameters: {'n_estimators': 266, 'learning_rate': 0.04993936966769113, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 246, 'subsample': 0.7294640615071608, 'colsample_bytree': 0.7407081704948747, 'reg_alpha': 6.182189686344562, 'reg_lambda': 1.7202095897204637}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  34%|█████████████▋                          | 137/400 [13:42<39:48,  9.08s/it]

[I 2026-05-25 16:47:58,780] Trial 139 finished with value: 0.9500953724039624 and parameters: {'n_estimators': 209, 'learning_rate': 0.04120713618298955, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 245, 'subsample': 0.7435733626266016, 'colsample_bytree': 0.7124982607369894, 'reg_alpha': 5.208062212970167, 'reg_lambda': 6.6747086187183795}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  34%|█████████████▊                          | 138/400 [13:43<29:31,  6.76s/it]

[I 2026-05-25 16:48:00,124] Trial 135 finished with value: 0.9500982484578859 and parameters: {'n_estimators': 265, 'learning_rate': 0.049801333437555134, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 247, 'subsample': 0.7442705689608351, 'colsample_bytree': 0.7104993495376378, 'reg_alpha': 2.3302245224562537, 'reg_lambda': 1.6117046927120628}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  35%|██████████████                          | 140/400 [13:47<17:38,  4.07s/it]

[I 2026-05-25 16:48:03,497] Trial 136 finished with value: 0.9501133767944159 and parameters: {'n_estimators': 240, 'learning_rate': 0.04089967062110215, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 247, 'subsample': 0.7437256055602545, 'colsample_bytree': 0.7344029565373836, 'reg_alpha': 5.4795409679724125, 'reg_lambda': 0.021845314989643795}. Best is trial 120 with value: 0.9501174064007986.
[I 2026-05-25 16:48:03,666] Trial 137 finished with value: 0.9501075835797392 and parameters: {'n_estimators': 264, 'learning_rate': 0.040663848391082925, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 216, 'subsample': 0.7663304771050423, 'colsample_bytree': 0.7137883562763596, 'reg_alpha': 2.7532601427372967, 'reg_lambda': 0.6590352908027206}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  35%|██████████████                          | 141/400 [13:53<20:02,  4.64s/it]

[I 2026-05-25 16:48:09,649] Trial 141 finished with value: 0.9500882935634436 and parameters: {'n_estimators': 175, 'learning_rate': 0.04101956034368044, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 244, 'subsample': 0.7427954725651166, 'colsample_bytree': 0.7091751894917439, 'reg_alpha': 2.950039793695844, 'reg_lambda': 0.009796996034204936}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  36%|██████████████▏                         | 142/400 [13:59<21:24,  4.98s/it]

[I 2026-05-25 16:48:15,398] Trial 140 finished with value: 0.9501046465751906 and parameters: {'n_estimators': 209, 'learning_rate': 0.04069393468338869, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 247, 'subsample': 0.7442201695283797, 'colsample_bytree': 0.7060275509250153, 'reg_alpha': 2.8042186284991852, 'reg_lambda': 0.6178918405130235}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  36%|██████████████▎                         | 143/400 [14:10<29:02,  6.78s/it]

[I 2026-05-25 16:48:26,383] Trial 142 finished with value: 0.9501144198602998 and parameters: {'n_estimators': 238, 'learning_rate': 0.04087838379857554, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 245, 'subsample': 0.7431123743207462, 'colsample_bytree': 0.7104348761972946, 'reg_alpha': 5.464656048113388, 'reg_lambda': 0.5118075778270087}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  36%|██████████████▍                         | 144/400 [14:14<26:09,  6.13s/it]

[I 2026-05-25 16:48:30,995] Trial 143 finished with value: 0.9500998655194243 and parameters: {'n_estimators': 243, 'learning_rate': 0.04071623607655452, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 249, 'subsample': 0.7440462859091167, 'colsample_bytree': 0.7244290411695242, 'reg_alpha': 2.279883537817252, 'reg_lambda': 0.010017041734572433}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  36%|██████████████▌                         | 145/400 [14:19<24:01,  5.65s/it]

[I 2026-05-25 16:48:35,549] Trial 145 finished with value: 0.9500900980364374 and parameters: {'n_estimators': 188, 'learning_rate': 0.04066095427916972, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 213, 'subsample': 0.7443233743039762, 'colsample_bytree': 0.7160065569755242, 'reg_alpha': 2.4086072224846937, 'reg_lambda': 0.5643725367744801}. Best is trial 120 with value: 0.9501174064007986.
[I 2026-05-25 16:48:35,554] Trial 144 finished with value: 0.950107795358116 and parameters: {'n_estimators': 240, 'learning_rate': 0.040559335723691296, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 217, 'subsample': 0.7455123845463637, 'colsample_bytree': 0.7076110761983493, 'reg_alpha': 4.566358436975048, 'reg_lambda': 0.009671258314943504}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  37%|██████████████▋                         | 147/400 [14:22<16:30,  3.92s/it]

[I 2026-05-25 16:48:39,309] Trial 150 pruned.

Best trial: 120. Best value: 0.950117:  37%|██████████████▊                         | 148/400 [14:30<19:52,  4.73s/it]

[I 2026-05-25 16:48:46,528] Trial 146 finished with value: 0.9500974463735636 and parameters: {'n_estimators': 208, 'learning_rate': 0.04067743572756329, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 215, 'subsample': 0.7412113583197422, 'colsample_bytree': 0.778417704763407, 'reg_alpha': 2.6647810640349414, 'reg_lambda': 0.00936841298391976}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  37%|██████████████▉                         | 149/400 [14:37<22:55,  5.48s/it]

[I 2026-05-25 16:48:54,117] Trial 147 finished with value: 0.9501032493034834 and parameters: {'n_estimators': 238, 'learning_rate': 0.04064316653700007, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 259, 'subsample': 0.7464150244489741, 'colsample_bytree': 0.7781694201716277, 'reg_alpha': 2.7770845378621964, 'reg_lambda': 0.009462519141437609}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  38%|███████████████                         | 150/400 [14:39<18:53,  4.53s/it]

[I 2026-05-25 16:48:56,123] Trial 156 pruned.

Best trial: 120. Best value: 0.950117:  38%|███████████████                         | 151/400 [14:58<34:47,  8.39s/it]

[I 2026-05-25 16:49:14,404] Trial 149 finished with value: 0.9501063151402664 and parameters: {'n_estimators': 244, 'learning_rate': 0.040596035054116374, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 268, 'subsample': 0.7815904009153241, 'colsample_bytree': 0.7492161499710199, 'reg_alpha': 10.810794428552589, 'reg_lambda': 0.008107106782851361}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  38%|███████████████▏                        | 152/400 [14:58<25:40,  6.21s/it]

[I 2026-05-25 16:49:15,194] Trial 151 finished with value: 0.949470835776491 and parameters: {'n_estimators': 239, 'learning_rate': 0.006876737659870966, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 272, 'subsample': 0.7873395862884804, 'colsample_bytree': 0.7776189613691626, 'reg_alpha': 27.96239061734607, 'reg_lambda': 0.009872761684766541}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  38%|███████████████▎                        | 153/400 [15:01<21:38,  5.26s/it]

[I 2026-05-25 16:49:18,118] Trial 148 finished with value: 0.9497374924507478 and parameters: {'n_estimators': 241, 'learning_rate': 0.005472665776150372, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 260, 'subsample': 0.7502045333962357, 'colsample_bytree': 0.777967672593515, 'reg_alpha': 3.045045132741421, 'reg_lambda': 0.0081278445744476}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  38%|███████████████▍                        | 154/400 [15:06<20:30,  5.00s/it]

[I 2026-05-25 16:49:22,496] Trial 152 finished with value: 0.9494693302866922 and parameters: {'n_estimators': 243, 'learning_rate': 0.006605329723968815, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 262, 'subsample': 0.7483024673896066, 'colsample_bytree': 0.7502796144847179, 'reg_alpha': 27.658995002336095, 'reg_lambda': 0.0326378703223865}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  39%|███████████████▌                        | 156/400 [15:12<15:26,  3.80s/it]

[I 2026-05-25 16:49:28,698] Trial 153 finished with value: 0.9501172729402038 and parameters: {'n_estimators': 242, 'learning_rate': 0.046152549244189676, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 260, 'subsample': 0.6453815030875949, 'colsample_bytree': 0.7790246295748854, 'reg_alpha': 11.30851572807236, 'reg_lambda': 0.03327365772685394}. Best is trial 120 with value: 0.9501174064007986.
[I 2026-05-25 16:49:28,795] Trial 160 finished with value: 0.9497534541002256 and parameters: {'n_estimators': 234, 'learning_rate': 0.04982929095873912, 'max_depth': 1, 'num_leaves': 15, 'min_child_samples': 270, 'subsample': 0.7000329163589426, 'colsample_bytree': 0.696450528584699, 'reg_alpha': 10.792533239702635, 'reg_lambda': 0.032620186109192074}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  39%|███████████████▋                        | 157/400 [15:22<22:57,  5.67s/it]

[I 2026-05-25 16:49:38,882] Trial 154 finished with value: 0.9501130333202908 and parameters: {'n_estimators': 233, 'learning_rate': 0.04617285029273176, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 258, 'subsample': 0.7516867654821789, 'colsample_bytree': 0.7784481120035371, 'reg_alpha': 10.932388542075145, 'reg_lambda': 0.030679920196408663}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  40%|███████████████▊                        | 158/400 [15:31<27:13,  6.75s/it]

[I 2026-05-25 16:49:48,186] Trial 157 finished with value: 0.9501155449088913 and parameters: {'n_estimators': 235, 'learning_rate': 0.04649155177250281, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 262, 'subsample': 0.7015665343914242, 'colsample_bytree': 0.7482220292368857, 'reg_alpha': 11.55788189784761, 'reg_lambda': 0.06439140570558605}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  40%|███████████████▉                        | 159/400 [15:36<24:29,  6.10s/it]

[I 2026-05-25 16:49:52,735] Trial 158 finished with value: 0.9501111809399647 and parameters: {'n_estimators': 232, 'learning_rate': 0.045879543568929274, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 271, 'subsample': 0.6468730632235972, 'colsample_bytree': 0.7488477500944629, 'reg_alpha': 13.431449796544195, 'reg_lambda': 0.032495117988519465}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  40%|████████████████                        | 160/400 [15:37<18:56,  4.73s/it]

[I 2026-05-25 16:49:54,286] Trial 155 finished with value: 0.949518926909598 and parameters: {'n_estimators': 237, 'learning_rate': 0.005346871802014288, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 260, 'subsample': 0.784957291957489, 'colsample_bytree': 0.7789058740908467, 'reg_alpha': 11.933562020579364, 'reg_lambda': 0.03135605004623738}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  40%|████████████████                        | 161/400 [15:47<24:44,  6.21s/it]

[I 2026-05-25 16:50:03,947] Trial 159 finished with value: 0.9497335195905746 and parameters: {'n_estimators': 254, 'learning_rate': 0.006743508204263855, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 268, 'subsample': 0.7953636465098729, 'colsample_bytree': 0.6819741651401665, 'reg_alpha': 10.99151415423258, 'reg_lambda': 0.030644490314221777}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  40%|████████████████▏                       | 162/400 [15:54<25:48,  6.51s/it]

[I 2026-05-25 16:50:11,140] Trial 161 finished with value: 0.9501092910919258 and parameters: {'n_estimators': 253, 'learning_rate': 0.04588557015887622, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 273, 'subsample': 0.7879898079262071, 'colsample_bytree': 0.6824575836296618, 'reg_alpha': 12.048148448869169, 'reg_lambda': 0.026886225268389703}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  41%|████████████████▎                       | 163/400 [16:12<38:48,  9.83s/it]

[I 2026-05-25 16:50:28,715] Trial 162 finished with value: 0.9501085935066274 and parameters: {'n_estimators': 255, 'learning_rate': 0.04642228396484536, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 271, 'subsample': 0.7539393974304501, 'colsample_bytree': 0.689868966287724, 'reg_alpha': 9.636419521375737, 'reg_lambda': 0.028340142326312524}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  41%|████████████████▍                       | 164/400 [16:17<33:06,  8.42s/it]

[I 2026-05-25 16:50:33,846] Trial 164 finished with value: 0.9501061857037362 and parameters: {'n_estimators': 258, 'learning_rate': 0.04605461487346402, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 268, 'subsample': 0.6390718305117433, 'colsample_bytree': 0.695872977818458, 'reg_alpha': 9.834713726525283, 'reg_lambda': 0.03030760572684208}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  41%|████████████████▌                       | 165/400 [16:19<25:40,  6.55s/it]

[I 2026-05-25 16:50:36,053] Trial 163 finished with value: 0.9501097709019437 and parameters: {'n_estimators': 255, 'learning_rate': 0.04660651439132722, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 223, 'subsample': 0.638609337872633, 'colsample_bytree': 0.6889194018528362, 'reg_alpha': 9.619537593825012, 'reg_lambda': 0.030676687932430127}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  42%|████████████████▌                       | 166/400 [16:22<20:43,  5.32s/it]

[I 2026-05-25 16:50:38,473] Trial 165 finished with value: 0.9501038275297111 and parameters: {'n_estimators': 257, 'learning_rate': 0.046525364489789424, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 225, 'subsample': 0.7002739495901626, 'colsample_bytree': 0.7323641066243887, 'reg_alpha': 10.318812329879533, 'reg_lambda': 0.8606373750385554}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  42%|████████████████▋                       | 167/400 [16:27<20:14,  5.21s/it]

[I 2026-05-25 16:50:43,453] Trial 166 finished with value: 0.9501072826241161 and parameters: {'n_estimators': 256, 'learning_rate': 0.04583101523409444, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 272, 'subsample': 0.6441723119416523, 'colsample_bytree': 0.6952189222335176, 'reg_alpha': 13.013986772503806, 'reg_lambda': 0.029114480249623154}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  42%|████████████████▊                       | 168/400 [16:28<16:02,  4.15s/it]

[I 2026-05-25 16:50:45,124] Trial 167 finished with value: 0.9501116869164905 and parameters: {'n_estimators': 256, 'learning_rate': 0.04564278528619209, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 267, 'subsample': 0.7038542762030228, 'colsample_bytree': 0.7301693890275093, 'reg_alpha': 11.66595611383478, 'reg_lambda': 0.06601157801183787}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  42%|████████████████▉                       | 169/400 [16:37<21:18,  5.53s/it]

[I 2026-05-25 16:50:53,893] Trial 168 finished with value: 0.950111726877528 and parameters: {'n_estimators': 254, 'learning_rate': 0.04598289397740371, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 255, 'subsample': 0.6445893192721005, 'colsample_bytree': 0.7315255385010194, 'reg_alpha': 13.616440187412199, 'reg_lambda': 0.06568192063646548}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  42%|█████████████████                       | 170/400 [16:40<18:22,  4.79s/it]

[I 2026-05-25 16:50:56,938] Trial 169 finished with value: 0.9501082883798274 and parameters: {'n_estimators': 228, 'learning_rate': 0.04589170852462094, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 254, 'subsample': 0.6258960435665214, 'colsample_bytree': 0.735219815873336, 'reg_alpha': 13.523644970925744, 'reg_lambda': 0.05835246785846412}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  43%|█████████████████                       | 171/400 [16:45<17:56,  4.70s/it]

[I 2026-05-25 16:51:01,428] Trial 171 finished with value: 0.9501104455015081 and parameters: {'n_estimators': 227, 'learning_rate': 0.04597976400656821, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 254, 'subsample': 0.6315895832127987, 'colsample_bytree': 0.7357853991754757, 'reg_alpha': 5.323461388204326, 'reg_lambda': 0.020189905074001032}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  43%|█████████████████▏                      | 172/400 [16:48<16:05,  4.23s/it]

[I 2026-05-25 16:51:04,589] Trial 170 finished with value: 0.9501068360775816 and parameters: {'n_estimators': 229, 'learning_rate': 0.04590693293047628, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 254, 'subsample': 0.7068557224603546, 'colsample_bytree': 0.7349693737240048, 'reg_alpha': 5.224964350438894, 'reg_lambda': 0.06789039289666622}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  43%|█████████████████▎                      | 173/400 [17:05<30:19,  8.02s/it]

[I 2026-05-25 16:51:21,421] Trial 172 finished with value: 0.9501044921314674 and parameters: {'n_estimators': 255, 'learning_rate': 0.04593941377407181, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 254, 'subsample': 0.6330977617292318, 'colsample_bytree': 0.7339795974291186, 'reg_alpha': 5.205447601841885, 'reg_lambda': 0.02145537492645982}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  44%|█████████████████▍                      | 174/400 [17:11<27:50,  7.39s/it]

[I 2026-05-25 16:51:27,350] Trial 173 finished with value: 0.9501086062345966 and parameters: {'n_estimators': 256, 'learning_rate': 0.04573278800331239, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 254, 'subsample': 0.652068525937437, 'colsample_bytree': 0.736348994032057, 'reg_alpha': 4.372820636743525, 'reg_lambda': 0.05742165527427151}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  44%|█████████████████▌                      | 175/400 [17:15<24:53,  6.64s/it]

[I 2026-05-25 16:51:32,252] Trial 174 finished with value: 0.9501050336992837 and parameters: {'n_estimators': 216, 'learning_rate': 0.04584432127043859, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 255, 'subsample': 0.6274172358029362, 'colsample_bytree': 0.7336793663067865, 'reg_alpha': 5.263713627942265, 'reg_lambda': 0.05927983161604297}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  44%|█████████████████▌                      | 176/400 [17:23<25:57,  6.95s/it]

[I 2026-05-25 16:51:39,943] Trial 175 finished with value: 0.9501105345130411 and parameters: {'n_estimators': 217, 'learning_rate': 0.04584148574618556, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 255, 'subsample': 0.7055986781077477, 'colsample_bytree': 0.7312355111491217, 'reg_alpha': 15.177416397741885, 'reg_lambda': 0.07020767391274833}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  44%|█████████████████▋                      | 177/400 [17:38<34:31,  9.29s/it]

[I 2026-05-25 16:51:54,672] Trial 179 finished with value: 0.9501049145996564 and parameters: {'n_estimators': 246, 'learning_rate': 0.04949096516081146, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 255, 'subsample': 0.6692744378422502, 'colsample_bytree': 0.7315496992649516, 'reg_alpha': 4.656638237103146, 'reg_lambda': 0.165443572873153}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  44%|█████████████████▊                      | 178/400 [17:40<26:56,  7.28s/it]

[I 2026-05-25 16:51:57,270] Trial 176 finished with value: 0.9501117014852289 and parameters: {'n_estimators': 270, 'learning_rate': 0.04566489625371349, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 256, 'subsample': 0.616864443151127, 'colsample_bytree': 0.7311626982930409, 'reg_alpha': 15.600293636579725, 'reg_lambda': 0.05617452734248237}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  45%|█████████████████▉                      | 179/400 [17:42<20:00,  5.43s/it]

[I 2026-05-25 16:51:58,377] Trial 178 finished with value: 0.9501057978066335 and parameters: {'n_estimators': 247, 'learning_rate': 0.04958477315772067, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 254, 'subsample': 0.6181374053948235, 'colsample_bytree': 0.8030905449601647, 'reg_alpha': 5.457306717966218, 'reg_lambda': 0.019160808025277826}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  45%|██████████████████                      | 180/400 [17:47<20:22,  5.56s/it]

[I 2026-05-25 16:52:04,238] Trial 177 finished with value: 0.9501109819859035 and parameters: {'n_estimators': 270, 'learning_rate': 0.04969956408476219, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 254, 'subsample': 0.7067962226629237, 'colsample_bytree': 0.7321834977959861, 'reg_alpha': 5.374403261370968, 'reg_lambda': 0.07096532197736277}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  45%|██████████████████                      | 181/400 [17:50<16:55,  4.64s/it]

[I 2026-05-25 16:52:06,719] Trial 182 finished with value: 0.9501090294316363 and parameters: {'n_estimators': 217, 'learning_rate': 0.04985756004050199, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 256, 'subsample': 0.6700250037449722, 'colsample_bytree': 0.729595699779368, 'reg_alpha': 4.927548371427223, 'reg_lambda': 0.07114299882706131}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  46%|██████████████████▏                     | 182/400 [17:50<12:10,  3.35s/it]

[I 2026-05-25 16:52:07,054] Trial 181 finished with value: 0.9501066663388587 and parameters: {'n_estimators': 247, 'learning_rate': 0.0496452983646157, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 255, 'subsample': 0.6718729540548198, 'colsample_bytree': 0.7396490980493818, 'reg_alpha': 5.650997037744971, 'reg_lambda': 0.020054295113290384}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  46%|██████████████████▎                     | 183/400 [17:53<10:59,  3.04s/it]

[I 2026-05-25 16:52:09,374] Trial 180 finished with value: 0.9501131788462592 and parameters: {'n_estimators': 248, 'learning_rate': 0.04288724097980755, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 255, 'subsample': 0.6178659993771846, 'colsample_bytree': 0.7393360321352593, 'reg_alpha': 5.810822989143896, 'reg_lambda': 0.15655813108790126}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  46%|██████████████████▍                     | 184/400 [18:05<20:56,  5.82s/it]

[I 2026-05-25 16:52:21,667] Trial 183 finished with value: 0.9501099596456534 and parameters: {'n_estimators': 249, 'learning_rate': 0.042526463219376046, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 265, 'subsample': 0.6678799720425588, 'colsample_bytree': 0.7437929091059073, 'reg_alpha': 6.606270957098931, 'reg_lambda': 0.04842039404286867}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  46%|██████████████████▌                     | 185/400 [18:24<34:40,  9.68s/it]

[I 2026-05-25 16:52:40,359] Trial 185 finished with value: 0.9500892183449008 and parameters: {'n_estimators': 247, 'learning_rate': 0.04947977268836758, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 264, 'subsample': 0.7253000946230111, 'colsample_bytree': 0.7453176246900547, 'reg_alpha': 62.18025704854881, 'reg_lambda': 0.1540803149574308}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  46%|██████████████████▌                     | 186/400 [18:24<25:04,  7.03s/it]

[I 2026-05-25 16:52:41,230] Trial 184 finished with value: 0.950113647761531 and parameters: {'n_estimators': 269, 'learning_rate': 0.042370889258010094, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 280, 'subsample': 0.7236077563925741, 'colsample_bytree': 0.7431705945621588, 'reg_alpha': 6.842930217395565, 'reg_lambda': 0.18007770477640656}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  47%|██████████████████▋                     | 187/400 [18:37<30:41,  8.64s/it]

[I 2026-05-25 16:52:53,623] Trial 187 finished with value: 0.950110773422441 and parameters: {'n_estimators': 249, 'learning_rate': 0.04284224371823075, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 265, 'subsample': 0.667678385527758, 'colsample_bytree': 0.7469279563761152, 'reg_alpha': 6.712431125352301, 'reg_lambda': 0.046863765743920274}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  47%|██████████████████▊                     | 188/400 [18:37<21:46,  6.16s/it]

[I 2026-05-25 16:52:54,006] Trial 186 finished with value: 0.9501074115842245 and parameters: {'n_estimators': 248, 'learning_rate': 0.04264076852497119, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 242, 'subsample': 0.6722300349402947, 'colsample_bytree': 0.744380038831654, 'reg_alpha': 6.669970155874078, 'reg_lambda': 0.14631496724008575}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  47%|██████████████████▉                     | 189/400 [18:53<31:54,  9.07s/it]

[I 2026-05-25 16:53:09,877] Trial 188 finished with value: 0.950092586610465 and parameters: {'n_estimators': 269, 'learning_rate': 0.04974134446699375, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 264, 'subsample': 0.724778400127525, 'colsample_bytree': 0.7442122056490162, 'reg_alpha': 62.682684044014124, 'reg_lambda': 0.016919031076256096}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  48%|███████████████████                     | 190/400 [18:55<23:58,  6.85s/it]

[I 2026-05-25 16:53:11,548] Trial 189 finished with value: 0.9501092977882134 and parameters: {'n_estimators': 249, 'learning_rate': 0.04254718043497165, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 243, 'subsample': 0.7222367647670239, 'colsample_bytree': 0.7449945882414325, 'reg_alpha': 26.222106963115678, 'reg_lambda': 0.005337331108646307}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  48%|███████████████████                     | 191/400 [19:04<26:03,  7.48s/it]

[I 2026-05-25 16:53:20,481] Trial 190 finished with value: 0.9500879827463852 and parameters: {'n_estimators': 271, 'learning_rate': 0.0424196357599116, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 279, 'subsample': 0.612410427238889, 'colsample_bytree': 0.7449799861224726, 'reg_alpha': 61.493379777601454, 'reg_lambda': 0.005468231463355634}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  48%|███████████████████▏                    | 192/400 [19:08<22:51,  6.59s/it]

[I 2026-05-25 16:53:25,008] Trial 191 finished with value: 0.9500839237391245 and parameters: {'n_estimators': 270, 'learning_rate': 0.042566144587044656, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 241, 'subsample': 0.6508952869470623, 'colsample_bytree': 0.769071350261336, 'reg_alpha': 58.88286054054602, 'reg_lambda': 0.043059617755154905}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  48%|███████████████████▎                    | 193/400 [19:08<16:14,  4.71s/it]

[I 2026-05-25 16:53:25,312] Trial 194 finished with value: 0.9501122896461973 and parameters: {'n_estimators': 249, 'learning_rate': 0.04217964385947899, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 241, 'subsample': 0.6150815423565967, 'colsample_bytree': 0.7470786688122905, 'reg_alpha': 25.829042792570707, 'reg_lambda': 0.1436737132104551}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  48%|███████████████████▍                    | 194/400 [19:09<11:39,  3.40s/it]

[I 2026-05-25 16:53:25,645] Trial 192 finished with value: 0.9501117577793879 and parameters: {'n_estimators': 269, 'learning_rate': 0.04228165309137935, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 264, 'subsample': 0.6131000019682267, 'colsample_bytree': 0.7456816042923733, 'reg_alpha': 27.12402840052554, 'reg_lambda': 0.0450482958078158}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  49%|███████████████████▌                    | 195/400 [19:12<11:19,  3.31s/it]

[I 2026-05-25 16:53:28,786] Trial 193 finished with value: 0.9501073193546368 and parameters: {'n_estimators': 271, 'learning_rate': 0.042399129983874614, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 241, 'subsample': 0.7221842933878837, 'colsample_bytree': 0.7521238501022319, 'reg_alpha': 27.239750320952208, 'reg_lambda': 0.04474929713375415}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  49%|███████████████████▌                    | 196/400 [19:28<23:46,  6.99s/it]

[I 2026-05-25 16:53:44,373] Trial 195 finished with value: 0.9501114506031116 and parameters: {'n_estimators': 270, 'learning_rate': 0.042765228292057034, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 243, 'subsample': 0.613711813943969, 'colsample_bytree': 0.7533114147348309, 'reg_alpha': 24.91051648727134, 'reg_lambda': 0.16758575994070896}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  49%|███████████████████▋                    | 197/400 [19:33<22:19,  6.60s/it]

[I 2026-05-25 16:53:50,045] Trial 200 finished with value: 0.9497359517776631 and parameters: {'n_estimators': 268, 'learning_rate': 0.0384522419469197, 'max_depth': 4, 'num_leaves': 2, 'min_child_samples': 241, 'subsample': 0.6519708342617845, 'colsample_bytree': 0.7683822701977038, 'reg_alpha': 25.65461934105126, 'reg_lambda': 0.39406038199117743}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  50%|███████████████████▊                    | 198/400 [19:38<20:02,  5.95s/it]

[I 2026-05-25 16:53:54,484] Trial 203 finished with value: 0.9499168399141228 and parameters: {'n_estimators': 80, 'learning_rate': 0.038482653885327636, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 278, 'subsample': 0.6129414784262586, 'colsample_bytree': 0.7597799939007766, 'reg_alpha': 0.0010453467864036336, 'reg_lambda': 0.4686889133271014}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  50%|███████████████████▉                    | 199/400 [19:50<26:03,  7.78s/it]

[I 2026-05-25 16:54:06,515] Trial 197 finished with value: 0.9501066559079657 and parameters: {'n_estimators': 269, 'learning_rate': 0.04245705222690081, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 243, 'subsample': 0.6178829752547826, 'colsample_bytree': 0.7566339265440805, 'reg_alpha': 7.804216660643897, 'reg_lambda': 0.14193254836818348}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  50%|████████████████████                    | 200/400 [19:52<20:06,  6.03s/it]

[I 2026-05-25 16:54:08,482] Trial 196 finished with value: 0.9501124181950434 and parameters: {'n_estimators': 271, 'learning_rate': 0.04223794389322496, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 243, 'subsample': 0.6004901501863029, 'colsample_bytree': 0.7687914379052407, 'reg_alpha': 8.147877952123059, 'reg_lambda': 0.046074183864739264}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  50%|████████████████████                    | 201/400 [19:53<14:57,  4.51s/it]

[I 2026-05-25 16:54:09,421] Trial 198 finished with value: 0.9501098335198102 and parameters: {'n_estimators': 270, 'learning_rate': 0.042432044637790156, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 241, 'subsample': 0.6131742275371211, 'colsample_bytree': 0.7702357416799599, 'reg_alpha': 25.444192258402296, 'reg_lambda': 0.04252250449874788}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  50%|████████████████████▏                   | 202/400 [19:58<15:23,  4.67s/it]

[I 2026-05-25 16:54:14,475] Trial 199 finished with value: 0.9501088234357 and parameters: {'n_estimators': 267, 'learning_rate': 0.03768075631622021, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 241, 'subsample': 0.760452944114973, 'colsample_bytree': 0.7692539364861224, 'reg_alpha': 26.294993527234965, 'reg_lambda': 0.4007926524510155}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  51%|████████████████████▎                   | 203/400 [20:20<32:26,  9.88s/it]

[I 2026-05-25 16:54:36,511] Trial 201 finished with value: 0.9501141854137785 and parameters: {'n_estimators': 268, 'learning_rate': 0.03822957745213173, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 240, 'subsample': 0.612987807051288, 'colsample_bytree': 0.7678855581985942, 'reg_alpha': 7.836041366597824, 'reg_lambda': 1.0812406634262666}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  51%|████████████████████▍                   | 204/400 [20:24<27:04,  8.29s/it]

[I 2026-05-25 16:54:41,063] Trial 205 finished with value: 0.9501118062892701 and parameters: {'n_estimators': 262, 'learning_rate': 0.03830920529678361, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 248, 'subsample': 0.6106423227142403, 'colsample_bytree': 0.7580181297466683, 'reg_alpha': 26.26370360226132, 'reg_lambda': 0.17667123101766624}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  51%|████████████████████▌                   | 205/400 [20:26<20:45,  6.39s/it]

[I 2026-05-25 16:54:43,049] Trial 202 finished with value: 0.9501123219153133 and parameters: {'n_estimators': 269, 'learning_rate': 0.038393169914941676, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 278, 'subsample': 0.6003238244602113, 'colsample_bytree': 0.7674576130483558, 'reg_alpha': 15.96497887237172, 'reg_lambda': 0.43515117117200147}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  52%|████████████████████▌                   | 206/400 [20:29<17:34,  5.43s/it]

[I 2026-05-25 16:54:46,241] Trial 204 finished with value: 0.9501087835896387 and parameters: {'n_estimators': 271, 'learning_rate': 0.037610915515549896, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 195, 'subsample': 0.6121010057758536, 'colsample_bytree': 0.7572326476394072, 'reg_alpha': 15.01744286911533, 'reg_lambda': 0.19027781127075602}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  52%|████████████████████▋                   | 207/400 [20:30<12:39,  3.93s/it]

[I 2026-05-25 16:54:46,673] Trial 206 finished with value: 0.9501108808952454 and parameters: {'n_estimators': 260, 'learning_rate': 0.03807232362723087, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 248, 'subsample': 0.6051541901113284, 'colsample_bytree': 0.7584989991776627, 'reg_alpha': 8.177838463880324, 'reg_lambda': 0.12386438465699627}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  52%|████████████████████▊                   | 208/400 [20:38<17:02,  5.33s/it]

[I 2026-05-25 16:54:55,241] Trial 207 finished with value: 0.9501162432950956 and parameters: {'n_estimators': 237, 'learning_rate': 0.044037117238640976, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 233, 'subsample': 0.7633815030185118, 'colsample_bytree': 0.7669513027986791, 'reg_alpha': 8.9552782152396, 'reg_lambda': 0.11291936680519289}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  52%|████████████████████▉                   | 209/400 [20:46<19:19,  6.07s/it]

[I 2026-05-25 16:55:03,067] Trial 208 finished with value: 0.9501019704341991 and parameters: {'n_estimators': 237, 'learning_rate': 0.037385261536598276, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 232, 'subsample': 0.6019046944576615, 'colsample_bytree': 0.7573041570722268, 'reg_alpha': 8.364178227759787, 'reg_lambda': 0.9579694165278184}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  52%|█████████████████████                   | 210/400 [20:47<14:25,  4.56s/it]

[I 2026-05-25 16:55:04,079] Trial 209 finished with value: 0.9501054552046094 and parameters: {'n_estimators': 234, 'learning_rate': 0.03919500507253963, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 229, 'subsample': 0.7558045443216926, 'colsample_bytree': 0.7217589700626487, 'reg_alpha': 8.127914169535217, 'reg_lambda': 0.2026380965307768}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  53%|█████████████████████                   | 211/400 [21:09<30:26,  9.66s/it]

[I 2026-05-25 16:55:25,663] Trial 211 finished with value: 0.9501045412308967 and parameters: {'n_estimators': 234, 'learning_rate': 0.037147285392571235, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 233, 'subsample': 0.6240905619394435, 'colsample_bytree': 0.7609290404555761, 'reg_alpha': 8.671396749106286, 'reg_lambda': 0.012813304471470015}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  53%|█████████████████████▏                  | 212/400 [21:11<22:48,  7.28s/it]

[I 2026-05-25 16:55:27,379] Trial 212 finished with value: 0.9501083189219539 and parameters: {'n_estimators': 237, 'learning_rate': 0.03836600640192539, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 231, 'subsample': 0.6053057225292333, 'colsample_bytree': 0.7192030074858272, 'reg_alpha': 8.403130547233115, 'reg_lambda': 0.09223937875039628}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  53%|█████████████████████▎                  | 213/400 [21:14<18:49,  6.04s/it]

[I 2026-05-25 16:55:30,536] Trial 213 finished with value: 0.9500921072091959 and parameters: {'n_estimators': 236, 'learning_rate': 0.0369980023106447, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 231, 'subsample': 0.6003390003847975, 'colsample_bytree': 0.7237635948529882, 'reg_alpha': 8.595443951492907, 'reg_lambda': 0.09633894571892311}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  54%|█████████████████████▍                  | 214/400 [21:14<13:35,  4.38s/it]

[I 2026-05-25 16:55:31,056] Trial 210 finished with value: 0.9501091226748809 and parameters: {'n_estimators': 262, 'learning_rate': 0.039127098140565725, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 232, 'subsample': 0.6038938572210124, 'colsample_bytree': 0.7651095912632018, 'reg_alpha': 17.199751449544085, 'reg_lambda': 0.987841706365057}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  54%|█████████████████████▌                  | 215/400 [21:33<27:07,  8.80s/it]

[I 2026-05-25 16:55:50,165] Trial 214 finished with value: 0.9501016293334826 and parameters: {'n_estimators': 236, 'learning_rate': 0.039226850661874306, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 249, 'subsample': 0.6033476566329661, 'colsample_bytree': 0.762880411639393, 'reg_alpha': 8.48001847881262, 'reg_lambda': 0.013491461831264574}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  54%|█████████████████████▌                  | 216/400 [21:37<22:13,  7.24s/it]

[I 2026-05-25 16:55:53,782] Trial 215 finished with value: 0.9501024853426578 and parameters: {'n_estimators': 235, 'learning_rate': 0.038491219797470826, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 232, 'subsample': 0.6061565207639984, 'colsample_bytree': 0.7628493468821786, 'reg_alpha': 7.876614275890356, 'reg_lambda': 1.3228501819657352}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  54%|█████████████████████▋                  | 217/400 [21:39<17:37,  5.78s/it]

[I 2026-05-25 16:55:56,131] Trial 221 pruned.

Best trial: 120. Best value: 0.950117:  55%|█████████████████████▊                  | 218/400 [21:42<14:33,  4.80s/it]

[I 2026-05-25 16:55:58,645] Trial 216 finished with value: 0.9500957651094222 and parameters: {'n_estimators': 235, 'learning_rate': 0.036624501067422696, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 229, 'subsample': 0.6020682617975116, 'colsample_bytree': 0.7615176739225614, 'reg_alpha': 8.454233276023258, 'reg_lambda': 0.8825576542034343}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  55%|█████████████████████▉                  | 219/400 [21:53<20:41,  6.86s/it]

[I 2026-05-25 16:56:10,307] Trial 219 finished with value: 0.9501070512587105 and parameters: {'n_estimators': 234, 'learning_rate': 0.040150347432674476, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 231, 'subsample': 0.6212822061117053, 'colsample_bytree': 0.7654314009842288, 'reg_alpha': 9.011819701521816, 'reg_lambda': 1.2811627894239042}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  55%|██████████████████████                  | 220/400 [21:55<16:06,  5.37s/it]

[I 2026-05-25 16:56:12,213] Trial 218 finished with value: 0.9500915854124111 and parameters: {'n_estimators': 283, 'learning_rate': 0.040545343647354196, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 232, 'subsample': 0.6009352126717117, 'colsample_bytree': 0.764981208539923, 'reg_alpha': 0.060227273655157954, 'reg_lambda': 0.22674637361281202}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  55%|██████████████████████                  | 221/400 [21:56<11:59,  4.02s/it]

[I 2026-05-25 16:56:13,071] Trial 217 finished with value: 0.9501126809370695 and parameters: {'n_estimators': 282, 'learning_rate': 0.039186406300126556, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 230, 'subsample': 0.6016858739214709, 'colsample_bytree': 0.763023791290466, 'reg_alpha': 9.29039148321099, 'reg_lambda': 1.153548622989239}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 120. Best value: 0.950117:  56%|██████████████████████▏                 | 222/400 [22:10<20:51,  7.03s/it]

[I 2026-05-25 16:56:27,138] Trial 220 finished with value: 0.9501150183521793 and parameters: {'n_estimators': 283, 'learning_rate': 0.03983646282229084, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 231, 'subsample': 0.6021368091113152, 'colsample_bytree': 0.7678962171320918, 'reg_alpha': 8.142701009570935, 'reg_lambda': 1.1591788366750382}. Best is trial 120 with value: 0.9501174064007986.

Best trial: 222. Best value: 0.950118:  56%|██████████████████████▎                 | 223/400 [22:27<29:27,  9.99s/it]

[I 2026-05-25 16:56:44,007] Trial 222 finished with value: 0.950118144149393 and parameters: {'n_estimators': 262, 'learning_rate': 0.03963893079330622, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 249, 'subsample': 0.6063030208447914, 'colsample_bytree': 0.7672395523888131, 'reg_alpha': 3.896978974630455, 'reg_lambda': 0.9477735691848992}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  56%|██████████████████████▍                 | 224/400 [22:32<24:25,  8.32s/it]

[I 2026-05-25 16:56:48,455] Trial 224 finished with value: 0.9501072208401482 and parameters: {'n_estimators': 262, 'learning_rate': 0.039775464426215074, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 290, 'subsample': 0.8147286791830155, 'colsample_bytree': 0.7848427464092559, 'reg_alpha': 3.95452120437578, 'reg_lambda': 1.112367591437781}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  56%|██████████████████████▌                 | 225/400 [22:42<25:44,  8.82s/it]

[I 2026-05-25 16:56:58,443] Trial 225 finished with value: 0.9501103747459856 and parameters: {'n_estimators': 283, 'learning_rate': 0.04022139396435987, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 249, 'subsample': 0.6214085698765054, 'colsample_bytree': 0.7719387575939761, 'reg_alpha': 17.187765313217263, 'reg_lambda': 1.2296738520787163}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  56%|██████████████████████▌                 | 226/400 [22:43<18:41,  6.45s/it]

[I 2026-05-25 16:56:59,342] Trial 223 finished with value: 0.9499720997005149 and parameters: {'n_estimators': 281, 'learning_rate': 0.01428294898484313, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 248, 'subsample': 0.606674897249025, 'colsample_bytree': 0.7694910370554243, 'reg_alpha': 3.583974905092996, 'reg_lambda': 0.29843503367499025}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  57%|██████████████████████▋                 | 227/400 [22:44<13:58,  4.85s/it]

[I 2026-05-25 16:57:00,465] Trial 227 finished with value: 0.950104392333866 and parameters: {'n_estimators': 223, 'learning_rate': 0.044167663250941375, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 294, 'subsample': 0.6210709515849231, 'colsample_bytree': 0.7752861175478247, 'reg_alpha': 3.406982214062483, 'reg_lambda': 0.0001469103145009567}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  57%|██████████████████████▊                 | 228/400 [22:58<22:28,  7.84s/it]

[I 2026-05-25 16:57:15,303] Trial 226 finished with value: 0.9501031472046165 and parameters: {'n_estimators': 284, 'learning_rate': 0.04386821894197128, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 249, 'subsample': 0.6320252554488751, 'colsample_bytree': 0.7855101803997547, 'reg_alpha': 3.6585278422628216, 'reg_lambda': 1.105528830256258}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  57%|██████████████████████▉                 | 229/400 [22:59<16:26,  5.77s/it]

[I 2026-05-25 16:57:16,222] Trial 228 finished with value: 0.9501113630317481 and parameters: {'n_estimators': 262, 'learning_rate': 0.045021043809958146, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 292, 'subsample': 0.6226617860920423, 'colsample_bytree': 0.769377124157789, 'reg_alpha': 16.43676043719321, 'reg_lambda': 0.30573055177433356}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  57%|███████████████████████                 | 230/400 [23:02<14:01,  4.95s/it]

[I 2026-05-25 16:57:19,261] Trial 229 finished with value: 0.9501011832676489 and parameters: {'n_estimators': 260, 'learning_rate': 0.044120488264413185, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 176, 'subsample': 0.619303684213324, 'colsample_bytree': 0.7740624408559442, 'reg_alpha': 0.06932857986921664, 'reg_lambda': 1.2052532342951625}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  58%|███████████████████████                 | 231/400 [23:08<14:11,  5.04s/it]

[I 2026-05-25 16:57:24,509] Trial 230 finished with value: 0.9501103019274755 and parameters: {'n_estimators': 242, 'learning_rate': 0.04424245963464753, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 248, 'subsample': 0.8251458521656495, 'colsample_bytree': 0.7751005680363684, 'reg_alpha': 3.7859598234311966, 'reg_lambda': 0.30174093075151887}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  58%|███████████████████████▏                | 232/400 [23:08<10:25,  3.72s/it]

[I 2026-05-25 16:57:25,169] Trial 232 finished with value: 0.9500999768746006 and parameters: {'n_estimators': 242, 'learning_rate': 0.04432760234765227, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 291, 'subsample': 0.6327495145154776, 'colsample_bytree': 0.7751177641533356, 'reg_alpha': 0.01707209636741484, 'reg_lambda': 2.514990618966865}. Best is trial 222 with value: 0.950118144149393.

Best trial: 222. Best value: 0.950118:  58%|███████████████████████▎                | 233/400 [23:15<12:56,  4.65s/it]

[I 2026-05-25 16:57:31,974] Trial 231 finished with value: 0.9501094337860382 and parameters: {'n_estimators': 262, 'learning_rate': 0.044519226169747524, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 294, 'subsample': 0.633538759052218, 'colsample_bytree': 0.7740203417325554, 'reg_alpha': 3.7535433845913886, 'reg_lambda': 0.3495191462283241}. Best is trial 222 with value: 0.950118144149393.

Best trial: 233. Best value: 0.950121:  58%|███████████████████████▍                | 234/400 [23:36<26:26,  9.56s/it]

[I 2026-05-25 16:57:52,986] Trial 233 finished with value: 0.9501206549495727 and parameters: {'n_estimators': 281, 'learning_rate': 0.04357452029809975, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 225, 'subsample': 0.8297589147310568, 'colsample_bytree': 0.7742067007572333, 'reg_alpha': 14.515041750336636, 'reg_lambda': 2.285385461715537}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  59%|███████████████████████▌                | 235/400 [23:48<28:22, 10.32s/it]

[I 2026-05-25 16:58:05,061] Trial 234 finished with value: 0.9501175901585718 and parameters: {'n_estimators': 290, 'learning_rate': 0.044316046987742386, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 174, 'subsample': 0.621018625137235, 'colsample_bytree': 0.667162655925639, 'reg_alpha': 4.120214860867975, 'reg_lambda': 2.4982231635523156}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  59%|███████████████████████▌                | 236/400 [23:53<23:35,  8.63s/it]

[I 2026-05-25 16:58:09,775] Trial 236 finished with value: 0.950109722285213 and parameters: {'n_estimators': 242, 'learning_rate': 0.044366606699339825, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 220, 'subsample': 0.6325931727087424, 'colsample_bytree': 0.7732168308128065, 'reg_alpha': 3.820030809382593, 'reg_lambda': 0.7687542342573223}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  59%|███████████████████████▋                | 237/400 [23:54<17:37,  6.49s/it]

[I 2026-05-25 16:58:11,251] Trial 238 finished with value: 0.9501181087560091 and parameters: {'n_estimators': 242, 'learning_rate': 0.043678627906529564, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 224, 'subsample': 0.632003317469897, 'colsample_bytree': 0.6656104313027777, 'reg_alpha': 11.982666990577968, 'reg_lambda': 0.7027247730812117}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  60%|███████████████████████▊                | 238/400 [24:00<16:56,  6.28s/it]

[I 2026-05-25 16:58:17,031] Trial 235 finished with value: 0.9500966079144989 and parameters: {'n_estimators': 292, 'learning_rate': 0.04469737765843791, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 237, 'subsample': 0.6331220286240593, 'colsample_bytree': 0.772210075724225, 'reg_alpha': 3.580969391284798, 'reg_lambda': 0.5981600590247215}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  60%|███████████████████████▉                | 239/400 [24:01<12:43,  4.74s/it]

[I 2026-05-25 16:58:18,205] Trial 237 finished with value: 0.9501132682092251 and parameters: {'n_estimators': 292, 'learning_rate': 0.043391789477168936, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 174, 'subsample': 0.6252881787568655, 'colsample_bytree': 0.6633852925815602, 'reg_alpha': 11.791664975116717, 'reg_lambda': 1.9944997952673706}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  60%|████████████████████████                | 240/400 [24:13<18:03,  6.77s/it]

[I 2026-05-25 16:58:29,716] Trial 240 finished with value: 0.9501066525823555 and parameters: {'n_estimators': 244, 'learning_rate': 0.04389452169165079, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 225, 'subsample': 0.7671656017158731, 'colsample_bytree': 0.7514459291823046, 'reg_alpha': 11.72650303246089, 'reg_lambda': 0.6822510264105448}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  60%|████████████████████████                | 241/400 [24:14<13:47,  5.20s/it]

[I 2026-05-25 16:58:31,249] Trial 239 finished with value: 0.950113321573892 and parameters: {'n_estimators': 244, 'learning_rate': 0.04440829485895466, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 221, 'subsample': 0.7499808997857116, 'colsample_bytree': 0.7528649898866189, 'reg_alpha': 13.337155545259346, 'reg_lambda': 0.6504985306864659}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  60%|████████████████████████▏               | 242/400 [24:29<21:19,  8.10s/it]

[I 2026-05-25 16:58:46,111] Trial 241 finished with value: 0.9501101340492484 and parameters: {'n_estimators': 291, 'learning_rate': 0.04452966231218625, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 220, 'subsample': 0.7540123382139649, 'colsample_bytree': 0.7537921817538646, 'reg_alpha': 11.612347277409292, 'reg_lambda': 0.6613828967952287}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  61%|████████████████████████▎               | 243/400 [24:32<17:05,  6.53s/it]

[I 2026-05-25 16:58:48,984] Trial 242 finished with value: 0.9501121265599553 and parameters: {'n_estimators': 277, 'learning_rate': 0.04151127641515065, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 225, 'subsample': 0.7536437639138954, 'colsample_bytree': 0.7496775479398385, 'reg_alpha': 11.323272119190413, 'reg_lambda': 0.7080585547701644}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 233. Best value: 0.950121:  61%|████████████████████████▍               | 244/400 [24:36<14:35,  5.61s/it]

[I 2026-05-25 16:58:52,447] Trial 243 finished with value: 0.9501108542689725 and parameters: {'n_estimators': 290, 'learning_rate': 0.0413919467056516, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 220, 'subsample': 0.7113123180650154, 'colsample_bytree': 0.7544994330599081, 'reg_alpha': 12.816984854623973, 'reg_lambda': 0.6349858266786176}. Best is trial 233 with value: 0.9501206549495727.

Best trial: 244. Best value: 0.950121:  61%|████████████████████████▌               | 245/400 [24:41<14:11,  5.49s/it]

[I 2026-05-25 16:58:57,670] Trial 244 finished with value: 0.9501212554745905 and parameters: {'n_estimators': 290, 'learning_rate': 0.04146784438894685, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 225, 'subsample': 0.7117089585508981, 'colsample_bytree': 0.754082121213906, 'reg_alpha': 11.812401864668468, 'reg_lambda': 0.6492214539570073}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  62%|████████████████████████▌               | 246/400 [25:02<26:24, 10.29s/it]

[I 2026-05-25 16:59:19,124] Trial 251 finished with value: 0.9500580518904677 and parameters: {'n_estimators': 280, 'learning_rate': 0.04746918981197869, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 169, 'subsample': 0.7366643843505696, 'colsample_bytree': 0.6697999668632132, 'reg_alpha': 5.793185838969284, 'reg_lambda': 1.797732354122188}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  62%|████████████████████████▋               | 247/400 [25:03<18:38,  7.31s/it]

[I 2026-05-25 16:59:19,491] Trial 245 finished with value: 0.9499024000852382 and parameters: {'n_estimators': 289, 'learning_rate': 0.011347535229588472, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 222, 'subsample': 0.7369805139642974, 'colsample_bytree': 0.754951968623011, 'reg_alpha': 11.720696640213937, 'reg_lambda': 0.7036395338577441}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  62%|████████████████████████▊               | 248/400 [25:05<14:50,  5.86s/it]

[I 2026-05-25 16:59:21,961] Trial 246 finished with value: 0.9501022383319633 and parameters: {'n_estimators': 275, 'learning_rate': 0.04752174330027387, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 222, 'subsample': 0.7391779608635666, 'colsample_bytree': 0.6692522136165765, 'reg_alpha': 6.239803974466748, 'reg_lambda': 2.5676571748707198}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  62%|████████████████████████▉               | 249/400 [25:15<17:43,  7.04s/it]

[I 2026-05-25 16:59:31,771] Trial 248 finished with value: 0.9501188380810894 and parameters: {'n_estimators': 287, 'learning_rate': 0.04762109297990088, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 223, 'subsample': 0.8410167352715877, 'colsample_bytree': 0.7520168107759261, 'reg_alpha': 6.1312770201965705, 'reg_lambda': 2.347254992147657}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  62%|█████████████████████████               | 250/400 [25:17<13:42,  5.48s/it]

[I 2026-05-25 16:59:33,592] Trial 247 finished with value: 0.9501057527599089 and parameters: {'n_estimators': 292, 'learning_rate': 0.04758039113150673, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 222, 'subsample': 0.8445057874720896, 'colsample_bytree': 0.6333618092558662, 'reg_alpha': 11.518864199185678, 'reg_lambda': 0.7061540864221644}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  63%|█████████████████████████               | 251/400 [25:20<11:42,  4.72s/it]

[I 2026-05-25 16:59:36,512] Trial 249 finished with value: 0.950116512155116 and parameters: {'n_estimators': 291, 'learning_rate': 0.04749083946028196, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 220, 'subsample': 0.7380394944859018, 'colsample_bytree': 0.6627625180518995, 'reg_alpha': 6.4747379831714795, 'reg_lambda': 2.215599749529647}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  63%|█████████████████████████▏              | 252/400 [25:24<11:18,  4.59s/it]

[I 2026-05-25 16:59:40,801] Trial 250 finished with value: 0.9501190043150751 and parameters: {'n_estimators': 292, 'learning_rate': 0.04769661619062518, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 185, 'subsample': 0.7675303503258716, 'colsample_bytree': 0.6498931988010624, 'reg_alpha': 12.121674298453552, 'reg_lambda': 2.542955554139736}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  63%|█████████████████████████▎              | 253/400 [25:32<13:58,  5.70s/it]

[I 2026-05-25 16:59:49,124] Trial 252 finished with value: 0.9501096682303661 and parameters: {'n_estimators': 292, 'learning_rate': 0.047872057895826395, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 162, 'subsample': 0.7524844924817601, 'colsample_bytree': 0.6656560454563278, 'reg_alpha': 11.493798896132152, 'reg_lambda': 2.3135787224583204}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  64%|█████████████████████████▍              | 254/400 [25:52<23:50,  9.80s/it]

[I 2026-05-25 17:00:08,453] Trial 253 finished with value: 0.9501155986369738 and parameters: {'n_estimators': 290, 'learning_rate': 0.047052799394267576, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 222, 'subsample': 0.7396189068881355, 'colsample_bytree': 0.6512154731176892, 'reg_alpha': 5.772120473310927, 'reg_lambda': 2.1628266570782753}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  64%|█████████████████████████▌              | 255/400 [25:52<16:43,  6.92s/it]

[I 2026-05-25 17:00:08,667] Trial 254 finished with value: 0.9501131865702839 and parameters: {'n_estimators': 293, 'learning_rate': 0.047008169997844136, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 205, 'subsample': 0.7369974651549227, 'colsample_bytree': 0.6678882510089951, 'reg_alpha': 6.710100777277425, 'reg_lambda': 2.323764029995384}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  64%|█████████████████████████▌              | 256/400 [25:58<15:43,  6.55s/it]

[I 2026-05-25 17:00:14,344] Trial 255 finished with value: 0.950104844478109 and parameters: {'n_estimators': 289, 'learning_rate': 0.04834371433671451, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 183, 'subsample': 0.7381480685088528, 'colsample_bytree': 0.6579332050009431, 'reg_alpha': 6.041746584192474, 'reg_lambda': 2.716315085736474}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  64%|█████████████████████████▋              | 257/400 [26:03<14:52,  6.24s/it]

[I 2026-05-25 17:00:19,896] Trial 256 finished with value: 0.9501188518009874 and parameters: {'n_estimators': 292, 'learning_rate': 0.0476339748836283, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 133, 'subsample': 0.8446688953915876, 'colsample_bytree': 0.6590434709124477, 'reg_alpha': 5.850278335468435, 'reg_lambda': 2.1777868094242505}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  64%|█████████████████████████▊              | 258/400 [26:09<14:53,  6.29s/it]

[I 2026-05-25 17:00:26,308] Trial 259 finished with value: 0.9501091489175277 and parameters: {'n_estimators': 227, 'learning_rate': 0.04776569113239017, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 211, 'subsample': 0.7163097367252526, 'colsample_bytree': 0.6435952722190267, 'reg_alpha': 6.616128124543142, 'reg_lambda': 1.9922436381980249}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  65%|█████████████████████████▉              | 259/400 [26:20<17:50,  7.60s/it]

[I 2026-05-25 17:00:36,931] Trial 261 finished with value: 0.9501085151276154 and parameters: {'n_estimators': 228, 'learning_rate': 0.047268280727019676, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 214, 'subsample': 0.867228212219599, 'colsample_bytree': 0.655828676169156, 'reg_alpha': 5.120992826052115, 'reg_lambda': 2.132028711232979}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  65%|██████████████████████████              | 260/400 [26:21<12:46,  5.47s/it]

[I 2026-05-25 17:00:37,460] Trial 257 finished with value: 0.9501066627433309 and parameters: {'n_estimators': 288, 'learning_rate': 0.04716448437644708, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 183, 'subsample': 0.7375461054709608, 'colsample_bytree': 0.6248186874796173, 'reg_alpha': 5.918997654627361, 'reg_lambda': 2.5203999139902025}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  65%|██████████████████████████              | 261/400 [26:22<10:02,  4.33s/it]

[I 2026-05-25 17:00:39,140] Trial 258 finished with value: 0.9501045273321328 and parameters: {'n_estimators': 293, 'learning_rate': 0.04756247286530762, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 211, 'subsample': 0.7240347270761857, 'colsample_bytree': 0.6652320846696753, 'reg_alpha': 6.128496397462893, 'reg_lambda': 2.563154776629773}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  66%|██████████████████████████▏             | 262/400 [26:37<17:17,  7.51s/it]

[I 2026-05-25 17:00:54,071] Trial 260 finished with value: 0.950113788836689 and parameters: {'n_estimators': 293, 'learning_rate': 0.0473782440767152, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 206, 'subsample': 0.8420790663808195, 'colsample_bytree': 0.6457480366294043, 'reg_alpha': 6.505180182423143, 'reg_lambda': 2.0540096000975487}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  66%|██████████████████████████▎             | 263/400 [26:42<15:09,  6.64s/it]

[I 2026-05-25 17:00:58,655] Trial 263 finished with value: 0.9500945771753276 and parameters: {'n_estimators': 293, 'learning_rate': 0.047406780404750444, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 181, 'subsample': 0.8348687036411917, 'colsample_bytree': 0.653029008294957, 'reg_alpha': 1.9187837196312616, 'reg_lambda': 2.113513327604425}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 244. Best value: 0.950121:  66%|██████████████████████████▍             | 264/400 [26:42<10:57,  4.84s/it]

[I 2026-05-25 17:00:59,298] Trial 262 finished with value: 0.9501068998573287 and parameters: {'n_estimators': 292, 'learning_rate': 0.0473275353984306, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 212, 'subsample': 0.8464853555769298, 'colsample_bytree': 0.6485983999835208, 'reg_alpha': 6.48681065767354, 'reg_lambda': 2.4277292872566907}. Best is trial 244 with value: 0.9501212554745905.

Best trial: 264. Best value: 0.950122:  66%|██████████████████████████▌             | 265/400 [26:55<16:20,  7.26s/it]

[I 2026-05-25 17:01:12,214] Trial 264 finished with value: 0.9501217147145968 and parameters: {'n_estimators': 295, 'learning_rate': 0.04685805093361932, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 213, 'subsample': 0.7652287122753422, 'colsample_bytree': 0.6502581107643186, 'reg_alpha': 5.659830763360885, 'reg_lambda': 5.8897659491389645}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  66%|██████████████████████████▌             | 266/400 [27:10<21:02,  9.42s/it]

[I 2026-05-25 17:01:26,676] Trial 266 finished with value: 0.9501078022390013 and parameters: {'n_estimators': 287, 'learning_rate': 0.04727603148528217, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 191, 'subsample': 0.842746864782155, 'colsample_bytree': 0.6102998373907794, 'reg_alpha': 1.6906707781496344, 'reg_lambda': 4.870356551842994}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  67%|██████████████████████████▋             | 267/400 [27:14<17:19,  7.81s/it]

[I 2026-05-25 17:01:30,740] Trial 265 finished with value: 0.9501098426234911 and parameters: {'n_estimators': 287, 'learning_rate': 0.04723377312152879, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 207, 'subsample': 0.7615371567566129, 'colsample_bytree': 0.6461450836428548, 'reg_alpha': 6.028284680258927, 'reg_lambda': 2.8775149383971974}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  67%|██████████████████████████▊             | 268/400 [27:15<12:37,  5.74s/it]

[I 2026-05-25 17:01:31,647] Trial 267 finished with value: 0.9500953205000731 and parameters: {'n_estimators': 296, 'learning_rate': 0.049966661001560865, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 216, 'subsample': 0.7671559453386475, 'colsample_bytree': 0.6461823697371416, 'reg_alpha': 1.7625783943291182, 'reg_lambda': 5.337868618176358}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  67%|██████████████████████████▉             | 269/400 [27:25<15:42,  7.20s/it]

[I 2026-05-25 17:01:42,241] Trial 268 finished with value: 0.9501171026311186 and parameters: {'n_estimators': 294, 'learning_rate': 0.046593111492244696, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 196, 'subsample': 0.8510083794892022, 'colsample_bytree': 0.6478185034137819, 'reg_alpha': 6.009731181639414, 'reg_lambda': 4.545425794110998}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  68%|███████████████████████████             | 270/400 [27:35<17:11,  7.94s/it]

[I 2026-05-25 17:01:51,904] Trial 269 finished with value: 0.9501063181050087 and parameters: {'n_estimators': 287, 'learning_rate': 0.04607131933146392, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 128, 'subsample': 0.8546661497592644, 'colsample_bytree': 0.6496405449020216, 'reg_alpha': 4.898125653313338, 'reg_lambda': 3.9214310350256816}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  68%|███████████████████████████             | 271/400 [27:39<14:42,  6.84s/it]

[I 2026-05-25 17:01:56,189] Trial 270 finished with value: 0.9501028339394614 and parameters: {'n_estimators': 288, 'learning_rate': 0.04511221692256382, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 149, 'subsample': 0.7612651820506597, 'colsample_bytree': 0.6513812508743158, 'reg_alpha': 1.8797380846601563, 'reg_lambda': 4.206497466654671}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  68%|███████████████████████████▏            | 272/400 [27:42<12:04,  5.66s/it]

[I 2026-05-25 17:01:59,088] Trial 271 finished with value: 0.9501185275553106 and parameters: {'n_estimators': 296, 'learning_rate': 0.04549505689019877, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 133, 'subsample': 0.8389749467500782, 'colsample_bytree': 0.6527884492672137, 'reg_alpha': 4.711401079093943, 'reg_lambda': 1.513746315294986}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  68%|███████████████████████████▎            | 273/400 [27:45<09:57,  4.70s/it]

[I 2026-05-25 17:02:01,565] Trial 272 finished with value: 0.9501019935733351 and parameters: {'n_estimators': 296, 'learning_rate': 0.04148128832035227, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 198, 'subsample': 0.8481092709159491, 'colsample_bytree': 0.6509874368595069, 'reg_alpha': 1.4642363275362287, 'reg_lambda': 3.8201084659297724}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  68%|███████████████████████████▍            | 274/400 [27:56<14:11,  6.76s/it]

[I 2026-05-25 17:02:13,115] Trial 273 finished with value: 0.9501036121713919 and parameters: {'n_estimators': 297, 'learning_rate': 0.04957338382062394, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 203, 'subsample': 0.8392110274156364, 'colsample_bytree': 0.650466399422352, 'reg_alpha': 1.9038823704018268, 'reg_lambda': 4.674911191889702}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  69%|███████████████████████████▌            | 275/400 [27:58<10:46,  5.17s/it]

[I 2026-05-25 17:02:14,590] Trial 275 finished with value: 0.9501077748506743 and parameters: {'n_estimators': 285, 'learning_rate': 0.04963322938688488, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 200, 'subsample': 0.8409804480373343, 'colsample_bytree': 0.6411604814003375, 'reg_alpha': 4.5408097316069345, 'reg_lambda': 5.24679948277716}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  69%|███████████████████████████▌            | 276/400 [28:00<08:46,  4.25s/it]

[I 2026-05-25 17:02:16,667] Trial 274 finished with value: 0.950109790434183 and parameters: {'n_estimators': 296, 'learning_rate': 0.0497623082556722, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 130, 'subsample': 0.8395422270518499, 'colsample_bytree': 0.6465483911723324, 'reg_alpha': 4.8521474950776495, 'reg_lambda': 6.039667890013052}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  69%|███████████████████████████▋            | 277/400 [28:17<16:35,  8.09s/it]

[I 2026-05-25 17:02:33,741] Trial 276 finished with value: 0.9500938454120833 and parameters: {'n_estimators': 299, 'learning_rate': 0.04960630394809094, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 218, 'subsample': 0.8605102678191081, 'colsample_bytree': 0.6377709933245447, 'reg_alpha': 0.1921462295050288, 'reg_lambda': 5.54513658154826}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  70%|███████████████████████████▊            | 278/400 [28:34<21:40, 10.66s/it]

[I 2026-05-25 17:02:50,377] Trial 278 finished with value: 0.9501084016690348 and parameters: {'n_estimators': 299, 'learning_rate': 0.0451951172098311, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 201, 'subsample': 0.8273314745142644, 'colsample_bytree': 0.6561387624779191, 'reg_alpha': 4.532272357443019, 'reg_lambda': 6.4861378344071285}. Best is trial 264 with value: 0.9501217147145968.
[I 2026-05-25 17:02:50,392] Trial 277 finished with value: 0.9501085662946611 and parameters: {'n_estimators': 296, 'learning_rate': 0.049967616830690585, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 194, 'subsample': 0.8571616987131386, 'colsample_bytree': 0.6352718951542985, 'reg_alpha': 4.5383180164507655, 'reg_lambda': 6.458613993178071}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  70%|████████████████████████████            | 280/400 [28:37<12:54,  6.46s/it]

[I 2026-05-25 17:02:53,482] Trial 279 finished with value: 0.9501149363176655 and parameters: {'n_estimators': 300, 'learning_rate': 0.04530555684073959, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 198, 'subsample': 0.8509319564979041, 'colsample_bytree': 0.6332427602701735, 'reg_alpha': 4.529464764551447, 'reg_lambda': 3.779962376781984}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  70%|████████████████████████████            | 281/400 [28:48<15:12,  7.66s/it]

[I 2026-05-25 17:03:04,824] Trial 280 finished with value: 0.950107177262565 and parameters: {'n_estimators': 297, 'learning_rate': 0.049907658702327086, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 197, 'subsample': 0.8285781055885437, 'colsample_bytree': 0.6796080331100328, 'reg_alpha': 4.405619048542754, 'reg_lambda': 6.936454882781253}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  70%|████████████████████████████▏           | 282/400 [28:50<12:10,  6.19s/it]

[I 2026-05-25 17:03:06,846] Trial 285 pruned.

Best trial: 264. Best value: 0.950122:  71%|████████████████████████████▎           | 283/400 [28:56<12:08,  6.23s/it]

[I 2026-05-25 17:03:13,168] Trial 281 finished with value: 0.9501121532259112 and parameters: {'n_estimators': 297, 'learning_rate': 0.04999821502989651, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 202, 'subsample': 0.854914466488019, 'colsample_bytree': 0.6304421058382159, 'reg_alpha': 8.663161246508137, 'reg_lambda': 4.984653216073373}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  71%|████████████████████████████▍           | 284/400 [28:58<09:29,  4.91s/it]

[I 2026-05-25 17:03:14,702] Trial 282 finished with value: 0.9501082216308501 and parameters: {'n_estimators': 297, 'learning_rate': 0.049314411558717665, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 199, 'subsample': 0.8248596859330464, 'colsample_bytree': 0.6371555222120782, 'reg_alpha': 4.665554234970988, 'reg_lambda': 6.208035428708284}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  71%|████████████████████████████▌           | 285/400 [28:58<07:01,  3.67s/it]

[I 2026-05-25 17:03:15,249] Trial 283 finished with value: 0.9501196781664696 and parameters: {'n_estimators': 299, 'learning_rate': 0.04453273790355554, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 200, 'subsample': 0.8267535235861511, 'colsample_bytree': 0.6352367404707462, 'reg_alpha': 4.726464667781602, 'reg_lambda': 8.644785179158314}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  72%|████████████████████████████▌           | 286/400 [29:09<10:53,  5.73s/it]

[I 2026-05-25 17:03:26,052] Trial 284 finished with value: 0.950108155620599 and parameters: {'n_estimators': 299, 'learning_rate': 0.04983050636581021, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 140, 'subsample': 0.8374767364742415, 'colsample_bytree': 0.632902661961753, 'reg_alpha': 4.588364713815616, 'reg_lambda': 9.81575426328805}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 264. Best value: 0.950122:  72%|████████████████████████████▋           | 287/400 [29:17<11:41,  6.21s/it]

[I 2026-05-25 17:03:33,380] Trial 289 finished with value: 0.9500747881753151 and parameters: {'n_estimators': 132, 'learning_rate': 0.044689027690415495, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 141, 'subsample': 0.8094479026207517, 'colsample_bytree': 0.6758911441416097, 'reg_alpha': 9.166687900017765, 'reg_lambda': 1.4758369146519315}. Best is trial 264 with value: 0.9501217147145968.

Best trial: 286. Best value: 0.950125:  72%|████████████████████████████▊           | 288/400 [29:18<08:49,  4.73s/it]

[I 2026-05-25 17:03:34,605] Trial 286 finished with value: 0.9501246423366506 and parameters: {'n_estimators': 300, 'learning_rate': 0.04460625592803928, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 143, 'subsample': 0.8581353567696219, 'colsample_bytree': 0.6751232937489222, 'reg_alpha': 9.171164160128546, 'reg_lambda': 1.523737456441205}. Best is trial 286 with value: 0.9501246423366506.

Best trial: 287. Best value: 0.950125:  72%|████████████████████████████▉           | 289/400 [29:24<09:43,  5.26s/it]

[I 2026-05-25 17:03:41,120] Trial 287 finished with value: 0.950124856169478 and parameters: {'n_estimators': 297, 'learning_rate': 0.0445850002648349, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 142, 'subsample': 0.8266384653021891, 'colsample_bytree': 0.6572010325519047, 'reg_alpha': 9.038880464820691, 'reg_lambda': 1.5268153771055861}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  72%|█████████████████████████████           | 290/400 [29:32<10:53,  5.94s/it]

[I 2026-05-25 17:03:48,681] Trial 288 finished with value: 0.9501069174876993 and parameters: {'n_estimators': 283, 'learning_rate': 0.04441187561318956, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 142, 'subsample': 0.8227822255251442, 'colsample_bytree': 0.6740487110464793, 'reg_alpha': 1.0004244612318238, 'reg_lambda': 1.3610674124283173}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  73%|█████████████████████████████           | 291/400 [29:48<16:15,  8.95s/it]

[I 2026-05-25 17:04:04,702] Trial 290 finished with value: 0.950099317079238 and parameters: {'n_estimators': 280, 'learning_rate': 0.04491966165181297, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 226, 'subsample': 0.8340666937806118, 'colsample_bytree': 0.6769124989755132, 'reg_alpha': 1.024060821031857e-05, 'reg_lambda': 1.68207908586291}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  73%|█████████████████████████████▏          | 292/400 [29:54<14:22,  7.99s/it]

[I 2026-05-25 17:04:10,447] Trial 291 finished with value: 0.9501192739272323 and parameters: {'n_estimators': 280, 'learning_rate': 0.04465874493573001, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 192, 'subsample': 0.8320285371005856, 'colsample_bytree': 0.6274797549073488, 'reg_alpha': 3.140098035321726, 'reg_lambda': 9.741424171365097}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  73%|█████████████████████████████▎          | 293/400 [29:59<12:50,  7.20s/it]

[I 2026-05-25 17:04:15,772] Trial 297 finished with value: 0.9500062892800376 and parameters: {'n_estimators': 280, 'learning_rate': 0.04401192873149772, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 188, 'subsample': 0.8636664703023437, 'colsample_bytree': 0.6233558842695948, 'reg_alpha': 2.9166936478611696, 'reg_lambda': 3.2191185640809747}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  74%|█████████████████████████████▍          | 294/400 [29:59<09:05,  5.14s/it]

[I 2026-05-25 17:04:16,119] Trial 292 finished with value: 0.9501149788879196 and parameters: {'n_estimators': 282, 'learning_rate': 0.044454431187415905, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 137, 'subsample': 0.8048537891120867, 'colsample_bytree': 0.674217115945433, 'reg_alpha': 2.777835921286638, 'reg_lambda': 1.593101511994578}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  74%|█████████████████████████████▌          | 295/400 [30:09<11:09,  6.37s/it]

[I 2026-05-25 17:04:25,375] Trial 296 finished with value: 0.9501107871662372 and parameters: {'n_estimators': 281, 'learning_rate': 0.04433744197920895, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 136, 'subsample': 0.7991792843621172, 'colsample_bytree': 0.6241678676068458, 'reg_alpha': 3.082407189936709, 'reg_lambda': 8.41085758208371}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  74%|█████████████████████████████▌          | 296/400 [30:10<08:18,  4.79s/it]

[I 2026-05-25 17:04:26,454] Trial 293 finished with value: 0.9501052383951343 and parameters: {'n_estimators': 283, 'learning_rate': 0.04457300490008586, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 135, 'subsample': 0.8597510054948188, 'colsample_bytree': 0.6263994611889957, 'reg_alpha': 2.5370060866494737, 'reg_lambda': 11.801503227195948}. Best is trial 287 with value: 0.950124856169478.
[I 2026-05-25 17:04:26,483] Trial 294 finished with value: 0.9501173960385026 and parameters: {'n_estimators': 280, 'learning_rate': 0.045061025171318846, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 123, 'subsample': 0.8019647335939266, 'colsample_bytree': 0.6761597104001316, 'reg_alpha': 2.7163700670356117, 'reg_lambda': 1.4690221141068764}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  74%|█████████████████████████████▊          | 298/400 [30:11<04:55,  2.89s/it]

[I 2026-05-25 17:04:27,826] Trial 295 finished with value: 0.9501144424437384 and parameters: {'n_estimators': 281, 'learning_rate': 0.044548401940275116, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 189, 'subsample': 0.8751012243936704, 'colsample_bytree': 0.6791484928547982, 'reg_alpha': 2.8896899678209778, 'reg_lambda': 1.468283913340258}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  75%|█████████████████████████████▉          | 299/400 [30:29<11:04,  6.58s/it]

[I 2026-05-25 17:04:45,559] Trial 301 finished with value: 0.9501065820816667 and parameters: {'n_estimators': 200, 'learning_rate': 0.0425678731474971, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 157, 'subsample': 0.8639073536163178, 'colsample_bytree': 0.6599620634058232, 'reg_alpha': 9.25160994127728, 'reg_lambda': 10.376947914566822}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  75%|██████████████████████████████          | 300/400 [30:36<11:11,  6.72s/it]

[I 2026-05-25 17:04:52,682] Trial 300 finished with value: 0.9501111704205212 and parameters: {'n_estimators': 281, 'learning_rate': 0.04320211405082718, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 223, 'subsample': 0.8812274221915843, 'colsample_bytree': 0.6615352468401483, 'reg_alpha': 9.734967359346001, 'reg_lambda': 1.704059298629761}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  75%|██████████████████████████████          | 301/400 [30:37<08:27,  5.12s/it]

[I 2026-05-25 17:04:53,538] Trial 298 finished with value: 0.95011284490029 and parameters: {'n_estimators': 280, 'learning_rate': 0.04472147214309287, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 212, 'subsample': 0.878542943791116, 'colsample_bytree': 0.6268752406563142, 'reg_alpha': 2.9035830298562404, 'reg_lambda': 3.247277080616949}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  76%|██████████████████████████████▏         | 302/400 [30:37<06:09,  3.77s/it]

[I 2026-05-25 17:04:53,818] Trial 299 finished with value: 0.9501149719422985 and parameters: {'n_estimators': 283, 'learning_rate': 0.044431023161265404, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 226, 'subsample': 0.8717393869655649, 'colsample_bytree': 0.6253986361842432, 'reg_alpha': 3.0413076812476163, 'reg_lambda': 3.151265963065524}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  76%|██████████████████████████████▎         | 303/400 [30:47<08:48,  5.44s/it]

[I 2026-05-25 17:05:03,447] Trial 306 finished with value: 0.9499589066961777 and parameters: {'n_estimators': 198, 'learning_rate': 0.04177568452355789, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 153, 'subsample': 0.8183691935471438, 'colsample_bytree': 0.6594700918964566, 'reg_alpha': 10.034261692887146, 'reg_lambda': 13.908457567788096}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  76%|██████████████████████████████▍         | 304/400 [31:03<13:57,  8.72s/it]

[I 2026-05-25 17:05:20,224] Trial 309 finished with value: 0.9500380667897023 and parameters: {'n_estimators': 290, 'learning_rate': 0.04154049684317409, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 122, 'subsample': 0.8153912472203664, 'colsample_bytree': 0.6575615832622319, 'reg_alpha': 7.267720151509319, 'reg_lambda': 15.73732667974126}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  76%|██████████████████████████████▌         | 305/400 [31:05<10:21,  6.54s/it]

[I 2026-05-25 17:05:21,495] Trial 302 finished with value: 0.950112505498352 and parameters: {'n_estimators': 289, 'learning_rate': 0.04191568209869279, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 154, 'subsample': 0.8673063518083967, 'colsample_bytree': 0.6620949203392609, 'reg_alpha': 2.675526349254982, 'reg_lambda': 3.1304020510007526}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  76%|██████████████████████████████▌         | 306/400 [31:10<09:41,  6.18s/it]

[I 2026-05-25 17:05:26,806] Trial 303 finished with value: 0.9501202466917359 and parameters: {'n_estimators': 288, 'learning_rate': 0.042259802317983146, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 132, 'subsample': 0.8790209960061233, 'colsample_bytree': 0.6207009037691399, 'reg_alpha': 9.797770965542309, 'reg_lambda': 10.753884172142971}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  77%|██████████████████████████████▋         | 307/400 [31:14<08:31,  5.50s/it]

[I 2026-05-25 17:05:30,687] Trial 304 finished with value: 0.9501052449958213 and parameters: {'n_estimators': 290, 'learning_rate': 0.04232979389033553, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 132, 'subsample': 0.8142004104633508, 'colsample_bytree': 0.6190177407378296, 'reg_alpha': 3.2085760918135913, 'reg_lambda': 1.6424034067704016}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  77%|██████████████████████████████▊         | 308/400 [31:20<08:42,  5.68s/it]

[I 2026-05-25 17:05:36,804] Trial 305 finished with value: 0.9501187862967638 and parameters: {'n_estimators': 289, 'learning_rate': 0.04229155894061746, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 131, 'subsample': 0.8725283519420775, 'colsample_bytree': 0.6600225025907079, 'reg_alpha': 9.467835059699675, 'reg_lambda': 11.095123294711893}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  77%|██████████████████████████████▉         | 309/400 [31:25<08:22,  5.52s/it]

[I 2026-05-25 17:05:41,916] Trial 307 finished with value: 0.9501100798244047 and parameters: {'n_estimators': 289, 'learning_rate': 0.04158954256997402, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 122, 'subsample': 0.821922181124182, 'colsample_bytree': 0.6630318768010718, 'reg_alpha': 7.866096299621352, 'reg_lambda': 15.213810593476659}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  78%|███████████████████████████████         | 310/400 [31:30<07:50,  5.23s/it]

[I 2026-05-25 17:05:46,477] Trial 308 finished with value: 0.9501166418083521 and parameters: {'n_estimators': 289, 'learning_rate': 0.04209115739556203, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 154, 'subsample': 0.8179078960212542, 'colsample_bytree': 0.6574786725369206, 'reg_alpha': 7.435855617904223, 'reg_lambda': 2.9278986556626956}. Best is trial 287 with value: 0.950124856169478.
[I 2026-05-25 17:05:46,507] Trial 312 finished with value: 0.9500393331630648 and parameters: {'n_estimators': 290, 'learning_rate': 0.04163542822775019, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 179, 'subsample': 0.7779497973993675, 'colsample_bytree': 0.6580033589006173, 'reg_alpha': 7.0445193426015, 'reg_lambda': 3.282555288573178}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  78%|███████████████████████████████▏        | 312/400 [31:46<09:41,  6.61s/it]

[I 2026-05-25 17:06:02,939] Trial 310 finished with value: 0.950117918670456 and parameters: {'n_estimators': 290, 'learning_rate': 0.042021972797277145, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 121, 'subsample': 0.8209986157005758, 'colsample_bytree': 0.6612550769165004, 'reg_alpha': 7.245419029200878, 'reg_lambda': 14.281140498910313}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  78%|███████████████████████████████▎        | 313/400 [31:58<11:38,  8.03s/it]

[I 2026-05-25 17:06:15,287] Trial 313 finished with value: 0.9501096814173774 and parameters: {'n_estimators': 290, 'learning_rate': 0.041590053206179235, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 123, 'subsample': 0.8287114826940605, 'colsample_bytree': 0.6594378577339101, 'reg_alpha': 7.1244497692275734, 'reg_lambda': 14.452946868881686}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  78%|███████████████████████████████▍        | 314/400 [32:01<09:33,  6.67s/it]

[I 2026-05-25 17:06:18,118] Trial 314 finished with value: 0.9501123339775942 and parameters: {'n_estimators': 289, 'learning_rate': 0.04170565430588699, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 179, 'subsample': 0.7820565305229609, 'colsample_bytree': 0.6610151885992104, 'reg_alpha': 6.878345018835753, 'reg_lambda': 1.6683521886729749}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  79%|███████████████████████████████▌        | 315/400 [32:02<07:00,  4.95s/it]

[I 2026-05-25 17:06:18,436] Trial 318 finished with value: 0.9500901012590207 and parameters: {'n_estimators': 159, 'learning_rate': 0.046575458982781974, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 112, 'subsample': 0.794120554520735, 'colsample_bytree': 0.6169191607442944, 'reg_alpha': 15.811688814400664, 'reg_lambda': 8.615280884170826}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  79%|███████████████████████████████▌        | 316/400 [32:11<08:32,  6.11s/it]

[I 2026-05-25 17:06:27,536] Trial 311 finished with value: 0.9500686471530363 and parameters: {'n_estimators': 288, 'learning_rate': 0.02042597871082228, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 124, 'subsample': 0.8168378676388894, 'colsample_bytree': 0.6144061133000122, 'reg_alpha': 6.404656256086236, 'reg_lambda': 3.55485423151247}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  79%|███████████████████████████████▋        | 317/400 [32:23<10:50,  7.84s/it]

[I 2026-05-25 17:06:39,703] Trial 316 finished with value: 0.9501135179470317 and parameters: {'n_estimators': 293, 'learning_rate': 0.046732710319960985, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 130, 'subsample': 0.8303804125732391, 'colsample_bytree': 0.6122381410912948, 'reg_alpha': 15.14078455428933, 'reg_lambda': 0.9413815123056333}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  80%|███████████████████████████████▊        | 318/400 [32:31<10:53,  7.97s/it]

[I 2026-05-25 17:06:47,986] Trial 315 finished with value: 0.9500743503721782 and parameters: {'n_estimators': 290, 'learning_rate': 0.020878145480261262, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 108, 'subsample': 0.7754590292009992, 'colsample_bytree': 0.6143681153258099, 'reg_alpha': 15.806376077570404, 'reg_lambda': 0.948767243377318}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  80%|███████████████████████████████▉        | 319/400 [32:33<08:22,  6.20s/it]

[I 2026-05-25 17:06:49,944] Trial 317 finished with value: 0.9501100755202543 and parameters: {'n_estimators': 294, 'learning_rate': 0.041362188762603065, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 124, 'subsample': 0.8980128950701984, 'colsample_bytree': 0.666056603592704, 'reg_alpha': 14.242701673644508, 'reg_lambda': 8.673410795999933}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  80%|████████████████████████████████        | 320/400 [32:45<10:41,  8.02s/it]

[I 2026-05-25 17:07:02,282] Trial 320 finished with value: 0.950115652753872 and parameters: {'n_estimators': 293, 'learning_rate': 0.04036679641700168, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 126, 'subsample': 0.8973745610208103, 'colsample_bytree': 0.6169110491465751, 'reg_alpha': 16.25041584032074, 'reg_lambda': 9.547071169727671}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  80%|████████████████████████████████        | 321/400 [32:47<08:04,  6.14s/it]

[I 2026-05-25 17:07:03,959] Trial 322 finished with value: 0.9501203561966636 and parameters: {'n_estimators': 294, 'learning_rate': 0.04641606757041639, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 113, 'subsample': 0.8879835465045542, 'colsample_bytree': 0.6092905342406639, 'reg_alpha': 15.54220418443464, 'reg_lambda': 9.824885860928207}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  80%|████████████████████████████████▏       | 322/400 [32:48<05:52,  4.52s/it]

[I 2026-05-25 17:07:04,683] Trial 319 finished with value: 0.9501217232310125 and parameters: {'n_estimators': 294, 'learning_rate': 0.04076539092911413, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 124, 'subsample': 0.8998407634881465, 'colsample_bytree': 0.6166695668453341, 'reg_alpha': 16.02277617563202, 'reg_lambda': 9.515125821338208}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  81%|████████████████████████████████▎       | 323/400 [32:51<05:08,  4.01s/it]

[I 2026-05-25 17:07:07,461] Trial 321 finished with value: 0.9501110468714125 and parameters: {'n_estimators': 294, 'learning_rate': 0.04154473284206043, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 127, 'subsample': 0.8966691915819409, 'colsample_bytree': 0.6692602672398715, 'reg_alpha': 16.650901651638122, 'reg_lambda': 8.174466942884653}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  81%|████████████████████████████████▍       | 324/400 [33:05<08:55,  7.04s/it]

[I 2026-05-25 17:07:21,617] Trial 323 finished with value: 0.9501185384453008 and parameters: {'n_estimators': 294, 'learning_rate': 0.04012683762992746, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 109, 'subsample': 0.8302322849348885, 'colsample_bytree': 0.6039241507511535, 'reg_alpha': 15.536401483463106, 'reg_lambda': 8.437361201329978}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  81%|████████████████████████████████▌       | 325/400 [33:19<11:29,  9.19s/it]

[I 2026-05-25 17:07:35,840] Trial 324 finished with value: 0.9500799488968259 and parameters: {'n_estimators': 295, 'learning_rate': 0.02398775493660441, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 128, 'subsample': 0.807638785278566, 'colsample_bytree': 0.615251753765032, 'reg_alpha': 15.930216106670079, 'reg_lambda': 11.322055351171795}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  82%|████████████████████████████████▌       | 326/400 [33:21<08:41,  7.04s/it]

[I 2026-05-25 17:07:37,863] Trial 326 finished with value: 0.9501133116320695 and parameters: {'n_estimators': 300, 'learning_rate': 0.04081726621090051, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 129, 'subsample': 0.8014747372967304, 'colsample_bytree': 0.6686921764114445, 'reg_alpha': 15.817828706968548, 'reg_lambda': 21.074354459710428}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  82%|████████████████████████████████▋       | 327/400 [33:22<06:25,  5.28s/it]

[I 2026-05-25 17:07:39,037] Trial 325 finished with value: 0.9501105553348733 and parameters: {'n_estimators': 295, 'learning_rate': 0.03944978228535796, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 128, 'subsample': 0.8324382977153941, 'colsample_bytree': 0.6416400133721855, 'reg_alpha': 15.514505972728958, 'reg_lambda': 9.393522827576518}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  82%|████████████████████████████████▊       | 328/400 [33:32<07:50,  6.53s/it]

[I 2026-05-25 17:07:48,478] Trial 327 finished with value: 0.9501146986219412 and parameters: {'n_estimators': 294, 'learning_rate': 0.03976120343323677, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 130, 'subsample': 0.8930174475657588, 'colsample_bytree': 0.6724118389787833, 'reg_alpha': 14.90599738642813, 'reg_lambda': 22.138801832804315}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  82%|████████████████████████████████▉       | 329/400 [33:42<09:01,  7.62s/it]

[I 2026-05-25 17:07:58,634] Trial 328 finished with value: 0.950109238846297 and parameters: {'n_estimators': 296, 'learning_rate': 0.039367327834469064, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 149, 'subsample': 0.8907080820001011, 'colsample_bytree': 0.6704523403877312, 'reg_alpha': 9.622662936457503e-05, 'reg_lambda': 9.810885387178555}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  82%|█████████████████████████████████       | 330/400 [33:55<10:50,  9.29s/it]

[I 2026-05-25 17:08:11,828] Trial 329 finished with value: 0.9501093551596721 and parameters: {'n_estimators': 300, 'learning_rate': 0.039883729590990576, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 126, 'subsample': 0.8316831779428144, 'colsample_bytree': 0.6685102811718582, 'reg_alpha': 3.8593846816588777, 'reg_lambda': 11.098192925564627}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  83%|█████████████████████████████████       | 331/400 [33:57<08:00,  6.97s/it]

[I 2026-05-25 17:08:13,371] Trial 330 finished with value: 0.9501061417244644 and parameters: {'n_estimators': 300, 'learning_rate': 0.03976706973109416, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 147, 'subsample': 0.8853978263720089, 'colsample_bytree': 0.6706257830522528, 'reg_alpha': 4.036274017470927, 'reg_lambda': 20.355442579079774}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  83%|█████████████████████████████████▏      | 332/400 [34:02<07:31,  6.65s/it]

[I 2026-05-25 17:08:19,265] Trial 336 finished with value: 0.9497470659877397 and parameters: {'n_estimators': 299, 'learning_rate': 0.039840460705519824, 'max_depth': 1, 'num_leaves': 10, 'min_child_samples': 117, 'subsample': 0.9077881956088258, 'colsample_bytree': 0.6001360537651731, 'reg_alpha': 0.0019517004385048954, 'reg_lambda': 16.51501307780635}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  83%|█████████████████████████████████▎      | 333/400 [34:05<06:03,  5.43s/it]

[I 2026-05-25 17:08:21,853] Trial 331 finished with value: 0.9501165122848187 and parameters: {'n_estimators': 300, 'learning_rate': 0.03960364293641558, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 133, 'subsample': 0.8033805934852748, 'colsample_bytree': 0.6018299311634046, 'reg_alpha': 9.881826268279152, 'reg_lambda': 19.814807287131565}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  84%|█████████████████████████████████▍      | 334/400 [34:07<04:58,  4.53s/it]

[I 2026-05-25 17:08:24,281] Trial 332 finished with value: 0.9501085344917574 and parameters: {'n_estimators': 295, 'learning_rate': 0.03978580280917791, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 103, 'subsample': 0.8880858129536793, 'colsample_bytree': 0.642451769929989, 'reg_alpha': 10.500314156367716, 'reg_lambda': 11.90549524935028}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  84%|█████████████████████████████████▌      | 335/400 [34:08<03:29,  3.23s/it]

[I 2026-05-25 17:08:24,497] Trial 333 finished with value: 0.9501171692119567 and parameters: {'n_estimators': 297, 'learning_rate': 0.03982565955566396, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 117, 'subsample': 0.8884048280853455, 'colsample_bytree': 0.6007306546226404, 'reg_alpha': 19.650887820849125, 'reg_lambda': 12.112156714409245}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  84%|█████████████████████████████████▌      | 336/400 [34:13<04:01,  3.77s/it]

[I 2026-05-25 17:08:29,495] Trial 334 finished with value: 0.9501153138366896 and parameters: {'n_estimators': 299, 'learning_rate': 0.03947922536637703, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 148, 'subsample': 0.8921786970781738, 'colsample_bytree': 0.6043981964617114, 'reg_alpha': 10.843535774568545, 'reg_lambda': 10.51279997729529}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  84%|█████████████████████████████████▋      | 337/400 [34:29<07:58,  7.59s/it]

[I 2026-05-25 17:08:46,027] Trial 335 finished with value: 0.9501028239743622 and parameters: {'n_estimators': 300, 'learning_rate': 0.031169643294553958, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 116, 'subsample': 0.9069264325097567, 'colsample_bytree': 0.6057774814077953, 'reg_alpha': 7.931699250185064e-05, 'reg_lambda': 21.256194501938424}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  84%|█████████████████████████████████▊      | 338/400 [34:46<10:38, 10.30s/it]

[I 2026-05-25 17:09:02,641] Trial 338 finished with value: 0.9501160862662381 and parameters: {'n_estimators': 300, 'learning_rate': 0.03578963490989048, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 111, 'subsample': 0.8524026291079536, 'colsample_bytree': 0.6060710566722264, 'reg_alpha': 10.807998690755001, 'reg_lambda': 31.551273272315395}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  85%|█████████████████████████████████▉      | 339/400 [34:47<07:48,  7.69s/it]

[I 2026-05-25 17:09:04,240] Trial 337 finished with value: 0.9500373255168331 and parameters: {'n_estimators': 296, 'learning_rate': 0.016480388603346538, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 102, 'subsample': 0.8855284497773848, 'colsample_bytree': 0.6056294549986984, 'reg_alpha': 10.873492543969133, 'reg_lambda': 12.020782577989012}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  85%|██████████████████████████████████      | 340/400 [34:56<07:53,  7.90s/it]

[I 2026-05-25 17:09:12,616] Trial 339 finished with value: 0.9501189409835332 and parameters: {'n_estimators': 298, 'learning_rate': 0.036981380224135586, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 112, 'subsample': 0.9092483963700613, 'colsample_bytree': 0.688057560534043, 'reg_alpha': 20.831670171168113, 'reg_lambda': 18.82750679270817}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  85%|██████████████████████████████████      | 341/400 [35:03<07:25,  7.56s/it]

[I 2026-05-25 17:09:19,394] Trial 340 finished with value: 0.9501083748885362 and parameters: {'n_estimators': 285, 'learning_rate': 0.03632530352863031, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 115, 'subsample': 0.851154072180565, 'colsample_bytree': 0.6092687844323091, 'reg_alpha': 21.456633211005713, 'reg_lambda': 12.96314131943686}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  86%|██████████████████████████████████▏     | 342/400 [35:07<06:26,  6.66s/it]

[I 2026-05-25 17:09:23,976] Trial 341 finished with value: 0.9501236351628389 and parameters: {'n_estimators': 284, 'learning_rate': 0.045795922926639886, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 111, 'subsample': 0.9095184098477604, 'colsample_bytree': 0.602731933943914, 'reg_alpha': 10.898741533844081, 'reg_lambda': 28.624563506571693}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  86%|██████████████████████████████████▎     | 343/400 [35:13<06:04,  6.40s/it]

[I 2026-05-25 17:09:29,743] Trial 342 finished with value: 0.950122341091505 and parameters: {'n_estimators': 275, 'learning_rate': 0.045295159473941915, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 101, 'subsample': 0.9040578210532534, 'colsample_bytree': 0.6021879244711269, 'reg_alpha': 10.19478925042269, 'reg_lambda': 31.684155106541315}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  86%|██████████████████████████████████▍     | 344/400 [35:22<06:40,  7.15s/it]

[I 2026-05-25 17:09:38,661] Trial 346 finished with value: 0.9501115099022138 and parameters: {'n_estimators': 284, 'learning_rate': 0.03692727943807134, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 109, 'subsample': 0.9212019486111458, 'colsample_bytree': 0.604386600347038, 'reg_alpha': 23.125465672276917, 'reg_lambda': 30.86650255381086}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  86%|██████████████████████████████████▌     | 345/400 [35:25<05:31,  6.03s/it]

[I 2026-05-25 17:09:42,084] Trial 344 finished with value: 0.9500125310218765 and parameters: {'n_estimators': 285, 'learning_rate': 0.01634813507329165, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 104, 'subsample': 0.8527257602315288, 'colsample_bytree': 0.6108152360327604, 'reg_alpha': 21.842896690259536, 'reg_lambda': 6.798607834477412}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  86%|██████████████████████████████████▌     | 346/400 [35:27<04:22,  4.87s/it]

[I 2026-05-25 17:09:44,218] Trial 343 finished with value: 0.9501035219279863 and parameters: {'n_estimators': 285, 'learning_rate': 0.02928439634966834, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 103, 'subsample': 0.8486005947824466, 'colsample_bytree': 0.6057931738914173, 'reg_alpha': 10.420451960947558, 'reg_lambda': 5.942015318355947}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  87%|██████████████████████████████████▋     | 347/400 [35:28<03:17,  3.73s/it]

[I 2026-05-25 17:09:45,328] Trial 347 finished with value: 0.950112881459764 and parameters: {'n_estimators': 285, 'learning_rate': 0.036330515427828024, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 110, 'subsample': 0.9093121325907528, 'colsample_bytree': 0.6099404277580861, 'reg_alpha': 21.6690342891592, 'reg_lambda': 6.940956078940588}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  87%|██████████████████████████████████▊     | 348/400 [35:30<02:43,  3.14s/it]

[I 2026-05-25 17:09:47,076] Trial 345 finished with value: 0.9500261814259383 and parameters: {'n_estimators': 285, 'learning_rate': 0.01682508720260699, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 117, 'subsample': 0.8554569568089415, 'colsample_bytree': 0.6036327402682654, 'reg_alpha': 19.9655931323657, 'reg_lambda': 6.934076331806733}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  87%|██████████████████████████████████▉     | 349/400 [35:38<03:52,  4.56s/it]

[I 2026-05-25 17:09:54,931] Trial 348 finished with value: 0.9500736099810634 and parameters: {'n_estimators': 285, 'learning_rate': 0.03648525104058782, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 108, 'subsample': 0.9102722769195131, 'colsample_bytree': 0.6097092936406624, 'reg_alpha': 20.93013766631842, 'reg_lambda': 6.655640178988417}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  88%|███████████████████████████████████     | 350/400 [36:03<08:54, 10.68s/it]

[I 2026-05-25 17:10:19,910] Trial 350 finished with value: 0.9501077312935629 and parameters: {'n_estimators': 283, 'learning_rate': 0.035788560191178535, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 137, 'subsample': 0.9059622952244234, 'colsample_bytree': 0.6115968505939844, 'reg_alpha': 20.199280592929462, 'reg_lambda': 15.588020238961136}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  88%|███████████████████████████████████     | 351/400 [36:04<06:23,  7.82s/it]

[I 2026-05-25 17:10:21,057] Trial 349 finished with value: 0.9501181418840045 and parameters: {'n_estimators': 286, 'learning_rate': 0.03602256466272491, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 111, 'subsample': 0.9070001713286644, 'colsample_bytree': 0.609916679310125, 'reg_alpha': 22.30334623988606, 'reg_lambda': 6.812689054007485}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  88%|███████████████████████████████████▏    | 352/400 [36:12<06:13,  7.78s/it]

[I 2026-05-25 17:10:28,727] Trial 357 pruned.

Best trial: 287. Best value: 0.950125:  88%|███████████████████████████████████▎    | 353/400 [36:14<04:47,  6.11s/it]

[I 2026-05-25 17:10:30,929] Trial 351 finished with value: 0.9501121110828024 and parameters: {'n_estimators': 286, 'learning_rate': 0.036112016510851754, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 108, 'subsample': 0.9093175839664592, 'colsample_bytree': 0.6863337774291277, 'reg_alpha': 21.98274716855414, 'reg_lambda': 28.404764089636124}. Best is trial 287 with value: 0.950124856169478.

[I 2026-05-25 17:10:37,894] Trial 352 finished with value: 0.9501124172780215 and parameters: {'n_estimators': 286, 'learning_rate': 0.03655503746492312, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 108, 'subsample': 0.9193039508804326, 'colsample_bytree': 0.6912721692153487, 'reg_alpha': 23.64519168214118, 'reg_lambda': 7.036206747604778}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  89%|███████████████████████████████████▌    | 355/400 [36:21<03:23,  4.51s/it]

[I 2026-05-25 17:10:38,090] Trial 358 pruned.

Best trial: 287. Best value: 0.950125:  89%|███████████████████████████████████▌    | 356/400 [36:26<03:25,  4.66s/it]

[I 2026-05-25 17:10:43,088] Trial 353 finished with value: 0.950118252272655 and parameters: {'n_estimators': 286, 'learning_rate': 0.04336466570755807, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 105, 'subsample': 0.9119997863353624, 'colsample_bytree': 0.6856490052311177, 'reg_alpha': 28.907151365151858, 'reg_lambda': 36.827317059691204}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  89%|███████████████████████████████████▋    | 357/400 [36:31<03:21,  4.69s/it]

[I 2026-05-25 17:10:47,818] Trial 354 finished with value: 0.9501055213305214 and parameters: {'n_estimators': 275, 'learning_rate': 0.03244178694251246, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 92, 'subsample': 0.9251773184790816, 'colsample_bytree': 0.619458548817897, 'reg_alpha': 21.4125979977452, 'reg_lambda': 37.44470786098956}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  90%|███████████████████████████████████▊    | 358/400 [36:40<04:14,  6.05s/it]

[I 2026-05-25 17:10:57,070] Trial 355 finished with value: 0.9501192187152899 and parameters: {'n_estimators': 285, 'learning_rate': 0.04339534344798657, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 99, 'subsample': 0.9219650508817558, 'colsample_bytree': 0.6886275086442791, 'reg_alpha': 33.58000158801732, 'reg_lambda': 32.9771643330546}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  90%|███████████████████████████████████▉    | 359/400 [36:43<03:24,  4.99s/it]

[I 2026-05-25 17:10:59,589] Trial 356 finished with value: 0.9501185533882339 and parameters: {'n_estimators': 278, 'learning_rate': 0.043335337387136214, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 92, 'subsample': 0.9098105789850474, 'colsample_bytree': 0.6882579105508891, 'reg_alpha': 23.134847599120945, 'reg_lambda': 31.69531528497584}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  90%|████████████████████████████████████    | 360/400 [36:49<03:35,  5.39s/it]

[I 2026-05-25 17:11:05,884] Trial 359 finished with value: 0.9496067240493652 and parameters: {'n_estimators': 277, 'learning_rate': 0.009846041261071059, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 94, 'subsample': 0.9206297988525248, 'colsample_bytree': 0.6837440186480965, 'reg_alpha': 34.74187674291304, 'reg_lambda': 26.612366545983367}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  90%|████████████████████████████████████    | 361/400 [37:02<04:56,  7.61s/it]

[I 2026-05-25 17:11:18,692] Trial 360 finished with value: 0.9501104941958621 and parameters: {'n_estimators': 288, 'learning_rate': 0.043419090004958624, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 94, 'subsample': 0.9129712134955681, 'colsample_bytree': 0.6206338970399662, 'reg_alpha': 32.99958015135876, 'reg_lambda': 16.97394662912446}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  91%|████████████████████████████████████▎   | 363/400 [37:18<04:23,  7.13s/it]

[I 2026-05-25 17:11:34,716] Trial 361 finished with value: 0.9501164020790751 and parameters: {'n_estimators': 275, 'learning_rate': 0.043474315168218446, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 136, 'subsample': 0.9187187551336399, 'colsample_bytree': 0.6844225104312507, 'reg_alpha': 33.64318114428461, 'reg_lambda': 40.24253141361946}. Best is trial 287 with value: 0.950124856169478.
[I 2026-05-25 17:11:34,829] Trial 362 finished with value: 0.9500962678228182 and parameters: {'n_estimators': 275, 'learning_rate': 0.03428056326375448, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 112, 'subsample': 0.9217253450119435, 'colsample_bytree': 0.6211458941415461, 'reg_alpha': 33.24128049532253, 'reg_lambda': 53.402902001055196}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  91%|████████████████████████████████████▍   | 364/400 [37:24<04:06,  6.84s/it]

[I 2026-05-25 17:11:41,012] Trial 363 finished with value: 0.9501103960569643 and parameters: {'n_estimators': 275, 'learning_rate': 0.04336894746760456, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 109, 'subsample': 0.9284223882966641, 'colsample_bytree': 0.6208833405765936, 'reg_alpha': 37.4038315393518, 'reg_lambda': 29.815298233050164}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  91%|████████████████████████████████████▌   | 365/400 [37:30<03:53,  6.68s/it]

[I 2026-05-25 17:11:47,325] Trial 364 finished with value: 0.9500968065275132 and parameters: {'n_estimators': 275, 'learning_rate': 0.034322189737680635, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 96, 'subsample': 0.9189485962796435, 'colsample_bytree': 0.6215207074227191, 'reg_alpha': 39.74567866372049, 'reg_lambda': 51.70965620687158}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  92%|████████████████████████████████████▌   | 366/400 [37:31<02:45,  4.86s/it]

[I 2026-05-25 17:11:47,944] Trial 366 finished with value: 0.9500921378560439 and parameters: {'n_estimators': 277, 'learning_rate': 0.04309735474231955, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 98, 'subsample': 0.874028075096722, 'colsample_bytree': 0.6246622011740207, 'reg_alpha': 12.710893370263932, 'reg_lambda': 58.5530587584066}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  92%|████████████████████████████████████▋   | 367/400 [37:38<03:04,  5.58s/it]

[I 2026-05-25 17:11:55,191] Trial 365 finished with value: 0.950101181458925 and parameters: {'n_estimators': 278, 'learning_rate': 0.03199109477537763, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 92, 'subsample': 0.9178788001792947, 'colsample_bytree': 0.6215816582623249, 'reg_alpha': 12.16126802259918, 'reg_lambda': 31.621685361561568}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  92%|████████████████████████████████████▊   | 368/400 [37:45<03:05,  5.81s/it]

[I 2026-05-25 17:12:01,543] Trial 368 finished with value: 0.950114530792994 and parameters: {'n_estimators': 292, 'learning_rate': 0.043381369188387454, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 101, 'subsample': 0.9177272787997411, 'colsample_bytree': 0.6149544616447665, 'reg_alpha': 36.54019030113425, 'reg_lambda': 65.32327983000862}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  92%|████████████████████████████████████▉   | 369/400 [37:47<02:26,  4.74s/it]

[I 2026-05-25 17:12:03,771] Trial 369 finished with value: 0.950056244093574 and parameters: {'n_estimators': 277, 'learning_rate': 0.033317856820107, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 93, 'subsample': 0.918604620530436, 'colsample_bytree': 0.6208425735018448, 'reg_alpha': 49.80613853790414, 'reg_lambda': 30.151277237180253}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  92%|█████████████████████████████████████   | 370/400 [37:55<02:52,  5.75s/it]

[I 2026-05-25 17:12:11,903] Trial 367 finished with value: 0.9501082643667818 and parameters: {'n_estimators': 290, 'learning_rate': 0.03402576528474021, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 96, 'subsample': 0.9281531938016621, 'colsample_bytree': 0.6232261094831734, 'reg_alpha': 13.113789025710915, 'reg_lambda': 31.788064832238227}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  93%|█████████████████████████████████████   | 371/400 [37:59<02:28,  5.14s/it]

[I 2026-05-25 17:12:15,605] Trial 370 finished with value: 0.9501041712989556 and parameters: {'n_estimators': 277, 'learning_rate': 0.043110618143603806, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 94, 'subsample': 0.9164493844282882, 'colsample_bytree': 0.7005739003576164, 'reg_alpha': 37.903064652034516, 'reg_lambda': 57.50927816876847}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  93%|█████████████████████████████████████▏  | 372/400 [38:04<02:24,  5.15s/it]

[I 2026-05-25 17:12:20,767] Trial 371 finished with value: 0.9500874563201129 and parameters: {'n_estimators': 276, 'learning_rate': 0.03325121958216934, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 84, 'subsample': 0.9177805236105452, 'colsample_bytree': 0.6220621273558603, 'reg_alpha': 45.25160121893886, 'reg_lambda': 60.40445265470456}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  93%|█████████████████████████████████████▎  | 373/400 [38:22<04:01,  8.94s/it]

[I 2026-05-25 17:12:38,585] Trial 372 finished with value: 0.9500877215980387 and parameters: {'n_estimators': 275, 'learning_rate': 0.03300647672202223, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 101, 'subsample': 0.9164078102512255, 'colsample_bytree': 0.6961470555645721, 'reg_alpha': 42.81871982959813, 'reg_lambda': 28.611268000238947}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  94%|█████████████████████████████████████▍  | 374/400 [38:26<03:16,  7.57s/it]

[I 2026-05-25 17:12:42,926] Trial 374 finished with value: 0.9500824784913909 and parameters: {'n_estimators': 293, 'learning_rate': 0.04324798106786607, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 85, 'subsample': 0.9032001587826646, 'colsample_bytree': 0.7005893988230891, 'reg_alpha': 46.44094442364497, 'reg_lambda': 48.71628050653492}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  94%|█████████████████████████████████████▌  | 375/400 [38:32<02:59,  7.17s/it]

[I 2026-05-25 17:12:49,186] Trial 373 finished with value: 0.9500828379235724 and parameters: {'n_estimators': 279, 'learning_rate': 0.042868426711242406, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 87, 'subsample': 0.902966563295742, 'colsample_bytree': 0.700499427638078, 'reg_alpha': 67.08281308176171, 'reg_lambda': 25.531004211459607}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  94%|█████████████████████████████████████▌  | 376/400 [38:43<03:15,  8.14s/it]

[I 2026-05-25 17:12:59,583] Trial 376 finished with value: 0.9500902193403373 and parameters: {'n_estimators': 291, 'learning_rate': 0.04262080831351349, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 96, 'subsample': 0.8765602817401258, 'colsample_bytree': 0.6976685632711143, 'reg_alpha': 14.541119406274639, 'reg_lambda': 34.24455866807184}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  94%|█████████████████████████████████████▋  | 377/400 [38:45<02:23,  6.24s/it]

[I 2026-05-25 17:13:01,390] Trial 375 finished with value: 0.9500990162804849 and parameters: {'n_estimators': 294, 'learning_rate': 0.042826180791833014, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 97, 'subsample': 0.9016381871389971, 'colsample_bytree': 0.6372781335076734, 'reg_alpha': 50.00431971634544, 'reg_lambda': 71.8874280362705}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  94%|█████████████████████████████████████▊  | 378/400 [38:50<02:11,  5.97s/it]

[I 2026-05-25 17:13:06,723] Trial 377 finished with value: 0.950099583870708 and parameters: {'n_estimators': 293, 'learning_rate': 0.03822084055404149, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 86, 'subsample': 0.9357531944681317, 'colsample_bytree': 0.704536117691701, 'reg_alpha': 43.59333422106543, 'reg_lambda': 25.506209821895254}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  95%|█████████████████████████████████████▉  | 379/400 [38:57<02:12,  6.30s/it]

[I 2026-05-25 17:13:13,797] Trial 378 finished with value: 0.950090615212839 and parameters: {'n_estimators': 293, 'learning_rate': 0.03836739088192735, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 89, 'subsample': 0.9004494331414153, 'colsample_bytree': 0.6926342323068356, 'reg_alpha': 48.618483820552434, 'reg_lambda': 25.120851627365184}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  95%|██████████████████████████████████████  | 380/400 [39:04<02:13,  6.65s/it]

[I 2026-05-25 17:13:21,262] Trial 379 finished with value: 0.9501016056800395 and parameters: {'n_estimators': 293, 'learning_rate': 0.03795055799033689, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 102, 'subsample': 0.9049545315927283, 'colsample_bytree': 0.7024900207536049, 'reg_alpha': 41.53233825067715, 'reg_lambda': 20.283773196462406}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  95%|██████████████████████████████████████  | 381/400 [39:08<01:47,  5.68s/it]

[I 2026-05-25 17:13:24,683] Trial 380 finished with value: 0.9501084605023984 and parameters: {'n_estimators': 293, 'learning_rate': 0.03867601152185491, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 79, 'subsample': 0.9018196063884912, 'colsample_bytree': 0.701595532414311, 'reg_alpha': 16.40943790656069, 'reg_lambda': 21.356956785355255}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  96%|██████████████████████████████████████▏ | 382/400 [39:18<02:04,  6.92s/it]

[I 2026-05-25 17:13:34,526] Trial 381 finished with value: 0.9501029401608525 and parameters: {'n_estimators': 294, 'learning_rate': 0.037902374896409026, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 104, 'subsample': 0.9018302848611386, 'colsample_bytree': 0.7006242011785878, 'reg_alpha': 45.566170926199774, 'reg_lambda': 20.036378285117088}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  96%|██████████████████████████████████████▎ | 383/400 [39:20<01:35,  5.64s/it]

[I 2026-05-25 17:13:37,156] Trial 382 finished with value: 0.9501113387494202 and parameters: {'n_estimators': 293, 'learning_rate': 0.03799346369366634, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 81, 'subsample': 0.8983297875769006, 'colsample_bytree': 0.6320547547093885, 'reg_alpha': 15.692318611454935, 'reg_lambda': 91.30533032607669}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  96%|██████████████████████████████████████▍ | 384/400 [39:23<01:14,  4.66s/it]

[I 2026-05-25 17:13:39,513] Trial 383 finished with value: 0.9501148338029035 and parameters: {'n_estimators': 292, 'learning_rate': 0.03791939699879399, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 102, 'subsample': 0.8989710712101818, 'colsample_bytree': 0.6969959665724822, 'reg_alpha': 16.775832863428978, 'reg_lambda': 14.041916720163432}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  96%|██████████████████████████████████████▌ | 385/400 [39:42<02:15,  9.02s/it]

[I 2026-05-25 17:13:58,720] Trial 384 finished with value: 0.9501153821164283 and parameters: {'n_estimators': 293, 'learning_rate': 0.03851598399247184, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 85, 'subsample': 0.9007354993872053, 'colsample_bytree': 0.7019567701217289, 'reg_alpha': 16.482594096496257, 'reg_lambda': 20.81882638726351}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  96%|██████████████████████████████████████▌ | 386/400 [39:43<01:32,  6.58s/it]

[I 2026-05-25 17:13:59,599] Trial 385 finished with value: 0.9501151609652949 and parameters: {'n_estimators': 294, 'learning_rate': 0.038197048367182386, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 141, 'subsample': 0.9012422939483753, 'colsample_bytree': 0.638535167102444, 'reg_alpha': 26.61134039527123, 'reg_lambda': 20.154067168155017}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  97%|██████████████████████████████████████▋ | 387/400 [39:54<01:42,  7.85s/it]

[I 2026-05-25 17:14:10,425] Trial 386 finished with value: 0.950113955633142 and parameters: {'n_estimators': 292, 'learning_rate': 0.03858141444563143, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 105, 'subsample': 0.8780441516604869, 'colsample_bytree': 0.6350283824793403, 'reg_alpha': 16.06928161427956, 'reg_lambda': 19.51253928839337}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  97%|██████████████████████████████████████▊ | 388/400 [40:00<01:29,  7.44s/it]

[I 2026-05-25 17:14:16,907] Trial 387 finished with value: 0.9501155162575523 and parameters: {'n_estimators': 286, 'learning_rate': 0.0377761739857353, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 140, 'subsample': 0.9326297596495783, 'colsample_bytree': 0.6327474656851174, 'reg_alpha': 28.12257825426775, 'reg_lambda': 20.825311688189046}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  97%|██████████████████████████████████████▉ | 389/400 [40:06<01:16,  6.96s/it]

[I 2026-05-25 17:14:22,723] Trial 388 finished with value: 0.9501047960309534 and parameters: {'n_estimators': 286, 'learning_rate': 0.03775563717823359, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 142, 'subsample': 0.8384674821185781, 'colsample_bytree': 0.6303976620063536, 'reg_alpha': 0.009480998450811988, 'reg_lambda': 16.601798099436763}. Best is trial 287 with value: 0.950124856169478.
[I 2026-05-25 17:14:22,738] Trial 389 finished with value: 0.9501086194943197 and parameters: {'n_estimators': 286, 'learning_rate': 0.045499799937161446, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 141, 'subsample': 0.8388123976560453, 'colsample_bytree': 0.6392878552514493, 'reg_alpha': 0.013861588725766563, 'reg_lambda': 15.652968698638851}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  98%|███████████████████████████████████████ | 391/400 [40:12<00:45,  5.09s/it]

[I 2026-05-25 17:14:28,540] Trial 395 finished with value: 0.9500929436420206 and parameters: {'n_estimators': 173, 'learning_rate': 0.045809358770852765, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 141, 'subsample': 0.8397261478013915, 'colsample_bytree': 0.6001449023161054, 'reg_alpha': 28.270362781386705, 'reg_lambda': 8.637499338792098}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  98%|███████████████████████████████████████▏| 392/400 [40:16<00:38,  4.85s/it]

[I 2026-05-25 17:14:32,690] Trial 391 finished with value: 0.9501177871444814 and parameters: {'n_estimators': 286, 'learning_rate': 0.04535874204267811, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 143, 'subsample': 0.8363238295842486, 'colsample_bytree': 0.6299715413077603, 'reg_alpha': 27.571481437288195, 'reg_lambda': 15.662284776685512}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  98%|███████████████████████████████████████▎| 393/400 [40:17<00:27,  3.98s/it]

[I 2026-05-25 17:14:34,197] Trial 390 finished with value: 0.9501074740820172 and parameters: {'n_estimators': 287, 'learning_rate': 0.04582623435709388, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 104, 'subsample': 0.8344174804506761, 'colsample_bytree': 0.8286192073842302, 'reg_alpha': 17.771608738624607, 'reg_lambda': 1.2587718059246366e-05}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  98%|███████████████████████████████████████▍| 394/400 [40:21<00:22,  3.79s/it]

[I 2026-05-25 17:14:37,479] Trial 392 finished with value: 0.9501239371986822 and parameters: {'n_estimators': 286, 'learning_rate': 0.04673397863765046, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 137, 'subsample': 0.835187180836793, 'colsample_bytree': 0.6311746433083012, 'reg_alpha': 17.987558702521174, 'reg_lambda': 90.695530635781}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  99%|███████████████████████████████████████▌| 395/400 [40:23<00:16,  3.37s/it]

[I 2026-05-25 17:14:39,776] Trial 398 finished with value: 0.9500306664641954 and parameters: {'n_estimators': 111, 'learning_rate': 0.04573756218597977, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 117, 'subsample': 0.8301405951865398, 'colsample_bytree': 0.649425016282349, 'reg_alpha': 9.369139915133303, 'reg_lambda': 9.619294833470924}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  99%|███████████████████████████████████████▌| 396/400 [40:24<00:11,  2.79s/it]

[I 2026-05-25 17:14:41,118] Trial 393 finished with value: 0.9501000996251256 and parameters: {'n_estimators': 285, 'learning_rate': 0.04554457514023082, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 117, 'subsample': 0.8358511307430413, 'colsample_bytree': 0.6305331466332675, 'reg_alpha': 0.00037906241058521535, 'reg_lambda': 9.151642508248406}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  99%|███████████████████████████████████████▋| 397/400 [40:25<00:06,  2.17s/it]

[I 2026-05-25 17:14:41,767] Trial 394 finished with value: 0.9501159370956425 and parameters: {'n_estimators': 286, 'learning_rate': 0.045844046901297404, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 141, 'subsample': 0.838730362559848, 'colsample_bytree': 0.6396934564322847, 'reg_alpha': 26.485745115937053, 'reg_lambda': 8.99443312662752}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125: 100%|███████████████████████████████████████▊| 398/400 [40:31<00:06,  3.41s/it]

[I 2026-05-25 17:14:48,172] Trial 397 finished with value: 0.9501126895435823 and parameters: {'n_estimators': 285, 'learning_rate': 0.045967090239230936, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 113, 'subsample': 0.8386226627975651, 'colsample_bytree': 0.6293098417118342, 'reg_alpha': 0.0006096308730616138, 'reg_lambda': 8.754968483628737}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125: 100%|███████████████████████████████████████▉| 399/400 [40:32<00:02,  2.55s/it]

[I 2026-05-25 17:14:48,664] Trial 399 finished with value: 0.9500993756367541 and parameters: {'n_estimators': 283, 'learning_rate': 0.04605759095727158, 'max_depth': 4, 'num_leaves': 6, 'min_child_samples': 118, 'subsample': 0.8359544108751806, 'colsample_bytree': 0.6005173377489544, 'reg_alpha': 0.01590379040231663, 'reg_lambda': 9.2364013825848}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125: 100%|████████████████████████████████████████| 400/400 [40:32<00:00,  6.08s/it]

[I 2026-05-25 17:14:48,986] Trial 396 finished with value: 0.9501110300459077 and parameters: {'n_estimators': 285, 'learning_rate': 0.045538941600613905, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 133, 'subsample': 0.8362400214685676, 'colsample_bytree': 0.8304872008647101, 'reg_alpha': 26.29541388066824, 'reg_lambda': 9.2125971146953}. Best is trial 287 with value: 0.950124856169478.
Best trial score:
0.950124856169478

Best params:
{'n_estimators': 297, 'learning_rate': 0.0445850002648349, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 142, 'subsample': 0.8266384653021891, 'colsample_bytree': 0.6572010325519047, 'reg_alpha': 9.038880464820691, 'reg_lambda': 1.5268153771055861}

In [30]:
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=200, n_jobs=-1, show_progress_bar=True)

Best trial: 287. Best value: 0.950125:   0%|▏                                         | 1/200 [00:17<58:55, 17.77s/it]

[I 2026-05-25 17:16:35,812] Trial 404 pruned.

Best trial: 287. Best value: 0.950125:   1%|▍                                         | 2/200 [00:30<48:00, 14.55s/it]

[I 2026-05-25 17:16:48,129] Trial 409 finished with value: 0.9498337629231106 and parameters: {'n_estimators': 80, 'learning_rate': 0.04012169840323628, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 133, 'subsample': 0.8893044550869753, 'colsample_bytree': 0.6101449651333914, 'reg_alpha': 11.34043628122149, 'reg_lambda': 83.88357159692966}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   2%|▌                                       | 3/200 [01:17<1:36:57, 29.53s/it]

[I 2026-05-25 17:17:35,485] Trial 405 finished with value: 0.9501153941250597 and parameters: {'n_estimators': 281, 'learning_rate': 0.04105147877474378, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 133, 'subsample': 0.8851962365790177, 'colsample_bytree': 0.6527854413555808, 'reg_alpha': 12.236292149119688, 'reg_lambda': 86.52350488932251}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   2%|▊                                         | 4/200 [01:18<59:17, 18.15s/it]

[I 2026-05-25 17:17:36,187] Trial 408 finished with value: 0.9501166052476705 and parameters: {'n_estimators': 300, 'learning_rate': 0.04060003358315087, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 164, 'subsample': 0.8827788438497506, 'colsample_bytree': 0.611913435848227, 'reg_alpha': 12.324471092819461, 'reg_lambda': 89.86906682745855}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   3%|█▎                                        | 6/200 [01:20<26:50,  8.30s/it]

[I 2026-05-25 17:17:38,660] Trial 411 finished with value: 0.950123881180226 and parameters: {'n_estimators': 300, 'learning_rate': 0.04090368232604689, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 111, 'subsample': 0.892274406103953, 'colsample_bytree': 0.6122837261648587, 'reg_alpha': 11.408172619260728, 'reg_lambda': 42.71217811994539}. Best is trial 287 with value: 0.950124856169478.
[I 2026-05-25 17:17:38,819] Trial 406 finished with value: 0.9501211367935307 and parameters: {'n_estimators': 280, 'learning_rate': 0.04118378631379946, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 122, 'subsample': 0.8816576078761288, 'colsample_bytree': 0.6779841679650842, 'reg_alpha': 11.564850360462438, 'reg_lambda': 5.152608125256937}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   4%|█▍                                        | 7/200 [01:22<20:01,  6.23s/it]

[I 2026-05-25 17:17:40,788] Trial 403 finished with value: 0.9501126653190723 and parameters: {'n_estimators': 300, 'learning_rate': 0.04079127230300655, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 136, 'subsample': 0.8828605871489479, 'colsample_bytree': 0.646514669031841, 'reg_alpha': 10.762116105001102, 'reg_lambda': 96.15518978993572}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   4%|█▋                                        | 8/200 [01:23<13:58,  4.37s/it]

[I 2026-05-25 17:17:41,159] Trial 410 finished with value: 0.9501191996781098 and parameters: {'n_estimators': 299, 'learning_rate': 0.04023345928916796, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 73, 'subsample': 0.8870163312744405, 'colsample_bytree': 0.6106492754510603, 'reg_alpha': 11.452640609180051, 'reg_lambda': 4.702842890682351}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   4%|█▉                                        | 9/200 [01:26<12:58,  4.08s/it]

[I 2026-05-25 17:17:44,601] Trial 407 finished with value: 0.9501233076063406 and parameters: {'n_estimators': 300, 'learning_rate': 0.04189400267368998, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 134, 'subsample': 0.8853822588545464, 'colsample_bytree': 0.6792513004448505, 'reg_alpha': 11.41497208867709, 'reg_lambda': 90.74251358979521}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   5%|██                                       | 10/200 [01:26<09:08,  2.89s/it]

[I 2026-05-25 17:17:44,812] Trial 400 finished with value: 0.9501242861933694 and parameters: {'n_estimators': 300, 'learning_rate': 0.040949785329869995, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 135, 'subsample': 0.8885257730213101, 'colsample_bytree': 0.6814754843062152, 'reg_alpha': 10.488434288803823, 'reg_lambda': 4.57899445505797}. Best is trial 287 with value: 0.950124856169478.
[I 2026-05-25 17:17:44,815] Trial 401 finished with value: 0.9501177140155574 and parameters: {'n_estimators': 281, 'learning_rate': 0.04155404791146948, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 134, 'subsample': 0.8921433874360707, 'colsample_bytree': 0.6111759974525687, 'reg_alpha': 12.195444234275055, 'reg_lambda': 41.69510046594194}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   6%|██▍                                      | 12/200 [01:32<09:12,  2.94s/it]

[I 2026-05-25 17:17:50,817] Trial 402 finished with value: 0.9499949780857829 and parameters: {'n_estimators': 281, 'learning_rate': 0.014940421905344935, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 134, 'subsample': 0.8836401167808453, 'colsample_bytree': 0.6133901471531527, 'reg_alpha': 10.783325793255894, 'reg_lambda': 4.697310528534982}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   6%|██▋                                      | 13/200 [01:49<19:39,  6.31s/it]

[I 2026-05-25 17:18:07,208] Trial 412 finished with value: 0.9501134091465339 and parameters: {'n_estimators': 300, 'learning_rate': 0.04121944582301051, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 20, 'subsample': 0.8675787266063136, 'colsample_bytree': 0.6147254832871065, 'reg_alpha': 19.856319348510443, 'reg_lambda': 4.294989482936113}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   7%|██▊                                      | 14/200 [01:51<16:23,  5.29s/it]

[I 2026-05-25 17:18:09,604] Trial 413 finished with value: 0.9501213090389135 and parameters: {'n_estimators': 300, 'learning_rate': 0.0405521784962639, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 124, 'subsample': 0.8718974073652254, 'colsample_bytree': 0.653255342492562, 'reg_alpha': 10.046150626945224, 'reg_lambda': 4.624014897997931}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   8%|███                                      | 15/200 [02:31<45:07, 14.64s/it]

[I 2026-05-25 17:18:49,072] Trial 424 finished with value: 0.9498103752080826 and parameters: {'n_estimators': 300, 'learning_rate': 0.048058398419882166, 'max_depth': 1, 'num_leaves': 11, 'min_child_samples': 122, 'subsample': 0.8888727063320587, 'colsample_bytree': 0.6795075875176644, 'reg_alpha': 8.748242553640651, 'reg_lambda': 4.6792692696502165}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   8%|███▎                                     | 16/200 [02:39<39:26, 12.86s/it]

[I 2026-05-25 17:18:57,370] Trial 415 finished with value: 0.9501138843283574 and parameters: {'n_estimators': 300, 'learning_rate': 0.04824790842922268, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 110, 'subsample': 0.8469957178683746, 'colsample_bytree': 0.6786573728873738, 'reg_alpha': 17.858421249697685, 'reg_lambda': 5.084234840523123}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   8%|███▍                                     | 17/200 [02:41<30:08,  9.88s/it]

[I 2026-05-25 17:18:59,853] Trial 417 finished with value: 0.9501181777929512 and parameters: {'n_estimators': 300, 'learning_rate': 0.047467813688943934, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 121, 'subsample': 0.8681262471046391, 'colsample_bytree': 0.681988358649836, 'reg_alpha': 8.559010765661242, 'reg_lambda': 47.00485341747698}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:   9%|███▋                                     | 18/200 [02:42<21:38,  7.13s/it]

[I 2026-05-25 17:19:00,277] Trial 414 finished with value: 0.9501151749349537 and parameters: {'n_estimators': 297, 'learning_rate': 0.04090032436105782, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 71, 'subsample': 0.8235554959051442, 'colsample_bytree': 0.6790620783779452, 'reg_alpha': 21.248662553767403, 'reg_lambda': 4.77121397914204}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  10%|███▉                                     | 19/200 [02:43<16:00,  5.31s/it]

[I 2026-05-25 17:19:01,154] Trial 418 finished with value: 0.9501167429854152 and parameters: {'n_estimators': 300, 'learning_rate': 0.04794051250825215, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 122, 'subsample': 0.8674139613527426, 'colsample_bytree': 0.6782676934115933, 'reg_alpha': 9.350335332920231, 'reg_lambda': 4.11085182761907}. Best is trial 287 with value: 0.950124856169478.

Best trial: 287. Best value: 0.950125:  10%|████                                     | 20/200 [02:47<14:45,  4.92s/it]

[I 2026-05-25 17:19:05,158] Trial 421 finished with value: 0.9501192088516307 and parameters: {'n_estimators': 300, 'learning_rate': 0.04189086420763162, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 123, 'subsample': 0.872557582542555, 'colsample_bytree': 0.6810097923437466, 'reg_alpha': 8.750999030006723, 'reg_lambda': 4.103794756738464}. Best is trial 287 with value: 0.950124856169478.

Best trial: 420. Best value: 0.950128:  10%|████▎                                    | 21/200 [02:47<10:55,  3.66s/it]

[I 2026-05-25 17:19:05,857] Trial 420 finished with value: 0.9501277594483449 and parameters: {'n_estimators': 300, 'learning_rate': 0.041804167819467365, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 46, 'subsample': 0.8630687541337554, 'colsample_bytree': 0.6787381617284337, 'reg_alpha': 8.976119729871975, 'reg_lambda': 4.284718721723572}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  11%|████▌                                    | 22/200 [02:48<08:31,  2.87s/it]

[I 2026-05-25 17:19:06,863] Trial 422 finished with value: 0.9501152362560588 and parameters: {'n_estimators': 300, 'learning_rate': 0.04788337327507815, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 54, 'subsample': 0.8687003815371213, 'colsample_bytree': 0.6797682613202105, 'reg_alpha': 9.20252256724253, 'reg_lambda': 4.485254367938466}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  12%|████▋                                    | 23/200 [02:52<09:00,  3.05s/it]

[I 2026-05-25 17:19:10,336] Trial 419 finished with value: 0.9500157551260318 and parameters: {'n_estimators': 298, 'learning_rate': 0.01510305461210008, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 74, 'subsample': 0.8658185048223224, 'colsample_bytree': 0.617050196179708, 'reg_alpha': 8.495520843796701, 'reg_lambda': 3.9305781446261006}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  12%|████▉                                    | 24/200 [02:53<07:12,  2.46s/it]

[I 2026-05-25 17:19:11,397] Trial 423 finished with value: 0.9501126997422059 and parameters: {'n_estimators': 299, 'learning_rate': 0.048064059456625625, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 69, 'subsample': 0.8634517692649961, 'colsample_bytree': 0.6768572028436364, 'reg_alpha': 8.737254411675657, 'reg_lambda': 3.509556254932402}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  12%|█████▏                                   | 25/200 [02:56<07:24,  2.54s/it]

[I 2026-05-25 17:19:14,118] Trial 416 finished with value: 0.9496105905573939 and parameters: {'n_estimators': 300, 'learning_rate': 0.00605316578522059, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 121, 'subsample': 0.8672705380546167, 'colsample_bytree': 0.6460906910475586, 'reg_alpha': 0.5011426332657084, 'reg_lambda': 41.02660011491801}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  13%|█████▎                                   | 26/200 [03:19<25:22,  8.75s/it]

[I 2026-05-25 17:19:37,417] Trial 425 finished with value: 0.950118550464453 and parameters: {'n_estimators': 300, 'learning_rate': 0.04724633358306116, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 119, 'subsample': 0.873714257159755, 'colsample_bytree': 0.6797935664609931, 'reg_alpha': 7.984718847140855, 'reg_lambda': 4.033894998502848}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  14%|█████▌                                   | 27/200 [03:53<47:15, 16.39s/it]

[I 2026-05-25 17:20:11,653] Trial 426 finished with value: 0.9501212011087258 and parameters: {'n_estimators': 297, 'learning_rate': 0.041713731111083036, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 126, 'subsample': 0.8730382081137055, 'colsample_bytree': 0.6780915798522695, 'reg_alpha': 8.476097923239823, 'reg_lambda': 4.394514112603163}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  14%|█████▋                                   | 28/200 [04:03<41:17, 14.40s/it]

[I 2026-05-25 17:20:21,413] Trial 430 finished with value: 0.9501198548926512 and parameters: {'n_estimators': 296, 'learning_rate': 0.04218019202462858, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 72, 'subsample': 0.8755941387866923, 'colsample_bytree': 0.6411357736885306, 'reg_alpha': 8.120153865148874, 'reg_lambda': 2.934106841546685}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  14%|█████▉                                   | 29/200 [04:03<29:06, 10.21s/it]

[I 2026-05-25 17:20:21,837] Trial 428 finished with value: 0.9501244811321085 and parameters: {'n_estimators': 295, 'learning_rate': 0.04208684378659606, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 126, 'subsample': 0.8721563534638378, 'colsample_bytree': 0.6750729040930699, 'reg_alpha': 8.332663508552768, 'reg_lambda': 3.5697665606425426}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  15%|██████▏                                  | 30/200 [04:07<23:06,  8.16s/it]

[I 2026-05-25 17:20:25,202] Trial 427 finished with value: 0.9501133813248736 and parameters: {'n_estimators': 296, 'learning_rate': 0.04188102069454782, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 68, 'subsample': 0.865037833445882, 'colsample_bytree': 0.6786509087039353, 'reg_alpha': 8.247714557806168, 'reg_lambda': 4.844152672813008}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  16%|██████▎                                  | 31/200 [04:07<16:16,  5.78s/it]

[I 2026-05-25 17:20:25,418] Trial 433 finished with value: 0.9501028228314313 and parameters: {'n_estimators': 296, 'learning_rate': 0.04191031152780055, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 44, 'subsample': 0.8764770513862441, 'colsample_bytree': 0.6718230150492042, 'reg_alpha': 0.4221347811098805, 'reg_lambda': 3.815703011569829}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  16%|██████▌                                  | 32/200 [04:09<12:59,  4.64s/it]

[I 2026-05-25 17:20:27,413] Trial 431 finished with value: 0.9501071726951406 and parameters: {'n_estimators': 300, 'learning_rate': 0.04213915603609901, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 127, 'subsample': 0.877608959267388, 'colsample_bytree': 0.6439436486627838, 'reg_alpha': 0.4269338569909869, 'reg_lambda': 4.0816227629812625}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  16%|██████▊                                  | 33/200 [04:09<09:25,  3.39s/it]

[I 2026-05-25 17:20:27,863] Trial 432 finished with value: 0.9501171340254311 and parameters: {'n_estimators': 296, 'learning_rate': 0.0414438750888815, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 39, 'subsample': 0.8781471322740094, 'colsample_bytree': 0.6764931258334087, 'reg_alpha': 7.949317609326259, 'reg_lambda': 3.629531663281608}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  17%|██████▉                                  | 34/200 [04:11<07:33,  2.73s/it]

[I 2026-05-25 17:20:29,083] Trial 434 finished with value: 0.9501118793633456 and parameters: {'n_estimators': 295, 'learning_rate': 0.04149861512940457, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 128, 'subsample': 0.8747157022733475, 'colsample_bytree': 0.6710708756177715, 'reg_alpha': 13.603743672476892, 'reg_lambda': 3.275318062575284}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  18%|███████▏                                 | 35/200 [04:12<06:27,  2.35s/it]

[I 2026-05-25 17:20:30,530] Trial 435 finished with value: 0.9501130933206564 and parameters: {'n_estimators': 295, 'learning_rate': 0.04209876119903068, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 49, 'subsample': 0.8724931193741612, 'colsample_bytree': 0.6717514547397611, 'reg_alpha': 15.122190705048919, 'reg_lambda': 5.823514455405781}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  18%|███████▍                                 | 36/200 [04:16<07:52,  2.88s/it]

[I 2026-05-25 17:20:34,643] Trial 436 finished with value: 0.9501188953587155 and parameters: {'n_estimators': 296, 'learning_rate': 0.04184970340022255, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 127, 'subsample': 0.8772192183188575, 'colsample_bytree': 0.6727108253090992, 'reg_alpha': 13.896151182709682, 'reg_lambda': 5.472710520879663}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  18%|███████▌                                 | 37/200 [04:18<07:20,  2.70s/it]

[I 2026-05-25 17:20:36,938] Trial 429 finished with value: 0.949935690995779 and parameters: {'n_estimators': 300, 'learning_rate': 0.012305451455912943, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 69, 'subsample': 0.87284815064526, 'colsample_bytree': 0.8028414332951279, 'reg_alpha': 8.182919457253053, 'reg_lambda': 3.893140262461279}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  19%|███████▊                                 | 38/200 [04:41<23:40,  8.77s/it]

[I 2026-05-25 17:20:59,867] Trial 437 finished with value: 0.9501122759733883 and parameters: {'n_estimators': 294, 'learning_rate': 0.0416035653626236, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 46, 'subsample': 0.8799310741187271, 'colsample_bytree': 0.6880476431582889, 'reg_alpha': 13.78638876100558, 'reg_lambda': 6.476607210145005}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  20%|███████▉                                 | 39/200 [05:12<40:53, 15.24s/it]

[I 2026-05-25 17:21:30,193] Trial 438 finished with value: 0.9501219900520406 and parameters: {'n_estimators': 294, 'learning_rate': 0.04137514401592588, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 126, 'subsample': 0.8762511313697487, 'colsample_bytree': 0.6917009235480436, 'reg_alpha': 14.257715607595978, 'reg_lambda': 5.82244499296412}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  20%|████████▏                                | 40/200 [05:23<37:28, 14.05s/it]

[I 2026-05-25 17:21:41,482] Trial 440 finished with value: 0.9501139825123948 and parameters: {'n_estimators': 295, 'learning_rate': 0.040753227276186285, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 60, 'subsample': 0.8762360729732883, 'colsample_bytree': 0.6750126631008093, 'reg_alpha': 6.508377609580346, 'reg_lambda': 2.912024061757923}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  20%|████████▍                                | 41/200 [05:25<27:39, 10.44s/it]

[I 2026-05-25 17:21:43,481] Trial 439 finished with value: 0.9501124895252856 and parameters: {'n_estimators': 294, 'learning_rate': 0.041488139082739184, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 40, 'subsample': 0.8759847648607179, 'colsample_bytree': 0.6283535565636943, 'reg_alpha': 13.719433408787804, 'reg_lambda': 5.519842992908035}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  21%|████████▌                                | 42/200 [05:25<19:26,  7.38s/it]

[I 2026-05-25 17:21:43,738] Trial 442 finished with value: 0.950115338502575 and parameters: {'n_estimators': 294, 'learning_rate': 0.04027063615249464, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 27, 'subsample': 0.8777979064761136, 'colsample_bytree': 0.6900427687433041, 'reg_alpha': 6.523606715920157, 'reg_lambda': 6.344407190864462}. Best is trial 420 with value: 0.9501277594483449.
[I 2026-05-25 17:21:43,803] Trial 441 finished with value: 0.9501122653301681 and parameters: {'n_estimators': 294, 'learning_rate': 0.04078333192452257, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 58, 'subsample': 0.8787365010802421, 'colsample_bytree': 0.6883236942700375, 'reg_alpha': 6.534033522121516, 'reg_lambda': 6.17750154262925}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  22%|█████████                                | 44/200 [05:29<12:23,  4.77s/it]

[I 2026-05-25 17:21:47,182] Trial 444 finished with value: 0.9501188975927006 and parameters: {'n_estimators': 294, 'learning_rate': 0.040531701384895605, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 47, 'subsample': 0.8889747559076148, 'colsample_bytree': 0.6900714081819502, 'reg_alpha': 6.210398347684649, 'reg_lambda': 6.004635013639717}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  22%|█████████▏                               | 45/200 [05:34<12:42,  4.92s/it]

[I 2026-05-25 17:21:52,553] Trial 446 finished with value: 0.9498874855594271 and parameters: {'n_estimators': 291, 'learning_rate': 0.010956321576199947, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 125, 'subsample': 0.8928928918120745, 'colsample_bytree': 0.6916092866704101, 'reg_alpha': 6.539832919421426, 'reg_lambda': 7.279643784133342}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  23%|█████████▍                               | 46/200 [05:36<10:45,  4.19s/it]

[I 2026-05-25 17:21:54,692] Trial 447 finished with value: 0.9501205520146667 and parameters: {'n_estimators': 290, 'learning_rate': 0.04379403344993373, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 27, 'subsample': 0.8933385617614387, 'colsample_bytree': 0.6246683647229632, 'reg_alpha': 6.521573261878633, 'reg_lambda': 6.745512552213971}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  24%|█████████▋                               | 47/200 [05:37<08:30,  3.34s/it]

[I 2026-05-25 17:21:55,744] Trial 448 finished with value: 0.9501171477118415 and parameters: {'n_estimators': 289, 'learning_rate': 0.039933939628027874, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 146, 'subsample': 0.8917687447258759, 'colsample_bytree': 0.6920022908043276, 'reg_alpha': 6.869959943274057, 'reg_lambda': 5.6373257767572005}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  24%|█████████▊                               | 48/200 [05:38<06:20,  2.50s/it]

[I 2026-05-25 17:21:56,098] Trial 443 finished with value: 0.9499193419921127 and parameters: {'n_estimators': 295, 'learning_rate': 0.01168510719169233, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 62, 'subsample': 0.8788422797945177, 'colsample_bytree': 0.6282008262523299, 'reg_alpha': 6.423255144863197, 'reg_lambda': 5.843825012373679}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  24%|██████████                               | 49/200 [05:43<08:42,  3.46s/it]

[I 2026-05-25 17:22:01,958] Trial 445 finished with value: 0.9499513050971322 and parameters: {'n_estimators': 290, 'learning_rate': 0.012761858656849177, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 126, 'subsample': 0.8905860238616781, 'colsample_bytree': 0.6296805750193217, 'reg_alpha': 6.3034383921738355, 'reg_lambda': 6.319611482407176}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  25%|██████████▎                              | 50/200 [05:57<15:48,  6.33s/it]

[I 2026-05-25 17:22:15,304] Trial 449 finished with value: 0.9501182340345313 and parameters: {'n_estimators': 290, 'learning_rate': 0.039569072679940184, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 146, 'subsample': 0.8932924116566764, 'colsample_bytree': 0.6275200822799843, 'reg_alpha': 6.270468286110506, 'reg_lambda': 6.32496783859338}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  26%|██████████▍                              | 51/200 [06:03<15:25,  6.21s/it]

[I 2026-05-25 17:22:21,220] Trial 460 finished with value: 0.9497718745069406 and parameters: {'n_estimators': 49, 'learning_rate': 0.044207149430813955, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 26, 'subsample': 0.85794414560794, 'colsample_bytree': 0.6360747284005684, 'reg_alpha': 0.02422285586898749, 'reg_lambda': 7.731774445092839}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  26%|██████████▋                              | 52/200 [06:33<32:36, 13.22s/it]

[I 2026-05-25 17:22:51,203] Trial 450 finished with value: 0.9501179535910053 and parameters: {'n_estimators': 290, 'learning_rate': 0.03974966906115675, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 146, 'subsample': 0.86017773577434, 'colsample_bytree': 0.6909019382154639, 'reg_alpha': 5.887877566117501, 'reg_lambda': 0.0003039710395678142}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  27%|███████████                              | 54/200 [06:41<20:19,  8.35s/it]

[I 2026-05-25 17:22:59,734] Trial 452 finished with value: 0.9501163652881439 and parameters: {'n_estimators': 290, 'learning_rate': 0.044522439388934146, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 32, 'subsample': 0.8922912234717122, 'colsample_bytree': 0.63835270873314, 'reg_alpha': 5.973799096360535, 'reg_lambda': 64.55868963775411}. Best is trial 420 with value: 0.9501277594483449.
[I 2026-05-25 17:22:59,876] Trial 451 finished with value: 0.9501152305163283 and parameters: {'n_estimators': 291, 'learning_rate': 0.044106899060298674, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 125, 'subsample': 0.8621760236156838, 'colsample_bytree': 0.6946257590958702, 'reg_alpha': 6.166249880403009, 'reg_lambda': 6.155130968105438}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  28%|███████████▎                             | 55/200 [06:43<15:14,  6.31s/it]

[I 2026-05-25 17:23:01,378] Trial 455 finished with value: 0.9501088270953846 and parameters: {'n_estimators': 289, 'learning_rate': 0.04347432122956055, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 126, 'subsample': 0.8882617914995475, 'colsample_bytree': 0.6368198528484016, 'reg_alpha': 0.022964404973382348, 'reg_lambda': 56.51388132922232}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  28%|███████████▍                             | 56/200 [06:44<11:43,  4.88s/it]

[I 2026-05-25 17:23:02,923] Trial 454 finished with value: 0.950116959380605 and parameters: {'n_estimators': 289, 'learning_rate': 0.04449978684705024, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 147, 'subsample': 0.8590067377461928, 'colsample_bytree': 0.6895157391518606, 'reg_alpha': 9.716136183009354, 'reg_lambda': 59.34941412575558}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  28%|███████████▋                             | 57/200 [06:45<08:27,  3.55s/it]

[I 2026-05-25 17:23:03,339] Trial 453 finished with value: 0.9501234106108007 and parameters: {'n_estimators': 289, 'learning_rate': 0.04413585004132268, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 147, 'subsample': 0.8588950245503569, 'colsample_bytree': 0.6897551240335021, 'reg_alpha': 5.607520442928945, 'reg_lambda': 60.48157537188783}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  29%|███████████▉                             | 58/200 [06:51<10:34,  4.47s/it]

[I 2026-05-25 17:23:09,977] Trial 459 finished with value: 0.9501252839738221 and parameters: {'n_estimators': 289, 'learning_rate': 0.04411348153381528, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.8615970220741623, 'colsample_bytree': 0.6385483472862005, 'reg_alpha': 12.512558199025177, 'reg_lambda': 2.9754739475697396}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  30%|████████████                             | 59/200 [06:52<07:57,  3.38s/it]

[I 2026-05-25 17:23:10,812] Trial 457 finished with value: 0.9501204128521958 and parameters: {'n_estimators': 289, 'learning_rate': 0.04318838641685462, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 38, 'subsample': 0.8589836089908577, 'colsample_bytree': 0.6386088751918826, 'reg_alpha': 10.758355721344953, 'reg_lambda': 57.955466171005355}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  30%|████████████▎                            | 60/200 [06:54<06:55,  2.96s/it]

[I 2026-05-25 17:23:12,808] Trial 458 finished with value: 0.950126014983872 and parameters: {'n_estimators': 289, 'learning_rate': 0.04455669921873379, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 129, 'subsample': 0.8564722821180443, 'colsample_bytree': 0.6272359571892165, 'reg_alpha': 10.894686074392578, 'reg_lambda': 63.29377266145299}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  30%|████████████▌                            | 61/200 [06:56<05:54,  2.55s/it]

[I 2026-05-25 17:23:14,371] Trial 456 finished with value: 0.950123811719541 and parameters: {'n_estimators': 289, 'learning_rate': 0.04384518708646654, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 148, 'subsample': 0.8580646522223241, 'colsample_bytree': 0.6261758059493724, 'reg_alpha': 10.316241543163477, 'reg_lambda': 57.898118208524565}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  31%|████████████▋                            | 62/200 [07:15<17:38,  7.67s/it]

[I 2026-05-25 17:23:34,003] Trial 461 finished with value: 0.950115614000099 and parameters: {'n_estimators': 289, 'learning_rate': 0.044016910176600754, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 137, 'subsample': 0.8855567248930355, 'colsample_bytree': 0.6197072547231972, 'reg_alpha': 10.401398181629117, 'reg_lambda': 11.33916055739233}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  32%|████████████▉                            | 63/200 [07:19<14:28,  6.34s/it]

[I 2026-05-25 17:23:37,241] Trial 462 finished with value: 0.9501239716843353 and parameters: {'n_estimators': 290, 'learning_rate': 0.04424194442840158, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 34, 'subsample': 0.8604339320896905, 'colsample_bytree': 0.6413941702089234, 'reg_alpha': 10.307522605370448, 'reg_lambda': 97.77319723471457}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  32%|█████████████                            | 64/200 [07:50<31:09, 13.75s/it]

[I 2026-05-25 17:24:08,268] Trial 472 finished with value: 0.9500470553454259 and parameters: {'n_estimators': 282, 'learning_rate': 0.044986476369832946, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 36, 'subsample': 0.8560985419255476, 'colsample_bytree': 0.6652167819629563, 'reg_alpha': 13.450017224984952, 'reg_lambda': 92.59545356650258}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  32%|█████████████▎                           | 65/200 [07:50<21:53,  9.73s/it]

[I 2026-05-25 17:24:08,641] Trial 463 finished with value: 0.9501095639507009 and parameters: {'n_estimators': 287, 'learning_rate': 0.0440840406020331, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 115, 'subsample': 0.8579554007328669, 'colsample_bytree': 0.6403816701412596, 'reg_alpha': 0.09509827258041045, 'reg_lambda': 61.140022237837734}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  33%|█████████████▌                           | 66/200 [07:58<20:24,  9.14s/it]

[I 2026-05-25 17:24:16,393] Trial 466 finished with value: 0.9501147816108922 and parameters: {'n_estimators': 282, 'learning_rate': 0.044167380931346395, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 137, 'subsample': 0.8832349471922154, 'colsample_bytree': 0.6169245577877189, 'reg_alpha': 10.22955347709607, 'reg_lambda': 2.4997067883515296}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  34%|█████████████▋                           | 67/200 [08:00<15:38,  7.06s/it]

[I 2026-05-25 17:24:18,598] Trial 468 finished with value: 0.9501098469540418 and parameters: {'n_estimators': 282, 'learning_rate': 0.0367270724312829, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 158, 'subsample': 0.8838017602833536, 'colsample_bytree': 0.6204209454797207, 'reg_alpha': 10.42037463822917, 'reg_lambda': 71.01896133248937}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  34%|█████████████▉                           | 68/200 [08:01<11:28,  5.21s/it]

[I 2026-05-25 17:24:19,490] Trial 464 finished with value: 0.9501146403940209 and parameters: {'n_estimators': 287, 'learning_rate': 0.04396338934749437, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 38, 'subsample': 0.9613025089735991, 'colsample_bytree': 0.6241030329844277, 'reg_alpha': 10.232066669799226, 'reg_lambda': 48.265500551951234}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  35%|██████████████▎                          | 70/200 [08:02<06:16,  2.90s/it]

[I 2026-05-25 17:24:20,885] Trial 469 finished with value: 0.9501201010115633 and parameters: {'n_estimators': 288, 'learning_rate': 0.044620242588256906, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 28, 'subsample': 0.8577230500441295, 'colsample_bytree': 0.6541395476400959, 'reg_alpha': 11.287040934524155, 'reg_lambda': 96.35969842351095}. Best is trial 420 with value: 0.9501277594483449.
[I 2026-05-25 17:24:21,030] Trial 465 finished with value: 0.950114607727701 and parameters: {'n_estimators': 281, 'learning_rate': 0.043968739970005756, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 138, 'subsample': 0.9574956059126924, 'colsample_bytree': 0.6186551860531865, 'reg_alpha': 9.881572086264594, 'reg_lambda': 2.9168255050486724}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  36%|██████████████▌                          | 71/200 [08:06<06:20,  2.95s/it]

[I 2026-05-25 17:24:24,123] Trial 470 finished with value: 0.95011818880941 and parameters: {'n_estimators': 282, 'learning_rate': 0.04385703224656766, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 21, 'subsample': 0.8531954817586108, 'colsample_bytree': 0.643684657386187, 'reg_alpha': 10.616642891181037, 'reg_lambda': 75.97811471372732}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  36%|██████████████▊                          | 72/200 [08:09<06:50,  3.20s/it]

[I 2026-05-25 17:24:27,929] Trial 467 finished with value: 0.9501035505979848 and parameters: {'n_estimators': 281, 'learning_rate': 0.0355171738462404, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 34, 'subsample': 0.8865161667914648, 'colsample_bytree': 0.6180199882529512, 'reg_alpha': 9.837124364264032, 'reg_lambda': 2.920212600795365}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  36%|██████████████▉                          | 73/200 [08:11<06:00,  2.84s/it]

[I 2026-05-25 17:24:29,894] Trial 471 finished with value: 0.9501084384952687 and parameters: {'n_estimators': 283, 'learning_rate': 0.03562303495797585, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 36, 'subsample': 0.8569877943483613, 'colsample_bytree': 0.6201428393323394, 'reg_alpha': 0.003926179826289888, 'reg_lambda': 72.18802379548647}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  37%|███████████████▏                         | 74/200 [08:36<19:31,  9.29s/it]

[I 2026-05-25 17:24:54,271] Trial 474 finished with value: 0.9500188238503504 and parameters: {'n_estimators': 282, 'learning_rate': 0.018418903582852614, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 35, 'subsample': 0.8570830354001571, 'colsample_bytree': 0.6543152107955599, 'reg_alpha': 12.556656924396245, 'reg_lambda': 97.03440170652966}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  38%|███████████████▍                         | 75/200 [08:37<14:30,  6.97s/it]

[I 2026-05-25 17:24:55,811] Trial 473 finished with value: 0.950053050955653 and parameters: {'n_estimators': 282, 'learning_rate': 0.019232202383125906, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.8550236940668928, 'colsample_bytree': 0.6184561902016834, 'reg_alpha': 0.003880915569529221, 'reg_lambda': 55.64380313129659}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  38%|███████████████▌                         | 76/200 [08:55<20:52, 10.10s/it]

[I 2026-05-25 17:25:13,212] Trial 480 pruned.

Best trial: 420. Best value: 0.950128:  38%|███████████████▊                         | 77/200 [08:58<16:34,  8.08s/it]

[I 2026-05-25 17:25:16,603] Trial 481 finished with value: 0.9499988289816985 and parameters: {'n_estimators': 289, 'learning_rate': 0.03593533511231841, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.8607566857891324, 'colsample_bytree': 0.6545514665659498, 'reg_alpha': 16.927896631317644, 'reg_lambda': 70.05067426568294}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  39%|███████████████▉                         | 78/200 [08:59<12:20,  6.07s/it]

[I 2026-05-25 17:25:17,966] Trial 482 finished with value: 0.9500003991977926 and parameters: {'n_estimators': 289, 'learning_rate': 0.03614426461542967, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.8641067584830706, 'colsample_bytree': 0.6514879332385086, 'reg_alpha': 17.326152428718256, 'reg_lambda': 51.71986455984734}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  40%|████████████████▏                        | 79/200 [09:07<13:00,  6.45s/it]

[I 2026-05-25 17:25:25,281] Trial 475 finished with value: 0.9501045734897074 and parameters: {'n_estimators': 282, 'learning_rate': 0.03580664537436043, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 32, 'subsample': 0.8538454270342763, 'colsample_bytree': 0.6520421337546315, 'reg_alpha': 11.395604368882708, 'reg_lambda': 64.90362466040739}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  40%|████████████████▍                        | 80/200 [09:14<13:40,  6.84s/it]

[I 2026-05-25 17:25:33,040] Trial 476 finished with value: 0.9501073036510833 and parameters: {'n_estimators': 282, 'learning_rate': 0.0360166876291465, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 34, 'subsample': 0.8506604526187446, 'colsample_bytree': 0.6541507701510465, 'reg_alpha': 11.795599046532265, 'reg_lambda': 93.05675732406132}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  40%|████████████████▌                        | 81/200 [09:15<09:37,  4.86s/it]

[I 2026-05-25 17:25:33,282] Trial 477 finished with value: 0.9500992449937004 and parameters: {'n_estimators': 282, 'learning_rate': 0.036044968327690795, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 40, 'subsample': 0.8528995369481168, 'colsample_bytree': 0.6533887556283742, 'reg_alpha': 16.682086024307146, 'reg_lambda': 99.08958163245977}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  41%|████████████████▊                        | 82/200 [09:20<09:46,  4.97s/it]

[I 2026-05-25 17:25:38,525] Trial 478 finished with value: 0.950109171584663 and parameters: {'n_estimators': 288, 'learning_rate': 0.03563799540512131, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 32, 'subsample': 0.8600278140045586, 'colsample_bytree': 0.6553993058934692, 'reg_alpha': 16.47030939086305, 'reg_lambda': 95.93782322848223}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  42%|█████████████████                        | 83/200 [09:21<07:14,  3.72s/it]

[I 2026-05-25 17:25:39,306] Trial 479 finished with value: 0.95012017259569 and parameters: {'n_estimators': 289, 'learning_rate': 0.03849504673497879, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.8517933623229481, 'colsample_bytree': 0.651457105952217, 'reg_alpha': 16.039733118058894, 'reg_lambda': 66.61736357447727}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  42%|█████████████████▏                       | 84/200 [09:28<09:06,  4.72s/it]

[I 2026-05-25 17:25:46,351] Trial 483 finished with value: 0.9501154669023183 and parameters: {'n_estimators': 289, 'learning_rate': 0.03906134600877446, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 33, 'subsample': 0.8479067436753831, 'colsample_bytree': 0.6487641941052968, 'reg_alpha': 16.317593343557455, 'reg_lambda': 68.21089271092589}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  42%|█████████████████▍                       | 85/200 [09:29<07:10,  3.75s/it]

[I 2026-05-25 17:25:47,837] Trial 488 finished with value: 0.9499043267856205 and parameters: {'n_estimators': 93, 'learning_rate': 0.03861708326273944, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 152, 'subsample': 0.8472804468487347, 'colsample_bytree': 0.6651274387060924, 'reg_alpha': 17.706135744794665, 'reg_lambda': 47.41138563397056}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  43%|█████████████████▋                       | 86/200 [09:31<06:01,  3.17s/it]

[I 2026-05-25 17:25:49,675] Trial 484 finished with value: 0.9501166944223043 and parameters: {'n_estimators': 289, 'learning_rate': 0.038255620996908546, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.8483523352876545, 'colsample_bytree': 0.6519802312973911, 'reg_alpha': 18.046024718413605, 'reg_lambda': 60.24987599413066}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  44%|█████████████████▊                       | 87/200 [09:42<10:22,  5.51s/it]

[I 2026-05-25 17:26:00,615] Trial 489 finished with value: 0.9500380547871432 and parameters: {'n_estimators': 139, 'learning_rate': 0.03926457730348326, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 154, 'subsample': 0.868861430483193, 'colsample_bytree': 0.6433306707968498, 'reg_alpha': 17.511441462474156, 'reg_lambda': 46.29616843819377}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  44%|██████████████████                       | 88/200 [09:50<11:40,  6.25s/it]

[I 2026-05-25 17:26:08,635] Trial 487 finished with value: 0.9500200294176013 and parameters: {'n_estimators': 289, 'learning_rate': 0.038987716789333916, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 151, 'subsample': 0.8652890513952423, 'colsample_bytree': 0.6652825266672974, 'reg_alpha': 16.021076146406205, 'reg_lambda': 48.58201853551271}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  44%|██████████████████▏                      | 89/200 [09:51<08:39,  4.68s/it]

[I 2026-05-25 17:26:09,635] Trial 493 finished with value: 0.9499371054692141 and parameters: {'n_estimators': 95, 'learning_rate': 0.039503221462105144, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 151, 'subsample': 0.8663370739561098, 'colsample_bytree': 0.6447317017819993, 'reg_alpha': 8.066523435975878, 'reg_lambda': 40.488513116255525}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  45%|██████████████████▍                      | 90/200 [09:54<07:22,  4.02s/it]

[I 2026-05-25 17:26:12,117] Trial 485 finished with value: 0.949328375606945 and parameters: {'n_estimators': 290, 'learning_rate': 0.007435180362151774, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.8652902370261705, 'colsample_bytree': 0.6526925615576136, 'reg_alpha': 17.685236084419273, 'reg_lambda': 49.24391406631385}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  46%|██████████████████▋                      | 91/200 [09:55<06:03,  3.34s/it]

[I 2026-05-25 17:26:13,868] Trial 486 finished with value: 0.9501209832238029 and parameters: {'n_estimators': 289, 'learning_rate': 0.03889879598646362, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.8481975917273847, 'colsample_bytree': 0.6546035022189677, 'reg_alpha': 16.39516439247264, 'reg_lambda': 53.725980957890044}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  46%|██████████████████▊                      | 92/200 [10:18<16:34,  9.21s/it]

[I 2026-05-25 17:26:36,764] Trial 498 finished with value: 0.9500390986079623 and parameters: {'n_estimators': 118, 'learning_rate': 0.04637842452216904, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 45, 'subsample': 0.8661882633482939, 'colsample_bytree': 0.6352855799794285, 'reg_alpha': 8.051416676128149, 'reg_lambda': 48.553392551809594}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  46%|███████████████████                      | 93/200 [10:29<17:13,  9.66s/it]

[I 2026-05-25 17:26:47,468] Trial 490 finished with value: 0.9501178497758793 and parameters: {'n_estimators': 294, 'learning_rate': 0.03995428278323655, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.8647415186371087, 'colsample_bytree': 0.6678358584438121, 'reg_alpha': 15.97172306261599, 'reg_lambda': 40.52738719339339}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  47%|███████████████████▎                     | 94/200 [10:35<15:04,  8.53s/it]

[I 2026-05-25 17:26:53,380] Trial 499 finished with value: 0.9500778486747266 and parameters: {'n_estimators': 151, 'learning_rate': 0.045457574501287706, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 23, 'subsample': 0.8691504752863111, 'colsample_bytree': 0.6323125379999187, 'reg_alpha': 8.281932298458319, 'reg_lambda': 47.55590812869437}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  48%|███████████████████▍                     | 95/200 [10:38<11:51,  6.78s/it]

[I 2026-05-25 17:26:56,074] Trial 491 finished with value: 0.9501187642451162 and parameters: {'n_estimators': 294, 'learning_rate': 0.0389241478428855, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 150, 'subsample': 0.8690662983152517, 'colsample_bytree': 0.6671910353100159, 'reg_alpha': 18.315922477876512, 'reg_lambda': 43.216111661145455}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  48%|███████████████████▋                     | 96/200 [10:41<10:17,  5.93s/it]

[I 2026-05-25 17:27:00,033] Trial 492 finished with value: 0.9501185583432763 and parameters: {'n_estimators': 293, 'learning_rate': 0.03925348686330103, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 150, 'subsample': 0.8692156566793445, 'colsample_bytree': 0.6659804245403698, 'reg_alpha': 15.360171102038377, 'reg_lambda': 47.26369344201816}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  48%|███████████████████▉                     | 97/200 [10:45<09:02,  5.27s/it]

[I 2026-05-25 17:27:03,762] Trial 494 finished with value: 0.9501145209660351 and parameters: {'n_estimators': 294, 'learning_rate': 0.038906994557335164, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 151, 'subsample': 0.8674862294201457, 'colsample_bytree': 0.6669560940098928, 'reg_alpha': 5.077234682750338, 'reg_lambda': 46.72612683559289}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  49%|████████████████████                     | 98/200 [10:48<07:30,  4.42s/it]

[I 2026-05-25 17:27:06,177] Trial 495 finished with value: 0.9501156279466285 and parameters: {'n_estimators': 295, 'learning_rate': 0.040021886775483476, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 152, 'subsample': 0.8677910927008168, 'colsample_bytree': 0.664742408187105, 'reg_alpha': 8.208716186809172, 'reg_lambda': 43.90669657674789}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  50%|████████████████████▎                    | 99/200 [10:50<06:25,  3.81s/it]

[I 2026-05-25 17:27:08,578] Trial 496 finished with value: 0.9501011992013998 and parameters: {'n_estimators': 293, 'learning_rate': 0.03928477845469607, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 27, 'subsample': 0.8675401308676378, 'colsample_bytree': 0.6332415259365689, 'reg_alpha': 4.754546099012873, 'reg_lambda': 41.87226867342113}. Best is trial 420 with value: 0.9501277594483449.
[I 2026-05-25 17:27:08,616] Trial 497 finished with value: 0.9501140437658299 and parameters: {'n_estimators': 294, 'learning_rate': 0.04636427706521645, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 24, 'subsample': 0.8706987664454692, 'colsample_bytree': 0.6374568766066334, 'reg_alpha': 7.82067353143939, 'reg_lambda': 37.59393359495547}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  50%|████████████████████▏                   | 101/200 [11:10<10:57,  6.65s/it]

[I 2026-05-25 17:27:28,475] Trial 501 finished with value: 0.9501227565245696 and parameters: {'n_estimators': 294, 'learning_rate': 0.04631090149284826, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 49, 'subsample': 0.8701741263337347, 'colsample_bytree': 0.6324699349120034, 'reg_alpha': 7.89932795790975, 'reg_lambda': 42.907424332887466}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  51%|████████████████████▍                   | 102/200 [11:13<09:14,  5.66s/it]

[I 2026-05-25 17:27:31,162] Trial 500 finished with value: 0.9501220483130373 and parameters: {'n_estimators': 295, 'learning_rate': 0.045981019714187395, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 23, 'subsample': 0.8674381919745019, 'colsample_bytree': 0.6319863158334625, 'reg_alpha': 8.480275645481067, 'reg_lambda': 44.85479910960569}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  52%|████████████████████▌                   | 103/200 [11:14<07:16,  4.50s/it]

[I 2026-05-25 17:27:32,366] Trial 502 finished with value: 0.9501198267967684 and parameters: {'n_estimators': 295, 'learning_rate': 0.04629795991822276, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 24, 'subsample': 0.8720009340068198, 'colsample_bytree': 0.6694261439797482, 'reg_alpha': 4.799826027503483, 'reg_lambda': 42.421033646229205}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  52%|████████████████████▊                   | 104/200 [11:38<15:34,  9.74s/it]

[I 2026-05-25 17:27:56,143] Trial 507 finished with value: 0.950087405532196 and parameters: {'n_estimators': 181, 'learning_rate': 0.04218386241148945, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 140, 'subsample': 0.8471600019601897, 'colsample_bytree': 0.6827997463902932, 'reg_alpha': 12.148697391853503, 'reg_lambda': 65.5085141341412}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  52%|█████████████████████                   | 105/200 [11:39<11:38,  7.35s/it]

[I 2026-05-25 17:27:57,350] Trial 503 finished with value: 0.9501105739369864 and parameters: {'n_estimators': 295, 'learning_rate': 0.049788865908194584, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 23, 'subsample': 0.8669727880732822, 'colsample_bytree': 0.668409253960964, 'reg_alpha': 4.706404831278027, 'reg_lambda': 74.59171067689184}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  53%|█████████████████████▏                  | 106/200 [11:48<12:28,  7.96s/it]

[I 2026-05-25 17:28:06,816] Trial 504 finished with value: 0.9501115916066956 and parameters: {'n_estimators': 295, 'learning_rate': 0.04221027392683255, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 145, 'subsample': 0.8708047920727472, 'colsample_bytree': 0.6725805988349834, 'reg_alpha': 4.837078547020149, 'reg_lambda': 71.54381963611978}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  54%|█████████████████████▍                  | 107/200 [11:53<10:54,  7.03s/it]

[I 2026-05-25 17:28:11,587] Trial 505 finished with value: 0.9501065715054192 and parameters: {'n_estimators': 295, 'learning_rate': 0.04984504889600548, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 141, 'subsample': 0.8683700248339883, 'colsample_bytree': 0.7135005357586898, 'reg_alpha': 4.489507949660628, 'reg_lambda': 2.01653136995476}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  54%|█████████████████████▌                  | 108/200 [11:55<08:25,  5.49s/it]

[I 2026-05-25 17:28:13,357] Trial 514 finished with value: 0.9498167903621857 and parameters: {'n_estimators': 300, 'learning_rate': 0.04992560989916642, 'max_depth': 1, 'num_leaves': 10, 'min_child_samples': 143, 'subsample': 0.8449205540442751, 'colsample_bytree': 0.6822447921959929, 'reg_alpha': 0.20548347005423592, 'reg_lambda': 70.10023574807744}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  55%|█████████████████████▊                  | 109/200 [12:04<09:59,  6.59s/it]

[I 2026-05-25 17:28:22,568] Trial 506 finished with value: 0.9501152247193364 and parameters: {'n_estimators': 300, 'learning_rate': 0.0418038369011466, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 162, 'subsample': 0.8958890862338258, 'colsample_bytree': 0.7118349374409553, 'reg_alpha': 5.39738916882699, 'reg_lambda': 75.30508269597438}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  55%|██████████████████████                  | 110/200 [12:07<08:26,  5.62s/it]

[I 2026-05-25 17:28:25,892] Trial 508 finished with value: 0.9501136187787118 and parameters: {'n_estimators': 296, 'learning_rate': 0.04242755151123358, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 141, 'subsample': 0.895370612450218, 'colsample_bytree': 0.6828956392534915, 'reg_alpha': 5.031768377202076, 'reg_lambda': 2.0641181486962075}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  56%|██████████████████████▏                 | 111/200 [12:09<06:25,  4.33s/it]

[I 2026-05-25 17:28:27,171] Trial 509 finished with value: 0.9501193543963963 and parameters: {'n_estimators': 297, 'learning_rate': 0.042166939806561915, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 142, 'subsample': 0.8978981718129171, 'colsample_bytree': 0.6758495601511116, 'reg_alpha': 4.973296274523715, 'reg_lambda': 71.7092790280938}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 420. Best value: 0.950128:  56%|██████████████████████▍                 | 112/200 [12:13<06:24,  4.37s/it]

[I 2026-05-25 17:28:31,642] Trial 510 finished with value: 0.9501190804350197 and parameters: {'n_estimators': 300, 'learning_rate': 0.042171667193455255, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 139, 'subsample': 0.8447362126079481, 'colsample_bytree': 0.6002431664334371, 'reg_alpha': 11.948849053592904, 'reg_lambda': 2.174918076295138}. Best is trial 420 with value: 0.9501277594483449.

Best trial: 511. Best value: 0.950128:  56%|██████████████████████▌                 | 113/200 [12:16<05:38,  3.89s/it]

[I 2026-05-25 17:28:34,385] Trial 511 finished with value: 0.9501279251657385 and parameters: {'n_estimators': 300, 'learning_rate': 0.04228141700736481, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 159, 'subsample': 0.8958894136410026, 'colsample_bytree': 0.683066200227659, 'reg_alpha': 12.687979786072988, 'reg_lambda': 70.4091155037546}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  57%|██████████████████████▊                 | 114/200 [12:17<04:29,  3.13s/it]

[I 2026-05-25 17:28:35,744] Trial 518 pruned.

Best trial: 511. Best value: 0.950128:  57%|███████████████████████                 | 115/200 [12:30<08:27,  5.97s/it]

[I 2026-05-25 17:28:48,369] Trial 512 finished with value: 0.9501205857655544 and parameters: {'n_estimators': 300, 'learning_rate': 0.04770073143633031, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 140, 'subsample': 0.8961865009411224, 'colsample_bytree': 0.6777283578330802, 'reg_alpha': 12.55434515257999, 'reg_lambda': 74.71927407020951}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  58%|███████████████████████▏                | 116/200 [12:32<06:57,  4.97s/it]

[I 2026-05-25 17:28:50,996] Trial 517 finished with value: 0.9498024707671314 and parameters: {'n_estimators': 300, 'learning_rate': 0.04723503476047781, 'max_depth': 1, 'num_leaves': 10, 'min_child_samples': 131, 'subsample': 0.9917043987653216, 'colsample_bytree': 0.71479532733854, 'reg_alpha': 11.701679294292033, 'reg_lambda': 27.829327196312054}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  58%|███████████████████████▍                | 117/200 [12:35<06:00,  4.35s/it]

[I 2026-05-25 17:28:53,882] Trial 513 finished with value: 0.9501175675590563 and parameters: {'n_estimators': 300, 'learning_rate': 0.04964253509063296, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 143, 'subsample': 0.8464740657677106, 'colsample_bytree': 0.6834954405945851, 'reg_alpha': 11.935383881320822, 'reg_lambda': 71.04228089858802}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  59%|███████████████████████▌                | 118/200 [12:57<12:58,  9.50s/it]

[I 2026-05-25 17:29:15,421] Trial 515 finished with value: 0.9501225225606152 and parameters: {'n_estimators': 300, 'learning_rate': 0.04817578109613312, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 129, 'subsample': 0.8609916041963522, 'colsample_bytree': 0.7158290279590229, 'reg_alpha': 11.846450784929672, 'reg_lambda': 71.1579044968925}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  60%|███████████████████████▊                | 119/200 [12:58<09:30,  7.04s/it]

[I 2026-05-25 17:29:16,747] Trial 516 finished with value: 0.9501244056663809 and parameters: {'n_estimators': 300, 'learning_rate': 0.04936309164864215, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 50, 'subsample': 0.9795472990483087, 'colsample_bytree': 0.6421935976339366, 'reg_alpha': 12.392833710046848, 'reg_lambda': 29.76565695945305}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  60%|████████████████████████                | 120/200 [13:06<09:32,  7.15s/it]

[I 2026-05-25 17:29:24,141] Trial 530 pruned.

Best trial: 511. Best value: 0.950128:  60%|████████████████████████▏               | 121/200 [13:12<08:57,  6.81s/it]

[I 2026-05-25 17:29:30,142] Trial 519 finished with value: 0.9501240070740273 and parameters: {'n_estimators': 298, 'learning_rate': 0.04557499459991745, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 161, 'subsample': 0.8580882391789476, 'colsample_bytree': 0.6268527098206721, 'reg_alpha': 11.811430607493984, 'reg_lambda': 76.40137719475503}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  61%|████████████████████████▍               | 122/200 [13:22<10:10,  7.83s/it]

[I 2026-05-25 17:29:40,354] Trial 520 finished with value: 0.9501167665728183 and parameters: {'n_estimators': 300, 'learning_rate': 0.04702582162790108, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 49, 'subsample': 0.8814638152382134, 'colsample_bytree': 0.6290094439886368, 'reg_alpha': 10.511550040125002, 'reg_lambda': 32.21418532106584}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  62%|████████████████████████▌               | 123/200 [13:26<08:34,  6.69s/it]

[I 2026-05-25 17:29:44,373] Trial 522 finished with value: 0.950124946210621 and parameters: {'n_estimators': 299, 'learning_rate': 0.046456647958044536, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 131, 'subsample': 0.8602581550668108, 'colsample_bytree': 0.6416024727977253, 'reg_alpha': 11.985109716287724, 'reg_lambda': 28.852506389197345}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  62%|████████████████████████▊               | 124/200 [13:30<07:33,  5.96s/it]

[I 2026-05-25 17:29:48,649] Trial 521 finished with value: 0.9501036023330531 and parameters: {'n_estimators': 300, 'learning_rate': 0.04666326968946361, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 51, 'subsample': 0.8592888297842881, 'colsample_bytree': 0.6434088216259694, 'reg_alpha': 0.04559754896442012, 'reg_lambda': 32.30784092780723}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  62%|█████████████████████████               | 125/200 [13:32<05:55,  4.74s/it]

[I 2026-05-25 17:29:50,505] Trial 523 finished with value: 0.9501218335754571 and parameters: {'n_estimators': 300, 'learning_rate': 0.046734085221019794, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 129, 'subsample': 0.8563293045172106, 'colsample_bytree': 0.642861038107282, 'reg_alpha': 9.755855556837142, 'reg_lambda': 30.53636674176975}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  63%|█████████████████████████▏              | 126/200 [13:35<05:06,  4.15s/it]

[I 2026-05-25 17:29:53,285] Trial 524 finished with value: 0.9501249739353266 and parameters: {'n_estimators': 300, 'learning_rate': 0.04739388197825096, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 131, 'subsample': 0.8775262832745765, 'colsample_bytree': 0.6275461330592431, 'reg_alpha': 8.579148121218097, 'reg_lambda': 34.01417212219998}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  64%|█████████████████████████▍              | 127/200 [13:36<03:52,  3.19s/it]

[I 2026-05-25 17:29:54,258] Trial 525 finished with value: 0.9501185352959098 and parameters: {'n_estimators': 295, 'learning_rate': 0.04683803178287449, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 130, 'subsample': 0.8809274488507021, 'colsample_bytree': 0.680950264018271, 'reg_alpha': 8.345105327403271, 'reg_lambda': 30.922769209200297}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  64%|█████████████████████████▌              | 128/200 [13:38<03:40,  3.06s/it]

[I 2026-05-25 17:29:56,993] Trial 526 finished with value: 0.9500966201152444 and parameters: {'n_estimators': 295, 'learning_rate': 0.04621446084554495, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 130, 'subsample': 0.8818833861519049, 'colsample_bytree': 0.6844873407973896, 'reg_alpha': 9.247936889826219, 'reg_lambda': 29.513902035310085}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  64%|█████████████████████████▊              | 129/200 [13:53<07:52,  6.66s/it]

[I 2026-05-25 17:30:12,056] Trial 528 finished with value: 0.9501265304061896 and parameters: {'n_estimators': 294, 'learning_rate': 0.04476884180118738, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 164, 'subsample': 0.8822052537306279, 'colsample_bytree': 0.6957455815321267, 'reg_alpha': 8.238325820042927, 'reg_lambda': 30.181540559663283}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  65%|██████████████████████████              | 130/200 [13:54<05:33,  4.76s/it]

[I 2026-05-25 17:30:12,380] Trial 527 finished with value: 0.9501276632145654 and parameters: {'n_estimators': 300, 'learning_rate': 0.04604980381388762, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 157, 'subsample': 0.8824727552861789, 'colsample_bytree': 0.6951652798889797, 'reg_alpha': 8.02707509395731, 'reg_lambda': 35.638577086623954}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  66%|██████████████████████████▏             | 131/200 [14:15<11:02,  9.60s/it]

[I 2026-05-25 17:30:33,274] Trial 532 pruned.

Best trial: 511. Best value: 0.950128:  66%|██████████████████████████▍             | 132/200 [14:15<07:49,  6.90s/it]

[I 2026-05-25 17:30:33,895] Trial 529 finished with value: 0.9501214259958936 and parameters: {'n_estimators': 295, 'learning_rate': 0.045593630769507086, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 132, 'subsample': 0.8800504978614307, 'colsample_bytree': 0.6974863262702609, 'reg_alpha': 7.948695791790281, 'reg_lambda': 89.9286695694057}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  66%|██████████████████████████▌             | 133/200 [14:21<07:13,  6.46s/it]

[I 2026-05-25 17:30:39,305] Trial 531 finished with value: 0.9501125557629357 and parameters: {'n_estimators': 300, 'learning_rate': 0.04986553748352294, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 54, 'subsample': 0.9660523552224344, 'colsample_bytree': 0.6403937558313636, 'reg_alpha': 0.048290856971859204, 'reg_lambda': 98.71437183140925}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  67%|██████████████████████████▊             | 134/200 [14:39<11:05, 10.08s/it]

[I 2026-05-25 17:30:57,856] Trial 533 finished with value: 0.9500914669852657 and parameters: {'n_estimators': 300, 'learning_rate': 0.028021583265456892, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 166, 'subsample': 0.9504128909892312, 'colsample_bytree': 0.629612515970478, 'reg_alpha': 7.535810817867368, 'reg_lambda': 58.39682519894415}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 511. Best value: 0.950128:  68%|███████████████████████████             | 135/200 [14:43<08:46,  8.10s/it]

[I 2026-05-25 17:31:01,346] Trial 534 finished with value: 0.9501142165632819 and parameters: {'n_estimators': 295, 'learning_rate': 0.04904377820492285, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 50, 'subsample': 0.8602853369222827, 'colsample_bytree': 0.6385877135160651, 'reg_alpha': 22.849834772039035, 'reg_lambda': 31.82167349835576}. Best is trial 511 with value: 0.9501279251657385.

Best trial: 535. Best value: 0.950131:  68%|███████████████████████████▏            | 136/200 [14:45<06:49,  6.40s/it]

[I 2026-05-25 17:31:03,769] Trial 535 finished with value: 0.950131034246073 and parameters: {'n_estimators': 295, 'learning_rate': 0.04995445372537153, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 56, 'subsample': 0.9420928217811894, 'colsample_bytree': 0.6282200309387433, 'reg_alpha': 23.17062571921209, 'reg_lambda': 95.33997082002051}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  68%|███████████████████████████▍            | 137/200 [14:49<05:56,  5.67s/it]

[I 2026-05-25 17:31:07,718] Trial 536 finished with value: 0.9501136019935597 and parameters: {'n_estimators': 294, 'learning_rate': 0.0493720180846786, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 167, 'subsample': 0.9539320265675126, 'colsample_bytree': 0.6313010568013766, 'reg_alpha': 23.854765674025618, 'reg_lambda': 95.68777013543765}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  69%|███████████████████████████▌            | 138/200 [14:50<04:17,  4.16s/it]

[I 2026-05-25 17:31:08,366] Trial 538 finished with value: 0.9501217979217694 and parameters: {'n_estimators': 300, 'learning_rate': 0.04957098664974846, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 157, 'subsample': 0.860384277680732, 'colsample_bytree': 0.6292526204202874, 'reg_alpha': 7.205748171495469, 'reg_lambda': 94.49422562074702}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  70%|███████████████████████████▊            | 139/200 [14:52<03:46,  3.71s/it]

[I 2026-05-25 17:31:11,020] Trial 539 finished with value: 0.9501205218914992 and parameters: {'n_estimators': 300, 'learning_rate': 0.049053134296008515, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 55, 'subsample': 0.9771734243072926, 'colsample_bytree': 0.632729065262363, 'reg_alpha': 7.6119457852369585, 'reg_lambda': 99.9928085733196}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  70%|████████████████████████████            | 140/200 [14:56<03:42,  3.71s/it]

[I 2026-05-25 17:31:14,730] Trial 537 finished with value: 0.9501189504194645 and parameters: {'n_estimators': 295, 'learning_rate': 0.04889966303562888, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 54, 'subsample': 0.8599554880248321, 'colsample_bytree': 0.6301173990132926, 'reg_alpha': 8.25696622246286, 'reg_lambda': 28.11186752565846}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  70%|████████████████████████████▏           | 141/200 [15:03<04:34,  4.66s/it]

[I 2026-05-25 17:31:21,602] Trial 545 finished with value: 0.9498782924200757 and parameters: {'n_estimators': 68, 'learning_rate': 0.04964882382710135, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 167, 'subsample': 0.8576684006032564, 'colsample_bytree': 0.6313881564882531, 'reg_alpha': 7.2388537302663325, 'reg_lambda': 24.07077162399111}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  71%|████████████████████████████▍           | 142/200 [15:04<03:28,  3.59s/it]

[I 2026-05-25 17:31:22,703] Trial 540 finished with value: 0.9501115749855906 and parameters: {'n_estimators': 292, 'learning_rate': 0.04915757198923942, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 167, 'subsample': 0.9828191740477844, 'colsample_bytree': 0.631699147284239, 'reg_alpha': 7.42906925199805, 'reg_lambda': 54.09566177620644}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  72%|████████████████████████████▌           | 143/200 [15:14<05:09,  5.42s/it]

[I 2026-05-25 17:31:32,413] Trial 541 finished with value: 0.950114396312976 and parameters: {'n_estimators': 300, 'learning_rate': 0.048461991133270814, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 50, 'subsample': 0.8603069079842078, 'colsample_bytree': 0.6283637118912783, 'reg_alpha': 7.2719280225806, 'reg_lambda': 0.00246662433253711}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  72%|████████████████████████████▊           | 144/200 [15:30<08:03,  8.64s/it]

[I 2026-05-25 17:31:48,553] Trial 542 finished with value: 0.95012368721499 and parameters: {'n_estimators': 300, 'learning_rate': 0.04648091581239935, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 167, 'subsample': 0.9479885279760635, 'colsample_bytree': 0.7053500888234006, 'reg_alpha': 6.79787388356546, 'reg_lambda': 37.56378178690174}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  72%|█████████████████████████████           | 145/200 [15:31<05:47,  6.32s/it]

[I 2026-05-25 17:31:49,436] Trial 543 finished with value: 0.9501182367973637 and parameters: {'n_estimators': 300, 'learning_rate': 0.04990856626136128, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 166, 'subsample': 0.8604387389582755, 'colsample_bytree': 0.7083928581313351, 'reg_alpha': 6.989846776389398, 'reg_lambda': 52.52550023713565}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  73%|█████████████████████████████▏          | 146/200 [15:38<05:53,  6.55s/it]

[I 2026-05-25 17:31:56,543] Trial 544 finished with value: 0.9501159635449309 and parameters: {'n_estimators': 291, 'learning_rate': 0.04991508828894993, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 157, 'subsample': 0.8610743437519671, 'colsample_bytree': 0.7086592494186386, 'reg_alpha': 6.970074236067211, 'reg_lambda': 24.737455693285355}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  74%|█████████████████████████████▍          | 147/200 [16:04<10:54, 12.35s/it]

[I 2026-05-25 17:32:22,415] Trial 549 finished with value: 0.9501199251366484 and parameters: {'n_estimators': 289, 'learning_rate': 0.04913580022574342, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 160, 'subsample': 0.8864717742948974, 'colsample_bytree': 0.704323576065675, 'reg_alpha': 23.559158864746813, 'reg_lambda': 58.573236623368864}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  74%|█████████████████████████████▌          | 148/200 [16:06<07:55,  9.15s/it]

[I 2026-05-25 17:32:24,106] Trial 548 finished with value: 0.9501202955766214 and parameters: {'n_estimators': 290, 'learning_rate': 0.049700829149104064, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 161, 'subsample': 0.8572566043829264, 'colsample_bytree': 0.6240883757604598, 'reg_alpha': 25.19535825108852, 'reg_lambda': 60.888058806814186}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  74%|█████████████████████████████▊          | 149/200 [16:07<05:48,  6.83s/it]

[I 2026-05-25 17:32:25,544] Trial 546 finished with value: 0.9501042157233988 and parameters: {'n_estimators': 291, 'learning_rate': 0.04946657625146852, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 155, 'subsample': 0.8548858772969529, 'colsample_bytree': 0.9384886244932306, 'reg_alpha': 6.819766557557891, 'reg_lambda': 38.0523384027735}. Best is trial 535 with value: 0.950131034246073.
[I 2026-05-25 17:32:25,550] Trial 547 finished with value: 0.9501152098499663 and parameters: {'n_estimators': 291, 'learning_rate': 0.048381923233475066, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 160, 'subsample': 0.9790123375678186, 'colsample_bytree': 0.6248840645090218, 'reg_alpha': 23.422737046505926, 'reg_lambda': 61.66223578448085}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  76%|██████████████████████████████▏         | 151/200 [16:11<03:46,  4.61s/it]

[I 2026-05-25 17:32:29,577] Trial 550 finished with value: 0.9501143042451767 and parameters: {'n_estimators': 290, 'learning_rate': 0.049451546716533096, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 43, 'subsample': 0.9365429001798208, 'colsample_bytree': 0.6080948215459806, 'reg_alpha': 22.64257136468827, 'reg_lambda': 59.15254109334614}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  76%|██████████████████████████████▍         | 152/200 [16:13<03:09,  3.95s/it]

[I 2026-05-25 17:32:31,521] Trial 551 finished with value: 0.9501192719703931 and parameters: {'n_estimators': 289, 'learning_rate': 0.04981464061342856, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 44, 'subsample': 0.9676577949452396, 'colsample_bytree': 0.7034477082812346, 'reg_alpha': 20.46832192554084, 'reg_lambda': 62.3297663022656}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  76%|██████████████████████████████▌         | 153/200 [16:18<03:20,  4.27s/it]

[I 2026-05-25 17:32:36,700] Trial 552 finished with value: 0.9501218303600044 and parameters: {'n_estimators': 289, 'learning_rate': 0.04558082224024096, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 174, 'subsample': 0.9481064719552591, 'colsample_bytree': 0.6951567156588794, 'reg_alpha': 13.358562689721362, 'reg_lambda': 65.33747442409717}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  77%|██████████████████████████████▊         | 154/200 [16:22<03:09,  4.12s/it]

[I 2026-05-25 17:32:40,393] Trial 553 finished with value: 0.9501217613647333 and parameters: {'n_estimators': 290, 'learning_rate': 0.04578712350364924, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 157, 'subsample': 0.944656453371703, 'colsample_bytree': 0.6969830473278634, 'reg_alpha': 24.37717539289985, 'reg_lambda': 0.0023018397114726295}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  78%|███████████████████████████████         | 155/200 [16:38<05:39,  7.53s/it]

[I 2026-05-25 17:32:56,715] Trial 554 finished with value: 0.9501188772112821 and parameters: {'n_estimators': 289, 'learning_rate': 0.04636988939021331, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 157, 'subsample': 0.936127175080955, 'colsample_bytree': 0.6984328159887477, 'reg_alpha': 22.863536301751825, 'reg_lambda': 58.132035968796735}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  78%|███████████████████████████████▏        | 156/200 [16:48<05:58,  8.14s/it]

[I 2026-05-25 17:33:06,385] Trial 555 finished with value: 0.9501193325389646 and parameters: {'n_estimators': 290, 'learning_rate': 0.04582647685564862, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 163, 'subsample': 0.9938655190990483, 'colsample_bytree': 0.7011109204178513, 'reg_alpha': 22.54862408007114, 'reg_lambda': 60.382227549911974}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  78%|███████████████████████████████▍        | 157/200 [16:48<04:11,  5.85s/it]

[I 2026-05-25 17:33:06,589] Trial 556 finished with value: 0.9501107285028795 and parameters: {'n_estimators': 291, 'learning_rate': 0.04544443651427793, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 174, 'subsample': 0.9718625793185585, 'colsample_bytree': 0.7046045959818916, 'reg_alpha': 23.504661178840603, 'reg_lambda': 62.17957190103233}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  79%|███████████████████████████████▌        | 158/200 [16:55<04:18,  6.16s/it]

[I 2026-05-25 17:33:13,537] Trial 557 finished with value: 0.9501161671116669 and parameters: {'n_estimators': 289, 'learning_rate': 0.045785641077779465, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 174, 'subsample': 0.8842477503558187, 'colsample_bytree': 0.7065561985579283, 'reg_alpha': 23.046768644336908, 'reg_lambda': 60.45562176231161}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  80%|███████████████████████████████▊        | 159/200 [17:22<08:23, 12.29s/it]

[I 2026-05-25 17:33:40,497] Trial 558 finished with value: 0.9501283781847116 and parameters: {'n_estimators': 291, 'learning_rate': 0.046176912249588135, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 173, 'subsample': 0.9422002911631251, 'colsample_bytree': 0.6991657826473748, 'reg_alpha': 12.990682495819696, 'reg_lambda': 38.9983800538028}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  80%|████████████████████████████████        | 160/200 [17:23<05:55,  8.88s/it]

[I 2026-05-25 17:33:41,270] Trial 559 finished with value: 0.950126670457928 and parameters: {'n_estimators': 291, 'learning_rate': 0.04568096448004861, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 161, 'subsample': 0.9771281341855182, 'colsample_bytree': 0.700467599674773, 'reg_alpha': 13.735165293220982, 'reg_lambda': 39.0677664522439}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  80%|████████████████████████████████▏       | 161/200 [17:25<04:32,  6.99s/it]

[I 2026-05-25 17:33:43,800] Trial 561 finished with value: 0.9501253043598641 and parameters: {'n_estimators': 287, 'learning_rate': 0.04580548899235521, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 172, 'subsample': 0.9625481861807083, 'colsample_bytree': 0.6976762203744994, 'reg_alpha': 13.331280886435579, 'reg_lambda': 41.77092869043372}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  81%|████████████████████████████████▍       | 162/200 [17:26<03:10,  5.00s/it]

[I 2026-05-25 17:33:44,104] Trial 560 finished with value: 0.9501267935953889 and parameters: {'n_estimators': 287, 'learning_rate': 0.046527793468600864, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 177, 'subsample': 0.9742384239031818, 'colsample_bytree': 0.705008433982943, 'reg_alpha': 12.893392794942534, 'reg_lambda': 40.778332541751865}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  82%|████████████████████████████████▌       | 163/200 [17:29<02:50,  4.61s/it]

[I 2026-05-25 17:33:47,825] Trial 562 finished with value: 0.9501254695365985 and parameters: {'n_estimators': 294, 'learning_rate': 0.04568165354324828, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 175, 'subsample': 0.9421243312812289, 'colsample_bytree': 0.7000246391102196, 'reg_alpha': 13.358128041371907, 'reg_lambda': 38.653968935528795}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  82%|████████████████████████████████▊       | 164/200 [17:31<02:19,  3.87s/it]

[I 2026-05-25 17:33:49,971] Trial 563 finished with value: 0.9501196061044386 and parameters: {'n_estimators': 295, 'learning_rate': 0.04568448599788252, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 173, 'subsample': 0.9393395920555216, 'colsample_bytree': 0.6993309357380114, 'reg_alpha': 13.252979549629233, 'reg_lambda': 40.19011073186245}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  82%|█████████████████████████████████       | 165/200 [17:35<02:11,  3.75s/it]

[I 2026-05-25 17:33:53,432] Trial 564 finished with value: 0.9501160070965533 and parameters: {'n_estimators': 295, 'learning_rate': 0.04531513500512641, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 172, 'subsample': 0.9976121044456374, 'colsample_bytree': 0.7165870686182112, 'reg_alpha': 13.21293379396599, 'reg_lambda': 45.348238636236175}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  83%|█████████████████████████████████▏      | 166/200 [17:37<01:51,  3.29s/it]

[I 2026-05-25 17:33:55,641] Trial 565 finished with value: 0.9501047310226156 and parameters: {'n_estimators': 294, 'learning_rate': 0.04520938493256846, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 161, 'subsample': 0.8753561875838319, 'colsample_bytree': 0.7185667822207492, 'reg_alpha': 1.9354264562761934e-05, 'reg_lambda': 39.51043550244711}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  84%|█████████████████████████████████▍      | 167/200 [17:59<04:54,  8.93s/it]

[I 2026-05-25 17:34:17,725] Trial 566 finished with value: 0.950118932937348 and parameters: {'n_estimators': 296, 'learning_rate': 0.045061902547309504, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 171, 'subsample': 0.9624662177056005, 'colsample_bytree': 0.7204673015997505, 'reg_alpha': 3.7183158374181455, 'reg_lambda': 39.964340406604755}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  84%|█████████████████████████████████▌      | 168/200 [18:04<04:04,  7.64s/it]

[I 2026-05-25 17:34:22,374] Trial 568 finished with value: 0.9501134410461589 and parameters: {'n_estimators': 295, 'learning_rate': 0.044563253582307116, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 172, 'subsample': 0.9573445441156853, 'colsample_bytree': 0.7141454501026302, 'reg_alpha': 13.937724628449264, 'reg_lambda': 46.06783278659283}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  84%|█████████████████████████████████▊      | 169/200 [18:09<03:37,  7.01s/it]

[I 2026-05-25 17:34:27,897] Trial 567 finished with value: 0.9501195946360639 and parameters: {'n_estimators': 295, 'learning_rate': 0.044775562438843244, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 174, 'subsample': 0.9641890076756823, 'colsample_bytree': 0.7184783308635295, 'reg_alpha': 13.127821046436402, 'reg_lambda': 37.35817519498354}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  85%|██████████████████████████████████      | 170/200 [18:18<03:43,  7.44s/it]

[I 2026-05-25 17:34:36,358] Trial 569 finished with value: 0.9501164668561142 and parameters: {'n_estimators': 300, 'learning_rate': 0.04433301656540791, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 147, 'subsample': 0.9722889906194679, 'colsample_bytree': 0.7190580899520569, 'reg_alpha': 13.073620847031687, 'reg_lambda': 41.422899016204674}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  86%|██████████████████████████████████▏     | 171/200 [18:34<04:49,  9.98s/it]

[I 2026-05-25 17:34:52,240] Trial 571 finished with value: 0.9501060806885933 and parameters: {'n_estimators': 286, 'learning_rate': 0.044057962600434264, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 171, 'subsample': 0.9733010308299872, 'colsample_bytree': 0.6890029977143016, 'reg_alpha': 13.573850178893258, 'reg_lambda': 36.76203238048898}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  86%|██████████████████████████████████▍     | 172/200 [18:42<04:26,  9.52s/it]

[I 2026-05-25 17:35:00,697] Trial 572 finished with value: 0.9501239436513066 and parameters: {'n_estimators': 286, 'learning_rate': 0.04429947020256852, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 173, 'subsample': 0.9629009850230396, 'colsample_bytree': 0.6978426201139245, 'reg_alpha': 13.711635612335852, 'reg_lambda': 36.79972437306187}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  86%|██████████████████████████████████▌     | 173/200 [18:42<03:02,  6.76s/it]

[I 2026-05-25 17:35:00,991] Trial 570 finished with value: 0.9501231558699557 and parameters: {'n_estimators': 295, 'learning_rate': 0.043794312883543574, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 173, 'subsample': 0.9554294234593168, 'colsample_bytree': 0.6890257913232891, 'reg_alpha': 13.810650755819706, 'reg_lambda': 37.656436267557815}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  87%|██████████████████████████████████▊     | 174/200 [18:46<02:31,  5.83s/it]

[I 2026-05-25 17:35:04,670] Trial 573 finished with value: 0.9501256217703643 and parameters: {'n_estimators': 285, 'learning_rate': 0.044027467833840706, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 171, 'subsample': 0.9586434726560723, 'colsample_bytree': 0.7066630033498289, 'reg_alpha': 14.895094042088353, 'reg_lambda': 25.742053395090274}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  88%|███████████████████████████████████     | 175/200 [18:48<01:54,  4.56s/it]

[I 2026-05-25 17:35:06,296] Trial 576 finished with value: 0.9501108398596877 and parameters: {'n_estimators': 285, 'learning_rate': 0.044123245394740475, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 183, 'subsample': 0.9579621384719209, 'colsample_bytree': 0.7106848672103627, 'reg_alpha': 15.24526342757611, 'reg_lambda': 22.65749569326064}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  88%|███████████████████████████████████▏    | 176/200 [18:49<01:22,  3.45s/it]

[I 2026-05-25 17:35:07,152] Trial 574 finished with value: 0.9501206575037869 and parameters: {'n_estimators': 285, 'learning_rate': 0.044056236794059664, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 171, 'subsample': 0.9579074922384261, 'colsample_bytree': 0.7114513563867404, 'reg_alpha': 13.844946622769953, 'reg_lambda': 25.789453726068377}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  88%|███████████████████████████████████▍    | 177/200 [18:50<01:04,  2.81s/it]

[I 2026-05-25 17:35:08,458] Trial 575 finished with value: 0.9501239708257583 and parameters: {'n_estimators': 286, 'learning_rate': 0.04450581050248438, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 179, 'subsample': 0.9604624112515356, 'colsample_bytree': 0.7165892583507056, 'reg_alpha': 14.526110010428487, 'reg_lambda': 5.3994117843271516e-05}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  89%|███████████████████████████████████▌    | 178/200 [19:00<01:48,  4.91s/it]

[I 2026-05-25 17:35:18,289] Trial 577 finished with value: 0.9501170128988619 and parameters: {'n_estimators': 285, 'learning_rate': 0.04381980198676519, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 177, 'subsample': 0.9593224677523526, 'colsample_bytree': 0.7233379929370009, 'reg_alpha': 13.843995604576813, 'reg_lambda': 26.448143065309882}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  90%|███████████████████████████████████▊    | 179/200 [19:20<03:22,  9.65s/it]

[I 2026-05-25 17:35:39,001] Trial 579 finished with value: 0.9501197756754969 and parameters: {'n_estimators': 286, 'learning_rate': 0.0436874741478507, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 180, 'subsample': 0.9857055145427494, 'colsample_bytree': 0.7109004879181596, 'reg_alpha': 32.45649758540069, 'reg_lambda': 21.969551323819335}. Best is trial 535 with value: 0.950131034246073.
[I 2026-05-25 17:35:39,031] Trial 578 finished with value: 0.9501232217122038 and parameters: {'n_estimators': 285, 'learning_rate': 0.04380372875050051, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 179, 'subsample': 0.9765989323680238, 'colsample_bytree': 0.708518934090735, 'reg_alpha': 14.495640553160657, 'reg_lambda': 36.384386803665485}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  90%|████████████████████████████████████▏   | 181/200 [19:28<02:10,  6.86s/it]

[I 2026-05-25 17:35:46,192] Trial 580 finished with value: 0.9501209045360504 and parameters: {'n_estimators': 287, 'learning_rate': 0.04358851826543809, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 169, 'subsample': 0.9754141125432324, 'colsample_bytree': 0.7066033348784345, 'reg_alpha': 17.704366217776062, 'reg_lambda': 19.75925012690848}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  91%|████████████████████████████████████▍   | 182/200 [19:35<02:03,  6.87s/it]

[I 2026-05-25 17:35:53,090] Trial 581 finished with value: 0.9501214683670117 and parameters: {'n_estimators': 285, 'learning_rate': 0.04361677255898673, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 178, 'subsample': 0.9801661327742065, 'colsample_bytree': 0.7070767659904339, 'reg_alpha': 17.817787861032173, 'reg_lambda': 22.693638106094628}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  92%|████████████████████████████████████▌   | 183/200 [19:44<02:07,  7.49s/it]

[I 2026-05-25 17:36:02,349] Trial 585 finished with value: 0.9501016996030419 and parameters: {'n_estimators': 190, 'learning_rate': 0.04758697909860404, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 178, 'subsample': 0.9828099760492094, 'colsample_bytree': 0.7063913991053129, 'reg_alpha': 31.970911974485343, 'reg_lambda': 23.072438397308115}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  92%|████████████████████████████████████▊   | 184/200 [19:55<02:15,  8.48s/it]

[I 2026-05-25 17:36:13,474] Trial 582 finished with value: 0.950057715420644 and parameters: {'n_estimators': 286, 'learning_rate': 0.021900121054908944, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 177, 'subsample': 0.9828205808835877, 'colsample_bytree': 0.7066171311014287, 'reg_alpha': 30.467362553251032, 'reg_lambda': 23.180050941980483}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  92%|█████████████████████████████████████   | 185/200 [19:57<01:41,  6.74s/it]

[I 2026-05-25 17:36:15,731] Trial 584 finished with value: 0.9501206239726023 and parameters: {'n_estimators': 284, 'learning_rate': 0.04692348264263931, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 176, 'subsample': 0.9721425857579084, 'colsample_bytree': 0.696748424896158, 'reg_alpha': 31.747508129893646, 'reg_lambda': 23.30248628596865}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  93%|█████████████████████████████████████▏  | 186/200 [20:04<01:35,  6.80s/it]

[I 2026-05-25 17:36:22,687] Trial 583 finished with value: 0.9500692069723575 and parameters: {'n_estimators': 285, 'learning_rate': 0.02354898992844665, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 181, 'subsample': 0.9709698788298415, 'colsample_bytree': 0.6976438508003554, 'reg_alpha': 30.188488551826552, 'reg_lambda': 23.114422515399216}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  94%|█████████████████████████████████████▍  | 187/200 [20:05<01:04,  4.99s/it]

[I 2026-05-25 17:36:23,238] Trial 586 finished with value: 0.9501101886509822 and parameters: {'n_estimators': 285, 'learning_rate': 0.04766412830275457, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 179, 'subsample': 0.9844940846840684, 'colsample_bytree': 0.6960421098864328, 'reg_alpha': 0.8074795249847369, 'reg_lambda': 24.933036559399397}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  94%|█████████████████████████████████████▌  | 188/200 [20:11<01:05,  5.49s/it]

[I 2026-05-25 17:36:29,943] Trial 587 finished with value: 0.9500716772819926 and parameters: {'n_estimators': 285, 'learning_rate': 0.022989268609027082, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 178, 'subsample': 0.9867501658110188, 'colsample_bytree': 0.6966002126428188, 'reg_alpha': 19.73268597303078, 'reg_lambda': 23.596861829416145}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  94%|█████████████████████████████████████▊  | 189/200 [20:15<00:54,  4.95s/it]

[I 2026-05-25 17:36:33,585] Trial 589 finished with value: 0.9501225403180502 and parameters: {'n_estimators': 278, 'learning_rate': 0.04725794712055189, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 179, 'subsample': 0.9870739583637992, 'colsample_bytree': 0.7071326839987211, 'reg_alpha': 33.09676330517962, 'reg_lambda': 0.00011552972272008325}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  95%|██████████████████████████████████████  | 190/200 [20:21<00:53,  5.36s/it]

[I 2026-05-25 17:36:39,939] Trial 588 finished with value: 0.9500621840783439 and parameters: {'n_estimators': 277, 'learning_rate': 0.022235301996217555, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 189, 'subsample': 0.9842666962857641, 'colsample_bytree': 0.696127635261787, 'reg_alpha': 29.29541033738972, 'reg_lambda': 0.0013692862225993232}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  96%|██████████████████████████████████████▏ | 191/200 [20:32<01:02,  6.92s/it]

[I 2026-05-25 17:36:50,552] Trial 591 finished with value: 0.950120669870059 and parameters: {'n_estimators': 273, 'learning_rate': 0.04711431714363572, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 187, 'subsample': 0.9814930640229295, 'colsample_bytree': 0.696551299226695, 'reg_alpha': 19.649888585590844, 'reg_lambda': 19.29351399034243}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  96%|██████████████████████████████████████▍ | 192/200 [20:32<00:39,  4.99s/it]

[I 2026-05-25 17:36:50,978] Trial 590 finished with value: 0.9501152804709164 and parameters: {'n_estimators': 278, 'learning_rate': 0.047176333323117076, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 182, 'subsample': 0.9792693694028116, 'colsample_bytree': 0.6965682775653963, 'reg_alpha': 19.18043497086027, 'reg_lambda': 3.513782842116634e-05}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  96%|██████████████████████████████████████▌ | 193/200 [20:36<00:32,  4.67s/it]

[I 2026-05-25 17:36:54,918] Trial 592 finished with value: 0.9501152195541621 and parameters: {'n_estimators': 276, 'learning_rate': 0.04719284263770425, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 187, 'subsample': 0.9696401551733503, 'colsample_bytree': 0.7011850848940049, 'reg_alpha': 22.462866424665435, 'reg_lambda': 23.586540542193152}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  97%|██████████████████████████████████████▊ | 194/200 [20:41<00:28,  4.75s/it]

[I 2026-05-25 17:36:59,862] Trial 593 finished with value: 0.9501200933994755 and parameters: {'n_estimators': 277, 'learning_rate': 0.045970216398685634, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 183, 'subsample': 0.9691194833227119, 'colsample_bytree': 0.6918775340447102, 'reg_alpha': 19.462807202884797, 'reg_lambda': 25.850996481282753}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  98%|███████████████████████████████████████ | 195/200 [20:47<00:25,  5.07s/it]

[I 2026-05-25 17:37:05,682] Trial 594 finished with value: 0.9501189123342492 and parameters: {'n_estimators': 276, 'learning_rate': 0.046908679452920696, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 186, 'subsample': 0.9479949607918211, 'colsample_bytree': 0.6969299099093845, 'reg_alpha': 20.367187728361504, 'reg_lambda': 0.004011180653159255}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  98%|███████████████████████████████████████▏| 196/200 [20:50<00:18,  4.51s/it]

[I 2026-05-25 17:37:08,871] Trial 595 finished with value: 0.9501209467407641 and parameters: {'n_estimators': 274, 'learning_rate': 0.04732245883609619, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 186, 'subsample': 0.967801596751241, 'colsample_bytree': 0.6953605223944411, 'reg_alpha': 19.54768762090807, 'reg_lambda': 0.004037449104427741}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  98%|███████████████████████████████████████▍| 197/200 [20:52<00:11,  3.72s/it]

[I 2026-05-25 17:37:10,757] Trial 596 finished with value: 0.9501254766249131 and parameters: {'n_estimators': 278, 'learning_rate': 0.046555514464615984, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 182, 'subsample': 0.9432191564927672, 'colsample_bytree': 0.697525468355304, 'reg_alpha': 21.410615882582412, 'reg_lambda': 0.0009087781547661486}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131:  99%|███████████████████████████████████████▌| 198/200 [20:53<00:05,  2.93s/it]

[I 2026-05-25 17:37:11,857] Trial 598 finished with value: 0.9501182388857213 and parameters: {'n_estimators': 274, 'learning_rate': 0.04760248011313686, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 189, 'subsample': 0.9437070288659243, 'colsample_bytree': 0.6952017146238905, 'reg_alpha': 19.8729414903485, 'reg_lambda': 30.906654287034915}. Best is trial 535 with value: 0.950131034246073.

Best trial: 535. Best value: 0.950131: 100%|████████████████████████████████████████| 200/200 [20:54<00:00,  6.27s/it]

[I 2026-05-25 17:37:12,824] Trial 597 finished with value: 0.9501147387330148 and parameters: {'n_estimators': 275, 'learning_rate': 0.047309941803596725, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 166, 'subsample': 0.9657079572527418, 'colsample_bytree': 0.6959679310924869, 'reg_alpha': 18.501810904114123, 'reg_lambda': 0.00011024203601341157}. Best is trial 535 with value: 0.950131034246073.
[I 2026-05-25 17:37:12,962] Trial 599 finished with value: 0.950125978671663 and parameters: {'n_estimators': 276, 'learning_rate': 0.04707590311762272, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 188, 'subsample': 0.9427697203272083, 'colsample_bytree': 0.7027180140408709, 'reg_alpha': 18.8598099478477, 'reg_lambda': 17.42449716243865}. Best is trial 535 with value: 0.950131034246073.

In [31]:
stacking_lgbm = LGBMClassifier(**study.best_params).fit(X_train, y_train.PitNextLap)

[LightGBM] [Info] Number of positive: 87381, number of negative: 351759
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013048 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5621
[LightGBM] [Info] Number of data points in the train set: 439140, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198982 -> initscore=-1.392668
[LightGBM] [Info] Start training from score -1.392668

# Submission

In [32]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [33]:
submission['PitNextLap'] = stacking_lgbm.predict_proba(X_test)[:, 1]

In [34]:
submission.to_csv('../data/submission/submission.csv', index=False)

In [35]:
X_train.columns

Index(['lgbm_proba', 'cat_proba', 'xgb_proba', 'hist_proba', 'lg_proba',
       'pca_knn_proba', 'ridge_logit', 'truncatedsvd_linear_svc_logit',
       'truncatedsvd_ridge_logit', 'sgdclassifier_proba',
       'truncatedsvd_lgbm_proba', 'truncatedsvd_knn_proba',
       'truncatedsvd_nystroem_knn_proba', 'truncatedsvd_rbfsampler_knn_proba',
       'truncatedsvd_logistic_regression_proba',
       'truncatedsvd_nystroem_logistic_regression_proba',
       'truncatedsvd_nystroem_sgdclassifier_proba',
       'truncatedsvd_rbfsampler_logistic_regression_proba',
       'truncatedsvd_rbfsampler_sgdclassifier_proba',
       'voting_lgbm_and_cat_and_xgb_and_hist_proba',
       'voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier',
       'voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba',
       'stacking_voting_lgbm_and_cat_and_xgb_and_hist_proba_and_voting_and_lg_and_ridge_and_truncatedsvd_ridge_and_sgdclassifier_and_truncatedsvd_logistic_regression_and_truncatedsvd_nystroem_logistic_regression_and_truncatedsvd_nystroem_sgdclassifier_and_truncatedsvd_rbfsampler_logistic_regression_and_truncatedsvd_rbfsampler_sgdclassifier_and_voting_truncatedsvd_nytroem_knn_and_truncated_rbfsampler_knn_and_truncatedsvd_knn_and_pca_knn_proba_and_truncatedsvd_linear_svc_logit'],
      dtype='str')